### ISSUE TITLE
[BUG] python -m mlflow.server.auth db upgrade fails with PostgreSQL

### ISSUE THREAD

**Issue by hoangelos** [mlflow/mlflow#10052]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.7.1
- Tracking server: 2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
root@963789eb8270:/app# uname -a
Linux 963789eb8270 6.5.5-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 16:14:15 UTC 2023 aarch64 GNU/Linux

- **Python version**:
root@963789eb8270:/app# python --version
Python 3.10.13

- **yarn version, if running the dev UI**:
N/A

### Describe the problem

I want to use the basic-auth from a PostgreSQL database.  I add in a custom basic_auth.ini and set the MLFLOW_AUTH_CONFIG_PATH to the location of the file.  It is trying to create the database tables needs and fails.

root@5fff7fac63dd:/app# mlflow server --app-name basic-auth --dev
[2023-10-20 19:41:18 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 4
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: mlflow.server.auth:create_app()
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffa2afc700>
  on_reload: <function OnReload.on_reload at 0xffffa2afc820>
  when_ready: <function WhenReady.when_ready at 0xffffa2afc940>
  pre_fork: <function Prefork.pre_fork at 0xffffa2afca60>
  post_fork: <function Postfork.post_fork at 0xffffa2afcb80>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffa2afcca0>
  worker_int: <function WorkerInt.worker_int at 0xffffa2afcdc0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffa2afcee0>
  pre_exec: <function PreExec.pre_exec at 0xffffa2afd000>
  pre_request: <function PreRequest.pre_request at 0xffffa2afd120>
  post_request: <function PostRequest.post_request at 0xffffa2afd1b0>
  child_exit: <function ChildExit.child_exit at 0xffffa2afd2d0>
  worker_exit: <function WorkerExit.worker_exit at 0xffffa2afd3f0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffa2afd510>
  on_exit: <function OnExit.on_exit at 0xffffa2afd630>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffa2afd750>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-10-20 19:41:18 +0000] [7] [INFO] Starting gunicorn 21.2.0
[2023-10-20 19:41:18 +0000] [7] [DEBUG] Arbiter booted
[2023-10-20 19:41:18 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2023-10-20 19:41:18 +0000] [7] [INFO] Using worker: sync
[2023-10-20 19:41:18 +0000] [8] [INFO] Booting worker with pid: 8
[2023-10-20 19:41:18 +0000] [9] [INFO] Booting worker with pid: 9
[2023-10-20 19:41:18 +0000] [11] [INFO] Booting worker with pid: 11
[2023-10-20 19:41:18 +0000] [13] [INFO] Booting worker with pid: 13
[2023-10-20 19:41:18 +0000] [7] [DEBUG] 4 workers
2023/10/20 19:41:19 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/20 19:41:19 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/20 19:41:19 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/20 19:41:19 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[2023-10-20 19:41:22 +0000] [7] [ERROR] Worker (pid:8) exited with code 3
[2023-10-20 19:41:22 +0000] [7] [ERROR] Worker (pid:9) was sent SIGTERM!
[2023-10-20 19:41:22 +0000] [7] [ERROR] Worker (pid:13) was sent SIGTERM!
[2023-10-20 19:41:22 +0000] [7] [ERROR] Worker (pid:11) was sent SIGTERM!
[2023-10-20 19:41:22 +0000] [7] [ERROR] Shutting down: Master
[2023-10-20 19:41:22 +0000] [7] [ERROR] Reason: Worker failed to boot.
Running the mlflow server failed. Please see the logs above for details.

Then I try to use the mlflow.server.auth db upgrade to create the needed tables, but it fails too.

### Tracking information

```shell
python -m mlflow.server.auth db upgrade --url postgresql+psycopg2://foo:bar@db.secret-server.com:5432/MLFlow?sslmode=require

```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 244, in _catch_revision_errors
    yield
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 454, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 796, in iterate_revisions
    revisions, heads = fn(
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 1448, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 524, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 524, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 549, in get_revisions
    return tuple(
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 550, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 621, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '7f2a7d5fae7d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/auth/__main__.py", line 4, in <module>
    commands()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/auth/db/cli.py", line 17, in upgrade
    utils.migrate(engine, revision)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/auth/db/utils.py", line 27, in migrate
    upgrade(alembic_cfg, revision)
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 399, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/auth/db/migrations/env.py", line 76, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/auth/db/migrations/env.py", line 70, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 612, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 388, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 442, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 276, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '7f2a7d5fae7d'

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by barrywhart** [comment]
I think you have to create a different database. IIUC, Alembic doesn't support multiple schemas in one database.

I'm working on deploying this to our instance, and I'm creating a different database, passing a different connection URI, etc. Still a work in progress, but I was seeing very similar Alembic errors before I got this straightened out.

**Comment by hoangelos** [comment]
@barrywhart this was exactly because I was putting the schemas together.  I had suspicions that was it.  However, there's still a bug in here somewhere with multiple workers.  One eventually is able to do the update.  But everyone crashes.  Once I restart everything is perfect.

`[2023-10-21 00:03:11 +0000] [8] [INFO] Starting gunicorn 21.2.0
[2023-10-21 00:03:11 +0000] [8] [DEBUG] Arbiter booted
[2023-10-21 00:03:11 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-10-21 00:03:11 +0000] [8] [INFO] Using worker: sync
[2023-10-21 00:03:11 +0000] [9] [INFO] Booting worker with pid: 9
[2023-10-21 00:03:11 +0000] [11] [INFO] Booting worker with pid: 11
[2023-10-21 00:03:11 +0000] [13] [INFO] Booting worker with pid: 13
[2023-10-21 00:03:11 +0000] [14] [INFO] Booting worker with pid: 14
[2023-10-21 00:03:11 +0000] [8] [DEBUG] 4 workers
2023/10/21 00:03:12 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/21 00:03:12 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/21 00:03:12 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
2023/10/21 00:03:12 WARNING mlflow.server.auth: This feature is still experimental and may change in a future release without warning
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 8606fa83a998, initial_migration
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[2023-10-21 00:03:15 +0000] [8] [ERROR] Worker (pid:11) exited with code 3
[2023-10-21 00:03:15 +0000] [8] [ERROR] Worker (pid:13) was sent SIGTERM!
[2023-10-21 00:03:15 +0000] [8] [ERROR] Worker (pid:14) was sent SIGTERM!
[2023-10-21 00:03:16 +0000] [8] [ERROR] Shutting down: Master
[2023-10-21 00:03:16 +0000] [8] [ERROR] Reason: Worker failed to boot.
Running the mlflow server failed. Please see the logs above for details.`

**Comment by barrywhart** [comment]
I'll reach that point in the next week or two. My intuition is that schema installation/upgrades should be a separate batch process, rather than something automatically applied at worker startup, otherwise there may be a race condition when multiple workers try to apply the schema upgrade(s) simultaneously. Not sure if the current MLflow release supports that.

**Comment by BenWilson2** [comment]
From what we've seen with people trying to run the auth setup from the MLflow tracking server (as confirmed by your exception, which is from alembic attempting to process the migration version update https://github.com/mlflow/mlflow/blob/master/mlflow/store/db_migrations/versions/7f2a7d5fae7d_add_datasets_inputs_input_tags_tables.py that is reserved solely from the MLflow tracking server), the solution seems to be to define a separate DB in order to isolate the auth and tracking server processes. 

@hoangelos can you attempt to isolate the table creation to another DB instance?

**Comment by barrywhart** [comment]
Having two databases is working well for me. One Postgres server with two separate databases. It's a bit of a juggle, but it's fine.

It may be helpful for future users of this feature to provide example scripts for initial database creation as well as schema upgrades.

**Comment by hoangelos** [comment]
I agree it’s working now.  The documentation needs to make it more clear for with to work a separate database is needed. 

I think if we run this as a container we’d probably want an init container that calls to upgrade the databases manually for each in case we role out a new version with migrations to either.

**Comment by roshan3133** [comment]
for me also issue fixed with 2 deferent database
