### ISSUE TITLE
`mlflow.tensorflow.log_model` crashed with "KeyError: 'experiment_id'"

### ISSUE THREAD

**Issue by sfo** [mlflow/mlflow#10194]
The follwing error occurs when logging a Keras model to a local tracking uri:
```
Successfully registered model '2f34a0d1ead548f4acc5d3c395598f30'.
Traceback (most recent call last):
  File "[...]/modelling/models/mixture_density_network.py", line 238, in fit
    history = model.fit(
  File "[...]/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "[...]/modelling/callbacks.py", line 52, in on_train_end
    mlflow.tensorflow.log_model(
  File "[...]/lib/python3.10/site-packages/mlflow/tensorflow/__init__.py", line 207, in log_model
    return Model.log(
  File "[...]/lib/python3.10/site-packages/mlflow/models/model.py", line 590, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "[...]/lib/python3.10/site-packages/mlflow/tracking/_model_registry/fluent.py", line 105, in _register_model
    source = RunsArtifactRepository.get_underlying_uri(model_uri)
  File "[...]/lib/python3.10/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 39, in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
  File "[...]/lib/python3.10/site-packages/mlflow/tracking/artifact_utils.py", line 47, in get_artifact_uri
    run = store.get_run(run_id)
  File "[...]/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 660, in get_run
    run_info = self._get_run_info(run_id)
  File "[...]/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 687, in _get_run_info
    run_info = self._get_run_info_from_dir(run_dir)
  File "[...]/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 696, in _get_run_info_from_dir
    return _read_persisted_run_info_dict(meta)
  File "[...]/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 142, in _read_persisted_run_info_dict
    if isinstance(dict_copy["experiment_id"], int):
KeyError: 'experiment_id'
```
After some analysis, I found that the code tries to read the experiment id from a `meta.yaml` file. However, the file is not read from the experiment's path at `mlflow/<id>` but rather from `mlflow/models`. There, the run directory contains a `meta.yaml` file, but it's content differs from those located in the experiment's subdirectories, a. o. missing the `experiment_id` key.

The problem is caused by this call to `_get_active_experiments`, where the `full_path` parameter is set to `True`:
https://github.com/mlflow/mlflow/blob/feac3cb6d716c2db5cde08d3addfe4704f4704e9/mlflow/store/tracking/file_store.py#L581

However, in `_get_active_experiments` the condition checks whether the full path equals "models", which it of course does not.
https://github.com/mlflow/mlflow/blob/feac3cb6d716c2db5cde08d3addfe4704f4704e9/mlflow/store/tracking/file_store.py#L258-L265

Consequently, the "models" directory is included in the list of experiments, causing the error mentioned above.

---
MWE:
```python
from mlflow.store.tracking.file_store import FileStore

fs = FileStore("/tmp/results/mlflow")
fs._get_active_experiments(True)
```
gives
```
['/tmp/results/mlflow/models',
 '/tmp/results/mlflow/946900977152863280',
 '/tmp/results/mlflow/0']
```

**Comment by BenWilson2** [comment]
Hi @sfo thank you for reporting. Do you have a simple repro that we can take a look at?

**Comment by sfo** [comment]
Sure:
```python
from pathlib import Path
import tensorflow as tf
import mlflow

output_path = Path("/tmp/results")
mlflow_path = output_path / "mlflow"
mlflow.set_tracking_uri(mlflow_path)

model = tf.keras.Sequential([tf.keras.Input(1)])

with mlflow.start_run() as run:
    mlflow.tensorflow.log_model(
        model,
        artifact_path="model",
        registered_model_name=f"{run.info.run_id}",
    )
```
In the meantime, I did some more analysis regarding specific conditions under which the error occurs:
- the error happens when outputting to "/tmp", not when using, e. g., `output_path = Path("./results")`
- the error only happens when setting the `registered_model_name` parameter to `run.info.run_id`. Using, e. g., `registered_model_name=f"{run.info.run_id}_"` does not trigger the error.
