### ISSUE TITLE
[BUG] MLflow Artifacts error

### ISSUE THREAD

**Issue by micron1390** [mlflow/mlflow#10240]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 22.04
- **Python version**: Python 3.10.12
- **yarn version, if running the dev UI**:

### Describe the problem

Hi everyone,
Could you tell me please how to configure MLflow Local storage according to the guide:
[mlflow-storage](https://mlflow.org/docs/latest/tracking.html#scenario-1-mlflow-on-localhost)

I added it to docker-compose:
```
    app:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - 5001
        # networks:
        #     - frontend
        #     - backend
        environment:
          - BACKEND=postgresql://${DB_USER:-postgres}@${DB_SERVER:-db}:${DB_PORT:-5432}/${DB_NAME:-mlflow}
          - ARTIFACTS=/storage/mlruns  # in-container path to filestore in filesys
          # For artifact store in AWS S3 (uses boto that was installed in container):
          # Commment out ARTIFACTS line above and instead use:
          #  - ARTIFACTS="s3://mlflow_bucket/my_mlflow_dir/"
          #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          #  - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        volumes:
            - ${FILESTORE:-/storage/mlruns}:/storage/mlruns  # can comment out this line if using S3
            - ${PGPASS:-~/.pgpass}:/root/.pgpass  # provides the pw for BACKEND database
            - condaenv_vol:/opt/conda  # provides continuity/speed when looping runs with same container
        command:
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server
                --port 5001
                --host 0.0.0.0
                --backend-store-uri $${BACKEND}
                --default-artifact-root $${ARTIFACTS}
                --app-name basic-auth
``` 

but artifacts are not written to local storage

Thanks in advance for your advice and suggestions.

### Steps to reproduce the bug

cat python3 mlflow_test.py

```
import os
from random import random, randint
from mlflow import log_metric, log_param, log_params, log_artifacts

if __name__ == "__main__":
    # Log a parameter (key-value pair)
    log_param("config_value", randint(0, 100))

    # Log a dictionary of parameters
    log_params({"param1": randint(0, 100), "param2": randint(0, 100)})

    # Log a metric; metrics can be updated throughout the run
    log_metric("accuracy", random() / 2.0)
    log_metric("accuracy", random() + 0.1)
    log_metric("accuracy", random() + 0.2)

    # Log an artifact (output file)
    if not os.path.exists("outputs"):
        os.makedirs("outputs")
    with open("outputs/test.txt", "w") as f:
        f.write("hello world!")
    log_artifacts("outputs")
``` 

```
Traceback (most recent call last):
  File "/home/ubuntu/docker_mlflow_db/mlflow_test.py", line 22, in <module>
    log_artifacts("outputs")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1008, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1188, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 538, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 59, in log_artifacts
    mkdir(artifact_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/utils/file_utils.py", line 204, in mkdir
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mlflow/utils/file_utils.py", line 201, in mkdir
    os.makedirs(target)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/storage/mlruns/0/bfddb2f449d2464eb25fc0ebd4a46e60'

```

**Comment by BenWilson2** [comment]
Hi @micron1390 I think this example might help out a bit, which showcases defining a minio setup (better than using local disk from my experience) with a postgres DB configuration, all setup with docker configuration .yml and basic DockerFile specifications: 

https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts

If you read through the README in the 2nd half (the advanced setup portion), you'll see which files in that directory are involved and you can look at the configuration setup within https://github.com/mlflow/mlflow/blob/master/examples/mlflow_artifacts/docker-compose.yml to see how things are setup :)

**Comment by micron1390** [comment]
> Hi @micron1390 I think this example might help out a bit, which showcases defining a minio setup (better than using local disk from my experience) with a postgres DB configuration, all setup with docker configuration .yml and basic DockerFile specifications:
> 
> https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts
> 
> If you read through the README in the 2nd half (the advanced setup portion), you'll see which files in that directory are involved and you can look at the configuration setup within https://github.com/mlflow/mlflow/blob/master/examples/mlflow_artifacts/docker-compose.yml to see how things are setup :)

Hi @BenWilson2 Thanks for your reply
I deployed docker-compose: [https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts](https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts)

```
# Build services
$ docker-compose build

# Launch tracking and artifacts servers in the background
$ docker-compose up -d

# Run `example.py` in the client container
$ docker-compose run -v ${PWD}/example.py:/app/example.py client python example.py
```

but when I run the model experiment, I get an error saving artifacts:
```
mlflow run . --experiment-name=lr_test2 --run-name=first_run
```

```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    mlflow.sklearn.log_model(lr, "model", signature=signature)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 411, in log_model
    return Model.log(
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/models/model.py", line 620, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1008, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1188, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 538, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 45, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 28, in log_artifact
    resp = http_request(
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 120, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://artifacts-server:5500/api/2.0/mlflow-artifacts/artifacts/experiments/3/d3a02e2e3c4441c6bc2a1c893f5a18c5/artifacts/model/model.pkl failed with exception HTTPConnectionPool(host='artifacts-server', port=5500): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiments/3/d3a02e2e3c4441c6bc2a1c893f5a18c5/artifacts/model/model.pkl (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe65fe308e0>: Failed to resolve 'artifacts-server' ([Errno -2] Name or service not known)"))
2023/11/08 21:51:26 ERROR mlflow.cli: === Run (ID 'd3a02e2e3c4441c6bc2a1c893f5a18c5') failed ===
```
I took the experiment from here:
[https://github.com/mlflow/mlflow/tree/master/examples/sklearn_logistic_regression](https://github.com/mlflow/mlflow/tree/master/examples/sklearn_logistic_regression)



Please help me figure it out

many thanks.

**Comment by micron1390** [comment]
> Hi @micron1390 I think this example might help out a bit, which showcases defining a minio setup (better than using local disk from my experience) with a postgres DB configuration, all setup with docker configuration .yml and basic DockerFile specifications:
> 
> https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts
> 
> If you read through the README in the 2nd half (the advanced setup portion), you'll see which files in that directory are involved and you can look at the configuration setup within https://github.com/mlflow/mlflow/blob/master/examples/mlflow_artifacts/docker-compose.yml to see how things are setup :)

I currently have these containers running, but I can’t write artifacts, what could be the problem?

```
docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                      PORTS                              NAMES
1850761e0a8f   mlflow_artifacts_client             "python example.py"      21 seconds ago   Exited (0) 6 seconds ago                                       mlflow_artifacts_client_run_d58f73f9283b
135eda8acfe6   mlflow_artifacts_client             "python3"                7 hours ago      Exited (0) 7 hours ago                                         mlflow_artifacts_client_1
707b59b45e10   mlflow_artifacts_tracking-server    "mlflow server --hos…"   7 hours ago      Up 7 hours                  0.0.0.0:5000->5000/tcp             mlflow_artifacts_tracking-server_1
1dc464ca479b   mlflow_artifacts_artifacts-server   "mlflow server --hos…"   7 hours ago      Up 7 hours                  0.0.0.0:5500->5500/tcp             mlflow_artifacts_artifacts-server_1
76af3dc35afa   minio/mc                            "bash -c ' mc alias …"   7 hours ago      Exited (1) 19 seconds ago                                      mlflow_artifacts_minio-create-bucket_1
9fae270650ab   postgres                            "docker-entrypoint.s…"   7 hours ago      Up 7 hours                  5432/tcp                           mlflow_artifacts_postgres_1
a92b1f5b50e3   minio/minio                         "/usr/bin/docker-ent…"   7 hours ago      Up 7 hours (healthy)        0.0.0.0:9000-9001->9000-9001/tcp   mlflow_artifacts_minio_1
```

```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    mlflow.sklearn.log_model(lr, "model", signature=signature)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 411, in log_model
    return Model.log(
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/models/model.py", line 620, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1020, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1188, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 538, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 45, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 28, in log_artifact
    resp = http_request(
  File "/home/user/.mlflow/envs/mlflow-5dbdec5f659320e5e6956110ef10edf5e2a822f6/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 120, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://artifacts-server:5500/api/2.0/mlflow-artifacts/artifacts/experiments/4/19e722e4f905493595c686fa9abb8710/artifacts/model/model.pkl failed with exception HTTPConnectionPool(host='artifacts-server', port=5500): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiments/4/19e722e4f905493595c686fa9abb8710/artifacts/model/model.pkl (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f67db3e58e0>: Failed to resolve 'artifacts-server' ([Errno -2] Name or service not known)"))
2023/11/20 23:11:54 ERROR mlflow.cli: === Run (ID '19e722e4f905493595c686fa9abb8710') failed ===
```


Thanks in advance.

**Comment by BenWilson2** [comment]
Can you try to access the minio container directly via a write command (not through MLflow) and see if that works?

**Comment by micron1390** [comment]
> Can you try to access the minio container directly via a write command (not through MLflow) and see if that works?

Please clarify what you mean, I'm connecting to the minio container

**Comment by BenWilson2** [comment]
externally, from, say, a terminal, can you write files and read files from the minio instance?

**Comment by micron1390** [comment]
> externally, from, say, a terminal, can you write files and read files from the minio instance?

yes, externally from a terminal I was able to mount the bucket and read the created experiments
```
$ docker-compose run -v ${PWD}/example.py:/app/example.py client python example.py
```
![minio](https://github.com/mlflow/mlflow/assets/47168912/7bf19a62-6354-467e-a36a-33b39ede448b)

I was also able to create directories and files

**Comment by micron1390** [comment]
> externally, from, say, a terminal, can you write files and read files from the minio instance?

Please clarify, should DNS be raised on the host or in the container?
As I understand it, it is trying to connect via dns and not via ip

```
mlflow.exceptions.MlflowException: API request to http://artifacts-server:5500/api/2.0/mlflow-artifacts/artifacts/experiments/4/19e722e4f905493595c686fa9abb8710/artifacts/model/model.pkl failed with exception HTTPConnectionPool(host='artifacts-server', port=5500): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiments/4/19e722e4f905493595c686fa9abb8710/artifacts/model/model.pkl (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f67db3e58e0>: Failed to resolve 'artifacts-server' ([Errno -2] Name or service not known)"))
2023/11/20 23:11:54 ERROR mlflow.cli: === Run (ID '19e722e4f905493595c686fa9abb8710') failed ===
```

**Comment by dvalenciar** [comment]
**Not sure if this is still helpful or relevant, but I wanted to share the solution that worked for me in case it helps others.**

I was running an MLflow tracking server on a local machine (not using S3 or cloud storage) and had trouble logging artifacts from a remote training machine.

The command that solved my issue was:

```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri sqlite:///mlflow_server/mlflow.db \
    --artifacts-destination ./mlflow_server/artifacts
```
The key component is the `artifacts-destination` flag, which tells the MLflow server where to store the artifacts and enables HTTP-proxied artifact uploads. Without this, the client will incorrectly try to write files directly to the server’s file system and cause permission errors.

**Comment by psennats** [comment]
The main issue I encountered is that server settings related to artifacts (like --serve-artifacts or --artifacts-destination) only affect newly created experiments, not existing ones. So, testing server changes required creating new experiments each time. I wasted a ton of time until realizing this detail.

Also, when the server wasn't serving artifacts, the error message from my application was unclear: PermissionError: [Errno 13] Permission denied: '/mlflow'. This seems to indicate that the experiment was created when the server did not support artifacts. So fixing the server and creating new runs for the same experiment will continue to show the same error message.

**So for each change you make to the server, create a new experiment to test it!**
