### ISSUE TITLE
[BUG]mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from http://pnc-mlflow.nioint.com/api/2.0/mlflow-artifacts/artifacts/52/4c1e6428f3cc4717acfe78ac5636a1c2/artifacts: {'466090b8bb526f993964393c77c88287_train.txt': 'ChunkedEncodingError(ProtocolError("     Connection broken: InvalidChunkLength(got length b\'\', 0 bytes read)", InvalidChunkLength(got length b\'\', 0 bytes read)))'}

### ISSUE THREAD

**Issue by zoro0312** [mlflow/mlflow#10720]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.3.2
- Tracking server: 2.0.1

### System information

- Linux Ubuntu 16.04)
- 3.8.12
- **yarn version, if running the dev UI**:

### Describe the problem

Traceback (most recent call last):
  File "/data-driven/bin/../train_main.py", line 366, in <module>
    main(cfg)
  File "/data-driven/bin/../train_main.py", line 267, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/data-driven/data/__init__.py", line 32, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/data-driven/data/attention_dataset.py", line 22, in __init__
    train_files, val_files, eval_files = self.get_files_from_mlflow(dataset_cfg.data_index_run_id)
  File "/data-driven/data/attention_dataset.py", line 100, in get_files_from_mlflow
    mlflow.artifacts.download_artifacts(run_id=run_id, dst_path=index_download_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/artifacts/__init__.py", line 69, in download_artifacts
    artifact_location = artifact_repo.download_artifacts(artifact_path, dst_path=dst_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 268, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from http://pnc-mlflow.nioint.com/api/2.0/mlflow-artifacts/artifacts/52/4c1e6428f3cc4717acfe78ac5636a1c2/artifacts: {'466090b8bb526f993964393c77c88287_train.txt': 'ChunkedEncodingError(ProtocolError("Connection broken: InvalidChunkLength(got length b\'\', 0 bytes read)", InvalidChunkLength(got length b\'\', 0 bytes read)))'}
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 7 (pid: 309) of binary: /opt/conda/bin/python

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by Harikishan3** [comment]
python javascript
