### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kgoz12** [mlflow/mlflow#10860]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.9.2

### System information

Databricks Runtime Version: 11.3 LTS ML (includes Apache Spark 3.3.0, Scala 2.12)
Python Version: 3.9

### Describe the problem

mlflow.pyfunc.spark_udf() returns the following error when attempting to use a custom pipeline and task as defined by PIPELINE_REGISTRY.register_pipeline().
The error: 'KeyError: "Unknown task entity-pair-classification, available tasks are ['audio-classification', 'automatic-speech-recognition', 'conversational', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-segmentation', 'image-to-text', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'summarization', 'table-question-answering', 'text-classification', 'text-generation', 'text2text-generation', 'token-classification', 'translation', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']"'.

Full code for reproducing error: https://github.com/kgoz12/Reproducible_Ex/blob/main/Reproducible_Example_Custom_Pipeline_Spark_UDF.ipynb

Does the call from _validate_transformers_task_type() to get_supported_tasks() (https://github.com/mlflow/mlflow/blob/98aefdf1af299c4ddef898377860e06eda7969f3/mlflow/transformers/__init__.py#L1276) simply call for the list in https://github.com/huggingface/transformers/blob/f4f57f9dfa68948a383c352a900d588f63f6290a/src/transformers/pipelines/__init__.py#L434? And is the code in the directory specified by code_paths run once the environment is set up? Could get_supported_tasks() call PIPELINE_REGISTRY.get_supported_tasks() once prepended code is run?

### Code to reproduce issue

import mlflow
from pyspark.sql.functions import struct, col
logged_model = 'runs:/27c7190cf78d493ca4c3d779c73d6581/re_custom_pipeline'

loaded_model = mlflow.pyfunc.spark_udf(
    spark, 
    model_uri=logged_model, 
    result_type='string',
    )

display(spark_df.withColumn('predictions', loaded_model(struct(*map(col, spark_df.columns)))))
     

### Stack trace

Downloading artifacts:   0%|          | 0/19 [00:00<?, ?it/s]

2024/01/17 20:16:41 INFO mlflow.store.artifact.artifact_repo: The progress bar can be disabled by setting the environment variable MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR to false
2024/01/17 20:16:51 WARNING mlflow.pyfunc: Calling `spark_udf()` with `env_manager="local"` does not recreate the same environment that was used during training, which may lead to errors or inaccurate predictions. We recommend specifying `env_manager="conda"`, which automatically recreates the environment that was used to train the model and performs inference in the recreated environment.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2024/01/17 20:16:51 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 4 times, most recent failure: Lost task 0.3 in stage 27.0 (TID 89) (10.21.102.0 executor 3): org.apache.spark.api.python.PythonException: 'KeyError: "Unknown task entity-pair-classification, available tasks are ['audio-classification', 'automatic-speech-recognition', 'conversational', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-segmentation', 'image-to-text', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'summarization', 'table-question-answering', 'text-classification', 'text-generation', 'text2text-generation', 'token-classification', 'translation', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']"'. Full traceback below: Traceback (most recent call last): File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1647, in udf os.kill(scoring_server_proc.pid, signal.SIGTERM) File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 689, in load_model raise e File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/mlflow/transformers/__init__.py", line 1626, in _load_pyfunc _load_model(str(local_path), flavor_configuration, "pipeline"), File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/mlflow/transformers/__init__.py", line 1009, in _load_model return transformers.pipeline(**conf) File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 744, in pipeline normalized_task, targeted_task, task_options = check_task(task) File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 487, in check_task return PIPELINE_REGISTRY.check_task(task) File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4fb885a9-934f-4c6a-a113-d42622273905/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1194, in check_task raise KeyError( KeyError: "Unknown task entity-pair-classification, available tasks are ['audio-classification', 'automatic-speech-recognition', 'conversational', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-segmentation', 'image-to-text', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'summarization', 'table-question-answering', 'text-classification', 'text-generation', 'text2text-generation', 'token-classification', 'translation', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']" at org.apache.spark.api.python.BasePythonRunner

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hi @kgoz12 I feel like this this not `spark_udf` issue but issue in your custom model .

To narrow down the issue scope, could you **start a fresh python process** and try following code firstly:

```
pyfunc_model = mlflow.pyfunc.load(<your_model_uri>)

pyfunc_model.predict(..)
```

**Comment by WeichenXu123** [comment]
this is probably because `PIPELINE_REGISTRY.register_pipeline()` is not called when loading the model in spark UDF side, let's test this firstly https://github.com/mlflow/mlflow/issues/10860#issuecomment-1903436798

**Comment by WeichenXu123** [comment]
I think so.

**Comment by kgoz12** [comment]
The .py in `code_paths=["/Workspace/Users/FAKE/FAKE/FAKE/"] `contains the following: 
```
class EntityPairClassificationPipeline(Pipeline):

    def _sanitize_parameters(self, **kwargs):
       …

    def __call__(self, text, **kwargs): 
        …

    def preprocess(self, text, entity_spans=None):
        …

    def _forward(self, model_inputs):
        ….

    def postprocess(self, model_outputs):
        …

PIPELINE_REGISTRY.register_pipeline(
    "entity-pair-classification",
    pipeline_class=EntityPairClassificationPipeline,
    pt_model=LukeForEntityPairClassification,
    type="text"  
)
```
If an error were to exist with this code I would expect a different error message to be returned than `"Unknown task entity-pair-classification, available tasks are ...`. Is the pipeline registry being checked using `PIPELINE_REGISTRY.get_supported_tasks()`? Or is the user provided task being compared to the hard-codded list in the HuggingFace repo? https://github.com/huggingface/transformers/blob/f4f57f9dfa68948a383c352a900d588f63f6290a/src/transformers/pipelines/__init__.py#L158

**Comment by WeichenXu123** [comment]
Could you test on this branch too ?

https://github.com/mlflow/mlflow/pull/10896

Btw we are going to redesign "code_paths" features in next quarter to totally address related issues, pls stay tuned. :)

**Comment by akunta1** [comment]
> Could you test on this branch too ?
> 
> #10896
> 
> Btw we are going to redesign "code_paths" features in next quarter to totally address related issues, pls stay tuned. :)

Hi, Im getting the same error with the latest mlflow. Could you please advice.
