### ISSUE TITLE
No user id find when using on kubernetes cluster

### ISSUE THREAD

**Issue by lifeisshubh** [mlflow/mlflow#1103]
Error Trace.
```
Traceback (most recent call last):
  File "Contest.py", line 178, in <module>
    with mlflow.start_run() as run:
  File "/scratch/scratch5/shubham/anaconda3/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 142, in start_run
    tags=tags
  File "/scratch/scratch5/shubham/anaconda3/lib/python3.6/site-packages/mlflow/tracking/client.py", line 74, in create_run
    user_id=user_id if user_id is not None else _get_user_id(),
  File "/scratch/scratch5/shubham/anaconda3/lib/python3.6/site-packages/mlflow/tracking/client.py", line 269, in _get_user_id
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1111'

 ```
I am running my code on the kubernetes cluster by deploying jobs with docker images. 
Operating system : ubuntu 16.04
Ram : 8 GB
GPU : Nvidia 1080

Does any way to fix it?

**Comment by lifeisshubh** [comment]
Fixed it by hard coding user id.

**Comment by tritab** [comment]
In case anyone else runs into this, had the same problem in a k8s cluster. I was able to set the `USER` environment variable, which allowed getpass to use that for the user name. https://docs.python.org/3/library/getpass.html

> This function checks the environment variables LOGNAME, USER, LNAME and USERNAME, in order, and returns the value of the first one which is set to a non-empty string.
