### ISSUE TITLE
[BUG] [QUESTION] Is there an example somewhere which uses Recipes with `automl/flaml`?

### ISSUE THREAD

**Issue by mchutani-CS** [mlflow/mlflow#11112]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.2
- Tracking server: 2.10.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: M1 MACOS
- **Python version**: 3.9.17
- **yarn version, if running the dev UI**:

### Describe the problem

While running wine quality example by setting `train.using: automl/flaml`, I'm getting the following error:

```
2024/02/13 16:13:54 INFO mlflow.recipes.recipe: Creating MLflow Recipe 'wine-quality' with profile: 'local'
2024/02/13 16:13:54 INFO mlflow.recipes.utils.execution: ingest, split, transform: No changes. Skipping.
Run MLflow Recipe step: train
2024/02/13 16:13:55 INFO mlflow.recipes.step: Running step train...
2024/02/13 16:13:55 INFO mlflow.recipes.steps.train: Detected class imbalance: minority class percentage is 0.25
2024/02/13 16:13:55 INFO mlflow.recipes.steps.train: After downsampling: minority class percentage is 0.30
[flaml.automl.logger: 02-13 16:13:55] {1679} INFO - task = classification
[flaml.automl.logger: 02-13 16:13:55] {1690} INFO - Evaluation method: cv
[flaml.automl.logger: 02-13 16:13:55] {1788} INFO - Minimizing error metric: 1-f1
[flaml.automl.logger: 02-13 16:13:56] {1900} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'catboost', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'lrl1']
[flaml.automl.logger: 02-13 16:13:56] {2218} INFO - iteration 0, current learner lgbm
/bin/sh: line 1: 26769 Segmentation fault: 11  python -c "from mlflow.recipes.steps.train import TrainStep; TrainStep.from_step_config_path(step_config_path='.mlflow/recipes/ec3d911f9f99a38cf5a57b2828bc3f3a12c8e8c33602d49cc5e1c979e7713f6d/steps/train/conf.yaml', recipe_root='mlflow-test/recipes/wine-quality').run(output_directory='.mlflow/recipes/ec3d911f9f99a38cf5a57b2828bc3f3a12c8e8c33602d49cc5e1c979e7713f6d/steps/train/outputs')"
make: *** [steps/train/outputs/run_id] Error 139
2024/02/13 16:13:56 INFO mlflow.recipes.step: Unable to locate runtime info for step 'train'. Re-run the step before inspect.
Traceback (most recent call last):
  File "mlflow-test/recipes/wine-quality/run.py", line 8, in <module>
    regression_recipe.run()
  File "miniconda3/envs/cortex/lib/python3.9/site-packages/mlflow/recipes/classification/v1/recipe.py", line 265, in run
    return super().run(step=step)
  File "miniconda3/envs/cortex/lib/python3.9/site-packages/mlflow/recipes/recipe.py", line 108, in run
    raise MlflowException(
mlflow.exceptions.MlflowException: Failed to run recipe 'wine-quality':
The following error occurred while running step 'Step:train':
None
Last step status: 'StepStatus.RUNNING'
```

Is there any example or documentation that uses `automl/flaml` with MLFLOW Recipes?

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
# `recipe.yaml` is the main configuration file for an MLflow Recipe.
# Required recipe parameters should be defined in this file with either concrete values or
# variables such as {{ INGEST_DATA_LOCATION }}.

# Variables must be dereferenced in a profile YAML file, located under `profiles/`.
# See `profiles/local.yaml` for example usage. One may switch among profiles quickly by
# providing a profile name such as `local` in the Recipe object constructor:
# `p = Recipe(profile="local")`
#
# NOTE: YAML does not support tabs for indentation. Please use spaces and ensure that all YAML
# files are properly formatted.

recipe: "classification/v1"
# Specifies the name of the column containing targets / labels for model training and evaluation
target_col: "is_red"
# Specifies the value of `target_col` which is considered the positive class: red wine in this case.
positive_class: 1
# Sets the primary metric to use to evaluate model performance. This primary metric is used
# to sort MLflow Runs corresponding to the recipe in the MLflow Tracking UI
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    # Train/validation/test split ratios
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
    # Specifies the method to use to perform additional cleaning on split datasets
    # Note that arbitrary transformations should go into the transform step
    # post_split_filter_method: create_dataset_filter
  transform:
    using: custom
    # Specifies the method that defines the data transformations to apply during model inference
    transformer_method: transformer_fn
  train:
    using: "automl/flaml"
    # Specifies the method that defines the estimator type and parameters to use for model training
    # estimator_method: estimator_fn
  evaluate:
    # Sets performance thresholds that a trained model must meet in order to be eligible for
    # registration to the MLflow Model Registry
    validation_criteria:
      - metric: f1_score
        threshold: 0.6
      - metric: precision_score
        threshold: 0.6
      - metric: recall_score
        threshold: 0.6
  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}
    # model_uri: "models/model.pkl"

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@mchutani-CS I checked https://github.com/mlflow/recipes-classification-template but we don't seem to have an example which uses Recipes with automl/flaml.

**Comment by harupy** [comment]
@mchutani-CS do you have the full traceback? Can you check the card of the failed step? I think the full traceback is included there.

**Comment by mchutani-CS** [comment]
@harupy There are no artifacts recorded with this run. I'm getting the straceback attached above. Is there any other location I should look at?

**Comment by johannesrave** [comment]
unsure whether this is the same issue, but i also can't run my test-project using `automl/flaml`.

```
❯ pdm run mlflow recipes clean --profile space-titanic && pdm run mlflow recipes run --profile space-titanic
2024/03/14 10:12:09 INFO mlflow.recipes.recipe: Creating MLflow Recipe 'mlflow-recipes' with profile: 'space-titanic'
2024/03/14 10:12:11 INFO mlflow.recipes.recipe: Creating MLflow Recipe 'mlflow-recipes' with profile: 'space-titanic'
Run MLflow Recipe step: ingest
2024/03/14 10:12:12 INFO mlflow.recipes.step: Running step ingest...
Run MLflow Recipe step: split
2024/03/14 10:12:13 INFO mlflow.recipes.step: Running step split...
/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/split.py:133: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return data_subset.applymap(func)
/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/split.py:133: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return data_subset.applymap(func)
/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/split.py:133: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return data_subset.applymap(func)
/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/split.py:133: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return data_subset.applymap(func)
Run MLflow Recipe step: transform
2024/03/14 10:12:14 INFO mlflow.recipes.step: Running step transform...
Run MLflow Recipe step: train
2024/03/14 10:12:15 INFO mlflow.recipes.step: Running step train...
2024/03/14 10:12:16 INFO mlflow.recipes.steps.train: Training data has less than 5000 rows, skipping rebalancing.
[flaml.automl.logger: 03-14 10:12:16] {1680} INFO - task = classification
[flaml.automl.logger: 03-14 10:12:16] {1691} INFO - Evaluation method: cv
[flaml.automl.logger: 03-14 10:12:16] {1789} INFO - Minimizing error metric: customized metric
[flaml.automl.logger: 03-14 10:12:16] {1901} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'lrl1']
[flaml.automl.logger: 03-14 10:12:16] {2219} INFO - iteration 0, current learner lgbm
2024/03/14 10:12:16 WARNING mlflow.recipes.steps.automl.flaml: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 166, in _create_model_automl
    automl.fit(X, y, **automl_settings)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 1929, in fit
    self._search()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2483, in _search
    self._search_sequential()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2319, in _search_sequential
    analysis = tune.run(
               ^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/tune/tune.py", line 814, in run
    result = evaluation_function(trial_to_run.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/state.py", line 304, in _compute_with_config_base
    ) = compute_estimator(
        ^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 369, in compute_estimator
    val_loss, metric_for_logging, train_time, pred_time = task.evaluate_model_CV(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/task/generic_task.py", line 740, in evaluate_model_CV
    val_loss_i, metric_i, train_time_i, pred_time_i = get_val_loss(
                                                      ^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 494, in get_val_loss
    estimator.fit(X_train, y_train, budget=budget, free_mem_ratio=free_mem_ratio, **fit_kwargs)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 1413, in fit
    self._fit(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 220, in _fit
    model = self.estimator_class(**self.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
Stack (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/step.py", line 132, in run
    self.step_card = self._run(output_directory=output_directory)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 369, in _run
    estimator = self._resolve_estimator(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 702, in _resolve_estimator
    return self._resolve_estimator_plugin(using_plugin, X_train, y_train, output_directory)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 677, in _resolve_estimator_plugin
    estimator, best_parameters = estimator_fn(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 52, in get_estimator_and_best_params
    return _create_model_automl(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 176, in _create_model_automl
    _logger.warning(e, exc_info=e, stack_info=True)
Traceback (most recent call last):
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 166, in _create_model_automl
    automl.fit(X, y, **automl_settings)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 1929, in fit
    self._search()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2483, in _search
    self._search_sequential()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2319, in _search_sequential
    analysis = tune.run(
               ^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/tune/tune.py", line 814, in run
    result = evaluation_function(trial_to_run.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/state.py", line 304, in _compute_with_config_base
    ) = compute_estimator(
        ^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 369, in compute_estimator
    val_loss, metric_for_logging, train_time, pred_time = task.evaluate_model_CV(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/task/generic_task.py", line 740, in evaluate_model_CV
    val_loss_i, metric_i, train_time_i, pred_time_i = get_val_loss(
                                                      ^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 494, in get_val_loss
    estimator.fit(X_train, y_train, budget=budget, free_mem_ratio=free_mem_ratio, **fit_kwargs)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 1413, in fit
    self._fit(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 220, in _fit
    model = self.estimator_class(**self.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/step.py", line 132, in run
    self.step_card = self._run(output_directory=output_directory)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 369, in _run
    estimator = self._resolve_estimator(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 702, in _resolve_estimator
    return self._resolve_estimator_plugin(using_plugin, X_train, y_train, output_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 677, in _resolve_estimator_plugin
    estimator, best_parameters = estimator_fn(
                                 ^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 52, in get_estimator_and_best_params
    return _create_model_automl(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 177, in _create_model_automl
    raise MlflowException(
mlflow.exceptions.MlflowException: Error has occurred during training of AutoML model using FLAML: TypeError("'NoneType' object is not callable")
make: *** [Makefile:40: steps/train/outputs/run_id] Error 1
2024/03/14 10:12:16 INFO mlflow.recipes.utils.step: Opening HTML file at: '/home/johannesrave/.mlflow/recipes/4017c17da008f790842d057848e03dabf1f2c837c6f6beee05118abec7520772/steps/train/outputs/card.html'
Traceback (most recent call last):
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/bin/mlflow", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/cli.py", line 44, in run
    Recipe(profile=profile).run(step)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/classification/v1/recipe.py", line 266, in run
    return super().run(step=step)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/recipe.py", line 111, in run
    raise MlflowException(
mlflow.exceptions.MlflowException: Failed to run recipe 'mlflow-recipes':
The following error occurred while running step 'Step:train':
Traceback (most recent call last):
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 166, in _create_model_automl
    automl.fit(X, y, **automl_settings)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 1929, in fit
    self._search()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2483, in _search
    self._search_sequential()
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/automl.py", line 2319, in _search_sequential
    analysis = tune.run(
               ^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/tune/tune.py", line 814, in run
    result = evaluation_function(trial_to_run.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/state.py", line 304, in _compute_with_config_base
    ) = compute_estimator(
        ^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 369, in compute_estimator
    val_loss, metric_for_logging, train_time, pred_time = task.evaluate_model_CV(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/task/generic_task.py", line 740, in evaluate_model_CV
    val_loss_i, metric_i, train_time_i, pred_time_i = get_val_loss(
                                                      ^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/ml.py", line 494, in get_val_loss
    estimator.fit(X_train, y_train, budget=budget, free_mem_ratio=free_mem_ratio, **fit_kwargs)
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 1413, in fit
    self._fit(
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/flaml/automl/model.py", line 220, in _fit
    model = self.estimator_class(**self.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/step.py", line 132, in run
    self.step_card = self._run(output_directory=output_directory)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 369, in _run
    estimator = self._resolve_estimator(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 702, in _resolve_estimator
    return self._resolve_estimator_plugin(using_plugin, X_train, y_train, output_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/train.py", line 677, in _resolve_estimator_plugin
    estimator, best_parameters = estimator_fn(
                                 ^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 52, in get_estimator_and_best_params
    return _create_model_automl(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/dev/kaggle/mlflow-recipes/.venv/lib/python3.11/site-packages/mlflow/recipes/steps/automl/flaml.py", line 177, in _create_model_automl
    raise MlflowException(
mlflow.exceptions.MlflowException: Error has occurred during training of AutoML model using FLAML: TypeError("'NoneType' object is not callable")

Last step status: 'StepStatus.FAILED'
```
the space-titanic.yaml:

```
recipe: "classification/v1"
# FIXME::REQUIRED: Specifies the target column name for model training and evaluation.
target_col: "Transported"
# FIXME::REQUIRED: Specifies the value of `target_col` that is considered the positive class.
positive_class: "True"
# FIXME::REQUIRED: Sets the primary metric to use to evaluate model performance. This primary
#                  metric is used to select best performing models in MLflow UI as well as in
#                  train and evaluation step.
#                  Built-in primary metrics are: recall_score, precision_score, f1_score, accuracy_score.
primary_metric: "precision_score"
steps:
  # Specifies the dataset to use for model development
  ingest: {{INGEST_CONFIG}}
  split:
    #
    # FIXME::OPTIONAL: Adjust the train/validation/test split ratios below.
    #
    split_ratios: [0.75, 0.125, 0.125]
    #
    #  FIXME::OPTIONAL: Specifies the method to use to "post-process" the split datasets. Note that
    #                   arbitrary transformations should go into the transform step.
    post_split_filter_method: create_dataset_filter
  transform:
    using: "custom"
    #
    #  FIXME::OPTIONAL: Specifies the method that defines an sklearn-compatible transformer, which
    #                   applies input feature transformation during model training and inference.
    transformer_method: transformer_fn
  train:
    #
    # FIXME::REQUIRED: Specifies the method to use for training. Options are "automl/flaml" for
    #                  AutoML training or "custom" for user-defined estimators.
    using: "automl/flaml"
    time_budget_secs: 30
  evaluate:
    #
    # FIXME::OPTIONAL: Sets performance thresholds that a trained model must meet in order to be
    #                  eligible for registration to the MLflow Model Registry.
    #
    # validation_criteria:
    #   - metric: root_mean_squared_error
    #     threshold: 10
  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
```

**Comment by zemogoravla** [comment]
Please check if this helps:
https://github.com/microsoft/FLAML/issues/1193#issuecomment-1688326149

The classification example works after installing flaml with:
pip install "flaml[automl]"
