### ISSUE TITLE
could not find mlflow module

### ISSUE THREAD

**Issue by juhanishen** [mlflow/mlflow#1116]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.4 virtual machine, user name k8s
- **MLflow installed from (source or binary)**:  pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.7,3
- **npm version (if running the dev UI): not installed
- **Exact command to reproduce**: python examples/sklearn_elasticnet_wine/train.py

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

Follow [MLFlow's quickStart](https://www.mlflow.org/docs/latest/quickstart.html), I install the `python 3.7.3` (I put python in `/usr/local/python3Dir`), `anaconda(conda)` and `pip install mlflow`, I use `git clone` the example in github. The example is in `/home/k8s/mlflow/mlflow/` directory, the first `mlflow` directory is created by me, the second `mlflow` is created by `git clone`, when I enter `/home/k8s/mlflow/mlflow`, I try to run some example, it tells me could not find `mlflow`:

```
   (base) [k8s@k8s mlflow]$ python examples/sklearn_elasticnet_wine/train.py

   Traceback (most recent call last):
   File "examples/sklearn_elasticnet_wine/train.py", line 15, in <module>
     import mlflow
   ModuleNotFoundError: No module named 'mlflow'
```
It could find `myflow` command, though I myself do not know where `myflow` module is installed?
```
   (base) [k8s@k8s mlflow]$ mlflow --version
   /usr/local/python3Dir/lib/python3.7/site-packages/mlflow/utils/environment.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
   env = yaml.load(_conda_header)
   mlflow, version 0.9.0
   (base) [k8s@k8s mlflow]$ whereis mlflow
   mlflow: /usr/local/python3Dir/bin/mlflow
   (base) [k8s@k8s mlflow]$ python --version
   Python 3.7.3

   ```
   How could I let example know where is mlflow so that I could import mlflow module?

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by smurching** [comment]
@juhanishen it sounds like MLflow was pip-installed outside of your conda environment (the `mlflow executable is in `/usr/local/python3Dir/` rather than under a directory managed by conda). Thus `mlflow` is available on your path but is not installed within your conda environment, so `python` (an executable within your conda environment) is unable to find it. I'd try removing the MLflow installation outside your conda environment & reinstalling it within your environment, such that the parent directories of `python` and `mlflow` are the same. For example, my environment looks like:

```
(mlflow_python3) ➜  mlflow git:(branch-0.9) which python
/Users/siddharthmurching/miniconda3/envs/mlflow_python3/bin/python
(mlflow_python3) ➜  mlflow git:(branch-0.9) which mlflow
/Users/siddharthmurching/miniconda3/envs/mlflow_python3/bin/mlflow
```

**Comment by juhanishen** [comment]
I try to uninstall mlflow, but I could not delete mlflow, see the steps below:

```
(base) [k8s@k8s ~]$ pip uninstall mlflow
Skipping mlflow as it is not installed.
(base) [k8s@k8s ~]$ whereis mlflow
mlflow: /usr/local/python3Dir/bin/mlflow
(base) [k8s@k8s ~]$ which mlflow
/usr/local/python3Dir/bin/mlflow
```
At the same time, I found I have multiple python 3 installed. 

```
(base) [k8s@k8s ~]$ which mlflow
/usr/local/python3Dir/bin/mlflow
(base) [k8s@k8s ~]$ which python
~/anaconda3/bin/python
(base) [k8s@k8s ~]$ which python2.7
/usr/bin/python2.7
(base) [k8s@k8s ~]$ which python3.7
~/anaconda3/bin/python3.7
(base) [k8s@k8s ~]$ whereis python
python: /usr/bin/python /usr/bin/python2.7 /usr/bin/python.bak /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/include/python2.7 /home/k8s/anaconda3/bin/python /home/k8s/anaconda3/bin/python3.7-config /home/k8s/anaconda3/bin/python3.7m /home/k8s/anaconda3/bin/python3.7 /home/k8s/anaconda3/bin/python3.7m-config /usr/local/python3Dir/bin/python3.7m /usr/local/python3Dir/bin/python3.7 /usr/local/python3Dir/bin/python3.7m-config /usr/local/python3Dir/bin/python3.7-config /usr/share/man/man1/python.1.gz

```
My question is how to uninstall mlflow and install mlflow in the conda environment?

**Comment by ahshanmd** [comment]
i encountered the same situation , but i had to resolve the issue by doing
` pip3.7 install mlflow`

**Comment by sharmaanix** [comment]
[2020-03-04 13:39:54 +0545] [11791] [INFO] Starting gunicorn 20.0.4
[2020-03-04 13:39:54 +0545] [11791] [INFO] Listening at: http://127.0.0.1:5000 (11791)
[2020-03-04 13:39:54 +0545] [11791] [INFO] Using worker: sync
[2020-03-04 13:39:54 +0545] [11794] [INFO] Booting worker with pid: 11794
[2020-03-04 13:39:54 +0545] [11794] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/anish/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mlflow'
[2020-03-04 13:39:54 +0545] [11794] [INFO] Worker exiting (pid: 11794)
[2020-03-04 13:39:54 +0545] [11791] [INFO] Shutting down: Master
[2020-03-04 13:39:54 +0545] [11791] [INFO] Reason: Worker failed to boot.
Running the mlflow server failed. Please see the logs above for details.
