### ISSUE TITLE
[BUG] MLflow Model server automatically encodes base64, but does not seem to reliably decode base64 according to documentation.

### ISSUE THREAD

**Issue by croth1-liveeo** [mlflow/mlflow#11170]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 2.10.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**:

### Describe the problem

It appears to me that when predicting with pyfunc models, binary outputs are automatically base64 encoded, however for me binary inputs seem to not get automatically base64 decoded.

Added the code I used to replicate the behavior a locally running server seems to have. Note that the model needs to base64 decode explicitly.

Any ideas what is going wrong here? Am I holding it wrong?

The [MLflow documenation for local model deployment](https://mlflow.org/docs/latest/deployment/deploy-model-locally.html#encoding-complex-data) suggests:

> Encoding complex data
> Complex data types, such as dates or binary, do not have a native JSON representation. If you include a model signature, MLflow can automatically decode supported data types from JSON. The following data type conversions are supported:
> - binary: data is expected to be base64 encoded, MLflow will automatically base64 decode.
> - datetime: data is expected to be encoded as a string according to [ISO 8601 specification](https://www.iso.org/iso-8601-date-and-time-format.html). MLflow will parse this into the appropriate datetime representation on the given platform.
>
> binary: data is expected to be base64 encoded, MLflow will automatically base64 decode.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import base64
import json
import tempfile
from io import StringIO
from pathlib import Path

import cloudpickle
import mlflow.pyfunc
import numpy as np
from mlflow.models.signature import ModelSignature
from mlflow.models.utils import _enforce_schema
from mlflow.pyfunc.model import PythonModelContext, _PythonModelPyfuncWrapper
from mlflow.pyfunc.scoring_server import infer_and_parse_data, predictions_to_json
from mlflow.types.schema import ColSpec, Schema


class Base64NumpyModel(mlflow.pyfunc.PythonModel):
    def load_context(self, context):
        # This method can be used to load artifacts or models when the server starts.
        # For this example, we don't need to load anything specific.
        pass

    def predict(self, context, model_input):
        decoded_tensors = []
        for _, row in model_input.iterrows():
            # TODO: why is it assymetric here, in that that a have to base64 decode the tensor, but not the prediction?

            # expected, but does not work:
            # decoded_tensor = cloudpickle.loads(row["tensor"])

            # works, but possibly should not be necessary:
            decoded_tensor = cloudpickle.loads(base64.b64decode(row["tensor"]))
            decoded_tensors.append(decoded_tensor)
        return {"prediction": [cloudpickle.dumps(tensor) for tensor in decoded_tensors]}


# write schema for binary input field
input_schema = Schema([ColSpec(name="tensor", type=mlflow.types.DataType.binary)])
output_schema = Schema([ColSpec(name="prediction", type=mlflow.types.DataType.binary)])

# Create the model signature with binary input
signature = ModelSignature(inputs=input_schema, outputs=output_schema)


model = Base64NumpyModel()

# test the model behavior
wrapper = _PythonModelPyfuncWrapper(model, PythonModelContext({}, {}), signature)
input_array = np.array([1, 2, 3])
base64_encoded_data = base64.b64encode(cloudpickle.dumps(input_array))

input_json = dict(
    inputs={
        "tensor": [base64.b64encode(cloudpickle.dumps(input_array)).decode("ascii")]
    }
)

inputs_raw = infer_and_parse_data(input_json, input_schema)
inputs = _enforce_schema(inputs_raw, input_schema)
output_raw = wrapper.predict(model_input=inputs)
outputs = _enforce_schema(output_raw, output_schema)

output_sink = StringIO()
predictions_to_json(outputs, output_sink)
output_json = json.loads(output_sink.getvalue())

print(output_json)
output_array = cloudpickle.loads(
    base64.b64decode(output_json["predictions"][0]["prediction"])
)
assert np.array_equal(output_array, input_array)
```

### Stack trace

If I change `decoded_tensor = cloudpickle.loads(base64.b64decode(row["tensor"]))` to `decoded_tensor = cloudpickle.loads(row["tensor"])`, I get:

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ray/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ray/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "build_model.py", line 60, in <module>
    output_raw = wrapper.predict(model_input=inputs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/mlflow/pyfunc/model.py", line 469, in predict
    return self.python_model.predict(self.context, self._convert_input(model_input))
  File "build_model.py", line 29, in predict
    decoded_tensor = cloudpickle.loads(row["tensor"])
_pickle.UnpicklingError: pickle data was truncated
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
cc @serena-ruan do we need to add an additional check and decode step for binary types to ensure that we unpack the output correctly?
