### ISSUE TITLE
Unable to run mlflow behind jupyter-server-proxy

### ISSUE THREAD

**Issue by mckev-amazon** [mlflow/mlflow#1120]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon SageMaker (Amazon Linux)
- **MLflow installed from (source or binary)**: pip install
- **MLflow version (run ``mlflow --version``)**: latest
- **Python version**: 3
- **npm version (if running the dev UI): n/a
- **Exact command to reproduce**: See https://stackoverflow.com/questions/55593128/how-to-run-the-mlflow-web-based-user-interface-from-amazon-sagemaker

### Describe the problem
In a hosted environment such as Amazon SageMaker or JupyterHub, a user might want to run mlflow behind the popular [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) extension.  This allows them to use Jupyter alongside mlflow on the same host.

Unfortunately, the way this works is that mlflow is proxied to a path such as http://myjupyter-server.com/proxy/5000 instead of http://127.0.0.1:5000.  Because there are a lot of references to paths that don't exist, the UI doesn't load.

I was almost able to get mlflow up and running, I get as far as the "Oops! Something went wrong." page, but nothing beyond that.

### Source code / logs

1. Create a SageMaker Notebook Instance.
2. !pip install mlflow
3. !mlflow
4. Open http://mynotebook.notebook.region.sagemaker.aws/proxy/5000/
5. "Oops! Something went wrong." (Niagra falls.)

**Comment by freefrag** [comment]
+1 

I'd like to expose MlFlow from behind an Nginx Server, with an application path `/mlflow` and the hard-coded references to `$HOST:$PORT` disallow this.

**Comment by cbg** [comment]
+1

**Comment by vermanurag** [comment]
+1

**Comment by cfrazier91** [comment]
+1

**Comment by Jomonsugi** [comment]
+1

**Comment by murphycrosby** [comment]
+1

**Comment by johnDorian** [comment]
The reason why the website fails, is that there are api calls in the javascript code which are executedon the client side. The definition of these api calls are in mlflow/server/js/src/sdk/MlflowService.js - which is automatically generated based on the proto definitions. 

When you load the website on the client side, the api endpoints (/ajax-api/...) in the javascript code are combined with the hostname and the port number, but not the path of the url. 

I haven't run it on sagemaker, and without seeing the logs from the client side, it's hard to tell if it's the same issue. If it is the same issue, you can change the api path in the source code of mlflow and then compile a custom mlflow package. In regards to the port number, maybe you could run mlflow server on port 80. 

If you're running mlflow behind an nginx reverse proxy you can a filter to update the path in the javascript code that is sent to the client when serving the files: 

````
location /mlflow/ {
    proxy_pass http://localhost:5000/;
    sub_filter '/ajax-api' '/mlflow/ajax-api';
    sub_filter_once off;
    sub_filter_types *;
}
````

**Comment by xhochy** [comment]
It should be fixed by removing the leading `/` from the JavaScript calls. To fix this, I'm sadly missing documentation on how `mlflow/server/js/src/sdk/MlflowService.js` is generated. This is not covered by `generate-protos.sh`.

**Comment by xhochy** [comment]
@mckev-amazon can you give https://github.com/mlflow/mlflow/pull/1413 a try?

**Comment by piratezoro** [comment]
+1

**Comment by zoux86** [comment]
@johnDorian do you know how mlflow/server/js/src/sdk/MlflowService.js is generated ?

**Comment by alext234** [comment]
+1

**Comment by ashutoshsaboo** [comment]
Hello, I'm seeing some new errors with regards to trying to open mlflow in sagemaker notebook, see log below. The UI is opening up fine, but it doesn't show the experiments for some reason. Was anything changed recently that could be causing this? @smurching @harupy @dbczumar If so, can this issue be please re-opened? Or should I create a new issue? 

```
2022/02/15 10:25:55 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/mlflow/server/handlers.py", line 238, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/mlflow/server/handlers.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/mlflow/server/handlers.py", line 539, in _search_runs
    request_message = _get_request_message(SearchRuns())
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/mlflow/server/handlers.py", line 207, in _get_request_message
    request_json = _get_request_json(flask_request)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/mlflow/server/handlers.py", line 177, in _get_request_json
    return flask_request.get_json(force=True, silent=True)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/werkzeug/wrappers/request.py", line 583, in get_json
    data = self.get_data(cache=cache)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/werkzeug/wrappers/request.py", line 424, in get_data
    rv = self.stream.read()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/gunicorn/http/body.py", line 215, in read
    data = self.reader.read(1024)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/gunicorn/http/body.py", line 30, in read
    self.buf.write(next(self.parser))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/gunicorn/http/body.py", line 58, in parse_chunked
    (size, rest) = self.parse_chunk_size(unreader)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/gunicorn/http/body.py", line 82, in parse_chunk_size
    self.get_data(unreader, buf)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/gunicorn/http/body.py", line 105, in get_data
    raise NoMoreData()
gunicorn.http.errors.NoMoreData: No more data after: None
```

**Comment by ravitashaw** [comment]
I'm stuck on the same above issue as above ^^

**Comment by fjpa121197** [comment]
> I'm stuck on the same above issue as above ^^

Did you solve this? Getting same error

**Comment by ravitashaw** [comment]
Nope, have a work around for it. Download the generated files (zipped) in local and run mlflow in local

**Comment by natalipivnitskaya** [comment]
I was able to resolve the issue by port-forwarding instead of using the proxy link. 

In the local terminal, run the following command:
```
ssh -N -L 5000:127.0.0.1:5000 ec2-user@your_sagemaker_instance_ip_address 
```
And then just go to http://127.0.0.1:5000

**Comment by deepwilson** [comment]
@natalipivnitskaya how do you get the sagemaker_instance_ip_address ?
