### ISSUE TITLE
Unable to load S3 Aritifacts

### ISSUE THREAD

**Issue by iamhritik290799** [mlflow/mlflow#11259]
### Willingness to contribute
No

### MLflow version

2.10.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux & 11
- **Python version**: 3.10.13

### Describe the problem

When trying to load Aritifacts from S3 bucket, getting this error 

`2024/02/27 10:27:16 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 494, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 535, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 953, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 211, in list_artifacts
    for result in results:
  File "/opt/bitnami/python/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.`

### Steps to reproduce the bug

Simply Install mlflow on EKS cluster using Bitnami HELM Chart - https://artifacthub.io/packages/helm/bitnami/mlflow

using these value in values.yaml related to S3

externalS3.bucket example-bucket
externalS3.host example-bucket.s3.eu-central-1.amazonaws.com

**Comment by B-Step62** [comment]
Hi @iamhritik290799, thanks for contacting us. Apparently more configuration is required for accessing the S3 bucket, however, the `values.yaml` is specific concept of the Bitnami Helm Chart and we don't maintain it. Could you please reach out to Bitnami for getting further support for the Helm Chart?

**Comment by iamhritik290799** [comment]
Checked with bitnami team as well but they are saying maybe there is some issue with S3 inside the mlflow code that's why getting this error message when accessing S3 artifacts.

**Comment by iamhritik290799** [comment]
We are using this args in our mlflow image
**mlflow image:** docker.io/bitnami/mlflow:2.10.0-debian-11-r3

```
containers:
  - args:
    - server
    - --backend-store-uri=postgresql://admin:$(MLFLOW_DATABASE_PASSWORD)@rds-instance-endpoint.rds.amazonaws.com:5432/mlflow
    - --artifacts-destination=s3://mlflow-artifacts
    - --serve-artifacts
    - --host=0.0.0.0
    - --port=5000
    - --app-name=basic-auth
```

**Comment by iamhritik290799** [comment]
some issue in the bitnami helm chart.
