### ISSUE TITLE
[BUG] MLflow external tracking servers loading is not thread-safe

### ISSUE THREAD

**Issue by aagten** [mlflow/mlflow#11283]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.9.2 (mlflow-skinny)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22
- **Python version**: Python 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

Hi, we're building a python project with both `mlflow-skinny==2.9.2` and `azure-mlflow==1.54.0`. However, when spawning multiple (2+) threads, the tracking URI for Azure is not recognised anymore. For a single-thread and a two-threaded process it works (i.e. setting the range variables to 1), but starting from 3 threads (and more), the azure ML tracking URI is not recognized anymore.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import threading
import mlflow

if __name__ == "__main__":
    tracking_uri = "azureml://myworkspace.workspace.westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.MachineLearningServices/workspaces/myworkspace"
    mlflow.set_tracking_uri(tracking_uri)

    def _do_set_tracking_uri():
        from mlflow import MlflowClient
        client = MlflowClient()
        filter_string = "name='my_model_name'"
        model_versions = client.search_model_versions(filter_string=filter_string, max_results=1)

    threads = []
    for _ in range(0, 3):
        thread = threading.Thread(target=_do_set_tracking_uri)
        thread.start()
        threads.append(thread)

    for t in threads:
        t.join()
```

### Stack trace

```
Exception in thread Exception in thread Thread-2 (_do_set_tracking_uri):
Traceback (most recent call last):
Thread-1 (_do_set_tracking_uri):
Traceback (most recent call last):
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 79, in get_store_builder
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 79, in get_store_builder
    store_builder = self._registry[scheme]
KeyError:     store_builder = self._registry[scheme]
KeyError'azureml'

During handling of the above exception, another exception occurred:

: 'azureml'Traceback (most recent call last):
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 122, in _get_registry_client


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 122, in _get_registry_client
    registry_client = ModelRegistryClient(self._registry_uri, self.tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 36, in __init__
    registry_client = ModelRegistryClient(self._registry_uri, self.tracking_uri)    self.store  # pylint: disable=pointless-statement
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 40, in store

  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 36, in __init__
    self.store  # pylint: disable=pointless-statement    return utils._get_store(self.registry_uri, self.tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 40, in store

  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/utils.py", line 209, in _get_store
    return _get_store_registry().get_store(store_uri, tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/registry.py", line 43, in get_store
    return utils._get_store(self.registry_uri, self.tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/utils.py", line 209, in _get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, resolved_tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/registry.py", line 52, in _get_store_with_resolved_uri
    return _get_store_registry().get_store(store_uri, tracking_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/registry.py", line 43, in get_store
    builder = self.get_store_builder(resolved_store_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 81, in get_store_builder
    return self._get_store_with_resolved_uri(resolved_store_uri, resolved_tracking_uri)
    raise UnsupportedModelRegistryStoreURIException(
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'azureml://myworkspace.workspace.westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.MachineLearningServices/workspaces/myworkspace' for model registry data storage. Supported URI schemes are: ['databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql', '', 'file']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/_model_registry/registry.py", line 52, in _get_store_with_resolved_uri
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    builder = self.get_store_builder(resolved_store_uri)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 81, in get_store_builder
    raise UnsupportedModelRegistryStoreURIException(
mlflow.tracking.registry.    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
UnsupportedModelRegistryStoreURIException    self._target(*self._args, **self._kwargs)
  File "/home/aagten/dev/azure-mlflow-issue/src/main.py", line 13, in _do_set_tracking_uri
:  Model registry functionality is unavailable; got unsupported URI 'azureml://myworkspace.workspace.westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.MachineLearningServices/workspaces/myworkspace' for model registry data storage. Supported URI schemes are: ['databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql', '', 'file']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    model_versions = client.search_model_versions(filter_string=filter_string, max_results=1)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 3234, in search_model_versions
    return self._get_registry_client().search_model_versions(
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 129, in _get_registry_client
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    raise MlflowException(
mlflow.exceptions.MlflowException: Model Registry features are not supported by the store with URI: 'azureml://myworkspace.workspace.westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.MachineLearningServices/workspaces/myworkspace'. Stores with the following URI schemes are supported: ['databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql', '', 'file'].
    self._target(*self._args, **self._kwargs)
  File "/home/aagten/dev/azure-mlflow-issue/src/main.py", line 13, in _do_set_tracking_uri
    model_versions = client.search_model_versions(filter_string=filter_string, max_results=1)
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 3234, in search_model_versions
    return self._get_registry_client().search_model_versions(
  File "/home/aagten/dev/azure-mlflow-issue/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 129, in _get_registry_client
    raise MlflowException(
mlflow.exceptions.MlflowException: Model Registry features are not supported by the store with URI: 'azureml://myworkspace.workspace.westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.MachineLearningServices/workspaces/myworkspace'. Stores with the following URI schemes are supported: ['databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql', '', 'file'].

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@aagten I was able to reproduce the issue. Investigating how this happens.

**Comment by harupy** [comment]
The attached traceback looks like Thread-2 is accessing `self._registry` while it's registering model registry stores.

**Comment by aagten** [comment]
@harupy are you still looking into this?

I would expect that setting the tracking URI before spinning up any threads would alleviate the issue.

From my debugging attempts, I saw that the entrypoints are only executed once. Yet somehow, importing mlflow in a Thread still resets the registry.

**Comment by timunt** [comment]
I have encountered the same issue, is there an update on this @harupy ?
