### ISSUE TITLE
[BUG] Azure Databricks Spark OSError: No such file or directory: '/local_disk0/.ephemeral_nfs/

### ISSUE THREAD

**Issue by moroclash** [mlflow/mlflow#11332]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.6
- Tracking server: Databricks default tracker

### System information

- **Standard_DS13_v2 · 13.3 LTS ML (includes Apache Spark 3.4.1, Scala 2.12)**:

### Describe the problem

I created a workflow by chaining notebooks, each one ends up saving Delta Temporary View, so the downstream notebook can read it and continue the process, at the first notebook, the model is trained, sorted in Mlflow experiment, registered into the Unity catalog, then loaded to predict Pyspark dataframe using mlflow.pyfunc.spark_udf, and after predicting that DF, it is stored as Delta Temp View. at 2nd notebook, while trying to perform some processing (where the Pyspark starts to perform eager processing), it crashes and throws that error.

```
An exception was thrown from the Python worker. Please see the stack trace below.
'OSError: No such file or directory: '/local_disk0/.ephemeral_nfs/repl_tmp_data/ReplId-*******/mlflow/models/tmpb63df0bs/.''. Full traceback below:
Traceback (most recent call last):
File "/databricks/python/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 1435, in udf
loaded_model = mlflow.pyfunc.load_model(local_model_path)
File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-******/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 611, in load_model
local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-*******/lib/python3.10/site-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-********/lib/python3.10/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 81, in download_artifacts
raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: '/local_disk0/.ephemeral_nfs/repl_tmp_data/ReplId-*******/mlflow/models/tmpb63df0bs/.'
```

That error didn't appear when running the notebooks manually, but it crashed when automating them in Databricks workflow.
also when storing the output as a normal Delta table, and reading it in 2nd notebook as a delta table it works too, i can't speculate what's the problem with TempView.

any solution?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@moroclash Thanks for reporting this. Would you mind filing a support ticket or contacting your Databricks account team?

**Comment by harupy** [comment]
@moroclash Any updates on this?

**Comment by juanma9613** [comment]
@moroclash , how did you end up solving this issue? It's happening to me mainly because spot instances terminating and new instances being created in the middle of a model inference. I was running inference for 100M images and it worked fine for the first 10M until a spot instance was terminated and a new one was created and failed.

**Comment by dohrenstein** [comment]
Facing the same issue, also not working when running code locally using "Serverless" compute.

![image](https://github.com/user-attachments/assets/c40bdc2f-8237-4f29-bf8b-c8a35301864d)
![image](https://github.com/user-attachments/assets/bfd3df62-b999-429b-af75-dde9c940c243)
