### ISSUE TITLE
multistep_workflow example can not run with --no-conda

### ISSUE THREAD

**Issue by liangxinhui** [mlflow/mlflow#1136]
### System information
- **Have I written custom code** : No. I use the example multistep_workflow. 
- **OS Platform and Distribution**: Ubuntu 18.04
- **MLflow installed from** :  pip install 
- **MLflow version (run ``mlflow --version``)** : mlflow, version 0.9.0
- **Python version** : 3.6.7
- **npm version (if running the dev UI)** : not care
- **Exact command to reproduce** :  mlflow run . --no-conda

### Describe the problem
I want to run this project without conda, but it reports an error of conda env problem.

### Source code / logs
```
root@dev:/data/mlwork/mlflow/examples/multistep_workflow# mlflow run . --no-conda
2019/04/18 11:22:11 INFO mlflow.projects: === Created directory /tmp/tmpich63ftu for downloading remote URIs passed to arguments of type 'path' ===
2019/04/18 11:22:11 INFO mlflow.projects: === Running command 'python main.py --als-max-iter 10 --keras-hidden-units 20' in run with ID '0d1aea0835dd4c838b03f8f1dc68af92' === 
Launching new run for entrypoint=load_raw_data and parameters={}
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    workflow()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 76, in workflow
    load_raw_data_run = _get_or_run("load_raw_data", {}, source_version)
  File "main.py", line 63, in _get_or_run
     submitted_run = mlflow.run(".", entrypoint, parameters=parameters)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 209, in run
    storage_dir=storage_dir, block=block, run_id=run_id)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 118, in _run
    conda_env_name = _get_or_create_conda_env(project.conda_env_path)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 434, in _get_or_create_conda_env
    (_, stdout, _) = process.exec_cmd([conda_path, "env", "list", "--json"])
  File "/usr/local/lib/python3.6/dist-packages/mlflow/utils/process.py", line 48, in exec_cmd
    (exit_code, stdout, stderr))
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1

STDOUT:


STDERR:ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.


2019/04/18 11:22:13 ERROR mlflow.cli: === Run (ID '0d1aea0835dd4c838b03f8f1dc68af92') failed ===
```

### Analysis

I noticed that the `main.py` called the `mlflow.run()` for dealing sub tasks, but it does not use the param `use_conda` which default value is `True`.

```
  File "main.py", line 63, in _get_or_run
     submitted_run = mlflow.run(".", entrypoint, parameters=parameters)
```

Then, I try to change it with fixed param  `use_conda=False`, the project can run now.

```
  File "main.py", line 63, in _get_or_run
     submitted_run = mlflow.run(".", entrypoint, parameters=parameters, use_conda=False)
```

**The best solution is passing the params (like --no-conda) to the mlflow.run() function.**

While, I checked the `active_run.info`,  it's not there.

Please fix the example to support running with `--no-conda`.

Thanks!

**Comment by dorukhansergin** [comment]
+1. 
I encountered the same problem. Same system information except for the following.

**System information**
**OS Platform and Distribution:** Ubuntu 16.04
MLflow installed from : pip install inside another conda environment
**Python version:** 3.7.3

**Comment by HwangJohn** [comment]
+1

System information
OS Platform and Distribution: Mac OS 10.14.5
MLflow installed from : pip install mlflow
Python version: 3.6.5
