### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pytorch_lightning' (related to 'pytorch-lightning' renaming imports, discovery to 'lightning.pytorch')

### ISSUE THREAD

**Issue by DouglasKrouth** [mlflow/mlflow#11364]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.9.2
- Tracking server: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: Python 3.11.7
- **yarn version, if running the dev UI**: N/A

### Describe the problem

MLflow is using the "wrong" import for pytorch_lightning `import pytorch_lightning ...` which is being actively deprecated by Lightning.ai, new usage should be `import lighting.pytorch ...`. This is a bit of a goofy problem as `pytorch-lightning` is still an available index on PyPI (as of _pytorch-lightning / lightning_ version 2.2.1) and both packages maintain the same API outside of the naming change.

**Initial solution suggestion:**
1. Make a shim module to intercept mlflow import, apply the correct import path for whatever is currently installed (either `pytorch-lightning` or `lightning`).
2. Include a warning if user's env has `pytorch-lightning` installed with recommendation to update to `lightning`.
3. Come up with a plan to deprecate `pytorch-lightning` usage in future releases
---
**Relevant GitHub issues**
1. [Mention on Lightning-AI/pytorch-lightning](https://github.com/Lightning-AI/pytorch-lightning/discussions/16688)
2. [Old issue (~2 years) related to mlflow lightning dependency](https://github.com/mlflow/mlflow/issues/7285)

### Tracking information

N/A

### Code to reproduce issue

```
import logging
import sys
from typing import Any, Dict, Union

import lightning.pytorch as pl
import mlflow
from lightning import LightningDataModule, LightningModule
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.cli import LightningArgumentParser, LightningCLI
from ray.train import ScalingConfig
from ray.train.lightning import (RayDDPStrategy, RayFSDPStrategy,
                                 RayLightningEnvironment,
                                 RayTrainReportCallback, prepare_trainer)
from ray.train.torch import TorchTrainer

def main():
...
    if mlflow_config is not None:
        mlflow.set_tracking_uri(mlflow_config.get("tracking_uri"))
        mlflow.set_experiment(mlflow_config.get("experiment_name"))
        with mlflow.start_run(
            run_id=mlflow_config.get("run_id"),
            description=mlflow_config.get("run_description"),
        ) as run:
            mlflow.set_tags(mlflow_config.get("tags"))
            mlflow.log_artifact(mlflow_config.get("config_file_path"))
            
        # set up training function config
        train_func_config = {
            "model": cli.model,
            "datamodule": cli.datamodule,
            "trainer": cli.trainer,
        }

        # Configure scaling and resource requirements.
        scaling_config = ScalingConfig(
            num_workers=1,
            use_gpu=True,
            trainer_resources={"cpu": 0}
        )
        ray_trainer = TorchTrainer(
            train_loop_per_worker=train_func,
            train_loop_config=train_func_config,
            scaling_config=scaling_config,
        )
        # Calls mlflow logging here
        mlflow.pytorch.autolog()
        result = ray_trainer.fit()
        mlflow.end_run()

```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
2024/03/07 12:27:56 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of pytorch. If you encounter errors during autologging, try upgrading / downgrading pytorch to a supported version, or try upgrading MLflow.
Traceback (most recent call last):
  File "/tmp/ray/session_2024-03-07_12-26-25_704272_8/runtime_resources/working_dir_files/_ray_pkg_285a67e3a166a7a7/deepcdl/scripts/training/krouth_ray_train.py", line 279, in <module>
    main()
  File "/tmp/ray/session_2024-03-07_12-26-25_704272_8/runtime_resources/working_dir_files/_ray_pkg_285a67e3a166a7a7/<PROJECT>/scripts/training/<SCRIPT>.py", line 204, in main
    mlflow.pytorch.autolog()
  File "/home/ray/anaconda3/envs/<PROJECT>/lib/python3.11/site-packages/mlflow/utils/autologging_utils/__init__.py", line 424, in autolog
    return _autolog(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/envs/<PROJECT>/lib/python3.11/site-packages/mlflow/pytorch/__init__.py", line 1049, in autolog
    from mlflow.pytorch._lightning_autolog import patched_fit
  File "/home/ray/anaconda3/envs/<PROJECT>/lib/python3.11/site-packages/mlflow/pytorch/_lightning_autolog.py", line 23, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@DouglasKrouth Thanks for reporting this issue! Actually we've updated the dependency in extra-ml-requirements.txt file to use lightning instead of pytorch_lightning, but haven't updated it _lightning_autolog.py file. I think we need some import catch logic that try to import lightning first, it we get importError then delegate to pytorch_lightning for backwards compatibility. Please feel free to file a PR and I'll help review it!

**Comment by DouglasKrouth** [comment]
@serena-ruan opened a PR here :smile: 

https://github.com/mlflow/mlflow/pull/11372
