### ISSUE TITLE
[BUG]Fail to download artifact when load models

### ISSUE THREAD

**Issue by SarahWei0804** [mlflow/mlflow#11499]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.11.2
- Tracking server: 2.11.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux x86_64
- **Python version**:3.9.18
- **yarn version, if running the dev UI**:

### Describe the problem

I've created an experiment and I try to load_model from the remote server. It failed to download artifacts even if I load_model locally.

I've seen the prbloem similar to [mine](https://github.com/mlflow/mlflow/issues/10919), but it doesn't fix the problem.
### Tracking information

I start up a MLFlow server with:
`mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns.db`

### Code to reproduce issue

For the client side, I send API request to get the models by the run_id.

```
import mlflow

remote_server_uri = "http://xxxxxxx:5000"
mlflow.set_tracking_uri(remote_server_uri)
os.environ['MLFLOW_TRACKING_URI'] = remote_server_uri

logged_model = 'runs:/9160dbf5c23a4b8f9bedf3f9dbea9e07/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)
print(loaded_model.predict(pd.DataFrame(data)))
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/router/XGBoost/prediction.py", line 86, in <module>
    loaded_model = mlflow.pyfunc.load_model(logged_model)
  File "/home/router/miniconda3/envs/citadel/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 828, in load_model
    local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "/home/router/miniconda3/envs/citadel/lib/python3.9/site-packages/mlflow/tracking/artifact_utils.py", line 105, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/home/router/miniconda3/envs/citadel/lib/python3.9/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 131, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
  File "/home/router/miniconda3/envs/citadel/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repo.py", line 230, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from http://xxxxx:5000/api/2.0/mlflow-artifacts/artifacts/890206080438747679/9160dbf5c23a4b8f9bedf3f9dbea9e07/artifacts:
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by SarahWei0804** [comment]
I've already found the issue, the command line to start the server should add `--serve-artifacts` argument.
