### ISSUE TITLE
[FR]Model registery in .pt extension

### ISSUE THREAD

**Issue by subbiah-cape** [mlflow/mlflow#11587]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Hi, when I register a PyTorch model, it automatically saves with a .pth extension. Could you suggest adding a feature to save the logged model with a .pt extension? I am using the YOLOv8 model, and when I log the model, it saves with a .pth extension. However, I am unable to load that model in score.py while performing inference.

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@subbiah-cape What blocks you from loading the model saved with `.pth` in your `score.py`? As far as I know, there is no difference between `.pt` and `.pth` extension, Pytorch uses a single serialization format.

**Comment by subbiah-cape** [comment]
So far, I have been using YOLOv8x-seg for segmentation. Once the training is completed, the framework itself saves the best model in a .pt extension. However, when registering the model in MLflow, it saves it with a .pth extension, and I was unable to load that model in YOLO. Is there any other feature to save the model in a .pt extension? Additionally, I have separately loaded the registered model, but I was unable to load it, and the parameters that I have been using in yolov8x-seg.pt are not supported here.

**Comment by B-Step62** [comment]
@subbiah-cape Could you share what is the error shown when loading the `pth` file, and any code to reproduce the issue"?

The extension should do nothing ([ref](https://discuss.pytorch.org/t/difference-between-saving-a-tensor-via-pt-and-pth/30780/4)) for the saving format, so if model is saved normally, you should be able to load the model (or by just renaming to `.pt` if YOLO validates extension).

> the parameters that I have been using in yolov8x-seg.pt are not supported here

What parameter is not supported?

**Comment by MohamedKHALILRouissi** [comment]
i have the same issue here i trained model then logged it using mlflow.pytorch.log_model() , the train.py script of ultralytics generate best.pt and last.pt 

this is the modified script of mlflow.py integration
trainer.model point to the model 
```
def on_train_end(trainer):
    """Log model artifacts at the end of the training."""
    if not mlflow:
        return
    # mlflow.log_artifact(str(trainer.best.parent))  # log save_dir/weights directory with best.pt and last.pt
    mlflow.pytorch.log_model(trainer.model,"model")
    for f in trainer.save_dir.glob("*"):  # log all other files in save_dir
        if f.suffix in {".png", ".jpg", ".csv", ".pt", ".yaml"}:
            mlflow.log_artifact(str(f))
    keep_run_active = os.environ.get("MLFLOW_KEEP_RUN_ACTIVE", "False").lower() == "true"
    if keep_run_active:
        LOGGER.info(f"{PREFIX}mlflow run still alive, remember to close it using mlflow.end_run()")
    else:
        mlflow.end_run()
        LOGGER.debug(f"{PREFIX}mlflow run ended")

    LOGGER.info(
        f"{PREFIX}results logged to {mlflow.get_tracking_uri()}\n{PREFIX}disable with 'yolo settings mlflow=False'"
    )
```

after that i get model stored in 
![image](https://github.com/user-attachments/assets/252c21a8-4219-4808-af9f-3e902b37ed1a)

when i run the model by changing the format from pth to pt i doesnt work

**Comment by MohamedKHALILRouissi** [comment]
WARNING ⚠️ The file 'model/model.pt' appears to be improperly saved or formatted. For optimal results, use model.save('filename.pt') to correctly save YOLO models.
Traceback (most recent call last):
  File "/home/khalil/itona-trainer-executor/test/inference_test.py", line 31, in <module>
    results = model(img)
  File "/home/khalil/itona-trainer-executor/core/logic/ultralytics/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/khalil/itona-trainer-executor/core/logic/ultralytics/ultralytics/engine/model.py", line 560, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/khalil/itona-trainer-executor/core/logic/ultralytics/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
  File "/home/khalil/itona-trainer-executor/runpodvenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/khalil/itona-trainer-executor/core/logic/ultralytics/ultralytics/nn/autobackend.py", line 144, in __init__
    model = model.fuse(verbose=verbose)
  File "/home/khalil/itona-trainer-executor/runpodvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Sequential' object has no attribute 'fuse'

**Comment by tranvangaohd1994** [comment]
I have a tip 
+ download model .pth by client_mlflow.download_artifact()
+ change name model.pth to model.pt by os.rename
+ model = YOLO('model.pt')
It loaded and run ok
