### ISSUE TITLE
[SETUP-BUG] endpoint  deployment 7000, get_deploy_client() return  endpoint_url 

### ISSUE THREAD

**Issue by LazyCatLee** [mlflow/mlflow#11641]
### System information

(base) master@ubuntu:~$ mlflow doctor
System information: Linux #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023
Python version: 3.11.5
MLflow version: 2.11.3
MLflow module location: /home/master/anaconda3/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: file:///home/master/mlruns
Registry URI: file:///home/master/mlruns
MLflow dependencies: 
  Flask: 2.2.2
  Jinja2: 3.1.2
  aiohttp: 3.9.3
  alembic: 1.13.1
  boto3: 1.34.72
  botocore: 1.34.72
  click: 8.1.7
  cloudpickle: 2.2.1
  docker: 7.0.0
  entrypoints: 0.4
  fastapi: 0.109.0
  gitpython: 3.1.42
  graphene: 3.3
  gunicorn: 21.2.0
  importlib-metadata: 6.0.0
  markdown: 3.4.1
  matplotlib: 3.7.2
  numpy: 1.24.3
  packaging: 23.2
  pandas: 2.0.3
  protobuf: 4.25.3
  pyarrow: 15.0.0
  pydantic: 1.10.11
  pytz: 2023.3.post1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.0
  scipy: 1.11.1
  slowapi: 0.1.9
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
  tiktoken: 0.5.2
  uvicorn: 0.23.1
  virtualenv: 20.25.1
  watchfiles: 0.21.0

### Code to reproduce issue

from mlflow.deployments import get_deploy_client

client = get_deploy_client("http://127.0.0.1:7000")
print(client.list_endpoints())

name = "chat"

endpoint = client.get_endpoint("chat")
print(endpoint)

data = dict({
    "temperature": 5,
    "n": 1,
    "max_tokens": 500,
    "stream": True,
    "messages": [
        {
            "role": "user",
            "content": "Which harry potter house am I most likely to belong to?"
        }
    ]
})
response = client.predict(endpoint=name, inputs=data)
print(resp

### Describe the problem

get_deploy_client() return  endpoint_url  not the same as client.predict url

### Other info / logs

[Endpoint(name='completions', endpoint_type='llm/v1/completions', model=RouteModelInfo(name='gpt-3.5-turbo', provider='openai'), endpoint_url='http://127.0.0.1:7000/gateway/completions/invocations', limit=Limit(calls=10, key=None, renewal_period='minute')), Endpoint(name='chat', endpoint_type='llm/v1/chat', model=RouteModelInfo(name='gpt-3.5-turbo', provider='openai'), endpoint_url='http://127.0.0.1:7000/gateway/chat/invocations', limit=None), Endpoint(name='embeddings', endpoint_type='llm/v1/embeddings', model=RouteModelInfo(name='text-embedding-ada-002', provider='openai'), endpoint_url='http://127.0.0.1:7000/gateway/embeddings/invocations', limit=None)]
name='chat' endpoint_type='llm/v1/chat' model=RouteModelInfo(name='gpt-3.5-turbo', provider='openai') endpoint_url='http://127.0.0.1:7000/gateway/chat/invocations' limit=None
Traceback (most recent call last):
  File "/home/master/mlflow/mlflow/utils/request_utils.py", line 63, in augmented_raise_for_status
    response.raise_for_status()
  File "/home/master/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: http://127.0.0.1:7000/endpoints/chat/invocations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/master/mlflow/tests/openai_test3.py", line 47, in <module>
    response = client.predict(endpoint=name, inputs=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master/mlflow/mlflow/deployments/mlflow/__init__.py", line 305, in predict
    return self._call_endpoint(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/master/mlflow/mlflow/deployments/mlflow/__init__.py", line 141, in _call_endpoint
    augmented_raise_for_status(response)
  File "/home/master/mlflow/mlflow/utils/request_utils.py", line 66, in augmented_raise_for_status
    raise HTTPError(
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: http://127.0.0.1:7000/endpoints/chat/invocations. Response text: {"detail":[{"loc":["body","temperature"],"msg":"ensure this value is less than or equal to 2","type":"value_error.number.not_le","ctx":{"limit_value":2}}]}

**Comment by harupy** [comment]
@LazyCatLee Can you try a smaller `temperature` like `1`?

**Comment by LazyCatLee** [comment]
> @LazyCatLee Can you try a smaller `temperature` like `1`?
yeah,  I have set the temperature 1 ,but ERROR like this:

data = dict({
    "temperature": 1,
    "n": 1,
    "max_tokens": 500,
    "stream": True,
    "messages": [
        {
            "role": "user",
            "content": "Which harry potter house am I most likely to belong to?"
        }
    ]
})

Running Result:

  File "/home/master/mlflow/mlflow/utils/rest_utils.py", line 141, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:7000/endpoints/chat/invocations failed with exception Response ended prematurely


MlflowException: API request to  http://127.0.0.1:7000/endpoints/chat/invocations
but endpoint_url='http://127.0.0.1:7000/gateway/chat/invocations' 
this si why

**Comment by LazyCatLee** [comment]
@harupy  

yeah, I have set the temperature 1 ,but ERROR like this:

data = dict({
"temperature": 1,
"n": 1,
"max_tokens": 500,
"stream": True,
"messages": [
{
"role": "user",
"content": "Which harry potter house am I most likely to belong to?"
}
]
})

Running Result:

File "/home/master/mlflow/mlflow/utils/rest_utils.py", line 141, in http_request
raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:7000/endpoints/chat/invocations failed with exception Response ended prematurely

MlflowException: API request to http://127.0.0.1:7000/endpoints/chat/invocations
but endpoint_url='http://127.0.0.1:7000/gateway/chat/invocations'
this why

**Comment by harupy** [comment]
@LazyCatLee did you get the same error or a different one?
