### ISSUE TITLE
Type error in in module mlflow/entities/run_info.py, line 150 on mlflow server run

### ISSUE THREAD

**Issue by MeisterUrian** [mlflow/mlflow#1166]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**: 3.7.3
- **npm version (if running the dev UI):
- **Exact command to reproduce**: 
1. run mlflow server:
```bash
mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
```
2. run sample code:
```python
import mlflow

mlflow.set_experiment('myexp')

with mlflow.start_run():
    mlflow.log_param('a', 1)
    mlflow.log_metric('b', 2)

    with open('artifact.txt', 'w') as f:
        f.write('artifact')
    
    mlflow.log_artifact('artifact.txt')
```

### Describe the problem
Type error in module __mlflow/entities/run_info.py__, line 150.

#### Possible solution
This change (method RunInfo.to_proto())  avoids problem:
change
```python 
proto.experiment_id = self.experiment_id
```
to 
```python 
proto.experiment_id = str(self.experiment_id)
```

Cause of problem: probably field __experiment_id__  of proto requires string or bytes value, but the same name field in SQLite database has type INTEGER.

### Source code / logs
```bash
ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 272, in _get_run
    response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
  File "/usr/local/lib/python3.7/site-packages/mlflow/entities/run.py", line 38, in to_proto
    run.info.MergeFrom(self.info.to_proto())
  File "/usr/local/lib/python3.7/site-packages/mlflow/entities/run_info.py", line 150, in to_proto
    proto.experiment_id = self.experiment_id
TypeError: 1 has type int, but expected one of: bytes, unicode
[2019-04-24 21:15:41,842] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 209, in _update_run
    response_message = UpdateRun.Response(run_info=updated_info.to_proto())
  File "/usr/local/lib/python3.7/site-packages/mlflow/entities/run_info.py", line 150, in to_proto
    proto.experiment_id = self.experiment_id
TypeError: 1 has type int, but expected one of: bytes, unicode
[2019-04-24 21:15:42,528] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 209, in _update_run
    response_message = UpdateRun.Response(run_info=updated_info.to_proto())
  File "/usr/local/lib/python3.7/site-packages/mlflow/entities/run_info.py", line 150, in to_proto
    proto.experiment_id = self.experiment_id
TypeError: 1 has type int, but expected one of: bytes, unicode
```

Thanks for your attention.

**Comment by drewmcdonald** [comment]
Seems to be the same underlying problem as #1165

**Comment by wilderrodrigues** [comment]
Hi there,

I have the same issue, but when logging parameters from a dictionary.

```
mlflow.log_params(parameters)
```

It fails with a dictionary like this:

```
hyper_parameters = {'backend': 'tensorflow', 'backend_version': tf_version, 'batch_size': batch_size, 'num_epochs': num_epochs}
``
`

It only works is a cast the integers to string. For instance, `str(batch_size)` will work fine.

The error is the same as reported here.

```
/usr/local/lib/python3.6/dist-packages/mlflow/entities/param.py in to_proto(self)
     25         param = ProtoParam()
     26         param.key = self.key
---> 27         param.value = self.value
     28         return param
     29 
TypeError: 128 has type int, but expected one of: bytes, unicode
```

**Comment by jmrr** [comment]
I also experience this error when adding tags integer to a run:

```
  File "/home/jose/projects/lpr/.venv/lib/python3.6/site-packages/mlflow/entities/run_tag.py", line 30, in to_proto                                                                                    
    param.value = self.value                                                                                                                                                                                
TypeError: 2 has type int, but expected one of: bytes, unicode  
```

when I run `create_run` as:

```
create_run(experiment_id, start_time=None, tags={"source_type": 2})
```
