### ISSUE TITLE
[BUG] OpenAI flavor `api_request_parallel_processor.py` marks requests as failed due to unavailable TPM capacity

### ISSUE THREAD

**Issue by pb-martins** [mlflow/mlflow#11694]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.11.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 14.4.1 (23E224)
- **Python version**: 3.10.14

### Describe the problem

When running model predictions using any OpenAI flavour on large enough dataset, most of the rows will return an `MLflowException` due to surpassing the maximum number of available token per minute quota in `mlflow.openai.api_request_parallel_processor`.

`mlflow.openai. _OpenAIApiConfig` defines the maximum number of tokens per minute (TPM) that can be used by the `mlflow.openai.api_request_parallel_processor.process_api_requests` method. 

I have found two issues on `mlflow.openai.api_request_parallel_processor.process_api_requests`:

* If we use a large enough dataset whose sum of all tokens is way bigger than the available maximum capacity, there are rows that will be set to failed and launch an exception, as their token usage is always superior to the current available capacity (see [here](https://github.com/mlflow/mlflow/blob/fc858460b719be7c1dfec414b5219533a3424455/mlflow/openai/api_request_parallel_processor.py#L298-L320)).
  The just mentioned if condition also leads to unwanted behaviour. Currently this is defined as: if the current request token usage is larger than the current available TPM capacity, set the request as failed, i.e., launch an exception. The proposed solution would only set the request to failed if the request token usage is larger the maximum TPM quota. Otherwise, if there isn't available capacity at given point in time, run the loop again until there is capacity.
* Regarding `mlflow.openai. _OpenAIApiConfig. max_tokens_per_minute`, I suggest to also read this value from an environment variable, similarly to `api_type = os.getenv(_OpenAIEnvVar.OPENAI_API_TYPE.value, openai.api_type)`. Currently, Mlflow defines the maximum possible quotas (e.g., 60000 for AzureOpenAI). However, for custom deployments such as `AzureOpenAI` deployments, this quota limit might be considerably lower, thus the ability to customise this parameter.
  Moreover, if this value is not customisable, if we consider a quota large enough to generate a lot of retry actions, they might timeout after 10 minutes, due to the amount of request in the retry queue.
  Another consideration to take into account is that, if we provide this customisability, we will need to refactor slightly the loop in `mlflow.openai.api_request_parallel_processor.process_api_requests`. The loop is running every 1 ms (defined by `time.sleep(0.001)`), yet we are casting the available TPM and request per minute (RPM) capacity differences to integers. Given the small interval, this sum operation is basically invalid if the maximum TPM is under 60000, as the computed value will always be close 0, thus summing 0 to the available capacity (see [here](https://github.com/mlflow/mlflow/blob/fc858460b719be7c1dfec414b5219533a3424455/mlflow/openai/api_request_parallel_processor.py#L280-L292)). If we did not cast the value, the quota would be a float, but it would gradually increase over time, until reaching the maximum defined TPM and RPM. 

### Tracking information

```shell
```

### Code to reproduce issue

```python
import os

import mlflow
import openai
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

# You need your own deployment keys for the code to run.

os.environ["OPENAI_API_KEY"] = os.environ.get("AZURE_OPENAI_API_KEY")
os.environ["OPENAI_API_BASE"] = os.environ.get("AZURE_OPENAI_ENDPOINT")
os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
os.environ["OPENAI_API_TYPE"] = "azure"
openai.api_type = "azure"

prompt = """
Compose a well-researched and analytical essay on the impact of climate change on global ecosystems and biodiversity. Your essay should include an in-depth examination of the role that human activities play in accelerating climate change, leading to the loss of biodiversity and the destabilization of ecosystems. Discuss the potential consequences of these changes, including habitat loss, species extinction, and disruptions to ecosystem services. Additionally, explore the interconnectedness of biodiversity and climate change, examining how preserving biodiversity can contribute to climate change mitigation and adaptation efforts. Incorporate relevant scientific data, case studies, and examples from different regions of the world to support your arguments. Propose potential solutions and strategies for addressing the impacts of climate change on ecosystems and biodiversity, considering the importance of international collaboration and policy interventions in promoting sustainable solutions. Finally, analyze the ethical, economic, and social implications of addressing these challenges, and present a compelling case for the urgency of taking action to protect global ecosystems and biodiversity in the face of climate change.
Use a maximum of 40 words.
"""

logged_model = mlflow.openai.log_model(
    model="gpt-4-1106-Preview",
    task=openai.chat.completions,
    artifact_path="model",
    messages=[
        {"role": "user", "content": prompt},
    ],
    temperature=0.0,
)

model = mlflow.pyfunc.load_model(logged_model.model_uri)

df = pd.DataFrame([prompt] * 10_000, columns=["prompt"])
model.predict(df)

```

### Stack trace

```
Traceback (most recent call last):
  File "/home/user/mlflow/test.py", line 35, in <module>
    model.predict(df)
  File "/home/user/mlflow/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 681, in predict
    return self._predict_fn(data, params=params)
  File "/home/user/mlflow/lib/python3.10/site-packages/mlflow/openai/__init__.py", line 809, in predict
    return self._predict_chat(data, params or {})
  File "/home/user/mlflow/lib/python3.10/site-packages/mlflow/openai/__init__.py", line 730, in _predict_chat
    results = process_api_requests(
  File "/home/user/mlflow/lib/python3.10/site-packages/mlflow/openai/api_request_parallel_processor.py", line 349, in process_api_requests
    raise mlflow.MlflowException(
mlflow.exceptions.MlflowException: 9953 tasks failed. See logs for details.
```

### Other info / logs

I have added debug logic to if-else statement in the for loop to check which request failed.

```
...
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3725 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3726 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3727 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3728 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3729 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3730 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3731 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3732 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3733 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3734 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3735 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3736 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3737 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3738 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3739 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3740 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3741 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3742 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3743 set to failed.
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #3744 set to failed.
^C2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #4 succeeded
2024/04/12 12:15:26 DEBUG mlflow.openai.api_request_parallel_processor: Request #15 started
2024/04/12 12:15:27 DEBUG mlflow.openai.api_request_parallel_processor: Request #5 succeeded
2024/04/12 12:15:27 DEBUG mlflow.openai.api_request_parallel_processor: Request #16 started
2024/04/12 12:15:30 DEBUG mlflow.openai.api_request_parallel_processor: Request #14 succeeded
2024/04/12 12:15:30 DEBUG mlflow.openai.api_request_parallel_processor: Request #17 started
2024/04/12 12:15:30 DEBUG mlflow.openai.api_request_parallel_processor: Request #10 succeeded
...
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Proposal TLDR:
1. Update next_request handling -- we only fail when `next_request_tokens>max_tokens_per_minute`, and wait instead if `next_request_tokens>available_token_capacity` until the capacity matches.
2. Read `max_tokens_per_minute` from env vars.

Thanks for raising this issue, this makes sense to me. We'll discuss internally and get back to you!
