### ISSUE TITLE
running into an error while running mlflow run . [SETUP-BUG]

### ISSUE THREAD

**Issue by lautarortega** [mlflow/mlflow#11697]
### System information

- **MacOS Sonoma v14.0**:
- **MLflow installed from (source or binary)**:
- **MLflow version 2.11.3**:
- **Python 3.11.4**:

### Code to reproduce issue

Within the multistep_workflow directory running:
`mlflow run .`

### Describe the problem

I think it might be related to pyenv and pyenv-virtualenvs.
I first created a virtualenv where I installed mlflow. 
I thought there could had been some issues with that so I did:
`pyenv deactivate`

### Other info / logs

```
lautaroortegacarati@Air-de-Lautaro multistep_workflow % mlflow run .      
2024/04/12 21:16:32 INFO mlflow.utils.virtualenv: Installing python 3.8.19 if it does not exist
2024/04/12 21:16:32 INFO mlflow.utils.virtualenv: Creating a new environment in /Users/lautaroortegacarati/.mlflow/envs/mlflow-30321ac57d98d5da42d5ee318e7a4ec7af1aa401 with /Users/lautaroortegacarati/.pyenv/versions/3.8.19/bin/python
created virtual environment CPython3.8.19.final.0-64 in 338ms
  creator CPython3Posix(dest=/Users/lautaroortegacarati/.mlflow/envs/mlflow-30321ac57d98d5da42d5ee318e7a4ec7af1aa401, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/lautaroortegacarati/Library/Application Support/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.0.0, wheel==0.41.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
2024/04/12 21:16:32 INFO mlflow.utils.virtualenv: Installing dependencies

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.2 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1)
ERROR: No matching distribution found for tensorflow==1.15.2

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
2024/04/12 21:16:33 WARNING mlflow.utils.virtualenv: Encountered an unexpected error: ShellCommandException("Non-zero exit code: 1\nCommand: ['bash', '-c', 'source /Users/lautaroortegacarati/.mlflow/envs/mlflow-30321ac57d98d5da42d5ee318e7a4ec7af1aa401/bin/activate && python -m pip install --quiet -r requirements.ac5a4418171540d88e4c72e5bcee203e.txt']") while creating a virtualenv environment in /Users/lautaroortegacarati/.mlflow/envs/mlflow-30321ac57d98d5da42d5ee318e7a4ec7af1aa401, removing the environment directory...
Traceback (most recent call last):
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/bin/mlflow", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/cli.py", line 203, in run
    projects.run(
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/projects/__init__.py", line 344, in run
    submitted_run_obj = _run(
                        ^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/projects/__init__.py", line 109, in _run
    submitted_run = backend.run(
                    ^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/projects/backend/local.py", line 164, in run
    activate_cmd = _create_virtualenv(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/utils/virtualenv.py", line 288, in _create_virtualenv
    _exec_cmd(cmd, capture_output=capture_output, cwd=tmpdir, extra_env=extra_env)
  File "/Users/lautaroortegacarati/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mlflow/utils/process.py", line 120, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['bash', '-c', 'source /Users/lautaroortegacarati/.mlflow/envs/mlflow-30321ac57d98d5da42d5ee318e7a4ec7af1aa401/bin/activate && python -m pip install --quiet -r requirements.ac5a4418171540d88e4c72e5bcee203e.txt']
```

**Comment by maishathasin** [comment]
it looks like tensorflow 1.15.2 is not available for your python version, you can try to downgrade your python version to 3.7 , by doing ``` pyenv install 3.7```

**Comment by lautarortega** [comment]
python: "3.8"
build_dependencies:
  - pip
dependencies:
  - tensorflow==1.15.2
  - keras==2.2.4
  - mlflow>=1.0
  - pyspark
  - requests
  - click

These are the packages mlflow is trying to install for this project. I tried running mlflow run . while using python 3.8 and I got the same error. I am getting an error while trying to install mlflow in python 3.7.

**Comment by serena-ruan** [comment]
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.2 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1)
ERROR: No matching distribution found for tensorflow==1.15.2`
Are you able to directly install `tensorflow==1.15.2` in your local pyenv?

**Comment by serena-ruan** [comment]
@lautarortega tensorflow 1.15.2 sounds super old, could you try upgrading the dependency in python_env.yaml file and test? I think the minimum version we support is 2.6.5 now :)
