### ISSUE TITLE
[BUG] env-manager not recognising local

### ISSUE THREAD

**Issue by dean-n** [mlflow/mlflow#11849]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.12.1
- Tracking server: 2.11.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: debian:11-slim
- **Python version**: 3.10.14
- **yarn version, if running the dev UI**: n/a

### Describe the problem

I've been unable to get MLFlow in my container to run without trying to create it's own environment using `--env-manager local`.

The exact error I'm getting is:

```
root@my-mlflow-training:/app# mlflow run . --experiment-name My-Mlflow-Training --run-name test --env-manager=local
2024/04/29 11:28:41 INFO mlflow.projects.utils: === Created directory /tmp/tmpvpwrf5gp for downloading remote URIs passed to arguments of type 'path' ===
2024/04/29 11:28:41 INFO mlflow.projects.backend.local: === Running command 'python ./workflow/main.py' in run with ID 'dd365095f9684085bd0d537ea042d6d9' ===
Launching 'generate_data' run...
2024/04/29 11:28:43 INFO mlflow.utils.virtualenv: Installing python 3.10.14 if it does not exist
Traceback (most recent call last):
  File "/app/./workflow/main.py", line 33, in <module>
    workflow()
  File "/app/./workflow/main.py", line 16, in workflow
    generate_data_run = mlflow.projects.run(uri = ".", entry_point= "generate_data", parameters={}, run_name="Generate Data")
  File "/usr/local/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 344, in run
    submitted_run_obj = _run(
  File "/usr/local/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 109, in _run
    submitted_run = backend.run(
  File "/usr/local/lib/python3.10/site-packages/mlflow/projects/backend/local.py", line 161, in run
    python_bin_path = _install_python(python_env.python, pyenv_root=pyenv_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/virtualenv.py", line 138, in _install_python
    _exec_cmd(
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/process.py", line 98, in _exec_cmd
    process = subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv'
2024/04/29 11:28:44 ERROR mlflow.cli: === Run (ID 'dd365095f9684085bd0d537ea042d6d9') failed ===
```

However, I have this version of python installed in my container.

```
root@example-mlflow-training:/app# python3
Python 3.10.14 (main, Apr 24 2024, 12:45:30) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlflow
>>>
```

And I'm creating my container with the following Dockerfile:
```
FROM python:3.10.14-bullseye

WORKDIR /app
COPY . .
ADD requirements.txt .

RUN pip install -r requirements.txt

RUN pip freeze > requirements.txt

...
```

This is what's in my MLProject file:
```
root@example-mlflow-training:/app# cat MLProject
name: apple_sales_forecasting
entry_points:
  generate_data:
    command: "python ./workflow/generate_data.py"

  train_model:
    command: "python ./workflow/train_model.py"
    dependencies:
      - data/sales_data.csv

  main:
    command: "python ./workflow/main.py"
```

Do I need to install pyenv into my container regardless even though I want to use my local installation of python? My container will not have internet access, so I need to do the setup during the image build. If yes, should this be added to the docs? Apologies in advance if I've missed something.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dean-n** [comment]
Closing, didn't realise you had to specify the env_manager args in the .run
