### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by ctrado18** [mlflow/mlflow#1193]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``master --version``)**:
- **Python version**:  3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

I installed latest master via pip install mlflow

I am in a conda environment and do:

python examples/quickstart/mlflow_tracking.py

and get the message:

```

Running mlflow_tracking.py
2019/05/03 17:57:16 WARNING mlflow.tracking.context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Traceback (most recent call last):
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\utils.py", line 245, in get_store
    store_builder = self._registry[scheme]
KeyError: 'c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/quickstart/mlflow_tracking.py", line 9, in <module>
    log_param("param1", randint(0, 100))
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\fluent.py", line 176, in log_param
    run_id = _get_or_start_run().info.run_uuid
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\fluent.py", line 296, in _get_or_start_run
    return start_run()
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\fluent.py", line 141, in start_run
    active_run_obj = MlflowClient().create_run(
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\client.py", line 35, in __init__
    self.store = utils._get_store(self.tracking_uri)
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\utils.py", line 272, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\\Anaconda3\lib\site-packages\mlflow\tracking\utils.py", line 250, in get_store
    store_uri, list(self._registry.keys())
mlflow.exceptions.MlflowException: Could not find a registered tracking store for: C:\Users\\mlflow-master\mlruns. Currently registered schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']




```

**Comment by pko89403** [comment]
help me

**Comment by lakshman2205** [comment]
For 'Failed to import Git' - Try downloading git , and adding git.exe to your Path
For 'Key Error' - Try setting tracking URI with registered scheme 'file' before run
mlflow.set_tracking_uri("file:/C:/Users/mlflow-masters/mlruns")

**Comment by enpinzolas** [comment]
Windows support isn't great yet. The problem about the key error here is that your path, `C:\Users\\mlflow-master\mlruns`, starts with ´C:´ and MLFlow thinks that is the storing scheme. 
To fix that, prefacing the path with `file://` might work, but I'm not sure.

**Comment by eedeleon** [comment]
This PR adds support for windows paths: https://github.com/mlflow/mlflow/pull/1171

**Comment by desaijairav** [comment]
I too am facing the same issue..
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
MLflow version (run master --version): 0.9.1
Python version: 3.7
I installed latest master via pip install mlflow

I am in command prompt at the path->
C:\Users\Username\mlflow\examples\quickstart>python mlflow_tracking.py 
and get the message:
I have attached the "mlflow_tracking" file with .txt extension instead of .py.
```

C:\Users\Username\mlflow\examples\quickstart>python mlflow_tracking.py
Running mlflow_tracking.py
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\utils.py", line 245, in get_store
    store_builder = self._registry[scheme]
KeyError: 'c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mlflow_tracking.py", line 9, in <module>
    log_param("param1", randint(0, 100))
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\fluent.py", line 176, in log_param
    run_id = _get_or_start_run().info.run_uuid
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\fluent.py", line 296, in _get_or_start_run
    return start_run()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\fluent.py", line 141, in start_run
    active_run_obj = MlflowClient().create_run(
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\client.py", line 35, in __init__
    self.store = utils._get_store(self.tracking_uri)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\utils.py", line 272, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\mlflow\tracking\utils.py", line 250, in get_store
    store_uri, list(self._registry.keys())
mlflow.exceptions.MlflowException: Could not find a registered tracking store for: **C:\Users\Username\mlflow\examples\quickstart\mlruns. Currently registered schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']**
[mlflow_tracking.txt](https://github.com/mlflow/mlflow/files/3222113/mlflow_tracking.txt)


```

**Comment by desaijairav** [comment]
> Windows support isn't great yet. The problem about the key error here is that your path, `C:\Users\\mlflow-master\mlruns`, starts with ´C:´ and MLFlow thinks that is the storing scheme.
> To fix that, prefacing the path with `file://` might work, but I'm not sure.

I tried these steps but no luck !!

**Comment by soicter** [comment]
@desaijairav  have you found a solution yet? I am facing the same problem :(

**Comment by mwoss** [comment]
@soicter My naive approach for fixing this bug (just for running examples) was settting scheme variable in _get_store_ function to `scheme = 'file'`. It works for running tutorial example, but I do not encourage using this for anything else.

**Comment by RajviMultani** [comment]
exactly same issue facing on windows10, python3.7

**Comment by pollyannaog** [comment]
Any updates? Facing the same issue here. Using Windows Server 2016.

**Comment by knjenga** [comment]
Any updates? I am still getting the error in August.

mlflow_log_metric("foo", 1)

Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlflow_1.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1      magrittr_1.5    lattice_0.20-38 R6_2.4.0        rlang_0.3.2     httr_1.4.0      tools_3.5.3     grid_3.5.3      withr_2.1.2    
[10] askpass_1.1     openssl_1.3     yaml_2.1.19     forge_0.2.0     processx_3.3.0  Matrix_1.2-15   ini_0.3.1       purrr_0.2.5     later_0.8.0    
[19] fs_1.2.7        base64enc_0.1-3 promises_1.0.1  ps_1.3.0        zeallot_0.1.0   compiler_3.5.3  swagger_3.9.2   reticulate_1.13 jsonlite_1.5   
[28] httpuv_1.5.0

**Comment by preyanshdwivedi** [comment]
> @soicter My naive approach for fixing this bug (just for running examples) was settting scheme variable in _get_store_ function to `scheme = 'file'`. It works for running tutorial example, but I do not encourage using this for anything else.

Hi,

Can you please help me by letting me know where can i find the function _get_store_ ?
