### ISSUE TITLE
[FR]MLflow Deployments Server Support inside corporate proxy

### ISSUE THREAD

**Issue by s-natsubori** [mlflow/mlflow#12069]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Deployments Server shoud be communicate with Cloud LLM(ex OpenAI)  from inside corporate proxy.

### Motivation

> #### What is the use case for this feature?
Case where cloud LLM and local model are evaluated using the same MLFlow

> #### Why is this use case valuable to support for MLflow users in general?
easily use MLFlow in more diverse environments.

> #### Why is this use case valuable to support for your project(s) or organization?
I want to use Deployments Server to evaluate Cloud LLM(ex OpenAI) and OSS Model serves localy.
My Model server placed inside corporate proxy, so I serve MLFlow  inside corporate proxy too.

> #### Why is it currently difficult to achieve this use case?
Deployments Server raise ClientConnectorError.

### Details

I try to setup Deployments Server with
- local served LLM Model  inside corporate proxy
- Azure OpenAI API
- Deployment server inside corporate proxy

It raise following Error

``` shell
api-1        | Traceback (most recent call last):
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
api-1        |     hosts = await self._resolve_host(host, port, traces=traces)
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
api-1        |     return await asyncio.shield(resolved_host_task)
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 917, in _resolve_host_with_throttle
api-1        |     addrs = await self._resolver.resolve(host, port, family=self._family)
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
api-1        |     infos = await self._loop.getaddrinfo(
api-1        |   File "uvloop/loop.pyx", line 1528, in getaddrinfo
api-1        | socket.gaierror: [Errno -5] No address associated with hostname
api-1        | 
api-1        | The above exception was the direct cause of the following exception:
api-1        | 
api-1        | Traceback (most recent call last):
api-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
api-1        |     result = await app(  # type: ignore[func-returns-value]
api-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
api-1        |     return await self.app(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
api-1        |     await super().__call__(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
api-1        |     await self.middleware_stack(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
api-1        |     raise exc
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
api-1        |     await self.app(scope, receive, _send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
api-1        |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
api-1        |     raise exc
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api-1        |     await app(scope, receive, sender)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
api-1        |     await self.middleware_stack(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
api-1        |     await route.handle(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
api-1        |     await self.app(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
api-1        |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
api-1        |     raise exc
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api-1        |     await app(scope, receive, sender)
api-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
api-1        |     response = await func(request)
api-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
api-1        |     raw_response = await run_endpoint_function(
api-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
api-1        |     return await dependant.call(**values)
api-1        |   File "/usr/local/lib/python3.10/site-packages/mlflow/deployments/server/app.py", line 90, in _chat
api-1        |     return await prov.chat(payload)
api-1        |   File "/usr/local/lib/python3.10/site-packages/mlflow/gateway/providers/openai.py", line 130, in chat
api-1        |     resp = await send_request(
api-1        |   File "/usr/local/lib/python3.10/site-packages/mlflow/gateway/providers/utils.py", line 39, in send_request
api-1        |     async with _aiohttp_post(headers, base_url, path, payload) as response:
api-1        |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
api-1        |     return await anext(self.gen)
api-1        |   File "/usr/local/lib/python3.10/site-packages/mlflow/gateway/providers/utils.py", line 17, in _aiohttp_post
api-1        |     async with session.post(url, json=payload, timeout=timeout) as response:
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1197, in __aenter__
api-1        |     self._resp = await self._coro
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
api-1        |     conn = await self._connector.connect(
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
api-1        |     proto = await self._create_connection(req, traces, timeout)
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
api-1        |     _, proto = await self._create_direct_connection(req, traces, timeout)
api-1        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
api-1        |     raise ClientConnectorError(req.connection_key, exc) from exc
api-1        | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host XXXXXXXXX.openai.azure.com:443 ssl:default [No address associated with hostname]
```

Set `http_proxy` and `https_proxy` as environment variables.
Also, my other scripts (langChain, openai-python, httpx, etc.) can communicate with the Azure OpenAI.
I can also use the `curl` command to debug.
However, this is not possible with MLFliow Deployments Server.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@s-natsubori Do you want to file a PR for your fix?

**Comment by s-natsubori** [comment]
@serena-ruan 
Looking at the stack trace, it seems that the cause of the error is aiohttp, but I'm not familiar with aiohttp, so I don't know how to control proxy and dns.

I usually use httpx, which also supports async requests and does not cause errors with proxy.
I think it would be a good idea to have someone with more knowledge correct the implementation.
