### ISSUE TITLE
CLI fails to create an experiment with a name as str

### ISSUE THREAD

**Issue by vfdev-5** [mlflow/mlflow#1216]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 8
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**:  3.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**: 
```
mlflow experiments create dataset_v0.1
``` 

### Describe the problem
Context:
I have a folder with MLProject file and I would like to launch a run with the command
```
# I do not want to log in the source folder
export MLFLOW_TRACKING_URI=/path/to/outputs
mlflow run . -P param=value
> mlflow.exceptions.MlflowException: Could not find experiment with ID 0
```
Okay, let's create an experiment:
```
mlflow experiments create dataset_v0.1
```
and the output is
```
Traceback (most recent call last):
  File "/home/jupyter/anaconda3/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jupyter/anaconda3/lib/python3.7/site-packages/mlflow/experiments.py", line 38, in create
    print("Created experiment '%s' with id %d" % (experiment_name, exp_id))
TypeError: %d format: a number is required, not str
```
However the help says:
```
$ mlflow experiments create --help
Usage: mlflow experiments create [OPTIONS] EXPERIMENT_NAME

  Create an experiment in the configured tracking server.

Options:
  -l, --artifact-location TEXT  Base location for runs to store artifact
                                results. Artifacts will be stored at
                                $artifact_location/$run_id/artifacts. See http
                                s://mlflow.org/docs/latest/tracking.html#where
                                -runs-get-recorded for more info on the
                                properties of artifact location. If no
                                location is provided, the tracking server will
                                pick a default.
  --help                        Show this message and exit.
```

**Comment by vfdev-5** [comment]
Seems like the problem is fixed in the master : https://github.com/mlflow/mlflow/blob/master/mlflow/experiments.py#L38
