### ISSUE TITLE
Tutorial fails with "meta.yaml does not exist"

### ISSUE THREAD

**Issue by k0pper** [mlflow/mlflow#1228]
### System information
- **OS Platform and Distribution**: macOS High Sierra 10.13.6 (17G5019)
- **MLflow installed from**: conda via `conda install -c conda-forge mlflow 
`
- **MLflow version**: 0.9.0.1
- **Python version**: 3.7.3
- **npm version**: 6.9.0

### Problem Description
I'm doing the tutorial from the [Mlflow documentation](https://www.mlflow.org/docs/latest/tutorial.html). I cloned the git repo mlflow/mlflow. When running the mlflow server via `mlflow ui` inside examples/sklearn_elasticnet_wine and afterwards running python example/sklearn_elasticnet_wine/train.py I get the some Errors.

examples/sklearn_elasticnet_wine
`$ mlflow ui`

```
/anaconda3/envs/deepspeechtest/lib/python3.7/site-packages/mlflow/utils/environment.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env = yaml.load(_conda_header)
[2019-05-09 10:51:07 +0200] [5023] [INFO] Starting gunicorn 19.9.0
[2019-05-09 10:51:07 +0200] [5023] [INFO] Listening at: http://127.0.0.1:5000 (5023)
[2019-05-09 10:51:07 +0200] [5023] [INFO] Using worker: sync
[2019-05-09 10:51:07 +0200] [5027] [INFO] Booting worker with pid: 5027
```
This seems to be fine. The UI is accessible at localhost:5000, but without any experiments.

examples/sklearn_elasticnet_wine
 `$ python train.py`
```
/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/utils/environment.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env = yaml.load(_conda_header)
2019/05/09 10:53:04 ERROR mlflow.utils.rest_utils: API request to http://localhost:5000/api/2.0/preview/mlflow/runs/create failed with code 500 != 200, retrying up to 2 more times. API response body: {"error_code": "INTERNAL_ERROR", "message": "Yaml file './mlruns/0/meta.yaml' does not exist."}
2019/05/09 10:53:07 ERROR mlflow.utils.rest_utils: API request to http://localhost:5000/api/2.0/preview/mlflow/runs/create failed with code 500 != 200, retrying up to 1 more times. API response body: {"error_code": "INTERNAL_ERROR", "message": "Yaml file './mlruns/0/meta.yaml' does not exist."}
2019/05/09 10:53:10 ERROR mlflow.utils.rest_utils: API request to http://localhost:5000/api/2.0/preview/mlflow/runs/create failed with code 500 != 200, retrying up to 0 more times. API response body: {"error_code": "INTERNAL_ERROR", "message": "Yaml file './mlruns/0/meta.yaml' does not exist."}
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    with mlflow.start_run():
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 142, in start_run
    tags=tags
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/tracking/client.py", line 83, in create_run
    source_version=source_version
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 156, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 64, in _call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 73, in http_request_safe
    response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
  File "/anaconda3/envs/mlflowenv/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 58, in http_request
    (url, retries))
mlflow.exceptions.MlflowException: API request to http://localhost:5000/api/2.0/preview/mlflow/runs/create failed to return code 200 after 3 tries
```

### My questions
* What is this meta.yaml file?
* Why is it saying it's missing, shouldnt it be already there, the only thing I did was cloning the repo.
* Why does the tutorial not specify that you have to set the tracking URI of mlflow to the one of the server (for me localhost:5000)
* How to fix the Issue, is there something I don't understand well?

Alex

**Comment by dbczumar** [comment]
@k0pper I tried reproducing the issue on the latest version of MLflow (1.1.0). I was unable to reproduce the behavior you've described. The UI is displaying example results successfully. Can you try again with MLflow 1.1.0 and let me know if this issue persists? I am going to mark it closed for now; please re-open it if this is still a problem.
