### ISSUE TITLE
[BUG] Generate Valid AWS Names for Models

### ISSUE THREAD

**Issue by nablabits** [mlflow/mlflow#12418]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.13.0

### System information

In CircleCI:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04 LTS
- **Python version**: 3.9.7

Locally:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04 LTS
- **Python version**: 3.9.7

### Describe the problem

I have hit an error —two independent times, one from circleci and another time from my local environment— when running `create_deploy` to a sagemaker endpoint as mlflow is trying to create a model in AWS with a random name that AWS does not quite like. This random name shouldn't end in `-` regarding the stacktrace. It's not a major issue as running again `create_deploy` usually works out, but it's kind of annoying.

It feels to me that [this folk](https://github.com/mlflow/mlflow/blob/2248511d5d86bbd751a0fea4241f78be7bc8f3c8/mlflow/sagemaker/__init__.py#L1384) is the one spoiling the party so I guess that just sanitizing the output should do the trick so I'm happy to give it a go unless people more knowledgeable of the platform advise otherwise.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

Due to the random nature of the function it's hard to reproduce but I guess that one can force the output of `_get_sagemaker_model_name` and try an upload to AWS. This will require having some experiment run in the server, an account in AWS and a valid ECR image. Assuming that all that is there, then it's *as simple* as calling `create_endpoint`:
```python
import os
from mlflow.deployments import get_deploy_client

config = {
    "execution_role_arn": os.getenv("AWS_SAGEMAKER_EXECUTION_ROLE_ARN"),
    "image_url": os.getenv("AWS_ECR_IMAGE"),
    "bucket_name": os.getenv("AWS_S3_ARTIFACT_BUCKET"),
    "instance_type": "ml.m5.large",
    "instance_count": 1,
    "synchronous": True,
}

region = os.getenv("AWS_REGION")
sagemaker = get_deploy_client(f"sagemaker:/{region}")

sagemaker.create_deployment(
    name="some_endpoint_with_a_meaningful_name",
    model_uri="some_model",
    flavor="python_function",
    config=config,
)
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/circleci/project/deploy.py", line 138, in <module>
    callable_(env=REMOTE)
  File "/home/circleci/project/deploy.py", line 113, in __call__
    self._deploy()
  File "/home/circleci/project/deploy.py", line 94, in _deploy
    self.sagemaker.create_deployment(
  File "/home/circleci/project/venv/lib/python3.9/site-packages/******/sagemaker/__init__.py", line 2331, in create_deployment
    app_name, flavor = _deploy(
  File "/home/circleci/project/venv/lib/python3.9/site-packages/******/sagemaker/__init__.py", line 448, in _deploy
    deployment_operation = _create_sagemaker_endpoint(
  File "/home/circleci/project/venv/lib/python3.9/site-packages/******/sagemaker/__init__.py", line 1601, in _create_sagemaker_endpoint
    model_response = _create_sagemaker_model(
  File "/home/circleci/project/venv/lib/python3.9/site-packages/******/sagemaker/__init__.py", line 1899, in _create_sagemaker_model
    return sage_client.create_model(**create_model_args)
  File "/home/circleci/project/venv/lib/python3.9/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/circleci/project/venv/lib/python3.9/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateModel operation: 1 validation error detected: Value 'uat-7ae4e0ce66884d02b4487ba45a89f26c-model-cnxhxy9tqbuxajvvvzx-' at 'modelName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9]([\-a-zA-Z0-9]*[a-zA-Z0-9])?
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by nablabits** [comment]
Hi @harupy hope you are doing great!

Thanks for promptly solving this bug. I'd like to leave some feedback on the process, though, so the contribution experience can be improved 🙂. 

I appreciate that according to the 4th point of the lifecycle of a bug in the [issue policy](https://github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#bug-reports) that comes to say, _MLflow committers may choose to adopt ownership of severe bugs to ensure a timely fix._, you are entitled to pick the bug yourselves. No complains on that, but when someone spends some time collecting a fair amount of information to put a case together in the terms you state, at the very least, dropping a message in the issue like:

_Hey, x thanks for flagging this issue. As it's a high priority one, we are going to pick it up, feel free to flag any other issue you might spot._

is a symbol of politeness, specially when one is willing to contribute to a fix. At least I see that way, let me know if you have any other view.

I also appreciate that this may well be your way of proceed usually and it just happened in my case that you just pushed through a PR, closed the issue, and moved on without any other notice. All of us have hectic weeks or otherwise personal problems. So sorry, if this is the case. If not, no big deal either, we are all here to learn a bit from one another 😅

Hope this makes sense to you :slightly_smiling_face:
