### ISSUE TITLE
[BUG] Logged sklearn models pyfunc flavour does not work when using sklearn pipelines on sklearn>=1.4+

### ISSUE THREAD

**Issue by timvink** [mlflow/mlflow#12445]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.03
- **Python version**: 3.12.3

### Describe the problem

`mlflow.models.predict` on a logged sklearn model pipeline fails if you use `pyfunc_predict_fn="predict_proba"` in combination with a sklearn pipeline:

```
TypeError: HistGradientBoostingClassifier.predict_proba() got an unexpected keyword argument 'params'
```

### Tracking information

-

### Code to reproduce issue

```python
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2
from sklearn.pipeline import make_pipeline

# train the model
X, y = make_hastie_10_2(random_state=0)
X = pd.DataFrame(X, columns=[f"f{i}" for i in range(X.shape[1])])
X_train, X_test = X[:2000], X[2000:]
y_train, y_test = y[:2000], y[2000:]
# notice we use a sklearn pipeline. Without it would work fine!
clf = make_pipeline(HistGradientBoostingClassifier(max_iter=100)).fit(X_train, y_train)

# log the model
with mlflow.start_run():
    mlflow.sklearn.log_model(
            sk_model=clf,
            artifact_path="model",
            code_paths=None,
            signature=None,
            input_example=X_train.sample(1),
            pyfunc_predict_fn="predict_proba", # <-- Notice it would work fine with the default "predict"
            pip_requirements=["scikit-learn==1.5.0"],
            registered_model_name="bug_report",
    )

# Assert predictions work
assert clf.predict_proba(X_test.sample(1)) is not None

# Run the model
mlflow.models.predict(
    model_uri="models:/bug_report/1",
    input_data=X_test.sample(1),
    env_manager="local",
)
#> TypeError: HistGradientBoostingClassifier.predict_proba() got an unexpected keyword argument 'params'
```

### Stack trace

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 mlflow.models.predict(
      2     model_uri="models:/test_tim/15",
      3     input_data=X_test.sample(1),
      4     env_manager="local",
      5 )

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/models/python_api.py:180, in predict(model_uri, input_data, input_path, content_type, output_path, env_manager, install_mlflow, pip_requirements_override)
    177         with open(input_path, "w") as f:
    178             f.write(input_data)
--> 180         _predict(input_path)
    181 else:
    182     _predict(input_path)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/models/python_api.py:159, in predict.<locals>._predict(_input_path)
    156 def _predict(_input_path: str):
    157     return get_flavor_backend(
    158         model_uri, env_manager=env_manager, install_mlflow=install_mlflow
--> 159     ).predict(
    160         model_uri=model_uri,
    161         input_path=_input_path,
    162         output_path=output_path,
    163         content_type=content_type,
    164         pip_requirements_override=pip_requirements_override,
    165     )

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/backend.py:217, in PyFuncBackend.predict(self, model_uri, input_path, output_path, content_type, pip_requirements_override)
    212 if pip_requirements_override:
    213     raise MlflowException(
    214         "`pip_requirements_override` is not supported for local env manager."
    215         "Please use conda or virtualenv instead."
    216     )
--> 217 scoring_server._predict(local_uri, input_path, output_path, content_type)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/scoring_server/__init__.py:470, in _predict(model_uri, input_path, output_path, content_type)
    467     raise Exception(f"Unknown content type '{content_type}'")
    469 if inspect.signature(pyfunc_model.predict).parameters.get("params"):
--> 470     raw_predictions = pyfunc_model.predict(df, params=params)
    471 else:
    472     _log_warning_if_params_not_in_predict_signature(_logger, params)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py:737, in PyFuncModel.predict(self, data, params)
    735 with self._try_get_or_generate_prediction_context() as context:
    736     self._update_dependencies_schemas_in_prediction_context(context)
--> 737     return self._predict(data, params)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py:769, in PyFuncModel._predict(self, data, params)
    767 data, params = self._validate_prediction_input(data, params)
    768 if inspect.signature(self._predict_fn).parameters.get("params"):
--> 769     return self._predict_fn(data, params=params)
    771 _log_warning_if_params_not_in_predict_signature(_logger, params)
    772 return self._predict_fn(data)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/sklearn/pipeline.py:724, in Pipeline.predict_proba(self, X, **params)
    722     for _, name, transform in self._iter(with_final=False):
    723         Xt = transform.transform(Xt)
--> 724     return self.steps[-1][1].predict_proba(Xt, **params)
    726 # metadata routing enabled
    727 routed_params = process_routing(self, "predict_proba", **params)

TypeError: HistGradientBoostingClassifier.predict_proba() got an unexpected keyword argument 'params'
```

### Other info / logs

This bit from the stacktrace is relevant:

```
    469 if inspect.signature(pyfunc_model.predict).parameters.get("params"):
--> 470     raw_predictions = pyfunc_model.predict(df, params=params)
```

Here's what going on:

```python
import inspect
from sklearn.ensemble import HistGradientBoostingClassifier
m = HistGradientBoostingClassifier()
assert inspect.signature(m.predict_proba).parameters.get("params") == None  # all OK!

from sklearn.pipeline import make_pipeline
m = make_pipeline(HistGradientBoostingClassifier())
assert inspect.signature(m.predict_proba).parameters.get("params") == None  # Fails! 
```

If you look at the docs for `Pipeline` ([here](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.predict_proba)) you can see that `sklearn.pipeline.Pipeline.predict_proba` has a `**params` argument added since sklearn 1.4. 

```python
inspect.signature(m.predict_proba).parameters
#> mappingproxy({'X': <Parameter "X">, 'params': <Parameter "**params">})
```

I'm not sure how to fix, but it definitely seems like a bug to me. 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @timvink we'll take a look at this and work on a fix for the predict_proba interface. 
cc @WeichenXu123

**Comment by timvink** [comment]
Thanks!

**Comment by WeichenXu123** [comment]
@timvink I filed a fix, https://github.com/mlflow/mlflow/pull/12489 could you test it ?
by `pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12489/merge`

But with this fix, I ran your repro code, I got another error:

```
  File "/Users/weichen.xu/work/mlflow/mlflow/pyfunc/__init__.py", line 769, in _predict
    return self._predict_fn(data, params=params)
  File "/Users/weichen.xu/work/mlflow/mlflow/sklearn/__init__.py", line 525, in _custom_predict_fn_wrapper
    return fn(data, **params)
  File "/Users/weichen.xu/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/pipeline.py", line 997, in score
    return self.steps[-1][1].score(Xt, y, **score_params)
  File "/Users/weichen.xu/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py", line 764, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/Users/weichen.xu/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 203, in wrapper
    validate_parameter_constraints(
  File "/Users/weichen.xu/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'y_true' parameter of accuracy_score must be an array-like or a sparse matrix. Got None instead.
```

Seemingly your pipeline model has some issue. Could you double check it. ?

**Comment by timvink** [comment]
I can confirm, I get the same error.

Something is wrong though. Why is mlflow trying to evaluate the model? 

Remember it works without mfllow:

```
# Assert predictions work
assert clf.predict_proba(X_test.sample(1)) is not None
```

But now with 

```
mlflow.models.predict(
    model_uri="models:/bug_report/1",
    input_data=X_test.sample(1),
    env_manager="local",
)
```

you get `InvalidParameterError: The 'y_true' parameter of accuracy_score must be an array-like or a sparse matrix. Got None instead.`

Some questions/observations:

- why is mlflow trying to get the accuracy score? We never specified it anywhere
- We never supplied a `y_true` anywhere.. so it makes sense it's complaining about `y_true` parameter being None. 

```python
from sklearn.metrics import accuracy_score
assert accuracy_score(y_test, clf.predict(X_test)) > 0.5 # works fine
```

So, there is something wrong at the MLflow side 

In case you need it, here's the full stacktrace:


<details>

<summary> stacktrace</summary>

```
{
	"name": "InvalidParameterError",
	"message": "The 'y_true' parameter of accuracy_score must be an array-like or a sparse matrix. Got None instead.",
	"stack": "---------------------------------------------------------------------------
InvalidParameterError                     Traceback (most recent call last)
File /home/azureuser/workspace/ds_ramen/tests/integration/pyfunc_model.py:1
----> 1 mlflow.models.predict(
      2     model_uri=\"models:/bug_report/1\",
      3     input_data=X_test.sample(1),
      4     env_manager=\"local\",
      5 )

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/models/python_api.py:188, in predict(model_uri, input_data, input_path, content_type, output_path, env_manager, install_mlflow, pip_requirements_override)
    185         with open(input_path, \"w\") as f:
    186             f.write(input_data)
--> 188         _predict(input_path)
    189 else:
    190     _predict(input_path)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/models/python_api.py:167, in predict.<locals>._predict(_input_path)
    164 def _predict(_input_path: str):
    165     return get_flavor_backend(
    166         model_uri, env_manager=env_manager, install_mlflow=install_mlflow
--> 167     ).predict(
    168         model_uri=model_uri,
    169         input_path=_input_path,
    170         output_path=output_path,
    171         content_type=content_type,
    172         pip_requirements_override=pip_requirements_override,
    173     )

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/backend.py:216, in PyFuncBackend.predict(self, model_uri, input_path, output_path, content_type, pip_requirements_override)
    211 if pip_requirements_override:
    212     raise MlflowException(
    213         \"`pip_requirements_override` is not supported for local env manager.\"
    214         \"Please use conda or virtualenv instead.\"
    215     )
--> 216 scoring_server._predict(local_uri, input_path, output_path, content_type)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/scoring_server/__init__.py:470, in _predict(model_uri, input_path, output_path, content_type)
    467     raise Exception(f\"Unknown content type '{content_type}'\")
    469 if inspect.signature(pyfunc_model.predict).parameters.get(\"params\"):
--> 470     raw_predictions = pyfunc_model.predict(df, params=params)
    471 else:
    472     _log_warning_if_params_not_in_predict_signature(_logger, params)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py:737, in PyFuncModel.predict(self, data, params)
    735 with self._try_get_or_generate_prediction_context() as context:
    736     self._update_dependencies_schemas_in_prediction_context(context)
--> 737     return self._predict(data, params)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py:769, in PyFuncModel._predict(self, data, params)
    767 data, params = self._validate_prediction_input(data, params)
    768 if inspect.signature(self._predict_fn).parameters.get(\"params\"):
--> 769     return self._predict_fn(data, params=params)
    771 _log_warning_if_params_not_in_predict_signature(_logger, params)
    772 return self._predict_fn(data)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/mlflow/sklearn/__init__.py:525, in _SklearnModelWrapper.__init__.<locals>._custom_predict_fn_wrapper(data, params)
    520 def _custom_predict_fn_wrapper(
    521     data,
    522     params: Optional[Dict[str, Any]] = None
    523 ):
    524     params = params or {}
--> 525     return fn(data, **params)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/sklearn/pipeline.py:1007, in Pipeline.score(self, X, y, sample_weight, **params)
   1005     if sample_weight is not None:
   1006         score_params[\"sample_weight\"] = sample_weight
-> 1007     return self.steps[-1][1].score(Xt, y, **score_params)
   1009 # metadata routing is enabled.
   1010 routed_params = process_routing(
   1011     self, \"score\", sample_weight=sample_weight, **params
   1012 )

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/sklearn/base.py:764, in ClassifierMixin.score(self, X, y, sample_weight)
    739 \"\"\"
    740 Return the mean accuracy on the given test data and labels.
    741 
   (...)
    760     Mean accuracy of ``self.predict(X)`` w.r.t. `y`.
    761 \"\"\"
    762 from .metrics import accuracy_score
--> 764 return accuracy_score(y, self.predict(X), sample_weight=sample_weight)

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/sklearn/utils/_param_validation.py:203, in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    200 to_ignore += [\"self\", \"cls\"]
    201 params = {k: v for k, v in params.arguments.items() if k not in to_ignore}
--> 203 validate_parameter_constraints(
    204     parameter_constraints, params, caller_name=func.__qualname__
    205 )
    207 try:
    208     with config_context(
    209         skip_parameter_validation=(
    210             prefer_skip_nested_validation or global_skip_validation
    211         )
    212     ):

File /anaconda/envs/ds_ramen/lib/python3.11/site-packages/sklearn/utils/_param_validation.py:95, in validate_parameter_constraints(parameter_constraints, params, caller_name)
     89 else:
     90     constraints_str = (
     91         f\"{', '.join([str(c) for c in constraints[:-1]])} or\"
     92         f\" {constraints[-1]}\"
     93     )
---> 95 raise InvalidParameterError(
     96     f\"The {param_name!r} parameter of {caller_name} must be\"
     97     f\" {constraints_str}. Got {param_val!r} instead.\"
     98 )

InvalidParameterError: The 'y_true' parameter of accuracy_score must be an array-like or a sparse matrix. Got None instead."
}
```

</details>

**Comment by WeichenXu123** [comment]
@timvink could you try 
```
model = mlflow.pyfunc.load_model("models:/bug_report/1")
model.predict(...) 
```
?

**Comment by WeichenXu123** [comment]
Interesting, seemingly it is invoking model.score function, need deeper look

**Comment by WeichenXu123** [comment]
@timvink 

It is bug in my PR, now I have fixed it. Could you try it again ? `pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12489/merge`

**Comment by timvink** [comment]
Yes, works! 🎉 Thanks!
