### ISSUE TITLE
[BUG] Transformer fine-tuning example is broken: log_model failed to process model config

### ISSUE THREAD

**Issue by dannikay** [mlflow/mlflow#12452]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.13.2
- Tracking server: 2.13.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.12.3
- **yarn version, if running the dev UI**:

### Describe the problem

The example in public doc is broken: https://mlflow.org/docs/latest/llms/transformers/tutorials/fine-tuning/transformers-fine-tuning.html

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import evaluate
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    pipeline,
)

import mlflow

sms_dataset = load_dataset("sms_spam")

sms_train_test = sms_dataset["train"].train_test_split(test_size=0.2)
train_dataset = sms_train_test["train"]
test_dataset = sms_train_test["test"]


mlflow.set_tracking_uri("http://127.0.0.1:8080")

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")


def tokenize_function(examples):
    return tokenizer(
        examples["sms"],
        padding="max_length",
        truncation=True,
        max_length=128,
    )


seed = 22

train_tokenized = train_dataset.map(tokenize_function)
train_tokenized = train_tokenized.remove_columns(["sms"]).shuffle(seed=seed)

test_tokenized = test_dataset.map(tokenize_function)
test_tokenized = test_tokenized.remove_columns(["sms"]).shuffle(seed=seed)

id2label = {0: "ham", 1: "spam"}
label2id = {"ham": 0, "spam": 1}

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2,
    label2id=label2id,
    id2label=id2label,
)

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

training_output_dir = "/tmp/sms_trainer"
training_args = TrainingArguments(
    output_dir=training_output_dir,
    evaluation_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_steps=8,
    num_train_epochs=3,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,
    compute_metrics=compute_metrics,
)

mlflow.set_experiment("Spam Classifier Training")

with mlflow.start_run() as run:
    trainer.train()

tuned_pipeline = pipeline(
    task="text-classification",
    model=trainer.model,
    batch_size=8,
    tokenizer=tokenizer,
    device="cuda",
)

quick_check = (
    "I have a question regarding the project development timeline and allocated resources; "
    "specifically, how certain are you that John and Ringo can work together on writing this next song? "
    "Do we need to get Paul involved here, or do you truly believe, as you said, 'nah, they got this'?"
)

tuned_pipeline(quick_check)

model_config = {"batch_size": 8, "device": "cuda"}

signature = mlflow.models.infer_signature(
    ["This is a test!", "And this is also a test."],
    mlflow.transformers.generate_signature_output(
        tuned_pipeline, ["This is a test response!", "So is this."]
    ),
    params=model_config,
)

signature

with mlflow.start_run(run_id=run.info.run_id):
    model_info = mlflow.transformers.log_model(
        transformers_model=tuned_pipeline,
        artifact_path="fine_tuned",
        signature=signature,
        input_example=["Pass in a string", "And have it mark as spam or not."],
        model_config=model_config,
        example_no_conversion=True,
    )



```

### Stack trace

```
2024[/06/22](http://localhost:8888/06/22) 13:39:25 WARNING mlflow.utils.requirements_utils: Failed to run predict on input_example, dependencies introduced in predict are not captured.
TypeError("PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'device'")Traceback (most recent call last):


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/mlflow/utils/_capture_modules.py", line 165](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/mlflow/utils/_capture_modules.py#line=164), in load_model_and_predict
    model.predict(input_example, params=params)


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py", line 1689](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py#line=1688), in predict
    return self._predict(input_data, model_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py", line 1781](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py#line=1780), in _predict
    raw_output = self._validate_model_config_and_return_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py", line 1608](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/mlflow/transformers/__init__.py#line=1607), in _validate_model_config_and_return_output
    return self.pipeline(data, **model_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/text_classification.py", line 156](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/text_classification.py#line=155), in __call__
    result = super().__call__(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/base.py", line 1224](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/base.py#line=1223), in __call__
    outputs = list(final_iterator)
              ^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py", line 124](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py#line=123), in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py", line 124](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py#line=123), in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py#line=630), in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 675](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py#line=674), in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py#line=50), in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py", line 19](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/pt_utils.py#line=18), in __getitem__
    processed = self.process(item, **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/pipelines/text_classification.py", line 180](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/pipelines/text_classification.py#line=179), in preprocess
    return self.tokenizer(inputs, return_tensors=return_tensors, **tokenizer_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 2883](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py#line=2882), in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 2989](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py#line=2988), in _call_one
    return self.encode_plus(
           ^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 3062](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py#line=3061), in encode_plus
    return self._encode_plus(
           ^^^^^^^^^^^^^^^^^^


  File "[/home/x/Programs/mlflow/venv/lib/python3.12/site-packages/transformers/tokenization_utils_fast.py", line 583](http://localhost:8888/doc/tree/venv/lib/python3.12/site-packages/transformers/tokenization_utils_fast.py#line=582), in _encode_plus
    batched_output = self._batch_encode_plus(
                     ^^^^^^^^^^^^^^^^^^^^^^^^


TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'device'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @dannikay I was able to validate with MLflow 2.14.1 and transformers latest 2 minor release versions. Filed a PR to remove the unneeded model_config entry. 
Thanks for the find!
