### ISSUE TITLE
Postgres backend store crashes when an experiment run is logged

### ISSUE THREAD

**Issue by joshpeng** [mlflow/mlflow#1248]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon Linux
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**: 3.7.3
- **Exact command to reproduce**: `mlflow server --backend-store-uri postgresql://user:password@localhost:5432/mlflow --default-artifact-root s3://somebucket/ --host 0.0.0.0`

### Describe the problem
Running the mlflow server on an EC2 box with a Postgres server with the following command starts the server with no issues. However, when an example experiment run is triggered, the mlflow UI can't figure out how to store it properly and breaks the server with a `TypeError: 0 has type int, but expected one of: bytes, unicode` error.

```
[2019-05-11 19:37:38,603] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 288, in _search_runs
    response_message.runs.extend([r.to_proto() for r in run_entities])
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 288, in <listcomp>
    response_message.runs.extend([r.to_proto() for r in run_entities])
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/entities/run.py", line 38, in to_proto
    run.info.MergeFrom(self.info.to_proto())
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/entities/run_info.py", line 150, in to_proto
    proto.experiment_id = self.experiment_id
TypeError: 0 has type int, but expected one of: bytes, unicode
[2019-05-11 19:37:38,617] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/experiments/get [GET]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 143, in _get_experiment
    response_message.runs.extend([r.to_proto() for r in run_info_entities])
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py", line 143, in <listcomp>
    response_message.runs.extend([r.to_proto() for r in run_info_entities])
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/mlflow/entities/run_info.py", line 150, in to_proto
    proto.experiment_id = self.experiment_id
TypeError: 0 has type int, but expected one of: bytes, unicode
```

### Source code / logs
Here is the actual experiment run. It is just a dummy run without any real logic:
```python
import os
import mlflow
import numpy as np
import matplotlib.pyplot as plt


MLFLOW_USER = os.environ['MLFLOW_USER']
MLFLOW_PASSWORD = os.environ['MLFLOW_PASSWORD']
MLFLOW_HOST = os.environ['MLFLOW_HOST']
# Include user name and password to request
TRACKING_URI = f'http://{MLFLOW_USER}:{MLFLOW_PASSWORD}@{MLFLOW_HOST}'


# set up tracking uri
mlflow.set_tracking_uri(TRACKING_URI)
client = mlflow.tracking.MlflowClient(TRACKING_URI)


# create plot that we will track as an artifact
x = np.linspace(0, 2*np.pi, num=100)
y = np.cos(x)
plt.plot(x,y)
plt.savefig('./test_picture.png')


# log parameters, metrics and artifacts on server
with mlflow.start_run(experiment_id=0):
    mlflow.log_param('parameter', 1)
    mlflow.log_metric('metric', 2)
```

**Comment by joshpeng** [comment]
Looks like https://github.com/mlflow/mlflow/pull/1167 would resolve this. Thanks.
