### ISSUE TITLE
[SETUP-BUG] address/offset not page-aligned with Scipy 1.14.0

### ISSUE THREAD

**Issue by fmulero** [mlflow/mlflow#12562]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 12 (bookworm) AMD64
- **MLflow installed from**: Source, tag 2.14.1
- **MLflow version (run ``mlflow --version``)**: mlflow, version 2.14.1
- **Python version: **: Python 3.10.14

### Code to reproduce issue

After compiling the code, if we try to run locally this example (the one we can see in the UI):
```python
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

# set the experiment id
mlflow.set_experiment(experiment_id="0")

mlflow.autolog()
db = load_diabetes()

X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

# Create and train models.
rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
rf.fit(X_train, y_train)

# Use the model to make predictions on the test dataset.
predictions = rf.predict(X_test)
```

We will face the following error:
```console
Traceback (most recent call last):
  File "/app/vib_test.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
  File "/opt/bitnami/python/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    import scipy.linalg  # noqa
  File "/opt/bitnami/python/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 203, in <module>
    from ._misc import *
  File "/opt/bitnami/python/lib/python3.10/site-packages/scipy/linalg/_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/opt/bitnami/python/lib/python3.10/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: libscipy_openblas-c128ec02.so: ELF load command address/offset not page-aligned
```

### Describe the problem

Please see the section **Code to reproduce issue**

### Other info / logs

This problem is happening after the release of scipy 1.14.0. If we force scipy version 1.13.1 everything will work as expected.

**Comment by fmulero** [comment]
To be perfectly blunt, not sure where is the problem. If I reinstall the scipy (`pip install -I scipy==1.14.0`) everything works as expected

**Comment by fmulero** [comment]
The root cause of the problem was in a minification process executed after building MLFlow. I'll close the issue.
