### ISSUE TITLE
[BUG} Error Loading and Deploying Registered Model! Response ERROR 500

### ISSUE THREAD

**Issue by mohammedsalah-ai** [mlflow/mlflow#12564]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow==2.14.1

### System information

- WSL2 Ubuntu 22.04 on Windows 11
- pyenv - python 3.12.4 on WSL2 and not windows

### Describe the problem

unable to load or serve registered models from mlflow model registery although present in mlflow UI
I tried to load a registered model *dismonds* with an alias `0-0-0` for version 1.

i ran the code
```python
model = mlflow.sklearn.load_model("models:/dismonds@0-0-0")
```
it failed,
so I tried deploying it locally
```bash
export MODEL_URI=models:/dismonds@0-0-0
export MLFLOW_TRACKING_URI=http://localhost:5000
mlflow models serve -m $MODEL_URI -p 5001 --env-manager local
```
it also failed.
both with the same error.
although the model is present in both the UI and the file system
![image](https://github.com/mlflow/mlflow/assets/125088083/54c93e05-a37f-4e7a-966c-61b12ed05ea1)

### Tracking information

**You could see clearly that It's trying to download the artifact multiple times**
```shell
[2024-07-03 16:27:03 +0300] [17939] [INFO] Starting gunicorn 22.0.0
[2024-07-03 16:27:03 +0300] [17939] [INFO] Listening at: http://127.0.0.1:5000 (17939)
[2024-07-03 16:27:03 +0300] [17939] [INFO] Using worker: sync
[2024-07-03 16:27:04 +0300] [17941] [INFO] Booting worker with pid: 17941
[2024-07-03 16:27:04 +0300] [17942] [INFO] Booting worker with pid: 17942
[2024-07-03 16:27:04 +0300] [17943] [INFO] Booting worker with pid: 17943
[2024-07-03 16:27:04 +0300] [17944] [INFO] Booting worker with pid: 17944
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
[2024-07-03 16:34:13 +0300] [17939] [INFO] Handling signal: winch
```

### Code to reproduce issue

```
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import json
import mlflow
from mlflow import MlflowClient

import optuna
if optuna.visualization.matplotlib.is_available():
    from optuna.visualization.matplotlib import (
        plot_contour,
        plot_parallel_coordinate,
        plot_param_importances
    )

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# for type annotations.
from matplotlib.figure import Figure
from sklearn.base import BaseEstimator

import warnings
warnings.filterwarnings('ignore')

# In[2]:


MLFLOW_TRACKING_URI ='http://localhost:5000' 
client = MlflowClient(tracking_uri=MLFLOW_TRACKING_URI)
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

# In[3]:


# an example on pre plots
def datacorr(save: str = "") -> Figure:
    """Displays diamond price correlation with other features"""
    fig, ax = plt.subplots()
    sns.heatmap(
        diamonds.select_dtypes(exclude=['category']).corr().price.drop('price').to_frame(), 
        annot=True,
        ax=ax
    )
    ax.set_title('Diamond Price Correlation')
    ax.set_ylabel('Features')

    if save:
        fig.savefig(save, format='png', dpi=750)

    plt.close(fig)
    return fig


def regeval(
    model: BaseEstimator, 
    X_test: np.array, 
    y_test: np.array,
    save: str = ""
) -> Figure:
    """Evaluates a regression algorithm"""
    fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(12, 12))
    
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r_squared = r2_score(y_test, y_pred)
    residuals = y_test - y_pred

    ax[0, 0].set_title("True vs. Predicted")
    sns.scatterplot(ax=ax[0, 0], x=y_pred, y=y_test, alpha=0.5)
    ax[0, 0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
    ax[0, 0].set_xlabel("Predicted Values")
    ax[0, 0].set_ylabel("True Values")
    

    ax[0, 1].set_title("Residuals Distribution")
    sns.histplot(ax=ax[0, 1], x=residuals, bins=20, alpha=0.5)
    ax[0, 1].set_xlabel("Residuals")
    ax[0, 1].set_ylabel("Frequency")
   
    
    ax[1, 0].set_title("Predicted vs. Residuals")
    sns.scatterplot(ax=ax[1, 0], x=y_pred, y=residuals, alpha=0.5)
    ax[1, 0].axhline(y=0, color='r', linestyle='--')
    ax[1, 0].set_xlabel("Predicted Values")
    ax[1, 0].set_ylabel("Residuals")
    
    
    ax[1, 1].set_title("True vs. Residuals")
    sns.scatterplot(ax=ax[1, 1], x=y_test, y=residuals, alpha=0.5)
    ax[1, 1].axhline(y=0, color='r', linestyle='--')
    ax[1, 1].set_xlabel("True Values")
    ax[1, 1].set_ylabel("Residuals")

    plt.tight_layout()
    
    if save:
        fig.savefig(save, format='png', dpi=750)

    plt.close(fig)
    return fig


# In[4]:

diamonds = sns.load_dataset('diamonds')
diamonds.head()


# In[5]:

optuna_diamond_experiment_id = mlflow.create_experiment(name="Diamonds")


# In[6]:

active_experiment = mlflow.set_experiment(experiment_id=optuna_diamond_experiment_id)

# In[7]:

X = diamonds.drop(["price"], axis=1)
y = diamonds["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42
)


# In[8]:

optuna.logging.set_verbosity(optuna.logging.ERROR)
def improvement_callback(study: optuna.Study, ftrial: optuna.trial.FrozenTrial) -> None:
    """reports back when improvements happen in the study"""
    
    winner = study.user_attrs.get("winner", None)
    if study.best_value and winner != study.best_value:
        study.set_user_attr("winner", study.best_value)
        if not winner:
            print(f"Initial trial {ftrial.number} achieved value: {ftrial.value}")
        else:
            improvement_percent = (abs(winner - study.best_value) / study.best_value) * 100
            print(
                f"Trial {ftrial.number} achieved value: {ftrial.value} with"
                f"{improvement_percent: .4f}% improvement"
            )


# In[9]:

def create_model(**params):
    transformer = ColumnTransformer(
        transformers=[
            ('one_hot_encoder', OneHotEncoder(), ['cut', 'color', 'clarity'])
        ],
        remainder='passthrough'
    )
    
    predictor = RandomForestRegressor(**params)
    
    model = Pipeline(
        steps=[
            ("transformer", transformer),
            ("predictor", predictor)
        ]
    )

    return model


# In[10]:

def calc_metrics(y_test, y_pred):
    metrics = {
        "mae": mean_absolute_error(y_test, y_pred),
        "mse": mean_squared_error(y_test, y_pred),
        "rmse": mean_squared_error(y_test, y_pred, squared=False),
        "r2_score": r2_score(y_test, y_pred)
    }

    return metrics


# In[11]:

def objective(trial: optuna.Trial):
    
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 80, 250),
        "max_depth": trial.suggest_int("max_depth", 8, 14)
    }
    
    model = create_model(**params)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    metrics = calc_metrics(y_test, y_pred)

    with mlflow.start_run(nested=True):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics) 
    
    return metrics['rmse']


# In[12]:

run = "hyperparameter_tuning"
artifact_path = "diamonds_model"

with mlflow.start_run(run_name=run, nested=True): # you need to specift nested=True
    study = optuna.create_study(direction="minimize")
    study.optimize(
        objective,
        n_trials=3,
        callbacks=[improvement_callback]
    )

    mlflow.set_tags(
        tags={
            "project": "Diamond Price",
            "optimizer_engine": "optuna",
            "model_family": "RandomForests",
            "feature_set_version": 1,
        }
    )
    
    model = create_model(**study.best_params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    metrics = calc_metrics(y_test, y_pred)
    
    mlflow.log_params(study.best_params)
    mlflow.log_metrics(metrics)
    mlflow.log_figure(figure=datacorr(), artifact_file="correlation_plot.png")
    mlflow.log_figure(figure=plot_contour(study).figure, artifact_file="optuna_contour_plot.png")
    mlflow.log_figure(figure=plot_parallel_coordinate(study).figure, artifact_file="optuna_parallel_coors_plot.png")
    mlflow.log_figure(figure=plot_param_importances(study).figure, artifact_file="optuna_param_importances.png")
    mlflow.log_figure(figure=regeval(model, X_test, y_test), artifact_file="model_performance.png")

    mlflow.sklearn.log_model(
        sk_model=model, 
        input_example=X_train, 
        artifact_path=artifact_path
    )


# In[13]:

best_run = client.search_runs(
    optuna_diamond_experiment_id, order_by=["metrics.rmse ASC"], max_results=1
)[0]


# In[14]:

model_uri = mlflow.get_artifact_uri(artifact_path)
example_figure_uri = mlflow.get_artifact_uri("correlation_plot.png")


# In[15]:

model_version = mlflow.register_model(
    model_uri,
    name="dismonds",
    tags={
        "data": "seaborn-diamonds"
    }
)


# In[16]:

client.set_registered_model_alias(name="dismonds", alias="0-0-0", version="1")


# In[17]:

model = mlflow.sklearn.load_model("models:/dismonds/1")
```

### Stack trace

**You can check mlflow logs to ensure that the model was successfully registered**
```
ExperimentalWarning: is_available is experimental (supported from v2.2.0). The interface can change in the future.
  if optuna.visualization.matplotlib.is_available():
Initial trial 0 achieved value: 581.03389499888
Trial 2 achieved value: 563.6792703878107 with 3.0788% improvement
Successfully registered model 'dismonds'.
2024/07/03 16:29:11 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: dismonds, version 1
Created version '1' of model 'dismonds'.
Downloading artifacts:   0%|                                                                                                    | 0/1 [01:01<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/c/.../2-mlflow+optuna.py", line 296, in <module>
    model = mlflow.sklearn.load_model("models:/dismonds/1")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supermaker/.../.cockpitc/lib/python3.12/site-packages/mlflow/sklearn/__init__.py", line 626, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supermaker/.../.cockpitc/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py", line 111, in _download_artifact_from_uri
    return repo.download_artifacts(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supermaker/.../.cockpitc/lib/python3.12/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 190, in download_artifacts
    model_path = self.repo.download_artifacts(artifact_path, dst_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supermaker/.../.cockpitc/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repo.py", line 274, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from http://localhost:5000/api/2.0/mlflow-artifacts/artifacts/784404421520436639/6c72c505b73a4c32b4728a344a5d7cb5/artifacts/diamonds_model:
##### File  #####
API request to http://localhost:5000/api/2.0/mlflow-artifacts/artifacts/784404421520436639/6c72c505b73a4c32b4728a344a5d7cb5/artifacts/diamonds_model/ failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/784404421520436639/6c72c505b73a4c32b4728a344a5d7cb5/artifacts/diamonds_model/ (Caused by ResponseError('too many 500 error responses'))
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mohammedsalah-ai** [comment]
I just wanted to say that I was able to solve the issue

to get the artifact uri of the model i used `.get_artifact_uri()` outside the run where I actually logged the model rather than throwing me an error it just created a new run and pointed to a non-existent artifact with the same name. that's why the mlflow server wasn't able to get the artifact. 

I'm closing this and reopening a new one as a suggestion
Thanks!
