### ISSUE TITLE
[BUG] 'Can't locate revision identified by' and 'No such revision or branch'

### ISSUE THREAD

**Issue by gioargyr** [mlflow/mlflow#12627]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.9.2
- Tracking server: 2.9.2

### System information

- **Debian 11**:
- **Python 3.10.13**:

### Describe the problem

I deploy MLFlow in Kubernetes.
- I am using the official docker image (ghcr.io/mlflow/mlflow:latest) and I install extra the packages 'psycopg2-binary' and 'boto3', so the MLFlow can be supported by a MinIO and a PostgreSQL
- The PostgreSQL and MinIO instances work without any issue.
- The docker container / Kubernetes is deployed with this entrypoint / command: 
`$ mlflow server --backend-store-uri postgresql://<PG_USER>:<PG_PWD>@<PG_HOST>:5432/<PG_DB> --host 0.0.0.0 --serve-artifacts --artifacts-destination s3://<BUCKET_NAME>`
Accordingly I have defined the proper environment variables '`MLFLOW_S3_ENDPOINT_URL`',  '`AWS_ACCESS_KEY_ID`' and '`AWS_SECRET_ACCESS_KEY`' which are used by MLFlow server to access the MinIO instance.

The deployment was fine and I am pretty sure the MLFlow server restarted several times recently.
However during it's last restart I see the following error:
```
2024/07/10 07:18:53 ERROR mlflow.cli: Error initializing backend store
2024/07/10 07:18:53 ERROR mlflow.cli: Can't locate revision identified by '5b0e9adcef9c'
```
followed by
`alembic.script.revision.ResolutionError: No such revision or branch '5b0e9adcef9c'`

I searched and I found a few things on this issue but nothing solves my problem.
I can clearly see there is a table `alembic_version` in the database and indeed there is a one row with only one value `5b0e9adcef9c`.
I deleted this table but it didn't fix the issue (it was one of the "solutions" I found). So, I reverted everything, as I have a copy of the database.

Can someone tell me with what value does the  MLFlow server cross-checks the entry on `alembic_version` table ? (another solution I found is that I can manually update the value of `alembic_version` table, so it will match the real one.)
Has anyone else experienced this issue?
Can I deactivate something when I deploy MLFlow?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

N/A

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
2024/07/10 07:18:53 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2024/07/10 07:18:53 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
2024/07/10 07:18:53 ERROR mlflow.cli: Error initializing backend store
2024/07/10 07:18:53 ERROR mlflow.cli: Can't locate revision identified by '5b0e9adcef9c'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 461, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 800, in iterate_revisions
    revisions, heads = fn(
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 1453, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 530, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 530, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 553, in get_revisions
    return tuple(
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 554, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/revision.py", line 625, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '5b0e9adcef9c'
id_elem
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 426, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 299, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 276, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 137, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 156, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 92, in _initialize_tables
    _upgrade_db(engine)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 215, in _upgrade_db
    command.upgrade(config, "heads")
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 401, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 585, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 939, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 612, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 390, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 449, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '5b0e9adcef9c'

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I guess last database migration execution was interrupted, then it causes the database going into inconsistent state.
To recover from a failed migration, I think this section helps you:
https://github.com/mlflow/mlflow/blob/master/mlflow/store/db_migrations/README.md#recovering-from-a-failed-migration

**Comment by gioargyr** [comment]
As documentation advises, I dropped the table `latest_metrics`, however the problem persists.

So, I continued, by deleting the only row of table `alembic_version`.
I launched mlflow and this time I get this error:
```
[SQL: ALTER TABLE metrics ADD COLUMN step BIGINT DEFAULT '0' NOT NULL]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "step" of relation "metrics" already exists
```

Should I delete the column `step`?
As far as I can understand, MLFlow tries to add column `step` on table `metrics` when it is launched.
Can someone tell me why?
Or, can you point me to documentation that explains all the actions MLFlow does every time it is launched?

**Comment by sir3mat** [comment]
I don't know if it related but when i try running the mlflow v15.0 it trrows this error
`
2024/08/01 08:10:25 ERROR mlflow.cli: Error initializing backend store
2024/08/01 08:10:25 ERROR mlflow.cli: No module named 'psycopg2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 425, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 355, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 332, in _get_tracking_store
2024-08-01T08:10:25.125266152Z     _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 42, in get_store
2024-08-01T08:10:25.125278892Z     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 52, in _get_store_with_resolved_uri
2024-08-01T08:10:25.125291893Z     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 153, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 164, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
2024-08-01T08:10:25.125322893Z   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 236, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 292, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
2024-08-01T08:10:25.125362004Z     return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
2024-08-01T08:10:25.125387294Z     import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
`

with v14.2.3 i don't have any issue

**Comment by thedevd** [comment]
We also hit with the same problem when upgrading our environment to new release. 
` 2024/10/17 16:53:55 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
 2024/10/17 16:53:55 INFO mlflow.store.db.utils: Updating database tables
 INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
 INFO  [alembic.runtime.migration] Will assume transactional DDL.
 2024/10/17 16:53:55 ERROR mlflow.cli: Error initializing backend store
 2024/10/17 16:53:55 ERROR mlflow.cli: Can't locate revision identified by '4465047574b1'
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 254, in _catch_revision_errors
     yield
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 462, in _upgrade_revs
     for script in reversed(list(revs))
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 814, in iterate_revisions
     revisions, heads = fn(
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 1475, in _collect_upgrade_revisions
     current_revisions = self.get_revisions(lower)
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 542, in get_revisions
     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 542, in <listcomp>
     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 565, in get_revisions
     return tuple(
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 566, in <genexpr>
     self._revision_for_ident(rev_id, branch_label)
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/revision.py", line 637, in _revision_for_ident
     raise ResolutionError(
 alembic.script.revision.ResolutionError: No such revision or branch '4465047574b1'

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/dist-packages/mlflow/cli.py", line 426, in server
     initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/server/handlers.py", line 289, in initialize_backend_stores
     _get_tracking_store(backend_store_uri, default_artifact_root)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/server/handlers.py", line 268, in _get_tracking_store
     _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/server/handlers.py", line 129, in _get_sqlalchemy_store
     return SqlAlchemyStore(store_uri, artifact_uri)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/store/tracking/sqlalchemy_store.py", line 156, in __init__
     mlflow.store.db.utils._initialize_tables(self.engine)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/store/db/utils.py", line 92, in _initialize_tables
     _upgrade_db(engine)
   File "/usr/local/lib/python3.10/dist-packages/mlflow/store/db/utils.py", line 215, in _upgrade_db
     command.upgrade(config, "heads")
   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 406, in upgrade
     script.run_env()
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 586, in run_env
     util.load_python_file(self.dir, "env.py")
   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 95, in load_python_file
     module = load_module_py(module_id, path)
   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 113, in load_module_py
     spec.loader.exec_module(module)  # type: ignore
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/usr/local/lib/python3.10/dist-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
     run_migrations_online()
   File "/usr/local/lib/python3.10/dist-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
     context.run_migrations()
   File "<string>", line 8, in run_migrations
   File "/usr/local/lib/python3.10/dist-packages/alembic/runtime/environment.py", line 946, in run_migrations
     self.get_context().run_migrations(**kw)
   File "/usr/local/lib/python3.10/dist-packages/alembic/runtime/migration.py", line 616, in run_migrations
     for step in self._migrations_fn(heads, self):
   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 395, in upgrade
     return script._upgrade_revs(revision, rev)
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 450, in _upgrade_revs
     with self._catch_revision_errors(
   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
     self.gen.throw(typ, value, traceback)
   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 286, in _catch_revision_errors
     raise util.CommandError(resolution) from re
 alembic.util.exc.CommandError: Can't locate revision identified by '4465047574b1'`

**Comment by gioargyr** [comment]
Hello again,

I found the workaround for this issue.
I lack experience in SQL, especially about migration processes, so my workaround may not be very sophisticated, but at least it always works.
Unfortunately, MLFlow has the decribed issue often, so I already had to execute the following actions a few times the last 6 months.
Please, give me your feedback, as I am very curious whether there is a more sophisticated solution.

In order to solve this issue, you need to recreate the database that is used by MLFlow with a new one, but the alembic version to should be different. On top of it, the data should not be lost.

For the next actions, I presume you work within an environment that has access to the database used by MLFlow and has `postgresql-client` available.
- First backup the database (3 times in total). The first 2 backups won't be used, but as we are going to intervene hard, better to be safe than sorry.
- For a general backup, execute this command (again, you can omit this step if you think it's uneccessary for you):
    `$ pg_dump -U PG_USER -p 5432 -h PG_HOSTNAME -d PG_DB_NAME -f DUMP_NAME1.sql -W --no-owner --no-acl`
- For a general but only-data backup, execute this command(again, you can omit this step if you think it's uneccessary for you):
    `$ pg_dump -U PG_USER -p 5432 -h PG_HOSTNAME -d PG_DB_NAME -f DUMP_NAME2.sql -W --data-only --no-owner --no-acl`

`DUMP_NAME1.sql ` and `DUMP_NAME2.sql` are not going to be used. It's only for safety in case you need to recreate the DB.

And now, the actual procedure for getting rid of the alembic version issue

- Connect to the PostgreSQL instance.
`$ psql -h PG_HOSTNAME -p PG_PORT_NO -d PG_DB_NAME -U PG_UN -W`
- `alembic_version` table should have only one row. Delete it.
```
db_name=# SELECT * FROM alembic_version;
db_name=# DELETE FROM alembic_version WHERE version_num = '5b0e9adcef9c';
```
- Now, delete the following 3 tables in this exact order: `trace_tags`, `trace_request_metadata`, and `trace_info`:
```
db_name=# DROP TABLE trace_tags;
db_name=# DROP TABLE trace_request_metadata;
db_name=# DROP TABLE trace_info;
```
- Disconnect from the PostgreSQL instance and take an only-data dump of the modified database  (no roles, no ownership)
`$ pg_dump -U PG_USER -p 5432 -h PG_HOSTNAME -d PG_DB_NAME -f DUMP_NAME.sql -W --data-only --no-owner --no-acl`

- Connect to the PostgreSQL instance and create a new database (you can use the same PostgreSQL instance)
`db_name=# CREATE DATABASE new_db_name`
- Now re-deploy MLFlow server (as you usually do) and make it point to this new database.
- After MLFlow server is deployed and sees the new and empty database, it will initialize it. You can verify the initialization by connecting to the PostgreSQL instance and checking the tables of this new DB. (before re-deploying MLFlow it was totally empty. Now it has 16 tables.)
```
db_name=# \c new_db_name
new_db_name=# \dt
```
- As you are connected to the PostgreSQL instance in the `new_db_name`, verify that `experiments` table has only one row, where `experiment_id = 0`. Delete this row:
```
new_db_name=# SELECT * FROM experiments;
new_db_name=# DELETE FROM experiments WHERE experiment_id = 0;
```
- Now the new_db_name is ready to get the data from the old one. Disconnect from the PostgreSQL instance and restore all data using the last dump DUMP_NAME.sql:
`$ psql --set ON_ERROR_STOP=on -U PG_UN -p PG_PORT_NO -h PG_HOSTNAME -d PG_new_DB_NAME < DUMP_NAME.sql`

Check GUI of MLFlow and you'll see that everything is running fine and all your data is there!

**Comment by timeisaved** [comment]
Hello, here to add my 2 cents.
its not a bug, if you look into mlflow docker container you will find that there are two separate alembic.ini files 
1. one for mlflow store
2. for mlflow authentifications

when you launch mlflow without --app-name basic-auth nothing happens because one alembic file is used but when you add that tag mlflow starts another alembic initialisation. thus, two alembic revisions are created on same database which causes that infamous
alembic.util.exc.CommandError: Can't locate revision identified by '5b0e9adcef9c'.

solution: have separate databases for mlflow store metadata and mlflow authentifications

basic_auth.ini file database_uri should be different than MLFLOW_BACKEND_STORE_URI

**Comment by fritz-trawa** [comment]
In our case it was caused by different versions of mlflow accessing the database and then blindly trying different commands to "fix it". Needlessly to say, the only thing that saved the day was a complete reinstall plus ensuring all versions of mlflow accessing the DB were synced.

**Comment by jankogasic** [comment]
Hello @fritz-trawa,

Can you explain how did you achieve this? Did you drop all tables first or maybe recreated entire database?

**Comment by fritz-trawa** [comment]
We basically restarted from scratch with a brand new DB and strict control on the version of the client accessing the DB. We gave up on trying to salvage the old data, but there wasn't much of it at that stage to be honest

**Comment by theoden8** [comment]
in my case i believe the problem is that, when you update to "latest", sometmes (like today) the latest is v2, but yesterday the latest was v3

**Comment by jankogasic** [comment]
Okay, I just had to to the same thing since I couldn't make anything else to work. Fresh new Mlflow deployment with fresh new S3 bucket and MySQL database. Thanks @fritz-trawa !

**Comment by jankogasic** [comment]
@theoden8 it is always a good practice to never use 'latest' and instead explicitly specify your versions

**Comment by aliisayev008gemini-cloud** [comment]
My problem was that I used old mlflow version for migration, and new mlflow version for the server itself. Using new mlflow version for both migration and the server solved the issue. Basically my old mlflow did not have new revision that my server had.
