### ISSUE TITLE
MLFlow runs are not recorded in database and artifact location ?

### ISSUE THREAD

**Issue by asraful** [mlflow/mlflow#1262]
Setup # OS : ubuntu 18.04 LTS

mysql Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using EditLine wrapper

(Installed bellow dependency also : sudo apt-get install libmysqlclient-dev sudo pip3 install mysqlclient conda install -c anaconda sqlalchemy )

Python 3.7.3

Steps i followed #

Created database there named # mlflow_tracker

Now i tried to start MlFlow server as "

(base) asraful@asraful:~$ conda activate my_env

(my_env) asraful@asraful:~$ mlflow server  --backend-store-uri "mysql://mlflow:password@localhost:3306/mlflow_tracker"  --default-artifact-root /mnt/mlflow_bucket  --host 0.0.0.0
This is giving output as #

[2019-05-14 01:49:56 +0600] [9976] [INFO] Starting gunicorn 19.9.0
[2019-05-14 01:49:56 +0600] [9976] [INFO] Listening at: http://0.0.0.0:5000 (9976)
[2019-05-14 01:49:56 +0600] [9976] [INFO] Using worker: sync
[2019-05-14 01:49:56 +0600] [9979] [INFO] Booting worker with pid: 9979
[2019-05-14 01:49:56 +0600] [9980] [INFO] Booting worker with pid: 9980
[2019-05-14 01:49:56 +0600] [9981] [INFO] Booting worker with pid: 9981
[2019-05-14 01:49:56 +0600] [9989] [INFO] Booting worker with pid: 9989
Therefor i tried to do one test run using bellow script #

```
import os
from mlflow import log_metric, log_param, log_artifact

if __name__ == "__main__":
    # Log a parameter (key-value pair)
    log_param("param1", 5)

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output.txt", "w") as f:
        f.write("Hello world!")
    log_artifact("output.txt")
This code runs perfectly .
```

Therefor my expectation is :

Metric will be saved in mlflow_tracker database . Other data will be saved under /mnt/mlflow_bucket

As i configured backend-store-uri as : mlflow_tracker database And default-artifact-root : /mnt/mlflow_bucket

But facing issues as #

all metric and metadata are writing under default mlflow location : /~/mlFlow/mlruns/0

And, if i try to access mlflow ui from brower getting defualt image and bellow stack trace .

Traceback (most recent call last):
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
return fn()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
return _ConnectionFairy._checkout(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
rec = pool._do_get()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
self._dec_overflow()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
raise value
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
return self._create_connection()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
return _ConnectionRecord(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
self.__connect(first_connect_check=True)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
connection = pool._invoke_creator(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
return dialect.connect(*cargs, **cparams)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
return self.dbapi.connect(*cargs, **cparams)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
return Connection(*args, **kwargs)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/MySQLdb/connections.py", line 164, in __init__
super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 81, in wrapper
return func(*args, **kwargs)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 326, in _list_experiments
experiment_entities = _get_store().list_experiments(request_message.view_type)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 35, in _get_store
return SqlAlchemyStore(store_dir, artifact_root)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/mlflow/store/sqlalchemy_store.py", line 58, in __init__
Base.metadata.create_all(self.engine)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2032, in _run_visitor
with self._optional_conn_ctx_manager(connection) as conn:
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/contextlib.py", line 112, in __enter__
return next(self.gen)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2024, in _optional_conn_ctx_manager
with self._contextual_connect() as conn:
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2226, in _contextual_connect
self._wrap_pool_connect(self.pool.connect, None),
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect
e, dialect, self
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
raise value.with_traceback(tb)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
return fn()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
return _ConnectionFairy._checkout(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
rec = pool._do_get()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
self._dec_overflow()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
raise value
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
return self._create_connection()
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
return _ConnectionRecord(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
self.__connect(first_connect_check=True)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
connection = pool._invoke_creator(self)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
return dialect.connect(*cargs, **cparams)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
return self.dbapi.connect(*cargs, **cparams)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
return Connection(*args, **kwargs)
File "/home/asraful/anaconda3/envs/my_env/lib/python3.7/site-packages/MySQLdb/connections.py", line 164, in __init__
super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
My question is :

What i am missing here ? What could be the possible solution for this ?

**Comment by mateiz** [comment]
It sounds like you need to set the MLFLOW_TRACKING_URI environment variable or call mlflow.set_tracking_uri when running your Python code so that it actually logs to the server. Otherwise, your code will log to a local mlruns directory. Do you see a mlruns directory where you ran it?

**Comment by asraful** [comment]
@mateiz  this is fixed now .  two problem was there ,  one tracking uri was not set inside the script , and  installed everything from beginning , fixed this  issue.   closing this issue
