### ISSUE TITLE
[BUG] Couldn't deploy custom PythonModel with MLServer backend

### ISSUE THREAD

**Issue by ppiszczek** [mlflow/mlflow#12656]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.14.2
- Tracking server: 2.14.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 11 (bullseye)
- **Python version**: 3.11.9
- **yarn version, if running the dev UI**:

### Describe the problem

Following tutorial https://www.mlflow.org/docs/latest/traditional-ml/creating-custom-pyfunc/notebooks/override-predict.html I have created a PythonModel which imports model artifact in `load_context()` and provides customized `predict()` method.

Serving the model to get predictions works fine in case of: 
- loading model locally via `mlflow.pyfunc.load_model()` 
- deploying model to Local Inference Server: `mlflow models serve -m models:/model_name/version -p 1234 --env-manager local`

However, deploying model to MLServer using `mlflow models serve -m models:/model_name/version -p 1234 --env-manager local  --enable-mlserver` ends with errors: `Couldn't load model 'mlflow-model'. Model will be removed from registry` and `AttributeError: 'NoneType' object has no attribute 'inputs'`.

Using `mlserver` and `mlserver-mlflow` version: 1.6.0

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue
```
import sklearn
import joblib
from joblib import dump
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import mlflow
from mlflow.models import infer_signature
from mlflow.pyfunc import PythonModel

mlflow.set_tracking_uri("http://localhost:8080")

iris = load_iris()
x = iris.data[:, 2:]
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9001)

model = LogisticRegression(random_state=0, max_iter=5_000, solver="newton-cg").fit(x_train, y_train)


model_directory = "/tmp/sklearn_model.joblib"
dump(model, model_directory)


class ModelWrapper(PythonModel):
    def __init__(self):
        self.model = None

    def load_context(self, context):
        from joblib import load

        self.model = load(context.artifacts["model_path"])

    def predict(self, context, model_input, params=None):
        params = params or {"predict_method": "predict"}
        predict_method = params.get("predict_method")

        if predict_method == "predict":
            return self.model.predict(model_input)
        elif predict_method == "predict_proba":
            return self.model.predict_proba(model_input)
        elif predict_method == "predict_log_proba":
            return self.model.predict_log_proba(model_input)
        else:
            raise ValueError(f"The prediction method '{predict_method}' is not supported.")
            

artifacts = {"model_path": model_directory}
signature = infer_signature(x_train, params={"predict_method": "predict_proba"})

with mlflow.start_run():
    model_info = mlflow.pyfunc.log_model(
        artifact_path = "model",
        python_model = ModelWrapper(),
        input_example = x_train,
        signature = signature,
        artifacts = artifacts,
        registered_model_name = "dynamic_regressor",
        extra_pip_requirements = [
            "sklearn==" + sklearn.__version__,
            "joblib==" + joblib.__version__,
            ]
    )
        
mlflow models serve -m models:/dynamic_regressor/1 -p 1234 --env-manager local --enable-mlserver
```

### Stack trace
```
Downloading artifacts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 4777.11it/s]
2024/07/12 09:54:44 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'
Downloading artifacts: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 686.14it/s]
2024/07/12 09:54:44 WARNING mlflow.pyfunc.mlserver: Timeout is not yet supported in MLServer.
2024/07/12 09:54:44 INFO mlflow.pyfunc.backend: === Running command 'exec mlserver start /var/tmp/tmpcly7_99i/'
2024-07-12 09:54:46,396 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-07-12 09:54:46,398 [mlserver.rest] INFO - HTTP server running on http://127.0.0.1:1234
INFO:     Started server process [21231]
INFO:     Waiting for application startup.
2024-07-12 09:54:46,434 [mlserver.metrics] INFO - Metrics server running on http://127.0.0.1:8082
2024-07-12 09:54:46,436 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://127.0.0.1:8082/metrics
INFO:     Started server process [21231]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-07-12 09:54:47,310 [mlserver.grpc] INFO - gRPC server running on http://127.0.0.1:8081
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://127.0.0.1:8082 (Press CTRL+C to quit)
2024-07-12 09:54:49,959 [mlserver][mlflow-model] INFO - Couldn't load model 'mlflow-model'. Model will be removed from registry.
2024-07-12 09:54:49,960 [mlserver][mlflow-model] INFO - Unloaded model 'mlflow-model' successfully.
2024-07-12 09:54:49,960 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Load'.
Traceback (most recent call last):
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/worker.py", line 158, in _process_model_update
    await self._model_registry.load(model_settings)
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 299, in load
    return await self._models[model_settings.name].load(model_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 150, in load
    await self._load_model(new_model)
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 167, in _load_model
    model.ready = await model.load()
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver_mlflow/runtime.py", line 162, in load
    self._sync_metadata()
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver_mlflow/runtime.py", line 181, in _sync_metadata
    self.outputs = to_metadata_tensors(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver_mlflow/metadata.py", line 57, in to_metadata_tensors
    for idx, input_spec in enumerate(schema.inputs):
                                     ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'inputs'
2024-07-12 09:54:49,971 [mlserver][mlflow-model] INFO - Couldn't load model 'mlflow-model'. Model will be removed from registry.
2024-07-12 09:54:49,977 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Unload'.
Traceback (most recent call last):
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/worker.py", line 160, in _process_model_update
    await self._model_registry.unload_version(
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 308, in unload_version
    await model_registry.unload_version(version)
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 204, in unload_version
    model = await self.get_model(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 243, in get_model
    raise ModelNotFound(self._name, version)
mlserver.errors.ModelNotFound: Model mlflow-model not found
2024-07-12 09:54:49,981 [mlserver][mlflow-model] INFO - Unloaded model 'mlflow-model' successfully.
2024-07-12 09:54:49,981 [mlserver] ERROR - Some of the models failed to load during startup!
Traceback (most recent call last):
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/server.py", line 125, in start
    await asyncio.gather(
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 299, in load
    return await self._models[model_settings.name].load(model_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 150, in load
    await self._load_model(new_model)
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/registry.py", line 163, in _load_model
    model = await callback(model)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/registry.py", line 171, in load_model
    loaded = await pool.load_model(model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/pool.py", line 171, in load_model
    await self._dispatcher.dispatch_update(load_message)
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 229, in dispatch_update
    return await asyncio.gather(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 244, in dispatch_update_to_worker
    return await self._async_responses.schedule_and_wait(worker_update, worker)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 59, in schedule_and_wait
    return await self._wait(message_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mlops/lib/python3.11/site-packages/mlserver/parallel/dispatcher.py", line 87, in _wait
    response_message = await future
                       ^^^^^^^^^^^^
mlserver.parallel.errors.WorkerError: builtins.AttributeError: 'NoneType' object has no attribute 'inputs'
2024-07-12 09:54:49,986 [mlserver.parallel] INFO - Waiting for shutdown of default inference pool...
2024-07-12 09:54:50,580 [mlserver.parallel] INFO - Shutdown of default inference pool complete
2024-07-12 09:54:50,580 [mlserver.grpc] INFO - Waiting for gRPC server shutdown
2024-07-12 09:54:50,581 [mlserver.grpc] INFO - gRPC server shutdown complete
INFO:     Shutting down
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [21231]
INFO:     Application shutdown complete.
INFO:     Finished server process [21231]
2024-07-12 09:54:50,785 [mlserver.parallel] INFO - Waiting for shutdown of default inference pool...
2024-07-12 09:54:50,786 [mlserver.parallel] INFO - Shutdown of default inference pool complete
2024-07-12 09:54:50,786 [mlserver.parallel] INFO - Waiting for shutdown of default inference pool...
2024-07-12 09:54:50,786 [mlserver.parallel] INFO - Shutdown of default inference pool complete
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ppiszczek** [comment]
After some debugging I have found that this error was caused by missing `outputs` in signature. From source code of `mlserver-mlflow` it seems that if signature is defined for MLflow model, both `inputs` and `outputs` have to be specified.
```
signature:
  inputs: '[{"type": "tensor", "tensor-spec": {"dtype": "float64", "shape": [-1, 2]}}]'
  outputs: null
  params: '[{"name": "predict_method", "type": "string", "default": "predict_proba",
    "shape": null}]
 ```

**Comment by B-Step62** [comment]
@ppiszczek Thank you for reporting the issue and sharing additional debugging information!

Yes, it seems `mlserer-mlflow` fails to load the signature without outputs schema. Could you report the issue to MLserver repository? The following line triggers the issue.
https://github.com/SeldonIO/MLServer/blob/ce93346302fb3c521e1e92373af8962664370a1a/runtimes/mlflow/mlserver_mlflow/metadata.py#L57

For a temporary workaround, you can remove the `signature` parameter when logging the model. As you pass the `input_example`, MLflow automatically infers both input and output signature based on the example. You can pass a tuple of input data and parameters, so that the signature include parameter schema as well. 

```
with mlflow.start_run():
    model_info = mlflow.pyfunc.log_model(
        artifact_path = "model",
        python_model = ModelWrapper(),
        input_example = (x_train, {"predict_method": "predict_proba"}),
        artifacts = artifacts,
        registered_model_name = "dynamic_regressor",
        extra_pip_requirements = [
            "sklearn==" + sklearn.__version__,
            "joblib==" + joblib.__version__,
            ]
    )
```

Inferred signature:
```
signature:
  inputs: '[{"type": "tensor", "tensor-spec": {"dtype": "float64", "shape": [-1, 2]}}]'
  outputs: '[{"type": "tensor", "tensor-spec": {"dtype": "float64", "shape": [-1,
    3]}}]'
  params: '[{"name": "predict_method", "type": "string", "default": "predict_proba",
    "shape": null}]'
```

I could start the MLServer with the updated model.
