### ISSUE TITLE
[BUG] langchain - 

### ISSUE THREAD

**Issue by alexandre-daniel-ext** [mlflow/mlflow#12660]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow 2.14.2
- langchain 0.2.7
- langchain-openai 0.1.8
- mlflow server on databricks

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs 14.5
- **Python version**: 3.10.14

### Describe the problem

try to log to mlflow a langchain agent but got the error : "'OpenAIToolsAgentOutputParser -- Cannot save runnable without `save` method.'"

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Python version: 3.10.14
MLflow version: 2.14.2
MLflow module location: /Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: databricks
Registry URI: databricks
Active experiment ID: 780316364487388
Active run ID: 0bb19d1aff0f4a328a76c4c542fed8f4
Active run artifact URI: dbfs:/databricks/mlflow-tracking/780316364487388/0bb19d1aff0f4a328a76c4c542fed8f4/artifacts
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.9.5
  alembic: 1.13.2
  cachetools: 5.3.3
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 7.1.0
  entrypoints: 0.4
  fastapi: 0.111.0
  gitpython: 3.1.43
  graphene: 3.3
  gunicorn: 22.0.0
  importlib-metadata: 7.1.0
  langchain: 0.2.7
  markdown: 3.6
  matplotlib: 3.9.1
  numpy: 1.26.4
  opentelemetry-api: 1.25.0
  opentelemetry-sdk: 1.25.0
  packaging: 24.1
  pandas: 2.2.2
  protobuf: 4.25.3
  pyarrow: 15.0.2
  pydantic: 2.7.3
  pytz: 2024.1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.5.1
  scipy: 1.14.0
  sqlalchemy: 2.0.30
  sqlparse: 0.5.0
  tiktoken: 0.7.0
  uvicorn: 0.29.0
  watchfiles: 0.22.0
```

### Code to reproduce issue

```
from langchain_openai import AzureChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain.agents import AgentExecutor, create_openai_tools_agent

tools = [TavilySearchResults(max_results=1)]
prompt = hub.pull("hwchase17/openai-tools-agent")
llm = AzureChatOpenAI(
        azure_deployment="gpt-4-32k-last",
        openai_api_version="2023-07-01-preview",
    )
agent = create_openai_tools_agent(llm, tools, prompt)
mlflow.start_run()
mlflow.langchain.log_model(agent, "chat_agent")
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is LangChain?"})

```

### Stack trace

```
>>> mlflow.langchain.log_model(agent, "chat_agent")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/tracing/provider.py", line 237, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/langchain/__init__.py", line 557, in log_model
    return Model.log(
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/models/model.py", line 683, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/tracing/provider.py", line 241, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/langchain/__init__.py", line 356, in save_model
    model_data_kwargs = _save_model(lc_model, path, loader_fn, persist_dir)
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/langchain/__init__.py", line 591, in _save_model
    return _save_runnables(model, path, loader_fn=loader_fn, persist_dir=persist_dir)
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/langchain/runnables.py", line 447, in _save_runnables
    _save_runnable_with_steps(
  File "/Users/alex/Documents/VSCode_project/services/.venv/lib/python3.10/site-packages/mlflow/langchain/runnables.py", line 333, in _save_runnable_with_steps
    raise MlflowException(f"Failed to save runnable sequence: {unsaved_runnables}.")
mlflow.exceptions.MlflowException: Failed to save runnable sequence: {'2': 'AzureChatOpenAI -- MLflow langchain flavor only supports subclasses of langchain.chains.base.Chain, langchain.agents.agent.AgentExecutor, langchain.schema.BaseRetriever, langchain.schema.runnable.RunnableSequence, langchain.schema.runnable.RunnableLambda, langchain.schema.runnable.RunnableParallel, langchain.schema.runnable.RunnablePassthrough, langchain.schema.runnable.passthrough.RunnableAssign instances, found AzureChatOpenAI', '3': 'OpenAIToolsAgentOutputParser -- Cannot save runnable without `save` method.'}.
```

### Other info / logs

```

>>> ```


### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@alexandre-daniel-ext Thank you for reporting the issue! 

MLflow does not support saving the raw agent runnable. Instead, it needs to be wrapped with `AgentExecutor` instance, as described in [the LangChain tutorial](https://python.langchain.com/v0.1/docs/use_cases/question_answering/conversational_retrieval_agents/#agent-constructor).

However, I also found there is a bug in saving AgentExecutor with the your configuration. This seems to be a bug in MLflow, so we will investigate and fix that soon!

> AttributeError: 'RunnableMultiActionAgent' object has no attribute 'llm_chain'

Meanwhile, you can workaround the situation by using the newer [models-from-code](https://mlflow.org/docs/latest/models.html#models-from-code) method for saving a LangChain model.

1. Save the model definition in `chain.py` (or any other file name).
```
%%writefile chain.py
from langchain import hub
from langchain_openai import AzureChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain.agents import AgentExecutor, create_openai_tools_agent
import mlflow

tools = [TavilySearchResults(max_results=1)]
prompt = hub.pull("hwchase17/openai-tools-agent")
llm = AzureChatOpenAI(
        azure_deployment="gpt-4-32k-last",
        openai_api_version="2023-07-01-preview",
    )
agent = create_openai_tools_agent(llm, tools, prompt

mlflow.models.set_model(agent)
```

2. Log the model in the next cell, with specifying the file path as a model.

```
with mlflow.start_run():
    model_info = mlflow.langchain.log_model(
      lc_model="chain.py",
      artifact_path="chat_agent",
      input_example={"input": "Hi"},
    )
```

3. Then you can load the model and make prediction as usual.
```
loaded = mlflow.pyfunc.load_model(model_info.model_uri)
loaded.predict({"input": "Hi"})
```

**Comment by alexandre-daniel-ext** [comment]
Hi,
Thanks for your support.
The turnaround do not works because you can not make inference on an agent object (and indeed on an agent log in MLflow) : you must have an AgentExecutor associated and use the invoke method

Regards
Alex

**Comment by B-Step62** [comment]
@alexandre-daniel-ext 

> The turnaround do not works because you can not make inference on an agent object (and indeed on an agent log in MLflow) : you must have an AgentExecutor associated and use the invoke method

You can use the model-from-code with AgentExecutor.

```
%%writefile chain.py
from langchain import hub
from langchain_openai import AzureChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain.agents import AgentExecutor, create_openai_tools_agent
import mlflow

tools = [TavilySearchResults(max_results=1)]
prompt = hub.pull("hwchase17/openai-tools-agent")
llm = AzureChatOpenAI(
        azure_deployment="gpt-4-32k-last",
        openai_api_version="2023-07-01-preview",
    )
agent = create_openai_tools_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools)

mlflow.models.set_model(agent_executor)
```

**Comment by prajwalbn** [comment]
@alexandre-daniel-ext Were you able to resolve this issue for your use case ? I am using Databricks to create a SQL agent and facing the same error when deploying the agent!
