### ISSUE TITLE
[BUG] OpenAI `chat.StreamResponsePayload` schema expects `object` to be literal `chat.completion.chunk`

### ISSUE THREAD

**Issue by danilopeixoto** [mlflow/mlflow#12767]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.14.3
- Tracking server: 2.14.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10
- **yarn version, if running the dev UI**: N/A

### Describe the problem

OpenAI `chat.StreamResponsePayload` schema expects `object` to be literal `chat.completion.chunk`. However, Azure OpenAI Service can return object `""`:

```json
{"choices": [], "created": 0, "id": "", "model": "", "object": "", "prompt_filter_results": [{"prompt_index": 0, "content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}}]}
```

https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#example

### Tracking information

```shell
mlflow deployments start-server --config-path config.yaml
```

### Code to reproduce issue

```yaml
endpoints:
  - name: gpt-4-turbo-chat
    endpoint_type: llm/v1/chat
    model:
        provider: openai
        name: gpt-4-turbo
        config:
            openai_api_base: 'openai_api_base'
            openai_api_key: 'openai_api_key'
            openai_api_type: azure
            openai_api_version: '2024-02-01'
            openai_deployment_name: gpt-4-turbo
    limit:
        renewal_period: minute
        calls: 3
```

### Stack trace

```
During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/responses.py", line 258, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/conda/envs/test/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/opt/conda/envs/test/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/opt/conda/envs/test/lib/python3.10/site-packages/mlflow/gateway/utils.py", line 308, in <genexpr>
    |     (to_sse_chunk(d.json()) async for d in resp),
    |   File "/opt/conda/envs/test/lib/python3.10/site-packages/mlflow/gateway/providers/openai.py", line 108, in chat_stream
    |     yield chat.StreamResponsePayload(
    |   File "/opt/conda/envs/test/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    |     self.__pydantic_validator__.validate_python(data, self_instance=self)
    | pydantic_core._pydantic_core.ValidationError: 1 validation error for StreamResponsePayload
    | object
    |   Input should be 'chat.completion.chunk' [type=literal_error, input_value='', input_type=str]
    |     For further information visit https://errors.pydantic.dev/2.8/v/literal_error
    +------------------------------------
```

### Other info / logs

```
N/A
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by danilopeixoto** [comment]
@harupy @gabrielfu I'm wondering if we could support Azure OpenAI Service endpoints with content filters enabled.

I dropped the `Literal` types for `str` type and the requests worked fine.

**Comment by gabrielfu** [comment]
Thanks for raising this. Can you help clarify how it is related to Azure content filtering? (if you disable it, does it still raise error?)

Also, can you send a streaming request without using MLflow and show us the entire streaming response with all chunks?

**Comment by danilopeixoto** [comment]
I have no capability to disable it easily. I will recheck it. However, I have the complete streaming request and response:

Request:

```json
{
    "temperature": 0.7,
    "n": 1,
    "stream": true,
    "messages": [
        {
            "role": "system",
            "content": "You are a conversational assistant living in IDE to help users.\nYou are not a language model, but rather an application built on a foundation model from AI Gateway called gpt-4-turbo.\nYou are talkative and you provide lots of specific details from the foundation model's context.\nYou may use Markdown to format your response.\nCode blocks must be formatted in Markdown.\nMath should be rendered with inline TeX markup, surrounded by $.\nIf you do not know the answer to a question, answer truthfully by responding that you do not know.\nThe following is a friendly conversation between you and a human."
        },
        {
            "role": "user",
            "content": "Hi!"
        }
    ],
    "logprobs": false
}
```

Response with `Literal[...]` type:

```json
{
    "choices": [],
    "created": 0,
    "id": "",
    "model": "",
    "object": "",
    "prompt_filter_results": [
        {
            "prompt_index": 0,
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ]
}
```

```
object
    |   Input should be 'chat.completion.chunk' [type=literal_error, input_value='', input_type=str]
    |     For further information visit https://errors.pydantic.dev/2.8/v/literal_error
```

Response with `str` type:

```json
{"choices": [], "created": 0, "id": "", "model": "", "object": "", "prompt_filter_results": [{"prompt_index": 0, "content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}}]}
{"choices": [{"content_filter_results": {}, "delta": {"content": "", "role": "assistant"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": "Hello"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": "!"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " How"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " can"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " I"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " assist"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " you"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": " today"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "delta": {"content": "?"}, "finish_reason": null, "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
{"choices": [{"content_filter_results": {}, "delta": {}, "finish_reason": "stop", "index": 0}], "created": 1721941558, "id": "chatcmpl-9ozws7h20VTcc0yzY3SRWLIjFgvuj", "model": "gpt-4", "object": "chat.completion.chunk", "system_fingerprint": "fp_811936bd4f"}
```

**Comment by danilopeixoto** [comment]
@gabrielfu  I believe it is related to this: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cuser-prompt%2Cpython-new#annotations-and-sample-responses

**Comment by gabrielfu** [comment]
Our response schema conforms to OpenAI and seems like Azure doesn't. 

I'm inclined to removing chunks with `id=""`, they represent Azure content filtering result.

Since our non-stream response model doesn't include content filtering either, I don't think it's a good idea to suddenly include streaming content filtering chunks.

@harupy what do you think? (ref: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cuser-prompt%2Cpython-new#sample-response-stream-passes-filters )

**Comment by danilopeixoto** [comment]
The provider today seems to be hybrid, with all the code below implemented:
https://github.com/mlflow/mlflow/blob/36227fcfcee9656c807bbb4180e5829ff04faf66/mlflow/gateway/providers/openai.py#L55

I believe before this issue, it was considered an implementation that fully supported both OpenAI and Azure OpenAI Service contracts. We find that the provider will now partially support the Azure OpenAI Service contract.

@gabrielfu But what if it still continues supporting the Azure contract fully? In that case, the `id=""` might still be useful for clients.

For that to happen, could we describe and add the `prompt_filter_results` as an `Optional[PromptFilterResults]` type?

**Comment by danilopeixoto** [comment]
@gabrielfu @harupy We found two major issues in the embeddings schema related to OpenAI (https://platform.openai.com/docs/api-reference/embeddings/create) and we would like to apply fixes along with content filter support:

- request should support `input: Union[str, List[int], List[str], List[List[int]]]`
- request should support `encoding_format: Optional[Literal["float", "base64"]] = "float"`
- `EmbeddingObject` response should comply with `encoding_format`: `embedding: Union[List[float], str]`

**Comment by harupy** [comment]
@danilopeixoto Thanks for reporting this. Does the OpenAI python SDK also have this issue?

**Comment by danilopeixoto** [comment]
@harupy The OpenAI SDK interface follows the API: https://github.com/openai/openai-python/blob/195c05a64d39c87b2dfdf1eca2d339597f1fce03/src/openai/resources/embeddings.py#L36.

For example, when specifying`encoding_format` as `base64` in the OpenAI SDK connected to the MLflow Deployments Server's OpenAI-compatible endpoints, we encounter issues because the MLflow endpoint response typing expects only `List[float]`.

**Comment by harupy** [comment]
Does the OpenAI SDK accept `"object": ""`?

**Comment by danilopeixoto** [comment]
@harupy The OpenAI SDK does not provide typing to support "object": "": https://github.com/openai/openai-python/blob/195c05a64d39c87b2dfdf1eca2d339597f1fce03/src/openai/types/chat/chat_completion_chunk.py#L122.

However, the typing from the SDK does not raise an error when using the Azure OpenAI Service. There is no explicit validation implemented (such as those usually implemented in APIs). As a result, the SDK supports the following non-transparently:

Chat completions:

```python
from openai import AzureOpenAI


client = AzureOpenAI(
    azure_endpoint="<azure-endpoint>",
    azure_deployment="gpt-4-turbo",
    api_key="<api-key>",
    api_version="2024-02-01"
)

response = client.chat.completions.create(
    model="gpt-4-turbo",
    stream=True,
    messages=[
        {
            "role": "system",
            "content": "You are a conversational assistant living in IDE to help users.\nYou are not a language model, but rather an application built on a foundation model from AI Gateway called gpt-4-turbo.\nYou are talkative and you provide lots of specific details from the foundation model's context.\nYou may use Markdown to format your response.\nCode blocks must be formatted in Markdown.\nMath should be rendered with inline TeX markup, surrounded by $.\nIf you do not know the answer to a question, answer truthfully by responding that you do not know.\nThe following is a friendly conversation between you and a human."
        },
        {
            "role": "user",
            "content": "Hi!"
        }
    ]
)

for chunk in response:
    print(chunk)
    print("---")
```

Output:

```
ChatCompletionChunk(id='', choices=[], created=0, model='', object='', service_tier=None, system_fingerprint=None, usage=None, prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}])
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content='Hello', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content='!', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' How', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' can', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' I', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' assist', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' you', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' today', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content='?', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=' 😊', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=None, content_filter_results={'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
---
ChatCompletionChunk(id='chatcmpl-9qD2YV4xUaYMPaXzYurlOaUwfECbU', choices=[Choice(delta=ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=None, content_filter_results={})], created=1722230210, model='gpt-4', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_811936bd4f', usage=None)
```


I suspect this is probably the reason Azure team found that was a good idea to implement it like that. The tests passed in the OpenAI SDK without strict type checking.

**Comment by harupy** [comment]
Interesting. How does the OpenAI SDK skip validation?

**Comment by harupy** [comment]
I see, the SDK uses their own `BaseModel`, not `pydantic.BaseModel`.

**Comment by harupy** [comment]
I ran this code and validation failed:

```python
from openai.types.chat import ChatCompletionChunk

ChatCompletionChunk(
    id="cmpl-3l4Kq6X7FVl3j1x6Z2xLXWQJ",
    object="foo",
    created=1645660168,
    model="text-davinci-003",
)
```

wonder what magic is used in the OpenAI SDK.

**Comment by danilopeixoto** [comment]
@harupy The magic is enabled by the client argument `_strict_response_validation` (sets to `False` by default):

```python
client = AzureOpenAI(
    azure_endpoint="<azure-endpoint>",
    azure_deployment="gpt-4-turbo",
    api_key="<api-key>",
    api_version="2024-02-01",
    _strict_response_validation=True # This will make strict validations and the request will fail like in MLflow
)
```

![image](https://github.com/user-attachments/assets/a634708d-4876-4cac-b5e8-fc36179faa95)

The magic is executed by `construct_type` function:

```python
from typing import cast

from openai.types.chat import ChatCompletionChunk
from openai._models import construct_type


content = {
    'id': '',
    'choices': [],
    'created': 0,
    'model': '',
    'object': '',
    'service_tier': None,
    'system_fingerprint': None,
    'usage': None,
    'prompt_filter_results': [
        {
            'prompt_index': 0,
            'content_filter_results': {
                'hate': {
                    'filtered': False,
                    'severity':
                    'safe'
                },
                'self_harm': {
                    'filtered': False,
                    'severity': 'safe'
                },
                'sexual': {
                    'filtered': False,
                    'severity': 'safe'
                },
                'violence': {
                    'filtered': False,
                    'severity': 'safe'
                }
            }
        }
    ]
}

response = cast(ChatCompletionChunk, construct_type(type_=ChatCompletionChunk, value=content))
print(response)
```

```
ChatCompletionChunk(id='', choices=[], created=0, model='', object='', service_tier=None, system_fingerprint=None, usage=None, prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}])
```
