### ISSUE TITLE
[BUG] SQLite Server with memory backend: Experiment creation unreliable

### ISSUE THREAD

**Issue by MichelBartelsQC** [mlflow/mlflow#12783]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.3
- Tracking server: 2.14.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 14.4
- **Python version**: 3.12
- **yarn version, if running the dev UI**:

### Describe the problem

The expected behaviour is that the code written below does not fail.
It works as expected when you are not running a server (`client = MlflowClient("sqlite:///:memory:")` or are storing the db in a file (`mlflow server --backend-store-uri sqlite:///test.db`).
I could also reproduce the bug on Ubuntu. It also occurs when you are creating runs instead of experiments. Sleeping for a few seconds after creating the experiment also does not fix it.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```bash
mlflow server --backend-store-uri sqlite:///:memory:
```

```py
from mlflow.client import MlflowClient

client = MlflowClient("http://localhost:5000")

i = 0
while True:
    experiment = client.create_experiment(str(i))
    client.get_experiment(experiment)
    i += 1
```

### Stack trace

```
Traceback (most recent call last):
  File "[...]/bug.py", line 9, in <module>
    client.get_experiment(experiment)
  File "[...]/python3.12/site-packages/mlflow/tracking/client.py", line 1206, in get_experiment
    return self._tracking_client.get_experiment(experiment_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 472, in get_experiment
    return self.store.get_experiment(experiment_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 137, in get_experiment
    response_proto = self._call_endpoint(GetExperiment, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.12/site-packages/mlflow/utils/rest_utils.py", line 304, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.12/site-packages/mlflow/utils/rest_utils.py", line 174, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: No Experiment with id={id} exists
```
where id is some integer that varies. It is usually quite small (1, 2 or 3)

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@MichelBartelsQC I don't think this is a bug. `mlflow server --backend-store-uri sqlite:///:memory:` spawns 4 workers. Each worker uses independent in-memory databases. Do you expect them to use **_the same in-memory_** database?

**Comment by harupy** [comment]
@MichelBartelsQC 

You can set the number of workers to 1 using `--workers 1`:

```
mlflow server --backend-store-uri sqlite:///:memory: --workers 1
```

https://github.com/user-attachments/assets/bc046ce5-0519-42e2-a15a-393e122bb858

**Comment by MichelBartelsQC** [comment]
Thanks, that fixes it.
