### ISSUE TITLE
[BUG] ValueError: Classification metrics can't handle a mix of unknown and binary targets when using mlflow.evaluate with model loaded from model_uri

### ISSUE THREAD

**Issue by robmcd** [mlflow/mlflow#12822]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.10

### Describe the problem

I'm getting an error when trying to evaluate a binary classification pyfunc model loaded from mlflow via model URI. The same model was able to be evaluated successfully prior to initially being logged.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

I am unable to provide code sample.

### Stack trace

```
Traceback (most recent call last):
  File "C:\dev\ws\proj\.venv\lib\site-packages\typer\main.py", line 326, in __call__
    raise e
  File "C:\dev\ws\proj\.venv\lib\site-packages\typer\main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\dev\ws\proj\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\dev\ws\proj\.venv\lib\site-packages\typer\core.py", line 661, in main
    return _main(
  File "C:\dev\ws\proj\.venv\lib\site-packages\typer\core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "C:\dev\ws\proj\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\dev\ws\proj\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\dev\ws\proj\.venv\lib\site-packages\typer\main.py", line 692, in wrapper
    return callback(**use_params)
  File "C:\dev\ws\proj\training.py", line 415, in eval_model
    eval_result = evaluate_model(
  File "C:\dev\ws\proj\training.py", line 302, in evaluate_model
    eval_result = mlflow.evaluate(
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\base.py", line 2131, in evaluate
    evaluate_result = _evaluate(
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\base.py", line 1309, in _evaluate
    eval_result = evaluator.evaluate(
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 2056, in evaluate
    evaluation_result = self._evaluate(model, is_baseline_model=False)
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1927, in _evaluate
    self._handle_builtin_metrics_by_model_type()
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1842, in _handle_builtin_metrics_by_model_type
    self._compute_builtin_metrics()
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1555, in _compute_builtin_metrics
    metrics = _get_binary_classifier_metrics(
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 281, in _get_binary_classifier_metrics
    tn, fp, fn, tp = sk_metrics.confusion_matrix(y_true, y_pred).ravel()
  File "C:\dev\ws\proj\.venv\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "C:\dev\ws\proj\.venv\lib\site-packages\sklearn\metrics\_classification.py", line 319, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "C:\dev\ws\proj\.venv\lib\site-packages\sklearn\metrics\_classification.py", line 94, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of unknown and binary targets
```

### Other info / logs

sklearn is saying that type of y_pred is "binary" but type of y_true is "unknown" 

![image](https://github.com/user-attachments/assets/cb85f905-ec10-439b-a0d8-ab30d35e5293)

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@robmcd Please provide code to repro, otherwise we can't help.
