### ISSUE TITLE
Error while integrating Ollama + llamaindex + mlflow

### ISSUE THREAD

**Issue by pavanjava** [mlflow/mlflow#12834]
### Description
Issue with mlflow==2.15.0 and llamaindex==0.10.58 while trying to integrate llamaindex with ollama and the inference call gives error

### Expected:
Normal output

### Error:
`TypeError: Ollama.__init__() got an unexpected keyword argument 'system_prompt'`

### Example code taken from user guide
```
with mlflow.start_run() as run:

    mlflow.llama_index.log_model(
        index,
        artifact_path="llama_index",
        engine_type="query",  # Defines the pyfunc and spark_udf inference type
        input_example="What are Context LLMs?",  # Infers signature
        registered_model_name="my_llama_index_vector_store",  # Stores an instance in the model registry
    )

    run_id = run.info.run_id
    model_uri = f"runs:/{run_id}/llama_index"
    print(f"Unique identifier for the model location for loading: {model_uri}")

    print("\n------------- Inference via Llama Index   -------------")
    index = mlflow.llama_index.load_model(model_uri)
    query_response = index.as_query_engine().query("What are Context LLMs?")
    print(query_response)
```

**Comment by serena-ruan** [comment]
@pavanjava Could you provide stacktrace?

**Comment by pavanjava** [comment]
> @pavanjava Could you provide stacktrace?

Traceback (most recent call last):
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/playground.py", line 47, in <module>
    index = mlflow.llama_index.load_model(model_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/tracing/provider.py", line 237, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/__init__.py", line 360, in load_model
    deserialize_settings(settings_path)
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/serialize_objects.py", line 171, in deserialize_settings
    settings_dict = _deserialize_dict_of_objects(path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/serialize_objects.py", line 117, in _deserialize_dict_of_objects
    output.update({k: dict_to_object(v)})
                      ^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/serialize_objects.py", line 105, in dict_to_object
    return object_class.from_dict(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/schema.py", line 125, in from_dict
    return cls(**data)
           ^^^^^^^^^^^
TypeError: Ollama.__init__() got an unexpected keyword argument 'system_prompt'

**Comment by pavanjava** [comment]
@serena-ruan Just for your information
<img width="605" alt="Screenshot 2024-07-31 at 10 10 42 AM" src="https://github.com/user-attachments/assets/964d6d51-6893-4c60-bd94-ae32a50b52b0">

<img width="780" alt="Screenshot 2024-07-31 at 10 07 05 AM" src="https://github.com/user-attachments/assets/af46f8a2-95b3-4c32-9f1e-aad8cb8eaad5">


The implementation of OpenAI and Ollama classes are different. OpenAI has `system_prompt` where as Ollama does not have it.

**Comment by serena-ruan** [comment]
@pavanjava Are you using `system_prompt` in global llamaindex settings object? From the stacktrace seems it's reading args from the saved settings, and that settings file should save the global settings. You could also check your run's artifacts storage to see if `system_prompt` is saved into the "settings.json" file

**Comment by pavanjava** [comment]
No I am not using any `system_prompt` in global Settings. is it recommended to use? I don't think its mandatory.

**Comment by serena-ruan** [comment]
I guess system_prompt is saved inside llm and it's saved when you use `Settings.llm = llm`. cc @B-Step62 I haven't looked deeper at the code, but seems like we're saving all configs together and then the config used by llm is accidentally used by OllamaEmbedding when we load the model back. Could you take a look?

**Comment by B-Step62** [comment]
@pavanjava This is an issue in LlamaIndex side, which accidentally removes `kwargs` from the constructor. The fix was merged to the `master` branch last week https://github.com/run-llama/llama_index/pull/14963, so I supposed it will be available in next LlamaIndex release soon!
