### ISSUE TITLE
mlflow.pyfunc.log_model failing with error : yaml.representer.RepresenterError: ('cannot represent an object'

### ISSUE THREAD

**Issue by akshat-40** [mlflow/mlflow#12882]
Hi, I am using mlflow 2.15.0. I am using mlflow.pyfunc for logging custom autoTS model. I am getting below error:
```
Traceback (most recent call last):
  File "/Users/aksarawg/Desktop/Data analytics/Multi_step_prophet/train.py", line 268, in <module>
    mlflow.pyfunc.log_model(model, "model")
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/tracing/provider.py", line 237, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 2820, in log_model
    return Model.log(
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/models/model.py", line 698, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/tracing/provider.py", line 241, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 2567, in save_model
    return _save_model_with_loader_module_and_data_path(
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 2902, in _save_model_with_loader_module_and_data_path
    mlflow_model.save(os.path.join(path, MLMODEL_FILE_NAME))
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/models/model.py", line 591, in save
    self.to_yaml(out)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/mlflow/models/model.py", line 579, in to_yaml
    return yaml.safe_dump(self.to_dict(), stream=stream, default_flow_style=False)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/__init__.py", line 269, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Users/aksarawg/anaconda3/envs/mlflow-601f2cf3e27cac06183c30a4dd0c6468e5359f94/lib/python3.10/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', Initiated AutoTS object with best model: 
FFT
{'fillna': 'rolling_mean_24', 'transformations': {'0': 'Slice', '1': 'Round', '2': 'SeasonalDifference', '3': 'ClipOutliers', '4': 'PCA', '5': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 100}, '1': {'decimals': 0, 'on_transform': True, 'on_inverse': False}, '2': {'lag_1': 7, 'method': 'Mean'}, '3': {'method': 'remove', 'std_threshold': 4, 'fillna': 'mean'}, '4': {'whiten': False, 'n_components': None}, '5': {'method': 'zscore', 'method_params': {'distribution': 'chi2', 'alpha': 0.05}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': 'ffill', 'transformations': {'0': 'AlignLastValue', '1': 'bkfilter'}, 'transformation_params': {'0': {'rows': 1, 'lag': 7, 'method': 'multiplicative', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '1': {}}}, 'isolated_only': False}}}
{'n_harmonics': 6, 'detrend': 'linear'}
Validation: 0, 1, 2
SMAPE: 0.26693577187060774, 0.2416566835430564, 0.28264902177100176
MAE: 2.716503098655199, 2.4505803745531627, 2.845562179741393
SPL: 0.06372034246841049, 0.06897768916207393, 0.06768634778175832)
2024/08/05 15:46:51 ERROR mlflow.cli: === Run (ID 'efdbfd7a5cd7485a9c63c36ae0299087') failed ===
```

Auto-TS model code:
```
from autots import AutoTS
df_train = pd.DataFrame(train_dict)
df_train = df_train.set_index('ds')
test_dict = {'ds': pd.to_datetime(test_X), 'y': test_y}
df_test = pd.DataFrame(test_dict)
df_test = df_test.set_index('ds')

# Set mlflow experiment
mlflow.set_experiment('Prophet Bandwidth Prediction')

# Starting mlflow run
with mlflow.start_run():
    artifact_uri = mlflow.get_artifact_uri()
    
    # Train model
    model = AutoTS(
        forecast_length=test_size,
        frequency='D',
        prediction_interval=0.95,
        ensemble=None,
        models_mode='deep',
        model_list = ['ARDL', 'GLS', 'DatepartRegression', 'GLM', 'FFT', 'UnivariateMotif', 'FBProphet', 'SeasonalNaive', 'ARCH', 'AverageValueNaive', 'MLEnsemble', 'NeuralProphet', 'ETS', 'UnobservedComponents'],# or 'univariate'
        max_generations=10,
        num_validations=3,
        no_negatives=True,
        n_jobs='auto')
    model.fit(df_train)
    (rmse, mae, r2, mape) = eval_metrics(test_y, y_pred)
    # Log mlflow model metrics and parameters
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2", r2)
    mlflow.log_metric("mae", mae)
    mlflow.log_metric("mape", mape)
    
    mlflow.pyfunc.log_model(model, "model")
```

**Comment by daniellok-db** [comment]
`mlflow.pyfunc.log_model()` is meant to be used with subclasses of `mlflow.pyfunc.PythonModel` (see [this section of the docs](https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#class-based-model))

You might have to save your model separately, and load the saved model within your `load_context()` see ([this guide](https://mlflow.org/docs/latest/traditional-ml/creating-custom-pyfunc/notebooks/override-predict.html#Defining-our-custom-PythonModel)). 

However, a [comment from the AutoTS maintainer](https://github.com/winedarksea/AutoTS/issues/51#issuecomment-783417655) says that they don't recommend saving the models. Is there a particular reason you want to log the model as opposed to some artifacts / results?

**Comment by akshat-40** [comment]
Thanks @daniellok-db 
Will check if my application works without the need for saving the model.
