### ISSUE TITLE
[BUG] AzureBlobArtifactRepository files for us govcloud endpoint

### ISSUE THREAD

**Issue by ahringer** [mlflow/mlflow#12921]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.15.0
- Tracking server: 2.15.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.4 LTS
- **Python version**:  3.10.12
- **yarn version, if running the dev UI**: N/A

### Describe the problem

parse_wasbs_uri in AzureBlobArtifactRepository class only looks for US commercial and China clouds:

  match = re.match(
            r"([^@]+)@([^.]+)\.(blob\.core\.(windows\.net|chinacloudapi\.cn))", parsed.netloc
        )

It fails for us gov cloud environment:  usgovcloudapi.net

should be:
  match = re.match(
            r"([^@]+)@([^.]+)\.(blob\.core\.(windows\.net|chinacloudapi\.cn|usgovcloudapi\.net))", parsed.netloc
        )

### Tracking information

```shell
mlflow server  --artifacts-destination wasbs://mlflow@xxxxxxx.blob.core.usgovcloudapi.net/ --backend-store-uri $BACKEND_URI --host 0.0.0.0 --port 5000 --serve-artifacts
```

### Code to reproduce issue

```
 mlflow artifacts list -r <runId>
```

### Stack trace

```
2024/08/09 14:48:51 ERROR mlflow.server: Exception on /api/2.0/mlflow-artifacts/artifacts [GET]
Traceback (most recent call last):
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/server/handlers.py", line 566, in wrapper
    return func(*args, **kwargs)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/server/handlers.py", line 588, in wrapper
    return func(*args, **kwargs)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/server/handlers.py", line 2174, in _list_artifacts_mlflow_artifacts
    artifact_repo = _get_artifact_repo_mlflow_artifacts()
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/server/handlers.py", line 191, in _get_artifact_repo_mlflow_artifacts
    _artifact_repo = get_artifact_repository(os.environ[ARTIFACTS_DESTINATION_ENV_VAR])
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 133, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 78, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 57, in __init__
    (_, account, _, api_uri_suffix) = AzureBlobArtifactRepository.parse_wasbs_uri(artifact_uri)
  File "/home/azureuser/mlflow-env/lib/python3.10/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 99, in parse_wasbs_uri
    raise Exception(
Exception: WASBS URI must be of the form <container>@<account>.blob.core.windows.net or <container>@<account>.blob.core.chinacloudapi.cn

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ahringer** [comment]
[dupe of 9657](https://github.com/mlflow/mlflow/issues/9657)

**Comment by WeichenXu123** [comment]
I will close the duplicated issue. please track https://github.com/mlflow/mlflow/issues/9657
