### ISSUE TITLE
Unable to store mlflow artifacts on mounted pvc

### ISSUE THREAD

**Issue by akshat-40** [mlflow/mlflow#12941]
Hi team,
I am using PVC for storing mlflow model artifacts. I have mounted pvc in /mlruns path. Gave "--default-artifact-root /mlruns" parameter for mlflow server command.

While running mlflow, it is failing while artifact store as seen below:
```
Traceback (most recent call last):
  File "/Users/aksarawg/Desktop/Data analytics/Multi_step_prediction/train_xgboost.py", line 201, in <module>
    mlflow.xgboost.log_model(model, "model")
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/xgboost/__init__.py", line 264, in log_model
    return Model.log(
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/models/model.py", line 714, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1147, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1962, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 843, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 66, in log_artifacts
    mkdir(artifact_dir)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/utils/file_utils.py", line 211, in mkdir
    raise e
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/site-packages/mlflow/utils/file_utils.py", line 208, in mkdir
    os.makedirs(target, exist_ok=True)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/Users/aksarawg/anaconda3/envs/mlflow-2d51264705cac92f7d9b7804ea498a3ad7eae202/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/mlruns'
```

**Comment by akshat-40** [comment]
When I am running the same command mentioned in from mlflow pod, it is working as seen below -
```
(base) bash-5.1# cat aks.py 
import os
path = "/mlruns/1/65d22d2c6814449aa431b8877d9a53d0/artifacts/model"

os.makedirs(path, exist_ok=True)
#os.mkdir(path);
print ("Path is created")
(base) bash-5.1# python3 aks.py 
Path is created
(base) bash-5.1# ls /mlruns/                                                  
1/          lost+found/ 
(base) bash-5.1# ls /mlruns/1/65d22d2c6814449aa431b8877d9a53d0/
artifacts
(base) bash-5.1# 
```
