### ISSUE TITLE
google.protobuf.json_format.ParseError: Failed to parse run field: Failed to parse info field: Message type "mlflow.RunInfo" has no field named "lifecycle_stage".

### ISSUE THREAD

**Issue by asraful** [mlflow/mlflow#1296]
Environment information :

mlflow, version 0.9.1
Python 3.6.7
conda 4.6.8

Started mllfow tracking server using : 

mlflow server --backend-store-uri mysql://root:password@localhost:3306/mlflow_tracker --default-artifact-root /home/ubuntu/mlflow_bucket --host 0.0.0.0

Test script #

```
import os
import mlflow
from mlflow import log_metric, log_param, log_artifact

if __name__ == "__main__":
    # Log a parameter (key-value pair
    mlflow.set_tracking_uri("http://localhost:5000");
    log_param("param1", 5)

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output.txt", "w") as f:
        f.write("Hello world!")
    log_artifact("output.txt")
```

Now trying to run above script as :   **python test.py**

unfortunately i am getting bellow error : 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 507, in _ConvertFieldValuePair
    [f.json_name for f in message_descriptor.fields]))
google.protobuf.json_format.ParseError: Message type "mlflow.RunInfo" has no field named "lifecycle_stage".
 Available Fields(except extensions): ['runUuid', 'experimentId', 'name', 'sourceType', 'sourceName', 'userId', 'status', 'startTime', 'endTime', 'sourceVersion', 'entryPointName', 'tags', 'artifactUri']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 565, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 470, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 572, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "mlflow.RunInfo" has no field named "lifecycle_stage".
 Available Fields(except extensions): ['runUuid', 'experimentId', 'name', 'sourceType', 'sourceName', 'userId', 'status', 'startTime', 'endTime', 'sourceVersion', 'entryPointName', 'tags', 'artifactUri']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 565, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 470, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 570, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse info field: Message type "mlflow.RunInfo" has no field named "lifecycle_stage".
 Available Fields(except extensions): ['runUuid', 'experimentId', 'name', 'sourceType', 'sourceName', 'userId', 'status', 'startTime', 'endTime', 'sourceVersion', 'entryPointName', 'tags', 'artifactUri']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    log_param("param1", 5)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 341, in log_param
    _get_or_start_run().log_param(Param(key, str(value)))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 314, in _get_or_start_run
    return start_run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 306, in start_run
    source_type=source_type or _get_source_type())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 243, in _create_run
    source_version=source_version, tags=[])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 152, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 83, in _call_endpoint
    ParseDict(js_dict=js_dict, message=response_proto)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 439, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 470, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/opt/conda/lib/python3.6/site-packages/google/protobuf/json_format.py", line 570, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse run field: Failed to parse info field: Message type "mlflow.RunInfo" has no field named "lifecycle_stage".
 Available Fields(except extensions): ['runUuid', 'experimentId', 'name', 'sourceType', 'sourceName', 'userId', 'status', 'startTime', 'endTime', 'sourceVersion', 'entryPointName', 'tags', 'artifactUri']

```

**Comment by asraful** [comment]
root cause  #  server and client was running with two different version of mlflow.  
fact is : one old installation was there in conda, and we installed new one also .
But, old one didn't removed properly . Say : we are running mllfow 0.9 server . But while executing experiment its picking up old version of mllfow from conda path.

Solution : removed old installation of mlflow , and installed newly , pip install --user mlflow.
Also , we should not mix up with, pip, pi3 and sudo pip while installing things.

Issue fixed, therefor closing the issue.
