### ISSUE TITLE
Exceptions when using "mlflow run"

### ISSUE THREAD

**Issue by HongHuangNeu** [mlflow/mlflow#130]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.1
- **MLflow installed from (source or binary)**:  pip install
- **MLflow version (run ``mlflow --version``)**: 0.1.0
- **Python version**: 2.7.13 

### Describe the problem
Got exceptions when I run "mlflow run    working_directory_name "

### Source code / logs
The command I used: "mlflow run ." to run the whole project as a mlflow Project,  I am not sure if this is a bug. The log is as follows:

=== Fetching project from . ===
=== Work directory for this run: . ===
=== Created directory /var/folders/p_/tdkm1f5159vdght67bhbc8rh0000gn/T/tmpHes0sB for downloading remote URIs passed to arguments of type 'path' ===
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mlflow/cli.py", line 117, in run
    use_temp_cwd=new_dir, storage_dir=_encode(storage_dir))
  File "/usr/local/lib/python2.7/site-packages/mlflow/projects.py", line 284, in run
    storage_dir=storage_dir)
  File "/usr/local/lib/python2.7/site-packages/mlflow/projects.py", line 247, in _run_local
    _run_project(project, entry_point, work_dir, parameters, use_conda, storage_dir, experiment_id)
  File "/usr/local/lib/python2.7/site-packages/mlflow/projects.py", line 367, in _run_project
    (exit_code, _, stderr) = process.exec_cmd(["conda", "--help"], throw_on_error=False)
  File "/usr/local/lib/python2.7/site-packages/mlflow/utils/process.py", line 38, in exec_cmd
    cmd, env=cmd_env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by mparkhe** [comment]
hi @HongHuangNeu,

The error suggests that you prolly dont have `git` installed. Can you verify that. Also `mlflow run` expects an MLproject like this [example/tutorial](https://github.com/databricks/mlflow/tree/master/example/tutorial) in directory argument. In this case current directory since you are executing `mlflow run .`

It looks like you are using 0.1 version. I recommending upgrading to latest version of mlflow. using `pip install --upgrade mlflow` in your virtual environment.

**Comment by smurching** [comment]
Thanks @mparkhe -  @HongHuangNeu were you able to resolve the issues with @mparkhe's suggestions? It also looks like `conda` may not be installed, you can install it here: https://conda.io/miniconda.html. We do expect `mlflow run .` within a project to work - let me know if these suggestions work & we can close this issue :)

**Comment by tomasatdatabricks** [comment]
Timed out.
