### ISSUE TITLE
[BUG] MLServer import fails when running tests in dev and build environment

### ISSUE THREAD

**Issue by rzalawad** [mlflow/mlflow#13037]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: mlflow, version 2.15.2.dev0
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 14.5
- **Python version**: 3.8.13
- **yarn version, if running the dev UI**:

### Describe the problem

Test case related to mlserver fails (https://github.com/mlflow/mlflow/actions/runs/10566204041/job/29353076683?pr=13005 ).
The reason is due to pydantic and mlserver version incomatibility.

Inside Docker, pydantic and mlserver versions are compatible
```
mlflow@258c243f8903:/app$ mlserver --version
pymlserver, version 1.3.5
mlflow@258c243f8903:/app$ python3 -c 'import pydantic; print(pydantic.__version__)'
1.10.18
mlflow@258c243f8903:/app$
```

when using venv (with `./dev/dev-env-setup.sh`), pydantic and mlserver versions are incompatible.
```
❯ which python
/Users/ridham/mlflow/.venvs/mlflow-dev/bin/python

❯ python -c 'import pydantic; print(pydantic.__version__)'
2.8.2

❯ mlserver --version                                      
/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic:PyObject` has been moved to `pydantic.types:ImportString`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
Traceback (most recent call last):
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/bin/mlserver", line 5, in <module>
    from mlserver.cli import main
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/mlserver/__init__.py", line 2, in <module>
    from .server import MLServer
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/mlserver/server.py", line 7, in <module>
    from mlserver.repository.factory import ModelRepositoryFactory
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/mlserver/repository/__init__.py", line 1, in <module>
    from .repository import (
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/mlserver/repository/repository.py", line 8, in <module>
    from ..settings import ModelParameters, ModelSettings
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/mlserver/settings.py", line 8, in <module>
    from pydantic import PyObject, Extra, Field, BaseSettings as _BaseSettings
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/pydantic/__init__.py", line 395, in __getattr__
    return _getattr_migration(attr_name)
  File "/Users/ridham/mlflow/.venvs/mlflow-dev/lib/python3.8/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.8/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.8/u/import-error
```
Solution has 2 approaches:
1. mlserver has finished the migration to pydantic v2 (https://github.com/SeldonIO/MLServer/pull/1748).
I believe due to this, we can also upgrade the mlserver version and remove the <1.4.0 restriction.
@harupy I see that you had raised https://github.com/SeldonIO/MLServer/pull/1595 to fix this issue but the migration wasn't complete yet. Any thoughts on this?
2. currently, in the failing build, 1.10.18 gets installed but later on, 2.8.2 gets installed. Spacy is updating pydantic to the latest version due to loose version bounds in the spacy package. Perhaps we can pin pydantic.
In the build environment:
```
2024-08-28T08:18:06.0549994Z Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 (from fastapi!=0.89.0,<=0.89.1,>=0.88.0->mlserver!=1.3.1,<1.4.0,>=1.2.0->mlflow==2.15.2.dev0)
2024-08-28T08:18:06.0702094Z   Downloading pydantic-1.10.18-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (152 kB)
...
2024-08-28T08:27:13.4545401Z   Attempting uninstall: pydantic
2024-08-28T08:27:13.4568097Z     Found existing installation: pydantic 1.10.18
2024-08-28T08:27:13.4632058Z     Uninstalling pydantic-1.10.18:
2024-08-28T08:27:13.4645290Z       Successfully uninstalled pydantic-1.10.18
...
2024-08-28T08:21:27.4117719Z Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core<0.12.0,>=0.11.2->llama_index->-r requirements/extra-ml-requirements.txt (line 68))
2024-08-28T08:21:27.4276789Z   Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
2024-08-28T08:21:27.5412842Z Collecting nest-asyncio<2.0.0,>=1.5.8 (from llama-index-core<0.12.0,>=0.11.2->llama_index->-r requirements/extra-ml-requirements.txt (line 68))
2024-08-28T08:21:27.5561050Z   Downloading nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
2024-08-28T08:21:27.8433087Z Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy>=3.3.0->-r requirements/extra-ml-requirements.txt (line 10))
2024-08-28T08:21:27.8452894Z   Using cached pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
2024-08-28T08:21:27.9951848Z Collecting typing-inspect>=0.8.0 (from llama-index-core<0.12.0,>=0.11.2->llama_index->-r requirements/extra-ml-requirements.txt (line 68))

```
In the dev environment, rstcheck-core upgrades the pydantic version due to constraint pydantic>=2 (https://github.com/rstcheck/rstcheck-core/blob/30c6c46f65b7618004d279f53c5aa73bd877b2c3/pyproject.toml#L25)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
#13039 is an attempt to unpin mlserver. It turns out we need to update the python version used in CI as well to install the latest version of mlserver.

**Comment by harupy** [comment]
I'll close this because this isn't an issue or bug in mlflow features.
