### ISSUE TITLE
error executing mlflow inside a PandasUDF

### ISSUE THREAD

**Issue by franperezlopez** [mlflow/mlflow#1315]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Azure Databricks

### Describe the problem
Running any mlflow task inside a PandasUDF provokes an error

### Source code / logs

```python
from pyspark.sql.functions import pandas_udf, PandasUDFType
@pandas_udf("group_key int, exception string, stacktrace string", PandasUDFType.GROUPED_MAP)
def train_model(df):
  import mlflow, traceback, sys
  group_key = df[group_column].iloc[0]  
  try:
    pass
    with mlflow.start_run(experiment_id='541031238511786') as ar:
      pass
  except Exception as e:
    exception = str(e)
    st = traceback.format_exc()
  else:
    exception = ''
    st = ''
  return pd.DataFrame.from_dict({'group_key': group_key, 'exception': exception, 'stacktrace':st}, orient='index').T

group_column = "Enclosure_Type"
df_spark.groupby(group_column).apply(train_model).head(4)
```

The output is like this:

_exception_:  
You haven't configured the CLI yet! Please configure by entering `/databricks/spark/python/pyspark/daemon.py configure`

_stacktrace_ : 
```
Traceback (most recent call last):
  File "<command-2871457586542518>", line 14, in train_model
  File "/databricks/python/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 144, in start_run
    tags=tags
  File "/databricks/python/lib/python3.6/site-packages/mlflow/tracking/client.py", line 101, in create_run
    source_version=source_version
  File "/databricks/python/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 156, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/databricks/python/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 57, in _call_endpoint
    host_creds = self.get_host_creds()
  File "/databricks/python/lib/python3.6/site-packages/mlflow/tracking/utils.py", line 188, in <lambda>
    return RestStore(lambda: get_databricks_host_creds(profile))
  File "/databricks/python/lib/python3.6/site-packages/mlflow/utils/databricks_utils.py", line 83, in get_databricks_host_creds
    config = provider.get_config()
  File "/databricks/python/lib/python3.6/site-packages/databricks_cli/configure/provider.py", line 122, in get_config
    raise InvalidConfigurationError.for_profile(None)
 "databricks_cli.utils.InvalidConfigurationError: You haven't configured the CLI yet! Please configure by entering `/databricks/spark/python/pyspark/daemon.py configure`
```

I believe the problem is that mlflow doesn't work when executed in a worker node, inside a PandasUDF. It looks like mlflow is not able to grab the host credentials (`get_databricks_host_creds()`), and then throws the error about databricks daemon

I couldn't find any example about how to run an mlflow inside a PandasUDF, so I'm not sure if I'm following a good pattern here

**Comment by andrewmchen** [comment]
We implemented something to handle getting default creds in workers in DBR 5.5 which should address this issue! Please re-open if it does not work.

**Comment by WaterKnight1998** [comment]
@andrewmchen Hmm, I am using DBR 9.1 LTS ML and I am finding the same issue. Could you provide me a link on this feature?
