### ISSUE TITLE
mlflow run producing nonetype errors

### ISSUE THREAD

**Issue by sakiii999** [mlflow/mlflow#1317]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:CentOS Linux 7
- **MLflow installed from (source or binary)**: pip install
- **MLflow version (run ``mlflow --version``)**:0.9.1
- **Python version**: 3.6
- **Exact command to reproduce**:mlflow run . -P alpha=0.5

### Describe the problem
Getting errors when I try to execute mlflow run after building docker example (mlflow-docker-example)

### Source code / logs
The command I used is mlflow run . -P alpha=0.5. I think the problem is I am not running in the same path mlflow is installed. Can anyone help me out on this issue.

[shoot@dev-2 docker]$ mlflow run . -P alpha=0.5
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mlflow/cli.py", line 139, in run
    run_id=run_id,
  File "/usr/local/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 230, in run
    storage_dir=storage_dir, block=block, run_id=run_id)
  File "/usr/local/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 125, in _run
    active_run=active_run)
  File "/usr/local/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 706, in _build_docker_image
    version=_get_git_commit(work_dir)[:7], )
TypeError: 'NoneType' object is not subscriptable

**Comment by aarondav** [comment]
Thanks for the report! This is indeed a bug, where running Docker projects requires you to be in a valid git repository. I created #1331 to resolve this issue.
