### ISSUE TITLE
[BUG] Boto3 read_timeout Issues (Proposed Solution Included)

### ISSUE THREAD

**Issue by nsrozak** [mlflow/mlflow#13316]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow==2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**:  3.11.9
- **yarn version, if running the dev UI**:

### Describe the problem

I get `botocore.exceptions.ReadTimeoutError` when trying to upload artifacts to the server when using MLFlow with S3 for artifact storage. I tried setting the `MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT` environment variable, but the error persisted. I examined the MLFlow source code and realized [s3_artifact_repo.py](https://github.com/mlflow/mlflow/blob/63ca2de1d138e106ad3220ec63cd64abca5327e6/mlflow/store/artifact/s3_artifact_repo.py) does not make use of the `MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT` environment variable. I propose the following changes to the `_cached_get_s3_client()` function that will hopefully resolve this issue.

```
_DEFAULT_TIMEOUT = 60    ## NEW
TIMEOUT = MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT.get() or _DEFAULT_TIMEOUT  ## NEW

def _cached_get_s3_client( ... ):
    """  ...  """
    import boto3
    from botocore.client import Config

    # Making it possible to access public S3 buckets
    # Workaround for https://github.com/boto/botocore/issues/2442
    if signature_version.lower() == "unsigned":
        from botocore import UNSIGNED
        signature_version = UNSIGNED

 return boto3.client(
        "s3",
        config=Config(
            signature_version=signature_version, s3={"addressing_style": addressing_style},
           connect_timeout= TIMEOUT,  ## NEW
           read_timeout= TIMEOUT  ## NEW
        ),
        endpoint_url=s3_endpoint_url,
        verify=verify,
        aws_access_key_id=access_key_id,
        aws_secret_access_key=secret_access_key,
        aws_session_token=session_token,
        region_name=region_name,
    )

### Tracking information

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```shell
AWS_ACCESS_KEY=...
AWS_SECRET_ACCESS_KEY=...

POSTGRES_HOST=...
POSTGRES_USER=...
POSTGRES_PASSWORD=...
POSTGRES_PORT=...
POSTGRES_DB=...

MLFLOW_S3_ENDPOINT=...
MLFLOW_TRACKING_URI=...
MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT=300

REQUESTS_CA_BUNDLE=...
```

### Code to reproduce issue

```
# global imports
import mlflow
from mlflow.client import MlflowClient
from sklearn.linear_model import LogisticRegression

# classes
class ModelWrapper(mlflow.pyfunc.PythonModel):
    def __init__(self, model):
        self.model = model
    def predict(self, context, model_input):
        return self.model.predict(model_input)

# create experiment
client = MlflowClient(tracking_uri=tracking_uri)
client.create_experiment('experiment')
client.create_registered_model('model')

# create fake run data
params = {'param':  1}
metrics = {'metric': 2}
model_path = 's3://' + bucket_name + '/models'

model = LogisticRegression()
pyfunc_model = ModelWrapper(model)

# start run
experiment_id = client.get_experiment_by_name('experiment').experiment_id

with mlflow.start_run(experiment_id=experiment_id, run_name='run') as run:
    mlflow.log_params(params)
    mlflow.log_metrics(metrics)
    mlflow.log_artifact('data.csv')

   mlflow.pyfunc.log_model(model_path, python_model=pyfunc_model)   # ERROR HERE
   model_version = client.create_model_version('model', model_pathm run_id=run_id)
```

### Stack trace

```
Traceback (most recent call last):

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 463, in _make_request

    httplib_response = conn.getresponse()

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse

    response.begin()

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin

    version, status, reason = self._read_status()

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto

    return self._sock.recv_into(b)

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into 

    return self.read(nbytes, buffer)

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read      

    return self._sslobj.read(len, buffer)

socket.timeout: The read operation timed out

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\httpsession.py", line 464, in send

    urllib_response = conn.urlopen(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen

    retries = retries.increment(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\util\retry.py", line 527, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise

    raise value

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen

    httplib_response = self._make_request(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 470, in _make_request

    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\urllib3\connectionpool.py", line 358, in _raise_timeout

    raise ReadTimeoutError(

urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='[san.ccsp.basf.net](http://san.ccsp.basf.net/)', port=443): Read timed out. (read timeout=60)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Users\RozakN\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code 

    exec(code, run_globals)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\test1.py", line 331, in <module>

    mlflow.pyfunc.log_model(model_path, python_model=pyfunc_model)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\tracing\provider.py", line 268, in wrapper

    is_func_called, result = True, f(*args, **kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\pyfunc\__init__.py", line 2858, in log_model

    return Model.log(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\models\model.py", line 743, in log

    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\tracking\fluent.py", line 1162, in log_artifacts

    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\tracking\client.py", line 1971, in log_artifacts

    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 853, in log_artifacts

    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\store\artifact\s3_artifact_repo.py", line 194, in log_artifacts

    self._upload_file(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\mlflow\store\artifact\s3_artifact_repo.py", line 169, in _upload_file

    s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\boto3\s3\inject.py", line 145, in upload_file

    return transfer.upload_file(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\boto3\s3\transfer.py", line 372, in upload_file

    future.result()

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\s3transfer\futures.py", line 103, in result

    return self._coordinator.result()

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\s3transfer\futures.py", line 266, in result

    raise self._exception

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\s3transfer\tasks.py", line 139, in __call__

    return self._execute_main(kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\s3transfer\tasks.py", line 162, in _execute_main

    return_value = self._main(**kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\s3transfer\upload.py", line 764, in _main

    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\client.py", line 569, in _api_call

    return self._make_api_call(operation_name, kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\client.py", line 1005, in _make_api_call

    http, parsed_response = self._make_request(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\client.py", line 1029, in _make_request

    return self._endpoint.make_request(operation_model, request_dict)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\endpoint.py", line 119, in make_request

    return self._send_request(request_dict, operation_model)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\endpoint.py", line 200, in _send_request

    while self._needs_retry(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\endpoint.py", line 360, in _needs_retry

    responses = self._event_emitter.emit(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\hooks.py", line 412, in emit

    return self._emitter.emit(aliased_event_name, **kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\hooks.py", line 256, in emit

    return self._emit(event_name, kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\hooks.py", line 239, in _emit

    response = handler(**kwargs)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 207, in __call__

    if self._checker(**checker_kwargs):

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 284, in __call__

    should_retry = self._should_retry(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 320, in _should_retry

    return self._checker(attempt_number, response, caught_exception)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 363, in __call__

    checker_response = checker(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 247, in __call__

    return self._check_caught_exception(

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\retryhandler.py", line 416, in _check_caught_exception

    raise caught_exception

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\endpoint.py", line 279, in _do_get_response

    http_response = self._send(request)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\endpoint.py", line 383, in _send

    return self.http_session.send(request)

  File "C:\Users\RozakN\Documents\test-mlflow-postgres\.venv\lib\site-packages\botocore\httpsession.py", line 501, in send

    raise ReadTimeoutError(endpoint_url=request.url, error=e)

botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: [https://<AWS_URL> /test-mlflow-postgres/74/b54b6dd820b145e5a831915fb3510c12/artifacts/s3%3A//test-mlflow-postgres/models/MLmodel](https://san.ccsp.basf.net/test-mlflow-postgres/74/b54b6dd820b145e5a831915fb3510c12/artifacts/s3%3A/test-mlflow-postgres/models/MLmodel)
```

### Other info / logs

```
No Log File Exists
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nsrozak Thanks for reporting this but. The proposed change looks reasonable. Can you verify the change?

**Comment by harupy** [comment]
@nsrozak Thanks for testing! I filed https://github.com/mlflow/mlflow/pull/13378.
