### ISSUE TITLE
[BUG] mlflow build docker fails because it lacks certificate/SSL awareness.

### ISSUE THREAD

**Issue by pauljohn32** [mlflow/mlflow#13359]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

λ pip list | grep mlflow
mlflow                             2.16.2
mlflow-skinny                      2.16.2
mlserver-mlflow                    1.3.5

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 and 11
- **OS**: WSL2 Ubuntu 24.04
- **Python version**: 3.9
- Windows Docker-Desktop: 4.34.2

### Describe the problem

When contacting git, pip, or mvn, my system hits problems with SSL certificates.  Our corporate setup has a self signed certificate and this blocks access to those servers.  Some special configuration in the user account is required to supply certificate settings. 

When I try to do `mlflow.models.build_docker`, I hit a sequence of certificate failures because the mlflow does not seem to run within my user account.  The same happens whether I run in Windows or in the WSL2 where docker executables are available.  

The first error is when mlflow tries to use git to retrieve pyenv.  
```
 10 | >>> RUN git clone \
  11 | >>>     --depth 1 \
  12 | >>>     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\.[1-9]+)+$' | tail -1) \
  13 | >>>     https://github.com/pyenv/pyenv.git /root/.pyenv
  14 |     ENV PYENV_ROOT="/root/.pyenv"
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone     --depth 1     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\\.[1-9]+)+$' | tail -1)     https://github.com/pyenv/pyenv.git /root/.pyenv" did not complete successfully: exit code: 128
```

So I hacked the mlflow installed package code like this to get past it. Insert "GIT_SSL_NO_VERIFY" with all git calls

```
models/docker_utils.py:    --branch $(GIT_SSL_NO_VERIFY=true git ls-remote -
```

After that, it fails because of pip calls.  So I hack your source to ignore pip problems, telling it to trust indicated hosts

```
models/container/__init__.py:    install_server_deps = [f"pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org {' '.join(server_deps)}"]
```

After that, I hit issue with MVN downloads.  Hack that.  

The build proceeds after that, but dies on the python download, and I've not found a work around for that. The error log is below in the traceback section.

I **think** this happens because Docker spins up a new WSL instance and it does not use any environment from my Windows user account.  I think that is the case because I uninstalled Windows Docker-Desktop and went into WSL2 and installed mlflow and docker from the Ubuntu packages.  When I run the build in my user account, which has been configured with the environment to correctly check certificates, the mlflow/docker build succeeds.  

I'm also asking about this in StackOverflow: https://stackoverflow.com/q/79063959/1086346.  

I wish this build would work without all of this hacking, of course.  I can give you code changes needed to disable cert checking if you want.  

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```

import mlflow
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
#create dataset
training_data=[(2,10),(2,6),(11,11),(6,9),(6,4),
               (1,2),(5,10),(4,9),(10,12),(7,5),
               (9,11),(4,6),(3,10),(3,8),(6,11)]
#create a new experiment
experiment_name = 'ClusteringWithMlflow3'
try:
    exp_id = mlflow.create_experiment(name=experiment_name)
except Exception as e:
    exp_id = mlflow.get_experiment_by_name(experiment_name).experiment_id


pip_needs = ["pip-system-certs", "keyring artifacts-keyring" "keyring artifacts-keyring"]
    
k = 5
with mlflow.start_run(experiment_id=exp_id) as run:
    untrained_model = KMeans(n_clusters=k)
    trained_model = untrained_model.fit(training_data)
    cluster_labels = trained_model.labels_
    score = silhouette_score(training_data, cluster_labels)
    #save parameter
    mlflow.log_param('value_of_k', k)
    #save metric
    mlflow.log_metric('silhoutte_score', score)
    #save model
    grr = mlflow.active_run()
    print("active:", grr)
    print("active_run:", mlflow.active_run())
    input_example = training_data
    ml_info = mlflow.sklearn.log_model(
        trained_model,
        "Clustering_Model",
        registered_model_name="pj-cluster",
        input_example=input_example,
        extra_pip_requirements=pip_needs
    )

      
# mlflow models build-docker -m runs:/<RUN_ID>/model -n my-iris-image --enable-mlserver

model_name = "pj-cluster"
model_version = "latest"

# Load the model from the Model Registry
# model_uri = f"models:/{model_name}/{model_version}"
model_uri = ml_info.model_uri
print("model_uri:", model_uri)
image_name = "mll_cluster"

print("ml_info.model_uri: ", ml_info.model_uri)
mlflow.models.build_docker(
   model_uri=model_uri,
   name=image_name,
   enable_mlserver=True,
   )
```

### Stack trace

The first error is when you try to run git:

```
2024/10/09 10:32:35 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException('Data (2, 10) is not one of the supported DataType'). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
Registered model 'pj-cluster' already exists. Creating a new version of this model...
Created version '16' of model 'pj-cluster'.
model_uri: runs:/bd938a4092d14ec4b61a7db95f549459/Clustering_Model
ml_info.model_uri:  runs:/bd938a4092d14ec4b61a7db95f549459/Clustering_Model
2024/10/09 10:32:42 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'
2024/10/09 10:32:42 INFO mlflow.pyfunc.backend: Building docker image with name hrb_mll_cluster
[+] Building 2.8s (8/21)                                                                                                                                                                docker:desktop-linux  => [internal] load build definition from Dockerfile                                                                                                                                                    0.1s  => => transferring dockerfile: 2.58kB                                                                                                                                                                  0.0s  => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                         1.9s  => [internal] load .dockerignore                                                                                                                                                                       0.0s  => => transferring context: 2B                                                                                                                                                                         0.0s  => [internal] load build context                                                                                                                                                                       0.0s  => => transferring context: 3.27kB                                                                                                                                                                     0.0s  => [ 1/17] FROM docker.io/library/ubuntu:20.04@sha256:6d8d9799fe6ab3221965efac00b4c34a2bcc102c086a58dff9e19a08b913c7ef                                                                                 0.0s  => => resolve docker.io/library/ubuntu:20.04@sha256:6d8d9799fe6ab3221965efac00b4c34a2bcc102c086a58dff9e19a08b913c7ef                                                                                   0.0s  => CACHED [ 2/17] RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends wget curl nginx ca-certificates bzip2 build-essential cmake git-core   0.0s  => CACHED [ 3/17] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata     libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm     libncursesw5-dev xz-  0.0s  => ERROR [ 4/17] RUN git clone     --depth 1     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\.[1-9]+)+$' | tail -1)     https://github  0.7s ------
 > [ 4/17] RUN git clone     --depth 1     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\.[1-9]+)+$' | tail -1)     https://github.com/pyenv/pyenv.git /root/.pyenv:
0.655 fatal: unable to access 'https://github.com/pyenv/pyenv.git/': server certificate verification failed. CAfile: none CRLfile: none
0.662 fatal: repository '/root/.pyenv' does not exist
------
Dockerfile:10
--------------------
   9 |         libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
  10 | >>> RUN git clone \
  11 | >>>     --depth 1 \
  12 | >>>     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\.[1-9]+)+$' | tail -1) \
  13 | >>>     https://github.com/pyenv/pyenv.git /root/.pyenv
  14 |     ENV PYENV_ROOT="/root/.pyenv"
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone     --depth 1     --branch $(git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1-9]+(\\.[1-9]+)+$' | tail -1)
  https://github.com/pyenv/pyenv.git /root/.pyenv" did not complete successfully: exit code: 128

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/nizz1fi7b3qbmu2dlf87mny06
Traceback (most recent call last):
  File "C:\Users\A1146108\tmp\mlflow-01\cluster-02.py", line 56, in <module>
    mlflow.models.build_docker(
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\models\python_api.py", line 86, in build_docker
    get_flavor_backend(model_uri, docker_build=True, env_manager=env_manager).build_image(
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\pyfunc\backend.py", line 369, in build_image
    docker_utils.build_image_from_context(context_dir=cwd, image_name=image_name)
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\models\docker_utils.py", line 230, in build_image_from_context
    raise RuntimeError("Docker build failed.")
RuntimeError: Docker build failed.
```

After hacking to get past problems with git, pip, and mvn, it ends like this.  This is the one I cannot hack around

```
2024/10/09 10:07:16 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException('Data (2, 10) is not one of the supported DataType'). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
Registered model 'pj-cluster' already exists. Creating a new version of this model...
Created version '15' of model 'pj-cluster'.
None
model_uri: runs:/f294bd0f2fed462c906c114990bbff69/Clustering_Model
ml_info.model_uri:  runs:/f294bd0f2fed462c906c114990bbff69/Clustering_Model
2024/10/09 10:07:22 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'
2024/10/09 10:07:22 INFO mlflow.pyfunc.backend: Building docker image with name hrb_mll_cluster
[+] Building 5.7s (20/22)                                                                                                                                                               docker:desktop-linux  => [internal] load build definition from Dockerfile                                                                                                                                                    0.1s  => => transferring dockerfile: 3.12kB                                                                                                                                                                  0.0s  => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                         2.0s  => [internal] load .dockerignore                                                                                                                                                                       0.0s  => => transferring context: 2B                                                                                                                                                                         0.0s  => [internal] load build context                                                                                                                                                                       0.0s  => => transferring context: 3.27kB                                                                                                                                                                     0.0s  => [ 1/18] FROM docker.io/library/ubuntu:20.04@sha256:6d8d9799fe6ab3221965efac00b4c34a2bcc102c086a58dff9e19a08b913c7ef                                                                                 0.0s  => => resolve docker.io/library/ubuntu:20.04@sha256:6d8d9799fe6ab3221965efac00b4c34a2bcc102c086a58dff9e19a08b913c7ef                                                                                   0.0s  => CACHED [ 2/18] RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends wget curl nginx ca-certificates bzip2 build-essential cmake git-core   0.0s  => CACHED [ 3/18] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata     libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm     libncursesw5-dev xz-  0.0s  => CACHED [ 4/18] RUN GIT_SSL_NO_VERIFY=true git clone     --depth 1     --branch $(GIT_SSL_NO_VERIFY=true git ls-remote --tags --sort=v:refname https://github.com/pyenv/pyenv.git | grep -o -E 'v[1  0.0s  => CACHED [ 5/18] RUN apt install -y python3.8 python3.8-distutils     && ln -s -f $(which python3.8) /usr/bin/python     && wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate -O /tmp  0.0s  => CACHED [ 6/18] RUN pip install virtualenv                                                                                                                                                           0.0s  => CACHED [ 7/18] RUN apt-get install -y --no-install-recommends openjdk-11-jdk maven                                                                                                                  0.0s  => CACHED [ 8/18] WORKDIR /opt/mlflow                                                                                                                                                                  0.0s  => CACHED [ 9/18] RUN pip install mlflow==2.16.2                                                                                                                                                       0.0s  => CACHED [10/18] RUN mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true --batch-mode dependency:copy -Dartifact=org.mlf  0.0s  => CACHED [11/18] RUN mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true --batch-mode dependency:copy -Dartifact=org.mlf  0.0s  => CACHED [12/18] RUN cp /opt/java/mlflow-scoring-2.16.2.pom /opt/java/pom.xml                                                                                                                         0.0s  => CACHED [13/18] RUN cd /opt/java && mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true--batch-mode dependency:copy-dep  0.0s  => CACHED [14/18] RUN  pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pip-system-certs                                                                                      0.0s  => [15/18] COPY model_dir/Clustering_Model /opt/ml/model                                                                                                                                               0.0s  => ERROR [16/18] RUN python -c "from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=True, env_manager='virtualenv');"              3.4s ------
 > [16/18] RUN python -c "from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=True, env_manager='virtualenv');":
2.704 2024/10/09 15:07:32 INFO mlflow.models.container: creating and activating custom environment
2.711 2024/10/09 15:07:32 INFO mlflow.utils.virtualenv: Installing python 3.9.13 if it does not exist
2.925 Downloading Python-3.9.13.tar.xz...
2.925 -> https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tar.xz
3.191 error: failed to download Python-3.9.13.tar.xz
3.191
3.191 BUILD FAILED (Ubuntu 20.04 using python-build 2.4.14)
3.210
3.216 Results logged to /tmp/python-build.20241009150732.90.log
3.216
3.216 Last 10 log lines:
3.217 /tmp/python-build.20241009150732.90 /opt/mlflow
3.217 curl: (60) SSL certificate problem: self signed certificate in certificate chain
3.217 More details here: https://curl.haxx.se/docs/sslcerts.html
3.217
3.217 curl failed to verify the legitimacy of the server and therefore could not
3.217 establish a secure connection to it. To learn more about this situation and
3.217 how to fix it, please visit the web page mentioned above.
3.221 Traceback (most recent call last):
3.221   File "<string>", line 1, in <module>
3.221   File "/usr/local/lib/python3.8/dist-packages/mlflow/models/container/__init__.py", line 92, in _install_pyfunc_deps
3.221     activate_cmd = _install_model_dependencies_to_env(model_path, env_manager) if model_path else []
3.221   File "/usr/local/lib/python3.8/dist-packages/mlflow/models/container/__init__.py", line 169, in _install_model_dependencies_to_env
3.221     env_activate_cmd = _get_or_create_virtualenv(model_path)
3.221   File "/usr/local/lib/python3.8/dist-packages/mlflow/utils/virtualenv.py", line 372, in _get_or_create_virtualenv
3.221     python_bin_path = _install_python(
3.221   File "/usr/local/lib/python3.8/dist-packages/mlflow/utils/virtualenv.py", line 137, in _install_python
3.221     _exec_cmd(
3.221   File "/usr/local/lib/python3.8/dist-packages/mlflow/utils/process.py", line 141, in _exec_cmd
3.221     raise ShellCommandException.from_completed_process(comp_process)
3.221 mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
3.221 Command: ['/root/.pyenv/bin/pyenv', 'install', '--skip-existing', '3.9.13']
------
Dockerfile:41
--------------------
  39 |     # Copy model to image and install dependencies
  40 |     COPY model_dir/Clustering_Model /opt/ml/model
  41 | >>> RUN python -c "from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=True, env_manager='virtualenv');"
  42 |
  43 |     ENV MLFLOW_DISABLE_ENV_CREATION=True
--------------------
ERROR: failed to solve: process "/bin/sh -c python -c \"from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=True, env_manager='virtualenv');\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/8qvxk6opx16d79rrgaehs0q8n
Traceback (most recent call last):
  File "C:\Users\A1146108\tmp\mlflow-01\cluster-02.py", line 65, in <module>
    mlflow.models.build_docker(
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\models\python_api.py", line 86, in build_docker
    get_flavor_backend(model_uri, docker_build=True, env_manager=env_manager).build_image(
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\pyfunc\backend.py", line 369, in build_image
    docker_utils.build_image_from_context(context_dir=cwd, image_name=image_name)
  File "C:\Users\A1146108\venv-mlflow-3.9\lib\site-packages\mlflow\models\docker_utils.py", line 234, in build_image_from_context
    raise RuntimeError("Docker build failed.")
RuntimeError: Docker build failed.
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by pauljohn32** [comment]
I made patch files to show the hacks I tried to get past the certificate problems.
[patch_container_init.txt](https://github.com/user-attachments/files/17311116/patch_container_init.txt)
[patch_docker_utils.txt](https://github.com/user-attachments/files/17311117/patch_docker_utils.txt)

**Comment by pauljohn32** [comment]
These patch files show hacks I applied to get past the certificate problems
[patch_container_init.txt](https://github.com/user-attachments/files/17311156/patch_container_init.txt)
[patch_docker_utils.txt](https://github.com/user-attachments/files/17311157/patch_docker_utils.txt)

**Comment by daniellok-db** [comment]
Thanks for the report! Could you upload the TXT files as gists on github (https://gist.github.com) so it's easily accessible?
