### ISSUE TITLE
[BUG] mlflow gc failed to delete runs in the deleted lifecycle stage using postgress and azure storage

### ISSUE THREAD

**Issue by David2011Hernandez** [mlflow/mlflow#13393]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.16.2
- Tracking server: 2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.12.1
- **yarn version, if running the dev UI**:

### Describe the problem

I have started my MLFlow server using docker compose in my local computer specifying postgress as `--backend-store-uri` and an Azure container as `--artifacts-destination`. With this local setting I am able to run experiments normally, and can see the metadata in the local postgres container and the blobs in azure. I then use `mlflow experiments search` to find the experiment ID that  I want to delete and deleted with `mlflow experiments delete` I then can see that the experiment get marked as `deleted` in the `lifecycle_stage` column in postgres but when I try to garbage collected using `mlflow gc` I get `mlflow.exceptions.MlflowException: API request to http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ (Caused by ResponseError('too many 500 error responses'))`

### Tracking information

```shell
# compose service
postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
      POSTGRES_DB: mlflowdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
    networks:
      - mlflow
  
  # MLflow tracking server
  mlflow:
    image: mlflow-azure-storage:0.1.0
    container_name: mlflow
    command:
      - server
      - --backend-store-uri 
      - postgresql://user:${POSTGRES_PASSWORD?err}@postgres/mlflowdb
      - --host
      - "0.0.0.0"
      - --port
      - "5000"
      - "--expose-prometheus"
      - "/metrics"
      - "--dev"
      - "--artifacts-destination"
      - ${MLFLOW_S3_ENDPOINT_URL?err}
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mlflow

# Dockerfile:
FROM python:3.12-slim AS build

RUN apt-get update && \
    apt-get install gcc python3-dev libpq-dev libyaml-cpp-dev libyaml-dev -y --no-install-recommends && \
    pip install --no-cache-dir --force-reinstall -I pyyaml azure-storage-blob mlflow psycopg2 prometheus-flask-exporter && \
    rm -rf /var/lib/apt/lists/*

# Runtime stage
FROM python:3.12-slim

# libyaml-cpp-dev libyaml-dev
RUN apt-get update && \
    apt-get install libpq-dev -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin/mlflow /usr/local/bin/mlflow

ENTRYPOINT [ "mlflow" ] 
```

### Code to reproduce issue

```
# python script 
from sklearn.datasets import make_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

import numpy as np
from PIL import Image

import mlflow
import mlflow.sklearn

import logging

logging.basicConfig(level=logging.DEBUG)

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("check-localhost-connection-1")

# Generate a large image (e.g., 1000x1000 pixels)
large_image = np.random.randint(0, 256, (1000, 1000, 3), dtype=np.uint8)
image = Image.fromarray(large_image)
image_path = "large_image.png"
image.save(image_path)

with mlflow.start_run() as run:
    X, y = make_regression(n_features=4, n_informative=2, random_state=0, shuffle=False)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    params = {"max_depth": 2, "random_state": 42}
    model = RandomForestRegressor(**params)
    model.fit(X_train, y_train)

    # Log parameters and metrics using the MLflow APIs
    mlflow.log_params(params)

    y_pred = model.predict(X_test)
    mlflow.log_metrics({"mse": root_mean_squared_error(y_test, y_pred)})

    # Log the sklearn model and register as version 1
    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="sklearn-model",
        input_example=X_train,
        registered_model_name="sk-learn-random-forest-reg-model",
    )

    # Log the large image as an artifact
    mlflow.log_artifact(image_path)

    logging.info("Logged large image and model to MLflow server")

# delete the experiment

MLFLOW_TRACKING_URI=http://127.0.0.1:5000 mlflow experiments delete --experiment-id 1


# garbage collect

MLFLOW_TRACKING_URI=http://127.0.0.1:5000 mlflow gc --backend-store-uri postgresql://user:$PASSWD@127.0.0.1/mlflowdb

```

### Stack trace

```
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 189, in http_request
    return _get_http_response_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/mlflow/utils/request_utils.py", line 237, in _get_http_response_with_retries
    return session.request(method, url, allow_redirects=allow_redirects, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dh2011/python_virtual_environments/mlflow/bin/mlflow", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/mlflow/cli.py", line 620, in gc
    artifact_repo.delete_artifacts()
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 113, in delete_artifacts
    resp = http_request(self._host_creds, endpoint, "DELETE", stream=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dh2011/python_virtual_environments/mlflow/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 212, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/ (Caused by ResponseError('too many 500 error responses'))


```

### Other info / logs

```
[2024-10-11 14:52:19 +0000] [1617] [DEBUG] DELETE /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
Do you have the logs of the tracking server? I'm curious if there might be some hints about the source of the 500 errors

**Comment by David2011Hernandez** [comment]
server logs are not very helpful, even when setting `--dev`

only showing the request bieng made e.g. `[2024-10-11 14:52:19 +0000] [1617] [DEBUG] DELETE /api/2.0/mlflow-artifacts/artifacts/1/dcb95351746b430b9a08ab886eeb9406/artifacts/`

I have `strace`d the server

some lines follows

```
92290 16:23:44.740648 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_list_blobs_helper.py", {st_mode=S_IFREG|0644, st_size=13160, ...}, 0) = 0
92290 16:23:44.740675 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_container_client.py", {st_mode=S_IFREG|0644, st_size=84722, ...}, 0) = 0
92290 16:23:44.740702 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client_helpers.py", {st_mode=S_IFREG|0644, st_size=997, ...}, 0) = 0
92290 16:23:44.740729 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", {st_mode=S_IFREG|0644, st_size=40366, ...}, 0) = 0
92290 16:23:44.740760 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/storage/blob/__init__.py", {st_mode=S_IFREG|0644, st_size=10694, ...}, 0) = 0
92290 16:23:44.740789 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/core/tracing/ext/__init__.py", {st_mode=S_IFREG|0644, st_size=0, ...}, 0) = 0
92290 16:23:44.740818 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/netrc.py", {st_mode=S_IFREG|0644, st_size=6922, ...}, 0) = 0
92290 16:23:44.740844 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/core/rest/_http_response_impl.py", {st_mode=S_IFREG|0644, st_size=17313, ...}, 0) = 0
92290 16:23:44.740871 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/site-packages/azure/core/rest/_requests_basic.py", {st_mode=S_IFREG|0644, st_size=4332, ...}, 0) = 0
92290 16:23:44.740898 newfstatat(AT_FDCWD, "/usr/local/lib/python3.12/encodings/utf_8_sig.py", {st_mode=S_IFREG|0644, st_size=4133, ...}, 0) = 0
92290 16:23:44.740948 clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, {tv_sec=7941, tv_nsec=168192349},  <unfinished ...>
92130 16:23:44.992699 <... pselect6 resumed>) = 1 (in [5], left {tv_sec=7, tv_nsec=528499519})
92130 16:23:44.993156 utimensat(8, NULL, [{tv_sec=7940, tv_nsec=420238231} /* 1970-01-01T03:12:20.420238231+0100 */, {tv_sec=7940, tv_nsec=420238231} /* 1970-01-01T03:12:20.420238231+0100 */], 0) = 0
92130 16:23:44.993632 accept4(5, {sa_family=AF_INET, sin_port=htons(35206), sin_addr=inet_addr("172.18.0.1")}, [16], SOCK_CLOEXEC) = 11
92130 16:23:44.994228 getsockname(11, {sa_family=AF_INET, sin_port=htons(5000), sin_addr=inet_addr("172.18.0.6")}, [128 => 16]) = 0
92130 16:23:44.994540 ioctl(11, FIONBIO, [0]) = 0
92130 16:23:44.994849 fcntl(11, F_GETFD) = 0x1 (flags FD_CLOEXEC)
92130 16:23:44.995144 fcntl(11, F_SETFD, FD_CLOEXEC) = 0
92130 16:23:44.995393 recvfrom(11, "DELETE /api/2.0/mlflow-artifacts"..., 8192, 0, NULL, NULL) = 256
92130 16:23:44.995946 getpid()          = 49
92130 16:23:44.996164 write(2, "[2024-10-14 14:23:44 +0000] [49]"..., 130) = 130
92130 16:23:44.996305 getsockname(5, {sa_family=AF_INET, sin_port=htons(5000), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
92130 16:23:44.997904 getpid()          = 49
92130 16:23:44.998260 getpid()          = 49
92130 16:23:44.998363 getpid()          = 49
92130 16:23:44.998440 getpid()          = 49
92130 16:23:44.998525 getpid()          = 49
92130 16:23:44.998591 getpid()          = 49
92130 16:23:44.998658 getpid()          = 49
92130 16:23:44.998736 getpid()          = 49
92130 16:23:44.998815 getpid()          = 49
92130 16:23:44.998883 getpid()          = 49
92130 16:23:44.998948 getpid()          = 49
92130 16:23:44.999016 getpid()          = 49
92130 16:23:44.999079 getpid()          = 49
92130 16:23:44.999142 getpid()          = 49
92130 16:23:44.999204 getpid()          = 49
92130 16:23:44.999266 getpid()          = 49
92130 16:23:44.999335 getpid()          = 49
92130 16:23:44.999380 getpid()          = 49
92130 16:23:44.999510 getpid()          = 49
92130 16:23:44.999603 getpid()          = 49
92130 16:23:44.999889 sendto(11, "HTTP/1.1 500 INTERNAL SERVER ERR"..., 164, 0, NULL, 0) = 164
92130 16:23:45.000037 sendto(11, "{\"error_code\": \"INTERNAL_ERROR\","..., 66, 0, NULL, 0) = 66
92130 16:23:45.000162 close(11)         = 0
92130 16:23:45.000245 utimensat(8, NULL, [{tv_sec=7940, tv_nsec=427480106} /* 1970-01-01T03:12:20.427480106+0100 */, {tv_sec=7940, tv_nsec=427480106} /* 1970-01-01T03:12:20.427480106+0100 */], 0) = 0
92130 16:23:45.000318 accept4(5, 0x7ffcb8a58a50, [16], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
92130 16:23:45.000409 getppid()         = 46
92130 16:23:45.000448 utimensat(8, NULL, [{tv_sec=7940, tv_nsec=427687637} /* 1970-01-01T03:12:20.427687637+0100 */, {tv_sec=7940, tv_nsec=427687637} /* 1970-01-01T03:12:20.427687637+0100 */], 0) = 0
92130 16:23:45.000509 pselect6(7, [5 6], NULL, NULL, {tv_sec=15, tv_nsec=0}, NULL <unfinished ...>
92290 16:23:45.741022 <... clock_nanosleep resumed>NULL) = 0
```

where `172.18.0.x` is my internal docker network

**Comment by David2011Hernandez** [comment]
The behavior on the UI side is that I do not see the runs related to that experiment anymore but I still see the experiment 

![image](https://github.com/user-attachments/assets/46eb44a5-77a1-416e-8d51-2cc09d426f91)

**Comment by daniellok-db** [comment]
Ah, I think there is an existing bug with MLflow GC related to improperly configured foreign key contraints: https://github.com/mlflow/mlflow/issues/13254

Unfortunately the team doesn't have bandwidth at the moment to fix the bug, but I believe the fix would be to write a [db migration](https://github.com/mlflow/mlflow/tree/109bd7a59f3385e5bc709752c19f9ec381a23e67/mlflow/store/db_migrations) to fix the FK constraints.

**Comment by David2011Hernandez** [comment]
```
2024-10-15 13:35:09.513 UTC [81] ERROR:  duplicate key value violates unique constraint "registered_model_pk"
2024-10-15 13:35:09.513 UTC [81] DETAIL:  Key (name)=(sk-learn-random-forest-reg-model) already exists.
2024-10-15 13:35:09.513 UTC [81] STATEMENT:  INSERT INTO registered_models (name, creation_time, last_updated_time, description) VALUES ('sk-learn-random-forest-reg-model', 1728999309512, 1728999309512, '')

```
from postgress docker container

**Comment by David2011Hernandez** [comment]
I was able to successfully delete the experiments after manually delete 

- DELETE FROM tags WHERE run_uuid in (SELECT run_uuid FROM runs WHERE experiment_id = 1)
- DELETE FROM metrics where run_uuid in (SELECT run_uuid FROM runs WHERE experiment_id = 1)
- DELETE FROM params where run_uuid in (SELECT run_uuid FROM runs WHERE experiment_id = 1)
- DELETE FROM latest_metrics where run_uuid in (SELECT run_uuid FROM runs WHERE experiment_id = 1)
- DELETE FROM runs WHERE experiment_id = 1

in this order although the first 4 can be done in any order. Once I did this

```
MLFLOW_TRACKING_URI=http://127.0.0.1:5000 mlflow gc --backend-store-uri postgresql://user:${PASSWORD}@localhost/mlflowdb
Experiment with ID 1 has been permanently deleted.

```
although I still see the artifacts on Azure blob storage

**Comment by DavidHernandez21** [comment]
I am not sure if this issue have been solved in the latest versions
But I have found this [project](https://github.com/xataio/pgroll) which might be useful for postgres schema migrations
