### ISSUE TITLE
An HTTP Client raised and unhandled exception: 's3'

### ISSUE THREAD

**Issue by analystanand** [mlflow/mlflow#1340]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**:  3.5.2
- **npm version (if running the dev UI):
- **Exact command to reproduce**:mlflow ui -h 0.0.0.0 -p 5000 --default-artifact-root s3://mlflow-testing --backend-store-uri mysql://guest:guest123@host:3306/mlflow

### Describe the problem
i used docker to run `mlflow server` and it worked fine. It successfully pushed data to S3 and metrics to **mysql**.
But when i am running `mlflow ui` on docker container to visualize the results ,I am getting below exception.

Both `mlflow ui` and `mlflow server` works fine in case running in ubuntu.

### Tracelog
`[2019-05-27 13:48:49 +0000] [18] [INFO] Starting gunicorn 19.9.0
[2019-05-27 13:48:49 +0000] [18] [INFO] Listening at: http://0.0.0.0:5000 (18)
[2019-05-27 13:48:49 +0000] [18] [INFO] Using worker: sync
[2019-05-27 13:48:49 +0000] [21] [INFO] Booting worker with pid: 21
[2019-05-27 13:48:58,431] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/botocore/httpsession.py", line 246, in send
    conn = manager.connection_from_url(request.url)
  File "/usr/local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 283, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/usr/local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 231, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.5/site-packages/urllib3/poolmanager.py", line 241, in connection_from_context
    pool_key_constructor = self.key_fn_by_scheme[scheme]
KeyError: 's3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/mlflow/server/handlers.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mlflow/server/handlers.py", line 299, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/usr/local/lib/python3.5/site-packages/mlflow/store/s3_artifact_repo.py", line 70, in list_artifacts
    for result in results:
  File "/usr/local/lib/python3.5/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.5/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.5/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/local/lib/python3.5/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python3.5/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python3.5/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.5/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.5/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.5/site-packages/botocore/httpsession.py", line 294, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: 's3'`

**Comment by analystanand** [comment]
possible fix 
MLFLOW_S3_ENDPOINT_URL=https://s3.**region**.amazonaws.com/
for more information check https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-s3
check **addressing_style**

**Comment by aarondav** [comment]
Did sending the endpoint resolve the issue? Is there an ongoing issue?

**Comment by aarondav** [comment]
(Closing for now -- please reopen if this is still an issue.)

**Comment by aissar** [comment]
I had a similar issue. Tried a few different variations of the S3 path and the following worked for me (kinda)... The train.py no longer throws an exception however instead of uploading the artifacts to the S3 bucket, MLflow is uploading artifacts to a folder within my Jupyter docker container. 

--default-artifact-root s3.ap-southeast-2.amazonaws.com/<bucket>
