### ISSUE TITLE
[BUG] {"error": "Model mlflow-wine-classifier not found"} 

### ISSUE THREAD

**Issue by Mayurji** [mlflow/mlflow#13433]
### Describe the problem

Trying to follow the [Develop ML model with MLflow and deploy to Kubernetes tutorial](https://mlflow.org/docs/latest/deployment/deploy-model-to-kubernetes/tutorial.html).

I followed the tutorial as it is, and i was able to run the seventh step deploying the model as kserve using docker image. But while testing the deployment, i am receiving an error as follows:
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v2/models/mlflow-wine-classifier/infer HTTP/1.1
> Host: mlflow-wine-classifier.mlflow-kserve-test.example.com
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 206
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 43
< content-type: application/json
< date: Wed, 16 Oct 2024 09:52:14 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 3
< 
* Connection #0 to host localhost left intact
{"error":"Model mlflow-wine-classifier not found"}
```

As a step to debug, i was able to run the docker image locally and was able to run the inference on it successfully. But after deploying through KServe, it fails and gives the above error.

Kserve-inference-service yaml
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "wine-classifier"
  namespace: "mlflow-kserve-test"
spec:
  predictor:
    containers:
      - name: "wine-classifier"
        image: "mayur28/mlflow-wine-classifier"
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: PROTOCOL
            value: "v2"
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi 
    terminationGracePeriodSeconds: 300`
```
You can download the docker image, and test it as well if required.

### Pod Logs

```
Defaulted container "kserve-container" out of: kserve-container, queue-proxy
/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/starlette_exporter/middleware.py:97: FutureWarning: group_paths and filter_unhandled_paths will change defaults from False to True in the next release. See https://github.com/stephenhillier/starlette_exporter/issues/79 for more info
  warnings.warn(
2024-10-16 08:35:04,159 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-10-16 08:35:04,251 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [39]
INFO:     Waiting for application startup.
2024-10-16 08:35:04,657 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2024-10-16 08:35:04,747 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [39]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-10-16 08:35:12,347 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:8081
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-10-16 08:35:27,349 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,356 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,656 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,948 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,948 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,957 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,049 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,057 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,061 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,165 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,177 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,252 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,289 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,347 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,474 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,547 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,549 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
INFO:     10.244.0.111:0 - "POST /v2/models/mlflow-wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/mlflow-wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/mlflow-wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/mlflow-wine-classifier/infer HTTP/1.1" 404 Not Found
```

### Where did you encounter this bug?

Local machine (ubuntu22.04), on minikube cluster.

### MLflow version

MLflow version: 2.17.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 22.04)**:
- **Python version: 3.10.12**:
- **yarn version, if running the dev UI**:

**Comment by Mayurji** [comment]
I resolved above error to get another issue as follows:
```
Defaulted container "kserve-container" out of: kserve-container, queue-proxy
/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/starlette_exporter/middleware.py:97: FutureWarning: group_paths and filter_unhandled_paths will change defaults from False to True in the next release. See https://github.com/stephenhillier/starlette_exporter/issues/79 for more info
  warnings.warn(
2024-10-16 08:35:04,159 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-10-16 08:35:04,251 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [39]
INFO:     Waiting for application startup.
2024-10-16 08:35:04,657 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2024-10-16 08:35:04,747 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [39]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-10-16 08:35:12,347 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:8081
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-10-16 08:35:27,349 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,356 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,656 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,948 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,948 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:27,957 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,049 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,057 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,061 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,165 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,177 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,252 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,289 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,347 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,474 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,547 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
2024-10-16 08:35:28,549 [mlserver] INFO - Loaded model 'mlflow-model' succesfully.
INFO:     10.244.0.111:0 - "POST /v2/models/wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/wine-classifier/infer HTTP/1.1" 404 Not Found
INFO:     10.244.0.111:0 - "POST /v2/models/wine-classifier/infer HTTP/1.1" 404 Not Found
/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlserver_mlflow/runtime.py:128: FutureWarning: ``mlflow.pyfunc.scoring_server.infer_and_parse_json_input`` is deprecated since 2.6.0. This method will be removed in a future release. Use ``infer_and_parse_data`` instead.
  data = infer_and_parse_json_input(raw_body, self._input_schema)
2024-10-16 11:22:48,209 [mlserver.parallel] ERROR - An error occurred calling method 'invocations' from model 'mlflow-model'.
Traceback (most recent call last):
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 668, in _validate_prediction_input
    data = _enforce_schema(data, input_schema, flavor)
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/models/utils.py", line 1184, in _enforce_schema
    return _enforce_tensor_schema(pf_input, input_schema)
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/models/utils.py", line 1040, in _enforce_tensor_schema
    raise MlflowException(
mlflow.exceptions.MlflowException: This model contains a tensor-based model signature with no input names, which suggests a numpy array input or a pandas dataframe input with proper column values, but an input of type <class 'list'> was found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlserver_mlflow/runtime.py", line 137, in invocations
    raw_predictions = self._model.predict(data)
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 755, in predict
    return self._predict(data, params)
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 788, in _predict
    data, params = _validate_prediction_input(
  File "/root/.mlflow/envs/mlflow-d8f1e42b6bc9c0f2977846872e48d7cd8749de56/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 671, in _validate_prediction_input
    raise MlflowException.invalid_parameter_value(
mlflow.exceptions.MlflowException: Failed to enforce schema of data '[{'name': array('input', dtype='<U5'), 'shape': array([13]), 'datatype': array('FP32', dtype='<U4'), 'data': array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])}]' with schema '[Tensor('float64', (-1, 13))]'. Error: This model contains a tensor-based model signature with no input names, which suggests a numpy array input or a pandas dataframe input with proper column values, but an input of type <class 'list'> was found.```

**Comment by daniellok-db** [comment]
the error message seems to indicate that you're querying the endpoint with an incorrect data type. have you set a [signature](https://mlflow.org/docs/latest/models.html#model-signatures-and-input-examples) on the model, and ensured that your provided input matches the schema?

**Comment by Mayurji** [comment]
This error should appear if i send a request to docker hosting the mlflow model, but it works fine there. And even the tutorial doesn't suggest creating a signature.

**Comment by Mayurji** [comment]
@daniellok-db , Thank you. Had to modify the request to match the schema.

**Comment by Mayurji** [comment]
@daniellok-db , Thank you. Had to modify the request to match the schema.
