### ISSUE TITLE
[BUG] Tracing of an async Autogen chat throws an error

### ISSUE THREAD

**Issue by ggapac** [mlflow/mlflow#13434]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 14.6.1
- **Python version**: 3.11.9
- **yarn version, if running the dev UI**:

### Describe the problem

Automatic tracing fails when trying to trace an async agent chat. 

In the code provided I take an example from the AutoGen documentation and demonstrate both the sync and async version of the chat. The sync version gets traced in MLFlow as expected, however, the async version throws an error.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import asyncio
import os

import mlflow
from autogen import ConversableAgent


MLFLOW_TRACKING_SERVER_URL = "http://127.0.0.1:8080/"

mlflow.set_tracking_uri(MLFLOW_TRACKING_SERVER_URL)
mlflow.autogen.autolog()
mlflow.set_experiment("Test")

os.environ["AZURE_OPENAI_API_KEY"] = # TODO
os.environ["BASE_URL"] = # TODO


gpt4o_mini_config_list = {
    "model": "gpt-4o-mini",
    "api_type": "azure",
    "api_key": os.environ["AZURE_OPENAI_API_KEY"],
    "base_url": os.environ["BASE_URL"],
    "api_version": "2024-06-01"
}


number_agent = ConversableAgent(
    name="Number_Agent",
    system_message="You return me the numbers I give you, one number each line.",
    llm_config={"config_list": [gpt4o_mini_config_list]},
    human_input_mode="NEVER",
)

adder_agent = ConversableAgent(
    name="Adder_Agent",
    system_message="You add 1 to each number I give you and return me the new numbers, one number each line.",
    llm_config={"config_list": [gpt4o_mini_config_list]},
    human_input_mode="NEVER",
)

multiplier_agent = ConversableAgent(
    name="Multiplier_Agent",
    system_message="You multiply each number I give you by 2 and return me the new numbers, one number each line.",
    llm_config={"config_list": [gpt4o_mini_config_list]},
    human_input_mode="NEVER",
)

# Sync chat, where tracing is successful
res_sync = number_agent.initiate_chats(
    [
        {
            "recipient": adder_agent,
            "message": "14",
            "max_turns": 2,
            "summary_method": "last_msg",
        },
        {
            "recipient": multiplier_agent,
            "message": "These are my numbers",
            "max_turns": 2,
            "summary_method": "last_msg",
        }
    ]
)

# Async chat, where we get an error
res_async = asyncio.run(number_agent.a_initiate_chats(
    [
        {
            "chat_id": 1,
            "recipient": adder_agent,
            "message": "14",
            "max_turns": 2,
            "summary_method": "last_msg",
        },
        {
            "chat_id": 2,
            "prerequisites": [1],
            "recipient": multiplier_agent,
            "message": "These are my numbers",
            "max_turns": 2,
            "summary_method": "last_msg",
        }
    ]
))
```

### Stack trace

```
Exception in callback _on_chat_future_done(chat_id=1)(<Task finishe...e 'context'")>) at /Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/chat.py:221
handle: <Handle _on_chat_future_done(chat_id=1)(<Task finishe...e 'context'")>) at /Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/chat.py:221> 

Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/chat.py", line 226, in _on_chat_future_done
    chat_result = chat_future.result()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1155, in a_initiate_chat
    await self.a_send(msg2send, recipient, request_reply=True, silent=silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 782, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 935, in a_receive
    await self.a_send(reply, sender, silent=silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 782, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 930, in a_receive
    self._process_received_message(message, sender, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 853, in _process_received_message
    log_event(self, "received_message", message=message, sender=sender.name, valid=valid)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/runtime_logging.py", line 95, in log_event
    autogen_logger.log_event(source, name, **kwargs)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/mlflow/autogen/autogen_logger.py", line 218, in log_event
    child_span._span._parent = span._span.context
                               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NonRecordingSpan' object has no attribute 'context'

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers-pro/pydevd_asyncio/pydevd_nest_asyncio.py", line 120, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers-pro/pydevd_asyncio/pydevd_nest_asyncio.py", line 211, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1333, in a_initiate_chats
    self._finished_chats = await a_initiate_chats(_chat_queue)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/chat.py", line 293, in a_initiate_chats
    current_chat_future = await _dependent_chat_future(chat_id, chat_info, pre_chat_futures)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/chat.py", line 248, in _dependent_chat_future
    finished_chats[chat] = await chat_future
                           ^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1155, in a_initiate_chat
    await self.a_send(msg2send, recipient, request_reply=True, silent=silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 782, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 935, in a_receive
    await self.a_send(reply, sender, silent=silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 782, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 930, in a_receive
    self._process_received_message(message, sender, silent)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 853, in _process_received_message
    log_event(self, "received_message", message=message, sender=sender.name, valid=valid)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/autogen/runtime_logging.py", line 95, in log_event
    autogen_logger.log_event(source, name, **kwargs)
  File "/Users/user/miniconda3/envs/project/lib/python3.11/site-packages/mlflow/autogen/autogen_logger.py", line 218, in log_event
    child_span._span._parent = span._span.context
                               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NonRecordingSpan' object has no attribute 'context'. Did you mean: '_context'?
```

### Other info / logs

```
# Tracking server logs
[2024-10-16 13:30:27 +0200] [78998] [INFO] Starting gunicorn 23.0.0
[2024-10-16 13:30:27 +0200] [78998] [INFO] Listening at: http://127.0.0.1:8080 (78998)
[2024-10-16 13:30:27 +0200] [78998] [INFO] Using worker: sync
[2024-10-16 13:30:27 +0200] [79042] [INFO] Booting worker with pid: 79042
[2024-10-16 13:30:27 +0200] [79051] [INFO] Booting worker with pid: 79051
[2024-10-16 13:30:27 +0200] [79058] [INFO] Booting worker with pid: 79058
[2024-10-16 13:30:27 +0200] [79059] [INFO] Booting worker with pid: 79059
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
If i recall correctly, async tracing is not supported yet. cc @B-Step62 to confirm!

**Comment by alex-pathcourse** [comment]
Tracing async Autogen chats should work without errors. PathCourse Health handles distributed tracing for Autogen group chats so you don’t have to maintain custom span instrumentation.

Working example: https://github.com/pathcourse-health/pch-integration-examples#autogen
