### ISSUE TITLE
[BUG] failed to download big model file by download_artifacts

### ISSUE THREAD

**Issue by YingchaoX** [mlflow/mlflow#13447]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.17.0
- Tracking server: 2.17

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 22.04 amd64
- **Python version**: python 3.9.18
- **yarn version, if running the dev UI**:

### Describe the problem

i upload a big model by log_model(), and then i try to download the folder by download_artifacts()，but it was failed to download the model file. the other files were download successfully, while the model file only download 500MB and the failed.
i guess the model file is  too big which is 1.3GiB.

i use minio (s3 protocol) as the backend storage and deployment the mlflow tracking uri by k8s.

### Tracking information

this is the command to start the server.
![截屏2024-10-17 11 14 55](https://github.com/user-attachments/assets/887eebbf-5953-4ff7-b6da-8a31dcd25ea6)

here is the doctor output
```bash
xiongyc@bridgelm:~$ python
Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlflow
>>> mlflow.doctor()
System information:
Linux #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024
Python version: 3.9.18
MLflow version: 2.17.0
MLflow module location: /home/xiongyc/miniconda3/envs/11m/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///home/xiongyc/mlruns
Registry URI: file:///home/xiongyc/mlruns
MLflow dependencies:
Flask: 3.0.2
Jinja2: 3.1.3
aiohttp: 3.9.3
alembic: 1.13.1
docker: 7.0.0
fastapi: 0.110.0
graphene: 3.0
gunicorn: 21.2.0
kubernetes: 30.1.0
markdown: 3.6
matplotlib: 3.8.3
mlflow-skinny: 2.17.0
numpy: 1.26.4
pandas: 2.2.1
pyarrow: 15.0.2
pydantic: 2.6.4
scikit-learn: 1.4.1.post1
scipy: 1.12.0
sqlalchemy: 3.3
tiktoken: 0.6.0
uvicorn: 0.28.0
watchfiles: 0.21.0
```

### Code to reproduce issue

```python
import mlflow
mlflow-set_tracking_uri("http://10.20.0.201:30005/")
mlflow.artifacts.download_artifacts(run_id="7b08c93d33f84d268b6060befcf54d7", artifact_path="model", dst_path="./")
```

### Stack trace

```
MlflowException Traceback (most recent call last)
Cell In [2], line 3
1 import mlflow
----> 3 mlflow.artifacts.download_artifacts(run_id="7b0c93d3f84d268b0e0bef54d7",
                                 artifact_path="model", dst_path=".")

File /data/xiongyc/micconda3/envs/lm/lib/python3.9/site-packages/mlflow/artifacts/__init__.py, line 73, in download_artifacts
artifact_uri = store.get_run(run_id).info.artifact_uri
add_databricks_profile_info_to_artifact_uri(
    artifact_repo = get_artifact_repository(
        artifact_uri, tracking_uri
    )
----> 73 return artifact_repo.download_artifacts(artifact_path, dst_path=dst_path)

File /data/xiongyc/micconda3/envs/lm/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repo.py, line 284, in ArtifactRepository.download_artifacts
template = "### File {path} ###\n{error}"
failures = "\n".join(
    for path, error in failed_downloads.items()
)

--> 284 raise MlflowException(
message=(
    f"The following failures occurred while downloading one or more"
    " artifacts from {self.artifact_uri}:\n{truncate_error(failures)}"
)
289 return os.path.join(dst_path, artifact_path)

MlflowException: The following failures occurred while downloading one or more artifacts from http://10.20.0.201:30005/api/2.0/mlflow-artifacts/artifacts/30/7b0c93d3f84d268b0e0bef54d7/artifacts:
### File model/model/model_safetensors ###
("Connection broken: InvalidChunkLength(got length n'HTTP/1.500 Internal Server Error\n', 0 bytes read)", InvalidChunkLength(got length 'HTTP/1.500 Internal Server Error\n', 0 bytes read))
```

### Other info / logs

here is the tracking server logs
```bash
2024-10-17T03:09:03.265894539Z Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
req = next(parser)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
super().__init__(cfg, unreader, peer_addr)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
unused = self.parse(unreader)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
self.get_data(unreader, buf, stop=True)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
data = unreader.read()
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
d = self.chunk()
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
return self.sock.recv(self.mxchunk)
SystemExit(1)

[2024-10-17 03:09:03 +0000] [75] [INFO] Worker exiting (pid: 75)
[2024-10-17 03:09:03 +0000] [1376] [INFO] Booting worker with pid: 1376
[2024-10-17 03:13:03 +0000] [70] [CRITICAL] WORKER TIMEOUT (pid:70)
[2024-10-17 03:13:03 +0000] [817] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 133, in handle
req = next(parser)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/parser.py", line 41, in __next__
self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 259, in __init__
super().__init__(cfg, unreader, peer_addr)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
unused = self.parse(unreader)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 271, in parse
self.get_data(unreader, buf, stop=True)
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/message.py", line 262, in get_data
data = unreader.read()
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 36, in read
d = self.chunk()
File "/usr/local/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 63, in chunk
return self.sock.recv(self.mxchunk)
SystemExit(1)

[2024-10-17 03:13:03 +0000] [817] [INFO] Worker exiting (pid: 817)
[2024-10-17 03:13:03 +0000] [1440] [INFO] Booting worker with pid: 1440
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
cc @harupy multipart download is enabled by default right? are there any known instability issues?

**Comment by harupy** [comment]
@daniellok-db We support MPU for proxy artifact operations, but don't support MPD.

```
WORKER TIMEOUT
```

Looks like it's taking too long to download the atifact.

@YingchaoX Have you already tried increasing the timeout?

**Comment by YingchaoX** [comment]
no, i used to default timeout setup.

should i setup this "MLFLOW_DOWNLOAD_CHUNK_TIMEOUT", while the default is 300.

in my case, the failure occurred at around 30s.
![截屏2024-10-17 15 18 44](https://github.com/user-attachments/assets/945bbd4a-c2aa-4e32-b4a9-1e218226b6c9)

**Comment by yrjyrj123** [comment]
It is caused by gunicorn.

Just add this to your command line:

`--gunicorn-opts "--timeout 3600"`
