### ISSUE TITLE
[BUG] mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(8000)

### ISSUE THREAD

**Issue by mcerman** [mlflow/mlflow#13575]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.17.0
- Tracking server: 2.17.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04.3 LTS
- **Python version**: 3.12.7

### Describe the problem

We have a tracking server and client, both with versions 2.17.0, running and track our training. We are using pytorch lightning and have set up a `pl.LightningModule` for our model module, a `pl.LightningDataModule` for our data module, and train using the `pl.Trainer`. Additionally we also use the `MLFlowLogger` from `pytorch_lightning.loggers`. We log hyperparameters, train and validation losses, a couple of validation images at the end of a validation epoch, and also save the model as an artifact. The validation/inference version of the model is created by calling the `get_export_model()` function and then submitted as an artifact using the `mlflow.pytorch.log_model()` function:

```python
mlflow.pytorch.log_model(
    pytorch_model=pl_module.get_export_model(),
    artifact_path=f"epoch_{trainer.current_epoch:04}/model",
    run_id=trainer.logger.run_id,
)
```

The first 15 validation epochs pass successfully and also log the model, but it consistenly fails after the 16th epoch with the error message below.

### Tracking information

```shell
System information: Linux #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024
Python version: 3.12.7
MLflow version: 2.17.0
MLflow module location: /home/<USER>/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/__init__.py
Tracking URI: file:///home/<USER>/dev/detekt/mlruns
Registry URI: file:///home/<USER>/dev/detekt/mlruns
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.10.6
  alembic: 1.13.3
  docker: 7.1.0
  graphene: 3.3
  gunicorn: 21.2.0
  markdown: 3.7
  matplotlib: 3.9.2
  mlflow-skinny: 2.17.0
  numpy: 1.26.4
  pandas: 2.2.3
  pyarrow: 15.0.2
  pydantic: 2.9.2
  scikit-learn: 1.5.2
  scipy: 1.14.1
  sqlalchemy: 2.0.35
  virtualenv: 20.26.6
```

### Code to reproduce issue

```
import pytorch_lightning as pl
import torch
from pytorch_lightning.callbacks import LearningRateMonitor
from pytorch_lightning.loggers import MLFlowLogger


class <MODEL>Module(pl.LightningModule):
    def __init__(
        self,
        model: <MODEL>,
        model_cfg: <MODEL>Conf,
        optimizer_cfg: OptimizerConfig,
        lr_scheduler_cfg: LearningRateSchedulerConfig,
        loss_cfg: LossConfig,
    ) -> None:
        super().__init__()

        ...

    def forward(self, images):
        ...

    def training_step(self, batch, batch_idx):
        ...
        
        loss, loss_item = self.loss_fn(...)

        loss_item = {f"train_{key}": val for key, val in loss_item.items()}
        loss_item["train_combined_loss"] = loss

        self.log_dict(loss_item, on_step=True, on_epoch=True, prog_bar=True, logger=True, batch_size=...)

        return loss

    def validation_step(self, batch, batch_idx):
        ...
        
        loss, loss_item = self.loss_fn(...)

        loss_item = {f"val_{key}": val for key, val in loss_item.items()}
        loss_item["val_combined_loss"] = loss

        # Log metrics
        self.log_dict(loss_item, on_step=False, on_epoch=True, prog_bar=True, logger=True, batch_size=...)

        return predicts_pp

    def on_validation_epoch_end(self):
        ...

    def configure_optimizers(self):
        ...

    def get_export_model(self) -> torch.nn.Module:
        val_model = <MODEL>(config=self.model_cfg, n_classes=self.model_cfg.class_num, val=True)

        train_weights = self.model.state_dict()
        val_weights = val_model.state_dict()

        num_loaded_weights = 0
        for model_key, model_weight in val_weights.items():
            if model_key in train_weights and model_weight.shape == train_weights[model_key].shape:
                val_weights[model_key] = train_weights[model_key]
                num_loaded_weights += 1

        val_model.load_state_dict(val_weights)

        return torch.nn.Sequential(self.pre_process, val_model).eval()

######################################


class DetektMLFlowCallback(Callback):
    """
    Callback to log extra metrics and artefacts to MLflow.

    Args:
        sample_image_every_nth_step: Sample an image every nth step and log it to MLflow.
    """

    def __init__(
        self,
        ...
        checkpoints_to_mlflow: bool = True,
    ):
        self.checkpoints_to_mlflow = checkpoints_to_mlflow


    def on_validation_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        if self.checkpoints_to_mlflow:
            mlflow.pytorch.log_model(
                pytorch_model=pl_module.get_export_model(),
                artifact_path=f"epoch_{trainer.current_epoch:04}/model",
                run_id=trainer.logger.run_id,
            )

######################################


data_module = DataModule(config.data)
model = build_model(
    config.model,
    n_classes=len(datamodule.class_names),
)

training_module = <MODEL>Module(
    model=model,
    model_cfg=config.model,
    optimizer_cfg=config.training.optimizer,
    lr_scheduler_cfg=config.training.learning_rate_scheduler,
    loss_cfg=config.training.loss,
)

callbacks = [LearningRateMonitor()]

logger = MLFlowLogger(
    run_name=config.run_name,
    experiment_name=config.experiment_name,
    tracking_uri=config.mlflow_uri,
    log_model=False,
)

logger.log_hyperparams(mlflow_normalize_dict(data_module.get_train_counts()))


logger.log_hyperparams(
    mlflow_normalize_dict(
        flatten_config(
            config.model_dump(mode="json", exclude={
                "data": {"sources": {"__all__": {"policy"}}}})
        )
    )
)

callbacks.append(
    MLFlowCallback(
        class_names=data_module.class_names,
        checkpoints_to_mlflow=config.training.mlflow_checkpoint_config.checkpoints_to_mlflow,
        disk_checkpoint_folder_path=config.training.mlflow_checkpoint_config.disk_checkpoint_folder_path,
    )
)

pl_trainer = pl.Trainer(
        max_epochs=config.training.epochs,
        limit_train_batches=config.training.n_batches_per_epoch,
        limit_val_batches=config.training.n_val_batches,
        logger=logger,
        callbacks=callbacks,
        log_every_n_steps=config.training.log_every_n_steps,
        num_sanity_val_steps=config.training.num_sanity_val_steps,
        check_val_every_n_epoch=config.training.check_val_every_n_epoch,
        gradient_clip_val=config.training.gradient_clip_val,
        gradient_clip_algorithm=config.training.gradient_clip_algorithm,
        precision=config.training.precision,
    )
mlflow.enable_system_metrics_logging()
pl_trainer.fit(model=training_module, datamodule=data_module, ckpt_path=config.training.checkpoint_path)
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/models/model.py", line 780, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model, run_id)
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 1559, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/tracking/client.py", line 2748, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 799, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 542, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 82, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcerman/.conda/envs/detekt_ml_new_env/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 240, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(8000)

[SQL: UPDATE tags SET value=%(value)s WHERE tags.key = %(tags_key)s AND tags.run_uuid = %(tags_run_uuid)s]
[parameters: {'value': '[{"run_id": "42f808089b5f4f52ba7b25a0211fc104", "artifact_path": "epoch_0000/model", "utc_time_created": "2024-10-28 15:01:57.963963", "model_uuid":  ... (8202 characters truncated) ... ", "loader_module": "mlflow.pytorch", "python_version": "3.12.7", "data": "data", "env": {"conda": "conda.yaml", "virtualenv": "python_env.yaml"}}}}]', 'tags_key': 'mlflow.log-model.history', 'tags_run_uuid': '42f808089b5f4f52ba7b25a0211fc104'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@mcerman The error message indicates that the tag `mlflow.log-model.history` exceeds the length limit of tag value (8000). That tag contains all models information that has been logged to the single run for model tracking purpose.

Since you are trying to log 16th model, it seems the single model metadata contains 500> characters. I suspect we could shrink it by filtering out unnecessary metadata fields before writing to the tag. Would you mind sharing what is being logged in `MLModel` in your run's artifact? It should contain same metadata as what's being logged to the tag as a single model metadata.

**Comment by mcerman** [comment]
@B-Step62 Hi, thank you very much for your quick response! I'll be able to have a look at it beginning of next week. I'll come back with my findings then. Thanks

**Comment by rsonger** [comment]
This issue is currently blocking me from being able to log models in a time series forecasting project where each time step has its own model trained in a single run. The `mlflow.log-model.history` tag gets filled up with metadata from the first 15 time-step models before reaching the limit and preventing any further models from being logged. Here is a sample of the metadata for one of the models:
```json
  {
    "run_id": "802210759cfa43f5bf45f8034db8ab93",
    "artifact_path": "sep_idx_13055+30",
    "utc_time_created": "2024-11-21 09:30:36.727335",
    "model_uuid": "a2c64e90fe684072b73bfaacb305930b",
    "flavors": {
      "python_function": {
        "loader_module": "mlflow.catboost",
        "python_version": "3.11.3",
        "data": "model.cb",
        "env": {
          "conda": "conda.yaml",
          "virtualenv": "python_env.yaml"
        }
      },
      "catboost": {
        "catboost_version": "1.2",
        "code": null,
        "model_type": "CatBoostRegressor",
        "save_format": "cbm",
        "data": "model.cb"
      }
    }
  },
```
