### ISSUE TITLE
[BUG] INVALID_PARAMETER_VALUE: Bad model name: please specify all three levels of the model in the form `catalog_name.schema_name.model_name`

### ISSUE THREAD

**Issue by miguel-m-cunha** [mlflow/mlflow#13833]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I am trying to migrate the models registered in one workspace which is not Unity Catalog enabled (non-UC) to another that is Unity Catalog enabled (UC). In the old workspace we have the models registered in the Workspace Model Registry, using stages as we haven't migrated yet to alias.

I am using the [mlflow-export-import](https://github.com/mlflow/mlflow-export-import/tree/master) package to migrate the models using the model names. In order to do so, I execute the export commands in the non-UC workspace, and then jump in the UC workspace and run the import commands to get the models. The export works fine, but the import gives me an error connect to the model name in Unity Catalog.

My objective is just to import the registered models from the non-UC workspace to the UC workspace, BUT register them in the Workspace Model Registry still, before we migrate them to the UC.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

On the non-UC workspace:

```
%pip install tabulate
%pip install mlflow-export-import
%pip install databricks-cli
dbutils.library.restartPython()

import mlflow
from mlflow_export_import.bulk import export_models
from mlflow_export_import.common import utils
import os

model_name = "amaz-datahub-ml-equ-mlr"

# define the environment variables
os.environ["DATABRICKS_HOST"] = "https://" + spark.conf.get("spark.databricks.workspaceUrl")
os.environ["DATABRICKS_TOKEN"] = environemnt_key

export_path = "dbfs:/mnt/abfss/temp/stagingzone/mlflow"

# run code in 
os.system(f"export-models --output-dir {export_path} --models {model_name}") # all

```

On the UC workspace:
```
%pip install tabulate
%pip install mlflow-export-import
%pip install databricks-cli
%pip install databricks-sdk
dbutils.library.restartPython()

# get secret from key vault
environemnt_key = dbutils.secrets.get(xxxxxx)

import_path = "/Volumes/datahub_dev/stagingzone/mlflow"

os.environ["DATABRICKS_HOST"] = "https://" + spark.conf.get("spark.databricks.workspaceUrl")
os.environ["DATABRICKS_TOKEN"] = environemnt_key

os.system(f"import-models --input-dir {import_path}")

```

### Stack trace

```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/bin/import-models", line 8, in <module>
    sys.exit(main())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/bulk/import_models.py", line 111, in main
    import_all(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/bulk/import_models.py", line 92, in import_all
    model_res = _import_models(client, input_dir, run_info_map, delete_model, import_source_tags, verbose, use_threads)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/bulk/import_models.py", line 75, in _import_models
    importer.import_model(model, dir, delete_model, verbose)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/model/import_model.py", line 188, in import_model
    model_dct = self._import_model(model_name, input_dir, delete_model)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/model/import_model.py", line 104, in _import_model
    raise e
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2bc73fe6-585e-465b-8266-e4f82e6a864b/lib/python3.10/site-packages/mlflow_export_import/model/import_model.py", line 100, in _import_model
    self.mlflow_client.create_registered_model(model_name, tags, model_dct.get("description"))
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/client.py", line 3110, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 64, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/store/_unity_catalog/registry/rest_store.py", line 347, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModelRequest, req_body)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/store/model_registry/base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 240, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Bad model name: please specify all three levels of the model in the form `catalog_name.schema_name.model_name`
```

### Other info / logs

```

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@miguel-m-cunha Thanks for reporting. Can you report this in https://github.com/mlflow/mlflow-export-import?
