### ISSUE TITLE
Unsupported manifest media type application/vnd.oci.image.index.v1+json

### ISSUE THREAD

**Issue by Aleksandre19** [mlflow/mlflow#13834]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.17.1
- Tracking server: 2.17.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS Sequoia 15.1
- **Python version**: 3.12.7
- **yarn version, if running the dev UI**:

### Describe the problem

I try to deploy the model on SageMaker and get the error which says: Unsupported manifest media type application/vnd.oci.image.index.v1+json for image [image_name]. I tried to downgrade to 2.16.0 but the error remains.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
<flow Deployment step deployment> failed:
Internal error
Traceback (most recent call last):
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2784, in get_deployment
return sage_client.describe_endpoint(EndpointName=name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/botocore/client.py", line 569, in _api_call
return self._make_api_call(operation_name, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DescribeEndpoint operation: Could not find endpoint "endpoint".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
/project_code/pipelines/deployment.py", line 230, in _deploy_to_sagemaker
deployment = deployment_client.get_deployment(self.endpoint)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2786, in get_deployment
raise MlflowException(
mlflow.exceptions.MlflowException: There was an error while retrieving the deployment: An error occurred (ValidationException) when calling the DescribeEndpoint operation: Could not find endpoint "endpoint".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/tmpchd9yh2j/metaflow/cli.py", line 1166, in main
start(auto_envvar_prefix="METAFLOW", obj=state)
File "/tmp/tmpchd9yh2j/metaflow/tracing/__init__.py", line 27, in wrapper_func
return func(args, kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/core.py", line 829, in __call__
return self.main(args, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/core.py", line 782, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/core.py", line 610, in invoke
return callback(args, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/_vendor/click/decorators.py", line 21, in new_func
return f(get_current_context(), args, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/tmpchd9yh2j/metaflow/cli.py", line 469, in step
task.run_step(
File "/tmp/tmpchd9yh2j/metaflow/task.py", line 653, in run_step
self._exec_step_function(step_func)
File "/tmp/tmpchd9yh2j/metaflow/task.py", line 62, in _exec_step_function
step_function()
/project_code/pipelines/deployment.py", line 125, in deployment
self._deploy_to_sagemaker()
/project_code/pipelines/deployment.py", line 250, in _deploy_to_sagemaker
self._create_sagemaker_deployment(
/project_code/pipelines/deployment.py", line 306, in _create_sagemaker_deployment
deployment_client.create_deployment(
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 2332, in create_deployment
app_name, flavor = _deploy(
^^^^^^^^
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 448, in _deploy
deployment_operation = _create_sagemaker_endpoint(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 1602, in _create_sagemaker_endpoint
model_response = _create_sagemaker_model(
^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/mlflow/sagemaker/__init__.py", line 1900, in _create_sagemaker_model
return sage_client.create_model(create_model_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/botocore/client.py", line 569, in _api_call
return self._make_api_call(operation_name, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateModel operation: Unsupported manifest media type application/vnd.oci.image.index.v1+json for image 202914516383.dkr.ecr.us-east-1.amazonaws.com/mlflow-pyfunc:2.16.0. Ensure that valid manifest media type is used for specified image.
2024-11-20 00:49:53.346 [1732060090995387/deployment/2 (pid 12794)] 
Task failed.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Aleksandre19 This might be a bug in botocore. I'll look into it.

**Comment by harupy** [comment]
@Aleksandre19 Can you reproduce the bug without using mlflow?

**Comment by Aleksandre19** [comment]
You mean, try to deploy without mlflow?

**Comment by harupy** [comment]
@Aleksandre19 Yes, if it doesn't work, then sagemaker issue. If it doesn't, mlflow is missing something.

**Comment by harupy** [comment]
https://repost.aws/questions/QUQgFRXiCYTjCtyxH_e2x9yg/oci-format-unsupported-when-creating-a-sagemaker-model seems like a similar issue.

**Comment by pazevedo-hyland** [comment]
Same issue here

**Comment by Aleksandre19** [comment]
Thank you all.  I will try

**Comment by Broker89** [comment]
Hi @harupy  I've managed to fix the problem with this PR: https://github.com/mlflow/mlflow/pull/14699

I needed to change the build command here: https://github.com/mlflow/mlflow/blob/9b1e8eec7f1cce0eb4611270acc8dfb867ef604e/mlflow/models/docker_utils.py#L220 to:

    commands = [
        "docker",
        "buildx", 
        "build",
        "--output=type=docker",
        "--attest", "type=provenance,disabled=true",
        "-t",
        image_name,
        "-f",
        "Dockerfile",
        *platform_option,
        ".",
    ]

As Sagemaker is not supporting oci media types for the CreateModel operation (https://repost.aws/questions/QUYwYL0SKaTQWvQMyqCSBvdQ/manifest-error-when-staging-ml-model) but it only supports Docker V1 / 2 manifest media types. The current code automatically creates oci media types. 

The changes worked for me but I'm quite new to using docker therefore someone with a bit more experience should double check it

**Comment by Marccrampe** [comment]
Amazing job @Broker89, you just saved my issue !!!!!!!

**Comment by wyzzhe** [comment]
Same here, Amazing job @Broker89 , you just saved my issue !!!!!!! Thanks a lot!
And in windows, I use command "docker buildx build --output=type=docker --attest type=provenance,disabled=true -t $image -f dev.Dockerfile ." in .ps1 file to resolve this issue.

**Comment by svpino** [comment]
This is a great patch @Broker89! Hopefully, the team integrates PR https://github.com/mlflow/mlflow/pull/14699 quickly.

**Comment by MaGuth** [comment]
Hi, since that seems to be not implemented in the near future, has anyone managed to fix the problem in a more sustainable way than directly modifying the file itself?
