### ISSUE TITLE
MLflow UI fails on 1.0 RC1 when backend store is MySQL 8.x

### ISSUE THREAD

**Issue by ananthc** [mlflow/mlflow#1385]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Mojave , MySQL 8.0.16
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.0 RC1 (https://mlflow-snapshots.s3-us-west-2.amazonaws.com/mlflow-1.0.0-1199.8386d25-py2.py3-none-any.whl)
- **Python version**: 3.6
- **npm version (if running the dev UI):N/A
- **Exact command to reproduce**: Perform install per documentation and launch the UI as follows:
- Install MySQL 8.0.16 (latest brew install fetches this version)
- create database in mysql (ex: create database orion_tracker)
- pip3 install mlflow per RC instructions given here https://docs.google.com/document/d/1Hu1y73aR21uDPbuUTBlTfSN7e5tR-9txqk_VHlCnupk/edit# 
- run using : mlflow server --backend-store-uri=$MLFLOW_TRACKING_URI --default-artifact-root=<some-artifact-location>
- traverse to the MLflow UI
- UI shows an "OOPS" page

### Describe the problem
Mlflow does not run on MySQL 8.x versions when enabled with backend store for mysql. This seems to be because of a duplicate constraint name in the autogeneration of schemas when running the server. The error stack trace points to a duplicate constrain check name 'lifecycle_stage'  while creating the 'runs' table.

### Source code / logs

```
[2019-05-31 04:16:13 +1000] [7836] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 353, in write
    util.write(self.sock, arg, self.chunked)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/gunicorn/util.py", line 304, in write
    sock.sendall(data)
OSError: [Errno 41] Protocol wrong type for socket
2019/05/31 04:16:13 INFO mlflow.store.sqlalchemy_store: Creating initial MLflow database tables...
[2019-05-31 04:16:13,159] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/experiments/list [GET]
Traceback (most recent call last):
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (3822, "Duplicate check constraint name 'lifecycle_stage'.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/mlflow/server/handlers.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/mlflow/server/handlers.py", line 330, in _list_experiments
    experiment_entities = _get_store().list_experiments(request_message.view_type)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/mlflow/server/handlers.py", line 35, in _get_store
    _store = SqlAlchemyStore(store_dir, artifact_root)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 81, in __init__
    SqlAlchemyStore._initialize_tables(self.engine)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 97, in _initialize_tables
    InitialBase.metadata.create_all(engine)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/anaconda3/envs/automl/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (3822, "Duplicate check constraint name 'lifecycle_stage'.")
[SQL:
CREATE TABLE runs (
	run_uuid VARCHAR(32) NOT NULL,
	name VARCHAR(250),
	source_type VARCHAR(20),
	source_name VARCHAR(500),
	entry_point_name VARCHAR(50),
	user_id VARCHAR(256),
	status VARCHAR(20),
	start_time BIGINT,
	end_time BIGINT,
	source_version VARCHAR(50),
	lifecycle_stage VARCHAR(20),
	artifact_uri VARCHAR(200),
	experiment_id INTEGER,
	CONSTRAINT run_pk PRIMARY KEY (run_uuid),
	CONSTRAINT source_type CHECK (source_type IN ('NOTEBOOK', 'JOB', 'LOCAL', 'UNKNOWN', 'PROJECT')),
	CONSTRAINT status CHECK (status IN ('SCHEDULED', 'FAILED', 'FINISHED', 'RUNNING')),
	CONSTRAINT lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')),
	FOREIGN KEY(experiment_id) REFERENCES experiments (experiment_id)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2019-05-31 04:16:43 +1000] [7832] [CRITICAL] WORKER TIMEOUT (pid:7835)
[2019-05-31 04:16:43 +1000] [7835] [INFO] Worker exiting (pid: 7835)
[2019-05-31 04:16:43 +1000] [7845] [INFO] Booting worker with pid: 7845
2019/05/31 04:17:15 ERROR mlflow.store.sqlalchemy_store: Detected one or more differences between current database schema and desired schema, exiting. Diff:
 [ ( 'add_table',
    Table('runs', MetaData(bind=Engine(mysql://root:***@localhost:3306/orion_tracker)), Column('run_uuid', String(length=32), table=<runs>, primary_key=True, nullable=False), Column('name', String(length=250), table=<runs>), Column('source_type', String(length=20), table=<runs>, default=ColumnDefault('LOCAL')), Column('source_name', String(length=500), table=<runs>), Column('entry_point_name', String(length=50), table=<runs>), Column('user_id', String(length=256), table=<runs>), Column('status', String(length=20), table=<runs>, default=ColumnDefault('SCHEDULED')), Column('start_time', BigInteger(), table=<runs>, default=ColumnDefault(1559240235)), Column('end_time', BigInteger(), table=<runs>), Column('source_version', String(length=50), table=<runs>), Column('lifecycle_stage', String(length=20), table=<runs>, default=ColumnDefault('active')), Column('artifact_uri', String(length=200), table=<runs>), Column('experiment_id', Integer(), ForeignKey('experiments.experiment_id'), table=<runs>), schema=None)),
  ( 'add_table',
    Table('metrics', MetaData(bind=Engine(mysql://root:***@localhost:3306/orion_tracker)), Column('key', String(length=250), table=<metrics>, primary_key=True, nullable=False), Column('value', Float(), table=<metrics>, primary_key=True, nullable=False), Column('timestamp', BigInteger(), table=<metrics>, primary_key=True, nullable=False, default=ColumnDefault(<function SqlMetric.<lambda> at 0x11e6bae18>)), Column('step', BigInteger(), table=<metrics>, primary_key=True, nullable=False, default=ColumnDefault(0)), Column('run_uuid', String(length=32), ForeignKey('runs.run_uuid'), table=<metrics>, primary_key=True, nullable=False), schema=None)),
  ( 'add_table',
    Table('params', MetaData(bind=Engine(mysql://root:***@localhost:3306/orion_tracker)), Column('key', String(length=250), table=<params>, primary_key=True, nullable=False), Column('value', String(length=250), table=<params>, nullable=False), Column('run_uuid', String(length=32), ForeignKey('runs.run_uuid'), table=<params>, primary_key=True, nullable=False), schema=None)),
  ( 'add_table',
    Table('tags', MetaData(bind=Engine(mysql://root:***@localhost:3306/orion_tracker)), Column('key', String(length=250), table=<tags>, primary_key=True, nullable=False), Column('value', String(length=250), table=<tags>), Column('run_uuid', String(length=32), ForeignKey('runs.run_uuid'), table=<tags>, primary_key=True, nullable=False), schema=None))]
[2019-05-31 04:17:45 +1000] [7832] [CRITICAL] WORKER TIMEOUT (pid:7836)
[2019-05-31 04:17:45 +1000] [7832] [CRITICAL] WORKER TIMEOUT (pid:7845)
[2019-05-31 04:17:45 +1000] [7836] [INFO] Worker exiting (pid: 7836)
[2019-05-31 04:17:45 +1000] [7845] [INFO] Worker exiting (pid: 7845)
[2019-05-31 04:17:45 +1000] [7890] [INFO] Booting worker with pid: 7890
[2019-05-31 04:17:45 +1000] [7891] [INFO] Booting worker with pid: 7891

```

**Comment by dbczumar** [comment]
@ananthc This should be fixed by #1292, which was merged *after* RC1. You can try installing MLflow from the `master` branch to confirm that this problem has been addressed. Please reopen this ticket if you still encounter the described issue.
