### ISSUE TITLE
[BUG] Migration 0584bdc529eb crashes initialization of database tables for Azure SQL DB

### ISSUE THREAD

**Issue by uliseshdzc** [mlflow/mlflow#13890]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Tracking server: 2.18.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.11.4
- **yarn version, if running the dev UI**: N/A

### Describe the problem

The server crashes when using an Azure SQL database as the backend store. This started to happen when the new 0584bdc529eb was integrated.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
# The error also occurs when using mlflow server --backend-store-uri ...
mlflow.cli.server([
    "--backend-store-uri",
    "mssql+pyodbc://?odbc_connect=Driver={ODBC Driver 18 for SQL Server};Server=<MY SERVER>;Database=<MY DATABASE>;Uid=serveradmin;Pwd=<PASSWORD>;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
])
```

### Stack trace

```
2024/11/27 15:50:46 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2024/11/27 15:50:50 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\ddl\mssql.py:123: UserWarning: MS-SQL ALTER COLUMN operations that specify type_= should also specify a nullable= or existing_nullable= argument to avoid implicit conversion of NOT NULL columns to NULL.
  util.warn(
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
INFO  [alembic.runtime.migration] Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2024/11/27 15:51:12 ERROR mlflow.cli: Error initializing backend store
2024/11/27 15:51:12 ERROR mlflow.cli: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]'FK__datasets__experi__6477ECF3' is not a constraint. (3728) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Could not drop constraint. See previous errors. (3727)")        
[SQL: ALTER TABLE datasets DROP CONSTRAINT [FK__datasets__experi__6477ECF3]]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]'FK__datasets__experi__6477ECF3' is not a constraint. (3728) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Could not drop constraint. See previous errors. (3727)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\cli.py", line 426, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\server\handlers.py", line 369, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\server\handlers.py", line 346, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 45, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 56, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\server\handlers.py", line 167, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\tracking\sqlalchemy_store.py", line 175, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\db\utils.py", line 98, in _initialize_tables
    _upgrade_db(engine)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\db\utils.py", line 223, in _upgrade_db
    command.upgrade(config, "heads")
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\command.py", line 406, in upgrade
    script.run_env()
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\script\base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\db_migrations\env.py", line 86, in <module>
    run_migrations_online()
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\db_migrations\env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\runtime\migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\mlflow\store\db_migrations\versions\0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py", line 55, in upgrade
    op.drop_constraint(fk_constraint_name, SqlDataset.__tablename__, type_="foreignkey")
  File "<string>", line 8, in drop_constraint
  File "<string>", line 3, in drop_constraint
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\operations\ops.py", line 222, in drop_constraint
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\operations\base.py", line 442, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\operations\toimpl.py", line 213, in drop_constraint
    operations.impl.drop_constraint(
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\ddl\impl.py", line 390, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\ddl\mssql.py", line 73, in _exec
    result = super()._exec(construct, *args, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\alembic\ddl\impl.py", line 247, in _exec
    return conn.execute(construct, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\<MY USER>\Desktop\azure_db_connection_patch\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]'FK__datasets__experi__6477ECF3' is not a constraint. (3728) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Could not drop constraint. See previous errors. (3727)")
[SQL: ALTER TABLE datasets DROP CONSTRAINT [FK__datasets__experi__6477ECF3]]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by uliseshdzc** [comment]
I removed the migration and ran the program again. The database is initialized with this key for me:

![image](https://github.com/user-attachments/assets/ce73a151-21bf-4231-89ee-b594088bf01d)

**Comment by WeichenXu123** [comment]
I think this line might set wrong constraint name:

https://github.com/mlflow/mlflow/blob/2cde6a5c02a5c276337af58d8afdce492223d0dd/mlflow/store/db_migrations/versions/0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py#L53

```
            # mssql fk constraint name at f5a4f2784254
            fk_constraint_name = f"FK__{SqlDataset.__tablename__}__experi__6477ECF3"
```

@daniellok-db would you take a look ? the code is added in https://github.com/mlflow/mlflow/pull/13741

**Comment by daniellok-db** [comment]
Hmm, that's interesting, the constraint is named as such in `tests/db/schemas/mssql.sql`:

https://github.com/mlflow/mlflow/pull/13741/files#diff-e38a5c9d8ccbd5f077565c58d755dcc56f7cdbd2b6b101a251f0804c09dfcba5L56

let me see what went wrong here

**Comment by daniellok-db** [comment]
@uliseshdzc would you mind confirming if the same problem occurs when using MSSQL 17 instead of 18?

**Comment by Tiemen-Vanderstraeten** [comment]
I've got the same error, both with ODBC dirver 17 and 18. Also using Azure SQL Database as backend store. It looks like it removes a foreign key from a table (datasets) that does not yet exist.

**Comment by daniellok-db** [comment]
@Tiemen-Vanderstraeten thanks for raising this. If you remove the latest migration, does it also initialize as `FK__datasets__experi__53B8409C`? Or is the key different. I'm trying to understand what causes this discrepancy

**Comment by Tiemen-Vanderstraeten** [comment]
@daniellok-db If I use MLFlow 2.17.2, everything works as expected.

**Comment by christinezuzart** [comment]
I too have got the same error with MSSQL 16 as well as MSSQL 22. MLFlow 2.18.0 , Python 3.12.8.


2024/12/12 15:58:18 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2024/12/12 15:58:18 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
c:\work\Code\DFMPro\Trunk\DFM\trunk\MachineLearning\AutoIgnore\src\code\autoignore_3128\Lib\site-packages\alembic\ddl\mssql.py:123: UserWarning: MS-SQL ALTER COLUMN operations that specify type_= should also specify a nullable= or existing_nullable= argument to avoid implicit conversion of NOT NULL columns to NULL.
  util.warn(
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysINFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys      
INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
INFO  [alembic.runtime.migration] Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments    
(pymssql.exceptions.OperationalError) (3728, b"'FK__datasets__experi__6477ECF3' is not a constraint.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: ALTER TABLE datasets DROP CONSTRAINT [FK__datasets__experi__6477ECF3]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by chris-aavang** [comment]
This was fixed in https://github.com/mlflow/mlflow/pull/14146 and released in [v2.20.0](https://github.com/mlflow/mlflow/releases/tag/v2.20.0).

> # MLflow 2.20.0
> [...]
> * \[Tracking\] Fix constraint name for MSSQL in migration 0584bdc529eb (https://github.com/mlflow/mlflow/pull/14146, @daniellok-db)
