### ISSUE TITLE
"mlflow db upgrade" fails on MySQL instance due to invalid keyword CONSTRAINT

### ISSUE THREAD

**Issue by tkocmathla** [mlflow/mlflow#1397]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: n/a
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: AWS Elastic Beanstalk (Amazon Linux)
- **MLflow installed from (source or binary)**: binary from pip
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6
- **Exact command to reproduce**:
mlflow db upgrade <db_uri>

### Describe the problem
The db upgrade command fails on a MySQL backend with the following error:
```
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT lifecycle_stage' at line 1")
[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
```

Evidently you must use FOREIGN KEY rather than CONSTRAINT on MySQL.

### Source code / logs
```
2019/06/04 15:57:22 INFO mlflow.store.db.utils: Updating database tables at mysql://<my_db_uri> in preparation for MLflow 1.0 schema migrations
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ff01da956556, ensure_unique_constraint_names
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT lifecycle_stage' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mlflow/db.py", line 23, in upgrade
    mlflow.store.db.utils._upgrade_db_initialized_before_mlflow_1(url)
  File "/usr/local/lib/python3.6/site-packages/mlflow/store/db/utils.py", line 90, in _upgrade_db_initialized_before_mlflow_1
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 77, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py", line 170, in upgrade
    condition=column('lifecycle_stage').in_(["active", "deleted"])
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/batch.py", line 73, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/mysql.py", line 107, in drop_constraint
    super(MySQLImpl, self).drop_constraint(const)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 240, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT lifecycle_stage' at line 1")
[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
(Background on this error at: http://sqlalche.me/e/f405)
2019/06/04 15:57:24 ERROR mlflow.cli: Error initializing backend store
2019/06/04 15:57:24 ERROR mlflow.cli: Detected out-of-date database schema (found version None, but expected 90e64c465722). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mlflow/cli.py", line 247, in server
    _get_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 35, in _get_store
    _store = SqlAlchemyStore(store_dir, artifact_root)
  File "/usr/local/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 89, in __init__
    SqlAlchemyStore._verify_schema(self.engine)
  File "/usr/local/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 128, in _verify_schema
    "more detail." % (current_rev, head_revision))
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version None, but expected 90e64c465722). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
```

**Comment by sueann** [comment]
hi @tkocmathla, what version of mysql are you using?

**Comment by tkocmathla** [comment]
This is an AWS RDS instance running MySQL 5.7.22.

**Comment by tkocmathla** [comment]
I upgraded a test instance to MySQL 8.0.15, and still get the same error.

**Comment by sueann** [comment]
Hi @tkocmathla, thanks for the info. Here's what I think is going on:

#### Root cause:

The migration script introduced in [this PR](https://github.com/mlflow/mlflow/pull/1292/commits/db4eba97b65c4255ef347812510306493f613088) drops some `CHECK` constraints.

To drop a check constraint in MySQL, 
- in versions 8.0.16+, you can use `DROP CHECK`
- in previous versions, dropping checks is not supported
However, `alembic` creates a `DROP CONSTRAINT` statement in its `drop_constraint` method, so the migration script here fails.

#### Resolution:
DBs that require the constraint names to be unique (e.g. mysql 8.0.16+) could not have been created pre-1.0, so they do not need to be migrated. 

DBs that do not require the constraint names to be unique (e.g. mysql 8.0.15-, postgres) do not need the “DROP CONSTRAINT” portion of the migration. 

Hence we can remove the “DROP CONSTRAINT” portion of the migration. I will create a PR to make this fix.

#### Workaround (until the next release):

Once the fix PR is in, you can check out the latest version of mlflow and build locally, then run the migration.
```
$ git clone https://github.com/mlflow/mlflow.git && cd mlflow  # or pull from master
... # optionally create a conda env (see the contribution guide linked below)
$ pip install -e .  # installs mlflow from current checkout
$ mlflow db upgrade <db_uri>
```
If you run into any trouble, please see the [contribution guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst) for more info on building and using mlflow locally.

If you don't want to wait for the PR, the change should be simple (just removing the drop_constraint calls [here](https://github.com/smurching/mlflow/blob/db4eba97b65c4255ef347812510306493f613088/mlflow/alembic/versions/ff01da956556_ensure_unique_constraint_names.py#L27) and [here]https://github.com/smurching/mlflow/blob/db4eba97b65c4255ef347812510306493f613088/mlflow/alembic/versions/ff01da956556_ensure_unique_constraint_names.py#L33)). The PR may take a little bit of time just so I can QA more scenarios.

**Comment by tkocmathla** [comment]
Thanks @sueann!

**Comment by tkocmathla** [comment]
I followed your workaround instructions and it worked nicely. Thanks again!

**Comment by SaadEphlux** [comment]
Hey I am still facing the same issue with mlflow 1.6.

**Comment by Esadruhn** [comment]
I have the same error with mlflow 1.6

* MLflow installed from (source or binary): binary from pip
* Ubuntu 18.04.3 LTS, backend: Postgres 11
* Python 3.7.6, psycopg2-binary 2.8.4

```
mlflow db upgrade postgresql://mlflow_user:mlflow_pwd@0.0.0.0:5432/mlflow_db

2020/02/19 16:25:46 INFO mlflow.store.db.utils: Updating database tables in preparation for MLflow 1.0 schema migrations
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ff01da956556, ensure_unique_constraint_names
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "experiments" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/db.py", line 28, in upgrade
    mlflow.store.db.utils._upgrade_db_initialized_before_mlflow_1(url)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 161, in _upgrade_db_initialized_before_mlflow_1
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 78, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 72, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py", line 174, in upgrade
    condition=column('lifecycle_stage').in_(["active", "deleted"])
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 354, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/batch.py", line 83, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 247, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "experiments" does not exist

[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
(Background on this error at: http://sqlalche.me/e/f405)
```
