### ISSUE TITLE
Facing issues in deploying mlflow models with  Kserve inference service.

### ISSUE THREAD

**Issue by VidhyaPandi** [mlflow/mlflow#14024]
### Discussed in https://github.com/mlflow/mlflow/discussions/13979

<div type='discussions-op-text'>

<sup>Originally posted by **VidhyaPandi** December  4, 2024</sup>
Hi team
Any help or suggestion is appreciated.
Issue:
We are trying to deploy a model created using the sample code - present in 
https://kserve.github.io/website/latest/modelserving/v1beta1/mlflow/v2/. 
We train a sample sklearn model and save as mlflow model format by calling mlflow log_model API. Here is the model artifacts gets tracked in our mlflow server.
![image](https://github.com/user-attachments/assets/bf68ad6f-209a-42c0-826b-02abeb41650d). 
We deploy our models in Kserve environment, here is the yaml configuration: 
--------
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mlflow-v2-wine-classifier"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: pvc://mlflow-v2-wine-classifier-pvc
---------
Error details:
Environment tarball not found at '/mnt/models/environment.tar.gz'
Environment not found at './envs/environment'
2024-12-04 14:11:18,893 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-12-04 14:11:18,962 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080/
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2024-12-04 14:11:18,983 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082/
2024-12-04 14:11:18,983 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-12-04 14:11:20,386 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:9000/
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082/ (Press CTRL+C to quit)
INFO:     127.0.0.1:55014 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55026 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55038 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55050 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55060 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55064 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:44440 - "GET / HTTP/1.1" 404 Not Found
2024/12/04 14:11:21 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
- mlflow (current: 2.3.1, required: mlflow==2.15.0)
- cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
- numpy (current: 1.23.5, required: numpy==1.26.4)
- psutil (current: uninstalled, required: psutil==5.9.8)
- scikit-learn (current: 1.2.2, required: scikit-learn==1.5.1)
- scipy (current: 1.9.1, required: scipy==1.13.1)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024-12-04 14:11:21,784 [mlserver] INFO - Couldn't load model 'mlflow-v2-wine-classifier'. Model will be removed from registry.
2024-12-04 14:11:21,784 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Load'.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 158, in _process_model_update
    await self._model_registry.load(model_settings)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 293, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 148, in load
    await self._load_model(new_model)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 165, in _load_model
    model.ready = await model.load()
  File "/opt/conda/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 155, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 582, in load_model
    model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))
  File "/opt/conda/lib/python3.8/site-packages/mlflow/models/model.py", line 468, in load
    return cls.from_dict(yaml.safe_load(f.read()))
  File "/opt/conda/lib/python3.8/site-packages/mlflow/models/model.py", line 478, in from_dict
    model_dict["signature"] = ModelSignature.from_dict(model_dict["signature"])
  File "/opt/conda/lib/python3.8/site-packages/mlflow/models/signature.py", line 83, in from_dict
    inputs = Schema.from_json(signature_dict["inputs"])
  File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 360, in from_json
    return cls([read_input(x) for x in json.loads(json_str)])
  File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 360, in <listcomp>
    return cls([read_input(x) for x in json.loads(json_str)])
  File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 358, in read_input
    return TensorSpec.from_json_dict(**x) if x["type"] == "tensor" else ColSpec(**x)
TypeError: __init__() got an unexpected keyword argument 'required'
2024-12-04 14:11:21,786 [mlserver] INFO - Couldn't load model 'mlflow-v2-wine-classifier'. Model will be removed from registry.
2024-12-04 14:11:21,789 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Unload'.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 160, in _process_model_update
    await self._model_registry.unload_version(
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 302, in unload_version
    await model_registry.unload_version(version)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 201, in unload_version
    model = await self.get_model(version)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 237, in get_model
    raise ModelNotFound(self._name, version)
mlserver.errors.ModelNotFound: Model mlflow-v2-wine-classifier not found
2024-12-04 14:11:21,790 [mlserver] ERROR - Some of the models failed to load during startup!
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/server.py", line 125, in start
    await asyncio.gather(
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 293, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 148, in load
    await self._load_model(new_model)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 161, in _load_model
    model = await callback(model)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/registry.py", line 152, in load_model
    loaded = await pool.load_model(model)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/pool.py", line 74, in load_model
    await self._dispatcher.dispatch_update(load_message)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 123, in dispatch_update
    return await asyncio.gather(
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 138, in _dispatch_update
    return await self._dispatch(worker_update)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 146, in _dispatch
    return await self._wait_response(internal_id)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 152, in _wait_response
    inference_response = await async_response
mlserver.parallel.errors.WorkerError: builtins.TypeError: __init__() got an unexpected keyword argument 'required'
2024-12-04 14:11:21,790 [mlserver.parallel] INFO - Waiting for shutdown of default inference pool...
INFO:     127.0.0.1:44446 - "GET / HTTP/1.1" 404 Not Found
2024-12-04 14:11:21,957 [mlserver.parallel] INFO - Shutdown of default inference pool complete
2024-12-04 14:11:21,957 [mlserver.grpc] INFO - Waiting for gRPC server shutdown
2024-12-04 14:11:21,961 [mlserver.grpc] INFO - gRPC server shutdown complete
INFO:     Shutting down
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
</div>

**Comment by serena-ruan** [comment]
@VidhyaPandi Which MLflow version are you using?

**Comment by VidhyaPandi** [comment]
Using version 2.15.0

________________________________

**Comment by serena-ruan** [comment]
From the current stacktrace, the mlflow version that was used to save the model is not compatible with the version that's used for loading the model `mlflow (current: 2.3.1, required: mlflow==2.15.0)`
Could you make sure the same version is used for logging and loading? And if there's still issues, pls upgrade to MLflow 2.19.0 and share the stacktrace
