### ISSUE TITLE
[BUG] is_databricks_connect TypeError if hasattr(spark.client, "metadata")

### ISSUE THREAD

**Issue by unj1m** [mlflow/mlflow#14174]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.19.0

### System information

- Linux Ubuntu 22.04
- 3.11.0

### Describe the problem

```
import databricks.connect, mlflow
spark = databricks.connect.DatabricksSession.builder.remote(host='...', token='...', cluster_id='...').getOrCreate()
mlflow.set_registry_uri('databricks-uc')
udf = mlflow.pyfunc.spark_udf(spark, "...", prebuilt_env_uri="...")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jim/p/automl-venv/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py", line 2077, in spark_udf
    is_dbconnect_mode = is_databricks_connect(spark)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/p/automl-venv/lib/python3.11/site-packages/mlflow/utils/databricks_utils.py", line 301, in is_databricks_connect
    return any(k in ["x-databricks-session-id", "x-databricks-cluster-id"] for k, v in metadata)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
```

Because `spark.client.metadata` is a method, not a list of tuples.  It needs to be called to get the desired metadata.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

See description above.  

### Other info / logs

The fix is to call `spark.client.metadata`.

I could write a test case, at which point I might as well create a PR.  It might come to that, :) 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Thanks for finding the bug! Filed a PR to fix it
