### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by KOUSHIKLA** [mlflow/mlflow#14180]
2024/12/30 19:37:08 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/experiments/search [GET]
Traceback (most recent call last):
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 573, in wrapper
    return func(*args, **kwargs)
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 614, in wrapper
    return func(*args, **kwargs)
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/mlflow/server/handlers.py", line 1549, in _search_experiments
    experiment_entities = _get_tracking_store().search_experiments(
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 328, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "/scratch/nanduc/nlp/miniconda3/envs/my_venv/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 423, in _get_experiment
    meta["tags"] = self.get_all_experiment_tags(experiment_id)
TypeError: 'NoneType' object does not support item assignment

How to fix it ?

**Comment by serena-ruan** [comment]
Please provide code to repro (most likely the meta.yaml file in your experiment directory is malformed)

**Comment by KOUSHIKLA** [comment]
Thank you for pointing that out! The issue was indeed related to the meta.yaml file, and I’ve already resolved it.
