### ISSUE TITLE
Unable to create table 'experiments' when MySQL is chosen as backend store

### ISSUE THREAD

**Issue by aranjanthakur** [mlflow/mlflow#1451]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS v10.14.4
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 2.7.16
- **npm version (if running the dev UI):
- **Exact command to reproduce**: mlflow server --backend-store-uri mysql://user:pass@MySql-server:3306/DB --default-artifact-root ./mlruns --host 0.0.0.0

### Describe the problem
I am using MySQL as the backend store. When I try to create server using the above command, server creation fails with the error 'Specified key was too long; max key length is 767 bytes' when trying to create table 'experiments'. 

### Source code / logs
root@ee9ffebd6949:/# mlflow server --backend-store-uri mysql://user:pass@MySql-server:3306/DB --default-artifact-root ./mlruns --host 0.0.0.0
2019/06/14 08:31:09 INFO mlflow.store.sqlalchemy_store: Creating initial MLflow database tables...
2019/06/14 08:31:13 ERROR mlflow.cli: Error initializing backend store
2019/06/14 08:31:13 ERROR mlflow.cli: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')
[SQL: 
CREATE TABLE experiments (
	experiment_id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(256) NOT NULL, 
	artifact_location VARCHAR(256), 
	lifecycle_stage VARCHAR(32), 
	CONSTRAINT experiment_pk PRIMARY KEY (experiment_id), 
	CONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), 
	UNIQUE (name)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mlflow/cli.py", line 247, in server
    _get_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python2.7/site-packages/mlflow/server/handlers.py", line 35, in _get_store
    _store = SqlAlchemyStore(store_dir, artifact_root)
  File "/usr/local/lib/python2.7/site-packages/mlflow/store/sqlalchemy_store.py", line 85, in __init__
    SqlAlchemyStore._initialize_tables(self.engine)
  File "/usr/local/lib/python2.7/site-packages/mlflow/store/sqlalchemy_store.py", line 101, in _initialize_tables
    InitialBase.metadata.create_all(engine)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')
[SQL: 
CREATE TABLE experiments (
	experiment_id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(256) NOT NULL, 
	artifact_location VARCHAR(256), 
	lifecycle_stage VARCHAR(32), 
	CONSTRAINT experiment_pk PRIMARY KEY (experiment_id), 
	CONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), 
	UNIQUE (name)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by smurching** [comment]
@aranjanthakur what version of MySQL are you using? It looks like this issue may be specific to MySQL 5.6 & older ([link](https://stackoverflow.com/a/1814594)) - is it possible for you to upgrade your database server's version of MySQL?

**Comment by aranjanthakur** [comment]
Thanks @smurching for the reply. We are using MySQL 5.1. We changed the charset to Latin1 and the tables got created in the DB. The problem is, metrics and params are getting logged under a directory mysql/user:pass@MySql-server:3306/DB in my server rather than in DB. There are no entries in DB tables.

**Comment by aranjanthakur** [comment]
Please ignore the above issue (that was because of a typo on my end). I am getting the following error while running the server.

2019/06/20 04:33:42 ERROR mlflow.cli: Error initializing backend store
2019/06/20 04:33:42 ERROR mlflow.cli: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/mlruns/0, 'active', 'Default', 0)' at line 1")
[SQL: INSERT INTO experiments (artifact_location, lifecycle_stage, name, experiment_id) VALUES (./mlruns/0, 'active', 'Default', 0);]
(Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mlflow/cli.py", line 247, in server
    _get_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python2.7/site-packages/mlflow/server/handlers.py", line 35, in _get_store
    _store = SqlAlchemyStore(store_dir, artifact_root)
  File "/usr/local/lib/python2.7/site-packages/mlflow/store/sqlalchemy_store.py", line 96, in __init__
    self._create_default_experiment(session)
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/mlflow/store/sqlalchemy_store.py", line 152, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
MlflowException: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/mlruns/0, 'active', 'Default', 0)' at line 1")
[SQL: INSERT INTO experiments (artifact_location, lifecycle_stage, name, experiment_id) VALUES (./mlruns/0, 'active', 'Default', 0);]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by kwin-wang** [comment]
@aranjanthakur I got the same error

**Comment by ProtD** [comment]
For MariaDB, the issue can be solved with
```
innodb_default_row_format=dynamic
innodb_file_format=barracuda
innodb_file_per_table=true
innodb_large_prefix=true
```
in `my.cnf`.

**Comment by SaadEphlux** [comment]
I am facing the same issue with mlflow 1.5 and 1.6 as well. I am using latest version of Maria DB.
Any suggestions how to resolve this?

ERROR mlflow.cli: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')
[SQL:
CREATE TABLE experiments (
experiment_id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(256) NOT NULL,
artifact_location VARCHAR(256),
lifecycle_stage VARCHAR(32),
CONSTRAINT experiment_pk PRIMARY KEY (experiment_id),
CONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')),
UNIQUE (name)
)

]

**Comment by NarekA** [comment]
If anyone is still having this issue, I made [this fork](https://github.com/NarekA/mlflow) which resolves it. If you deploy the fork once, it will create your database and then you can deploy the current version.
