### ISSUE TITLE
Unable to log_artifact using HDFS

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#1466]
Copied from an email thread on mlflow-users@googlegroups.com:

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:  Python 3.5
- **npm version (if running the dev UI): N/A
- **Exact command to reproduce**:

### Describe the problem
I am trying to use an HDFS for the artifact repository, but hitting an error when logging artifacts

### Source code / logs
I used the following command to run the mlflow server :
mlflow server --host 0.0.0.0 --default-artifact-root hdfs://--.--.--.---:8020/mlruns

In my python code :
```
mlflow.create_experiment("NewTest21","hdfs://--.--.--.---:8020/mlruns")
mlflow.set_experiment("NewTest21")
with mlflow.start_run():
	print(mlflow.get_artifact_uri())
	lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
	lr.fit(train_x, train_y)
	predicted_qualities = lr.predict(test_x)
	
	(rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)
	mlflow.log_param("alpha", alpha)
	mlflow.log_param("l1_ratio", l1_ratio)
	mlflow.log_metric("rmse", rmse)
	mlflow.log_metric("r2", r2)
	mlflow.log_metric("mae", mae)
        with open("output.txt", "w") as f:
    		f.write("Hello world! Its a new day")
    		mlflow.log_artifact("output.txt")
	mlflow.sklearn.log_model(lr,"hdfs://--.--.--.---::8020")
```

However I am getting the following error :
```
Traceback (most recent call last):
  File "C:\Program Files\KNIME\plugins\org.knime.python2_3.7.1.v201901281201\py\PythonKernelBase.py", line 278, in execute
    exec(source_code, self._exec_env, self._exec_env)
  File "<string>", line 59, in <module>
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\mlflow\tracking\fluent.py", line 244, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\mlflow\tracking\client.py", line 210, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\mlflow\store\hdfs_artifact_repo.py", line 34, in log_artifact
    with hdfs_system(host=self.host, port=self.port) as hdfs:
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\mlflow\store\hdfs_artifact_repo.py", line 168, in hdfs_system
    extra_conf=extra_conf)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\pyarrow\hdfs.py", line 211, in connect
    extra_conf=extra_conf)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\pyarrow\hdfs.py", line 36, in __init__
    _maybe_set_hadoop_classpath()
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\pyarrow\hdfs.py", line 134, in _maybe_set_hadoop_classpath
    classpath = _hadoop_classpath_glob(hadoop_bin)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\site-packages\pyarrow\hdfs.py", line 161, in _hadoop_classpath_glob
    return subprocess.check_output(hadoop_classpath_args)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\gs-2024\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by smurching** [comment]
Just to confirm, have you tried configuring auth environment variables etc as described in https://www.mlflow.org/docs/latest/tracking.html#hdfs? Also, what version of MLflow are you running?

**Comment by ShevyMittal-GSLab** [comment]
I didn't need to setup the environment variable. There were changes required in the core-site and hdfs xml files in the Hadoop environment. Making those changes I was able to resolve the issue.
Thanks

**Comment by smurching** [comment]
Awesome thanks @ShevyMittal-GSLab, will close this for now.

**Comment by finelycheng** [comment]
how did you solved this problem

**Comment by mustafa-pit** [comment]
I really wish @ShevyMittal-GSLab could have told us more about what he actually did to solve this isse. Does anyone from the mlflow team have any ideas?

**Comment by ramchinthamsetty** [comment]
Would you please share @ShevyMittal-GSLab how you have resolved this problem as we are running into the same issue?
