### ISSUE TITLE
Could not find valid Experiment ID when executing `mlflow run`

### ISSUE THREAD

**Issue by arinto** [mlflow/mlflow#147]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sierra 10.12.6
- **MLflow installed from (source or binary)**:  binary 
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.2.1
- **Python version**:  Python 3.6.6 :: Anaconda, Inc.
- **npm version (if running the dev UI)**: N.A
- **Exact command to reproduce**: 
```
(rr-sample-reg) ip-10-10-180-57:rr-sample-regression arinto$ mlflow experiments create life_sat_lr
Created experiment 'life_sat_lr' with id 1
(rr-sample-reg) ip-10-10-180-57:rr-sample-regression arinto$ export MLFLOW_EXPERIMENT_ID=1
(rr-sample-reg) ip-10-10-180-57:rr-sample-regression arinto$ mlflow run /Users/arinto/repository/github/rr-sample-regression -e main -P lr_feature="Employment rate as pct"
```

### Describe the problem
I try to organize runs into experiment following [this documentation](https://mlflow.org/docs/latest/tracking.html#organizing-runs-in-experiments) but `mlflow run` shows exception. I'm not using tracking server at the moment.

### Source code / logs
Exception stack from `mlflow run`

```
(rr-sample-reg) ip-10-10-180-57:rr-sample-regression arinto$ mlflow run /Users/arinto/repository/github/rr-sample-regression -e main -P lr_feature="Employment rate as pct"
=== Fetching project from /Users/arinto/repository/github/rr-sample-regression ===
=== Work directory for this run: /Users/arinto/repository/github/rr-sample-regression ===
=== Created directory /var/folders/fd/h7tg23rd2p3cx7mnp7j47_gw0000gn/T/tmpyzpx3_w9 for downloading remote URIs passed to arguments of type 'path' ===
Traceback (most recent call last):
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/cli.py", line 108, in run
    storage_dir=storage_dir)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 285, in run
    storage_dir=storage_dir, git_username=git_username, git_password=git_password)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 248, in _run_local
    _run_project(project, entry_point, work_dir, parameters, use_conda, storage_dir, experiment_id)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 415, in _run_project
    source_type=SourceType.PROJECT)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 257, in start_run
    entry_point_name, source_type)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 222, in _do_start_run
    source_version=(source_version or _get_source_version()), tags=[])
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/store/file_store.py", line 150, in create_run
    if self.get_experiment(experiment_id) is None:
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/store/file_store.py", line 116, in get_experiment
    raise Exception("Could not find experiment with ID %s" % experiment_id)
Exception: Could not find experiment with ID 1
```

**Comment by mateiz** [comment]
What is your `MLFLOW_TRACKING_URI` environment variable set to? Maybe this is pointing to a different location than where you created the experiment. The other problem could be if you ran these commands in different directories.

**Comment by arinto** [comment]
`MLFLOW_TRACKING_URI` is empty. 

```
(rr-sample-reg) arinto-mbp-tvlk:rr-sample-regression arinto$ echo $MLFLOW_TRACKING_URI

```
It seems that I need to set it up to `mlruns` (since I'm not using tracking server at the moment)

**Comment by mateiz** [comment]
Ah, I see. Maybe that mlruns directory needs to exist first. Make sure you run the create experiment command in the same directory where you have `mlruns` also.

**Comment by arinto** [comment]
Here's my latest observation
1. Creating the experiment will create folder `$PROJECT_ROOT\mlruns\$EXPERIMENT_ID`
2. However, that folder is erased after I executed `mlflow run .....`

I do not set `MLFLOW_TRACKING_URI` environment variable and relied on the default: `mlruns`

Here's the command line execution supporting my latest observation.
```
(rr-sample-reg) arinto-mbp-tvlk:rr-sample-regression arinto$ mlflow experiments create another_exp
Created experiment 'another_exp' with id 1
(rr-sample-reg) arinto-mbp-tvlk:rr-sample-regression arinto$ ls mlruns
0	1
(rr-sample-reg) arinto-mbp-tvlk:rr-sample-regression arinto$ mlflow run /Users/arinto/git/rr-sample-regression -e main -P lr_feature="Student skills as avg score"
=== Fetching project from /Users/arinto/git/rr-sample-regression ===
=== Work directory for this run: /Users/arinto/git/rr-sample-regression ===
=== Created directory /var/folders/fd/h7tg23rd2p3cx7mnp7j47_gw0000gn/T/tmp7_kl3llb for downloading remote URIs passed to arguments of type 'path' ===
Traceback (most recent call last):
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/cli.py", line 108, in run
    storage_dir=storage_dir)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 285, in run
    storage_dir=storage_dir, git_username=git_username, git_password=git_password)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 248, in _run_local
    _run_project(project, entry_point, work_dir, parameters, use_conda, storage_dir, experiment_id)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/projects.py", line 415, in _run_project
    source_type=SourceType.PROJECT)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 257, in start_run
    entry_point_name, source_type)
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 222, in _do_start_run
    source_version=(source_version or _get_source_version()), tags=[])
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/store/file_store.py", line 150, in create_run
    if self.get_experiment(experiment_id) is None:
  File "/Users/arinto/anaconda3/envs/rr-sample-reg/lib/python3.6/site-packages/mlflow/store/file_store.py", line 116, in get_experiment
    raise Exception("Could not find experiment with ID %s" % experiment_id)
Exception: Could not find experiment with ID 1
(rr-sample-reg) arinto-mbp-tvlk:rr-sample-regression arinto$ ls mlruns
0
```

**Comment by smurching** [comment]
Ah thanks for reporting the issue @arinto & investigating @mateiz, I think the problem is that we remove the `mlruns` directory from the working directory for the run if it exists [here](https://github.com/databricks/mlflow/blob/master/mlflow/projects.py#L339), and in this case the working directory for the run is the same as the tracking directory. I believe @juntai-zheng also hit this issue.

@mateiz I think a fix here could be to just not remove the "mlruns" & "outputs" directories - users who want to run in a pristine directory containing only their project files can pass the `--new-dir` flag to `mlflow run`.

**Comment by smurching** [comment]
@arinto a workaround for now is to run the `create experiment` and `mlflow run` commands from a directory other than (`/Users/arinto/repository/github/rr-sample-regression`) the one containing the project itself, or running `mlflow run` with the `--new-dir` flag

**Comment by arinto** [comment]
Ok, thanks for the workaround! It works! Should we keep this bug? Seems like it's low priority bug.

**Comment by smurching** [comment]
@arinto I think we should fix the issue, would you be interested in making a PR? I'd be happy to review & merge it :)

**Comment by arinto** [comment]
@smurching : so what is the correct behaviour ?
When we execute mlflow run in current working directory, we should not wipe out existing tracking directory? 

Any UT that emulate this scenario? 
I'm still occupied with another task, hence could not deep dive to the code at the moment. A pointer to the existing UT will speed up understanding of the code.

**Comment by smurching** [comment]
@arinto good question, yeah we shouldn't remove the tracking directory (`mlruns`) from the working directory for project execution. I think we just need to remove the `shutil.rmtree` calls [here](https://github.com/databricks/mlflow/blob/master/mlflow/projects.py#L338-L339). We do have a unit test for `mlflow.projects._fetch_project` (the utility method that fetches projects into a working directory / currently removes the `mlruns` directory, [see here](https://github.com/databricks/mlflow/blob/master/tests/projects/test_projects.py#L17)). We could add a test that creates an `mlruns` folder within a temp directory, attempts to fetch the temp directory, and verifies that the fetched directory's contents match the original as we do [here](https://github.com/databricks/mlflow/blob/master/tests/projects/test_projects.py#L23-L27)

**Comment by arinto** [comment]
Cool, will close this issue since PR is merged.
