### ISSUE TITLE
mlflow.exceptions.MlflowException: API request

### ISSUE THREAD

**Issue by anacarol** [mlflow/mlflow#1473]
Hi,

I am having the following issue. I am using version 0.9.0 and I tried also with the latest one.
I've checked on past similar issues and tried the suggestions but nothing works...
Anyone else running through this or with a new solution I havent tried?

Thanks!

2019/06/19 10:12:53 ERROR mlflow.utils.rest_utils: API request to https://mlflow-tracking.staging.travix.com/api/2.0/preview/mlflow/runs/log-parameter failed with code 500 != 200, retrying up to 1 more times. API response body:

<title>500 Internal Server Error</title>
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

2019/06/19 10:12:56 ERROR mlflow.utils.rest_utils: API request to https://mlflow-tracking.staging.travix.com/api/2.0/preview/mlflow/runs/log-parameter failed with code 500 != 200, retrying up to 0 more times. API response body:

<title>500 Internal Server Error</title>
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Traceback (most recent call last):
File "/anaconda/envs/emailforecasting/bin/mlflow", line 10, in 
sys.exit(cli())
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/cli.py", line 141, in run
run_id=run_id,
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/projects/init.py", line 209, in run
storage_dir=storage_dir, block=block, run_id=run_id)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/projects/init.py", line 81, in _run
tracking.MlflowClient().log_param(active_run.info.run_uuid, key, value)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/tracking/client.py", line 162, in log_param
self.store.log_param(run_id, param)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 182, in log_param
self._call_endpoint(LogParam, req_body)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 64, in _call_endpoint
host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 73, in http_request_safe
response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
File "/anaconda/envs/emailforecasting/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 58, in http_request
(url, retries))
mlflow.exceptions.MlflowException: API request to https://mlflow-tracking.staging.travix.com/api/2.0/preview/mlflow/runs/log-parameter failed to return code 200 after 3 tries
(emailforecasting) ➜ customerservice.callforecasting git:(acsaj)

**Comment by Aksh97** [comment]
Any solution to this?
