### ISSUE TITLE
docker example run error

### ISSUE THREAD

**Issue by MainHanzo** [mlflow/mlflow#1510]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``mlflow --version``)**:1.0.0
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**: **mlflow run examples/docker -P alpha=0.5**

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

I have followed the tuto of using a model in docker instead of conda. After building the image named mlflow-docker-example, I get this image locally:

REPOSITORY                                  TAG                   IMAGE ID                 CREATED                SIZE
mlflow_docker_example               latest              177e28ba0751        12 minutes ago      1.07 GB

However if I try to run this with the command: 
**mlflow run examples/docker -P alpha=0.5**

It would return to me such an error:

Traceback (most recent call last):
  File "/root/anaconda3/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/mlflow/cli.py", line 137, in run
    run_id=run_id,
  File "/root/anaconda3/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 230, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "/root/anaconda3/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 128, in _run
    active_run=active_run)
  File "/root/anaconda3/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 738, in _build_docker_image
    fileobj=docker_build_ctx, custom_context=True, encoding="gzip")
  File "/root/anaconda3/lib/python3.6/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: repository docker.io/mlflow-docker-example not found: does not exist or no pull access

PLS help

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by Dhaval08** [comment]
@MainHanzo Were you able to figure out a solution? I am facing the exact same error. Thank you.
