### ISSUE TITLE
MlFlow Java client: Failed to get mlflow version. Error: /usr/bin/python: No module named mlflow

### ISSUE THREAD

**Issue by TotalForgot** [mlflow/mlflow#1515]
### System information
- **I have just wrote a simple test on Mlflow Java-client**:
- **OS Platform and Distribution**: Client side: MAC OS. Server side: CentOS 7.4
- **MLflow installed from**: binary
- **MLflow version**: 1.0.0
- **Python version**: 2.7.10

### Describe the problem
We start a Mlflow server on our CentOS 7.4 node.
Then we created a simple java project to do very basic operation on the from our MAC laptop to this Mlflow server.

When trying to logArtifact, we received an exception mentioning that mlflow is not installed in our MAC laptop. Which is correct as we did not install it.

### Expectation
Our expectation is that, for a java-client, all we need to do is to declare the correct mlflow java-client jar so that our Mlflow client can connect correctly to the remote Mlflow server.
**So why it is required to have Mlflow installed on the client side?**
Please enlighten us.
Below is the logs and the stack trace

### Source code 
`
class Test {

    @org.junit.jupiter.api.Test
    void testMlFlow() {

        final MlflowClient client = new MlflowClient("http://remoteServer:5000");

        final String expName = "MyExp";

        final String expId = client.createExperiment(expName);

        final List<Service.Experiment> experimentList =client.listExperiments();

        final Service.RunInfo info = client.createRun(Service.CreateRun.newBuilder().setExperimentId(expId).build());

        client.logArtifact(info.getRunId(), new File("/tmp/test"));

    }
}
`

### Log
`org.mlflow.tracking.MlflowClientException: Failed to exec 'python -m mlflow.cli', needed to access artifacts within the non-Java-native artifact store at './mlruns/5/a1f44550f3194af3bf15e439862382e4/artifacts'. Please make sure mlflow is available on your local system path (e.g., from 'pip install mlflow')
	at org.mlflow.artifacts.CliBasedArtifactRepository.checkMlflowAccessible(CliBasedArtifactRepository.java:181)
	at org.mlflow.artifacts.CliBasedArtifactRepository.logArtifact(CliBasedArtifactRepository.java:66)
	at org.mlflow.artifacts.CliBasedArtifactRepository.logArtifact(CliBasedArtifactRepository.java:84)
	at org.mlflow.tracking.MlflowClient.logArtifact(MlflowClient.java:399)
	at com.exalead.onetrace.intelligent.services.Test.testMlFlow(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.mlflow.tracking.MlflowClientException: Failed to get mlflow version. Error: /usr/bin/python: No module named mlflow
	at org.mlflow.artifacts.CliBasedArtifactRepository.forkMlflowProcess(CliBasedArtifactRepository.java:209)
	at org.mlflow.artifacts.CliBasedArtifactRepository.checkMlflowAccessible(CliBasedArtifactRepository.java:173)
	... 55 more
`

**Comment by andrewmchen** [comment]
Currently the code to log files as artifacts to the different ArtifactRepositories only exists in Python. That's why we currently require the Python client to log artifacts in Java too. We are planning on adding native support to log artifacts to DBFS in the near future. After that piece of code is in, the infrastructure should be there to add ability to log artifacts to different filesystem backends.

**Comment by lucagiovagnoli** [comment]
Is there a way to download artifacts from a java codebase ?

**Comment by PriyaTomar** [comment]
I am facing similar type of problem.  I am using Java API to log the artifacts. I get error when I need to download the pre-stored artifacts. The error is: 
''Failed to exec 'python -m mlflow.store.artifact.cli', needed to access artifacts within the non-Java-native artifact store at 'null'. Please make sure mlflow is available on your local system path (e.g., from 'pip install mlflow')''.

Any solution for this??

**Comment by jotarada** [comment]
What a piece of crap. If java support can't added don't wrap it into a python code. It was better not include it at all. 
Need a python lib to run java code is insane.
