### ISSUE TITLE
error specifying MLproject with zero parameters

### ISSUE THREAD

**Issue by sameermahajan** [mlflow/mlflow#1541]
I am trying to specify MLproject with zero parameters as:

> `name: test
> 
> conda_env: conda.yaml
> 
> entry_points:
>   main:
>     parameters:
>     command: "python test.py"

when I get an error:

` Traceback (most recent call last):
 File "/home/ubuntu/.local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mlflow/cli.py", line 137, in run
    run_id=run_id,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mlflow/projects/__init__.py", line 230, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mlflow/projects/__init__.py", line 85, in _run
    project = _project_spec.load_project(work_dir)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mlflow/projects/_project_spec.py", line 40, in load_project
    entry_points[name] = EntryPoint(name, parameters, command)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mlflow/projects/_project_spec.py", line 87, in __init__
    self.parameters = {k: Parameter(k, v) for (k, v) in parameters.items()}
AttributeError: 'NoneType' object has no attribute 'items'

Am I missing something or mlflow does not allow project with zero parameters?

I have also posted this at my public repo of: https://github.com/sameermahajan/mlflow-try if someone would like to try out:

mlflow run https://github.com/sameermahajan/mlflow-try.git

**Comment by sameermahajan** [comment]
For this, you completely drop the 'parameters' section as below:

```
name: test

conda_env: conda.yaml

entry_points:
  main:
    command: "python test.py"

```
(I thought I had tried it earlier but I was trying too many different ways to may be miss out on this one)
```
