### ISSUE TITLE
when i set default-artifact-root , exceptions happend like this

### ISSUE THREAD

**Issue by finelycheng** [mlflow/mlflow#1545]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:  
- **MLflow version (run ``mlflow --version``)**: 1.0
- **Python version**:  3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.
i started the server like this:
mlflow server  --backend-store-uri "/home/experiment_data/"  -h 0.0.0.0 -p 5000  --default-
artifact-root "hdfs://finely:9000"
when i run the example with 
 root@finely:/home/finely/PycharmProjects/mlflow/examples# python ./sklearn_elasticnet_wine/train.py 

an exception happened 

2019-07-03 21:05:38,894 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Messagejava.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:225)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:900)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1660)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1583)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1580)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1595)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
hdfsCreateDirectory(/0/6fe34c6d6753471ebbcbfb3e86f64c2b/artifacts/wine): FileSystem#mkdirs error:
IllegalStateException: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:129)
        at org.apache.hadoop.ipc.Client.setCallIdAndRetryCount(Client.java:118)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:162)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.mkdirs(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.primitiveMkdir(DFSClient.java:2419)
        at org.apache.hadoop.hdfs.DFSClient.mkdirs(DFSClient.java:2395)
        at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1325)
        at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1322)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.mkdirsInternal(DistributedFileSystem.java:1339)
        at org.apache.hadoop.hdfs.DistributedFileSystem.mkdirs(DistributedFileSystem.java:1314)
        at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2275)
Traceback (most recent call last):
  File "./sklearn_elasticnet_wine/train.py", line 71, in <module>
    mlflow.sklearn.log_model(lr, "wine")
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/mlflow/sklearn.py", line 195, in log_model
    serialization_format=serialization_format)
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/mlflow/models/__init__.py", line 78, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 255, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/mlflow/tracking/client.py", line 221, in log_artifacts
    artifact_repo.log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/mlflow/store/hdfs_artifact_repo.py", line 52, in log_artifacts
    hdfs.mkdir(hdfs_base_path)
  File "/opt/anaconda3/envs/gluon/lib/python3.6/site-packages/pyarrow/hdfs.py", line 77, in mkdir
    return super(HadoopFileSystem, self).mkdir(path)
  File "pyarrow/io-hdfs.pxi", line 363, in pyarrow.lib.HadoopFileSystem.mkdir
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: HDFS create directory failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by finelycheng** [comment]
when i use sftp  there is also an exception happened when call the function mkdir  
permission deneied  ........

**Comment by mparkhe** [comment]
Are you trying to use HDFS to store artifacts or store them locally. The following error message suggests that HDFS access may not be set up correctly using kerberos. Also the path seems to be missing.

```
pyarrow.lib.ArrowIOError: HDFS create directory failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
```

[Artifact storage documentation for HDFS](https://mlflow.org/docs/latest/tracking.html#hdfs)
