### ISSUE TITLE
[BUG] MLFlow 1.1.0 - Database migration fails for Microsoft SQL

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [mlflow/mlflow#1667]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**:  Binary
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**:  python 3.6.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
mlflow db upgrade db_url

### Describe the problem
Trying to start mlflow server, I got an exception that database should be migrated (this was a new empty database. so, I really do not understand why empty database could not be installed from the beginning with appropriate DB schema)

When trying to perform the migration, the following exception occurs:
```
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ff01da956556, ensure_unique_constraint_names
Traceback (most recent call last):
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [FreeTDS][SQL Server]'lifecycle_stage' is not a constraint. (3728) (SQLExecDirectW)")
```

The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "/home/mlflow_user/.venvs/mlflow_env/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/mlflow/db.py", line 23, in upgrade
    mlflow.store.db.utils._upgrade_db_initialized_before_mlflow_1(url)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/mlflow/store/db/utils.py", line 91, in _upgrade_db_initialized_before_mlflow_1
    command.upgrade(config, 'heads')
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/util/compat.py", line 177, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 77, in <module>
    run_migrations_online()
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/runtime/migration.py", line 362, in run_migrations
    step.migration_fn(**kw)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py", line 174, in upgrade
    condition=column('lifecycle_stage').in_(["active", "deleted"])
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/operations/batch.py", line 79, in flush
    fn(*arg, **kw)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/ddl/impl.py", line 241, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/ddl/mssql.py", line 36, in _exec
    result = super(MSSQLImpl, self)._exec(construct, *args, **kw)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/mlflow_user/.venvs/mlflow_env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [FreeTDS][SQL Server]'lifecycle_stage' is not a constraint. (3728) (SQLExecDirectW)")
[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
(Background on this error at: http://sqlalche.me/e/f405)
```

### Code to reproduce issue
Install mlflow in venv on ubuntu 18.04
Specify valid connection str to MSSQL database
Try starting mlflow with backend_store pointing to the database

Observe failure by mlflow start in the logs

mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version None, but expected 181f10493468). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.

Try upgrading db schema

Observe this nice failure

**Comment by zanitete** [comment]
I have the same issue with Postgresql.
It seems like an empty db is detected as "initialized before mlflow 1.0". By removing the check at https://github.com/mlflow/mlflow/blob/v1.2.0/mlflow/db.py#L22 it works.

**Comment by ymym3412** [comment]
I got same issue with postgresql with Cloud SQL and my mlflow version is 1.3.0.
