### ISSUE TITLE
[BUG]mlflow models serve does not work in windows

### ISSUE THREAD

**Issue by stfj77** [mlflow/mlflow#1669]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: have used the add_n_model and xgboost model provided in samples
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**:  pip 
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:  `mlflow models serve --no-conda -m 'file'<some_path>/add_n_model`

### Describe the problem
It is not possible to start serving the model, as gunicorn is used also for windows in the method serve in backend.py.
(In case of the tracking UI there is waitress-serve used instead if  sys.platform == 'win32').

Following fix made it currently working for me:

```python
if sys.platform == 'win32':
        command = 'waitress-serve --expose-tracebacks --host={0} --port={1} --ident=mlflow mlflow.pyfunc.scoring_server.wsgi:app'.format(host, port)
        else:
            command = ("gunicorn --timeout 60 -b {host}:{port} -w {nworkers} "
                      "mlflow.pyfunc.scoring_server.wsgi:app").format(
                host=host,
                port=port,
                nworkers=self._nworkers)
```

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

**Comment by ankitmathur-db** [comment]
We only have support on Windows for tracking and the UI at the moment - please check out a workaround at #1684 and see if that might help you out!

**Comment by stfj77** [comment]
Thanks Ankit,

I have already provided the required change which made it working for me in my post.

Maybe you can incorporate it into a future release

Best regards
Josef


Am 01.08.19 um 19:45 schrieb Ankit Mathur

**Comment by ankitmathur-db** [comment]
Hi @stfj77 , does this mean you filed a PR?

**Comment by cyrilthank** [comment]
On windows10 mlflow run examples\sklearn_elasticnet_wine errors out with the below

Traceback (most recent call last):
  File "e:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "e:\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\mlflow\cli.py", line 137, in run
    run_id=run_id
  File "e:\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 266, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "e:\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 154, in _run
    run_id=active_run.info.run_id)
  File "e:\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 556, in _run_entry_point
    process = subprocess.Popen(command, close_fds=True, cwd=work_dir, env=env)
  File "e:\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "e:\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

please advise if this is related to known issue

requesting since putting the fix lines in line 140 of backend.py didnt work for me

**Comment by ahmadarbain** [comment]
@ankit-db can you please help me, i got this issue while i try model serve in 

```
'waitress-serve' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\ahmad\miniconda3\envs\mlflow\Scripts\mlflow-script.py", line 10, in <module>
    sys.exit(cli())
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\mlflow\models\cli.py", line 59, in serve
    ).serve(model_uri=model_uri, port=port, host=host, enable_mlserver=enable_mlserver)
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", line 79, in serve
    conda_env_path, command, self._install_mlflow, command_env=command_env
  File "C:\Users\ahmad\miniconda3\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", line 168, in _execute_in_conda_env
    "Command '{0}' returned non zero return code. Return code = {1}".format(command, rc)
Exception: Command 'conda activate mlflow-270591f5d4ece78a187f6457a571ae1ce1e4d11f & waitress-serve --host=127.0.0.1 --port=1235 --ident=mlflow mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 1
```
