### ISSUE TITLE
[BUG] `MlflowClient.download_artifacts` fails on empty directories with an `IsADirectoryError` when using `LocalArtifactRepository`

### ISSUE THREAD

**Issue by mgbckr** [mlflow/mlflow#1689]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora release 29 (Twenty Nine)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: NA
- **Exact command to reproduce**: NA

### Describe the problem
`MlflowClient.download_artifacts` fails on artifact directories containing empty directories with an `IsADirectoryError`. The following code snippet exemplifies the issue and also contains code lines as comments that `fix` the issue. For me this issue is related to the `LocalArtifactRepository`. The `MlflowClient.download_artifacts` method should simply support downloading empty directories.

### Code to reproduce issue
```python
import mlflow
import os
import tempfile

with tempfile.TemporaryDirectory() as tmp_dir:
    with mlflow.start_run():
        artifacts_dir = os.path.join(tmp_dir, "artifacts")
        empty_dir = os.path.join(artifacts_dir, "empty_dir")

        # empty_file = os.path.join(empty_dir, "empty.txt")
        # open(empty_file, 'a').close()

        mlflow.log_artifacts(artifacts_dir, "artifacts")
        run_id = mlflow.active_run().info.run_uuid

with tempfile.TemporaryDirectory() as tmp_dir:
    mlflow.tracking.MlflowClient().download_artifacts(run_id, "artifacts", tmp_dir)
```

### Other info / logs
Traceback:
```
Traceback (most recent call last):
  File "<project_home>/mlflow_bug.py", line 18, in <module>
    mlflow.tracking.MlflowClient().download_artifacts(run_id, "artifacts", tmp_dir)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/tracking/client.py", line 272, in download_artifacts
    return artifact_repo.download_artifacts(path, dst_path)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/store/local_artifact_repo.py", line 60, in download_artifacts
    return super(LocalArtifactRepository, self).download_artifacts(artifact_path, dst_path)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/store/artifact_repo.py", line 113, in download_artifacts
    return download_artifacts_into(artifact_path, dst_path)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/store/artifact_repo.py", line 91, in download_artifacts_into
    download_artifacts_into(artifact_path=file_info.path, dest_dir=local_path)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/store/artifact_repo.py", line 93, in download_artifacts_into
    self._download_file(remote_file_path=artifact_path, local_path=local_path)
  File "<virtualenv>/lib/python3.7/site-packages/mlflow/store/local_artifact_repo.py", line 88, in _download_file
    shutil.copyfile(remote_file_path, local_path)
  File "<virtualenv>/lib64/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '<project_home>/mlruns/0/efe570a205984c9e9fcf0840b469c0d4/artifacts/artifacts/empty_dir'
```

**Comment by mgbckr** [comment]
Hi, any progress on this?

**Comment by thisisandreeeee** [comment]
Has this been resolved?

**Comment by mgbckr** [comment]
I just tried in `1.7.0` and it doesn't seem to be an issue anymore.
