### ISSUE TITLE
Unable to use mlflow.projects.run API on my Spark Cluster

### ISSUE THREAD

**Issue by ShevyMittal-GSLab** [mlflow/mlflow#1703]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
I have saved a python file (The wine-quality python file as in mlflow example) and MLProject file in my own github repository. I am trying to log the model using mlflow.projects.run API giving the path of my github repository. However I get an error :

mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run '2ad8d348b4bd4cf59f16d3dc8eea9bf7' not found

### Code to reproduce issue

MLProject : - 
entry_points:
  main:
    command: "/usr/bin/spark-submit train.py"

train.py > Same as [mlflow example](https://github.com/mlflow/mlflow-example/blob/master/train.py)
Just added a line to change the tracking UI to my mlfow server.

On my spark cluster I run : -

import mlflow
r = mlflow.projects.run("--my github path",version='master',use_conda=False)

### Other info / logs

2019/08/07 05:13:41 INFO mlflow.projects: === Created directory /tmp/tmpowd4asyz for downloading remote URIs passed to arguments of type 'path' ===
2019/08/07 05:13:41 INFO mlflow.projects: === Running command '/usr/bin/spark-submit train.py' in run with ID '2ad8d348b4bd4cf59f16d3dc8eea9bf7' === 
Traceback (most recent call last):
  File "/tmp/tmpae63sriw/train.py", line 49, in <module>
    with mlflow.start_run():
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 116, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_id)
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/tracking/client.py", line 49, in get_run
    return self.store.get_run(run_id)
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 133, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 69, in _call_endpoint
    response = self._verify_rest_response(response, endpoint)
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/store/rest_store.py", line 52, in _verify_rest_response
    return verify_rest_response(response, endpoint)
  File "/usr/hdp/current/Anaconda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 84, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run '2ad8d348b4bd4cf59f16d3dc8eea9bf7' not found
19/08/07 05:13:46 INFO ShutdownHookManager: Shutdown hook called
19/08/07 05:13:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-c917b822-3cb8-469a-9b48-bd7d662fa2b4

**Comment by mateiz** [comment]
Thanks for the details. Did you set the MLflow tracking URI in the program where you called mlflow.run too? The mlflow.run command creates the run, then spawns a process (train.py in this case) that uses that run ID, so it needs to be using the same tracking server. This error message makes it seem that the run does not exist on the tracking server.

Basically, in your Python code before mlflow.run(), add mlflow.set_tracking_uri(your URI).

**Comment by ShevyMittal-GSLab** [comment]
Hi Mateiz,
Thanks a lot. That resolved the issue.
Another question, I want to run this code on the Spark Cluster, so can I use the "backend" for that purpose.? If so how? I do not have DataBricks, just a Spark Cluster

**Comment by mateiz** [comment]
Those backend parameters are for running the job in a completely different compute environment, but you don't need to use them for a locally accessible Spark cluster. Just make sure that the machine you are running your project on can access the Spark cluster -- or submit the driver program itself as a job on that cluster if you're using something like YARN. The connection to Spark happens gets set up in your project code, not in MLflow.

For multiple projects in the same Git repo, I'd recommend creating an MLproject file that lists different entry points. See examples/multistep_workflow/MLproject for an example.

**Comment by ShevyMittal-GSLab** [comment]
Thanks Mateiz.
It was very helpful.
I am facing another weird issue. I am unsure if it is related to mlflow or my Spark cluster
While using the projects run API:
I use the log_model API in my python code to log my model. However I get an error -java.lang.IllegalStateException(RPC channel is closed.)

It is strange since if I just run my code directly on the spark cluster without using the mlflow projects API, I do not get this error. Also the error is only while logging the model, I am able to log my parameters, metrix and other other artifacts.

Please let me know anything related to this

**Comment by mateiz** [comment]
It's really hard to tell without a full stack trace for your exception. You should probably report a different issue for that.

**Comment by carlos-rodrigo** [comment]
Hi! I have the same issue but I believe that is because I'm setting the tracking server URI inside the python code instead of the environment variable. 

I'm setup my MLproject to use docker,  and when I run the project using `mlflow run` command that excecute the docker run command passing MLFLOW_TRACKING_SERVER env variable using as value my local environment value. And then creates the run_id. But the run_id is generated using the MLFLOW_TRACKING_SERVER at the moment of the execution of the docker run command, not using the MLFLOW_TRACKING_SERVER that I setup inside my code. 

There is any way to pass the MLFLOW_TRACKING_SERVER to the docker run comment with setting it as a local environment value?

**Comment by y-tee** [comment]
Hi is there a way to specify how the spark job is run after being saved as a model, when i try to serve the model, it is choosing the wrong conda environment for each node. How do i specify the PYSPARK_PYTHON and DRIVER_PYSPARK_PYTHON during serving the saved model, or at saving the model itself?

This is the error i see:
```
19/11/29 18:10:58 ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
[2019-11-29 18:10:58 +0800] [28178] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/davidooi/.local/lib/python3.6/site-packages/mlflow/pyfunc/scoring_server/wsgi.py", line 6, in <module>
    app = scoring_server.init(load_model(os.environ[scoring_server._SERVER_MODEL_PATH]))
  File "/home/davidooi/.local/lib/python3.6/site-packages/mlflow/pyfunc/__init__.py", line 290, in load_model
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/home/davidooi/.local/lib/python3.6/site-packages/mlflow/spark.py", line 436, in _load_pyfunc
    return _PyFuncModelWrapper(spark, _load_model(model_uri=path))
  File "/home/davidooi/.local/lib/python3.6/site-packages/mlflow/spark.py", line 378, in _load_model
    return PipelineModel.load(model_path)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/ml/util.py", line 362, in load
    return cls.read().load(path)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/ml/pipeline.py", line 240, in load
    metadata = DefaultParamsReader.loadMetadata(path, self.sc)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/ml/util.py", line 558, in loadMetadata
    metadataStr = sc.textFile(metadataPath, 1).first()
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/rdd.py", line 1378, in first
    rs = self.take(1)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/rdd.py", line 1360, in take
    res = self.context.runJob(self, takeUpToNumLeft, p)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/context.py", line 1069, in runJob
    sock_info = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
  File "/home/davidooi/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/davidooi/.local/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/worker.py", line 267, in main
    ("%d.%d" % sys.version_info[:2], version))
Exception: Python in worker has different version 3.7 than that in driver 3.6, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:588)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:571)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
	at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1893)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1881)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1880)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1880)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2114)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2063)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2052)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:153)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/apps/ecm/service/spark/2.4.3-1.2.0/package/spark-2.4.3-1.2.0-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/worker.py", line 267, in main
    ("%d.%d" % sys.version_info[:2], version))
Exception: Python in worker has different version 3.7 than that in driver 3.6, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:588)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:571)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
	at org.apache.spark.api.python.PythonRDD$$anonfun$3.apply(PythonRDD.scala:153)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

[2019-11-29 18:10:58 +0800] [28178] [INFO] Worker exiting (pid: 28178)
[2019-11-29 18:10:58 +0800] [28169] [INFO] Shutting down: Master
[2019-11-29 18:10:58 +0800] [28169] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/home/davidooi/.conda/envs/mlflow/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/davidooi/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/davidooi/.conda/envs/mlflow/lib/python3.7/site-packages/mlflow/models/cli.py", line 56, in serve
    host=host)
  File "/home/davidooi/.conda/envs/mlflow/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 84, in serve
    command_env=command_env)
  File "/home/davidooi/.conda/envs/mlflow/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 164, in _execute_in_conda_env
    command, rc
Exception: Command 'source /opt/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-9ebeece9d3ad59af4a788f4ffa82db1db63f7d99 1>&2 && gunicorn --timeout=60 -b 127.0.0.1:5002 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 3
```

**Comment by pogil** [comment]
> Hi! I have the same issue but I believe that is because I'm setting the tracking server URI inside the python code instead of the environment variable.
> 
> I'm setup my MLproject to use docker, and when I run the project using `mlflow run` command that excecute the docker run command passing MLFLOW_TRACKING_SERVER env variable using as value my local environment value. And then creates the run_id. But the run_id is generated using the MLFLOW_TRACKING_SERVER at the moment of the execution of the docker run command, not using the MLFLOW_TRACKING_SERVER that I setup inside my code.
> 
> There is any way to pass the MLFLOW_TRACKING_SERVER to the docker run comment with setting it as a local environment value?

Hi @carlos-rodrigo, if you are still facing this issue, it would be better to create a new issue and spell out a bit more detail on how to reproduce the issue.

**Comment by pogil** [comment]
> Hi is there a way to specify how the spark job is run after being saved as a model, when i try to serve the model, it is choosing the wrong conda environment for each node. How do i specify the PYSPARK_PYTHON and DRIVER_PYSPARK_PYTHON during serving the saved model, or at saving the model itself?
> 


Hi @y-tee, if you are still facing this issue, would you please create a new issue with a bit more detail on the Spark environment you are running in and how the model was created?

**Comment by aayushisaxena2015** [comment]
Hi, i have registered a model and i'm able to log parameter/metrics details when the code is executed individually. But when i run the same code through pipeline, it doesn't log parameters and gives error "RestException: User does not have any permission level assigned to the registered model. "

Can somebody please help me on where I'm going wrong?
