### ISSUE TITLE
[BUG] Deploying spark model to azureml

### ISSUE THREAD

**Issue by Ben-Epstein** [mlflow/mlflow#1750]
Please do not delete this template unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux centos 7
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.7.0
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: full function listed above

### Describe the problem
When trying to deploy our pyspark model to azureml, we (myself and @abaveja313) encounter a bug where the JRE is not being installed and therefore not able to deploy the spark model.

### Code to reproduce issue
Code:
```
from azureml.core import Workspace
from azureml.core.webservice import AciWebservice, Webservice
from mlflow.azureml import build_image
from os import environ
workspace_name = "amrittest"
subscription_id = os.environ['SUBSCRIPTION_ID']
resource_group = "amrittest"
location = "East US"
azure_workspace = Workspace.create(name=workspace_name,
                                  subscription_id=subscription_id,
                                  resource_group=resource_group,
                                  location=location,
                                  create_resource_group=True,
                                  exist_ok=True)
azure_image, azure_model = build_image(model_uri="/tmp/model2",
                                                     workspace=azure_workspace,
                                                     description="Wine regression model 1",
                                                     synchronous=True)
print("Access the following URI for build logs: {}".format(azure_image.image_build_log_uri))
# Deploy the container image to ACI
webservice_deployment_config = AciWebservice.deploy_configuration()
webservice = Webservice.deploy_from_image(
                   image=azure_image, workspace=azure_workspace, name="amrittesttt")
webservice.wait_for_deployment()
```

### Other info / logs
Error on azureml container instance logs (where JAVA_HOME is not being set):
```
2019-08-16T16:43:37,939683552+00:00 - iot-server/run 
2019-08-16T16:43:37,940440658+00:00 - gunicorn/run 
2019-08-16T16:43:37,941200563+00:00 - rsyslog/run 
2019-08-16T16:43:38,137124526+00:00 - nginx/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2019-08-16T16:43:40,241560271+00:00 - iot-server/finish 1 0
2019-08-16T16:43:40,245790300+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.6.0
Listening at: http://127.0.0.1:31311 (11)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 43
Initializing logger
Starting up app insights client
Starting up request id generator
Starting up app insight hooks
Invoking user's init function
2019-08-16 16:44:36,744 | azureml.core.run | DEBUG | Could not load run context RunEnvironmentException:
    Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
    InnerException None
    ErrorResponse {"error": {"message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."}}, switching offline: False
2019-08-16 16:44:36,744 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
2019-08-16 16:44:36,744 | azureml.core.model | DEBUG | RunEnvironmentException: RunEnvironmentException:
    Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
    InnerException RunEnvironmentException:
    Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
    InnerException None
    ErrorResponse {"error": {"message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."}}
    ErrorResponse {"error": {"message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."}}
2019-08-16 16:44:36,745 | azureml.core.model | DEBUG | Using passed in version 1
2019-08-16 16:44:36,745 | azureml.core.model | DEBUG | Found model path at azureml-models/mlflow-y4ct2veitj6uszrg9sjjfq/1/model2
2019/08/16 16:44:36 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.7.3`, differs from the version of Python that is currently running, `Python 3.6.8`, and may be incompatible
JAVA_HOME is not set
User's init function failed
Encountered Exception Traceback (most recent call last):
  File "/var/azureml-server/aml_blueprint.py", line 162, in register
    main.init()
  File "/var/azureml-app/main.py", line 88, in init
    driver_module.init()
  File "execution_script.py", line 12, in init
    model = load_pyfunc(model_path)
  File "/opt/miniconda/lib/python3.6/site-packages/mlflow/pyfunc/__init__.py", line 314, in load_pyfunc
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/opt/miniconda/lib/python3.6/site-packages/mlflow/spark.py", line 383, in _load_pyfunc
    .master("local[1]").getOrCreate()
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/opt/miniconda/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
Worker exiting (pid: 43)
Shutting down: Master
Reason: Worker failed to boot.
2019-08-16T16:44:41,539825892+00:00 - gunicorn/finish 3 0
2019-08-16T16:44:41,541275102+00:00 - Exit code 3 is not normal. Killing image.
```

Error on our local logs:
```
 "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: amritest. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs.
```

Our proposed fix is to add:
`apt-get update && apt-get install default-jre` 
to the generated docker file inside mlflow.azureml._create_docker_file()

Local testing has shown that this solves the problem. We can create a PR as well.

**Comment by chayangujral** [comment]
Can someone help me understand how I should use"apt-get update && apt-get install default-jre" while creating docker image through mlflow.azureml,

**Comment by martinvt** [comment]
I have a similar issue...deploying spark models to azureml doesn't seem to work at all: 
`azure_image, azure_model = mlflow.azureml.build_image(model_uri='runs:/{}/{}'.format(runid, model_save_path),
                                                      workspace=ws,
                                                      model_name='mllib-model',
                                                      image_name='mllib-image',
                                                      synchronous=True)`

This hangs for me forever, in the azureml workspace it shows an experiment as "running"

**Comment by Ben-Epstein** [comment]
Closing because merged

**Comment by Ben-Epstein** [comment]
Closing because merged
