### ISSUE TITLE
[BUG] Deploying custom python models on azureml

### ISSUE THREAD

**Issue by cymonti** [mlflow/mlflow#1773]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 19.04)**:
- **MLflow installed from (source or binary)**: pip
- **MLflow version : 1.2.0
- **Python version**: 3.7.3

### Describe the problem
I am trying to deploy a custom python models on azureml. I built an image with mlflow command mlflow.azureml.build_image() and everything works well. However, when I try to deploy the image, I get the following errors (I used the example provided by mlflow : https://mlflow.org/docs/latest/python_api/mlflow.azureml.html).

```
2019-08-23T07:55:58,344543219+00:00 - gunicorn/run 
2019-08-23T07:55:58,349952130+00:00 - rsyslog/run 
2019-08-23T07:55:58,350110131+00:00 - iot-server/run 
2019-08-23T07:55:58,354993641+00:00 - nginx/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2019-08-23T07:55:58,587014416+00:00 - iot-server/finish 1 0
2019-08-23T07:55:58,591098524+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.6.0
Listening at: http://127.0.0.1:31311 (12)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 43
Initializing logger
Starting up app insights client
Starting up request id generator
Starting up app insight hooks
Invoking user's init function
2019-08-23 07:56:04,085 | azureml.core.run | DEBUG | Could not load run context RunEnvironmentException:
	Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."
    }
}, switching offline: False
2019-08-23 07:56:04,085 | azureml.core.run | DEBUG | Could not load the run context and allow_offline set to False
2019-08-23 07:56:04,085 | azureml.core.model | DEBUG | RunEnvironmentException: RunEnvironmentException:
	Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
	InnerException RunEnvironmentException:
	Message: Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."
    }
}
	ErrorResponse 
{
    "error": {
        "message": "Could not load a submitted run, if outside of an execution context, use experiment.start_logging to initialize an azureml.core.Run."
    }
}
2019-08-23 07:56:04,086 | azureml.core.model | DEBUG | Using passed in version 1
2019-08-23 07:56:04,086 | azureml.core.model | DEBUG | Found model path at azureml-models/mlflow-bzjxjqqwrzyxvt2xlpr7ow/1/ad_short_name_model
execution_script.py:12: DeprecationWarning: .. Warning:: ``mlflow.pyfunc.load_pyfunc`` is deprecated since 1.0. This method will be removed in a near future release. Use ``mlflow.pyfunc.load_model`` instead.
  model = load_pyfunc(model_path)
2019/08/23 07:56:04 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.7.3`, differs from the version of Python that is currently running, `Python 3.6.8`, and may be incompatible
XXX lineno: 44, opcode: 160
User's init function failed
/opt/miniconda/lib/python3.6/site-packages/plac_ext.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/opt/miniconda/lib/python3.6/site-packages/spacy/cli/converters/iob2json.py:24: DeprecationWarning: invalid escape sequence \w
  tokens = [re.split("[^\w\-]", line.strip())]
Encountered Exception Traceback (most recent call last):
  File "/var/azureml-server/aml_blueprint.py", line 162, in register
    main.init()
  File "/var/azureml-app/main.py", line 88, in init
    driver_module.init()
  File "execution_script.py", line 12, in init
    model = load_pyfunc(model_path)
  File "/opt/miniconda/lib/python3.6/site-packages/mlflow/utils/annotations.py", line 40, in deprecated_func
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.6/site-packages/mlflow/pyfunc/__init__.py", line 313, in load_pyfunc
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/opt/miniconda/lib/python3.6/site-packages/mlflow/pyfunc/model.py", line 223, in _load_pyfunc
    python_model.load_context(context=context)
  File "main.py", line 44, in load_context
    if run_supports_request_headers:
SystemError: unknown opcode

Worker exiting (pid: 43)
Shutting down: Master
Reason: Worker failed to boot.
2019-08-23T07:56:04,512021494+00:00 - gunicorn/finish 3 0
2019-08-23T07:56:04,513133796+00:00 - Exit code 3 is not normal. Killing image.
```

### Code to reproduce issue
```python
webservice = Webservice.deploy_from_image(image=azure_image,workspace=azure_workspace, name="<deployment-name>")
```

**Comment by dbczumar** [comment]
@cymonti Does your model define a custom `load_context` routine? If so, can you try deploying this locally with the `mlflow models serve` CLI and see if the problem persists in that environment? My hunch is that the model's `load_context` routine is the source of the issue, rather than the AzureML deployment process.

**Comment by cymonti** [comment]
@dbczumar Indeed, my model define a custom ```load_context```. I deployed my model locally with ```mlflow models serve``` and it works fine. I also tried to deploy the same model on aws sagemaker and I did not have problems.

**Comment by cymonti** [comment]
@dbczumar I changed my python version to 3.6 and I managed to deploy my model on azureml. Thank you for you help !

**Comment by JK87iab** [comment]
I am running into the same Issue using Databricks Runtime 6.1 ML (Uses Python 3.7)

switching to 5.5 ML works, but then I run into other issues. Is this an Mlflow or Azure issue?

Jonas

**Comment by joeltorby** [comment]
I had the same type of error when deploying my model to AzureML, got this messages which didn't tell me much:
"SystemError: unknown opcode" and "XXX lineno: 55, opcode: 160".

Thanks to this post, this problem was solved in the same way as earlier authors explain, by changing python version to 3.6 (from earlier 3.7) and re-run the model and saving the model.

In other words, these steps I did in anaconda prompt:
1. Create new 3.6-environment: `conda create -n <myenv>python=3.6 `
2. `conda activate <myenv>`
3. Install necessary libraries: `conda install pandas`, `pip install sklearn`, and so on.
4. If you use jupyter notebook you need to create a kernel for python 3.6: 
     `pip install ipykernel`
     `python -m ipykernel install --user --name=py_36`
5. `jupyter notebook`
6. Change kernel to py_36.
7. Run and save the model
