### ISSUE TITLE
[BUG] 'mlflow run' cannot find 'source' on Windows platform with defined env CONDA_EXE

### ISSUE THREAD

**Issue by artefom** [mlflow/mlflow#1786]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.7
- **Conda version**: 4.5.12
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

1. **MLproject i use**:
```
name: test
conda_env: env/test.yaml
entry_points:
  main:
    command: "echo 'Hello, world!'"
```
2. **Add CONDA_EXE to env**
3. **run**:
```bash
mlflow run . 
```

### Describe the problem

MLflow run fails with `"Running command 'source C:\Anaconda3\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-a0ccc40d6f0f515d16fcdead908287c92754d8fb 1>&2 && echo 'Hello, world!'' in run with ID '283707091aa0462f8c64d49ec0db2f31' ==="`

traceback:
```
Traceback (most recent call last):
  File "c:\anaconda3\envs\lenta\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\lenta\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\lenta\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\lenta\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda3\envs\lenta\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\anaconda3\envs\lenta\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda3\envs\lenta\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda3\envs\lenta\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda3\envs\lenta\lib\site-packages\mlflow\cli.py", line 137, in run
    run_id=run_id
  File "c:\anaconda3\envs\lenta\lib\site-packages\mlflow\projects\__init__.py", line 266, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "c:\anaconda3\envs\lenta\lib\site-packages\mlflow\projects\__init__.py", line 154, in _run
    run_id=active_run.info.run_id)
  File "c:\anaconda3\envs\lenta\lib\site-packages\mlflow\projects\__init__.py", line 556, in _run_entry_point
    process = subprocess.Popen(command, close_fds=True, cwd=work_dir, env=env)
  File "c:\anaconda3\envs\lenta\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\envs\lenta\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

*Clearly, it cannot find 'source' since i'm using Windows 10*

The root of the problem is in `mlflow/projects/__init__.py` (func: _get_conda_command)

```
def _get_conda_command(conda_env_name):
    #  Checking for newer conda versions
    if 'CONDA_EXE' in os.environ or 'MLFLOW_CONDA_HOME' in os.environ:
        conda_path = _get_conda_bin_executable("conda")

        activate_conda_env = ['source ' + os.path.dirname(conda_path) +
                              '/../etc/profile.d/conda.sh']
...
```

I have 'CONDA_EXE' environment variable and it branches into adding 'source' to command

to fix that, we need to check if os is 'nt' and proceed to adding 'sh' instead of 'source'

**Comment by artefom** [comment]
Clearly, replacing source with sh might not be a good idea, but the code below works perfectly for me

```
def _get_conda_command(conda_env_name):
    #  Checking for newer conda versions
    if 'CONDA_EXE' in os.environ or 'MLFLOW_CONDA_HOME' in os.environ:
        conda_path = _get_conda_bin_executable("conda")

        if os.name != "nt":
            activate_conda_env = ['source ' + os.path.dirname(conda_path) +
                                  '/../etc/profile.d/conda.sh']
        else:
            activate_conda_env = ['sh ' + os.path.dirname(conda_path) +
                      '/../etc/profile.d/conda.sh']
        activate_conda_env += ["conda activate {0} 1>&2".format(conda_env_name)]
    else:
        activate_path = _get_conda_bin_executable("activate")
        # in case os name is not 'nt', we are not running on windows. It introduces
        # bash command otherwise.
        if os.name != "nt":
            return ["source %s %s 1>&2" % (activate_path, conda_env_name)]
        else:
            return ["conda %s %s 1>&2" % (activate_path, conda_env_name)]
    return activate_conda_env
```

**Comment by Roffild** [comment]
```bat
set PYTHONHOME=
c:\Miniconda3\Scripts\conda.exe run -n pycharm mlflow ui
```
