### ISSUE TITLE
[BUG] models build-docker run not found 

### ISSUE THREAD

**Issue by latha-ai** [mlflow/mlflow#1957]
### System information
- using mlflow example 
mlflow\examples\sklearn_logistic_regression
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Error is same on both Windows 10 and Ubuntu
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.3.0
- **Python version**: Python 3.7.0
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
D:\__git\bda\mlflow\sklearn_logistic_regression where the models is saved.
set current working dir =  D:\__git\bda\mlflow\sklearn_logistic_regression
D:\__git\bda\mlflow\sklearn_logistic_regression>mlflow models build-docker -m "runs:/0/7989340d41e544d2a5e2167e54e19975/artifacts/model" -n "test-mlflow-image"

### Describe the problem
tried with -m args as /0/7989340d41e544d2a5e2167e54e19975/artifacts/model
/0/7989340d41e544d2a5e2167e54e19975/artifacts , /0/7989340d41e544d2a5e2167e54e19975 etc.
all of them have issues to find the run.

### Other info / logs
(mleap) D:\__git\bda\mlflow\sklearn_logistic_regression>mlflow models build-docker -m "runs:/0/7989340d41e544d2a5e2167e54e19975/artifacts/model" -n "test-mlflow-image"

_get_flavor_backend
runs:/0/7989340d41e544d2a5e2167e54e19975/artifacts/model = runs:/0/7989340d41e544d2a5e2167e54e19975/artifacts/model/MLmodel
parsed_uri = ParseResult(scheme='runs', netloc='', path='/0/7989340d41e544d2a5e2167e54e19975/artifacts/model/MLmodel', params='', query='', fragment='')
artifact_path = MLmodel
artifact_uri = runs:/0/7989340d41e544d2a5e2167e54e19975/artifacts/model repository = <class 'mlflow.store.runs_artifact_repo.RunsArtifactRepository'>
root_directory = file:///D:/__git/bda/mlflow/sklearn_logistic_regression/mlruns
self.root_directory = D:\__git\bda\mlflow\sklearn_logistic_regression\mlruns
self.root_directory = D:\__git\bda\mlflow\sklearn_logistic_regression\mlruns

['D:\\__git\\bda\\mlflow\\sklearn_logistic_regression\\mlruns\\0']
Traceback (most recent call last):
  File "d:\anaconda3\envs\mleap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\mleap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\mleap\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\mleap\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\models\cli.py", line 133, in build_docker
    _get_flavor_backend(model_uri, docker_build=True).build_image(model_uri, name,
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\models\cli.py", line 143, in _get_flavor_backend
    output_path=tmp.path())
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\tracking\artifact_utils.py", line 67, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\store\artifact_repository_registry.py", line 100, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\store\artifact_repository_registry.py", line 71, in get_artifact_repository
    return repository(artifact_uri)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\store\runs_artifact_repo.py", line 22, in __init__
    uri = get_artifact_uri(run_id, artifact_path)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\tracking\artifact_utils.py", line 37, in get_artifact_uri
    run = store.get_run(run_id)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\store\file_store.py", line 399, in get_run
    run_info = self._get_run_info(run_id)
  File "d:\anaconda3\envs\mleap\lib\site-packages\mlflow\store\file_store.py", line 415, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '0' not found in run_dir = 'None'

**Comment by pandae7** [comment]
Did you try giving the absolute path as an argument?
and Also check whether the mlruns/0/7989340d41e544d2a5e2167e54e19975/artifacts/model/ folder has MLmodel file

**Comment by latha-ai** [comment]
1. I tried all possible paths for runs options. Absolute path is not working. it has to start with /0, with and without MLModel.
I am saving the model using log_model here.

2. Changed to save_model
mlflow.sklearn.save_model(lr, 'D:\\tmp\\skmodels')    
# mlflow models build-docker --model-uri "file:D:\tmp\skmodels" -n "my-bda_mlflow-image"

ERROR:

mlflow models build-docker --model-uri "file:D:\tmp\skmodels" -n "my-bda_mlflow-image"
_get_flavor_backend
file:D:\tmp\skmodels = file:D:\tmp\skmodels/MLmodel
parsed_uri = ParseResult(scheme='', netloc='', path='D:\\tmp\\skmodels/MLmodel', params='', query='', fragment='')
artifact_path = MLmodel
artifact_uri = file:D:\tmp\skmodels repository = <class 'mlflow.store.local_artifact_repo.LocalArtifactRepository'>
2019/10/22 11:29:16 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
parsed_uri = ParseResult(scheme='', netloc='', path='D:\\tmp\\skmodels', params='', query='', fragment='')
artifact_path = D:\tmp\skmodels
artifact_uri = file: repository = <class 'mlflow.store.local_artifact_repo.LocalArtifactRepository'>
Traceback (most recent call last):
  File "d:\anaconda3\envs\mlflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\mlflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\anaconda3\envs\mlflow\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\models\cli.py", line 135, in build_docker
    install_mlflow=install_mlflow)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", line 122, in build_image
    entrypoint=pyfunc_entrypoint,
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\models\docker_utils.py", line 96, in _build_image
    custom_setup_steps = custom_setup_steps_hook(cwd) if custom_setup_steps_hook else ""
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", line 101, in copy_model_into_container
    model_path = _download_artifact_from_uri(model_uri, output_path=model_cwd)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\tracking\artifact_utils.py", line 68, in _download_artifact_from_uri
    artifact_path=artifact_path, dst_path=output_path)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\store\local_artifact_repo.py", line 60, in download_artifacts
    return super(LocalArtifactRepository, self).download_artifacts(artifact_path, dst_path)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\store\artifact_repo.py", line 113, in download_artifacts
    return download_artifacts_into(artifact_path, dst_path)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\store\artifact_repo.py", line 91, in download_artifacts_into
    download_artifacts_into(artifact_path=file_info.path, dest_dir=local_path)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\store\artifact_repo.py", line 93, in download_artifacts_into
    self._download_file(remote_file_path=artifact_path, local_path=local_path)
  File "d:\anaconda3\envs\mlflow\lib\site-packages\mlflow\store\local_artifact_repo.py", line 88, in _download_file
    shutil.copyfile(remote_file_path, local_path)
  File "d:\anaconda3\envs\mlflow\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '..\\..\\tmp\\skmodels\\MLmodel' and 'D:\\tmp\\skmodels\\MLmodel' are the same file

**Comment by latha-ai** [comment]
Too many issues in resolving the path and copying artifacts code.

Summary:
using windows posix path also does not resolve.

on ubuntu it works with full path - file for a built model.
mlflow models build-docker -m "file:/home/<user>/Share/skmodels/" -n "bda_mlflow-image"
