### ISSUE TITLE
[BUG] Calling get_artifact_uri() causes mlflow to get stuck at a run which cannot be killed

### ISSUE THREAD

**Issue by mirekphd** [mlflow/mlflow#1987]
I get a "Run with UUID < uuid >  is already active" error every time I call in the python script a seemingly innocuous read-only function `get_artifact_uri()` ("get*" functions are not supposed to alter anything...) - as a pure side effect of its being run. It breaks a python 3 code that worked previously for hundreds of runs and saved metrics for three different algos to a MariaDB database. I do not attempt to save any artifacts, just connect to the mlflow server and try to invoke `log_metric()` or `log_param()`. The MLflow web UI shows an empty table entry was created at this time, and a db query shows a new db record is being created for the current experiment.

Restarting python 3 kernel in the notebook (apart from commenting out the offending function call) is also required to get rid of the problem.

 Every time I restart `mlflow server` (entire container) I get a different UUID in the error message:
`Exception: Run with UUID 0c2471380c5949b4af7a18d0f1972f23 is already active. To start a nested run, call start_run with nested=True`

If I do not connect to the mlflow server (don't invoke `mlflow.set_tracking_uri(uri=tracking_server_url)`), then the error does not appear (but my results do not get stored in the db either).

Trying to kill the run with `mlflow.end_run(status="KILLED")` fails, and mlflow server reports the following error (keep scrolling:):

```
2019/10/24 14:53:34 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 158, in make_managed_session
    yield session
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 466, in update_run_info
    run = run.to_mlflow_entity()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/dbmodels/models.py", line 174, in to_mlflow_entity
    metrics=[m.to_mlflow_entity() for m in self.latest_metrics],
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 730, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 429, in __iter__
    self.session._autoflush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1588, in _autoflush
    util.raise_from_cause(e)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1577, in _autoflush
    self.flush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 238, in _update_run
    request_message.end_time)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 468, in update_run_info
    return run.info
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 165, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 105, in wrapper
    response.set_data(e.serialize_as_json())
  File "/opt/conda/lib/python3.6/site-packages/mlflow/exceptions.py", line 50, in serialize_as_json
    return json.dumps(exception_dict)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
2019/10/24 14:53:37 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 158, in make_managed_session
    yield session
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 466, in update_run_info
    run = run.to_mlflow_entity()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/dbmodels/models.py", line 174, in to_mlflow_entity
    metrics=[m.to_mlflow_entity() for m in self.latest_metrics],
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 730, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 429, in __iter__
    self.session._autoflush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1588, in _autoflush
    util.raise_from_cause(e)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1577, in _autoflush
    self.flush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 238, in _update_run
    request_message.end_time)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 468, in update_run_info
    return run.info
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 165, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 105, in wrapper
    response.set_data(e.serialize_as_json())
  File "/opt/conda/lib/python3.6/site-packages/mlflow/exceptions.py", line 50, in serialize_as_json
    return json.dumps(exception_dict)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable
2019/10/24 14:53:41 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 158, in make_managed_session
    yield session
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 466, in update_run_info
    run = run.to_mlflow_entity()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/dbmodels/models.py", line 174, in to_mlflow_entity
    metrics=[m.to_mlflow_entity() for m in self.latest_metrics],
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 730, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 429, in __iter__
    self.session._autoflush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1588, in _autoflush
    util.raise_from_cause(e)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1577, in _autoflush
    self.flush()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/conda/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 238, in _update_run
    request_message.end_time)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 468, in update_run_info
    return run.info
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/sqlalchemy_store.py", line 165, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.OperationalError) (4025, 'CONSTRAINT `status` failed for `mariadb`.`runs`')
[SQL: UPDATE runs SET status=%s, end_time=%s WHERE runs.run_uuid = %s]
[parameters: ('KILLED', 1571928814925, 'f6ba2d9431994eaa81cf28db67277387')]
(Background on this error at: http://sqlalche.me/e/e3q8 )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 105, in wrapper
    response.set_data(e.serialize_as_json())
  File "/opt/conda/lib/python3.6/site-packages/mlflow/exceptions.py", line 50, in serialize_as_json
    return json.dumps(exception_dict)
  File "/opt/conda/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OperationalError' is not JSON serializable

```

**Comment by smurching** [comment]
@mirekphd thanks for raising this, agree that this is confusing behavior - unfortunately, I'm not sure there's an easy way to  avoid creating an active run in `mlflow.get_artifact_uri` without a breaking API change, but we should keep this in mind for MLflow 2.0, although I'm open to ideas if you have any.

In the mean time, we should update the error message thrown by the MLflow Python API to provide some info on how to clear the active run, e.g. update [this line](https://github.com/mlflow/mlflow/blob/df980ea183cefcb71f3f8de23f40296bfbca136f/mlflow/tracking/fluent.py#L109) to indicate that users can also call `mlflow.end_run` to clear the current active run.

We should also update the doc for `get_artifact_uri` in [this file](https://github.com/mlflow/mlflow/blob/df980ea183cefcb71f3f8de23f40296bfbca136f/mlflow/tracking/fluent.py#L369) (and other fluent API methods) to explicitly state that an active run is created when the methods are called. 

I know this is probably not a super satisfactory response, but hopefully some of these doc changes will help reduce confusion until MLflow 2.0. Would you be interested in contributing any of them?

**Comment by andychow-db** [comment]
I've updated the documentation to reflect MLflow's behavior to let users know when an active run is generated (https://github.com/mlflow/mlflow/pull/2197)

**Comment by jwildner** [comment]
I had the same issue and found a simple workaround. I used the ```get_artifact_uri()``` function to save the path for later use. What I did is to create a run, end it after saving the uri and then starting the real run. It looks like this:
```
mlflow.set_tracking_uri(remote_server_uri)
mlflow.set_experiment("default")
artifact_uri = mlflow.get_artifact_uri()
mlflow.end_run()

with mlflow.start_run():
    mlflow.set_tracking_uri(remote_server_uri)
    mlflow.set_experiment("default")
    trainer.fit(model)
    mlflow.log_artifact("artifact.png", artifact_uri)
mlflow.end_run()
```

The downside is, that you always have an empty run in the mlflow ui and logs, but at least it is working. Please comment if you have a  more beautiful workaround.
