### ISSUE TITLE
[BUG] ValueError: Invalid Endpoint without '://' token in MLFLOW_S3_ENDPOINT_URL (client & server)

### ISSUE THREAD

**Issue by mirekphd** [mlflow/mlflow#1990]
Mlflow python client library (v1.3) and mlflow server (v1.3) both require that `MLFLOW_S3_ENDPOINT_URL `env var contain the "`://`" token (probably as in "`s3://`" in your typical Amazon scenario, but "`http://`" in my case as I use containerized minIO to emulate S3 buckets on premise).

So when setting the MLFLOW_S3_ENDPOINT_URL env var in python (using `os.environ()`) if I strip the "`://`" from the URL (for instance in order to use `minio` py library's function `fput_object()` for the same purpose as MLflow (to upload a binary file to an S3 bucket), I get `ValueError: Invalid endpoint  ml-minio-node1-shared.app.mycompany.mydomain` from botocore invoked by mlflow.

Similarly with the mlflow server - here if I inject to the container's environment the `MLFLOW_S3_ENDPOINT_URL` (through an Openshift's env) without the required "`://`", then when I navigate to any model (even those without any artifacts) details in the MLflow web UI, I get Niagara Falls photo in the browser and this error in mlflow server log:

```
2019/10/25 07:49:07 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 366, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 65, in list_artifacts
    s3_client = self._get_s3_client()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 29, in _get_s3_client
    return boto3.client('s3', endpoint_url=s3_endpoint_url)
  File "/opt/conda/lib/python3.6/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/conda/lib/python3.6/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/conda/lib/python3.6/site-packages/botocore/args.py", line 85, in get_client_args
    client_cert=new_config.client_cert)
  File "/opt/conda/lib/python3.6/site-packages/botocore/endpoint.py", line 261, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: ml-minio-node1-shared.app.mycompany.mydomain
```

With other apps I'd not test for this possibility, but with mlflow nothing seems impossible, however simple...:)

**Comment by dbczumar** [comment]
Hi @mirekphd - were you able to find a workaround for this issue? I suppose I'm not familiar enough with Minio to understand the need for passing an S3 endpoint URL without an `http://` prefix (which is required by boto). Given the age of this issue and the fact that this seems to be a limitation of S3's boto client, I'm going to go ahead and close it. Please let me know if this is causing a fundamental incompatibility between Minio and MLflow.

**Comment by MikBark** [comment]
Boto3 relies on `urllib.parse.urlsplit` to extract the hostname from a URL. If the URL does not include a scheme, `urlsplit` will not recognize the hostname. Prepending `http://` to the URL resolves this issue.

Example:
```python
from urllib.parse import urlsplit
print(urlsplit('some.host.com').hostname)  # Output: None
print(urlsplit('http://some.host.com').hostname)  # Output: some.host.com
```
