### ISSUE TITLE
[BUG] Model Registry problem with sklearn log method mlflow version 1.4.0 

### ISSUE THREAD

**Issue by echarso** [mlflow/mlflow#2037]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MAc OS Siera 10.12.6
- **MLflow installed from (source or binary)**: source via pip3 install 
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**:3.7.3

Hi all , 

I have launched the mlflow server -- host 0.0.0.0
 and in my python3 script I am  importing the followings and also loging the model at the end ::

import mlflow
import mlflow.sklearn
mlflow.set_tracking_uri('http://127.0.0.1:5000');

mlflow.sklearn.log_model(clf, "model_2")

In Mlflow UI everything looks OK but when I am going to register the model I get a server internal error notice.

In addition to that the server logs are the following:

2019/11/03 12:49:50 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 581, in _search_model_versions
    model_versions_detailed = _get_model_registry_store().search_model_versions(
AttributeError: 'NoneType' object has no attribute 'search_model_versions'

**Comment by harupy** [comment]
Duplicate of #1975

**Comment by harupy** [comment]
@echarso 
Model Registry does not support file-based stores.

https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L60

**Comment by echarso** [comment]
Thanks !
