### ISSUE TITLE
[BUG] can't register model in registry via code or UI

### ISSUE THREAD

**Issue by dr3s** [mlflow/mlflow#2047]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.7.3
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow server

### Describe the problem
model registry function not found when trying to register the model via the UI or log_model with a registered name

### Code to reproduce issue
```
mlflow server &
mlflow run .  
use the UI to register a model
```

### Other info / logs
```
2019/11/05 13:01:52 ERROR mlflow.server: Exception on /api/2.0/preview/mlflow/registered-models/create [POST]
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amarch/source/github/mlflow/mlflow/server/handlers.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/Users/amarch/source/github/mlflow/mlflow/server/handlers.py", line 455, in _create_registered_model
    registered_model = _get_model_registry_store().create_registered_model(request_message.name)
AttributeError: 'NoneType' object has no attribute 'create_registered_model'
[2019-11-05 13:01:55 -0500] [38819] [INFO] Handling signal: winch
^C[2019-11-05 13:02:13 -0500] [38819] [INFO] Handling signal: int
```

**Comment by harupy** [comment]
duplicate of #1975

**Comment by dr3s** [comment]
@harupy thanks, I didn't see that one.  I'm pretty sure that I also tried a sqlite db but I'll try again.

**Comment by abhishekmm** [comment]
Hi all,
I tried using  the  sqlite as well as MYSQL  on ubuntu system using following command :
mlflow server --backend-store-uri  sqlite:///mlruns.db --default-artifact-root gs://mflowdemo/ --host 0.0.0.0
yet I am not ablet register the model from mlflow UI
