### ISSUE TITLE
Bug with pyfunc serving int64

### ISSUE THREAD

**Issue by joshpeng** [mlflow/mlflow#208]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.3.0
- **Python version**: 3.6.3
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
When trying to serve via `mlflow pyfunc serve -m xxx`, the server comes online, but when passing in a curl command that would result in the function to output a pandas dataframe's numpy.int64 column, we run into this error:

```
Traceback (most recent call last):
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/site-packages/mlflow/pyfunc/scoring_server.py", line 67, in transformation
    result = json.dumps(predictions)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/josh/anaconda2/envs/py36/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
```

The reason for this is because Python 3 has issues with serializing numpy.int64 object type. An easy solution is as follows: https://stackoverflow.com/a/50577730/6467553

Create that helper function in `mlflow.utils` and then in pyfunc's `scoring_server.py` on line 67, the `json.dumps` line, we can just add the default parameter.

**Comment by aarondav** [comment]
Ah, good catch! Do you have time to make a quick PR? It seems like we should also add a unit test for this missing case.
