### ISSUE TITLE
[BUG] Could not find registered artifact repository / Run with UUID is already active

### ISSUE THREAD

**Issue by tbenst** [mlflow/mlflow#2093]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.14.0
- **Python version**: 
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
```
> mlflow server --backend-store-uri mysql://admin:pass@my-rds.amazonaws.com:3306/mlflow --default-artifact-root s3://mys3bucket/mlflow-artifacts/ --host 0.0.0.0 &
> export MLFLOW_TRACKING_URI="localhost:5000"
> mlflow run . -P alpha=0.5
2019/11/13 23:27:48 INFO mlflow.projects: === Created directory /tmp/tmp5zbr749r for downloading remote URIs passed to arguments of type 'path' ===
2019/11/13 23:27:48 INFO mlflow.projects: === Running command 'source /home/ubuntu/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac 1>&2 && python train.py 0.5 0.1' in run with ID '08e9146ed554414c8adfa4b7e99af732' === 
Elasticnet model (alpha=0.500000, l1_ratio=0.100000):
  RMSE: 0.7947931019036529
  MAE: 0.6189130834228138
  R2: 0.18411668718221819
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    mlflow.sklearn.log_model(lr, "model")
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/sklearn.py", line 200, in log_model
    registered_model_name=registered_model_name)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/models/__init__.py", line 82, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 303, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/client.py", line 260, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 257, in log_artifacts
    artifact_repo = get_artifact_repository(run.info.artifact_uri)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 102, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 68, in get_artifact_repository
    artifact_uri, list(self._registry.keys())
mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: localhost:5000/0/08e9146ed554414c8adfa4b7e99af732/artifacts. Currently registered schemes are: ['', 'file', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs', 'hdfs', 'viewfs', 'runs', 'models']
2019/11/13 23:27:49 ERROR mlflow.cli: === Run (ID '08e9146ed554414c8adfa4b7e99af732') failed ===
>
> mlflow run . -P alpha=0.5
2019/11/13 23:50:05 INFO mlflow.projects: === Created directory /tmp/tmpawe4lwat for downloading remote URIs passed to arguments of type 'path' ===
2019/11/13 23:50:05 INFO mlflow.projects: === Running command 'source /home/ubuntu/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac 1>&2 && python train.py 0.5 0.1' in run with ID '33410503b0274593b5b1a6edf5b4dc3c' === 
localhost:5000/0/33410503b0274593b5b1a6edf5b4dc3c/artifacts
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    with mlflow.start_run():
  File "/home/ubuntu/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 111, in start_run
    _active_run_stack[0].info.run_id))
Exception: Run with UUID 33410503b0274593b5b1a6edf5b4dc3c is already active. To start a nested run, call start_run with nested=True
2019/11/13 23:50:06 ERROR mlflow.cli: === Run (ID '33410503b0274593b5b1a6edf5b4dc3c') failed ===
```
### Describe the problem
I have two problems: 

1. `Could not find a registered artifact repository for [...]`
2. After repeated runs, now I get a new error, `Exception: Run with UUID [...] is already active`.

### Code to reproduce issue
See above

### Other info / logs
Thanks so much for any tips for troubleshooting!

**Comment by AdamBarnhard** [comment]
@tbenst - for some reason, it using your tracking server URI as the artifact location `localhost:5000/0/08e9146ed554414c8adfa4b7e99af732/artifacts` - that should be some type of file store. 

What happens when you run `mlflow experiments list`? What is that artifact location for `experiment_id = 0`? If it isn't properly showing your default artifact location, Id make a new experiment (which should pickup your default artifact location) and then make sure that the `start_run` within `train.py` references the correct experiment_id (which you can [set as a parameter](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run). With the new experiment and the model saving there, hopefully it will properly define the artifact location.

Not totally sure why the second error is happening, but your model is likely getting logged to the tracking server properly, just the artifacts aren't saving.

**Comment by tbenst** [comment]
ah thank you! The error was I should have `export MLFLOW_TRACKING_URI="http://localhost:5000"` (note the `http`)
