### ISSUE TITLE
[SETUP-BUG] mlflow db upgrade fails on first deploy

### ISSUE THREAD

**Issue by mbelang** [mlflow/mlflow#2113]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Stretch
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.6.8
- **Exact command to reproduce**: `mlflow db upgrade` (ran before the server is actually started)

### Describe the problem
I'm deploying mlflow tracking server on Kubernetes and I run the `mlflow db upgrade` in an init container i.e before the server is actually started. That procedure worked fine if the server has started at least once before.

So when I deploy mlflow for the first time (empty db), the migration fails because I suspect that it is the tracking server that setup the db on first deployment. Am I right? 

It would be nice if the DB would actually setup via the migration process or a separate command like `mlflow db init`. This command should be run multiple time without crashing. In other words it should be idempotent. As you can imagine the init-container will always be run before the server starts.

### Other info / logs
Here are the logs:

```
019/11/18 18:25:45 INFO mlflow.store.db.utils: Updating database tables at postgresql://dbadmin:wIZ4LFHfzxR96eOu04da@mlflow.c4ikfbyrjbf9.eu-central-1.rds.amazonaws.com:5432/mlflow in preparation for MLflow 1.0 schema migrations
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ff01da956556, ensure_unique_constraint_names
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "experiments" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mlflow/db.py", line 28, in upgrade
    mlflow.store.db.utils._upgrade_db_initialized_before_mlflow_1(url)
  File "/usr/local/lib/python3.6/site-packages/mlflow/store/db/utils.py", line 155, in _upgrade_db_initialized_before_mlflow_1
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 279, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 174, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 78, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 72, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 365, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.6/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py", line 174, in upgrade
    condition=column('lifecycle_stage').in_(["active", "deleted"])
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/batch.py", line 79, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 241, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "experiments" does not exist

[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by mbelang** [comment]
Still wanted :)

**Comment by mbelang** [comment]
Still wanted.

**Comment by Esadruhn** [comment]
I am interested too

**Comment by easokol** [comment]
> I am interested too

faced this problem too

**Comment by GlamTam** [comment]
would be great if this is fixed

**Comment by cmpgervais** [comment]
```python

from mlflow.store.db import utils

@commands.command()
@click.argument("url")
def init(url):
     engine = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(url)
     utils._initialize_tables(engine)
```
