### ISSUE TITLE
[BUG] Invalid experiment name: example. Expects a string.

### ISSUE THREAD

**Issue by tbenst** [mlflow/mlflow#2125]
### Describe the problem
I cannot get `mlflow run --experiment-name example` to work

### Code to reproduce issue
```
$ mlflow run --experiment-name="example" https://github.com/mlflow/mlflow-example  -P alpha=0.6 -P l1_ratio=0.1
INFO: 'example' does not exist. Creating a new experiment
Traceback (most recent call last):
  File "/home/tyler/.conda/envs/py2/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/cli.py", line 134, in run
    run_id=run_id
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/projects/__init__.py", line 280, in run
    experiment_id=experiment_id)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/projects/__init__.py", line 90, in _resolve_experiment_id
    return client.create_experiment(experiment_name)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/tracking/client.py", line 157, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 122, in create_experiment
    _validate_experiment_name(name)
  File "/home/tyler/.conda/envs/py2/lib/python2.7/site-packages/mlflow/utils/validation.py", line 201, in _validate_experiment_name
    error_code=INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: Invalid experiment name: example. Expects a string.
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

**Comment by tbenst** [comment]
Looks like a problem specific to python2. Works fine in python3
