### ISSUE TITLE
ConnectionReset Error [BUG]

### ISSUE THREAD

**Issue by gbmarc1** [mlflow/mlflow#2153]
I have this issue when I have a project with a docker Image:

```
Building docker image Employee Experience Categorisation:d9f321a ===
```

```
Traceback (most recent call last):
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen  chunked=chunked,
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_requestconn.request(method, url, **httplib_request_kw)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1252, in request  self._send_request(method, url, body, headers, encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1298, in _send_requestself.endheaders(body, encode_chunked=encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1247, in endheaders   self._send_output(message_body, encode_chunked=encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1065, in _send_output self.send(chunk)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 987, in send  self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/requests/adapters.py", line 449, in send  timeout=timeout
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen  method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in incrementraise six.reraise(type(error), error, _stacktrace)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraiseraise value.with_traceback(tb)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen  chunked=chunked,
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_requestconn.request(method, url, **httplib_request_kw)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1252, in request  self._send_request(method, url, body, headers, encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1298, in _send_requestself.endheaders(body, encode_chunked=encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1247, in endheaders   self._send_output(message_body, encode_chunked=encode_chunked)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 1065, in _send_output self.send(chunk)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/http/client.py", line 987, in send  self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/workspace/marc/miniconda3/envs/mlflow/bin/mlflow", line 8, in <module>  sys.exit(cli())
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/click/core.py", line 1137, in invoke  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/click/core.py", line 956, in invoke   return ctx.invoke(self.callback, **ctx.params)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/click/core.py", line 555, in invoke   return callback(*args, **kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/mlflow/cli.py", line 134, in run  run_id=run_id
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 285, in runuse_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)  File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 154, in _run   run_id=active_run.info.run_id)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 818, in _build_docker_imagefileobj=docker_build_ctx, custom_context=True, encoding="gzip")
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/docker/models/images.py", line 279, in build  resp = self.client.api.build(**kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/docker/api/build.py", line 269, in build  timeout=timeout,
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in innerreturn f(self, *args, **kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/docker/api/client.py", line 226, in _post return self.post(url, **self._set_request_timeout(kwargs))
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/requests/sessions.py", line 581, in post  return self.request('POST', url, data=data, json=json, **kwargs)   File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/requests/sessions.py", line 533, in request   resp = self.send(prep, **send_kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/requests/sessions.py", line 646, in send  r = adapter.send(request, **kwargs)
 File "/workspace/marc/miniconda3/envs/mlflow/lib/python3.7/site-packages/requests/adapters.py", line 498, in send  raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

My docker image is correctly built on my system. Is it because it does not find it on the machine and tries to find it somehwere else?

My MLproject file:
```yaml

name: Employee Experience Categorisation

docker_env:
  image: mlflow-docker

entry_points:
  train:
    parameters:
      data_file: path
      regularization: {type: float, default: 0.1}
    command: "python src/train.py -r {regularization} {data_file}"
  encode:
    parameters:
      save_path: path
      threshold: {type: int, default: 100}
    command: "python src/label_encoder.py --save_path {save_path} --map {map} --threshold {threshold} --log"

```
docker images mlflow-docker

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mlflow-docker       latest              245f9ddbbb75        45 minutes ago      4.47GB
```

Any idea?

**Comment by ksanjeevan** [comment]
@gbmarc1 having the same issue, did you ever solve this?

**Comment by ksanjeevan** [comment]
If anyone else is having this issue, I just solved it... Project name has to be all lowercase. I tried reproducing this error but when I try to I get the correct `Internal Server Error ("invalid reference format: repository name must be lowercase")`. But changing it in my project fixed the `ConnectionReset Error`. Hope it helps :)

**Comment by pogil** [comment]
It seems like a good improvement here would be to check for capitalization in project names prior to invoking docker and either 

- failing but providing a meaningful error message, such as "To use Docker with projects, you must use lowercase letters in the project name.", or 
- thinking through how the project names when interacting with the Docker components and whether it's safe to downcase the names automatically (could this cause a conflict if two projects have the same name but different capitalization - or is this already an issue and therefore wouldn't cause a regression) or do some other safe, but interpretable/debuggable behavior with how projects work with Docker. Fixing in this way should have a small amount of design and discussion prior to starting engineering.
