### ISSUE TITLE
MLflow models serve missing some dependencies

### ISSUE THREAD

**Issue by vikey725** [mlflow/mlflow#2154]
[2019-12-02 13:10:11 +0530] [23184] [INFO] Starting gunicorn 20.0.4
[2019-12-02 13:10:11 +0530] [23184] [INFO] Listening at: http://127.0.0.1:9999 (23184)
[2019-12-02 13:10:11 +0530] [23184] [INFO] Using worker: sync
[2019-12-02 13:10:11 +0530] [23193] [INFO] Booting worker with pid: 23193
[2019-12-02 13:10:11 +0530] [23193] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/mlflow/pyfunc/scoring_server/wsgi.py", line 6, in <module>
    app = scoring_server.init(load_model(os.environ[scoring_server._SERVER_MODEL_PATH]))
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 290, in load_model
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/mlflow/sklearn.py", line 219, in _load_pyfunc
    return _load_model_from_local_file(path)
  File "/home/vikash/anaconda3/envs/mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9/lib/python3.7/site-packages/mlflow/sklearn.py", line 210, in _load_model_from_local_file
    return pickle.load(f)
ModuleNotFoundError: **No module named 'sklearn_crfsuite'**
[2019-12-02 13:10:11 +0530] [23193] [INFO] Worker exiting (pid: 23193)
[2019-12-02 13:10:11 +0530] [23184] [INFO] Shutting down: Master
[2019-12-02 13:10:11 +0530] [23184] [INFO] Reason: **Worker failed to boot.**
Traceback (most recent call last):
  File "/home/vikash/anaconda3/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/mlflow/models/cli.py", line 56, in serve
    host=host)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 77, in serve
    command_env=command_env)
  File "/home/vikash/anaconda3/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 146, in _execute_in_conda_env
    command, rc
Exception: Command 'source /home/vikash/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-a9d9016cece6d46ef9f3e1cad06f59a5ea72ceb9 1>&2 && gunicorn --timeout 60 -b 127.0.0.1:9999 -w 1 mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 3

While saving the model, its not including sklearn_crfsuite in **yaml** file.

**Comment by tomasatdatabricks** [comment]
Hi @vikey725, thanks for posting!

The log_model function only logs default conda environment, if you have any extra dependencies you need to provide your own. E.g. in your case, you can do:

`
from mlflow.utils.environment import _mlflow_conda_env

def my_conda_env(include_cloudpickle=False):
    """
    :return: The default Conda environment for MLflow Models produced by calls to
             :func:`save_model()` and :func:`log_model()`.
    """
    import sklearn
    pip_deps = ["sklearn_crfsuite"]
    if include_cloudpickle:
        import cloudpickle
        pip_deps.append("cloudpickle=={}".format(cloudpickle.__version__))
    return _mlflow_conda_env(
        additional_conda_deps=[
            "scikit-learn={}".format(sklearn.__version__),
        ],
        additional_pip_deps=pip_deps,
        additional_conda_channels=None
    )
mlflow.sklearn.log_model(..., conda_env=my_conda_env())
`

**Comment by vikey725** [comment]
@tomasatdatabricks  Thanks a lot :)

**Comment by vrobinho** [comment]
Thanks for this post! It helped me to solve a similar issue with fasttext. 

I initially followed the xgb_boost example from the documentation (https://www.mlflow.org/docs/latest/models.html#example-saving-an-xgboost-model-in-mlflow-format), but to no avail.

Does it mean that the xgb_boost example should be fixed in the documentation?

**Comment by tomasatdatabricks** [comment]
Hi @vrobinho, yes it does look like the conda environment in the example does not work. It should install xgboost and cloudpickle from pip. Thanks for pointing it out!
