### ISSUE TITLE
Unable to download nested directory using GCSArtifactRepository

### ISSUE THREAD

**Issue by arinto** [mlflow/mlflow#219]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sierra 10.12.6 
- **MLflow installed from (source or binary)**: source, from commit fd361266122e5fe831f982601de1a0a8b85f6b62
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.3.0
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **npm version (if running the dev UI)**: N.A
- **Exact command to reproduce**:

1. Run Tensorflow training, and log the model using `mlflow.tensorflow.log_saved_model`, and here's the model structure in my GCS:
```
(rr-minist-tf) ip-10-10-180-19:src arinto$ gsutil ls -r  gs://arinto-dev/0
gs://arinto-dev/0/:

gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/:

gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/:

gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/:
gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/MLmodel
gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/saved_model.pb

gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/variables/:
gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/variables/variables.data-00000-of-00001
gs://arinto-dev/0/a0467cfc4a904ad894cb4793dde73605/artifacts/model/variables/variables.index
```

2. Then I want to serve the saved model using this command, but it fails. Error logs in the Source code/logs
`mlflow pyfunc serve -m model -r a0467cfc4a904ad894cb4793dde73605 -p 5001`

### Describe the problem
It seems that mlflow can't download the `variables` folder properly. I suspect there could be bugs in `GCSArtifactRepository` i.e it works fine for model without nested directory like sklearn, but not for Tensorflow (which has nested directory).  I haven't had chance to deep dive yet, and for now I'll raise this issue. 

### Source code / logs
```
Traceback (most recent call last):
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/bin/mlflow", line 11, in <module>
    load_entry_point('mlflow', 'console_scripts', 'mlflow')()
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/arinto/anaconda3/envs/rr-minist-tf/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Volumes/tvlk-repo/github/mlflow/mlflow/pyfunc/cli.py", line 31, in serve
    model_path = _get_model_log_dir(model_path, run_id)
  File "/Volumes/tvlk-repo/github/mlflow/mlflow/tracking/__init__.py", line 345, in _get_model_log_dir
    return artifact_repo.download_artifacts(model_name)
  File "/Volumes/tvlk-repo/github/mlflow/mlflow/store/artifact_repo.py", line 270, in download_artifacts
    return self._download_artifacts_into(artifact_path, tmp.path())
  File "/Volumes/tvlk-repo/github/mlflow/mlflow/store/artifact_repo.py", line 281, in _download_artifacts_into
    self._download_artifacts_into(file_info.path, local_path)
  File "/Volumes/tvlk-repo/github/mlflow/mlflow/store/artifact_repo.py", line 286, in _download_artifacts_into
    gcs_bucket.get_blob(remote_path).download_to_filename(local_path)
AttributeError: 'NoneType' object has no attribute 'download_to_filename'.
```

**Comment by jakeret** [comment]
@aarondav I can have a look

**Comment by jakeret** [comment]
I've sent a PR that fixes this issue

**Comment by arinto** [comment]
Cool, thanks! Closing this issue :)
