### ISSUE TITLE
[FR] Log conda environment creation log

### ISSUE THREAD

**Issue by Tradunsky** [mlflow/mlflow#2264]
## Describe the proposal
On `mlflow run` env creation can fail due to any errors in packages. There is no visability on what exactly happened, only following useless stacktrace:
`Collecting package metadata (repodata.json): ...working... Traceback (most recent call last):
  File "/opt/conda/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/cli.py", line 139, in run
    run_id=run_id,
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 230, in run
    storage_dir=storage_dir, block=block, run_id=run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 132, in _run
    conda_env_name = _get_or_create_conda_env(project.conda_env_path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 462, in _get_or_create_conda_env
    conda_env_path], stream_output=True)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/process.py", line 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: -9
`

### Motivation
Visibility on failures of mlflow run command 

### Proposed Changes
First and most important - rename that stream_output variable, because it is misleading.
Second - stream logs to log file (up to you, can be either separate log file or stderr) https://github.com/mlflow/mlflow/blob/cb07e3b4717075fd0d572a79c77ad9d85ea07f7b/mlflow/projects/__init__.py#L450

**Comment by Tradunsky** [comment]
Suddenly, logging of error didn't help, it logs empty lines. Conda via mlflow definitely has a lack in visibility.

**Comment by smurching** [comment]
@Tradunsky apologies for the delay, would you be able to provide more details around how to reproduce this issue? Does seem like it'd be good for us to ensure conda-env-creation logs are visible. At least on my Mac & MLflow 1.9.1, I can in fact see the output of `conda env create` while running a project

**Comment by Tradunsky** [comment]
@smurching since our users use pip inside conda.yaml, these errors not directly related to conda env creation, but pip used inside it. Apparently, conda does a poor job integrating pip environments also - in contrast to conda environment creation, pip is not running in transaction. 

Since long time passed, I cannot come up with exact code or steps to stably reproduce the issue. However, the simplest way to see that pip is not enough exposed to conda, thus to mlflow, is to have some native dependent package installing via pip in conda.yaml on env without gcc.

**Comment by chenmoneygithub** [comment]
I am closing this issue due to lacking steady reproducible code.
