### ISSUE TITLE
[BUG] Cannot create Mllfow tracking Server Database on Linux - Ubuntu 16.04 Error: (1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by SaadEphlux** [mlflow/mlflow#2381]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**: latest 1.6
- **Python version**:3.7
- **npm version, if running the dev UI**:-
- **Exact command to reproduce**: `mlflow.log_metric("dummy_metric", 12)`

### Describe the problem
Hey guys I am facing difficulty in creating a database tables using mlflow.  So I was doing my development on windows where I had no issues with the Database. The issue occurred when I **shifted** to **Linux** and installed **MariaDB** directly from the command line where as in windows I was using Xammp and the **MariaDB** version in that was **10.1.39**. On my Ubuntu VM the MariaDB version is 10.0.38 and I suspect this is the reason for the problem however I dont want to install a newer version on my Linux system at this time. Any help would be appreciated. 

### Code to reproduce issue
1- open MariaDB terminal and create a new Database:  `CREATE DATABASE mlflow`
2- Open python terminal
3- `import mlflow`
4- `mlflow.set_tracking_uri("mysql+pymysql://root@localhost/mlflow")`
5- `mlflow.log_metric("dummy_metric",12)`
### Error Logs
`020/02/03 17:54:13 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
Traceback (most recent call last):
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 251, in log_metric
    run_id = _get_or_start_run().info.run_id
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 506, in _get_or_start_run
    return start_run()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 151, in start_run
    active_run_obj = MlflowClient().create_run(
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/client.py", line 37, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 31, in __init__
    self.store = utils._get_store(self.tracking_uri)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/utils.py", line 114, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/registry.py", line 37, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/utils.py", line 78, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 97, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 29, in _initialize_tables
    InitialBase.metadata.create_all(engine)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2049, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1618, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/saad/miniconda3/envs/pxml/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1071, 'Specified key was too long; max key length is 767 bytes')
[SQL: 
CREATE TABLE experiments (
        experiment_id INTEGER NOT NULL AUTO_INCREMENT, 
        name VARCHAR(256) NOT NULL, 
        artifact_location VARCHAR(256), 
        lifecycle_stage VARCHAR(32), 
        CONSTRAINT experiment_pk PRIMARY KEY (experiment_id), 
        CONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), 
        UNIQUE (name)
)

]
(Background on this error at: http://sqlalche.me/e/2j85)

**Comment by tallen94** [comment]
I thought the tracking uri had to be the url to the MLFlow Tracking Server https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri 

It looks like you are using a database connection string as the tracking uri
```
mlflow.set_tracking_uri("mysql+pymysql://root@localhost/mlflow")
```

Are you running the [Tracking Server](https://www.mlflow.org/docs/latest/tracking.html)? That is where you input the database string when you start the server, I think.

```
mlflow server \
    --backend-store-uri mysql+pymysql://root@localhost/mlflow  \
    --default-artifact-root s3://bucket/artifacts \
    --host 0.0.0.0 \
    --port 5000
```

This runs on something like localhost:5000 and then you set the tracking uri to that address
```
mlflow.set_tracking_uri("http://localhost:5000")
```

**Comment by SaadEphlux** [comment]
Hey Thank you for the response but I have been  setting the tracking uri like that for months infact I never had the problem on even Linux when using XAMPP as a webserver. The problem only occurs when I installed just MariaDB using this guide [here](https://www.scaleway.com/en/docs/how-to-install-mariadb-on-ubuntu/).  Also the documentation here also suggests that we can specify the database URI like I have done. You can read it [here](https://www.mlflow.org/docs/latest/tracking.html#where-runs-are-recorded)

**Comment by tallen94** [comment]
Ahhhh, my mistake. I was reading some different documentation that didn't mention the use of database strings.

**Comment by SaadEphlux** [comment]
@smurching any suggestions?

**Comment by dbczumar** [comment]
@SaadEphlux We're investigating! Thanks for raising this issue.

**Comment by SaadEphlux** [comment]
Thanks for the response. I am not very good with databases but after a few Google searches I suspect the issue is with the length of VARCHAR i think it can't be more than 255 where as its specified as 256.

**Comment by dbczumar** [comment]
@SaadEphlux Got it! I'll take a look at the data type / length and see if we can make some modifications.

**Comment by SaadEphlux** [comment]
@dbczumar  hey any updates when this will get fixed?

**Comment by dbczumar** [comment]
Hi @SaadEphlux. I've investigated the issue, and it appears that the problem is specific to older versions of MySQL that are leveraging the InnoDB engine, which imposes a maximum index/key length of 767 bytes. The current MLflow `runs` table configuration defines a unique key constraint on `name`, which is a length-255 varchar column. Depending on the character set used for the InnoDB table, the length of each character may be several bytes (e.g., if you're using `utf16` or `utf8mb4`). 

This article describes the problem and recommends changing the character set to a representation that uses less space per character: https://wildlyinaccurate.com/mysql-specified-key-was-too-long-max-key-length-is-767-bytes/

Further, this StackOverflow post provides a MariaDB + InnoDB configuration that may enable you to raise/bypass these limits: https://dba.stackexchange.com/a/231234.

Can you explore these solutions and let me know if you're unable to make progress? We'd rather not reduce the size of an existing column in a backwards-incompatible way if it can be avoided.

**Comment by gudata** [comment]
I have the same error while using the was RDS aurora server.

**Comment by NarekA** [comment]
I made the [following branch](https://github.com/NarekA/mlflow/commit/8b6eba8da8acefd4867af190c48ace54171eb02b) to work around this issue. I run the server for the first time with that forked version and it initializes the DB with all the `VARCHAR(255)` fields as `VARCHAR(250)`. After that, I am able to run the current latest release and no longer need the fork.
