### ISSUE TITLE
[BUG] pyfunc.log_model fails for large .pkl files (PythonModel)

### ISSUE THREAD

**Issue by rrma** [mlflow/mlflow#2401]
### System information
- OS: tested on Linux & MaxOS 
- mlflow v1.6.0
- python 3.7.6

### Describe the problem
I want to log a SARIMAX model to a S3 bucket (artifact store) with mlflow. This works as long as the model (.pkl) file is small, but as soon as it reaches a larger size (because endog contains more values), the model upload fails.
It looks like the splitting the model file into multiple parts, due to file size, is the problem.

FYI - 
I found a similar problem in the issues of the moto package. There, it is stated that the issue could be solved in the TransferConfig of the boto3 client by setting use_treads=False (default value is True). => https://github.com/spulec/moto/issues/786
Maybe this could also be solved by that...

### Code to reproduce issue
Set environment variables

- MLFLOW_S3_ENDPOINT_URL
- MLFLOW_TRACKING_URI

```
import mlflow
import numpy as np

from mlflow.pyfunc import PythonModel
from statsmodels.tsa.statespace.sarimax import SARIMAX

class PythonModelWrapper(PythonModel):

    def __init__(self, model):
        self.model = model

    def predict(self, context, model_input):
        return self.model.predict(model_input)


y_train = np.random.randint(0, 1000, 8000)

model = SARIMAX(endog=y_train, order=(1, 1, 1), frequ='T').fit()

wrapper = PythonModelWrapper(model)
mlflow.pyfunc.log_model('model', python_model=wrapper)

```
### Other info / logs
```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File ".../lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File ".../lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File ".../lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File ".../lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File ".../lib/python3.7/site-packages/s3transfer/tasks.py", line 364, in _main
    **extra_args)
  File ".../lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: Unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../code/log_sarimax.py", line 22, in <module>
    mlflow.pyfunc.log_model('model', python_model=wrapper)
  File ".../lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 686, in log_model
    registered_model_name=registered_model_name)
  File ".../lib/python3.7/site-packages/mlflow/models/__init__.py", line 83, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File ".../lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 323, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File ".../lib/python3.7/site-packages/mlflow/tracking/client.py", line 260, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File ".../lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 259, in log_artifacts
    artifact_repo.log_artifacts(local_dir, artifact_path)
  File ".../lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 56, in log_artifacts
    posixpath.join(upload_path, f), Config=TransferConfig(use_threads=False))
  File ".../lib/python3.7/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File ".../lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /var/folders/m2/fx5640rj3xz5d0src7pqdqmwh9vmmr/T/tmpsa38v5w_/model/python_model.pkl to .../artifacts/model/python_model.pkl: An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: Unknown
```

**Comment by dbczumar** [comment]
@rrma thanks for raising this. Can you try the fix from Moto and let me know if it works? If so, we can probably proceed with merging that fix into the MLflow repo.

**Comment by rrma** [comment]
I tried it with setting `TransferConfig(use_threads=False)` but it did not solve the problem, unfortunately.

**Comment by shdowofdeath** [comment]
any update on this issue ?

**Comment by tomasatdatabricks** [comment]
Hi @rrma, sorry for dropping this. Have you resolved you issue in the meantime? I am not sure if this is an mlflow issue as it seems that the problem is in boto client itself. Can you verify if you can generate the pickle file yourself and upload it to s3 using boto client directly?

**Comment by rrma** [comment]
hi @tomasatdatabricks 
sorry for getting back to you so late. I was able to resolve the issue by increasing the upload limit (no clean code yet). But I am not sure if this is the best solution for this problem. I plan to clean the code and then add a PR

**Comment by tomasatdatabricks** [comment]
Ok, thanks for the update. PR would be appreciated!

**Comment by rrma** [comment]
Hi @tomasatdatabricks,

I wanted to start working on a fix today but it looks like in the meantime it was fixed through another change.
So, I'll close the ticket 😄
