### ISSUE TITLE
mlflow seems to assume the main is run through sys.argv[1], fails when python commands are run.

### ISSUE THREAD

**Issue by yogeshg** [mlflow/mlflow#241]
### System information
- **MLflow version (run ``mlflow --version``)**: 0.4.1

### Describe the problem
run the command, see the issue :)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
$ python -c "import mlflow; mlflow.log_param('wd', 'c')"

/Users/yo/.venvs/dev3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 335, in log_param
    _get_or_start_run().log_param(Param(key, str(value)))
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 308, in _get_or_start_run
    return start_run()
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 298, in start_run
    source_version=source_version or _get_source_version(),
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 215, in _get_source_version
    return _get_git_commit(main_file)
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 402, in _get_git_commit
    repo = Repo(path, search_parent_directories=True)
  File "/Users/yo/.venvs/dev3/lib/python3.6/site-packages/git/repo/base.py", line 131, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/yo/code/spark-deep-learning-private/dlami_scripts/-c

```

**Comment by aarondav** [comment]
Thanks for the report. I created #243 to fix this problem once and for all.

**Comment by aarondav** [comment]
Fix merged.
