### ISSUE TITLE
[BUG] log_param with multiple lines in the param causes failures later

### ISSUE THREAD

**Issue by SudoMike** [mlflow/mlflow#2416]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
NO

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04, running inside Docker

- **MLflow installed from (source or binary)**:
pip install mlflow==1.5.0

- **MLflow version (run ``mlflow --version``)**:
1.5.0

- **Python version**:
3.6.9

- **npm version, if running the dev UI**:

- **Exact command to reproduce**:
mlflow.log_param("whatever", "line 1 \n line 2")

### Describe the problem
I ran into this to by logging my git commit messages as params. If the commit message has more than one line, then log_param will accept it, but the server will cryptically fail later in file_store.py:_get_param_from_file because param_data has more than 1 line in it.

### Code to reproduce issue
mlflow.log_param("whatever", "line 1 \n line 2")

### Other info / logs
```
2020/02/11 00:11:35 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app             
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)                        
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise               
    raise value                                               
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request                
    rv = self.dispatch_request()                    
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request                  
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/server/handlers.py", line 137, in wrapper            
    return func(*args, **kwargs)                          
  File "/usr/local/lib/python3.6/dist-packages/mlflow/server/handlers.py", line 375, in _search_runs     
    max_results, order_by, page_token)                                                
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/abstract_store.py", line 229, in search_runs
    order_by, page_token)                                            
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/file_store.py", line 589, in _search_runs        
    runs.extend(self.get_run(r.run_id) for r in run_infos)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/file_store.py", line 589, in <genexpr>
    runs.extend(self.get_run(r.run_id) for r in run_infos)                                           
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/file_store.py", line 401, in get_run
    params = self.get_all_params(run_id)                                            
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/file_store.py", line 524, in get_all_params
    params.append(self._get_param_from_file(parent_path, param_file))                            
  File "/usr/local/lib/python3.6/dist-packages/mlflow/store/tracking/file_store.py", line 514, in _get_param_from_file
    % param_name)                                                                                
Exception: Unexpected data for param 'CI_COMMIT_MESSAGE'. Param recorded more than once
```
This seems worth fixing in 2 places: The docs for log_param should mention that newlines can't be in the value, and log_param itself should raise an exception if it's given a value with newlines.

**Comment by dbczumar** [comment]
@SudoMike This has been fixed in `master` via #2376. Please feel free to reopen this issue if that change doesn't help.
