### ISSUE TITLE
mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 3

### ISSUE THREAD

**Issue by ukab23** [mlflow/mlflow#2437]
**This error occurred while I was trying to serve the onnx model after registering it using PostgreSQL. This works in the case of a sklearn model though.**
/home/akash/.local/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Enter name for your model:new
2020/02/18 18:09:56 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2020/02/18 18:10:01 INFO mlflow.pyfunc.backend: === Running command 'source /home/akash/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-960bcb7a9eb015edaeb250062ae29e2f4403f944 1>&2 && gunicorn --timeout=60 -b 127.0.0.1:6050 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
[2020-02-18 18:10:01 +0530] [8031] [INFO] Starting gunicorn 20.0.4
[2020-02-18 18:10:01 +0530] [8031] [INFO] Listening at: http://127.0.0.1:6050 (8031)
[2020-02-18 18:10:01 +0530] [8031] [INFO] Using worker: sync
[2020-02-18 18:10:01 +0530] [8037] [INFO] Booting worker with pid: 8037
[2020-02-18 18:10:02 +0530] [8037] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/akash/.local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/pyfunc/scoring_server/wsgi.py", line 6, in <module>
    app = scoring_server.init(load_model(os.environ[scoring_server._SERVER_MODEL_PATH]))
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 292, in load_model
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/sklearn.py", line 219, in _load_pyfunc
    return _load_model_from_local_file(path)
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/sklearn.py", line 210, in _load_model_from_local_file
    return pickle.load(f)
ModuleNotFoundError: No module named 'onnx'
[2020-02-18 18:10:02 +0530] [8037] [INFO] Worker exiting (pid: 8037)
[2020-02-18 18:10:02 +0530] [8031] [INFO] Shutting down: Master
[2020-02-18 18:10:02 +0530] [8031] [INFO] Reason: Worker failed to boot.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/akash/.local/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akash/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/models/cli.py", line 57, in serve
    host=host)
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 92, in serve
    command_env=command_env)
  File "/home/akash/.local/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 172, in _execute_in_conda_env
    command, rc
Exception: Command 'source /home/akash/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-960bcb7a9eb015edaeb250062ae29e2f4403f944 1>&2 && gunicorn --timeout=60 -b 127.0.0.1:6050 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 3

**Comment by vrobinho** [comment]
Could you share the code that you used to register the model?

**Comment by dmatrix** [comment]
Can you please indicate or share the steps or code you used that resulted into this problem?

**Comment by juntai-zheng** [comment]
Hi @ukab23, I'm going to close this issue for now. Feel free to reopen it if needed, thanks!

**Comment by kaushalvivek** [comment]
Found the error/fix @ukab23 ?
