### ISSUE TITLE
[BUG] "mlflow db upgrade" fails on PostgreSQL instance due to invalid keyword CONSTRAINT

### ISSUE THREAD

**Issue by Esadruhn** [mlflow/mlflow#2444]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 10 (buster)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.7.6 
- psycopg2-binary 2.8.4
- backend: Postgres 11

### Describe the problem

Error on the `mlflow db upgrade $MLFLOW_DB_URI` command: `[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]`

There is an old issue about this, with MySQL, but it is closed and supposedly solved: #1397

### Dockerfile
I run MLFlow from a Docker container, the Dockerfile is:

```
FROM python:3.7

## ML FLOW SERVER CONFIG
ENV MLFLOW_DB_URI=postgresql://mlflow_user:mlflow_pwd@0.0.0.0:5432/mlflow_db

# Upgrade mlflow
RUN python3 --version
RUN pip3 install -U mlflow

RUN pip install psycopg2-binary
```
### Commands

Create the database
```
docker run --rm -it -p 5432:5432 -e POSTGRES_PASSWORD='mlflow_pwd' -e POSTGRES_USER='mlflow_user' -e POSTGRES_DB='mlflow_db' -e PGDATA='/var/lib/postgresql/data/pgdata' postgres:11
```

Create the ML Flow container and upgrade the db schema:
```
docker build -t mlflow .
docker run --rm -it --network=host -v artifact_folder:artifact_folder mlflow bash
mlflow db upgrade $MLFLOW_DB_URI
```

### Describe the problem

Error on the `mlflow db upgrade $MLFLOW_DB_URI` command: `[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]`

### Other info / logs

```
2020/02/19 16:44:21 INFO mlflow.store.db.utils: Updating database tables in preparation for MLflow 1.0 schema migrations
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ff01da956556, ensure_unique_constraint_names
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "experiments" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/db.py", line 28, in upgrade
    mlflow.store.db.utils._upgrade_db_initialized_before_mlflow_1(url)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 161, in _upgrade_db_initialized_before_mlflow_1
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 78, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/env.py", line 72, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.7/site-packages/mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py", line 174, in upgrade
    condition=column('lifecycle_stage').in_(["active", "deleted"])
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 354, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/batch.py", line 83, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 247, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "experiments" does not exist

[SQL: ALTER TABLE experiments DROP CONSTRAINT lifecycle_stage]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by Esadruhn** [comment]
Maybe I did not use it right and should not need to call this command on a newly created database ? Even if that is the case, it seems weird that it fails

**Comment by sukrat-kashyap** [comment]
It's failing for me as well with the same error.

**Comment by sukrat-kashyap** [comment]
I found the solution. Do not do `db upgrade` right after creating database. `mlflow db upgrade` is only necessary when you upgrade your mlflow version. When you are installing the first time all you need is the database created. When mlflow web server starts for the first time it automatically creates the table for you!

This issue can be closed! @jonas @d18s @tmielika

**Comment by iivvaall** [comment]
> This issue can be closed! @jonas @d18s @tmielika
No. The issue is very annoing. It makes the automated deploy difficult

**Comment by dbczumar** [comment]
@sukrat-kashyap @iivvaall @Esadruhn Thank you for raising this issue. I agree that `mlflow db upgrade` should be made to work with a fresh database instance; it is indeed annoying / problematic that this doesn't work until the database has been used to launch the MLflow server / record params & metrics.

I will investigate this issue.

**Comment by radzak** [comment]
I encountered this today. I can confirm that simply running `mlflow ui --backend-store-uri <dialect>+<driver>://<username>:<password>@<host>:<port>/<database>` helped, but I was confused and wasted some time on that.

**Comment by alanjcastonguay** [comment]
I'm running this in an init container, and got hit by the same problem. I've switched to simply `mlflow db upgrade || true` for now, but that's not going to catch _other_ problems.

**Comment by juftin** [comment]
I'm not sure how I haven't stumbled upon this issue yet. 

I'm ignoring this error in the underlying docker entrypoint:
```sh
# mlflow db upgrade fails when the database hasn't been initialized yet
mlflow db upgrade "${MLFLOW_BACKEND_STORE_URI}" || true
```

However, `mlflow db upgrade` should handle the initial database creation instead.

**Comment by kimminw00** [comment]
Any updates on this issue?

**Comment by mdyuldina** [comment]
Same issue here. It started to be reproduce often since mlflow>2.21. For some reason reproduced to all the time

**Comment by aoparaoji-innovative** [comment]
OK so i just saw this on mlflow 2.22.0
- new db
- container on an ec2 instance
- Postgres db
- fresh mlflow install only works after removing removing the db upgrade command

**Comment by rosinaderks** [comment]
Same issue here, new deployments fail due to this issue when we keep the `mlflow db upgrade "${MLFLOW_TRACKING_URI}"` command, which we do need when we update the a newer mlflow version (we are now moving from 2.22.2 to 3.3.2). Also using a container on ec2 instance and postgres db. Any updates on this? Would be nice if the `mlflow db upgrade` works consistently regardless of database state.
