### ISSUE TITLE
[BUG] MLflow doesn't delete conda environment created with pip dependency failure

### ISSUE THREAD

**Issue by Tradunsky** [mlflow/mlflow#2455]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: from 0.8.1 to 1.6.0
- **Python version**: 3.7
- **Exact command to reproduce**: 
`mlflow/examples/xgboost > mlflow run .`

### Describe the problem
Whenever pip fails to install a dependency (artifactory unavailable or wrong version specified), mlflow doesn't remove conda environment as it does if conda dependency fails. This way, on second run, mlflow re-uses this environment since content of conda.yaml doesn't change. However, conda environment cannot be re-used when it is not successfully setup by both conda and pip.  

### Code to reproduce issue
`conda.yaml`

> name: xgboost-example
> channels:
>   - defaults
>   - conda-forge
> dependencies:
>   - python=3.6
>   - xgboost
>   - pip:
>       - git+https://github.com/mlflow/mlflow==0
> 

..
`mlflow/examples/xgboost > mlflow run .`

### Other info / logs

> 2020/02/20 21:58:30 INFO mlflow.projects: === Creating conda environment **mlflow-605ca3beec0d13ae6e16f10cf433d51db8e58a09** ===
> Collecting package metadata (repodata.json): 
...
> CondaEnvException: Pip failed
> 
> Traceback (most recent call last):
>   File "/Users/username/anaconda3/bin/mlflow", line 11, in <module>
>     load_entry_point('mlflow==0.9.1', 'console_scripts', 'mlflow')()
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/mlflow/cli.py", line 139, in run
>     run_id=run_id,
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 230, in run
>     storage_dir=storage_dir, block=block, run_id=run_id)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 132, in _run
>     conda_env_name = _get_or_create_conda_env(project.conda_env_path)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 462, in _get_or_create_conda_env
>     conda_env_path], stream_output=True)
>   File "/Users/username/anaconda3/lib/python3.7/site-packages/mlflow/utils/process.py", line 38, in exec_cmd
>     raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
> mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1

`conda env list |grep mlflow-605ca3beec0d13ae6e16f10cf433d51db8e58a09`
>mlflow-605ca3beec0d13ae6e16f10cf433d51db8e58a09     /Users/username/anaconda3/envs/mlflow-605ca3beec0d13ae6e16f10cf433d51db8e58a09

**Comment by Tradunsky** [comment]
@AveshCSingh Here is the error I mentioned in https://github.com/mlflow/mlflow/issues/2201#issuecomment-583302366

Please take a look on pip case.

**Comment by Tradunsky** [comment]
Of course, it is not direct issue of mlflow, but I do believe mlflow should not re-use cached env then.

Related conda bug: https://github.com/conda/conda/issues/8537
