### ISSUE TITLE
[BUG] Columns disappear after sort in UI

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#2475]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Centos
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: latest
- **Python version**: 3.6
- **npm version, if running the dev UI**: 
- **Exact command to reproduce**:

### Describe the problem
Columns (metrics, params, tags) in the ExperimentView are computed from the run displayed in the page. If a column is not present in the first X runs, it will not be in the UI..
It does not work well with the sorting & fitlering features. Following the runs that have been extracted from DB, the columns will change. 
![columnsmlflow](https://user-images.githubusercontent.com/658597/75256072-2fd67d00-57e3-11ea-80ad-d555b0cb7f43.gif)

### Code to reproduce issue
Sort on a experiments with numerous runs but different tags,metrics and params

**Comment by lopezco** [comment]
I've a similar bug but I actually get an `INTERNAL_SERVER_ERROR` and the whole table disappears when I try to sort on any metric. I don't know if these are related.

This is the trace-back I got from the server:
```
2020/03/04 09:40:50 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 73, in make_managed_session
    yield session
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 651, in _search_runs
    .offset(offset).limit(max_results).all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
[SQL: SELECT DISTINCT TOP 100 runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id, CASE WHEN (anon_1.is_nan IS 1) THEN ? WHEN (anon_1.value IS NULL) THEN ? ELSE ? END AS clause_1, anon_1.value AS anon_1_value 
FROM runs LEFT OUTER JOIN (SELECT latest_metrics.[key] AS [key], latest_metrics.value AS value, latest_metrics.timestamp AS timestamp, latest_metrics.step AS step, latest_metrics.is_nan AS is_nan, latest_metrics.run_uuid AS run_uuid 
FROM latest_metrics 
WHERE latest_metrics.[key] = ?) AS anon_1 ON runs.run_uuid = anon_1.run_uuid 
WHERE runs.experiment_id IN (?) AND runs.lifecycle_stage IN (?) ORDER BY clause_1, anon_1.value, runs.start_time DESC, runs.run_uuid]
[parameters: (1, 1, 0, 'auc', '4', 'active')]
(Background on this error at: http://sqlalche.me/e/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 155, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 394, in _search_runs
    max_results, order_by, page_token)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/abstract_store.py", line 230, in search_runs
    order_by, page_token)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 654, in _search_runs
    next_page_token = compute_next_token(len(runs))
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 80, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
[SQL: SELECT DISTINCT TOP 100 runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id, CASE WHEN (anon_1.is_nan IS 1) THEN ? WHEN (anon_1.value IS NULL) THEN ? ELSE ? END AS clause_1, anon_1.value AS anon_1_value 
FROM runs LEFT OUTER JOIN (SELECT latest_metrics.[key] AS [key], latest_metrics.value AS value, latest_metrics.timestamp AS timestamp, latest_metrics.step AS step, latest_metrics.is_nan AS is_nan, latest_metrics.run_uuid AS run_uuid 
FROM latest_metrics 
WHERE latest_metrics.[key] = ?) AS anon_1 ON runs.run_uuid = anon_1.run_uuid 
WHERE runs.experiment_id IN (?) AND runs.lifecycle_stage IN (?) ORDER BY clause_1, anon_1.value, runs.start_time DESC, runs.run_uuid]
[parameters: (1, 1, 0, 'auc', '4', 'active')]
(Background on this error at: http://sqlalche.me/e/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 158, in wrapper
    response.set_data(e.serialize_as_json())
  File "/usr/local/lib/python3.7/site-packages/mlflow/exceptions.py", line 50, in serialize_as_json
    return json.dumps(exception_dict)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProgrammingError is not JSON serializable
```

**Comment by jdlesage** [comment]
Hi @lopezco 
In your case, there is an issue with MSSQL and the syntax of the query.... I think the root cause is different. Here the problem is the columns are computed from the 100 first runs, and when you sort them, the runs change => also the columns change.

I suggest to create another bug report for your problem. Because in this ticket, I report an UI problem not a SQL backend problem.

**Comment by lopezco** [comment]
Hi @jdlesage, you're right.
I've deleted my comment to avoid polluting you issue.

**Comment by Zangr** [comment]
This is more of a UX decision. I feel it's valid to only show columns introduced by all visible runs. @gioa what do you think about always showing all columns?

**Comment by gioa** [comment]
@Zangr I forgot why we only show the columns introduced by all visible runs. This indeed introduced inconsistency when you load more or sort, as pointed out here.

**Comment by Zangr** [comment]
@gioa thanks for confirming this. To always show all columns, we need to make some BE change to provide more metadata information. I'll adjust priority.

cc @sueann

**Comment by jdlesage** [comment]
With the help from @rom1504 , we already implemented the feature in our fork. (this branch: https://github.com/criteo-forks/mlflow/tree/criteo-master)
It enables us to solve this bug 
+ implement columns filtering (put in the payload only the columns that are displayed). It improves a lot the search with experiments that have tons of columns (some figures in this PR https://github.com/criteo-forks/mlflow/pull/178) 
+ and also be able to store in URL the columns to display (in order to share custom leaderboards by messages like slack) https://github.com/criteo-forks/mlflow/pull/199

At some point, if you are interested, we can organize a demo and see how we can help here.
