### ISSUE TITLE
[BUG]: Issue with running QuickStartDriver.java application

### ISSUE THREAD

**Issue by MarekScevlik** [mlflow/mlflow#2494]
### System information
- **OS Platform and Distribution: Windows 10
- **MLflow installed from (source or binary)**: via "pip install mlflow" in anaconda command prompt
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.6.0
- **Python version**: Python 3.7.4
- **Exact command to reproduce**: i have run the maven option Runs as "Maven test" on Eclipse after importing the downloaded git hub source of mlflow on to a local machine, 

### Describe the problem
Can you please tell me how to avoid this error?
Failed to exec 'python -m mlflow.store.artifact.cli', needed to access artifacts
within the non-Java-native artifact store at './mlruns/159/37b0d1d5af6741c68b97825667b204fc/artifacts'. 
Please make sure mlflow is available on your local system path (e.g., from 'pip install mlflow')

This occurs when Java tries to execute line of code: 
client.logArtifact(runId_7, tempFile);

I am not sure what I could be missing. Does it require a special system environment variable to be set? If so which one? and what it should contain?

mlflow was installed via anaconda command prompt command: pip install mlflow
then I have a Java project application that is refferncing mlflow libraries and is able to execute everything apart from this line of code where it returns that error. I am not sure anymore what to try. 

Please provide some hints.  

Thanks for replies
Regards Marek

**Comment by MarekScevlik** [comment]
I would want to know how I can run a simple Java application independently in Eclipse so that it references the necessary Jar files that make MLFLOW available to it so that my Machine learning Java code is able to processes a test machine learning scenario predicting result and the entire process is tracked in MLFLOW and is visible on the site. That is all I am trying to achieve. Nothing else. Please advise on how to do this successfully with Eclipse and Java. Is it possible? Would be great to know. Thanks for replies. Regards Marek

**Comment by MarekScevlik** [comment]
OK after spending some time I have now managed to get some stuff working on a local machine targeting http://localhost:5000 ... ok... 
So I have done it this way:
1. i have run maven command on command prompt: 
mvn install dependency:copy-dependencies -DskipTests
against the folder where the Java client file reside:   
("C:\mlflow\mlflow\java\client") where this operation has generated a list of jar files in the folder ("C:\mlflow\mlflow\java\client\target\dependency")
2. I have taken these jar files and have refferenced them in my new small java application in the libraries for that project
3. this project only consists of one Java file: QuickStartDriver.java which is the file from the original mlflow git hub project 
4. since it contains the main method you can execute it and it can process the lines of code with all necessary as the jar files cover the functionality 
5. once the file was processed till the end i have noticed successfull registering of the run in mlflow website where I can review the details of the run 

i think this is all i wanted to achieve ... bit weird i guess setup but what else can i do?

Thanks for advice
Regards Marek

**Comment by MarekScevlik** [comment]
might be useful for someone to get this thing going as a small stand alone java app for the sake of quick and small ml projects .. :  )

**Comment by dbczumar** [comment]
@MarekScevlik Sorry for the delay here! It sounds like the environment in which your Java application is running cannot find the `mlflow` binary in the system path; are you executing the Java application within your conda environment? Are you still blocked by this issue?

**Comment by dbczumar** [comment]
@MarekScevlik Please let me know if you're still encountering this issue. For now, I'm going to close the ticket until more information is available.

**Comment by MarekScevlik** [comment]
Hello dbczumar. Thanks a lot for a reply. Sorry for my later reply. I was busy with other work and simply did not have capacity/time to reply. So going back to the issue I faced. I still face it. The setup is that I am running the  code directly from Eclipse. I have a java file inside a java project. 
See the screenshot. I hope it was attached correctly. Everything seems to work just fine. The only problem is with the file it tries to access that was created using line of code: 
 FileUtils.writeStringToFile(tempFile, content, StandardCharsets.UTF_8)

See screenshot.
![2020-05-03 21_35_57-eclipse-workspace - MLFlow_Test_1_src_org_mlflow_tracking_samples_MlflowClientTe](https://user-images.githubusercontent.com/5921306/80923929-b466ee00-8d86-11ea-87e9-477b41f3e8f3.png)

**Comment by MarekScevlik** [comment]
So you think that this can be somehow fixed? What would my system path have to contain? 
When you say: environment in which your Java application is running cannot find the mlflow binary in the system path..

Related to system variables I have only this defined: 
![2020-05-03 21_45_43-Environment Variables](https://user-images.githubusercontent.com/5921306/80924113-74ecd180-8d87-11ea-9070-22073bb20038.png)

Do you think I am missing something?

My goal would be to setup a independent Java swing application that I can use to re-use mlflow libraries so that it can log result of machine learning mini projects into mlflow ui website. I am nearly there with this idea. Just this artifacts logging seems to be not working. Would appreciate if I get it working also. Would be great. Thanks for any advice. And sorry for my later replies. mlflow seems very nice and usefull so far.

**Comment by MarekScevlik** [comment]
Full error:
FAILED: testUseArtifactRepository
org.mlflow.tracking.MlflowClientException: Failed to exec 'python -m mlflow.store.artifact.cli', needed to access artifacts within the non-Java-native artifact store at './mlruns/171/fd413dabebdf4559b10270377831a9ca/artifacts'. Please make sure mlflow is available on your local system path (e.g., from 'pip install mlflow')
	at org.mlflow.artifacts.CliBasedArtifactRepository.checkMlflowAccessible(CliBasedArtifactRepository.java:204)
	at org.mlflow.artifacts.CliBasedArtifactRepository.logArtifact(CliBasedArtifactRepository.java:69)
	at org.mlflow.artifacts.CliBasedArtifactRepository.logArtifact(CliBasedArtifactRepository.java:87)
	at org.mlflow.tracking.MlflowClient.logArtifact(MlflowClient.java:519)
	at org.mlflow.tracking.samples.MlflowClientTest.testUseArtifactRepository(MlflowClientTest.java:591)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.mlflow.tracking.MlflowClientException: Failed to get mlflow version. Error: Traceback (most recent call last):
  File "C:\Users\Krispy007\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Krispy007\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Krispy007\Anaconda3\lib\site-packages\mlflow\__init__.py", line 29, in <module>
    import mlflow.tracking._model_registry.fluent
  File "C:\Users\Krispy007\Anaconda3\lib\site-packages\mlflow\tracking\__init__.py", line 16, in <module>
    from mlflow.tracking.fluent import _EXPERIMENT_ID_ENV_VAR, _EXPERIMENT_NAME_ENV_VAR, \
  File "C:\Users\Krispy007\Anaconda3\lib\site-packages\mlflow\tracking\fluent.py", line 13, in <module>
    import numpy as np
  File "C:\Users\Krispy007\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Krispy007\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

	at org.mlflow.artifacts.CliBasedArtifactRepository.forkMlflowProcess(CliBasedArtifactRepository.java:231)
	at org.mlflow.artifacts.CliBasedArtifactRepository.checkMlflowAccessible(CliBasedArtifactRepository.java:196)
	... 29 more

**Comment by dumdumxvx** [comment]
Any updates on this?

**Comment by MarekScevlik** [comment]
Hello. Unfortunately I did not really look into it since I was waiting for an input from you people. : )
It was just an exploration exercise from my side and that has then reached this stage where I shared the latest problem. Since then I have not really investigated further. So please feel free to close this topic. I might revisit it again in future. All the bes wishes. Have a good day.
