### ISSUE TITLE
[BUG] mlflow gc command fails with postgres backend store

### ISSUE THREAD

**Issue by sadanand-singh** [mlflow/mlflow#2542]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.7.0
- **Python version**: 3.6
- **npm version, if running the dev UI**: 6.13.7
- **Exact command to reproduce**: mlflow gc --backend-store-uri postgresql:///mlflow

### Describe the problem
Trying to use mlflow gc command on an existing postgres mlflow databse leads to the following error.

### Code to reproduce issue
Run command `mlflow gc --backend-store-uri postgresql:///mlflow`

### Other info / logs

```
/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py:1365: SAWarning: DELETE statement on table 'metrics' expected to delete 480 row(s); 72 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
  % (table.description, expected, rows_matched)
Traceback (most recent call last):
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(5dfec66f8711470c85245a349da31a09) is still referenced from table "metrics".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sadanand/Projects/mlflow-dojo/mlflow/store/db/utils.py", line 73, in make_managed_session
    yield session
  File "/home/sadanand/Projects/mlflow-dojo/mlflow/store/tracking/sqlalchemy_store.py", line 499, in _hard_delete_run
    session.commit()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 624, in execute
    uow,
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 348, in delete_obj
    delete,
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1341, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(5dfec66f8711470c85245a349da31a09) is still referenced from table "metrics".

[SQL: DELETE FROM runs WHERE runs.run_uuid = %(run_uuid)s]
[parameters: {'run_uuid': '5dfec66f8711470c85245a349da31a09'}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sadanand/anaconda3/envs/py36-dev/bin/mlflow", line 11, in <module>
    load_entry_point('mlflow', 'console_scripts', 'mlflow')()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sadanand/Projects/mlflow-dojo/mlflow/cli.py", line 422, in gc
    backend_store._hard_delete_run(run_id)
  File "/home/sadanand/Projects/mlflow-dojo/mlflow/store/tracking/sqlalchemy_store.py", line 499, in _hard_delete_run
    session.commit()
  File "/home/sadanand/anaconda3/envs/py36-dev/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sadanand/Projects/mlflow-dojo/mlflow/store/db/utils.py", line 80, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (psycopg2.errors.ForeignKeyViolation) update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(5dfec66f8711470c85245a349da31a09) is still referenced from table "metrics".

[SQL: DELETE FROM runs WHERE runs.run_uuid = %(run_uuid)s]
[parameters: {'run_uuid': '5dfec66f8711470c85245a349da31a09'}]
(Background on this error at: http://sqlalche.me/e/gkpj
```

**Comment by sadanand-singh** [comment]
@t-henry any comments based on your testing?

**Comment by sadanand-singh** [comment]
@dbczumar @t-henri any comments? This feature is pretty much unusable given this.

**Comment by dbczumar** [comment]
@t-henri Can you take a look at this?

**Comment by t-henri** [comment]
Hello, sorry for the long delay, I'll try to have a long this week or at the beginning of next week.

**Comment by sadanand-singh** [comment]
any update on this?

**Comment by dbczumar** [comment]
@sadanand-singh I've attempted to reproduce this issue using the following Postgres version: `PostgreSQL 12.1 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.12), 64-bit` with the following cases:

1. First, I created a fresh database on MLflow 1.7, logged runs, soft deleted them, and then ran `mlflow gc --backend-store-uri postgresql://<my_db_info>`. The `gc` command worked properly. I ran this in Python 2.7

2. Second, I tried (1) using Python 3.6.

3. Finally, I tried creating the postgres database on an older version of MLflow (1.2). Then, I upgraded to 1.7, upgraded the MLflow database state via Alembic with `mlflow db upgrade`, and attempted to log, soft delete, and then run `mlflow gc`; these steps worked as well.

___

@sadanand-singh Can you provide more information about the version of Postgresql that you're running, the version of MLflow that was initially used to create your MLflow + Postgres database, and which steps you took to set up the database initially?

**Comment by sadanand-singh** [comment]
@dbczumar  I am using PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) version. The db was created with mlflow 1.2, but I have upgraded the db with the `mlflow db upgrade` command.

**Comment by sadanand-singh** [comment]
After migrating postgres to 12.2 version, I can confirm that `mlflow gc` works. Thanks a lot @dbczumar for all the help.

I think it would be good to update docs with some minimum required version of postgres.

**Comment by jeremyjordan** [comment]
is there any reason why it shouldn't work on earlier postgres versions? AWS RDS instances don't even support version 12 yet https://aws.amazon.com/rds/postgresql/faqs/

**Comment by narendra36** [comment]
Hi @jeremyjordan, @dbczumar, I'm having Postgres version 9.2 on AWS EC2 instance and facing the same issue. 
MLFlow version is 1.14.1
How can I resolve it? Any update on this thread?

**Comment by narendra36** [comment]
any update on this?

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this looks like a duplicate of [#13254 "[BUG] gc fails with postgres backend, violates foreign key constraint"](https://github.com/mlflow/mlflow/issues/13254).

- Same symptom: `psycopg2.errors.ForeignKeyViolation` raised from `mlflow gc` against a postgres-backed tracking store.
- #13254 is filed against a much more recent MLflow release and is still open, so it's the right place to track the fix.

If you agree, would you mind closing in favour of the linked issue (and adding a 👍 there if you want to signal demand)? Happy to reopen if the symptoms diverge.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the cross-link was verified manually.)
