### ISSUE TITLE
[BUG] Logged tf.keras model in TF 1.X not running properly

### ISSUE THREAD

**Issue by lukemerrick** [mlflow/mlflow#2552]
### System information
- Linux PopOS (essentially Ubuntu) 19.10
- MLFlow from binary 1.7.0
- Python 3.7.5
- Happens in TF 1.14 and 1.15

### Describe the problem
Under the above configuration, saved/logged `tf.keras` models don't seem to run properly as `pyfunc` flavored models. It seems that there is some odd interplay between the way that MLFlow manages the session/graph and the way that `tf.keras` manages things, since after successfully invoking the model by hand the MLFlow code starts working.

### Code to reproduce issue
```Python
import collections
import io
import os
import pathlib
import shutil
import zipfile

import numpy as np
import pandas as pd
import requests
import sklearn.metrics
import sklearn.preprocessing
import tensorflow as tf

import mlflow
import mlflow.keras
import mlflow.pyfunc
import mlflow.tensorflow


def get_data():
    """Gets a named tuple of train-test-split bikeshare data via download."""
    zip_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip'
    z = zipfile.ZipFile(io.BytesIO(requests.get(zip_url).content))
    # here we pre-configure the datatypes for our dataframe
    # so it doesn't require any datatype modification after import
    bikeshare_dtypes = dict(season='category', holiday='bool',
                            workingday='bool', weathersit='category')
    bikeshare_datetime_columns = ['dteday']
    bikeshare_index_column = 'instant'
    with z.open('hour.csv') as csv:
        df = pd.read_csv(csv, 
                         dtype=bikeshare_dtypes, 
                         parse_dates=bikeshare_datetime_columns,
                         index_col=bikeshare_index_column)
        
    # drop categorical features
    df.drop(columns=df.select_dtypes('category').columns, inplace=True)
    
    # split train/test by year
    is_2011 = df['yr'] == 0
    df_2011 = df[is_2011].reset_index(drop=True)
    df_2012 = df[~is_2011].reset_index(drop=True)
    # specify which columns are features and which are not
    target = 'cnt'
    not_used_as_features = ['dteday', 'yr', 'casual', 'registered']
    non_feature_columns = [target] + not_used_as_features
    # split our data into features and targets
    x_train = df_2011.drop(columns=non_feature_columns)
    x_test = df_2012.drop(columns=non_feature_columns)
    y_train = df_2011[target]
    y_test = df_2012[target]
    return collections.namedtuple('Data', ['x_train', 'y_train', 'x_test', 'y_test'])(
        x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test)
    
# get data
data = get_data()
preprocessor = sklearn.preprocessing.StandardScaler()
preprocessor.fit(data.x_train)
x_train_processed = preprocessor.transform(data.x_train)
x_test_processed = preprocessor.transform(data.x_test)


# Construct a 2-layer MLP model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(1)
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.003), loss='mse')

# train with mlflow
epoch_number = 1
with mlflow.start_run() as run:
    for _ in range(2):
        model.fit(x_train_processed, data.y_train.values, batch_size=16)
        r2 = sklearn.metrics.r2_score(data.y_test, model.predict(x_test_processed))
        mlflow.log_metric('r2', r2, step=epoch_number)
        epoch_number += 1
    model.optimizer.learning_rate = 0.01
    for _ in range(3, 10):
        model.fit(x_train_processed, data.y_train.values, batch_size=32)
        r2 = sklearn.metrics.r2_score(data.y_test, model.predict(x_test_processed))
        mlflow.log_metric('r2', r2, step=epoch_number)
        epoch_number += 1
    # log the model
    mlflow.keras.log_model(model, 'keras_model', include_optimizer=False)

last_run_id = mlflow.search_runs().iat[0, 0]
mlf_model = mlflow.pyfunc.load_model(f'runs:/{last_run_id}/keras_model')
test_input = pd.DataFrame(x_train_processed[:3])

# this breaks when run first
try:
    print(mlf_model.predict(test_input))
except ValueError as e:
    print(e)

# this works, though!
with mlf_model._graph.as_default():
    with mlf_model._sess.as_default():
        print(pd.DataFrame(mlf_model.keras_model.predict(test_input.values),
                           index=test_input.index))
        
# once we've run on the DataFrame.values, the original call suddenly works?
print(mlf_model.predict(test_input))
```

### Other info
The issue happens when serving the model using `mlflow models serve -m ....` and letting MLFlow build a clean Conda environment for the model, too.

**Comment by mparkhe** [comment]
Thanks @lukemerrick : Thanks for filing this issue. Could you provide more details about the specific problem you have seen with this? You mentioned that

> saved/logged `tf.keras` models don't seem to run properly as `pyfunc` flavored models

What do you see? The the model through errors or not predicting expected results. If you could paste the error message you see or a stack trace that leads you believe there is a specific issue, that would be super helpful.

Since you are logging the model as a keras model, you should be able to serialize it as either pyfunc or keras flavor. Are you able to load it locally using `mlflow.keras.load_model` and predict using that? Docs: https://mlflow.org/docs/latest/models.html#keras-keras

**Comment by lukemerrick** [comment]
Sorry for the delay. Just re-built a Python 3.7 environment with TF 1.14.0 and MLFlow 1.7.0 and ran the above. The line with `mlf_model.predict(test_input)` raises a `ValueError`:

```python
Traceback (most recent call last):
  File "mlflow_bug.py", line 94, in <module>
    print(mlf_model.predict(test_input))
  File "/home/luke/.local/lib/python3.7/site-packages/mlflow/keras.py", line 321, in predict
    predicted = pd.DataFrame(self.keras_model.predict(dataframe))
  File "/home/luke/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1060, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "/home/luke/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2545, in _standardize_user_data
    'array or a list of arrays. You passed: x=' + str(x))
ValueError: Please provide as model inputs either a single array or a list of arrays. You passed: x=          0         1         2         3         4         5         6         7         8
0 -1.626038 -1.675535 -0.168618  1.488982 -1.470386 -1.258356 -1.024616  0.848628 -1.551923
1 -1.626038 -1.530763 -0.168618  1.488982 -1.470386 -1.359400 -1.110613  0.797681 -1.551923
2 -1.626038 -1.385991 -0.168618  1.488982 -1.470386 -1.359400 -1.110613  0.797681 -1.551923

```

**Comment by lukemerrick** [comment]
Re-running with the change to `mlflow.keras.load_model` raises the same error.

```python
# mlf_model = mlflow.pyfunc.load_model(f'runs:/{last_run_id}/keras_model')
mlf_model = mlflow.keras.load_model(f'runs:/{last_run_id}/keras_model')
```

**Comment by lukemerrick** [comment]
To recap, this raises the ValueError:
```python
mlf_model = mlflow.pyfunc.load_model(f'runs:/{last_run_id}/keras_model')
mlf_model.predict(test_input)
```

These are some workarounds that I think the `pyfunc`'s `.predict()` method should be equivalent to:
1. 
```python
mlf_model = mlflow.keras.load_model(f'runs:/{last_run_id}/keras_model')
pd.DataFrame(mlf_model.predict(test_input.values), index=test_input.index)
```
2.
```python
mlf_model = mlflow.pyfunc.load_model(f'runs:/{last_run_id}/keras_model')
with mlf_model._graph.as_default():
    with mlf_model._sess.as_default():
        print(pd.DataFrame(mlf_model.keras_model.predict(test_input.values),
                           index=test_input.index))
```

**Comment by lukemerrick** [comment]
@mparkhe Is there anything else you need?

**Comment by juntai-zheng** [comment]
Hi @lukemerrick, sorry for the delay. I believe I identified the bug and have a fix in https://github.com/mlflow/mlflow/pull/2762. The error was due to the MLflow implementation of the `keras` `pyfunc` expecting the input of arrays/list of arrays instead of a `pandas` dataframe.

As for `mlflow.keras.load_model.predict()` erroring out, this is expected since using this function loads the actual `keras` model back using `keras` native functions. You should be passing in arrays instead of `pandas` dataframes in your code for that error.

I don't know why the second call of `print(mlf_model.predict(test_input))` worked, I'll looks more into that...

**Comment by juntai-zheng** [comment]
The fix is now merged and will be included in the next release. Feel free to reopen if anything is still is going wrong. Thanks for pointing this issue out!
