### ISSUE TITLE
[BUG] NameError: name 'acc' is not defined

### ISSUE THREAD

**Issue by LuposX** [mlflow/mlflow#2562]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Used with PyTorch-lightning
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro
- **MLflow installed from (source or binary)**: `python-pip`
- **MLflow version (run ``mlflow --version``)**: 1.7.0
- **Python version**: 3.7
- **npm version, if running the dev UI**: /
- **Exact command to reproduce**: /

### Describe the problem
When using mlflow with pytorch-lighning to log I get the following error:` NameError: name 'acc' is not defined`

### Code to reproduce issue
```
    net = CNN()

    mf_logger = loggers.MLFlowLogger(experiment_name="test")
    trainer = pl.Trainer(fast_dev_run=True, logger=mf_logger)
    trainer.fit(net)
    trainer.test()
```

### Other info / logs
**Stacktrace:**
```
D:\Programme\Anaconda3\envs\pytorch\python.exe C:/Users/schup/PycharmProjects/Workspace/pytorch_test/GAN/CNN_lightning.py
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\directives.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(args, collections.Mapping), '{} args must be a dict with argument names as keys.'.format(name)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\typemap.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Sequence, defaultdict
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\callbacks\gradient_accumulation_scheduler.py:43: DeprecationWarning: Epochs indexing of `scheduling` starts from "1" until v0.6.x, but will start from "0" in v0.8.0.
  ' but will start from "0" in v0.8.0.', DeprecationWarning)
Validation sanity check:   0%|          | 0/1 [00:00<?, ?it/s]D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\directives.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(args, collections.Mapping), '{} args must be a dict with argument names as keys.'.format(name)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\typemap.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Sequence, defaultdict
Validation sanity check: 50it [00:05,  9.83it/s]              D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py:312: DeprecationWarning: validation_end was deprecated in 0.7.0 and will be removed 1.0.0. Use validation_epoch_end instead.
  warnings.warn(m, DeprecationWarning)
Epoch 1:   0%|          | 0/2 [00:00<?, ?it/s]D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\training_loop.py:280: DeprecationWarning: Displayed epoch numbers in the progress bar start from "1" until v0.6.x, but will start from "0" in v0.8.0.
  ' but will start from "0" in v0.8.0.', DeprecationWarning)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\directives.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(args, collections.Mapping), '{} args must be a dict with argument names as keys.'.format(name)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\typemap.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Sequence, defaultdict
Epoch 1: : 50it [00:06,  7.29it/s, loss=2.301]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\directives.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(args, collections.Mapping), '{} args must be a dict with argument names as keys.'.format(name)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\typemap.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Sequence, defaultdict

Epoch 1: : 100it [00:12,  7.74it/s, loss=2.301]WARNING:root:Experiment with name test not found. Creating it.
Epoch 1: : 100it [00:12,  7.74it/s, loss=2.301, v_num=8616c8db9c7643f5807bf1306fec48a4]
Epoch 1: : 100it [00:12,  7.73it/s, loss=2.301, v_num=8616c8db9c7643f5807bf1306fec48a4]
Testing:   0%|          | 0/1 [00:00<?, ?it/s]D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\directives.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(args, collections.Mapping), '{} args must be a dict with argument names as keys.'.format(name)
D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\graphql\type\typemap.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Sequence, defaultdict
Traceback (most recent call last):
  File "C:/Users/schup/PycharmProjects/Workspace/pytorch_test/GAN/CNN_lightning.py", line 133, in <module>
    trainer.test()
  File "D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 870, in test
    self.run_evaluation(test_mode=True)
  File "D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 368, in run_evaluation
    eval_results = self.evaluate(self.model, dataloaders, max_batches, test_mode)
  File "D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 262, in evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "D:\Programme\Anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 437, in evaluation_forward
    output = model.test_step(*args)
  File "C:/Users/schup/PycharmProjects/Workspace/pytorch_test/GAN/CNN_lightning.py", line 68, in test_step
    return {"test_acc": acc}
NameError: name 'acc' is not defined

Process finished with exit code 1

```

**Comment by LuposX** [comment]
error on my side
