### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by bhishanpdl** [mlflow/mlflow#2669]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Macos catalina
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.7.2
- **Python version**: Python 3.7.4
- **Exact command to reproduce**: python examples/quickstart/mlflow_tracking.py

### Describe the problem
I have installed libraries like numpy, pandas, pyspark, koalas, and mlflow in one of the fresh conda environment. Then I downloaded this official repo and tried to run the examples.

I used the following command as given in README:
```
 mlflow run examples/sklearn_elasticnet_wine -P alpha=0.4
```

This fails and gives the following error:
```
ConnectionRefusedError: [Errno 61] Connection refused
```

### Other info / logs
```
[04:47 PM]  Bhishan at BpMacpro in ~/OneDrive - Ohio University/a01_Data_Science/c02_Modules/mlflow
$ mlflow run examples/sklearn_elasticnet_wine -P alpha=0.4
/Users/poudel/.local/lib/python3.7/site-packages/markupsafe/__init__.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/pyspark/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import (
/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/pyspark/resultiterable.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ResultIterable(collections.Iterable):
/Users/poudel/.local/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):
Traceback (most recent call last):
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11b06f510>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11b06f510>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/poudel/miniconda3/envs/spk/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/Users/poudel/.local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/poudel/.local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/poudel/.local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/poudel/.local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/poudel/.local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/cli.py", line 138, in run
    run_id=run_id
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 288, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 111, in _run
    active_run = _create_run(uri, experiment_id, work_dir, entry_point)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 576, in _create_run
    active_run = tracking.MlflowClient().create_run(experiment_id=experiment_id, tags=tags)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/tracking/client.py", line 123, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 88, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)]
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 117, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 136, in call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 70, in http_request
    url=url, headers=headers, verify=verify, **kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 51, in request_with_ratelimit_retries
    response = requests.request(**kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/poudel/miniconda3/envs/spk/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11b06f510>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by andychow-db** [comment]
From the error message, it's trying to connect to an mlflow server. The command should work without that be necessary. 

Can you see if the env var `MLFLOW_TRACKING_URI` is set to `localhost:5000`? Clear that env var and it should work.

An alternative is to run a local version of the mlflow server in another terminal using the command `mlflow server`

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think this can be closed as a usage / configuration question rather than a bug.

- The error trace shows a `ConnectionRefusedError` against `localhost:5000`, which means a `MLFLOW_TRACKING_URI` (or equivalent) was set pointing at an HTTP tracking server that wasn't running.
- The quickstart example does not require a running tracking server; MLflow's default is the local file store, defined in [`mlflow/tracking/_tracking_service/utils.py:58-68`](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/_tracking_service/utils.py#L58-L68) (`_get_default_tracking_uri`, `is_tracking_uri_set`).
- @andychow-db raised exactly this above in 2020-04-17 and the reporter never confirmed.

If `mlflow run examples/sklearn_elasticnet_wine -P alpha=0.4` is still failing on a current MLflow with `MLFLOW_TRACKING_URI` unset, would you mind sharing a fresh traceback? Otherwise this looks safe to close — happy to be wrong if I missed something.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `master` branch.)
