### ISSUE TITLE
[BUG] Remote Tracking server with Docker env throws 'Connection refused'

### ISSUE THREAD

**Issue by ksanjeevan** [mlflow/mlflow#2697]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.7.2
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: N/A

### Describe the problem
When using a remote tracking server and a project with `MLproject` using a Docker env, I get an error thrown when `mlflow.start_run()` is called.

### Code to reproduce issue
1) Run `mlflow server` in a remote instance.
2) Run `ssh -L 5000:127.0.0.1:5000 remote_server`.
3) Run `export MLFLOW_TRACKING_URI=http://127.0.0.1:5000`.
4) Run the [examples/docker](https://github.com/mlflow/mlflow/tree/master/examples/docker) mlflow example.

Output I get is:
```
kiran[@boira]:mlflow>mlflow run examples/docker -P alpha=0.5
2020/04/13 13:20:50 INFO mlflow.projects: === Building docker image docker-example:aeaca67 ===
2020/04/13 13:20:50 INFO mlflow.projects: === Created directory /tmp/tmpr47gl3ca for downloading remote URIs passed to arguments of type 'path' ===
2020/04/13 13:20:50 INFO mlflow.projects: === Running command 'docker run --rm -v /home/kiran/.aws:/.aws -e MLFLOW_RUN_ID=27fe6853cbda4df080abd0c0c7fa681a -e MLFLOW_TRACKING_URI=http://127.0.0.1:5000 -e MLFLOW_EXPERIMENT_ID=0 docker-example:aeaca67 python train.py --alpha 0.5 --l1-ratio 0.1' in run with ID '27fe6853cbda4df080abd0c0c7fa681a' === 
/opt/conda/lib/python2.7/site-packages/mlflow/__init__.py:55: DeprecationWarning: MLflow support for Python 2 is deprecated and will be dropped in a future release. At that point, existing Python 2 workflows that use MLflow will continue to work without modification, but Python 2 users will no longer get access to the latest MLflow features and bugfixes. We recommend that you upgrade to Python 3 - see https://docs.python.org/3/howto/pyporting.html for a migration guide.
  "for a migration guide.", DeprecationWarning)
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    with mlflow.start_run():
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/fluent.py", line 122, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/client.py", line 96, in get_run
    return self._tracking_client.get_run(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 49, in get_run
    return self.store.get_run(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/rest_store.py", line 92, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/utils/rest_utils.py", line 133, in call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, params=json_body)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/utils/rest_utils.py", line 70, in http_request
    url=url, headers=headers, verify=verify, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/utils/rest_utils.py", line 51, in request_with_ratelimit_retries
    response = requests.request(**kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=27fe6853cbda4df080abd0c0c7fa681a&run_id=27fe6853cbda4df080abd0c0c7fa681a (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad1b41cb90>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020/04/13 13:20:52 ERROR mlflow.cli: === Run (ID '27fe6853cbda4df080abd0c0c7fa681a') failed ===
```

I've tested projects with a conda environment and they work perfectly fine, which makes me think it's an issue with how Docker talks to the remote tracking server? Does it need some permissions? Is my approach wrong?

Thanks.

**Comment by ksanjeevan** [comment]
I've had some progress on this. It can be solved with two steps:

1) Using the `docker run` flag propagataion introduced https://github.com/mlflow/mlflow/pull/2608 by passing `mlflow run .... -A net=host`. This fixes the the error thrown by `mlflow.start_run`. But then we get the error:

```
File "/mlflow/projects/code/validator/mlflow_handler.py", line 52, in _log_artifacts
    mlflow.log_artifact(config_path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 311, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 257, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 257, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 38, in log_artifact
    s3_client.upload_file(local_file, bucket, dest_path)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 613, in _make_api_call
    operation_model, request_dict, request_context)
  File "/opt/conda/lib/python3.6/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/conda/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/conda/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/opt/conda/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/opt/conda/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/opt/conda/lib/python3.6/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/opt/conda/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

This is because https://github.com/mlflow/mlflow/blob/71922462cc82225f5509d0baea71d523d169d73e/mlflow/projects/__init__.py#L831 doesn't place the aws credentials where they can be used. 

2) Workaround if docker is run as root is to add: 
```
docker_env:
    volumes: [..., 'home/user/.aws:/root/.aws']
```
in the MLproject file.

@tomasatdatabricks, @dbczumar Shouldn't https://github.com/mlflow/mlflow/blob/71922462cc82225f5509d0baea71d523d169d73e/mlflow/projects/__init__.py#L831 be modified? For some reason it only works for me when docker container is run as root. Any thoughts as to why? These two steps have been the only way I've gotten a docker project to log to a remote tracking server.

Let me know, thanks.

**Comment by juntai-zheng** [comment]
@tomasatdatabricks @dbczumar any thoughts on this?

**Comment by AAA97AAA** [comment]
I have encountered this issue `HTTPConnectionPool ()`. You should make sure your port is exposed on your dockerfile. And in case you have another container trying to access `mlflow_server` container, don't forget to bridge the connections.

For the credentials issue: are you sure you have both credentials on the `mlflow_server` container and on host ? mlflow requires to have it on the machine that runs the code as well as it uploads directly the artifacts on S3.

**Comment by ksanjeevan** [comment]
I'm not sure the credentials point is true @AAA97AAA. If that were the case, this error would also come up when using a remote tracking server using a `conda env`, but it doesn't. 
You shouldn't manually copy over your credentials to the tracking server, they should be correctly mounted as a volume like the code I lined to attempts to do.

**Comment by AAA97AAA** [comment]
For the credentials point, I wrote that after reading the following issue #629 

Sure, you shouldn't copy the credentials manually, but instead of mounting it as a volume, you can pass it as an environment variable: 

```
environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
```

Is there a reason why such approach is not recommendable ?

**Comment by bholligan** [comment]
I have also run into multiple issues with this default mount argument. It's now located here:
https://github.com/mlflow/mlflow/blob/cd90644d99a4465ac324633b0ae15400cb0a6489/mlflow/projects/backend/local.py#L363

and continues to be problematic for two reasons:
1. AWS credentials via packages like boto3 and the AWS CLI v2 look for credentials inside the `/root` directory on containers for the `.aws` folder, and the AWS cli does not currently support configuring the location of `.aws/sso/cache/*.json` files. 
2. It makes it incredibly hard to use a docker container to execute the mlflow run in a sibling container because the `str(aws_path)` on a container will reference a directory `/root/.aws` that is outside the scope of file sharing from the host container.

At the very least it would be helpful to be able to disable this argument from being passed by default to the docker args. I am also having to mount `~/.aws:/root/.aws`, and am not able to implement my `mlflow run` commands via a different docker container.
