### ISSUE TITLE
No module named mlflow.server

### ISSUE THREAD

**Issue by abaveja313** [mlflow/mlflow#270]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX Sierra
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.4.2
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**: mlflow server

### Describe the problem
MLFlow server module doesn't exist. Whenever I try to run mlflow server, it throws the error that the mlflow.server module doesn't exist

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
➜   mlflow ui
[2018-08-08 13:43:14 -0700] [21003] [INFO] Starting gunicorn 19.9.0
[2018-08-08 13:43:14 -0700] [21003] [INFO] Listening at: http://127.0.0.1:5000 (21003)
[2018-08-08 13:43:14 -0700] [21003] [INFO] Using worker: sync
[2018-08-08 13:43:14 -0700] [21006] [INFO] Booting worker with pid: 21006
[2018-08-08 13:43:14 -0700] [21006] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/amritbaveja/anaconda3/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'mlflow.server'
[2018-08-08 13:43:14 -0700] [21006] [INFO] Worker exiting (pid: 21006)
[2018-08-08 13:43:14 -0700] [21003] [INFO] Shutting down: Master
[2018-08-08 13:43:14 -0700] [21003] [INFO] Reason: Worker failed to boot.
Running the mlflow server failed. Please see the logs above for details.
```

**Comment by juntai-zheng** [comment]
Hi, I looked at your problem and couldn't reproduce it. Here were the steps I took that worked for me:
* created a new [conda](https://conda.io/docs/user-guide/tasks/manage-environments.html) environment with python 3.6 installed, using the command `conda create -n issue python=3.6`
* installed mlflow, using the command `pip install mlflow`
* ran both `mlflow server` and `mlflow ui`, both of which worked.

Do you think you could possibly reproduce these steps, or alternatively uninstall and reinstall mlflow to see if that fixes it?

**Comment by abaveja313** [comment]
Yes. Uninstalling and Reinstalling fixed. thanks.
