### ISSUE TITLE
[BUG]Unable to write artifact to a http server

### ISSUE THREAD

**Issue by ulorentz** [mlflow/mlflow#2744]
## System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 10.3
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.7.3

### Describe the problem
I am running a mlflow server on a machine that has a reverse proxy via https (using apache). A client runs experiment and logs to the server via ``mlflow.set_tracking_uri("https://url") ``. It manages to write metrics, but when I do ``mlflow.log_artifact(hist_path+".txt")`` it tries to write the artifacts to a local path and not to the server. The local path is the one set via server ``--default-artifact-root``, that I would expect to be the path on the server, and not local one. 

### Code to reproduce issue
The server is launched with ``mlflow server --backend-store-uri file:///media/server-data/mlflow --default-artifact-root file:///media/slow-data/mlflow_artifacts``
The client sets the tracking uri with ``mlflow.set_tracking_uri("https://url")`` (where ``url`` is the address of the server) and logs artifacts and model with ``mlflow.log_artifact(hist_path)`` and ``mlflow.pytorch.log_model(fitter.best_model, "models")``. 

### Other info / logs

```Traceback (most recent call last):
  File "tiny_linknet/extern.py", line 266, in <module>
    main(args)
  File "tiny_linknet/extern.py", line 201, in main
    mlflow.log_artifact(hist_path+".txt")
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 311, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 257, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 257, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 31, in log_artifact
    mkdir(artifact_dir)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 106, in mkdir
    raise e
  File "/home/lorenzo/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 103, in mkdir
    os.makedirs(target)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media'
```

**Comment by tomasatdatabricks** [comment]
Hi @ulorentz, thanks for posting. 

MLflow tracking server does not serve artifacts, artifacts are served via artifact repository. File uris (file:///path or just path) are served by local artifact repository. Local artifact repository points to the local filesystem on the client side. You can use ftp or sftp to store artifacts at remote tracking server. See https://mlflow.org/docs/latest/tracking.html#artifact-stores for the list of supported artifact repositories.

**Comment by dbczumar** [comment]
@ulorentz As @tomasatdatabricks points out, MLflow does not currently support streaming artifacts through the MLflow server; there is an open feature request for this - we would really appreciate a contribution to this discussion: https://github.com/mlflow/mlflow/issues/629.

For now, I'm going to resolve this ticket. Feel free to reopen it if these responses haven't addressed your issue.
