### ISSUE TITLE
Cannot load spacy model flavor from mlflow CLI

### ISSUE THREAD

**Issue by ditadi** [mlflow/mlflow#2772]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.6.9
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**:
1) Load a spacy model from disk `nlp = spacy.load("path/to/model")
2) Save Spacy as MLflow model to disk `mlflow.spacy.save_model(spacy_model=nlp, path="/path/to/saved/model")
3) Loading the Spacy model works from code
`nlp2 = mlflow.spacy.load_model("path")`
4) However, `mlflow models serve -m /path/to/model` fails with stack trace below. It says that it cannot find suitable flavor backend.

### Describe the problem
Cannot serve Spacy model via cli.

### Other info / logs
```
Traceback (most recent call last):
  File "/home/dima/miniconda2/envs/basemodel/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/mlflow/models/cli.py", line 56, in serve
    install_mlflow=install_mlflow).serve(model_uri=model_uri, port=port,
  File "/home/dima/miniconda2/envs/basemodel/lib/python3.6/site-packages/mlflow/models/cli.py", line 167, in _get_flavor_backend
    raise Exception("No suitable flavor backend was found for the model.")
Exception: No suitable flavor backend was found for the model.
```

**Comment by pogil** [comment]
Hi @ditadi - in order for the `mlflow models serve` command to work the MLmodel file needs to contain a `pyfunc` model flavor. From https://github.com/mlflow/mlflow/pull/2242#discussion_r407120557 it looks like the spaCy flavor only writes the `pyfunc` flavor in limited scenarios. If that's what is happening in your case, you may be able to help broaden the support. @arocketman may be willing to help you brainstorm how.

**Comment by arocketman** [comment]
Hi everyone. As @pogil pointed out, pyfunc flavor is present only under specific circumstances, please, as specified here:

https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/spacy.py#L98-L102

And in docstring of pyfunc method:

https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/spacy.py#L182-L189

Do you have a TextCategorizer in your spaCy pipeline? If not, that is probably the issue. If you do, then it could be a bug. 

What kind of pipeline do you have, and how do you wish that the pyfunc would predict?

**Comment by ditadi** [comment]
I do not have TextCategorizer in my pipeline. My use case is NER with EntityRecognizer. Would it be possible to hack together a pyfunc flavored model manually?

**Comment by naduhrin78** [comment]
Hey @ditadi , can you explain how you did spacy NER using pyfunc.
@arocketman how can we broaden the support for other spacy models, as I use variety of them?

**Comment by arocketman** [comment]
So, the point of change is the following:

https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/spacy.py#L178-L195

More specifically in:

https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/spacy.py#L193-L195

as you can see, we are applying the following:

`self.spacy_model(text).cats`

However, you can even call it with `self.spacy_model(text).ents` to retrieve, for example, the entities as specified here: https://spacy.io/api/doc#ents

Each object in ents is a Span: https://spacy.io/api/span#init 

The reason why I did not add in the first place the NER is that potentially you could have 100s of entities in your document, and creating a cell with all the entities inside formatted as span-string could get messy. However I think that there could be ways to make it cleaner. 

@ditadi what kind of output would you expect? How did you end up solving your specific case? Maybe your experience can help us brainstorm further

**Comment by naduhrin78** [comment]
I am tackling a specific use case as well and I guess according to each task even within NER, a prediction may differ, so perhaps exposing predict as an abstract method which can be modified on our end rather than changing function in library itself would be cooler?

**Comment by juntai-zheng** [comment]
Hi folks, did we want to discuss this any further? Otherwise I can close this issue. @naduhrin78 if you want to open another issue for a feature request, feel free to do so.

**Comment by Spooky-0** [comment]
Hi,
just want to mention that this is still an issue :)

**Comment by snosrap** [comment]
I've also encountered this limitation of not being able to use spacy's named-entity results from a `pyfunc` model flavor.

I've made some changes to the [spacy.py](https://github.com/snosrap/mlflow/commits/master/mlflow/spacy.py) file to include more columns for each dataframe row.

This means, that instead of getting a single `predictions` column that contains a `dict` of text categorization predictions:

|  | predictions |
| --- | --: |
| **0** | {'SPAM': 0.9, 'HAM': 0.21} |
| **1** | {'SPAM': 0.72, 'HAM': 0.46} |

You get more the the spacy doc features as additional columns:

| | text | ents | sents | cats | tokens | predictions
| --- | --- | --- | --- | --- | --- | --- |
**0** | Patient has pneumonia | [{'start': 12, 'end': 21, 'label': 'PNA'}] | [{'start': 0, 'end': 21}] | {'MILD': 0.8353676199913025, 'SEVERE': 0.98652... | [{'id': 0, 'start': 0, 'end': 7, 'pos': 'PROPN... | {'MILD': 0.8353676199913025, 'SEVERE': 0.98652...
**1** | Patient has pneumothorax | [{'start': 12, 'end': 24, 'label': 'PTX'}] | [{'start': 0, 'end': 24}] | {'MILD': 0.018907491117715836, 'SEVERE': 0.883... | [{'id': 0, 'start': 0, 'end': 7, 'pos': 'PROPN... | {'MILD': 0.018907491117715836, 'SEVERE': 0.883...

More detail on the columns:
* `text` (original text)
* `ents` (named entity offsets and labels)
* `sents` (sentence offsets)
* `cats` (category dictionary, like `predictions` previously)
* `tokens` (token offsets along with POS tagging)

I'll submit a PR, but wanted to discuss my approach here to get feedback.

Thanks!

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think this can be closed, as the behavior is by design (and now better documented).

`mlflow models serve` requires the pyfunc flavor, and `mlflow.spacy.save_model` only attaches a pyfunc flavor for spaCy pipelines that contain a `TextCategorizer` component:

- [`mlflow/spacy/__init__.py:145-150`](https://github.com/mlflow/mlflow/blob/master/mlflow/spacy/__init__.py#L145-L150) — the `if any(isinstance(pipe_component[1], spacy.pipeline.TextCategorizer) ...)` gate is what controls whether pyfunc is added.
- [`mlflow/spacy/__init__.py:159-166`](https://github.com/mlflow/mlflow/blob/master/mlflow/spacy/__init__.py#L159-L166) — the else-branch now emits an explicit warning: "Generating only the spacy flavor … cannot be loaded back using pyfunc APIs like `mlflow.pyfunc.load_model` or via the `mlflow models` CLI commands."

So an NER-only pipeline (no TextCategorizer) intentionally has no pyfunc backend. The "No suitable flavor backend was found" error is the downstream symptom; the warning at save time explains it.

Would you mind closing this out? If you have a use case for serving a non-classifier spaCy pipeline (NER, parser, etc.) via `mlflow models serve`, that's better filed as a separate feature request describing the desired wrapper contract.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `master` branch.)
