### ISSUE TITLE
[BUG] Tensorflow 1.x example conda ResolvePackageNotFound

### ISSUE THREAD

**Issue by jlangballe-miovision** [mlflow/mlflow#2789]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15.4
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:  1.8.0
- **Python version**: 3.7.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
```
cd examples/tensorflow/tf1
mlflow run .
```

### Describe the problem
Trying to run the tf1 examples gives an error installing dependencies.

```
ResolvePackageNotFound: 
  - python==3.6
```

### Code to reproduce issue
```
cd examples/tensorflow/tf1
mlflow run .
```

### Other info / logs
This is caused by a typo with dependencies in the tf1/conda.yaml file.

```
name: tensorflow-example
channels:
  - defaults
  - anaconda
dependencies:
  - python==3.6 # <-- Should be single =
  - tensorflow==1.13.1 # Here as well
  - pip:
    - mlflow
```

Changing the == to = fixes the issue.

Here's the full output of running the run command.
```

$ mlflow run .                                
2020/05/05 15:19:57 INFO mlflow.projects: === Creating conda environment mlflow-680bb0a93589120b486c611d395fa96a6ec264e5 ===
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - python==3.6

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/cli.py", line 133, in run
    run_id=run_id
  File "/usr/local/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 291, in run
    synchronous=synchronous, run_id=run_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 164, in _run
    conda_env_name = _get_or_create_conda_env(project.conda_env_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 456, in _get_or_create_conda_env
    conda_env_path], stream_output=True)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/process.py", line 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1
```

**Comment by juntai-zheng** [comment]
Thanks for catching this! Seems that this is relatively new and breaking a couple of our other examples as well - I'll make a PR to fix it.

**Comment by juntai-zheng** [comment]
The fix has been merged. Thanks again for pointing this out!
