### ISSUE TITLE
[BUG] mlflow Docker creates all folders as root

### ISSUE THREAD

**Issue by Zethson** [mlflow/mlflow#2883]
**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04 Docker
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.80
- **Python version**: 3.7
- **Exact command to reproduce**: Run any docker mlflow example

### Describe the problem
In my Docker container I am switching the user from root to a new user called 'user'. However, MLFlow creates all folders inside the Docker container as 'root'. Hence, I run into issues like:
```
GPU Run Time: 62.669366121292114 seconds
Logging model to mlflow...
Traceback (most recent call last):
  File "mnist_pytorch.py", line 188, in <module>
    start_training()
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "mnist_pytorch.py", line 175, in start_training
    mlflow.pytorch.log_model(model, 'models')
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 158, in log_model
    registered_model_name=registered_model_name, **kwargs)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/models/__init__.py", line 102, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 323, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/tracking/client.py", line 267, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 268, in log_artifacts
    artifact_repo.log_artifacts(local_dir, artifact_path)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 50, in log_artifacts
    mkdir(artifact_dir)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 110, in mkdir
    raise e
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 107, in mkdir
    os.makedirs(target)
  File "/home/user/miniconda/envs/pytorch/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/zeth/PycharmProjects/mlflow_pytorch/mlruns/0/fb257ba0821147898df402a23ee214c1/artifacts/models'
```

And when running `ls -la`:
```
(pytorch) user@3aabccf058b8:/mlflow/projects/code/mlruns/0/fb257ba0821147898df402a23ee214c1$ ls -la
total 32
drwxr-xr-x 6 root root 4096 Jan  1  1970 .
drwxrwxrwx 1 root root 4096 Jan  1  1970 ..
drwxr-xr-x 2 root root 4096 Jan  1  1970 artifacts
-rw-r--r-- 1 root root  396 Jan  1  1970 meta.yaml
drwxr-xr-x 2 root root 4096 Jan  1  1970 metrics
drwxr-xr-x 2 root root 4096 Jan  1  1970 params
drwxr-xr-x 2 root root 4096 Jan  1  1970 tags
```
I can see that everything is owned by root. 
However, to my mind everything should be created and owned by the current user!

Is there a workaround for this? I already made a workaround for the models subdirectory, where I just run chmod -R 777 /mlflowruns , however, this does not work for the artifacts, since this whole directory is created at runtime at the single code line.

### Code to reproduce issue
Any Docker example should suffice. I can share my custom code if you need it, but it's getting complex now.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by dmatrix** [comment]
Thanks for filing this. I wanted to ask a couple of questions. 

1. Are you executing this as `mflow run .  -e main -P arg=<value>` as a root
2. When do you say in the docker file you are switching the user, how are you switching the user?
3. Can you try running the mlflow server as a non-root user?

cc: asking @smurching for any insight into it.

**Comment by Zethson** [comment]
Thank you for your quick answer.




>     1. Are you executing this as `mflow run .  -e main -P arg=<value>` as a root
No.

>     2. When do you say in the docker file you are switching the user, how are you switching the user?
USER user
>     3. Can you try running the mlflow server as a non-root user?
Makes no difference.

The issue was confirmed by someone in the Slack channel.

**Comment by dmatrix** [comment]
Hello @Zethson, again thanks for answering the question quickly.

_Any Docker example should suffice._ 
I tried to run our examples/docker to see the results. 

 ```
docker images
REPOSITORY              TAG                 IMAGE ID            CREATED              SIZE
docker-example          e5eb78f             2fca45ad43a6        About a minute ago   1.08GB
mlflow-docker-example   latest              2c86e6ffd905        5 minutes ago        1.08GB
```
```
mlflow run examples/docker -P alpha=0.5
2020/05/27 09:10:23 INFO mlflow.projects: === Building docker image docker-example:e5eb78f ===
2020/05/27 09:10:24 INFO mlflow.projects: === Created directory /var/folders/jz/qg062ynx5v39wwmfxmph5nn40000gp/T/tmpo32eldbz for downloading remote URIs passed to arguments of type 'path' ===
2020/05/27 09:10:24 INFO mlflow.projects: === Running command 'docker run --rm -v /Users/julesdamji/gits/mlflow/mlruns:/mlflow/tmp/mlruns -v /Users/julesdamji/gits/mlflow/mlruns/0/82165e5cfeb74c238c980552480dcba1/artifacts:/Users/julesdamji/gits/mlflow/mlruns/0/82165e5cfeb74c238c980552480dcba1/artifacts -e MLFLOW_RUN_ID=82165e5cfeb74c238c980552480dcba1 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:e5eb78f python train.py --alpha 0.5 --l1-ratio 0.1' in run with ID '82165e5cfeb74c238c980552480dcba1' ===
/opt/conda/lib/python2.7/site-packages/mlflow/__init__.py:55: DeprecationWarning: MLflow support for Python 2 is deprecated and will be dropped in a future release. At that point, existing Python 2 workflows that use MLflow will continue to work without modification, but Python 2 users will no longer get access to the latest MLflow features and bugfixes. We recommend that you upgrade to Python 3 - see https://docs.python.org/3/howto/pyporting.html for a migration guide.
  "for a migration guide.", DeprecationWarning)
Elasticnet model (alpha=0.500000, l1_ratio=0.100000):
  RMSE: 0.794793101903653
  MAE: 0.6189130834228139
  R2: 0.18411668718221808
2020/05/27 09:10:31 INFO mlflow.projects: === Run (ID '82165e5cfeb74c238c980552480dcba1') succeeded ===
```
All the files created under mlruns are owned not by root but by me.

```
ls -l mlruns/0/82165e5cfeb74c238c980552480dcba1
total 8
drwxr-xr-x   3 julesdamji  staff   96 May 27 09:10 artifacts
-rw-r--r--   1 julesdamji  staff  399 May 27 09:10 meta.yaml
drwxr-xr-x   5 julesdamji  staff  160 May 27 09:10 metrics
drwxr-xr-x   4 julesdamji  staff  128 May 27 09:10 params
drwxr-xr-x  14 julesdamji  staff  448 May 27 09:10 tags
```
 _I can share my custom code if you need it, but it's getting complex now._

I would be curious how you ran this and all the steps from building the docker image, to running with mlflow. I guess you referring to this conversation on the [slack channel](https://mlflow-users.slack.com/archives/CBFQ95Y2G/p1590515743310600?thread_ts=1590514306.309500&cid=CBFQ95Y2G)

**Comment by Zethson** [comment]
Dear @dmatrix,

thanks! I guess the misunderstand is that we are talking about the files inside the docker container!
To me it looks like you were looking at the permissions of the mounted files on your very own filesystem.

So to reproduce it with the mlflow docker example:
`
mlflow run examples/docker -P alpha=0.5`

You will then see how it ran Docker, e.g.:
`docker run --rm -v /home/zeth/PycharmProjects/mlflow/examples/docker/mlruns:/mlflow/tmp/mlruns -v /home/zeth/PycharmProjects/mlflow/examples/docker/mlruns/0/f3ebf070053643ab9171c4834424c9c1/artifacts:/home/zeth/PycharmProjects/mlflow/examples/docker/mlruns/0/f3ebf070053643ab9171c4834424c9c1/artifacts -e MLFLOW_RUN_ID=f3ebf070053643ab9171c4834424c9c1 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:142abbb python train.py --alpha 0.5 --l1-ratio 0.1`

After mlflow is done you can start the Docker container in interactive mode with a shell:
`docker run --rm -it -v /home/zeth/PycharmProjects/mlflow/examples/docker/mlruns:/mlflow/tmp/mlruns -v /home/zeth/PycharmProjects/mlflow/examples/docker/mlruns/0/f3ebf070053643ab9171c4834424c9c1/artifacts:/home/zeth/PycharmProjects/mlflow/examples/docker/mlruns/0/f3ebf070053643ab9171c4834424c9c1/artifacts -e MLFLOW_RUN_ID=f3ebf070053643ab9171c4834424c9c1 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:142abbb /bin/bash` 
(I added -it and replaced the run command with /bin/bash).
If you now navigate through the file system to the artifacts etc everything will be owned by root.

**Comment by HiromuHota** [comment]
I was trying to use Docker container environment during mlflow run (https://github.com/HiromuHota/fonduer-mlflow/pull/13) last month.
It ran without any problem on Mac (as the Docker host), but did not on Linux. What I found was that the different behavior between Linux and Mac of file system sharing makes this hard to work as expected both on Linux and Mac.
https://stackoverflow.com/questions/43097341/docker-on-macosx-does-not-translate-file-ownership-correctly-in-volumes

Correct me if I'm wrong, but seems like @Zethson is using Linux (as the Docker host) and @dmatrix is using Mac.
In order to reproduce this issue, the Docker host may need to be Linux.

**Comment by Zethson** [comment]
Nice find @HiromuHota . I am indeed using Linux.

**Comment by dmatrix** [comment]
@HiromuHota @Zethson 
That solves a mystery of different behavior under Linux and macOS. I shall raise this with the team. 
Meanwhile, does the suggestion by @HiromuHota in the [slack thread](https://mlflow-users.slack.com/archives/CBFQ95Y2G/p1590515743310600?thread_ts=1590514306.309500&cid=CBFQ95Y2G) mitigate or resolve your issue on Linux?

**Comment by Zethson** [comment]
@dmatrix 
As a workaround I switch the user in the Docker container to root again, so that everything is run and (due to the bug?) owned by root.
Basically USER root.

Not ideal, but since I'm currently doing lots of experiments it's fine.

**Comment by dmatrix** [comment]
I can see it now:
```mlflow run . -e main -P alpha=0.5
2020/05/27 16:32:24 INFO mlflow.projects: === Building docker image docker-example:e5eb78f ===
2020/05/27 16:32:25 INFO mlflow.projects: === Created directory /var/folders/jz/qg062ynx5v39wwmfxmph5nn40000gp/T/tmp_fyabx3b for downloading remote URIs passed to arguments of type 'path' ===
2020/05/27 16:32:25 INFO mlflow.projects: === Running command 'docker run --rm -v /Users/julesdamji/gits/mlflow/examples/docker/mlruns:/mlflow/tmp/mlruns -v /Users/julesdamji/gits/mlflow/examples/docker/mlruns/0/79bc7f47017143c195659cda0924a159/artifacts:/Users/julesdamji/gits/mlflow/examples/docker/mlruns/0/79bc7f47017143c195659cda0924a159/artifacts -e MLFLOW_RUN_ID=79bc7f47017143c195659cda0924a159 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:e5eb78f python train.py --alpha 0.5 --l1-ratio 0.1' in run with ID '79bc7f47017143c195659cda0924a159' ===
/opt/conda/lib/python2.7/site-packages/mlflow/__init__.py:55: DeprecationWarning: MLflow support for Python 2 is deprecated and will be dropped in a future release. At that point, existing Python 2 workflows that use MLflow will continue to work without modification, but Python 2 users will no longer get access to the latest MLflow features and bugfixes. We recommend that you upgrade to Python 3 - see https://docs.python.org/3/howto/pyporting.html for a migration guide.
  "for a migration guide.", DeprecationWarning)
Elasticnet model (alpha=0.500000, l1_ratio=0.100000):
  RMSE: 0.794793101903653
  MAE: 0.6189130834228139
  R2: 0.18411668718221808
2020/05/27 16:32:27 INFO mlflow.projects: === Run (ID '79bc7f47017143c195659cda0924a159') succeeded ===

 docker run --rm -it -v /Users/julesdamji/gits/mlflow/examples/docker/mlruns:/mlflow/tmp/mlruns -v /Users/julesdamji/gits/mlflow/examples/docker/mlruns/0/79bc7f47017143c195659cda0924a159/artifacts:/Users/julesdamji/gits/mlflow/examples/docker/mlruns/0/79bc7f47017143c195659cda0924a159/artifacts -e MLFLOW_RUN_ID=79bc7f47017143c195659cda0924a159 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:e5eb78f /bin/bash
(base) root@1b0ef63ef1f8:/mlflow/projects/code# ls -l
total 292
-rw-r--r-- 1 root root    283 Jan  1  1970 Dockerfile
-rw-r--r-- 1 root root    123 Jan  1  1970 Dockerfile.mlflow-autogenerated
-rw-r--r-- 1 root root    237 Jan  1  1970 MLproject
-rw-r--r-- 1 root root   3284 Jan  1  1970 README.rst
-rw-r--r-- 1 root root    183 Jan  1  1970 kubernetes_config.json
-rw-r--r-- 1 root root    538 Jan  1  1970 kubernetes_job_template.yaml
drwxr-xr-x 4 root root   4096 Jan  1  1970 mlruns
-rw-r--r-- 1 root root   2331 Jan  1  1970 train.py
-rw-r--r-- 1 root root 264426 Jan  1  1970 wine-quality.csv

(base) root@1b0ef63ef1f8:/mlflow/projects/code/mlruns/0/79bc7f47017143c195659cda0924a159# ls -l
total 20
drwxr-xr-x 2 root root 4096 Jan  1  1970 artifacts
-rw-r--r-- 1 root root  406 Jan  1  1970 meta.yaml
drwxr-xr-x 2 root root 4096 Jan  1  1970 metrics
drwxr-xr-x 2 root root 4096 Jan  1  1970 params
drwxr-xr-x 2 root root 4096 Jan  1  1970 tags
```
