### ISSUE TITLE
[BUG] Windows 10 - CondaHTTPError: HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by luiztauffer** [mlflow/mlflow#2886]
### Willingness to contribute
- [x] Yes. I can contribute a fix for this bug independently.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No, except for my own repo. I did not change mlflow.
- **OS Platform and Distribution**: Windows 10
- **MLflow installed from**: pip
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow run .

### Describe the problem
When running `mlflow run .` from the root dir of my repo, I get this error traceback:

```shell
2020/05/28 13:06:01 INFO mlflow.projects: === Creating conda environment mlflow-a3b54c00d1403b3356472de25fb33ec1ac36c1a0 ===
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))


Traceback (most recent call last):
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Luiz\Anaconda3\envs\env_chamber_detector\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\mlflow\cli.py", line 133, in run
    run_id=run_id
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\mlflow\projects\__init__.py", line 291, in run
    synchronous=synchronous, run_id=run_id)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\mlflow\projects\__init__.py", line 164, in _run
    conda_env_name = _get_or_create_conda_env(project.conda_env_path)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\mlflow\projects\__init__.py", line 456, in _get_or_create_conda_env
    conda_env_path], stream_output=True)
  File "c:\users\luiz\anaconda3\envs\env_chamber_detector\lib\site-packages\mlflow\utils\process.py", line 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1
```

The weird thing is that conda works perfectly fine otherwise. The same command, with the same repo version works fine on my Ubuntu machine.

# Solution

I installed [OpenSSL for Windows](https://wiki.openssl.org/index.php/Binaries) and this problem was solved. 
I thought it would be helpful to register it here.

**Comment by luiztauffer** [comment]
Since I'm not sure if this is something you guys can solve from within mlflow, I'll leave it open for now

**Comment by dmatrix** [comment]
It seems this could be addressed as part of the documentation. Since you are willing to contribute, do you mind filing a PR request to document it?

**Comment by sai-krishna-msk** [comment]
Setting the environment variables as instructed in the following article helped 

https://arandika.medium.com/error-on-anaconda-creating-new-environment-using-conda-command-on-windows-7-cb0758431654

**Comment by dbczumar** [comment]
Because this issue appears to be related to Anaconda on Windows, rather than MLflow, I'm going to go ahead and close it. Thank you for using MLflow!
