### ISSUE TITLE
[FR] Adding snowflake support for backend store uri

### ISSUE THREAD

**Issue by edgBR** [mlflow/mlflow#2890]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

According to https://github.com/mlflow/mlflow/blob/master/mlflow/store/db/db_types.py it seems that only mysql, postgreSQL, MSSQL and sqlite are supported. It would be interesting to understand what it needs to be done to add snowflake as backend.

## Motivation
- What is the use case for this feature?

Snowflake is a fully managed database server where you only pay by use. It would be very beneficial for many people to offload the maintainability of the MLFlow backend server infrastructure as well as more cost efficient.

- Why is this use case valuable to support for MLflow users in general?

For organizations with buy over build policies this could be used as a pitch to ensure that MLflow maintainability will be minor.

- Why is this use case valuable to support for your project(s) or organization?

Snowflake is our main DBMS.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

We have not done any test yet.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
The current MLlfow backends supported are compatible with SQLAlchemy. If there's a SQL compatible connector to Snowflake, then it might be possible to extend the SQLAlchemy backend. 

While this is a good idea to extend the ecosystem, however,  it would be a big project for someone from the MLflow community to contribute. As such, we would appreciate starting with a short design that spells out different scenarios and expected behavior.

**Comment by edgBR** [comment]
Hi @dmatrix ,

Snowflake has their own native python connector as well as and sql alchemy backend: https://docs.snowflake.com/en/user-guide/sqlalchemy.html

I would try to provide more information for the scenarios and the expected behaviour. But basically as I pointed the idea would be to re run the same features that are available for the backend store with MySQL or SQLlite in snowflake. Probably the functions affected would be:

```python
mlflow.set_tracking_uri() 
mlflow.tracking.get_tracking_uri() 
mlflow.create_experiment() 
mlflow.set_experiment() 
mlflow.start_run()
mlflow.end_run() 
mlflow.active_run() 
mlflow.log_param() 
mlflow.log_metric()
mlflow.set_tag() 
mlflow.log_artifact()  #maybe?
mlflow.log_artifacts() #maybe? 
mlflow.get_artifact_uri()  #maybe?
```

Snowflake is ANSI SQL compliant so I believe that this will simplify some of the modifications.

BR
/Edgar

**Comment by dmatrix** [comment]
Thanks for responding. The next step is to design and follow some of the [contributing guidelines](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst).

**Comment by edgBR** [comment]
Hi @dmatrix 

We tried to add snowflake to the SQL alchemy backends but we got the following error:
```

(python3) [ec2-user@xxx-xxx-xxx i snowflake-test]$ mlflow server --backend-store-uri "snowflake://<user>:<password>@doman.aws-region/MCOG/my_user?role=my_role&warehouse=my_warehouse" --default-artifact-root file:/./mlruns -h 0.0.0.0 -p 5000 >> mlflow-error-log.txt
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2020/06/01 16:19:08 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2020/06/01 16:19:09 ERROR mlflow.cli: Error initializing backend store
2020/06/01 16:19:09 ERROR mlflow.cli: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error:
syntax error line 7 at position 40 unexpected 'CHECK'.
syntax error line 7 at position 77 unexpected ''deleted''.
syntax error line 7 at position 87 unexpected ')'. [SQL: "\nCREATE TABLE experiments (\n\texperiment_id INTEGER NOT NULL AUTOINCREMENT, \n\tname VARCHAR(256) NOT NULL, \n\tartifact_location VARCHAR(256), \n\tlifecycle_stage VARCHAR(32), \n\tCONSTRAINT experiment_pk PRIMARY KEY (experiment_id), \n\tCONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), \n\tUNIQUE (name)\n)\n\n"] (Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 603, in execute
    errvalue)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 7 at position 40 unexpected 'CHECK'.
syntax error line 7 at position 77 unexpected ''deleted''.
syntax error line 7 at position 87 unexpected ')'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/cli.py", line 286, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 101, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 87, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/registry.py", line 37, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 60, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 99, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/mlflow/store/db/utils.py", line 29, in _initialize_tables
    InitialBase.metadata.create_all(engine)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 603, in execute
    errvalue)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error:
syntax error line 7 at position 40 unexpected 'CHECK'.
syntax error line 7 at position 77 unexpected ''deleted''.
syntax error line 7 at position 87 unexpected ')'. [SQL: "\nCREATE TABLE experiments (\n\texperiment_id INTEGER NOT NULL AUTOINCREMENT, \n\tname VARCHAR(256) NOT NULL, \n\tartifact_location VARCHAR(256), \n\tlifecycle_stage VARCHAR(32), \n\tCONSTRAINT experiment_pk PRIMARY KEY (experiment_id), \n\tCONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), \n\tUNIQUE (name)\n)\n\n"] (Background on this error at: http://sqlalche.me/e/f405)
```

Any hints?

**Comment by dmatrix** [comment]
@edgBR, 

Thanks for filing this. Normally, for big feature enhancement, we would like to see some design or follow the guidelines
in [contribution process](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst).

Plus, it's hard to say from the stack trace where the problem is. 
@mparkhe @dbczumar do have any hints where he should do next?

**Comment by mparkhe** [comment]
@edgBR 

This seems be an error from the connector code trying to create experiment table. I would debug this by trying to create the table using `sqlalchemy` library (which MLflow uses for `SqlAlchemyStore` backend) and try and create the experiment table as defined with the DML printed above. The `CHECK` keyword seems to be an issue which is required to ensure that value for  `lifecycle_stage ` field is a valid one. This is enforced by SQL Alchemy `CheckConstraint`.

Possible solutions:
1. You may need to reach out to the creator of the library for advice on how to address this.
2. Use the [plugin](https://mlflow.org/docs/latest/plugins.html) mechanism to support this backend for your use case. You may be able to reuse the code from `SqlAlchemyStore` implementations.

To answer your other question, I would recommend using one of the existing [Artifact Store implementations](https://mlflow.org/docs/latest/tracking.html#artifact-stores) to store experiment run and model artifacts.

**Comment by edgBR** [comment]
Dear @mparkhe should I contact then the creator of the snowflake connector or the ones from the sql alchemy engine?
