### ISSUE TITLE
[BUG] Remote run completes with status succeeded  but throws an error mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run 'd1aabdea68ab4d919b5687cfedb32065' not found.

### ISSUE THREAD

**Issue by sudivate** [mlflow/mlflow#2958]
**Issue**

Remotely submitting run on Azure Databricks. Tracking URL set to 
`mlflow.set_tracking_uri("databricks")`

Remote run completes with a status succeeded but throws an error at the end 

**Area** 
MLflow Projects 

**Full Stack Trace:** 
2020/06/17 22:09:11 INFO mlflow.projects: === Run (ID '7dcea2b93466470fac23080877286ffc') **succeeded** ===
/opt/mlflow/mlflowproject
FINISHED
7dcea2b93466470fac23080877286ffc
dbfs:/databricks/mlflow/1315550910283717/7dcea2b93466470fac23080877286ffc/artifacts
Experiment Completed
Traceback (most recent call last):
  File "./run.py", line 41, in <module>
    run()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./run.py", line 33, in run
    print("Experiment Completed")
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 72, in __exit__
    end_run(RunStatus.to_string(status))
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 164, in end_run
    MlflowClient().set_terminated(_active_run_stack[-1].info.run_id, status)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 311, in set_terminated
    self._tracking_client.set_terminated(run_id, status, end_time)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 312, in set_terminated
    end_time=end_time)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 99, in update_run_info
    response_proto = self._call_endpoint(UpdateRun, req_body)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 137, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 103, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run 'd1aabdea68ab4d919b5687cfedb32065' not found.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 164, in end_run
    MlflowClient().set_terminated(_active_run_stack[-1].info.run_id, status)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 311, in set_terminated
    self._tracking_client.set_terminated(run_id, status, end_time)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 312, in set_terminated
    end_time=end_time)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 99, in update_run_info
    response_proto = self._call_endpoint(UpdateRun, req_body)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 137, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 103, in verify_rest_response
    raise RestException(json.loads(response.text))
**mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run 'd1aabdea68ab4d919b5687cfedb32065' not found.**

**Comment by pogil** [comment]
Hi @sudivate - would you please open an issue with Databricks support? We'll be able to much more effectively help you with Databricks issues that way. Use "submit case" link here: https://help.databricks.com/s/
