### ISSUE TITLE
[BUG]Issue with R API log artifacts

### ISSUE THREAD

**Issue by bickyealias** [mlflow/mlflow#3069]
We are trying to use MFLOW from RStudio.
MLFLOW tracking server is hosted on a remote server[docker container] access over https served by an nginx.
We have noticed 2 errors 

- RUN ID missing.At times it complains that the run id generated its not found.However that run ID is existing on MLFLOWServer .However if we rename the run id on the tracking server and re run the code the run id is accepted by the API.
```much existing on the mlflow tracking UI
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/bin/mlflow", line 11, in <module>
sys.exit(cli())
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/mlflow/store/cli.py", line 62, in log_artifacts
artifact_uri = store.get_run(run_id).info.artifact_uri
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/mlflow/store/file_store.py", line 380, in get_run
run_info = self._get_run_info(run_id)
File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/mlflow/store/file_store.py", line 396, in _get_run_info
databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '61f82e624abe44d094dccb320e22a3aa' not found
```
-  issue with "mlflow_log_artifact"

```Error in UseMethod("mlflow_id") :
no applicable method for 'mlflow_id' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
```

Below is the code and calls to MLFLOW server using R APIs listed here https://www.mlflow.org/docs/latest/R-api.html#mlflow-log-artifact
 
```Sys.setenv(PATH=paste0('/opt/conda/bin:', Sys.getenv('PATH')))
library(reticulate)
use_condaenv('mlflowtest4')
#mlflow::install_mlflow()
library(mlflow)
library(glmnet)
library(carrier)
# install_mlflow()
client <- mlflow_client(tracking_uri = "https://XXXX:4443")
mlflow_client(tracking_uri = "https://XXXXXX:4443")
mlflow_create_experiment("bicky/test_example66", artifact_location = '/home/ealiasbi/mlflow', client = client)
with(mlflow_start_run(),{
run1= mlflow_start_run(experiment_id=51,client=client)
mlflow_log_param("parameter", 5, run_id=run1$run_uuid, client=client)
mlflow_log_metric("metric", 0, run_id=run1$run_uuid, client=client)
mlflow_log_artifact("wine-quality.csv", artifact_path = '/home/ealiasbi/mflow/wine-quality.csv', run_id = run1$run_uuid, client = client)
})
```

**Comment by dmatrix** [comment]
@javierluraschi @kevinykuo Do you have any feedback on this?

**Comment by lorenzwalthert** [comment]
Do you run mlflow v1 on all involved components? Because this version was [released a year ago](https://github.com/mlflow/mlflow/tree/1.0.0) and I can imagine that either the bug was fixed already or caused by version incompatibilities. And as discussed in #3077, maybe also with the fact that you are pre-assigning an ID. I admit that this is a speculation 😄.

**Comment by bickyealias** [comment]
@lorenzwalthert thanks for your response.
Below is the code we are running.After replacing ```run_uuid``` with ```run_id``` as per your suggestion in [3077](https://github.com/mlflow/mlflow/issues/3077)
```Sys.setenv(PATH=paste0('/opt/conda/bin:', Sys.getenv('PATH')))
library(reticulate)
use_condaenv('mlflowtest5')
#mlflow::install_mlflow()
library(mlflow)
library(glmnet)
library(carrier)
client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
mlflow_create_experiment("bicky/test_example227", artifact_location = '/home/ealiasbi/mlflow', client = client)
with(mlflow_start_run(),{
  #pick experiment id from the pervious step and replace in the next step
  run1= mlflow_start_run(experiment_id=59,client=client)
  mlflow_log_param("parameter", 5, run_id=run1$run_id, client=client)
  #mlflow_log_metric("metric", 0, run_id=run1$run_id, client=client)
  #mlflow_log_artifact("test.txt", artifact_path = '/home/ealiasbi/mflow/test.txt', run_id = run1$run_id, client = client)

})
```
The latest error we see is 
```
Error in UseMethod("mlflow_id") : 
  no applicable method for 'mlflow_id' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
```
Earlier my assumption was this error is caused by ```mlflow_log_artifact```.However when calling ```mlflow_log_param``` alone by commenting other calls,it throws the same error.


Also to your question _*Do you run mlflow v1 on all involved components*_
can you please clarify what exactly do you mean?
On the mlflow server we have installed mlflow version 1.9.1
```/opt/conda/bin/pip install mlflow==1.9.1```
and on RStudio env when we do we install mlflow lib to our env
by doing ```mlflow::install_mlflow()``` it installs 1.0.0 by default.

``` mlflow::install_mlflow()
Collecting mlflow==1.0.0
```
Is there any other way to use upgraded versions of R apis if thats what you meant?This [document](https://www.mlflow.org/docs/latest/R-api.html#) doesnt clarify that.
Any help on this is much appreciated.

Regards,
Bicky

**Comment by lorenzwalthert** [comment]
> Also to your question Do you run mlflow v1 on all involved components
can you please clarify what exactly do you mean?

Well the version of the R and conda binary should correspond, i.e. when getting the R package version 1.9.1 from CRAN and you run `mlflow::install_mlflow()`, you should see 
```
Collecting mlflow==1.9.1
```
Which is not what you see.

I also don't see why you are using `with()` above. I think this is used in mlflow Python, but I haven't seen this in the R API. And as I said, I don't think you can pre-assign IDs like `59`.

**Comment by bickyealias** [comment]
HI @dmatrix thanks for your response.

Am only using an experiment id that is generated from the previous step of creating the experiment
Also I removed the ```with``` block and below is my updated code.
```Sys.setenv(PATH=paste0('/home/ealiasbi/.conda/envs/mlflow_test6/bin/python:', Sys.getenv('PATH')))
Sys.setenv(MLFLOW_PYTHON_BIN='/home/ealiasbi/.conda/envs/mlflow_test6/bin/python')
library(reticulate)
use_condaenv('mlflow_test6')
packageurl <- "https://artifactory.ai.cba:443/artifactory/static/ai/aiaa/rstudio-server-pro/mlflow_1.9.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
packageVersion('mlflow')
library(mlflow)
library(glmnet)
library(carrier)
client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
exp_id=mlflow_create_experiment("bicky/test_examplesample122", artifact_location = '/home/ealiasbi/mlflow', client = client)
run1= mlflow_start_run(experiment_id=exp_id,client=client)
mlflow_log_param("parameter", 5, run_id=run1$run_id, client=client)
mlflow_log_metric("metric", 0, run_id=run1$run_id, client=client)
mlflow_log_artifact("/home/ealiasbi/mflow/test.txt", artifact_path = '/home/ealiasbi/mflow/test.txt',run_id=run1$run_id, client=client)
```
Added python bin path to MLFLOW_PYTHON_BIN as per [this](https://mlflow.org/docs/latest/R-api.html#install-mlflow) documentation.
After the above changes, 

1. mlflow_log_param works fine
2. mlflow_log_metric works fine
3. mlflow_log_artifact fails with below error
  ```
  File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/mlflow/store/file_store.py", line 396, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '4a2f3e382fa547e6909d652b95b313f1' not found
Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose,  : 
  System command error
```
 However am not sure why it complains the ```Run '4a2f3e382fa547e6909d652b95b313f1'``` is missing as you can see in the attached screenshot on MLFlow tracking UI,the runid in question is existing for this experiment.
![image](https://user-images.githubusercontent.com/16069726/87839124-c44d9300-c8dc-11ea-8ae9-d71074b49401.png)


also as per [this](https://mlflow.org/docs/latest/R-api.html#mlflow-log-artifact) i tried to omit ```client_id ``` and ```run_id``` and just call 
```mlflow_log_artifact("/home/ealiasbi/mflow/test.txt", artifact_path = '/home/ealiasbi/mflow/test.txt')```
It fails with the errror
```Error in wait_for(function() mlflow_rest("experiments", "list", client = client),  : 
  Operation failed after waiting for 10 seconds"
```

Am also not disregarding your comment on version consistency.
I have installed mflow 1.9.0 from source . **I could not find 1.9.1 on CRAN** Not sure if that matters??(1.9.1 on conda vs 1.9.0 on R)?
``` 
packageVersion('mlflow')
[1] ‘1.9.0’
```
conda package version :
```
mlflow                    1.9.1 
```

 So clearly its the issue of binding experiment to a run id for uploading artifacts.Is there any suggestions on how I can change the code to bind them differently?

**Comment by lorenzwalthert** [comment]
From 
> File "/home/ealiasbi/.conda/envs/r-mlflow-1.0.0/lib/python3.6/site-packages/mlflow/store/file_store.py", line 396, in _get_run_info
  databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '4a2f3e382fa547e6909d652b95b313f1' not found
Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose,  : 
System command error

We can see that you use the r-mlflow-1.0.0 environment, which is a hint that the version used is not 1.9.1 here. I’d remove this conda  env if it does not contain anything you want to keep.

**Comment by lorenzwalthert** [comment]
Ask not sure why you use an absolute path as the target directory for the artifact. I think this should be relative, since the file will be logged somewhere under your run id -> artifacts -> relative dir. Try just the file name `artifact_path` instead of an absolute path.

**Comment by bickyealias** [comment]
@lorenzwalthert thanks for your reference.
I changed the code to remove reference from conda env.
```
Sys.setenv(MLFLOW_PYTHON_BIN='/home/ealiasbi/.conda/envs/mflow11/bin/python')
library(reticulate)
use_condaenv('mflow11')
library(mlflow)
library(glmnet)
library(carrier)
client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
exp_id=mlflow_create_experiment("bicky/test_examplesample130", artifact_location = '/home/ealiasbi/mlflow', client = client)
run1= mlflow_start_run(experiment_id=exp_id,client=client)
mlflow_log_param("parameter", 5, run_id=run1$run_id, client=client)
mlflow_log_metric("metric", 0, run_id=run1$run_id, client=client)
mlflow_log_artifact("/home/ealiasbi/mflow/test.txt", artifact_path = 'test.txt',run_id=run1$run_id, client=client)
```
Currently getting a whole different error- which I think is a progress :).Moving to same versions on R and conda has helped to git rid of the previous errors.
```
Error in process_initialize(self, private, command, args, stdout, stderr,  : 
  processx error: 'No such file or directory' at unix/processx.c:378
```
As per recommendation I have passed only the file name to the artifact path.However the issue is in the first parameter.
As per[this](https://mlflow.org/docs/latest/R-api.html#mlflow-log-artifact).Its not clear what should be the path.
The path in question is pretty much existing on the disk.
```
(mlflow11) ealiasbi@rstudio:~/bicky/Mflow_withoutConda$ ls -ltr /home/ealiasbi/mflow/test.txt
-rwx------+ 1 ealiasbi domain users 17 Jul  7 12:04 /home/ealiasbi/mflow/test.txt
```
I think this is an open issue as per [this](https://github.com/mlflow/mlflow/issues/1009)

**Comment by lorenzwalthert** [comment]
Can you use the [reprex](https://reprex.tidyverse.org) package so we see where exactly which error occurs? Also, you example contains a lot of code that is not required here. I dropped it. From running your code with a local client, I also got a 'no such file or directory error', but slightly different (because I use a local client). I think the problem was that the file you want to log should be in the working directory: 

``` r
library(mlflow)
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
mlflow_log_param("parameter", 5, run_id = run1$run_id, client = client)
mlflow_log_metric("metric", 0, run_id = run1$run_id, client = client)
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
writeLines(letters, artifact)

mlflow_log_artifact(artifact, artifact_path = "test.txt", run_id = run1$run_id, client = client)
#> 2020/07/19 08:42:55 INFO mlflow.store.artifact.cli: Logged artifact from local file mlflow-test.txt to artifact_path=test.txt
#> Root URI: /private/var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpipOW1Z/reprex1441e63d63b72/mlruns/1/5346ab7be2be4d59bd327c6990115821/artifacts
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The `client` and the `run_id` arguments are taken from the active run if not specified, so you can simplify:

``` r
library(mlflow)
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5)
mlflow_log_metric("metric", 0)
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
writeLines(letters, artifact)
mlflow_log_artifact(artifact, artifact_path = "test.txt")
#> 2020/07/19 08:47:11 INFO mlflow.store.artifact.cli: Logged artifact from local file mlflow-test.txt to artifact_path=test.txt
#> Root URI: /private/var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpipOW1Z/reprex1441e73031a58/mlruns/0/1a0b21fb932e48c6bc06cd859ebf577f/artifacts
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
So here is the reprex that shows we can't log from the home directory for example, and that it fails uninformatively. It's exactly the same code as in my previous comment, but `tmp` is `"~"` instead of `tempdir()`.

``` r
library(mlflow)
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5)
mlflow_log_metric("metric", 0)
tmp <- "~"
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
path_before_logged <- fs::path(tmp, artifact)
writeLines(letters, path_before_logged)
mlflow_log_artifact(path_before_logged, artifact_path = "test.txt")
#> Traceback (most recent call last):
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/bin/mlflow", line 8, in <module>
#>     sys.exit(cli())
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 829, in __call__
#>     return self.main(*args, **kwargs)
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 782, in main
#>     rv = self.invoke(ctx)
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
#>     return _process_result(sub_ctx.command.invoke(sub_ctx))
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
#>     return _process_result(sub_ctx.command.invoke(sub_ctx))
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
#>     return ctx.invoke(self.callback, **ctx.params)
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/click/core.py", line 610, in invoke
#>     return callback(*args, **kwargs)
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/mlflow/store/artifact/cli.py", line 42, in log_artifact
#>     artifact_repo.log_artifact(local_file, artifact_path)
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 32, in log_artifact
#>     shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
#>   File "/Users/lorenz/opt/miniconda3/envs/r-mlflow-1.9.0/lib/python3.6/shutil.py", line 120, in copyfile
#>     with open(src, 'rb') as fsrc:
#> FileNotFoundError: [Errno 2] No such file or directory: '~/mlflow-test.txt'
#> Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose, : System command 'mlflow' failed, exit status: 1, stdout & stderr were printed
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
Can you use the [reprex](https://reprex.tidyverse.org) package so we see where exactly which error occurs? In your code, you don't create the file `"/home/ealiasbi/mflow/test.txt"`, and I don't know if you created it earlier, but it must exist. I.e. you can't log an artifact that you have not yet created.

Also, you example contains a lot of code that is not required here. I dropped it. I usually log artifacts to a temp directory and then it works. 

The `client` and the `run_id` arguments are taken from the active run if not specified, so you can simplify:
``` r
library(mlflow)
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5)
mlflow_log_metric("metric", 0)
tmp <- tempdir()
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
path_before_logged <- fs::path(tmp, artifact)
writeLines(letters, path_before_logged)
mlflow_log_artifact(path_before_logged, artifact_path = "test.txt")
#> 2020/07/19 08:52:10 INFO mlflow.store.artifact.cli: Logged artifact from local file /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpR8pMLz/mlflow-test.txt to artifact_path=test.txt
#> Root URI: /private/var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpipOW1Z/reprex1441e7f16cadc/mlruns/0/6d88fc7767cf47279cbbdbefe0122191/artifacts
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Sidenote: The path expansion with `~` is not performed apparently in `mlflow_log_artifact()`, which should be a separate issue, so you need `path.expand("~")`  for now if you want to log from the home directory.

**Comment by bickyealias** [comment]
@lorenzwalthert thanks for your reference.
Towards the end of my above comment if you see the file is existing on the disk.So its clearly  not the case of file not present.
So I dont think the new code is needed.
Nevertheless,I ran your code as is.

On the next step to log param,if I run this
```mlflow_log_param("parameter", 5)``` it fails with 
```Error in process_initialize(self, private, command, args, stdout, stderr,  : 
  processx error: 'No such file or directory' at unix/processx.c:378
```

![image](https://user-images.githubusercontent.com/16069726/87870628-40370080-c9ed-11ea-80d1-86a114e42901.png)

as you can see without client_id and run_id it would simply fail.
So I introduced them back.
```
Sys.setenv(MLFLOW_PYTHON_BIN='/home/ealiasbi/.conda/envs/mflow11/bin/python')
library(reticulate)
use_condaenv('mflow11')
library(mlflow)
library(glmnet)
library(carrier)
client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
#client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5,run_id=run1$run_id, client=client)
mlflow_log_metric("metric", 0,run_id=run1$run_id, client=client)
tmp <- tempdir()
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
path_before_logged <- fs::path(tmp, artifact)
writeLines(letters, path_before_logged)
mlflow_log_artifact(path_before_logged, artifact_path = "test.txt",run_id=run1$run_id, client=client)
``` 
but still getting the same error as before,i.e writing to tmp is not helping the cause.
![image](https://user-images.githubusercontent.com/16069726/87870765-8771c100-c9ee-11ea-8fbe-9040e320541f.png)

I want to clarify one thing that **my MFLOW tracker server is not on the same host.Its a remote server sitting behind an nginx proxy.** Am not sure if thats worth considering.

Also,isnt this an acknowledged [bug](https://github.com/mlflow/mlflow/issues/1009).

**Comment by bickyealias** [comment]
@lorenzwalthert any thoughts on how to proceed further?

**Comment by lorenzwalthert** [comment]
I think it's important to distinguish the two backends according to the [docs](https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers):

- artifact store (defaults to local file system, can be S3 or similar)
- backend store (defaults to file system, can be a data base)

Can you verify that the parameters are logged correctly before tackling the artifact problem? Because according to the link above, the tracking uri should be something like `<dialect>+<driver>://<username>:<password>@<host>:<port>/<database>`, you have `"https://backend-mlflow-server.aiaa.ai.cba:4443"` (and I was not sure if you put this to hide your credentials or if you were really using this URL).

If you are running the above code locally, the arifact store should just be your local `mlruns` directory, but if you are running that in the cloud, maybe you should specthis does not work and you could try to specify an S3 backend (I remember seeing some databricks error above) when you create the experiment, like `mlflow::mlflow_create_experiment("YourExperiment", "s3://bucket/path")`. Note that you need to have an AWS account with the privliedges for S3 described in the above docs and either the aws cli tools or the env variables configured to provide your credentials to mlflow.

Also, from your code above, I can't conclude if the code runs successfully if you use the default client (i.e. a local backend store). Can you confirm this works by running

```r
library(mlflow)
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5)
mlflow_log_metric("metric", 0)
tmp <- tempdir()
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
path_before_logged <- fs::path(tmp, artifact)
writeLines(letters, path_before_logged)
mlflow_log_artifact(path_before_logged, artifact_path = "test.txt")
#> 2020/07/19 08:52:10 INFO mlflow.store.artifact.cli: Logged artifact from local file /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpR8pMLz/mlflow-test.txt to artifact_path=test.txt
#> Root URI: /private/var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/RtmpipOW1Z/reprex1441e7f16cadc/mlruns/0/6d88fc7767cf47279cbbdbefe0122191/artifacts
```

**Comment by dmatrix** [comment]
@lorenzwalthert, we are going to address this distinction clearly and succinctly in #3108

**Comment by bickyealias** [comment]
@lorenzwalthert thanks for your response.We are not using AWS or S3.We are running MLFLOW server on a docker container and RStudio on another container. They use POSIX compliant file systems.Nothing fancy.
I can confirm parameters and metrics are uploaded correctly
<img width="1318" alt="Screen Shot 2020-07-31 at 6 30 16 pm" src="https://user-images.githubusercontent.com/16069726/89017018-05be5380-d35d-11ea-9c3a-339b7c9a36f9.png">
Running the below wont solve anything as there is no MLFlow server running locally.
```
# client <- mlflow_client(tracking_uri = "https://backend-mlflow-server.aiaa.ai.cba:4443")
client <- mlflow_client()
``` 
as it wont upload anything to remote server where we want to record the experiment,metrics,parameter and artifacts.
Also the issues is only with artifacts.Metrics and params are uploaded correctly as see in the screenshot.
Let me know your thoughts.

**Comment by bickyealias** [comment]
@lorenzwalthert-As I mentioned before we are using an NGINX reverse proxy that is serving the MLFlow server(since mlflow currently doesnt support SSL/https).I wanted to rule out if that is causing the issue with log_artifact .However am still getting the same error even if I bypass the proxy completely.
```
Sys.setenv(MLFLOW_PYTHON_BIN='/home/ealiasbi/.conda/envs/mflow11/bin/python')
library(reticulate)
use_condaenv('mflow11')
library(mlflow)
library(glmnet)
library(carrier)
client <- mlflow_client(tracking_uri = "http://backend-mlflow-server.aiaa.ai.cba:5000")
#client <- mlflow_client()
exp_id <- mlflow_create_experiment(paste0("bicky/test_exp", digest::digest(Sys.time())), client = client)
run1 <- mlflow_start_run(experiment_id = exp_id, client = client)
# client and run_id are taken from the active run
mlflow_log_param("parameter", 5,run_id=run1$run_id, client=client)
mlflow_log_metric("metric", 0,run_id=run1$run_id, client=client)
tmp <- tempdir()
artifact <- "mlflow-test.txt" # sees not to work when placed outside working directory, e.g. artifact <- "~/mlflowow-test"
path_before_logged <- fs::path(tmp, artifact)
writeLines(letters, path_before_logged)
mlflow_log_artifact(path_before_logged, artifact_path = "test.txt",run_id=run1$run_id, client=client)

````
![Screen Shot 2020-08-04 at 11 34 06 am](https://user-images.githubusercontent.com/16069726/89243093-76f45400-d646-11ea-84e3-abc02f9b1533.png)

**Comment by lorenzwalthert** [comment]
@bickyealias sorry I can't help out further here, also I doubt other people can because we can't reproduce your error. I think if I was you, I'd use `debug(mlflow_log_artifact)` next in RStudio as well as `debug( some other function from the stack lower down that you find is going to cause problems)` and try to get more context of the error and post this here. Also, I hope #3108 is going to clarify some things for me. If you can't get the remove server working, why not just use a remote data base as backend storage and AWS s3 for artifact storage? Alternatively, try it with the Python API and if it works, try to work out the differences. Or provide a public server we can access for testing purposes (`http://backend-mlflow-server.aiaa.ai.cba:5000` is not open to the world).
