### ISSUE TITLE
Problems encountered in multistep running under docker

### ISSUE THREAD

**Issue by yzz-cver** [mlflow/mlflow#3153]
The following problem occurs when running the  mlflow run .   command.

2020/07/22 18:07:31 INFO mlflow.projects: === Building docker image docker-example ===
2020/07/22 18:07:31 INFO mlflow.projects: === Created directory /tmp/tmp20yr16p3 for downloading remote URIs passed to arguments of type 'path' ===
2020/07/22 18:07:31 INFO mlflow.projects: === Running command 'docker run --rm -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns:/mlflow/tmp/mlruns -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/3d6b35ed5605417f9cbb18311944eede/artifacts:/home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/3d6b35ed5605417f9cbb18311944eede/artifacts -e MLFLOW_RUN_ID=3d6b35ed5605417f9cbb18311944eede -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:latest python main.py --cphm-csv ./datasets/cd5_3x_curve_feayute_fixed.csv --split-prop 0.8 --n-neighbors 2' in run with ID '3d6b35ed5605417f9cbb18311944eede' === 
No matching run has been found.
Launching new run for entrypoint=load_data and parameters={'cphm_csv': './datasets/cd5_3x_curve_feayute_fixed.csv'}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 578, in _validate_docker_installation
    process.exec_cmd([docker_path, "--help"], throw_on_error=False)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/process.py", line 43, in exec_cmd
    cwd=cwd, universal_newlines=True, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    workflow(cphm_csv, split_prop, n_neighbors)
  File "main.py", line 86, in workflow
    load_data_run = _get_or_run("load_data", {"cphm_csv": cphm_csv}, git_commit)
  File "main.py", line 62, in _get_or_run
    submitted_run = mlflow.run(".", entrypoint, parameters=parameters)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 281, in run
    synchronous=synchronous)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 134, in _run
    _validate_docker_installation()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 580, in _validate_docker_installation
    raise ExecutionException("Could not find Docker executable. "
mlflow.exceptions.ExecutionException: Could not find Docker executable. Ensure Docker is installed as per the instructions at https://docs.docker.com/install/overview/.
2020/07/22 18:07:33 ERROR mlflow.cli: === Run (ID '3d6b35ed5605417f9cbb18311944eede') failed ===

Then I solved the above problem with docker -v command，but the following problems occurred when running the mlflow run . command again

2020/07/22 18:16:06 INFO mlflow.projects: === Building docker image docker-example ===
2020/07/22 18:16:07 INFO mlflow.projects: === Created directory /tmp/tmpj8pfnsvn for downloading remote URIs passed to arguments of type 'path' ===
2020/07/22 18:16:07 INFO mlflow.projects: === Running command 'docker run --rm -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns:/mlflow/tmp/mlruns -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/54904d42eefb4c5089371cc255a6009e/artifacts:/home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/54904d42eefb4c5089371cc255a6009e/artifacts -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -e MLFLOW_RUN_ID=54904d42eefb4c5089371cc255a6009e -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:latest python main.py --cphm-csv ./datasets/cd5_3x_curve_feayute_fixed.csv --split-prop 0.8 --n-neighbors 2' in run with ID '54904d42eefb4c5089371cc255a6009e' === 
No matching run has been found.
2020/07/22 10:16:08 INFO mlflow.projects: === Building docker image docker-example ===
2020/07/22 10:16:08 INFO mlflow.projects: === Created directory /tmp/tmp5__scuob for downloading remote URIs passed to arguments of type 'path' ===
2020/07/22 10:16:08 INFO mlflow.projects: === Running command 'docker run --rm -v /mlflow/tmp/mlruns:/mlflow/tmp/mlruns -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/f4854d7936704a66bc4633e4d3035f2d/artifacts:/home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/f4854d7936704a66bc4633e4d3035f2d/artifacts -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -e MLFLOW_RUN_ID=f4854d7936704a66bc4633e4d3035f2d -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:latest python load_data.py --cphm-csv ./datasets/cd5_3x_curve_feayute_fixed.csv' in run with ID 'f4854d7936704a66bc4633e4d3035f2d' === 
Traceback (most recent call last):
  File "load_data.py", line 41, in <module>
    load_data(cphm_csv)
  File "load_data.py", line 30, in load_data
    with mlflow.start_run() as mlrun:
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 119, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 96, in get_run
    return self._tracking_client.get_run(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 49, in get_run
    return self.store.get_run(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 423, in get_run
    run_info = self._get_run_info(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 442, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run 'f4854d7936704a66bc4633e4d3035f2d' not found
Launching new run for entrypoint=load_data and parameters={'cphm_csv': './datasets/cd5_3x_curve_feayute_fixed.csv'}
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    workflow(cphm_csv, split_prop, n_neighbors)
  File "main.py", line 86, in workflow
    load_data_run = _get_or_run("load_data", {"cphm_csv": cphm_csv}, git_commit)
  File "main.py", line 62, in _get_or_run
    submitted_run = mlflow.run(".", entrypoint, parameters=parameters)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 283, in run
    _wait_for(submitted_run_obj)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 300, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID 'f4854d7936704a66bc4633e4d3035f2d') failed
2020/07/22 18:16:10 ERROR mlflow.cli: === Run (ID '54904d42eefb4c5089371cc255a6009e') failed ===

Can you help me to solve this question?  Thanks!

**Comment by dmatrix** [comment]
@yzz-cver Can you try to install docker on your local machine and try this again?

**Comment by yzz-cver** [comment]
@dmatrix  Yes, I installed docker locally, but the following problems still occur

2020/07/23 09:12:19 INFO mlflow.projects: === Building docker image docker-example ===
2020/07/23 09:12:19 INFO mlflow.projects: === Created directory /tmp/tmpw5wfq4q5 for downloading remote URIs passed to arguments of type 'path' ===
2020/07/23 09:12:19 INFO mlflow.projects: === Running command 'docker run --rm -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns:/mlflow/tmp/mlruns -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/b151ae3ca93345929784ffe5340e5ac1/artifacts:/home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/b151ae3ca93345929784ffe5340e5ac1/artifacts -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -e MLFLOW_RUN_ID=b151ae3ca93345929784ffe5340e5ac1 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:latest python main.py --cphm-csv ./datasets/cd5_3x_curve_feayute_fixed.csv --split-prop 0.8 --n-neighbors 2' in run with ID 'b151ae3ca93345929784ffe5340e5ac1' === 
No matching run has been found.
2020/07/23 01:12:21 INFO mlflow.projects: === Building docker image docker-example ===
2020/07/23 01:12:21 INFO mlflow.projects: === Created directory /tmp/tmp0geivmdh for downloading remote URIs passed to arguments of type 'path' ===
2020/07/23 01:12:21 INFO mlflow.projects: === Running command 'docker run --rm -v /mlflow/tmp/mlruns:/mlflow/tmp/mlruns -v /home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/bf5a0eb44d674068b29d4133e053c410/artifacts:/home/zyz/cphm_mlflow_sklearn_docker/mlruns/0/bf5a0eb44d674068b29d4133e053c410/artifacts -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -e MLFLOW_RUN_ID=bf5a0eb44d674068b29d4133e053c410 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 docker-example:latest python load_data.py --cphm-csv ./datasets/cd5_3x_curve_feayute_fixed.csv' in run with ID 'bf5a0eb44d674068b29d4133e053c410' === 
Traceback (most recent call last):
  File "load_data.py", line 41, in <module>
    load_data(cphm_csv)
  File "load_data.py", line 30, in load_data
    with mlflow.start_run() as mlrun:
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 119, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 96, in get_run
    return self._tracking_client.get_run(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 49, in get_run
    return self.store.get_run(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 423, in get_run
    run_info = self._get_run_info(run_id)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 442, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run 'bf5a0eb44d674068b29d4133e053c410' not found
Launching new run for entrypoint=load_data and parameters={'cphm_csv': './datasets/cd5_3x_curve_feayute_fixed.csv'}
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    workflow(cphm_csv, split_prop, n_neighbors)
  File "main.py", line 86, in workflow
    load_data_run = _get_or_run("load_data", {"cphm_csv": cphm_csv}, git_commit)
  File "main.py", line 62, in _get_or_run
    submitted_run = mlflow.run(".", entrypoint, parameters=parameters)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 283, in run
    _wait_for(submitted_run_obj)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 300, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID 'bf5a0eb44d674068b29d4133e053c410') failed
2020/07/23 09:12:23 ERROR mlflow.cli: === Run (ID 'b151ae3ca93345929784ffe5340e5ac1') failed ===
