### ISSUE TITLE
[SETUP-BUG] Unable to log using mlflow.tensorflow.log_model()

### ISSUE THREAD

**Issue by naman-mehta** [mlflow/mlflow#3226]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution :Ubuntu 18.04
- **MLflow installed from :source
- **MLflow version :1.10

I am trying to log the TensorFlow based Deeplab model using mlflow.tensorflow.log_model(). It takes the following 3 arguments.
1-tf_saved_model_dir
2-tf_meta_graph_tags
3-tf_signature_def_key
1-tf_saved_model_dir - For the first argument- deeplab models are saved in .ckpt format but mlflow.tensorflow.log_model() expects in .pb format.
So I used export_model.py https://github.com/tensorflow/models/blob/master/research/deeplab/export_model.py to convert to pb format.
Command used-
python3 deeplab/export_model.py \
  --logtostderr \
  --model_variant="xception_65" \
  --num_classes=151 \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --crop_size=513 \
  --crop_size=513 \
  --checkpoint_path='/home/.../training_dir/model.ckpt-100' \
  --export_path='/home/.../training_dir/export_model/saved_model.pb' \
  --save_inference_graph=True
2-tf_meta_graph_tags -
For conversion of checkpoints to pb export_model.py uses freeze_graph_with_def_protos() function of /tensorflow/python/tools/freeze_graph.py. The arguments saved_model_tags is set to None.
But when I try
mlflow.tensorflow.log_model(tf_saved_model_dir= tf_saved_model_dir ,tf_meta_graph_tags= None , tf_signature_def_key=None , artifact_path = export_path)
I get the error -
TypeError: 'NoneType' object is not iterable
Or
mlflow.tensorflow.log_model(tf_saved_model_dir= tf_saved_model_dir ,tf_meta_graph_tags= tag_constants.SERVING , tf_signature_def_key=None , artifact_path = export_path)
RuntimeError: MetaGraphDef associated with tags serve could not be found in SavedModel.
Is tf_meta_graph_tags and saved_model_tags different.
how to find tf_meta_graph_tags.
I tried this
from tensorflow.python.tools import freeze_graph
tf_saved_model_dir = '/home/.../deeplab/training_dir/export_model'
print(freeze_graph._parse_input_meta_graph_proto(tf_saved_model_dir+'/inference_graph.pbtxt',input_binary= False))
Got this error-
google.protobuf.text_format.ParseError: 1:1 : Message type "tensorflow.MetaGraphDef" has no field named "node"
3-tf_signature_def_key- Please suggest how to find this argument. for eg- in few other codes other than deeplab it is tf_signature_def_key=’serving_default’.
But I am not sure it is the same for my model.
What I have understood till now is that I have to use saved_model_cli to know tags and key from my model. Am i right?
If yes how to use saved_model_cli here.
If I am wrong please suggest ways to know tf_meta_graph_tags and tf_signature_def_key.
I have also followed this https://medium.com/analytics-vidhya/mlflow-logging-for-tensorflow-37b6a6a53e3c approach.
to log model checkpoints as artifacts which can be a workaround to mlflow.tensorflow.log_model().

**Comment by harupy** [comment]
@naman-mehta 

> I get the error - TypeError: 'NoneType' object is not iterable

Can you provide the whole stack trace?

**Comment by naman-mehta** [comment]
@harupy 
Thanks for your time. 
The stack trace for the whole error is-
I get the error - TypeError: 'NoneType' object is not iterable
Please have a look here-
Traceback (most recent call last):
  File "train.py", line 485, in <module>
    tf.app.run()
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 481, in main
    mlflow.tensorflow.log_model(tf_saved_model_dir= tf_saved_model_dir ,tf_meta_graph_tags=None , tf_signature_def_key='predict' , artifact_path = export_path)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/utils/annotations.py", line 58, in wrapper
    return func(**kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 151, in log_model
    input_example=input_example)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/models/model.py", line 154, in log
    **kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/utils/annotations.py", line 58, in wrapper
    return func(**kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 218, in save_model
    tf_signature_def_key=tf_signature_def_key)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 262, in _validate_saved_model
    tf_signature_def_key=tf_signature_def_key)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 370, in _load_tensorflow_saved_model
    export_dir=tf_saved_model_dir)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 317, in get_meta_graph_def_from_tags
    if set(meta_graph_def.meta_info_def.tags) == set(tags):
TypeError: 'NoneType' object is not iterable
2020/08/05 06:39:56 ERROR mlflow.cli: === Run (ID '2cce01f12269456d9eee171b10b09bfc') failed ===

**Comment by harupy** [comment]
@naman-mehta What happens if you pass an empty list `[]` to `tf_meta_graph_tags`?

**Comment by naman-mehta** [comment]
Thanks @harupy  It is an awesome suggestion. It is not None rather it is an empty list which is an iterable also. 
i.e. why my saved_model_cli gives following output-
saved_model_cli show --dir ~/naman_workspace/mlflow_docker_deeplab/training_dir/export_model/ 
The given SavedModel contains the following tag-sets:


This solves the half of the issue.
The other half is tf_signature_def_key is also a required argument to mlflow.tensorflow.log_model().
I think usually MetaGraphDef with tag-set: 'something here' contains the following SignatureDefs:

saved_model_cli show --dir ~/naman_workspace/mlflow_docker_deeplab/training_dir/export_model/ --all

MetaGraphDef with tag-set: '' contains the following SignatureDefs:
Traceback (most recent call last):
  File "/home/annotation/venv_tf_1/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 691, in show
    _show_all(args.dir)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 278, in _show_all
    signature_def_map = get_signature_def_map(saved_model_dir, tag_set)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 323, in get_signature_def_map
    meta_graph = saved_model_utils.get_meta_graph_def(saved_model_dir, tag_set)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_utils.py", line 120, in get_meta_graph_def
    ' could not be found in SavedModel')
RuntimeError: MetaGraphDef associated with tag-set  could not be found in SavedModel
I tried 
1- tf_signature_def_key='' 
which gives error- mlflow.exceptions.MlflowException: Could not find signature def key . Available keys are: []
2-tf_signature_def_key=None
which gives error-TypeError: None has type NoneType, but expected one of: bytes, unicode
So what should I pass to  'tf_signature_def_key' as there are no tag_set.

**Comment by harupy** [comment]
@naman-mehta 

> This solves the half of the issue.

Just because it doesn't raise an error doesn't mean it's a correct value.

**Comment by harupy** [comment]
@naman-mehta 
Can you try pass these values to `log_model`?

```
from tensorflow.python.saved_model import tag_constants

tf_meta_graph_tags=[tag_constants.SERVING],
tf_signature_def_key='predict'
```

**Comment by naman-mehta** [comment]
@harupy 
```
from tensorflow.python.saved_model import tag_constants

tf_meta_graph_tags=[tag_constants.SERVING],
tf_signature_def_key='predict'
```
For the first time I tried these values only. This doesn't work as there are no tags in my tf_meta_graph_tags.
This gives the following error-
```
Traceback (most recent call last):
  File "train.py", line 485, in <module>
    tf.app.run()
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 481, in main
    mlflow.tensorflow.log_model(tf_saved_model_dir= tf_saved_model_dir ,tf_meta_graph_tags=[tag_constants.SERVING] , tf_signature_def_key='predict', artifact_path = export_path)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/utils/annotations.py", line 58, in wrapper
    return func(**kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 151, in log_model
    input_example=input_example)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/models/model.py", line 154, in log
    **kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/utils/annotations.py", line 58, in wrapper
    return func(**kwargs)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 218, in save_model
    tf_signature_def_key=tf_signature_def_key)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 262, in _validate_saved_model
    tf_signature_def_key=tf_signature_def_key)
  File "/home/annotation/.local/lib/python3.6/site-packages/mlflow/tensorflow.py", line 370, in _load_tensorflow_saved_model
    export_dir=tf_saved_model_dir)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/home/annotation/venv_tf_1/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 327, in get_meta_graph_def_from_tags
    "\navailable_tags: " + str(available_tags))
RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [set()]
```
the output from saved_cli is 
saved_model_cli show --dir ~/naman_workspace/mlflow_docker_deeplab/training_dir/export_model/
```
The given SavedModel contains the following tag-sets:

```
