### ISSUE TITLE
[BUG] hyperparam examples failure - could not read from remote repository - windows 10 - mlflow 1.10.0

### ISSUE THREAD

**Issue by extrospective** [mlflow/mlflow#3281]
- [ ] Yes. I can contribute a fix for this bug independently.
- [ x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Window 10
- **MLflow installed from (source or binary)**: both
- **MLflow version (run ``mlflow --version``)**: 1.10.0
- **Python version**: 3.7.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:mlflow run -e random --experiment-id 1 examples/hyperparam

### Describe the problem
Following steps for tutorial: https://github.com/mlflow/mlflow/tree/master/examples/hyperparam
Steps prior to this step succeed, including mlflow run -e train...
However, steps such as -e random, -e gpyopt, and -e hyperopt all fail with similar outcome.

Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

### Code to reproduce issue
(After creating experiment-id 1...)
```
mlflow run -e random --experiment-id 1 examples/hyperparam
```

### Other info / logs
When command is executed, about 3 call stacks are emitted.  Each roughly looks like:

```
2020/08/15 10:38:17 INFO mlflow.projects: === Asynchronously launching MLflow run with ID 15ac8310e9e84a4ea8811c80f3b7e492 ===
2020/08/15 10:38:19 INFO mlflow.projects.utils: === Fetching project from C:\repo\mlflow\examples\hyperparam into C:\Users\MANDER~1\AppData\Local\Temp\tmpyee_f5st ===
Traceback (most recent call last):
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mandersen\Anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\cli.py", line 133, in run
    run_id=run_id
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\projects\__init__.py", line 281, in run
    synchronous=synchronous)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\projects\__init__.py", line 105, in _run
    work_dir = fetch_and_validate_project(uri, version, entry_point, parameters)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\projects\utils.py", line 106, in fetch_and_validate_project
    work_dir = _fetch_project(uri=uri, version=version)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\projects\utils.py", line 139, in _fetch_project
    _fetch_git_repo(parsed_uri, version, dst_dir)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\mlflow\projects\utils.py", line 164, in _fetch_git_repo
    origin.fetch()
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\git\remote.py", line 797, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\git\remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "c:\users\mandersen\anaconda3\envs\mlflow-2f1503274a33c2abb9b8f98ec4692256aa959263\lib\site-packages\git\cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: 'C:/repo/mlflow/examples/hyperparam' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```

Possible areas of investigation:
* Type of installation - pip
```
(py37) C:\repo\mlflow>conda list | grep mlflow
mlflow                    1.10.0                   pypi_0    pypi
```

* Where am I running this from:
a. I installed mlflow with pip
b. I cloned the mlflow repo -- fresh clone
c. I cd into the top level directory of my mlflow repo clone (c:\repo\mlflow) and from there I run the tutorial commands for examples/hyperparam

* Git version: 2.28.0.windows.1

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
dup of #2824
