### ISSUE TITLE
UUID dependency breaks python 3 under AWS linux

### ISSUE THREAD

**Issue by antonpaquin** [mlflow/mlflow#330]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon linux deep learning AMI 12.0 (like CentOS)
- **MLflow installed from (source or binary)**: source (PyPI)
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.5.0
- **Python version**: Python 3.6.6
- **npm version (if running the dev UI): N/A
- **Exact command to reproduce**: python -c "import mlflow"

### Describe the problem
```pip install mlflow``` also installs uuid==1.30 (which breaks under python3)

The default "uuid" library is included in the python standard library. On the AWS instance, the installed version shadows the default, and includes syntax which is only valid in python2. 
On the computer I'm connecting to the instance from, the same script does not produce any errors, but ```uuid.__file__``` points to a standard library version and not the packaged 1.30

### Source code / logs
Full reproduction from a newly created instance:
```
source activate tensorflow_p36
virtualenv env --system-site-packages --python=$(which python) env
source env/bin/activate
pip install mlflow
python -c "import mlflow"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/__init__.py", line 33, in <module>
    import mlflow.projects as projects  # noqa
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 17, in <module>
    import mlflow.tracking as tracking
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/tracking/__init__.py", line 7, in <module>
    from mlflow.tracking.service import MLflowService, get_service
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/tracking/service.py", line 13, in <module>
    from mlflow.tracking.utils import _get_store
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/tracking/utils.py", line 8, in <module>
    from mlflow.store.file_store import FileStore
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/mlflow/store/file_store.py", line 3, in <module>
    import uuid
  File "/home/ec2-user/scratch/env/lib/python3.6/site-packages/uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax
```

**Comment by antonpaquin** [comment]
My current workaround is to run ```pip uninstall uuid``` after installing mlflow

**Comment by vpavlin** [comment]
Same issue here when we tried to use this with JupyterHub, workaround as discribed by @antonpaquin
