### ISSUE TITLE
[BUG] Accidentally clicking on large previewable artifacts causes the web UI to hang

### ISSUE THREAD

**Issue by patrick-plutoflume** [mlflow/mlflow#3384]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Chrome on Amazon Linux 2
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.10.0
- **Python version**: 3.6.10
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: Log a large (~10MB) JSON artifact and attempt to preview through Chrome

### Describe the problem
Whenever I accidentally click on an **large** artefact (i.e. 10MB) that's in a previewable file format in the web UI, the page becomes unresponsive. I would prefer it if these files were truncated or not considered previewable.

### Code to reproduce issue
N/A

### Other info / logs
I'm unfortunately not able to export logs or files from the machine.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ankit-db** [comment]
Thanks for filing this @patrick-plutoflume - I've set up an action item to take a look at this soon

**Comment by benglewis** [comment]
@ankit-db I don't like to bug, but it has been 4 years: Is there any update here?

**Comment by ankit-db** [comment]
That’s a great reason to bug! I do believe this has been fixed though with the new artifact viewer, but I no longer work on this. 

@BenWilson2 is this issue still relevant?

**Comment by BenWilson2** [comment]
It hopefully shouldn't be an issue any longer :) 
However, @benglewis, if you have a pseudo repro example (file size, file content type) as a guide for where you see a performance issue, we'll be glad to investigate and try to determine how to more optimally display the content. cc @daniellok-db

**Comment by shmuelyo** [comment]
Hey, I encountered this issue as well.
Here's a toy example that recreates the hanging problem:
```
import mlflow
import numpy as np
import pandas as pd

mlflow.set_tracking_uri("http://localhost:5000")
# Generate a large random pandas DataFrame
num_rows=100_000
num_columns=10
# Create random column names
column_names = [f'col_{i}' for i in range(num_columns)]
# Generate random data
data = np.random.random(size=(num_rows, num_columns))
# Convert to DataFrame
df = pd.DataFrame(data, columns=column_names)
with mlflow.start_run():
    mlflow.log_table(df, "random_df.json")
```
And literally nothing other then navigating to the artifacts tab and clicking on the table artifact causes the browser to freeze.

**Comment by benglewis** [comment]
@BenWilson2 I work with @shmuelyo and his example reproduces the issue easily. I would be happy to get some response on this. Unfortunately it makes the table previews much less usable

If necessary, I would be happy to consider reviewing the code and try to fix it if I can

Are you using a virtualized list? If not, DOM issues with too many elements seems like the classic cause

**Comment by daniellok-db** [comment]
Thanks for offering to take a look @benglewis, the relevant component is:

https://github.com/mlflow/mlflow/blob/3f808b6ab7680555a91f962f998425b80dc9fc93/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedTableView.tsx#L48

just briefly looking at the code, it seems the table should be paginated to prevent the issue of too many elements, but maybe something's going wrong there

**Comment by benglewis** [comment]
@daniellok-db Having looked at the issue, it seems like we chose to use `log_table` because `log_inputs` does not preview the data at all or show a count of the number of columns and that `log_table` doesn't work well with large files (maybe the 50MB preview limit is too high and it should be 1MB or something). I think that I will consider implementing a preview of the first and last rows and the column count, a-la, the `pandas` preview of a DataFrame in a Jupyter notebook. Is this something that you would consider merging?

**Comment by asaff1** [comment]
I'm also affected by this bug. I must say, this is also a backend issue, not just UI. Clicking for example on a large `input-example.json` in the UI, cause it to freeze, and also cause the server to error.
This is the log I'm seeing in the server
```
[2024-12-26 09:33:03 +0000] [19] [INFO] Booting worker with pid: 19
[2024-12-26 09:33:03 +0000] [20] [INFO] Booting worker with pid: 20
[2024-12-26 09:33:03 +0000] [21] [INFO] Booting worker with pid: 21
[2024-12-26 09:33:03 +0000] [22] [INFO] Booting worker with pid: 22
[2024-12-26 13:14:01 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:20)
[2024-12-26 13:14:01 +0000] [20] [ERROR] Error handling request /static-files/static/js/main.d78045af.js.map
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 180, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 393, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 383, in sendfile
    self.sock.sendfile(respiter.filelike, offset=offset, count=nbytes)
  File "/usr/local/lib/python3.10/socket.py", line 484, in sendfile
    return self._sendfile_use_sendfile(file, offset, count)
  File "/usr/local/lib/python3.10/socket.py", line 387, in _sendfile_use_sendfile
    sent = os_sendfile(sockno, fileno, offset, blocksize)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-12-26 13:14:01 +0000] [20] [INFO] Worker exiting (pid: 20)
[2024-12-26 13:14:01 +0000] [361] [INFO] Booting worker with pid: 361
```

The problematic API call is `/get-artifact?path=mlflow-model%2Finput_example.json&run_uuid=3f11ea45f9904d08805b184dfaf7ef61`

I see two issues with it:
1. The API server should check the file size, if it is previewable and more than 5MB, it should not show it or return it truncated (not sure if all object storages support that)
2. Anyway, there should be an option for the API server not to download the file at all, on S3 for example, it should generate a presigned URL and let the UI fetch the file directly from S3. It is much more efficient.

**Comment by soonjune** [comment]
Any update on this issue? I think it commonly happens when you infer signature with input_example with a large size tensor.

**Comment by BenWilson2** [comment]
Hi folks, sorry for the delay here. We'll be looking into a permanent fix to enhance UI stability here with a target for having this fix available in MLflow 2.21.0. Appreciate the patience!

**Comment by benglewis** [comment]
@BenWilson2 @daniellok-db Is there some way that I can contribute? What do you think about the `pandas`-style preview that would show the first and last rows and the columns?
