### ISSUE TITLE
How to log a custom model as artifact when it is run remotey from GitHub

### ISSUE THREAD

**Issue by MatthiasHerp** [mlflow/mlflow#3396]
I've stored my model in Github with MLProject so that others may run it in various variations. Now I would like to log the models created by runs as artifacts so that users can load them with MLModel. As my model is custom this is not as simple as with flavors such as spark. 
I first saved and loaded the model locally to make sure my Environment, model and artifact Code works.
Now I want to include the Login of the model as part of the MLProject run from GitHub.
As there is no example in the documentation I know of, I wanted to ask for help and suggest that this may be a good addition to the documentation or examples.

In Terms of Code I wrote the follwing inside the mlrun at the end:

#Model depending on the Parameters specified in the Project run
**ETS_Exogen = ETS_Exogen(params=res.x, before=before,after=after) #taking parameters from the model**

#logging the model with the previously defined model, evironment and artifacts
**mlflow.pyfunc.log_model(python_model=ETS_Exogen, conda_env=conda_env, artifacts=artifacts)**

1. Does **mlflow.pyfunc.log_model** automatically log the model into the artifacts of the runs or do I Need to define an artifact_path?
2. Should I rather use **mlflow.pyfunc.save_model** ?
3. I defined the artifacts paths so that they would be gathered from the GitHub repository as follows: 

**artifacts = {
"exogen_variables": os.path.join(os.path.dirname(os.path.abspath(__file__)), "exogen_variables.csv")
 }**

Is this correct?

Thanks for any help, tipp or link to an example I missed.

Links to Documentation on custom Models:
https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#pyfunc-create-custom-workflows

**Comment by harupy** [comment]
@MatthiasHerp Thanks for filing this.

> Is this correct?

Did this work or not?

**Comment by MatthiasHerp** [comment]
The Idea is that anyone can run the MLProject with the URI to create a model.  So when a user runs the MLProject the run stores the created model inside the artifacts of the run created locally. Then the user can acess the model for further use locally by loading it from he artifact Folder of the run.
In a sense similar to logging a model run from an example on Github.

**Comment by harupy** [comment]
@MatthiasHerp Just to confirm, you don't store your model in GitHub, correct?

**Comment by MatthiasHerp** [comment]
correct. I run the Project from GitHub and then want to store the model in the run Folder as an artifact

**Comment by harupy** [comment]
why don't you try to run your project via the command below and see if it works?

```
mlflow run https://github.com/MatthiasHerp/ETS_Ex_BA_MLFlow.git
```

**Comment by MatthiasHerp** [comment]
My Project is running. I just want to additionally store the created model every time I run the Project as the model is Always different since it depends on the Parameters i run the model with. Does that make sense?

I'll look into that:

> why don't you try running your project with the command below and see if it works?
> mlflow run https://github.com/MatthiasHerp/ETS_Ex_BA_MLFlow.git ...

But I dont think it is related to storing a model right?

**Comment by harupy** [comment]
> But I dont think it is related to storing a model right?

It is if your `train.py` logs a model.

**Comment by MatthiasHerp** [comment]
Yes. But my Problem is with logging the custom model. I dont seem to get the python script right.
How would you log a custom model as an artifact of a run?

**Comment by harupy** [comment]
https://github.com/MatthiasHerp/ETS_Ex_BA_MLFlow/blob/master/train.py#L672

Doesn't this line log your model?

**Comment by MatthiasHerp** [comment]
Yes it should but it doesn't, I'm getting an error back. So I'm wondering if I made made any mistake in logging the model or defining the artifacts

**Comment by harupy** [comment]
Can you provide the stacktrace when you got an error?

**Comment by MatthiasHerp** [comment]
Yes, I saved the stack trace as a MLFLow parameter in an exception.

The stack trace:
Traceback (most recent call last): File "train.py", line 677, in <module> mlflow.pyfunc.save_model(python_model=ETS_Exogen, conda_env=conda_env, artifacts=artifacts) TypeError: save_model() missing 1 required positional argument: 'path' 

So I tried defining a path. As i want to store the model locally in the artifact Folder of the run I used the following path:

#saving the run id to create path
run_id = run.info.run_id
#saving model in the artifact folder of the run
mlflow.pyfunc.save_model(str("runs:/"+run_id+"/artifact/model"),python_model=ETS_Exogen, conda_env=conda_env, artifacts=artifacts)

I also tried different paths such as:

str("runs:/"+run_id+"/model") 

"/model" #with and without dot at the beginning to signal a relativ path

"/artifact/model" #with and without dot at the beginning to signal a relativ path

The stack trace error was always:

Traceback (most recent call last): File "train.py", line 680, in <module> mlflow.pyfunc.log_model(str("runs:/"+run_id+"/artifacts/model"),python_model=ETS_Exogen, conda_env=conda_env, artifacts=artifacts) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\pyfunc\__init__.py", line 998, in log_model input_example=input_example, File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\models\model.py", line 161, in log mlflow.tracking.fluent.log_artifacts(local_path, artifact_path) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\tracking\fluent.py", line 328, in log_artifacts MlflowClient().log_artifacts(run_id, local_dir, artifact_path) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\tracking\client.py", line 290, in log_artifacts self._tracking_client.log_artifacts(run_id, local_dir, artifact_path) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 288, in log_artifacts self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 57, in log_artifacts mkdir(artifact_dir) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\utils\file_utils.py", line 111, in mkdir raise e File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\site-packages\mlflow\utils\file_utils.py", line 108, in mkdir os.makedirs(target) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\os.py", line 211, in makedirs makedirs(head, exist_ok=exist_ok) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\os.py", line 211, in makedirs makedirs(head, exist_ok=exist_ok) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\os.py", line 211, in makedirs makedirs(head, exist_ok=exist_ok) File "C:\Users\mah\Anaconda3\envs\mlflow-f4a9c66cbd381a72f7946866fb22ad9ff7f69fb1\lib\os.py", line 221, in makedirs mkdir(name, mode) OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\mah\\mlruns\\0\\54c00e8b874747a9b221da428ab53efe\\artifacts\\runs:' 

Which tells me that the path to log the model was incorrect

1. How would you set the path?

Heres the link to the documentation on the Topic of paths:

**Comment by harupy** [comment]
Have you tried `mlflow.pyfunc.log_model(artifact_path="model", ...)` which log a specified model in the active run?

**Comment by MatthiasHerp** [comment]
@harupy That was what I was missing. Thank you. Know the model logs.

Do you have any Tipp for my second Issue?

**Comment by harupy** [comment]
This SO post might be helpful: https://stackoverflow.com/a/23464217/6943581

**Comment by MatthiasHerp** [comment]
@harupy , that worked. Thank you very much :)
