### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TallakBergheim** [mlflow/mlflow#3397]
###Willingness to contribute
- [x ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows Server 2016 Standard 64 bit 
- **MLflow installed from (source or binary)**: Installed with Anaconda GUI
- **MLflow version (run ``mlflow --version``)**:  
Trying this, but getting this error message: 
Fatal error in launcher: Unable to create process using '"d:\bld\mlflow_1599218365944\_h_env\python.exe"  "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\Scripts\mlflow.exe" --version': The system cannot find the file specified.
But Anaconda says mlflow & mlflow-ui-dbg 1.11.0
- **Python version**: 3.8
- **npm version, if running the dev UI**: ? 
- **Exact command to reproduce**: See below

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.
When running the train() function of the train.ipnb in https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine , the tracking API returns an error message when trying to log to the tracking server set up with a mssql database. This issue does not happen when logging to a local sqlite database. 

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Initialize mlflow tracking server, using local artifact store and mssql server: 
python "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\Scripts\mlflow.exe" server --backend-store-uri mssql+pymssql://@<mssql> --default-artifact-root file://E:/MyFolder/MLFlow/ --host 0.0.0.0

Use the train.ipynb in https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine
Set the mlflow.set_tracking_uri('http://<local-computer-name>:5000')
Run train(0.3, 0.7)

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Error message in the notebook: 
Elasticnet model (alpha=0.300000, l1_ratio=0.700000):
  RMSE: 0.774713648356711
  MAE: 0.6079678532556209
  R2: 0.14961391810397706
2020/09/07 16:10:01 ERROR mlflow.utils.rest_utils: API request to http://<local-computer-name>:5000/api/2.0/mlflow/runs/get failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

(...)

Messages in the Tracking server terminal: 
Serving on http://<local-computer-name>:5000
C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\sqlalchemy\dialects\mssql\pymssql.py:61: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  module = __import__("pymssql")
2020/09/07 12:16:01 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\google\protobuf\internal\python_message.py", line 713, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\google\protobuf\internal\type_checkers.py", line 171, in CheckValue
    raise TypeError(message)
TypeError: Decimal('1599473751897') has type <class 'decimal.Decimal'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\mlflow\server\handlers.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\mlflow\server\handlers.py", line 445, in _get_run
    response_message.run.MergeFrom(_get_tracking_store().get_run(run_id).to_proto())
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\mlflow\entities\run.py", line 39, in to_proto
    run.info.MergeFrom(self.info.to_proto())
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\mlflow\entities\run_info.py", line 146, in to_proto
    proto.start_time = self.start_time
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    raise TypeError(
TypeError: Cannot set mlflow.RunInfo.start_time to Decimal('1599473751897'): Decimal('1599473751897') has type <class 'decimal.Decimal'>, but expected one of: (<class 'int'>,)
2020/09/07 12:16:05 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\google\protobuf\internal\python_message.py", line 713, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\lib\site-packages\google\protobuf\internal\type_checkers.py", line 171, in CheckValue
    raise TypeError(message)
TypeError: Decimal('1599473751897') has type <class 'decimal.Decimal'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:
(...)
This issue seems a bit similar to https://github.com/mlflow/mlflow/issues/1165 

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [? ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [? ] `area/windows`: Windows support

**Comment by harupy** [comment]
@TallakBergheim Thanks for filing this.

> TypeError: Decimal('1599473751897') has type <class 'decimal.Decimal'>, but expected one of: (<class 'int'>,)

Looks like timestamp is stored as decimal instead of integer.

**Comment by TallakBergheim** [comment]
This might be the case. I have used a standard MLFlow command to create the database tables:
python "C:\ProgramData\Anaconda3\envs\UtvPy_38_MLFlow\Scripts\mlflow.exe" server --backend-store-uri mssql+pymssql://<my-msssql-database> --default-artifact-root file://E:/Prosjekter/MLFlow/ --host 0.0.0.0

The database runs table looks like this: 
![image](https://user-images.githubusercontent.com/3862760/92450712-0d72e280-f1bc-11ea-9e63-1913d21b6568.png)

**Comment by harupy** [comment]
@TallakBergheim Can you run code like below using against the database table and check the type of `start_time`?

Example in http://www.pymssql.org/pymssql_examples.html#iterating-through-results:

```python
conn = pymssql.connect(server, user, password, "tempdb")
cursor = conn.cursor()
cursor.execute('SELECT * FROM persons WHERE salesrep=%s', 'John Doe')

for row in cursor:
    print('row = %r' % (row,))

conn.close()
```

**Comment by TallakBergheim** [comment]
> @TallakBergheim Can you run code like below using against the database table and check the type of `start_time` pymssql returns?
> 
> Example in http://www.pymssql.org/pymssql_examples.html#iterating-through-results:
> 
> ```python
> conn = pymssql.connect(server, user, password, "tempdb")
> cursor = conn.cursor()
> cursor.execute('SELECT * FROM persons WHERE salesrep=%s', 'John Doe')
> 
> for row in cursor:
>     print('row = %r' % (row,))
> 
> conn.close()
> ```
Running this with _cursor.execute('SELECT start_time FROM dbo.runs')_ yields
![image](https://user-images.githubusercontent.com/3862760/92524644-bb18dc80-f222-11ea-8867-53105d2b1827.png)
So, yes, start_time is returned as a decimal. 
Do you believe the error is on the definition of the SQL table, or in the interface between mssql and MLFlow? Anything else I can investigate?

**Comment by TallakBergheim** [comment]
Is there anything else I can investigate here?

**Comment by TallakBergheim** [comment]
I have recently upgraded to mlflow 1.12.1 at the tracking server and in the environment running experiments, with the same results; start_time is treated as Decimal instead of Int. 
![image](https://user-images.githubusercontent.com/3862760/100608251-6a3def00-330c-11eb-9f19-91bb60c70970.png)

I wish I could have fixed this, but I fear the learning curve will be too steep for me at this point. Is there anything I can do here,  @harupy ?
