### ISSUE TITLE
[BUG] Default experiment is not created when root directory already exists

### ISSUE THREAD

**Issue by dniku** [mlflow/mlflow#3429]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes

All versions are irrelevant, since the problem is in current `master`.

- **Exact command to reproduce**:

1. `mkdir /tmp/mlruns`
2. Run the following script:

```python
import mlflow

mlflow.set_tracking_uri(f'file:/tmp/mlruns')
mlflow.log_param("my int param", 6)
```

### Describe the problem

`FileStore` [creates a default experiment](https://github.com/mlflow/mlflow/blob/d743a40426d5dedbde395a4e6bbdeebadbccd4dc/mlflow/store/tracking/file_store.py#L138-L142) only if `self.root_directory` does not exist yet. However, if it does exist but is empty, this leads to an exception, which is difficult to interpret for those who encounter MLFlow for the first time:

```python
Traceback (most recent call last):
  File "test_mlflow.py", line 4, in <module>
    mlflow.log_param("my int param", 6)
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 175, in log_param
    run_id = _get_or_start_run().info.run_id
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 416, in _get_or_start_run
    return start_run()
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 141, in start_run
    active_run_obj = MlflowClient().create_run(
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/client.py", line 84, in create_run
    return self.store.create_run(
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/store/file_store.py", line 360, in create_run
    experiment = self.get_experiment(experiment_id)
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/store/file_store.py", line 270, in get_experiment
    experiment = self._get_experiment(experiment_id)
  File "/home/ser/.miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/store/file_store.py", line 245, in _get_experiment
    raise MlflowException("Could not find experiment with ID %s" % experiment_id,
mlflow.exceptions.MlflowException: Could not find experiment with ID 0
```

Perhaps `FileStore.__init__()` should create a default experiment if it is not present yet, instead of only creating it if the directory itself does not exist?

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

Guys, your issue template is really long, this somewhat discourages reporting and contributions :/

**Comment by harupy** [comment]
@dniku Thanks for filing this issue. I was able to reproduce the issue.

**Comment by ash-shaik** [comment]
@harupy I can take this up. 
Update FileStore to carve out the step to create the experiment from under condition of existence of root directory. 
Creating root directory when it does not exists remains as is.

do you have any opinions/suggestions/guidance on the approach and next steps ?
