### ISSUE TITLE
[BUG] mlflow <= 1.10.0 requires global set_tracking_uri when downloading artifacts from mlflow

### ISSUE THREAD

**Issue by kparaju** [mlflow/mlflow#3445]
This bug is fixed in mlflow==1.11.0 but exists in 1.5.0 to 1.10.0. I wanted to file this to document the issue for anyone else looking and can't upgrade to 1.11.0 yet. I believe https://github.com/mlflow/mlflow/pull/3360 fixes the issue. 

### System information
- OS Platform and Distribution: OSX
- MLflow installed from: pip
- MLflow versions: 1.5.0 to 1.10.0  (haven't tested pre-1.5.0)
- Python version: 3.7 and 3.8

### Describe the problem
Python MLFlow library cannot download artifacts from databricks if the tracking URI is not set via `mlflow.set_tracking_uri` which sets the tracking uri globally instead of for just that instance of the client. If you run the code below, you will get an exception on the download_artifacts line. Uncomment the two commented lines and it will work. 

### Code to reproduce issue
mlflow_test.py
```
from mlflow.tracking import MlflowClient

# Change me
experiment_id = 99999999
run_id = 'f999999999999999999999999999999999'
sample_artifact = 'artifact.json'

client = MlflowClient('databricks')
# import mlflow
# mlflow.set_tracking_uri('databricks')
client.search_runs(experiment_id, max_results=1)
client.download_artifacts(run_id, sample_artifact)
```

Exception:
```
Traceback (most recent call last):
  File "mlflow_test.py", line 10, in <module>
    client.download_artifacts('f999999999999999999999999999999999', 'artifact.json')
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 306, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 300, in download_artifacts
    artifact_repo = get_artifact_repository(artifact_root)
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 102, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 71, in get_artifact_repository
    return repository(artifact_uri)
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 188, in dbfs_artifact_repo_factory
    return DbfsRestArtifactRepository(cleaned_artifact_uri)
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 36, in __init__
    self.get_host_creds = _get_host_creds_from_default_store()
  File "/Users/kparajuli/repos/my_cool_project/venv/lib/python3.8/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 153, in _get_host_creds_from_default_store
    raise MlflowException('Failed to get credentials for DBFS; they are read from the ' +
mlflow.exceptions.MlflowException: Failed to get credentials for DBFS; they are read from the Databricks CLI credentials or MLFLOW_TRACKING* environment variables.

```

### Other info / logs
The right env vars exist:
```
(venv) ➜  env | grep DATABRICKS
DATABRICKS_TOKEN=dapi9999
DATABRICKS_HOST=https://bla.cloud.databricks.com/
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

**Comment by kparaju** [comment]
Closing this as it's an informational bug for anyone googling and a workaround is already supplied (use global set_tracking_uri)
