### ISSUE TITLE
I am using machine A to set up tracking server on machine B, but mlflow.set_tracking_uri() gives following error.

### ISSUE THREAD

**Issue by nakul3112** [mlflow/mlflow#3450]
So mlflow has a function set_tracking_uri(), where we can pass http/https URL of the tracking server as an argument. However, I dont have clue from the mlflow documents of the proper steps to start the tracking server. I am using mlflow with Nvidia's odth retinanet repository ```https://github.com/NVIDIA/retinanet-examples/```

 Here are the commands I use:

  1) `In terminal 1`:  mlflow server --host 0.0.0.0
  2) `In terminal 2`:  python main.py train --args1 --args2 -- 

However, I end up getting this issue .
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 244, in <module>
    main()
  File "main.py", line 238, in main
    worker(0, args, 1, model, state)
  File "main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/home/nakul/retinanet_pytorch/retinanet/train.py", line 33, in train
    with mlflow.start_run():
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 159, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 137, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 95, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 145, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 52, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 153, in call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 78, in http_request
    max_rate_limit_interval, url=url, headers=headers, verify=verify, **kwargs
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 57, in request_with_ratelimit_retries
    response = requests.request(**kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.1.20.152', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83bc22ceb8>: Failed to establish a new connection: [Errno 111] Connection refused',))

I kindly request to post step-by-step guide about
1) What modifications to make in files other than setting set_tracking_uri()
2)  what commands to use to start the tracking server

Looking forward to seeing the solution soon. Thanks

**Comment by ducthienbui97** [comment]
Seem like you can't access the `10.1.20.152` machine, probably not mlflow bug but just our network setting.
Are you able to access `10.1.20.152:5000` in your browser?

**Comment by nakul3112** [comment]
@ducthienbui97  So here is the thing. 10.1.20.152 is machine B. I have mlflow setup on machine A. So I wonder, if I am doing right thing by starting `mlflow server`, and then the `python command` in machine A? Because, as per the mlflow documentation, just setting the remote server through this one function mlflow.set_tracking_uri() should work, right?

Yes, I can access 10.1.20.152 through ssh port forwarding.

Thanks.

**Comment by ducthienbui97** [comment]
> So I wonder, if I am doing right thing by starting mlflow server, and then the python command in machine A
so you start your server in machine A?
`mlflow.set_tracking_uri` set where the tracking server is, it expect you already have the tracking server running at that uri. So if you want the tracking server in machine B, then you have to start the server in machine B
>  I can access 10.1.20.152 through ssh port forwarding.
But access `10.1.20.152:5000` in your browser?

**Comment by nakul3112** [comment]
@ducthienbui97  I was able to solve the above error, I was doing the things wrongly.
The correct way I think is : 1) Start `mlflow-server` command on the machine which you want as tracking server (Machine B)
2) Run `python main.py --args --args` command from another machine(Machine A).

But, now I end up with another sort of Connection error. ```File "main.py", line 244, in <module>
    main()
  File "main.py", line 238, in main
    worker(0, args, 1, model, state)
  File "main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/home/nakul/retinanet_pytorch/retinanet/train.py", line 33, in train
    with mlflow.start_run():
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 159, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 137, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 95, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 145, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 52, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 153, in call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 78, in http_request
    max_rate_limit_interval, url=url, headers=headers, verify=verify, **kwargs
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 57, in request_with_ratelimit_retries
    response = requests.request(**kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/nakul/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
```

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think this can be closed as a configuration question rather than a bug.

The setup needs three pieces, and the original report only had two:

1. Start the server: `mlflow server --host 0.0.0.0 --port 5000` ✓
2. **Point the client at the server**: either `export MLFLOW_TRACKING_URI=http://<server-host>:5000` before running `python main.py`, or call `mlflow.set_tracking_uri("http://<server-host>:5000")` in code, before the first `mlflow.start_run()`.
3. Run the training script.

Without step 2, the client falls back to the default tracking URI (a local `mlruns/` file store — see [`mlflow/tracking/_tracking_service/utils.py:58-68`](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/_tracking_service/utils.py#L58-L68), `_get_default_tracking_uri` and `is_tracking_uri_set`), and never contacts the server you started.

The official setup pattern is documented at https://mlflow.org/docs/latest/tracking/server.

Would you mind closing this out? If after setting `MLFLOW_TRACKING_URI` the client still fails to reach the server, please share the new error and current MLflow version.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `master` branch.)
