### ISSUE TITLE
[BUG] Storing artifacts to amazon S3 storage does not work

### ISSUE THREAD

**Issue by NemanjaML** [mlflow/mlflow#3453]
Hi everyone,

Due to instructions from the official docs at the following link: https://www.mlflow.org/docs/latest/tracking.html#amazon-s3-and-s3-compatible-storage, I tried to make connection between mlflow and amazon s3 storage, for the purpose of storing the artifacts remotely.

In the official example sklearn_elasticnet_wine I added the following line:

**`mlflow.set_tracking_uri('s3://os-ai-team/mlflow/sklearn')`**

And during the execution, I got the following error:

`Traceback (most recent call last):`
  `File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\registry.py", line 78, in get_store_builder`
    `store_builder = self._registry[scheme]`
`KeyError: 's3'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "C:/Users/stankovic/Projects/mlflow/examples/sklearn_elasticnet_wine/train.py", line 60, in <module>
    with mlflow.start_run():
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\fluent.py", line 159, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\client.py", line 55, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\client.py", line 39, in __init__
    self.store = utils._get_store(self.tracking_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\utils.py", line 127, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\registry.py", line 37, in get_store
    builder = self.get_store_builder(store_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\registry.py", line 81, in get_store_builder
    unsupported_uri=store_uri, supported_uri_schemes=list(self._registry.keys())
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 's3://os-ai-team/mlflow/sklearn' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\registry.py", line 78, in get_store_builder
    store_builder = self._registry[scheme]
KeyError: 's3'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tensorflow.py", line 583, in _flush_queue
    client = mlflow.tracking.MlflowClient()
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\client.py", line 55, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\client.py", line 39, in __init__
    self.store = utils._get_store(self.tracking_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\utils.py", line 127, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\_tracking_service\registry.py", line 37, in get_store
    builder = self.get_store_builder(store_uri)
  File "C:\Users\stankovic\Projects\mlflow\mlflow\tracking\registry.py", line 81, in get_store_builder
    unsupported_uri=store_uri, supported_uri_schemes=list(self._registry.keys())
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 's3://os-ai-team/mlflow/sklearn' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.`

I've also tried with:

**`mlflow run . --no-conda --storage-dir s3://os-ai-team/mlflow/sklearn`**

but the error was:

`Traceback (most recent call last):
  File "c:\users\stankovic\anaconda3\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\stankovic\Anaconda3\envs\py37\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\cli.py", line 187, in run
    run_id=run_id,
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\projects\__init__.py", line 284, in run
    synchronous=synchronous,
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\projects\__init__.py", line 107, in _run
    experiment_id,
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\projects\backend\local.py", line 95, in run
    command_args += get_entry_point_command(project, entry_point, params, storage_dir)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\projects\utils.py", line 284, in get_entry_point_command
    storage_dir_for_run = _get_storage_dir(storage_dir)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\site-packages\mlflow\projects\utils.py", line 64, in _get_storage_dir
    os.makedirs(storage_dir)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\stankovic\anaconda3\envs\py37\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 's3:'`

Is it even possible to do?

Note: I am using Windows10

Thanks in advance,
Nemanja.

**Comment by harupy** [comment]
@NemanjaML 

> mlflow.set_tracking_uri('s3://os-ai-team/mlflow/sklearn')

This is incorrect. You need to set `'s3://os-ai-team/mlflow/sklearn'` to artifact URI.

Can you try this code?

```python
import mlflow

expr_name = "foo"
s3_uri = "replace_with_your_s3_uri"

if mlflow.get_experiment_by_name(expr_name) is None:
    mlflow.create_experiment(expr_name, artifact_localtion=s3_uri)

mlflow.set_experiment(expr_name)

with open("foo.txt", "w") as f:
    f.write("foo")

with mlflow.start_run():
    mlflow.log_artifact("foo.txt")
```

**Comment by NemanjaML** [comment]
Thanks a lot!

**Comment by AkanimohOD19A** [comment]
I tried running this and got this error

`S3UploadFailedError: Failed to upload foo.txt to mlflow-artifacts-remote-010123/1/fda81f37e5b74023b798dc09dfc79f9b/artifacts/foo.txt: An error occurred (405) when calling the PutObject operation: Method Not Allowed`

Please assist
