### ISSUE TITLE
Using NFS server with mlflow.log_artifact() .No proper documntation on mlflow.org

### ISSUE THREAD

**Issue by nakul3112** [mlflow/mlflow#3463]
Hi, I have been trying to to use mlflow for storing params, metrics and artifacts(models) for my deep learning experiments. Till now, I have able to achieve following things:
 1) Setting up mlflow server on a remote machine and running the python script from another client machine
 2) Able to successfully store the params and metrics on the remote server, but `log_artifacts()` is not saving the artifacts remotely, in fact it stores locally in ./mlrun folder. 

Now, I just want to figure out a way to log artifacts remotely, which I have been struggling with since a day. On reading github issues, it seems that using NFS, SFTP and HDFS could help. However, I couldn't find a proper documentation for using NFS server with mlflow, and hence request anyone who has used NFS or other method to successfully store the artifacts.

 I look forward to a solution at the earliest. Thanks in advance.

Regards,
Nakul

**Comment by dmatrix** [comment]
@nakul3112 Thanks for filling this question. We are working on elaborate documentation to explain various scenarios for tracking server, artifact locations, model registry, etc. This relates to #3108.

To answer your questions, both the client and server have to have access to the artifact location.

Launching the server on my localhost:

```
mlflow server --backend-store-uri /tmp/mlruns.db  --default-artifact-root /tmp/artifacts_dir  --host 0.0.0.0
```
On the client side:

```
if __name__ == "__main__":
    with open('test.file', 'wb') as f:
        test = range(20)
        joblib.dump(test, f)

    mlflow.set_tracking_uri("http://0.0.0.0:5000")
    with mlflow.start_run() as run:
        run_id = run.run_id = run.info.run_uuid
        mlflow.log_artifact('test.file')
        print(f"artifact_uri={mlflow.get_artifact_uri()}")
        print(f"run_id={run_id}")
```

```
artifact_uri=/tmp/artifacts_dir/0/1addc3f3d5d04bed97af4c597dba420b/artifacts
run_id=1addc3f3d5d04bed97af4c597dba420b
```

![Screen Shot 2020-09-25 at 11 12 19 AM](https://user-images.githubusercontent.com/1117597/94301781-066c0400-ff20-11ea-8c84-5604fd654041.png)

I hope that this helps.

cheers
Jules

**Comment by nakul3112** [comment]
Hi @dmatrix ,
 
   So you mean to say there is no need to use NFS mount or other ways?

  1) Could you elaborate more on  `both the client and server have to have access to the artifact location.`. I am also running `mlflow server` command on machine B(where I want remote server) and running the python script for training on machine A(client).

     I am still confused about the parameters --backend-store-uri and --default-artifact-location, as in where do they refer to(the machine on which the command is run, or the client side)

**Comment by dmatrix** [comment]
@nakul3112 This example just illustrates that the client has to have access to the `default_root_artifact_location`. In my case, it is local directory other than the default `./mlruns`. If this was an S3 bucket or an NFS mounted directory, it would have to be accessible both in the server and client. 

`--backend-store-uri` is where the tracking server logs MLflow entities—parameters, metrics, tags, run metdata. 
MLflow supports FileStore and SQLAlchemy compatible. For the latter, if you using model registry than your 
`backend-store-uri` ought to an SQLAchemy compatible database: sqlite, mysql, postgresSQL etc.



> 1. I am still confused about the parameters --backend-store-uri and --default-artifact-location, as in where do they refer to(the machine on which the command is run, or the client side)

The server to on the tracking server. Say your tracking server is A, you would execute that on server A.
Let's say your client code is on machine B or your localhost. The client code ^^^ would run on machine B or localhost.

**Comment by nakul3112** [comment]
@dmatrix .

The mlfow documentation is really confusing.
1)  So what would be the order of running the commands? Should the python code be run first, or mlflow server command?

2) I am able to use default backend-store at ./mlruns and am successfully able to see the params and metrics at the server side. Only the artifacts is a issue.

**Comment by dmatrix** [comment]
@nakul3112, hence the #3108 to clarify some aspects. 

Now that I have answered your questions, can we close this issue?

**Comment by eminemence** [comment]
I am also facing the same issue with NFS share and the lack of documentation is really hurting.

We have a `server_NFS`, which has a share exported like this
`/home/nfsuser/share  <server_A>(rw,sync,no_root_squash,no_subtree_check)`

The permissions on `/home/nfsuser/share` have been set for all to read and write.

`server_A` has mlflow tracking server running and is the NFS client. The NFS share is mounted like this
`sudo mount server_NFS:/home/nfsuser/share /mnt/nfs_share`

Creating files and making dirs gets synced properly between the NFS client and server.

Now we tried providing this NFS share as the default artifact root in various forms, but the artifacts just do not get logged to the NFS share. The server command looks like this:
`mlflow server --backend-store-uri postgresql://user:pass@server_postgres:5432/mlflow_db  --default-artifact-root /mnt/nfs_share --host server_A`

In the notebook the get_artifact_uri call returns the following output, but there is nothing on the nfs_share
`artifact_uri: /mnt/nfs_share/18/a21fc1a8b4d9442199832c1e3acb398a/artifacts`

Out of frustration, we tried throwing all types of schemes like `file:/mnt/nfs_share`, `file:///mnt/nfs_share` but that gives INVALIDARGUMENT error and exited.

Any pointer to fix this?

**Comment by fabiansefranek** [comment]
> I am also facing the same issue with NFS share and the lack of documentation is really hurting.
> 
> We have a `server_NFS`, which has a share exported like this `/home/nfsuser/share <server_A>(rw,sync,no_root_squash,no_subtree_check)`
> 
> The permissions on `/home/nfsuser/share` have been set for all to read and write.
> 
> `server_A` has mlflow tracking server running and is the NFS client. The NFS share is mounted like this `sudo mount server_NFS:/home/nfsuser/share /mnt/nfs_share`
> 
> Creating files and making dirs gets synced properly between the NFS client and server.
> 
> Now we tried providing this NFS share as the default artifact root in various forms, but the artifacts just do not get logged to the NFS share. The server command looks like this: `mlflow server --backend-store-uri postgresql://user:pass@server_postgres:5432/mlflow_db --default-artifact-root /mnt/nfs_share --host server_A`
> 
> In the notebook the get_artifact_uri call returns the following output, but there is nothing on the nfs_share `artifact_uri: /mnt/nfs_share/18/a21fc1a8b4d9442199832c1e3acb398a/artifacts`
> 
> Out of frustration, we tried throwing all types of schemes like `file:/mnt/nfs_share`, `file:///mnt/nfs_share` but that gives INVALIDARGUMENT error and exited.
> 
> Any pointer to fix this?

did you fix this and if so, how?

**Comment by taddeusb90** [comment]
I mounted an nfs volume to my pod and when i try to save artifacts it fails 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    platform.apolo.us/inject-storage: '[{"storage_uri": "storage://default/apolo/taddeus/mlflow-artifacts",
      "mount_path": "/mlflow-artifacts", "mount_mode": "rw"}]'
  creationTimestamp: "2025-04-10T13:20:47Z"
  generateName: apolo-taddeus-mlflow-core-a242e4bc-custom-deployment-6ddd5cb4b4-
  labels:
    app.kubernetes.io/instance: apolo-taddeus-mlflow-core-a242e4bc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: custom-deployment
    app.kubernetes.io/version: 1.16.0
    application: mlflow
    helm.sh/chart: custom-deployment-0.1.0
    platform.apolo.us/component: app
    platform.apolo.us/inject-storage: "true"
    platform.apolo.us/org: apolo
    platform.apolo.us/preset: cpu-small
    platform.apolo.us/project: taddeus
    pod-template-hash: 6ddd5cb4b4
  name: apolo-taddeus-mlflow-core-a242e4bc-custom-deployment-6ddd5pp6m9
  namespace: apolo-taddeus-mlflow-core-a242e4bc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apolo-taddeus-mlflow-core-a242e4bc-custom-deployment-6ddd5cb4b4
    uid: eafebf2a-57e2-4625-8766-f779ab2803b3
  resourceVersion: "284837951"
  uid: d15aa6e4-5ce9-4627-9b29-0a8f5898686a
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: platform.neuromation.io/nodepool
            operator: In
            values:
            - default
  containers:
  - args:
    - server
    - --dev
    - --serve-artifacts
    - --backend-store-uri=sqlite:///mlflow-data/mlflow.db
    - --host=0.0.0.0
    - --port=5000
    - --artifacts-destination=/mlflow-artifacts
    command:
    - mlflow
    image: ghcr.io/apolo-actions/mlflow:v2.19.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: custom-deployment
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 953M
      requests:
        cpu: 500m
        memory: 953M
    securityContext:
      allowPrivilegeEscalation: true
      runAsGroup: 0
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mlflow-data
      name: mlflow-db-pvc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t2pbb
      readOnly: true
    - mountPath: /mlflow-artifacts
      name: storage-auto-injected-volume-35a6ab5f
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-dev-gke-cluster-dev-cpu-pool-57e01db7-qh32
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
    runAsUser: 0
  serviceAccount: apolo-taddeus-mlflow-core-a242e4bc-custom-deployment
  serviceAccountName: apolo-taddeus-mlflow-core-a242e4bc-custom-deployment
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: platform.neuromation.io/job
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: mlflow-db-pvc
    persistentVolumeClaim:
      claimName: mlflow-sqlite-storage
  - name: kube-api-access-t2pbb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: storage-auto-injected-volume-35a6ab5f
    nfs:
      path: //apolo/taddeus/mlflow-artifacts
      server: 10.6.61.74
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T13:20:48Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T13:20:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T13:21:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T13:21:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T13:20:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5b1d428b10fd890a882f2ff8e35b45c093348b3df8f7849c3ecbe361be762059
    image: ghcr.io/apolo-actions/mlflow:v2.19.0
    imageID: ghcr.io/apolo-actions/mlflow@sha256:daedfdcc5d916d5f01e0354e17d3ca28d40b8536438ca97f36b596bc81d73662
    lastState: {}
    name: custom-deployment
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-04-10T13:20:47Z"
    volumeMounts:
    - mountPath: /mlflow-data
      name: mlflow-db-pvc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t2pbb
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /mlflow-artifacts
      name: storage-auto-injected-volume-35a6ab5f
  hostIP: 10.0.0.56
  hostIPs:
  - ip: 10.0.0.56
  phase: Running
  podIP: 10.4.2.213
  podIPs:
  - ip: 10.4.2.213
  qosClass: Guaranteed
  startTime: "2025-04-10T13:20:47Z"
```

but saving artifacts fails with 

```
app-types) (base) ➜  app-types git:(MLO-149) ✗ /Users/taddeusbuica/anaconda3/envs/app-types/bin/python /Users/taddeusbuica/Desktop/work/app-types/mlflow_test.py
MLflow run_id: 5967179a7e824d879de1f1fbbe1bea80
Tracking URI: https://apolo-taddeus-mlflow-core-a242e4bc.apps.dev.apolo.us
Run Info: <RunInfo: artifact_uri='/mlflow-artifacts/1/5967179a7e824d879de1f1fbbe1bea80/artifacts', end_time=None, experiment_id='1', lifecycle_stage='active', run_id='5967179a7e824d879de1f1fbbe1bea80', run_name='local-mlflow-run', run_uuid='5967179a7e824d879de1f1fbbe1bea80', start_time=1744294734500, status='RUNNING', user_id='taddeusbuica'>
Artifact URI: /mlflow-artifacts/1/5967179a7e824d879de1f1fbbe1bea80/artifacts
🏃 View run local-mlflow-run at: https://apolo-taddeus-mlflow-core-a242e4bc.apps.dev.apolo.us/#/experiments/1/runs/5967179a7e824d879de1f1fbbe1bea80
🧪 View experiment at: https://apolo-taddeus-mlflow-core-a242e4bc.apps.dev.apolo.us/#/experiments/1
Traceback (most recent call last):
  File "/Users/taddeusbuica/Desktop/work/app-types/mlflow_test.py", line 51, in <module>
    main()
  File "/Users/taddeusbuica/Desktop/work/app-types/mlflow_test.py", line 44, in main
    mlflow.log_artifact(artifact_path, artifact_path="output_data")
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 1179, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/tracking/client.py", line 2374, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 926, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 43, in log_artifact
    mkdir(artifact_dir)
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/utils/file_utils.py", line 211, in mkdir
    raise e
  File "/Users/taddeusbuica/anaconda3/envs/app-types/lib/python3.12/site-packages/mlflow/utils/file_utils.py", line 208, in mkdir
    os.makedirs(target, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/mlflow-artifacts'
```

It's not a permission error cause when I kubectl exec'ed in the pod i could create files there and i'm aready running as root

Did anyone solve this issue?
