### ISSUE TITLE
[BUG] log_artifact timeout

### ISSUE THREAD

**Issue by ZackBarry** [mlflow/mlflow#3478]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ x ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS Catalina 10.15.6, Docker with python:3.8.5-buster as base image
- **MLflow installed from (source or binary)**:
pip install
- **MLflow version (run ``mlflow --version``)**:
1.10.0
- **Python version**:
3.8.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
See below.

### Describe the problem
When logging a single large (~500mb) artifact to an MLflow tracking server with a GCS artifact store hosted on GKE, MLflow times out. The cluster the server is running on seems to be large enough: 3 nodes, each with 3.75GB memory. No other experiments are being run at the same time.

### Code to reproduce issue

R script `train.R`:
```
library(mlflow) # 1.10.0
library(tibble) 
library(readr)

with(mlflow_start_run(), {
  test_df <- as.tibble(replicate(300, sample(letters, 1000000, rep=TRUE)))
  write_csv(test_df, 'test.csv') # ~500mb
  mlflow_log_artifact(path='test.csv')
})
```

Command:
```
mlflow run --experiment-name big-file-test --entry-point train.R --no-conda .
```

### Other info / logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-pack/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/cli.py", line 42, in log_artifact
    artifact_repo.log_artifact(local_file, artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 56, in log_artifact
    blob.upload_from_filename(local_file)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2334, in upload_from_filename
    self.upload_from_file(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2220, in upload_from_file
    created_json = self._do_upload(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2067, in _do_upload
    response = self._do_resumable_upload(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1946, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 495, in transmit_next_chunk
    response = _request_helpers.http_request(
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 165, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionErrages/mlflow/store/artifact/cli.py", line 42, in log_artifact
    artifact_repo.log_artifact(local_file, artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 56, in log_artifact
    blob.upload_from_filename(local_file)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2334, in upload_from_filename
    self.upload_from_file(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2220, in upload_from_file
    created_json = self._do_upload(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2067, in _do_upload
    response = self._do_resumable_upload(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1946, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 495, in transmit_next_chunk
    response = _request_helpers.http_request(
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/usr/local/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 165, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
or: ('Connection aborted.', timeout('The write operation timed out'))
Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose, : System command 'mlflow' failed, exit status: 1, stdout & stderr were printed
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ x ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ x  ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@ZackBarry Am cc the R contributors
cc: @kevinykuo

**Comment by dokasov** [comment]
Any updates on this? Same is happening to me. ~290MB file is not being uploaded, and instead it returns a timeout in `mlflow.log_artifact`.

**Comment by dokasov** [comment]
It's now happening with a ~50MB file and I still can't find the problem :(

**Comment by relferreira** [comment]
I'm with the same problem :(

**Comment by morkru** [comment]
@dokasov @relferreira Do you guys have slow upload speeds? As far as I digged I found out mlflow uploads files to gcs in 100MB chunk sizes? Could that be the issue?

**Comment by relferreira** [comment]
@morkru I live in Brazil so, unfortunately, my upload speed is really slow 😢

**Comment by morkru** [comment]
@relferreira @dmatrix @ZackBarry It seems one could either increase the timeout or change the chunk_size. A sample solution could look like this. Would that fix the issue? https://github.com/morkru/mlflow/commit/ce47e0856f67270a70b0f1c9190abf04a637eb55

**Comment by lorenzwalthert** [comment]
Have you tried to log an artifact with Python or CLI and does the same problem occur? 

Also, habe you tried AWS or Azure backends? 

Have you Limited data i/o into GCP?

**Comment by morkru** [comment]
@lorenzwalthert Python API and CLI produce the same error. I don't have AWS or Azure backends available. I'm assuming the issue is the upload speed. So no limited data i/o from GCS side. I'm guessing it's a client side problem. Changing either the timeout or chunk_size fixed the issue for me.

**Comment by morkru** [comment]
@lorenzwalthert I just checked it again. It seems GCS by default uploads in chunks of 100Mb requiring a response every 60 seconds (default timeout variable). Which means if your upload is less than 13 MBit/s then it should fail giving you a read-timeout.

To test this, I set the timeout to 300 seconds and it didn't work since my upload speed requires ~350 seconds for 100MB (yes it's slow). It works after setting it to 360 seconds. So I'm guessing my assumption should be right.

**Comment by Ankur-singh** [comment]
any updates on this ? I am facing the same issue. I have a 44 MB model, but because of poor connectivity I am always getting a timeout error. All other artifacts are logged successfully.

**Comment by palol** [comment]
@morkru are your changes available in any of the new versions of mlflow? I'm currently on v1.24.0 (latest release at the time of writing) and am not seeing any changes from overriding the default timeout. 

I tried adding the following to my code, but with no success
```
import os
os.environ['MLFLOW_GCS_DEFAULT_TIMEOUT'] = '200'
```

**Comment by morkru** [comment]
@palol Hi! I'm guessing they will be in v.1.25.0 next month

**Comment by mokrueger** [comment]
@palol Hi! I'm guessing they will be in v.1.25.0 next month

**Comment by saichandrapandraju** [comment]
Hi,
What if I'm using Minio ?
Is there a similar ENV variable for Minio?
