### ISSUE TITLE
[BUG]mlflow project throws INVALID_PARAMETER_VALUE exception for float parameter

### ISSUE THREAD

**Issue by akbindal** [mlflow/mlflow#3536]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.11
- **Python version**: 2.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

### Describe the problem
Running the mlflow project with float parameter value in exponential format throws the INVALID_PARAMETER_VALUE exception - "Changing param value is not allowed":

### Code to reproduce issue
Using the provided docker example in https://github.com/mlflow/mlflow/tree/master/examples/docker, running it with 
`mlflow run examples/docker -P alpha=0.5 -P alpha=0.00001`
`mlflow run examples/docker -P alpha=0.5 -P alpha=1e-1`
throws an INVALID_PARAMETER_VALUE exception. However the same with parameter in decimal format works until 4 decimal places, e.g:
`mlflow run examples/docker -P alpha=0.5 -P alpha=0.01`

The bug seems to be related to how floating parameter values are stored either in exponential format or decimal format. 

### Other info / logs
```
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    mlflow.log_param("alpha", alpha)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/fluent.py", line 214, in log_param
    MlflowClient().log_param(run_id, key, value)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/client.py", line 205, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 179, in log_param
    self.store.log_param(run_id, param)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/rest_store.py", line 143, in log_param
    self._call_endpoint(LogParam, req_body)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/utils/rest_utils.py", line 137, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/utils/rest_utils.py", line 103, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Changing param values is not allowed. Param with key='alpha' was already logged with value='1e-2' for run ID='a831272fa4f5498fb55e20e8a4116b5f'. Attempted logging new value '0.01'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@akbindal Thanks for reporting this. Here's how the error occurs:

1. `mlflow run examples/docker ... -P alpha=0.00001` creates a new run with `alpha=0.00001`.
2. in`examples/docker/train.py`, `alpha` is converted into a float value which is `1e-05`.
3. `mlflow.log_param` converts float `alpha` into a string which is `"1e-05"`, and tries to log it in the run created in step 1.
4. but `alpha` is already logged as `0.00001`, then the error is thrown.

```
>>> 
>>> str(float("0.00001"))
'1e-05'
```

**Comment by dmatrix** [comment]
@akbindal Thanks for filling this.

If you use supply duplicate parameters to mlflow run, it will fail with an error:

```
mlflow run. -e main -P alpha=0.5 -P alpha=0.01
....
Repeated parameter: 'alpha'
```

If you supply either -P='1e-05' or -P=1e-05, all will work fine.

```
mlflow run examples/docker -P alpha=1e-05
...

Elasticnet model (alpha=0.000010, l1_ratio=0.100000):
  RMSE: 0.7493979391840435
  MAE: 0.5825538052814186
  R2: 0.2746545999035419
2020/10/15 11:28:02 INFO mlflow.projects: === Run (ID '6ae0baac3b104d3eb365cd706c28e29e') succeeded ===
```

```
mlflow run examples/docker -P alpha='1e-05'
....
Elasticnet model (alpha=0.000010, l1_ratio=0.100000):
  RMSE: 0.7493979391840435
  MAE: 0.5825538052814186
  R2: 0.2746545999035419
2020/10/15 11:30:15 INFO mlflow.projects: === Run (ID 'cb61eb328ed54284961972dc1df8f5c5') succeeded ===

```

cc: @harupy Do you think this is a subtle bug, where 0.00001 -> converted to string causes it to fail?

**Comment by akbindal** [comment]
@dmatrix Parameter duplication is not an issue here. 
@harupy The inconsistency between how the value of the parameter is logged in MLflow tracking api and MLflow project run cmd causing the error. Parameter value provided at the time of mlflow run should have a proper typecasting to create the run rather than using the provided string format of the parameter value.  
given parameter value: 1e-2, logged string format: 0.01 --> causing error
given parameter value: 0.01, logged string format: 0.01 --> fine
given parameter value: 0.000001, logged string format: 1e-6 --> causing error

**Comment by dmatrix** [comment]
@harupy, Yes I see it now.
