### ISSUE TITLE
[BUG] Cloudpickle in pyfunc fails to serialize gpytorch model

### ISSUE THREAD

**Issue by donnut** [mlflow/mlflow#3546]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: 3.8.5

### Describe the problem
A pyfunc model is created to store a GPyTorch model (gpytorch.ai). When saving the model using the mlflow.pyfunc.log_model() it raises an pickle error:
```
Traceback (most recent call last):
  File "mlflow_issue.py", line 45, in <module>
    mlflow.pyfunc.log_model(artifact_path="gpmodel", python_model=gpmodel, conda_env=conda_env)
  File "/home/erwin/dev/ds/mlflow/mlflow/pyfunc/__init__.py", line 990, in log_model
    return Model.log(
  File "/home/erwin/dev/ds/mlflow/mlflow/models/model.py", line 172, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/home/erwin/dev/ds/mlflow/mlflow/pyfunc/__init__.py", line 868, in save_model
    return mlflow.pyfunc.model._save_model_with_class_artifacts_params(
  File "/home/erwin/dev/ds/mlflow/mlflow/pyfunc/model.py", line 138, in _save_model_with_class_artifacts_params
    cloudpickle.dump(python_model, out)
  File "/home/erwin/dev/ds/charging_time/.venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/home/erwin/dev/ds/charging_time/.venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
_pickle.PicklingError: Can't pickle <built-in function softplus>: import of module 'torch._C._nn' failed
```
Cloudpickle is not able to serialize the gpytorch model. This is reported in https://github.com/cloudpipe/cloudpickle/issues/381 as well. The cloudpickle alternative dill does the serialization correct. 

I'm raising this issue here as I would like to contribute to a vendor neutral pickle module for `pyfunc` that allows a choice between cloudpickle and dill.

### Code to reproduce issue
There are two examples to reproduce the error. First using `mlflow` and a second, even more minimalised version using cloudpickle only.

```python
import mlflow
import torch
import gpytorch

class GPPythonModel(mlflow.pyfunc.PythonModel):

    def __init__(self,
                 input_example,
                 output_example,
                 ):

        self.likelihood = gpytorch.likelihoods.GaussianLikelihood()
        self.model = gpytorch.models.ExactGP(torch.tensor(input_example, dtype=torch.float32), torch.tensor(output_example, dtype=torch.float32), self.likelihood)

    def predict(self, context, model_input):
        pass

conda_env = {
    'name': 'mlflow-env',
    'channels': ['defaults'],
    'dependencies': [
        'python=3.8.5', 
        {
            'pip': [
                'mlflow==1.11.0',
                'cloudpickle',
                'gpytorch',
                'torch'
            ]
        }
    ]
}

gpmodel = GPPythonModel(
    input_example=[[0., 0., 0.]],
    output_example=[[0.]],
)

mlflow.pyfunc.log_model(artifact_path="gpmodel", python_model=gpmodel, conda_env=conda_env)
```
Bare minimum example:
```python
import cloudpickle
import gpytorch

with open('ww', 'wb') as f:
    model = gpytorch.models.GP()
    cloudpickle.dump(gpmodel, f)
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sklingel** [comment]
Actually a similar problem also occurs when you use gpflow

**Comment by donnut** [comment]
In version 1.14.0 the same problem exists. I would like to fix this by committing code, but I'm unsure of the approach. Can someone please advise:

1. use `dill` instead of `cloudpickle` in `mlflow/mlflow/pyfunc/model.py` and add `dill` as a dependency in `setup.py`
2. use both `dill` and `cloudpickle` in `model.py` and make it configurable in `mlflow.pyfunc.log_model`

The second approach is more flexible, and backward compatible if `cloudpickle` is made default. It is quite a bit more work thou.

What would be the preferred method? Or is there a third one?
