### ISSUE TITLE
[BUG] MLflow deployment on AzureML fails because of a previous version of Numpy.

### ISSUE THREAD

**Issue by deepankerkoul** [mlflow/mlflow#3587]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.6
- **MLflow installed from (source or binary)**: Source (pip)
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: Tried with 3.6 as well as 3.7.9
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow.azureml.build_image(model_uri=<my_mlrun_uri>, workspace=ws, synchronous=True)

### Describe the problem
MLflow deployment on AzureML fails because of a previous version of Numpy.

I have developed a custom code that I am trying to deploy to Azure using MLFlow. I have used the deployment script multiple times over last couple of months so I know that nothing is wrong there.

Anyway, I let the image build using the command ```mlflow.azureml.build_image(model_uri=<my_mlrun_uri>, workspace=ws, synchronous=True)``` and build succeeds, but when I deploy the Image as a webservice using Azure Container Instances, the 
code fails with a Timeout Error and the following error:

```
WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 5bcee0af-35b7-45ae-8be3-ff3a610afa2a
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.
Please refer to https://aka.ms/debugimage#dockerlog for more information.",
  "details": [
    {
      "code": "AciDeploymentFailed",
      "message": "Your container application crashed. Please follow the steps to debug:
1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.
2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.
3. View the diagnostic events to check status of container, it may help you to debug the issue. 
{"restartCount":7,
"currentState": {"state":"Waiting","startTime":null,"exitCode":null,"finishTime":null,"detailStatus":"CrashLoopBackOff: Back-off 5m0s restarting failed"},
"previousState":{"state":"Terminated","startTime":"2020-10-22T18:53:39Z","exitCode":111,"finishTime":"2020-10-22T18:54:02Z","detailStatus":"Error"},
"events":[
{"count":3,"firstTimestamp":"2020-10-22T18:28:19Z","lastTimestamp":"2020-10-22T18:40:40Z","name":"Pulling","message":"pulling image \\\"<IMAGE_NAME>\\\" ", "type":"Normal"},
{"count":3,"firstTimestamp":"2020-10-22T18:39:31Z","lastTimestamp":"2020-10-22T18:40:41Z","name":"Pulled","message":"Successfully pulled image \\\"<IMAGE_NAME>\\\" ","type":"Normal"},
{"count":3,"firstTimestamp":"2020-10-22T18:39:35Z","lastTimestamp":"2020-10-22T18:40:41Z","name":"Created","message":"Created container","type":"Normal"},
{"count":3,"firstTimestamp":"2020-10-22T18:39:35Z","lastTimestamp":"2020-10-22T18:40:41Z","name":"Started","message":"Started container","type":"Normal"},
{"count":50,"firstTimestamp":"2020-10-22T18:40:28Z","lastTimestamp":"2020-10-22T18:53:23Z","name":"BackOff","message":"Back-off restarting failed container","type":"Warning"}]}"
    }
  ]
}
```

I pulled up the logs from the Azure Container Instances Services and it is as follows:
```
2020-10-22T06:58:49,020260384+00:00 - iot-server/run 
2020-10-22T06:58:49,019574380+00:00 - rsyslog/run 
2020-10-22T06:58:49,117097008+00:00 - gunicorn/run 
2020-10-22T06:58:49,118285816+00:00 - nginx/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2020-10-22T06:58:51,222442674+00:00 - iot-server/finish 1 0
2020-10-22T06:58:51,322087216+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.6.0
Listening at: http://127.0.0.1:31311 (12)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 41
Exception in worker process
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 31, in <module>
    import main as user_main
  File "/var/azureml-app/main.py", line 12, in <module>
    driver_module_spec.loader.exec_module(driver_module)
  File "/var/azureml-app/execution_script.py", line 2, in <module>
    import pandas as pd
  File "/opt/miniconda/lib/python3.6/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/opt/miniconda/lib/python3.6/site-packages/pandas/compat/numpy/__init__.py", line 21, in <module>
    "this version of pandas is incompatible with numpy < 1.15.4\n"
ImportError: this version of pandas is incompatible with numpy < 1.15.4
your numpy version is 1.14.2.
Please upgrade numpy to >= 1.15.4 to use this pandas version
Worker exiting (pid: 41)
Shutting down: Master
Reason: Worker failed to boot.
2020-10-22T06:59:16,624645953+00:00 - gunicorn/finish 3 0
2020-10-22T06:59:16,717989455+00:00 - Exit code 3 is not normal. Killing image.
```

I checked and my development venv (Py3.7.9) has the numpy version - 1.19.2 and even the base python (3.6.6) has 1.18.2

Initially the error was that the numpy version is 1.14.2. To mitigate that I explicitly passed ```numpy==1.16.1``` as a dependency and as a result the error now asks me to uninstall the previous versions of numpy. 

**DOUBT 01 of 02 : How do I uninstall this previous version? Is that even possible.**

While investigating it, I went back to the logs generated by MLflow while building the image and I noticed that it is installing a number of additional packages while building the base image (including Numpy version 1.14.2) that is subsequently overwritten using packages from my mlflow_env.yml file.

A snippet of logs while building the image is as follows:

```
Step 36/38 : RUN CONDA_ROOT_DIR=$(conda info --root) && if [ -n "$AZUREML_CONDA_ENVIRONMENT_PATH" ]; then conda env update -p "$AZUREML_CONDA_ENVIRONMENT_PATH" -f '/var/azureml-app/mlflow_env.yml'; else conda env update -n base -f '/var/azureml-app/mlflow_env.yml'; fi && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} +
 ---> Running in fe3b3c665339
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata: ...working... 
done
Solving environment: ...working... 
done

Downloading and Extracting Packages

<Random packages being installed>
<Random packages being installed>
<Random packages being installed>
numpy-1.14.2         | 4.0 MB    |            |   0% 
numpy-1.14.2         | 4.0 MB    | #######6   |  76% 
numpy-1.14.2         | 4.0 MB    | #########  |  91% 
numpy-1.14.2         | 4.0 MB    | ########## | 100% 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
done
Ran pip subprocess with arguments:
['/opt/miniconda/bin/python', '-m', 'pip', 'install', '-U', '-r', '/var/azureml-app/condaenv.kscafao_.requirements.txt']
Pip subprocess output:
Collecting torch==1.3.0
  Downloading torch-1.3.0-cp36-cp36m-manylinux1_x86_64.whl (773.1 MB)
Collecting numpy==1.16.1
  Downloading numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl (17.3 MB)
Installing collected packages: numpy, torch,
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
  Attempting uninstall: torch
    Found existing installation: torch 0.4.1
    Uninstalling torch-0.4.1:
      Successfully uninstalled torch-0.4.1
Successfully installed numpy-1.16.1  torch-1.3.0 
```

**Doubt 02 of 02: As you can see, my system has a different numpy (1.19) and in my yml file I'm asking for numpy (1.16) to be installed, then where is this numpy (1.14.2) coming from?**

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/build`: Build and test infrastructure for MLflow

Interface 
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models

Integrations
- [X] `integrations/azure`: Azure and Azure ML integrations

**Comment by dbczumar** [comment]
Hi @deepankerkoul , deploying with the new MLflow + AzureML deployment plugin should resolve this issue. Instructions are available here: https://aka.ms/aml-mlflow-deploy.
