### ISSUE TITLE
mlflow serve command with --no-conda not working in windows python environment

### ISSUE THREAD

**Issue by safuvanpp** [mlflow/mlflow#3633]
python env: 
python- 3.7.7
mlflow- 1.10.0

mlflow project folder created successfully with all the required files.
getting the following error while tried to deploy the model. 

(custom_ml_env) C:\Users\644947\CSAT\custom_model_templates\mlflow_impl_guide\classification>mlflow models serve -m runs:/92c6059bbea54c378bf1320f1a5632d1/artifacts/model -p 1234 --no-conda
Traceback (most recent call last):
  File "C:\Users\644947\python3.7.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\644947\python3.7.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\644947\custom_ml_env\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\644947\custom_ml_env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\models\cli.py", line 58, in serve
    install_mlflow=install_mlflow).serve(model_uri=model_uri, port=port,
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\models\cli.py", line 165, in _get_flavor_backend
    append_to_uri_path(underlying_model_uri, MLMODEL_FILE_NAME), output_path=tmp.path())
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\tracking\artifact_utils.py", line 74, in _download_artifact_from_uri
    artifact_path=artifact_path, dst_path=output_path)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 116, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 67, in download_artifacts
    return super(LocalArtifactRepository, self).download_artifacts(artifact_path, dst_path)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\store\artifact\artifact_repo.py", line 130, in download_artifacts
    return download_file(artifact_path)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\store\artifact\artifact_repo.py", line 90, in download_file
    self._download_file(remote_file_path=fullpath, local_path=local_file_path)
  File "c:\users\644947\custom_ml_env\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 95, in _download_file
    shutil.copyfile(remote_file_path, local_path)
  File "C:\Users\644947\python3.7.7\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\644947\\CSAT\\custom_model_templates\\mlflow_impl_guide\\classification\\mlruns\\0\\92c6059bbea54c378bf1320f1a5632d1\\artifacts\\artifacts\\model\\MLmodel'

**Comment by harupy** [comment]
@safuvanpp Thanks for reporting this. This seems like a bug. It looks like `artifacts` is duplicated.

```
'C:\Users\...\mlruns\0\92c6059bbea54c378bf1320f1a5632d1\artifacts\artifacts\model\MLmodel'
                                                        ^^^^^^^^^^^^^^^^^^^^^
```

It shoud look like:

```
'C:\Users\...\mlruns\0\92c6059bbea54c378bf1320f1a5632d1\artifacts\model\MLmodel'
```

**Comment by safuvanpp** [comment]
without '--no-conda' serve command is working for anaconda env, but not for python env in windows.(mlflow models serve -m mlruns\0\7eb99f884f60440691f5cbd59a53a67d\artifacts\model -p 1234)
--no-conda serve command is **not** working in anaconda env and python env as well(mlflow models serve -m mlruns\0\7eb99f884f60440691f5cbd59a53a67d\artifacts\model -p 1234 --no-conda).

Error:
(In Anaconda env)
(Env_name) C:\Users\644947\CSAT\custom_model_templates\mlflow_impl_guide\classification>mlflow models serve -m mlruns\0\7eb99f884f60440691f5cbd59a53a67d\artifacts\model -p 1234 --no-conda
2020/11/04 19:08:30 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2020/11/04 19:08:30 INFO mlflow.pyfunc.backend: === Running command 'waitress-serve --host=127.0.0.1 --port=1234 --ident=mlflow mlflow.pyfunc.scoring_server.wsgi:app'
Traceback (most recent call last):
  File "c:\users\644947\anaconda3\envs\env_name\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\644947\anaconda3\envs\env_name\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\644947\Anaconda3\envs\Env_name\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\mlflow\models\cli.py", line 59, in serve
    host=host)
  File "c:\users\644947\anaconda3\envs\env_name\lib\site-packages\mlflow\pyfunc\backend.py", line 98, in serve
    subprocess.Popen([command.split(" ")], env=command_env).wait()
  File "c:\users\644947\anaconda3\envs\env_name\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\644947\anaconda3\envs\env_name\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ahmadarbain** [comment]
@safuvanpp how could you fix this, I had similliar issue l
