### ISSUE TITLE
[BUG] mlflow.pytorch.log_model yields mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Tag value ... had length 5031, which exceeded length limit of 5000

### ISSUE THREAD

**Issue by daemonmaker** [mlflow/mlflow#3690]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.11 and 1.12
- **Python version**: 3.6.9 Anaconda
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Calling `mlflow.pytorch.log_model` yields a warning about being unable to log model metadata and suggests the MLFlow sever may be out of date even though Python package and server are the same version and both are either v1.11.0 or v1.12.0. Removing the try catch generating the warning reveals the length limit of a REST call is being violated.

### Code to reproduce issue
1. Clone retinanet-examples repo: https://github.com/NVIDIA/retinanet-examples
2. Instrument to save model using `mlflow.pytorch.log_model` to a Postgres backend store and FTP artifact store.
3. Execute `ODTK train`

### Other info / logs
The exact error is:
`2020/11/13 20:54:21 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under ftp://mlflow:mlflow@localhost/4/0bb3d83deea74868bb0bf2a838460223/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the  tracking store. If logging to a mlflow server via REST, consider  upgrading the server version to MLflow 1.7.0 or above.`.

Removing the `try-catch` from `def log` in `mlflow/models/model.py` reveals the stack trace:
```
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/home/repos/retinanet-examples/retinanet/main.py", line 251, in main
    worker(0, args, 1, model, state)
  File "/home/repos/retinanet-examples/retinanet/main.py", line 186, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/home/repos/retinanet-examples/retinanet/train.py", line 241, in train
    mlflow.pytorch.log_model(model, state['path'])
  File "/opt/conda/lib/python3.6/site-packages/mlflow/pytorch/__init__.py", line 193, in log_model
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/mlflow/models/model.py", line 163, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 333, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 299, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 255, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 288, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/tracking/rest_store.py", line 52, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 155, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 117, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Tag value '[{"run_id": "4f65dbd571364b3483d8cf155d7fa325", "artifact_path": "test.pth", "utc_time_created": "2020-11-13 21:01:50.210020", "flavors": {"pytorch": {"model_data": "data", "pytorch_version": "1.5.0a0+8f84ded"}, "python_function": {"pickle_module_nam' had length 5031, which exceeded length limit of 5000
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@daemonmaker Thanks for reporting this. Can you share your code?

**Comment by daemonmaker** [comment]
I cannot submit the code. Did the steps under code to reproduce not exhibit the problem for you?

**Comment by astan-iq** [comment]
Adding to the pool of problematic examples: https://gist.github.com/astan-iq/8722c75b9bdaad7596ae2f70562ecb6c
Which raises `mlflow.exceptions.MlflowException: Tag value ... had length 45560, which exceeded length limit of 5000`

Removing `signature`  from the `log_model` args works but then you lose the schema validation functionality.

It appears that tracking schemas of large datasets is not supported.

Has anyone found a solution to this? It looks like the new MLF dataset capture can log the train/test data schemas but 
signature being part of the model tag remains an issue.
