### ISSUE TITLE
[SETUP-BUG] Error initializing backend store: MS-SQL ALTER COLUMN operations with NULL or NOT NULL require the existing_type or a new type_ be passed

### ISSUE THREAD

**Issue by pauldj54** [mlflow/mlflow#3933]
**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **Docker python:3.7-slim-buster**:
- **binary**:
- **1.13.0**:
- **3.7**:
- **mlflow server --backend-store-uri mssql+pyodbc://<user>:<password>@myhost:port/databasename?driver=ODBC+Driver+17+for+SQL+Server --default-artifact-root "$MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT" --host 0.0.0.0**:

### Describe the problem
I created an Azure SQL Database.
I also added the SQL Server ODBC Driver 17 for Ubuntu 18.04 in the docker file for the mlflow server
I added the command above to the start script of the docker container.
I checked the connectivity with a local client using the same credentials, driver and connection string.

When I started the container (docker run) I got the eror: 

> ERROR mlflow.cli: MS-SQL ALTER COLUMN operations with NULL or NOT NULL require the existing_type or a new type_ be passed.

The curious thing is, the backend tables are created in the database:
![image](https://user-images.githubusercontent.com/706754/103463626-fe490f00-4d2d-11eb-98a7-e4c6dc508f07.png)

After that some database migration methods are called and it failed.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Complete error trace:
`2021/01/02 17:52:58 ERROR mlflow.cli: Error initializing backend store
2021/01/02 17:52:58 ERROR mlflow.cli: MS-SQL ALTER COLUMN operations with NULL or NOT NULL require the existing_type or a new type_ be passed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlflow/cli.py", line 385, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 146, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 131, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/registry.py", line 38, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 102, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 118, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 33, in _initialize_tables
    _upgrade_db(engine)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 146, in _upgrade_db
    command.upgrade(config, "heads")
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db_migrations/env.py", line 84, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db_migrations/env.py", line 78, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db_migrations/versions/a8c4a736bde6_allow_nulls_for_run_id.py", line 22, in upgrade
    batch_op.alter_column("run_id", nullable=True)
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 354, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/batch.py", line 83, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/mssql.py", line 72, in alter_column
    "MS-SQL ALTER COLUMN operations "
alembic.util.exc.CommandError: MS-SQL ALTER COLUMN operations with NULL or NOT NULL require the existing_type or a new type_ be passed.`

**Comment by dbczumar** [comment]
@pauldj54 Can you try running your workload on MLflow 1.13.1 (recently released)? We merged #3836 to address this issue. Feel free to reopen this if that doesn't resolve the issue!
