### ISSUE TITLE
[BUG] models not showing in UI

### ISSUE THREAD

**Issue by mat-l** [mlflow/mlflow#3954]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu Server 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow (1.13.1)
- **Python version**: Python 3.6.9
- **npm version, if running the dev UI**: ---
- **Exact command to reproduce**: 
I have stared the server as follows, either "mlflow server --backend-store-uri /media/ailabshare1/mlflow_test --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0" or "mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0"

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.
Case 1:
I start the server with `mlflow server --backend-store-uri /media/ailabshare1/mlflow_test --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0` and upload/log a model with `mlflow.pytorch.log_model(pytorch_model=model, registered_model_name="pytorch-model", artifact_path=new_path)`

This prints the status message, that the model is registered:
```
Registered model 'pytorch-model' already exists. Creating a new version of this model...
2021/01/07 15:07:31 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: pytorch-model, version 6
Created version '6' of model 'pytorch-model'.
```

Image Case 1 Experiments and Models: https://imgur.com/a/0oN8SUE

Case 2
As the error on the UI in the tab models advises me to use for example sqlite I am starting the server in the second case as follows:
`mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0`
Again I am logging a model with `mlflow.pytorch.log_model(pytorch_model=model, registered_model_name="pytorch-model", artifact_path=new_path)`.
It appears in the artifacts but not in the UI of Registered Models although the code
```
# print current models in registry
    from pprint import pprint
    client = MlflowClient()
    for rm in client.list_registered_models():
        pprint(dict(rm), indent=4)
```
an output of registered models shows:
```
{   'creation_timestamp': 1610017108891,
    'description': None,
    'last_updated_timestamp': 1610017108891,
    'latest_versions': [],
    'name': 'alexnet_membranfeder',
    'tags': {}}
{   'creation_timestamp': 1610017809482,
    'description': None,
    'last_updated_timestamp': 1610030717165,
```

Image Case 2 Experiments and Models: https://imgur.com/a/HTrdGiZ

### Code to reproduce issue
Start server as follow:
"mlflow server --backend-store-uri /media/ailabshare1/mlflow_test --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0"
or
"mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /media/ailabshare1/mlflow_test --host 0.0.0.0"

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Log for case 1:
 ```
in _list_run_infos
    run_info = self._get_run_info_from_dir(r_dir)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 529, in _get_run_info_from_dir
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/media/ailabshare1/mlflow_test/0/505b4e8272df4259ba21509f913223b7/meta.yaml' does not exist.
WARNING:root:Malformed run '5a312e035a664143bd440fcdd7eefe29'. Detailed error Yaml file '/media/ailabshare1/mlflow_test/0/5a312e035a664143bd440fcdd7eefe29/meta.yaml' does not exist.
Traceback (most recent call last):
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 699, in _list_run_infos
    run_info = self._get_run_info_from_dir(r_dir)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 529, in _get_run_info_from_dir
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/media/ailabshare1/mlflow_test/0/5a312e035a664143bd440fcdd7eefe29/meta.yaml' does not exist.
WARNING:root:Malformed run 'e1575667004a4fac9c65a736955d9a6a'. Detailed error Yaml file '/media/ailabshare1/mlflow_test/0/e1575667004a4fac9c65a736955d9a6a/meta.yaml' does not exist.
Traceback (most recent call last):
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 699, in _list_run_infos
    run_info = self._get_run_info_from_dir(r_dir)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 529, in _get_run_info_from_dir
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/media/ailabshare1/mlflow_test/0/e1575667004a4fac9c65a736955d9a6a/meta.yaml' does not exist.
WARNING:root:Malformed run '509627168073427aaa51a3de0c3c5e31'. Detailed error Yaml file '/media/ailabshare1/mlflow_test/0/509627168073427aaa51a3de0c3c5e31/meta.yaml' does not exist.
Traceback (most recent call last):
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 699, in _list_run_infos
    run_info = self._get_run_info_from_dir(r_dir)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 529, in _get_run_info_from_dir
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/media/ailabshare1/mlflow_test/0/509627168073427aaa51a3de0c3c5e31/meta.yaml' does not exist.
WARNING:root:Malformed run '6b080de05105476b99c02a0dae896e40'. Detailed error Yaml file '/media/ailabshare1/mlflow_test/0/6b080de05105476b99c02a0dae896e40/meta.yaml' does not exist.
Traceback (most recent call last):
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 699, in _list_run_infos
    run_info = self._get_run_info_from_dir(r_dir)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 529, in _get_run_info_from_dir
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/ailab/virtualenv-mlflow/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/media/ailabshare1/mlflow_test/0/6b080de05105476b99c02a0dae896e40/meta.yaml' does not exist.
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi could you try this and see how it works?

```python
# test.py

from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_iris

import mlflow

X, y = load_iris(return_X_y=True)

with mlflow.start_run():
    model = LinearRegression()
    model.fit(X, y)

    mlflow.sklearn.log_model(
        model, "model", registered_model_name="iris",
    )
```

How to run the script & lauch the UI:

```sh
export MLFLOW_TRACKING_URI=sqlite:///mlflow_temp.db
python test.py
mlflow ui --backend-store-uri=$MLFLOW_TRACKING_URI
```

**Comment by mat-l** [comment]
I have started mlflow on the server with your commands:
```
export MLFLOW_TRACKING_URI=sqlite:///mlflow_test.db
mlflow ui --backend-store-uri=$MLFLOW_TRACKING_URI
```

But I forgot to mention, that mlflow is running as a remote server and I am sending the model from a Win10 PC to the remote server. Therefore I have adjusted your example:
```
# test.py

from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_iris

import mlflow

registry_uri = 'sqlite:///mlflow.db'
tracking_uri = 'http://10.100.65.151:5000'

mlflow.tracking.set_registry_uri(registry_uri)
mlflow.tracking.set_tracking_uri(tracking_uri)

with mlflow.start_run():
    model = LinearRegression()
    model.fit(*load_iris(return_X_y=True))

    mlflow.sklearn.log_model(
        model, "model", registered_model_name="iris",
    )
```

It is sadly not working:
```
Connected to pydev debugger (build 203.5981.165)
Traceback (most recent call last):
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 972, in send
    self.connect()
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000012A0FFB9408>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.100.65.151', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012A0FFB9408>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\MYUSER\Sourcetree\virt_env_py37_mlflow\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.100.65.151', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012A0FFB9408>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))
python-BaseException

```

**Comment by jagdishponnada** [comment]
I am not able to see the models in the UI. I could see the metrics and holdout values.

**Comment by mat-l** [comment]
Any other ideas how to fix this problem?
@harupy @smurching or anybody else?
