### ISSUE TITLE
[SETUP-BUG] AttributeError while using command `mlflow ui`

### ISSUE THREAD

**Issue by VikingPathak** [mlflow/mlflow#4030]
I have successfully installed **MLFlow** using `pip install mlflow` but while running `mlflow ui` command in the console it gives the following **error**

```code
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

I am aware of the fact that `time.clock` is deprecated for `Python v3.8` and above. How can I fix this, as I don't want to downgrade python version.

**Comment by harupy** [comment]
Could you share the full error log?

**Comment by harupy** [comment]
Is this a SQLAlchemy issue?

https://github.com/sqlalchemy/sqlalchemy/issues/5305

**Comment by VikingPathak** [comment]
> @VikingPathak
> 
> Could you share the full error log?

@harupy  You can find the full log here -

```code
C:\Users\MAC Pathak>mlflow ui
Traceback (most recent call last):
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MAC Pathak\AppData\Local\Programs\Python\Python38-32\Scripts\mlflow.exe\__main__.py", line 4, in <module>
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\mlflow\cli.py", line 10, in <module>
    import mlflow.db
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\mlflow\db.py", line 3, in <module>
    import mlflow.store.db.utils
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\mlflow\store\db\utils.py", line 7, in <module>
    from alembic.migration import MigrationContext  # pylint: disable=import-error
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\alembic\__init__.py", line 3, in <module>
    from . import context  # noqa
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\alembic\context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\alembic\runtime\environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\alembic\runtime\migration.py", line 5, in <module>
    from sqlalchemy import Column
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\__init__.py", line 9, in <module>
    from .sql import (
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import (
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\sql\expression.py", line 33, in <module>
    from .visitors import Visitable
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\sql\visitors.py", line 28, in <module>
    from .. import util
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 8, in <module>
    from .compat import callable, cmp, reduce,  \
  File "c:\users\mac pathak\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 172, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by VikingPathak** [comment]
> Is this a SQLAlchemy issue?
> 
> [sqlalchemy/sqlalchemy#5305](https://github.com/sqlalchemy/sqlalchemy/issues/5305)
> 
> If so, upgrading SQLAlchemy should fix the error.
> 
> [sqlalchemy/sqlalchemy#5305 (comment)](https://github.com/sqlalchemy/sqlalchemy/issues/5305#issuecomment-623451647) says `time.clock` is no longer used.

@harupy  I am not sure if it is an SQLAlchemy issue. But I know python v3.8 has deprecated usage of `time.clock`. So the question stays how can I use the `mlflow ui` using Python v3.8

**Comment by harupy** [comment]
Can you update slqalchemy version]

**Comment by VikingPathak** [comment]
@harupy Hey thanks a lot. It worked.!! : )
