### ISSUE TITLE
[BUG] Cannot load multiple python_function models with the same script file name

### ISSUE THREAD

**Issue by potoo0** [mlflow/mlflow#4061]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution**: win10 20H2
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.13.1
- **Python version**: 3.8.5

### Describe the problem
Cannot load multiple python_function models with the same script file name in one file, it seems that the second loaded model did not download artifact.

### Code to reproduce issue
project tree:
```
$ tree
.
├── model1
│   ├── model_builder.py
│   └── regist_model1.py
├── model2
│   ├── model_builder.py
│   └── regist_model2.py
└── model_load.py

2 directories, 5 files
```
project files: mlflow_bug.zip
[mlflow_bug.zip](https://github.com/mlflow/mlflow/files/5924532/mlflow_bug.zip)

core script:
```
# model1.model_builder.py:
class Test1(mlflow.pyfunc.PythonModel):
    def __init__(self):
        super().__init__()

    def load_context(self, context):
        import numpy as np

        return

    def predict(self, context, model_input):
        '''
        Args:
            model_input: ndarray, shape: (-1)
        '''
        res = np.sum(model_input)

        return res


# model2.model_builder.py:
class Test2(mlflow.pyfunc.PythonModel):
    def __init__(self):
        super().__init__()

    def load_context(self, context):
        import numpy as np

        return

    def predict(self, context, model_input):
        '''
        Args:
            model_input: ndarray, shape: (-1)
        '''
        res = np.mean(model_input)

        return res


# model_load.py
import mlflow
import numpy as np
from mlflow.pyfunc import load_model

# config
tracking_server = 'http://localhost:8088'
mlflow.tracking.set_tracking_uri(tracking_server)

model_1_reg_name = 'pyfunc_model_t1'
model_2_reg_name = 'pyfunc_model_t2'
stage = None

# input
x = np.arange(1, 10)

# model inference
loadedml_1 = load_model(f"models:/{model_1_reg_name}/{stage}")
print(f'loadedml_1.pred: {loadedml_1.predict(x)}')

loadedml_2 = load_model(f"models:/{model_2_reg_name}/{stage}")
print(f'loadedml_2.pred: {loadedml_2.predict(x)}')
```

issue reproduce:
```powershell
cd xxx\mlflow_bug
# register model1
cd .\model1\
python .\regist_model1.py
# register model2
cd ..\model2\
python .\regist_model2.py
cd ..

# load two python_function
python .\model_load.py
```

### Other info / logs
```
loadedml_1.pred: 45
Traceback (most recent call last):
  File "E:\mlflow_bug\model_load.py", line 20, in <module>
    loadedml_2 = load_model(f"models:/{model_2_reg_name}/{stage}")
  File "D:\Miniconda3\lib\site-packages\mlflow\pyfunc\__init__.py", line 522, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "D:\Miniconda3\lib\site-packages\mlflow\pyfunc\model.py", line 223, in _load_pyfunc
    python_model = cloudpickle.load(f)
AttributeError: Can't get attribute 'Test2' on <module 'model_builder' from 'C:\\Users\\potoo\\AppData\\Local\\Temp\\tmps9pobp26\\code\\model_builder.py'>
```

**Comment by amnesiacandres** [comment]
+1 Observing same issue.

First model is loaded and additional code is imported. Then, the second model is loaded but uses previously imported functions if the file has the same name (model_builder.py in @potoo0's code above)

Best case scenario, using the incorrect function throws an error as in this bug. But is also possible that the code file from the first model contains a same named function that is compatible with the call and returns something the user did not intend to get.

**Comment by ablanchard** [comment]
I came across the same issue. This happened with models logged along with code using the `code_path` parameter (as [documented here](https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.log_model))

A workaround that can be used is to unload the python module before loading the 2nd model. This suppose to know the name of the module. For the example above, it would look like:
```
import sys
loadedml_1 = load_model(f"models:/{model_1_reg_name}/{stage}")
print(f'loadedml_1.pred: {loadedml_1.predict(x)}')

sys.modules.pop("model_builder", None)
loadedml_2 = load_model(f"models:/{model_2_reg_name}/{stage}")
print(f'loadedml_2.pred: {loadedml_2.predict(x)}')
```
The `sys.modules` contains all the current loaded modules ([documented here](https://docs.python.org/3/library/sys.html#sys.modules)). By removing our entry from this dict, we are making the module unavailable for the program.
The entry name is the same as the script name but more complex cases can occur like if the script linked others scripts in the code_path. Also the name of the module can collide with an already given name by another lib.
There is some edge cases to think about in order to make the fix inside mlflow.

**Comment by danielmarostica** [comment]
Firstly, thanks for saving my job.

Secondly, why hasn't this been fixed yet?

**Comment by kathryn-baker** [comment]
Hi there, has there been any progress on this? I am trying to compare two models trained in different directories (and therefore with slightly different directory structures when saving the models with the `code_path` parameters. In my current set up, I am unable to load the two models within the same file without the second model defaulting to use the modules loaded by the first model rather than its own. 

I can resolve the issue for now by removing the modules from the path as suggested above:
```python
for key in list(sys.modules.keys()):
    value = sys.modules[key]
    if 'tmp' in str(value):
        sys.modules.pop(key)
```
However this doesn't seem to be the most user-friendly solution as I think most users would assume you could load models from different locations without issue. 

```
mlflow == 2.6.0
python == 3.10.13
```
