### ISSUE TITLE
mlflow serve not working, getting "AttributeError: module 'types' has no attribute 'ClassType'"

### ISSUE THREAD

**Issue by itachiRedhair** [mlflow/mlflow#4092]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:docker image-> continuumio/miniconda3
- **MLflow installed from (source or binary)**:source
- **MLflow version (run ``mlflow --version``)**:1.11.0
- **Python version**:3.7.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:mlflow models serve -m ./custom-pyfunc-model --port 5000

### Describe the problem
I have created a Pyfunc model that calls sk-learn model to predict. When I download model artifacts and run mlflow serve from local I get the following error:
<details>
  <summary>Error</summary>
  
[2021-02-11 12:30:21 +0000] [24] [INFO] Starting gunicorn 20.0.4
[2021-02-11 12:30:21 +0000] [24] [INFO] Listening at: http://127.0.0.1:8000 (24)
[2021-02-11 12:30:21 +0000] [24] [INFO] Using worker: gevent
[2021-02-11 12:30:21 +0000] [37] [INFO] Booting worker with pid: 37
[2021-02-11 12:30:21 +0000] [38] [INFO] Booting worker with pid: 38
[2021-02-11 12:30:24 +0000] [38] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/miniconda/envs/custom_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/models/container/scoring_server/wsgi.py", line 4, in <module>
    app = scoring_server.init(pyfunc.load_pyfunc("/opt/ml/model/"))
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 42, in deprecated_func
    return func(*args, **kwargs)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 548, in load_pyfunc
    return load_model(model_uri, suppress_warnings)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 522, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/model.py", line 223, in _load_pyfunc
    python_model = cloudpickle.load(f)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 415, in _builtin_type
    return getattr(types, name)
AttributeError: module 'types' has no attribute 'ClassType'
[2021-02-11 12:30:24 +0000] [38] [INFO] Worker exiting (pid: 38)
[2021-02-11 12:30:24 +0000] [37] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/miniconda/envs/custom_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/models/container/scoring_server/wsgi.py", line 4, in <module>
    app = scoring_server.init(pyfunc.load_pyfunc("/opt/ml/model/"))
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 42, in deprecated_func
    return func(*args, **kwargs)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 548, in load_pyfunc
    return load_model(model_uri, suppress_warnings)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 522, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/mlflow/pyfunc/model.py", line 223, in _load_pyfunc
    python_model = cloudpickle.load(f)
  File "/miniconda/envs/custom_env/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 415, in _builtin_type
    return getattr(types, name)
AttributeError: module 'types' has no attribute 'ClassType'
</details>

### Code to reproduce issue
```
class CustomPyFuncModel(mlflow.pyfunc.PythonModel):
    def __init__(self, model, age_mul_factor, pre_process, post_process):
        self.model = model
        self.pre_process = pre_process
        self.post_process = post_process

    def predict(self, context, model_input):
        model_input_processed = self.pre_process(model_input,self.age_mul_factor)       
        
        obj = self.model.predict(model_input_processed)
        x = self.post_process(obj)
        return x
```
```
custom_pyfunc_model_conda_env = {
 'name': 'mlflow-env',
 'channels': ['defaults', 'conda-forge'],
 'dependencies': [
   f'python={python_version}', 
   'pip',
   f'scikit-learn={sklearn.__version__}',
   {
     'pip': [
       f'mlflow',
       f'cloudpickle=={cloudpickle.__version__}'
     ]
   }
  ]
}
```
Block that trains the model:
```
  with mlflow.start_run() as run:
    lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
    lr.fit(train_x, train_y)
    
    mlflow.log_param("alpha", alpha)
    mlflow.log_param("l1_ratio", l1_ratio)
    
    mlflow.sklearn.log_model(lr, "model")
    
  with mlflow.start_run() as run:
    custom_pyfunc_model = CustomPyFuncModel(
      model=lr, 
      pre_process=pre_process, 
      post_process=post_process
    )

    mlflow.log_param("alpha", alpha)
    mlflow.log_param("l1_ratio", l1_ratio)
    
    mlflow.pyfunc.log_model(
                            artifact_path = "model",
                            python_model = custom_pyfunc_model,
                            conda_env = custom_pyfunc_model_conda_env
    )
    
```
After this, I download the model artifacts from the run page and run following command:
```
mlflow models serve -m ./model --port 5000
```
And this gives the above error.
Note that when I serve the model within databricks, it works.

### Other info / logs
To me this seems like a library version issue, most likely with cloudpickle. I used the exact same libraries that I used to train the model and then served the model locally.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors

**Comment by dmatrix** [comment]
@itachiRedhair Thanks for filing this. A couple of things.

First, can you provide a full listing, to reproduce the code? Second, you don't need to download the artifacts from the UI. You just
have to provide `runs://URI` to the option. This is in the form of `-m runs:/<run_id>/model`

**Comment by itachiRedhair** [comment]
@dmatrix  thanks for replying. I am using databricks to run MLflow. My ultimate goal is to automate the download of the model dockerize the model serving. 
I have provided missing part of code. 
When I serve sklearn logged model it works, but it fails for wrapper pyfunc model.

**Comment by itachiRedhair** [comment]
Hi @dmatrix,  did you get a chance to have a detailed look?
I also tried using `mlflow models build-docker` and the resulting docker image when run gives the same error as when I tried on local with `mlflow serve`
