### ISSUE TITLE
mlflow models serve fails with 'FileNotFoundError: [Errno 2] No such file or directory: /tmp/tmpv459n53j/MLmodel/MLmodel'

### ISSUE THREAD

**Issue by akhiljain794** [mlflow/mlflow#4104]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15.6
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.13.1
- **Python version**: 3.8.5
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: mlflow models serve -m "models:/SeasonalAD/1" -p 1234

### Describe the problem
Mlflow details-
I have mlflow running in k8s container with s3 storage (models being stored at s3://mlflow/ bucket) on a remote cluster.
On my mac:
I have a custom anomaly detection python class with training and prediction method. I am using jupyter notebook(running on my mac) to train and save the model.
I have set suitable env variables from my jupyter notebook to communicate to remote mlflow process. Below vars are set -
import os
os.environ["MLFLOW_S3_ENDPOINT_URL"]="XXXX"
os.environ["AWS_ACCESS_KEY_ID"]="XXXX"
os.environ["AWS_SECRET_ACCESS_KEY"]="XXXX"
os.environ["MLFLOW_TRACKING_INSECURE_TLS"]="true"
os.environ["MLFLOW_TRACKING_URI"]="XXXX"
import mlflow
mlflow.set_experiment("aj-experiment")

I am training this model using a sample data and registering the model using below command-
mlflow.pyfunc.log_model(artifact_path="seasonalAD",python_model=seasonalADTrained, registered_model_name="SeasonalAD")

Model is successfully registered and I can view the model from s3 minIO UI under **Models** tab. Following are the contents-
seasonalAD
  |--MLModel
  |--conda.yaml
  |--python_model.pkl

Now, when I try to serve this model as a REST API through cli from my mac it is giving me below trace-

(base) akhiljain@akhil-jain ~ % mlflow models serve -m "models:/SeasonalAD/1" -p 1234
/Users/akhiljain/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'XXXX'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/Users/akhiljain/miniconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/cli.py", line 55, in serve
    return _get_flavor_backend(
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/cli.py", line 180, in _get_flavor_backend
    model = Model.load(local_path)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/model.py", line 112, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpv459n53j/MLmodel/MLmodel'

Expected behavior: Serve a model saved with MLflow by launching a webserver on the specified port

### Code to reproduce issue
import pandas as pd
import numpy as np
import mlflow.pyfunc
df = pd.read_csv("data/seasonal.csv", index_col="Time", parse_dates=True)
df_train = df.iloc[0:7000]
from SeasonalAD_class_mlflow import SeasonalAD
seasonalADTrained = SeasonalAD(adjust_trend = False)
df_train_r, anomalies_f =  seasonalADTrained.fit(df_train["Traffic"],return_result=True)
with mlflow.start_run():
    mlflow.pyfunc.log_model(artifact_path="seasonalAD",python_model=seasonalADTrained,
                        registered_model_name="SeasonalAD")

### Other info / logs
This issue comes even when I try to serve model as REST API created by running the ElasticnetWineModel tutorial present on mlflow documentation page.
(base) akhiljain@akhil-jain ~ % mlflow models serve -m "models:/ElasticnetWineModel/1" -p 1234
/Users/akhiljain/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'XXXX'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/Users/akhiljain/miniconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/cli.py", line 55, in serve
    return _get_flavor_backend(
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/cli.py", line 180, in _get_flavor_backend
    model = Model.load(local_path)
  File "/Users/akhiljain/miniconda3/lib/python3.8/site-packages/mlflow/models/model.py", line 112, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpjakqqrk7/MLmodel/MLmodel'

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors

**Comment by akhiljain794** [comment]
Can some one help and look into this issue ?

**Comment by joeltorby** [comment]
I have not used `log_model `specifically, but I had similar 'cryptical' error message for `mlflow.log_text(..)`. After some day struggling I noticed that the artifact_file needed to have "/" and not "\\" -> `"folder/text.txt"` will work but not "mlfolder\text.txt". 

When using `mlflow.log_artifact()` and giving `artifact_file` parameter one need to only give folder name ` "mlfolder"` but not "mlfolder/artifact.pkl").

I would guess that your error with log_model is something similar as this.

I would suggest some improved error messages are implemented from the mlflow team :)

**Comment by Perkzi** [comment]
> I have not used `log_model `specifically, but I had similar 'cryptical' error message for `mlflow.log_text(..)`. After some day struggling I noticed that the artifact_file needed to have "/" and not "\" -> `"folder/text.txt"` will work but not "mlfolder\text.txt".
> 
> When using `mlflow.log_artifact()` and giving `artifact_file` parameter one need to only give folder name ` "mlfolder"` but not "mlfolder/artifact.pkl").
> 
> I would guess that your error with log_model is something similar as this.
> 
> I would suggest some improved error messages are implemented from the mlflow team :)

I tried to run mlflow.spark in windows 10 , and I face the error of separator '\' when I use mlflow.spark.log_model. 
It seems that I can only do it on Linux. 😟
