### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by KangTomwk** [mlflow/mlflow#4128]
Hello all， When I started mlflow tracking server, the following error occurred FileNotFoundError: [Errno 2] No such file or directory: 'gunicorn' ：

### System information
- **OS Platform and Distribution (e.g., Linux Centos7.7)**:
- **MLflow installed from (source or binary)**:
- **MLflow version =1.13.1**:
- **Python version=3.8.5**:
- **Exact command to reproduce**:

### Describe the problem
Traceback (most recent call last):
  File "/root/anaconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/mlflow/cli.py", line 392, in server
    _run_server(
  File "/root/anaconda3/lib/python3.8/site-packages/mlflow/server/__init__.py", line 138, in _run_server
    exec_cmd(full_command, env=env_map, stream_output=True)
  File "/root/anaconda3/lib/python3.8/site-packages/mlflow/utils/process.py", line 34, in exec_cmd
    child = subprocess.Popen(
  File "/root/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gunicorn' 

But there is gunicorn command in my system, Why does it still report this error？

**Comment by dmatrix** [comment]
@KangTomwk Can you do a `which gunicorn` to see what you get and if that path is in your PATH? Do you get `/usr/local/bin/gunicorn`?

**Comment by FlMart** [comment]
Hi everyone, having the same issue here.


- OS Platform and Distribution (e.g., Linux Centos7.7): Manjaro 21.3.7
- MLflow installed from (source or binary): Installed with `python -m pip install mlflow`
- MLflow version =1.26.1:
- Python version=3.10.5:
- Exact command to reproduce:

Output of `mlflow server`:
```bash
/home/flo/.local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/flo/.local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/flo/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/flo/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/flo/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/flo/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/flo/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/flo/.local/lib/python3.10/site-packages/mlflow/cli.py", line 433, in server
    _run_server(
  File "/home/flo/.local/lib/python3.10/site-packages/mlflow/server/__init__.py", line 150, in _run_server
    _exec_cmd(full_command, extra_env=env_map, capture_output=False)
  File "/home/flo/.local/lib/python3.10/site-packages/mlflow/utils/process.py", line 76, in _exec_cmd
    process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gunicorn'
```
Output of `which mlflow`: `/home/flo/.local/bin/mlflow`
Output of `which gunicorn`: `/home/flo/.local/bin/gunicorn`
Output of `which python`: `/usr/bin/python`

I think I adapted the python path when I first installed first, so `cat $(which mlflow) | head -n 1` reads `#!/usr/bin/python` - not sure what it originally was. Maybe that is related to the issue?

**Comment by bkocis** [comment]
Make sure you activate the correct virtual environment where mlflow is installed.

**Comment by shawnjb** [comment]
If you are using a virtual environment, make sure you are in the right environment before running the mlflow command.

Also, it's worth checking to see if gunicorn is installed in the correct environment by running `pip list` or `conda list`, and verify that gunicorn is listed. You could also try running the command with the full path to gunicorn like `/usr/local/bin/gunicorn` to check if the command is present in the system.
