### ISSUE TITLE
[FR] Allow argument for 'local_dst_path' when loading Pyfunc Models

### ISSUE THREAD

**Issue by ameya-parab** [mlflow/mlflow#4154]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Currently, the 'mlflow.pyfunc.load_model(MODEL_URI)' just accepts the remote model URI (S3 in our case) when trying to load a Python flavored MLFlow model and its artifacts. As part of this call, the load_model method, downloads the artifacts registered when logging the MLFLow model to a temporary directory in the local filesystem for serving. I would like to open a feature request, to allow specifying a local path when calling the load_model function, this would enable the users to download the artifacts and the model to a specific location for further analysis.

## Motivation
- What is the use case for this feature?
      - Enables downloading the remote model and its artifacts to a specified location which caters to reduced model loading 
         times as the model is directly loaded from a local file path and can be reused by other programs, if required.
- Why is this use case valuable to support for MLflow users in general?
      - The feature will reduce the overall model serving time for large models as the artifacts and the model itself would be 
         available at a local filesystem path for multiple programs to use.
- Why is this use case valuable to support for your project(s) or organization?
      - This will help us to tackle the long loading times when iniializing the model serving framework as our production 
         deployment consists of ensemble of models rather than a single model.
- Why is it currently difficult to achieve this use case?
      - We have a workaround in place to shutil the models and their artifacts from the temporary directories to a different 
         location everytime it is initialized by a program, this is not optimized and can be error prone.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

```python
import mlflow

LOGGED_MODEL_S3_URI : "s3://buckeet/path/to/the/model/artifacts"

# Current API Call
model = mlflow.pyfunc.load_model(LOGGED_MODEL_S3_URI)

# Proposed API Call
model = mlflow.pyfunc.load_model(
                    LOGGED_MODEL_S3_URI, 
                    local_dst_path=os.path.join(os.path.expanduser("~"), "model")
               )
```

## Proposed solution

Changes in pyfunc.__init__.py

```python

# Current load_model implementation

def load_model(model_uri: str, suppress_warnings: bool = True) -> PyFuncModel:
    """
    Load a model stored in Python function format.

    :param model_uri: The location, in URI format, of the MLflow model. For example:

                      - ``/Users/me/path/to/local/model``
                      - ``relative/path/to/local/model``
                      - ``s3://my_bucket/path/to/model``
                      - ``runs:/<mlflow_run_id>/run-relative/path/to/model``
                      - ``models:/<model_name>/<model_version>``
                      - ``models:/<model_name>/<stage>``

                      For more information about supported URI schemes, see
                      `Referencing Artifacts <https://www.mlflow.org/docs/latest/concepts.html#
                      artifact-locations>`_.
    :param suppress_warnings: If ``True``, non-fatal warning messages associated with the model
                              loading process will be suppressed. If ``False``, these warning
                              messages will be emitted.
    """
    local_path = _download_artifact_from_uri(artifact_uri=model_uri)
    model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))

    conf = model_meta.flavors.get(FLAVOR_NAME)
    if conf is None:
        raise MlflowException(
            'Model does not have the "{flavor_name}" flavor'.format(flavor_name=FLAVOR_NAME),
            RESOURCE_DOES_NOT_EXIST,
        )
    model_py_version = conf.get(PY_VERSION)
    if not suppress_warnings:
        _warn_potentially_incompatible_py_version_if_necessary(model_py_version=model_py_version)
    if CODE in conf and conf[CODE]:
        code_path = os.path.join(local_path, conf[CODE])
        mlflow.pyfunc.utils._add_code_to_system_path(code_path=code_path)
    data_path = os.path.join(local_path, conf[DATA]) if (DATA in conf) else local_path
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
    return PyFuncModel(model_meta=model_meta, model_impl=model_impl)


# Proposed load_model implementation

def load_model(model_uri: str, local_dst_path: str = None, suppress_warnings: bool = True) -> PyFuncModel:
    """
    Load a model stored in Python function format.

    :param model_uri: The location, in URI format, of the MLflow model. For example:

                      - ``/Users/me/path/to/local/model``
                      - ``relative/path/to/local/model``
                      - ``s3://my_bucket/path/to/model``
                      - ``runs:/<mlflow_run_id>/run-relative/path/to/model``
                      - ``models:/<model_name>/<model_version>``
                      - ``models:/<model_name>/<stage>``

                      For more information about supported URI schemes, see
                      `Referencing Artifacts <https://www.mlflow.org/docs/latest/concepts.html#
                      artifact-locations>`_.
    :param local_dst_path: The local file system path to download model and its artifacts. 
                              Defaults to `None`.
    :param suppress_warnings: If ``True``, non-fatal warning messages associated with the model
                              loading process will be suppressed. If ``False``, these warning
                              messages will be emitted.
    """
    local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=local_dst_path)
    model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))

    conf = model_meta.flavors.get(FLAVOR_NAME)
    if conf is None:
        raise MlflowException(
            'Model does not have the "{flavor_name}" flavor'.format(flavor_name=FLAVOR_NAME),
            RESOURCE_DOES_NOT_EXIST,
        )
    model_py_version = conf.get(PY_VERSION)
    if not suppress_warnings:
        _warn_potentially_incompatible_py_version_if_necessary(model_py_version=model_py_version)
    if CODE in conf and conf[CODE]:
        code_path = os.path.join(local_path, conf[CODE])
        mlflow.pyfunc.utils._add_code_to_system_path(code_path=code_path)
    data_path = os.path.join(local_path, conf[DATA]) if (DATA in conf) else local_path
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
    return PyFuncModel(model_meta=model_meta, model_impl=model_impl)
```

**Comment by dmatrix** [comment]
@ameyaparab28 Thanks for filing this feature request. By local filesystem, you mean FS available on your production server machine. Do you want to load those models from that local FS path on the production server's FS rather than loading it from the S3 for each model?

This seems like a good first issue since most of what you suggest might work. Do you want to contribute?

cc: @harupy

**Comment by dmatrix** [comment]
@ankh6 Yes, we welcome contributions. This is an API change so we have to ensure backward compatibility too. 
@ameya-parab are you working on this?

**Comment by ameya-parab** [comment]
@dmatrix, I was planning on working on the issue and would create a PR in a couple of weeks. Thanks!

**Comment by ameya-parab** [comment]
@dmatrix ...I was working on running through the linter and unit tests before raising a PR but ran into a bunch of Package import and other errors. I have pasted the bash output below:

source lint.sh

```bash
========== pycodestyle ==========

mlflow tests:1:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'mlflow tests'

========== pylint ==========

Using config file /Users/parabam1/Projects/OpenSource/mlflow/pylintrc
************* Module mlflow.mlflow
mlflow/__init__.py (30,0): [E0611 no-name-in-module] No name 'version' in module 'mlflow'

.
.
.


========== rstcheck ==========

Traceback (most recent call last):
  File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/bin/rstcheck", line 8, in <module>
    sys.exit(main())
  File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/rstcheck.py", line 918, in main
    with enable_sphinx_if_possible():
  File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/rstcheck.py", line 876, in enable_sphinx_if_possible
    status=None)
  File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/sphinx/application.py", line 172, in __init__
    raise ApplicationError(__('Source directory and destination '
sphinx.errors.ApplicationError: Source directory and destination directory cannot be identical

One of the previous steps failed, check above
```

I have setup my development env using the instructions mentioned over [here](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#developing-and-testing-mlflow).

**Comment by dmatrix** [comment]
@ameya-parab can you try resync with the master and merge changes into your branch?

**Comment by enertel** [comment]
if there hasn't been any movement on this issue I'd be willing to pick it up!

@ameya-parab do you still plan to open a PR for this?

**Comment by ameya-parab** [comment]
@enertel - I was not able to work on the issue, please feel to take it forward. Thanks!

**Comment by huxuan** [comment]
> ========== rstcheck ==========
> 
> Traceback (most recent call last):
>   File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/bin/rstcheck", line 8, in <module>
>     sys.exit(main())
>   File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/rstcheck.py", line 918, in main
>     with enable_sphinx_if_possible():
>   File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/rstcheck.py", line 876, in enable_sphinx_if_possible
>     status=None)
>   File "/Users/parabam1/miniconda3/envs/mlflow-dev-env/lib/python3.6/site-packages/sphinx/application.py", line 172, in __init__
>     raise ApplicationError(__('Source directory and destination '
> sphinx.errors.ApplicationError: Source directory and destination directory cannot be identical

Sorry for potential OT.

I encountered same rstcheck error after following the contribution guide. Please let me know if there is a solution.

**Comment by NickSmyr** [comment]
Hello,

Is this issue still relevant? Me and [Neproxx](https://github.com/Neproxx) are willing to work on this. We are especially interested in the integration with Azure and SageMaker

**Comment by ameya-parab** [comment]
The issue seems still relevant if using mlflow, but on our project we ended up using TorchServe to host our models.

**Comment by Ankur-singh** [comment]
Is anyone working on this ? I am interested in GCS integration.

**Comment by rafaelvp-db** [comment]
instead of making this change, would any of the alternatives below make sense?

- running pyfunc.load_model from your different applications
- download the artifacts with load_model -> push them into another S3 bucket -> other applications download it
- same as previous,  but pushing to an NFS drive and mounting it wherever applications need to load it
- downloading the artifacts, packaging it with docker and making it available to these applications (either standalone or a as a base image)

telling MLflow backend to download model artifacts from S3 into its own storage doesn't seem to make a lot of sense to me compared with these options

**Comment by TomeHirata** [comment]
Hi, all. To download the model artifact to your local file system and use it across multiple models, can you do the following? The `mlflow.artifacts.download_artifacts` API allows you to download artifacts into a specified location, and `mlflow.pyfunc.load_model` can load the model from your local file system. Please let me know if this does not work! Thank you.

```python
path = mlflow.artifacts.download_artifacts("your model artifact", dst_path="your local file system")
model = mlflow.pyfunc.load_model(path)
```

**Comment by serena-ruan** [comment]
`dst_path` can be specified when loading pyfunc models now to support downloading the model to your specified local file path: https://github.com/mlflow/mlflow/blob/818dea7c0a05ca9317873214856c0e5217751049/mlflow/pyfunc/__init__.py#L1068
Close this ticket
