### ISSUE TITLE
[mlflow ui] FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by VikingPathak** [mlflow/mlflow#4175]
After successfully installing mlflow using `pip install mlflow` on my Windows system, I am trying to run the `mlflow ui` command but it throws the following error.
```code
(base) C:\Users\MAC Pathak\Documents\Projects\kaggle_stroke_prediction>mlflow ui
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Users\MAC Pathak\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\MAC Pathak\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\MAC Pathak\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\MAC Pathak\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\MAC Pathak\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\cli.py", line 280, in ui
    _run_server(backend_store_uri, default_artifact_root, host, port, None, 1)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\server\__init__.py", line 138, in _run_server
    exec_cmd(full_command, env=env_map, stream_output=True)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\utils\process.py", line 34, in exec_cmd
    child = subprocess.Popen(
  File "c:\programdata\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dmatrix** [comment]
@VikingPathak Seems like a PATH-related issue? Can ensure all the installed binaries are accessible via your $PATH variable on Windows?

**Comment by VikingPathak** [comment]
@dmatrix  The only path variable that I have provided manually is the `mlflow.exe` file in the variable name `MLFLOW_BIN`

**Comment by VikingPathak** [comment]
> @VikingPathak Seems like a PATH-related issue? Can ensure all the installed binaries are accessible via your $PATH variable on Windows?

@dmatrix  The only path variable that I have provided manually is the `mlflow.exe` file in the variable name `MLFLOW_BIN`

**Comment by nerubenstein** [comment]
I'm having the same problem on Windows

**Comment by skalra-v** [comment]
+1 
Got same error on windows server 2012 + python 3.6 
works on windows 10 + python 3.6

**Comment by YitongZhou** [comment]
the same issue on win10

**Comment by VikingPathak** [comment]
Nothing worked for me unfortunately on my local machine, but however, things worked out smooth when using it on a Linux system in Azure. So I never tried again locally.

**Comment by ak10net** [comment]
Add path location of mlflow package to your environment variables if global install check if mlflow is in C:\Users\user\AppData\Roaming\Python\Python37\site-packages. 

If you are using Virtualenv use that path such as S:\dir\venv\Lib\site-packages\mlflow.

If problem still persists. Clear pip chache with 'pip cache purge' and redo the above steps.

**Comment by bambinobino** [comment]
Any update on this issue? I am experiencing the same error on Windows 10 and python 3.7

**Comment by huidiwiwi** [comment]
I'm facing the same problem. `mlflow` works but `mlflow ui` return the same error. 

when I **uninstall waitress, mlflow** and then **reinstall mlflow**, it works then. see [**here**](https://stackoverflow.com/a/66733355). 

It seems like there is some version conflict of waitress if you have installed mlflow before. I guess uninstall mlflow will not automatically cleanup waitress. 
ps: I got mlflow command not recognized at first.(installed mlflow in a new conda env). After I uninstalled the mlflow from root, then reinstall it in the env, it works.

**Comment by demongolem-biz** [comment]
Same stack trace.  Is this a Windows-only problem and we should try to use Linux?  I am running mlflow 2.0.1.
