### ISSUE TITLE
 Run id not found exception when using set tracking uri

### ISSUE THREAD

**Issue by sirikorakoppula** [mlflow/mlflow#4176]
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

HI TEAM,
 Without setting tracking uri able to generate metrics, below is the command we tried
mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=0.2 --run-id  ecb8e7c8dfbc418cb211e7703fb61d4c 

when  i set an tracking uri to store model registry getting not found exception like below ***
#Use sqlite:///mlruns.db as the local store for tracking and registery
 mlflow.set_tracking_uri("sqlite:///mlruns.db")
PLEASE REFER BELOW ERROR**

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

**(base)** C:\Users\lenovo\Desktop\mlflow>mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=0.2 --run-id 810be4e0ce7c40f08a341357e7d72dd7
2021/03/15 10:53:28 INFO mlflow.projects.utils: === Fetching project from https://github.com/mlflow/mlflow-example.git into C:\Users\lenovo\AppData\Local\Temp\tmp5rbw24dd ===
2021/03/15 10:53:33 INFO mlflow.projects.utils: === Created directory C:\Users\lenovo\AppData\Local\Temp\tmpz2urzd3d for downloading remote URIs passed to arguments of type 'path' ===
2021/03/15 10:53:33 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-1abc00771765dd9dd15731cbda4938c765fbb90b && python train.py 0.2 0.1' in run with ID '810be4e0ce7c40f08a341357e7d72dd7' ===
C:\Users\lenovo\anaconda3\envs\mlflow-1abc00771765dd9dd15731cbda4938c765fbb90b\lib\site-packages\sklearn\utils\__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence
C:\Users\lenovo\anaconda3\envs\mlflow-1abc00771765dd9dd15731cbda4938c765fbb90b\lib\site-packages\sklearn\model_selection\_split.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
C:\Users\lenovo\anaconda3\envs\mlflow-1abc00771765dd9dd15731cbda4938c765fbb90b\lib\site-packages\sklearn\model_selection\_search.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, namedtuple, defaultdict, Sequence
Elasticnet model (alpha=0.200000, l1_ratio=0.100000):
  RMSE: 0.7836984021909766
  MAE: 0.6142020452688988
  R2: 0.20673590971167466
2021/03/15 10:53:35 INFO mlflow.projects: === Run (ID '810be4e0ce7c40f08a341357e7d72dd7') succeeded ===

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

HI TEAM,

when  i set an tracking uri to store model registry getting not found exception like below ***
PLEASE REFER BELOW ERROR**

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
(base) C:\Users\lenovo\Desktop\mlflow>mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=0.2 --run-id  7d92ea4ed32f44369cdabee824d396e3
2021/03/15 11:50:17 INFO mlflow.projects.utils: === Fetching project from https://github.com/mlflow/mlflow-example.git into C:\Users\lenovo\AppData\Local\Temp\tmp8cchydu9 ===
Traceback (most recent call last):
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\anaconda3\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\cli.py", line 168, in run
    projects.run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 293, in run
    submitted_run_obj = _run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 92, in _run
    submitted_run = backend.run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\backend\local.py", line 51, in run
    active_run = get_or_create_run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\utils.py", line 219, in get_or_create_run
    return tracking.MlflowClient().get_run(run_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\tracking\client.py", line 142, in get_run
    return self._tracking_client.get_run(run_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 54, in get_run
    return self.store.get_run(run_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 497, in get_run
    run_info = self._get_run_info(run_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 516, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run '7d92ea4ed32f44369cdabee824d396e3' not found

**Comment by dmatrix** [comment]
@sirikorakoppula Where are you setting the tracking ur?

If you clone the git and change train.py and add as follows:

 ```
...
    mlflow.set_tracking_uri("sqlite:///mlruns.db")
    with mlflow.start_run():
        lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
        lr.fit(train_x, train_y)

        predicted_qualities = lr.predict(test_x)
...
```

Then run ` mlflow run . -e main -P alpha=0.2`. It should work.

![Screen Shot 2021-03-15 at 10 23 45 AM](https://user-images.githubusercontent.com/1117597/111194570-922e2700-8578-11eb-9a9e-e47e870a3706.png)

**Comment by sirikorakoppula** [comment]
Thanks for the response..
tried the way you were posted but its not working, could you please check.

(base) C:\Users\lenovo\Downloads\mlflow-example-master\mlflow-example-master\src>mlflow run . -e main -P alpha=0.2
Traceback (most recent call last):
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\anaconda3\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lenovo\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\cli.py", line 168, in run
    projects.run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 293, in run
    submitted_run_obj = _run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\__init__.py", line 92, in _run
    submitted_run = backend.run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\backend\local.py", line 51, in run
    active_run = get_or_create_run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\utils.py", line 221, in get_or_create_run
    return _create_run(uri, experiment_id, work_dir, version, entry_point, parameters)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\projects\utils.py", line 261, in _create_run
    active_run = tracking.MlflowClient().create_run(experiment_id=experiment_id, tags=tags)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\tracking\client.py", line 252, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 89, in create_run
    return self.store.create_run(
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 455, in create_run
    experiment = self.get_experiment(experiment_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 336, in get_experiment
    experiment = self._get_experiment(experiment_id)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 309, in _get_experiment
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "c:\users\lenovo\anaconda3\lib\site-packages\mlflow\utils\file_utils.py", line 170, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\lenovo\Downloads\mlflow-example-master\mlflow-example-master\src\mlruns\0\meta.yaml' does not exist.

----------------------------------------------------------------------------------------------------------------------------------------------
I'm setting tracking uri here..,

import os
import warnings
import sys
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
import mlflow
import mlflow.sklearn


def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2



if __name__ == "__main__":
 
    warnings.filterwarnings("ignore")
    np.random.seed(40)

    # Read the wine-quality csv file (make sure you're running this from the root of MLflow!)
    wine_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "wine-quality.csv")
    data = pd.read_csv(wine_path)

    # Split the data into training and test sets. (0.75, 0.25) split.
    train, test = train_test_split(data)

    # The predicted column is "quality" which is a scalar from [3, 9]
    train_x = train.drop(["quality"], axis=1)
    test_x = test.drop(["quality"], axis=1)
    train_y = train[["quality"]]
    test_y = test[["quality"]]

    alpha = float(sys.argv[1]) if len(sys.argv) > 1 else 0.5
    l1_ratio = float(sys.argv[2]) if len(sys.argv) > 2 else 0.5

    mlflow.set_tracking_uri("sqlite:///mlruns.db")
    with mlflow.start_run():
        lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
        lr.fit(train_x, train_y)

        predicted_qualities = lr.predict(test_x)

        (rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)

        print("Elasticnet model (alpha=%f, l1_ratio=%f):" % (alpha, l1_ratio))
        print("  RMSE: %s" % rmse)
        print("  MAE: %s" % mae)
        print("  R2: %s" % r2)

        mlflow.log_param("alpha", alpha)
        mlflow.log_param("l1_ratio", l1_ratio)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("r2", r2)
        mlflow.log_metric("mae", mae)

        mlflow.sklearn.log_model(lr, "model")

**Comment by afanzott** [comment]
Hello, I have exactly the same issue. I'm running mlflow locally with /mlruns as artifact and backend store and everything works fine, but when I input 

`tracking_uri = "sqlite:///" + os.getcwd() + "/setup/mlruns.db"`
`mlflow.set_tracking_uri(tracking_uri)`

before `with mlflow.start_run():` I get the same error stating, that he can't find the RUN_id. 
I tried literally everything to fix it, but couldn't find a way.

`Traceback (most recent call last):
  File "train.py", line 82, in <module>
    with mlflow.start_run():
  File "/Users/afanzott/opt/miniconda3/envs/mlflow-4108a81c3d90d249d08cb8038c21ac8fa1a8d153/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 266, in start_run
    active_run_obj = client.get_run(existing_run_id)
  File "/Users/afanzott/opt/miniconda3/envs/mlflow-4108a81c3d90d249d08cb8038c21ac8fa1a8d153/lib/python3.8/site-packages/mlflow/tracking/client.py", line 150, in get_run
    return self._tracking_client.get_run(run_id)
  File "/Users/afanzott/opt/miniconda3/envs/mlflow-4108a81c3d90d249d08cb8038c21ac8fa1a8d153/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "/Users/afanzott/opt/miniconda3/envs/mlflow-4108a81c3d90d249d08cb8038c21ac8fa1a8d153/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 568, in get_run
    run = self._get_run(run_uuid=run_id, session=session, eager=True)
  File "/Users/afanzott/opt/miniconda3/envs/mlflow-4108a81c3d90d249d08cb8038c21ac8fa1a8d153/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 487, in _get_run
    raise MlflowException(
mlflow.exceptions.MlflowException: Run with id=3fdcfe4924ce454bbed21329061e1ca9 not found
2022/08/24 13:18:27 ERROR mlflow.cli: === Run (ID '3fdcfe4924ce454bbed21329061e1ca9') failed ===`

**Comment by zimonitrome** [comment]
Bumping again in contemplation of opening a new issue.

This is my full stack trace:

```
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/runner/runner.py", line 395, in __init__
    self.visualizer.add_config(self.cfg)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/dist/utils.py", line 366, in wrapper
    return func(*args, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/visualizer.py", line 1068, in add_config
    vis_backend.add_config(config, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/vis_backend.py", line 59, in wrapper
    return old_func(obj, *args, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/vis_backend.py", line 751, in add_config
    self._mlflow.log_params(self._flatten(self.cfg))
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 700, in log_params
    run_id = _get_or_start_run().info.run_id
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1552, in _get_or_start_run
    return start_run()
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 288, in start_run
    active_run_obj = client.get_run(existing_run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/client.py", line 158, in get_run
    return self._tracking_client.get_run(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 647, in get_run
    run_info = self._get_run_info(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 670, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run 'ab60ea7aad944e098edf9bef7c80f8bd' not found
```

I am using an mmlabs script that does not explicitly use a `with mlflow.start_run() as run:`, but instead just uses `self._mlflow.log_params()` like we can see in the stack trace. But this shouldn't be a problem since it seem to call `_get_or_start_run()` to create a run if needed.

I feel like it could be something like what is suggested here: https://github.com/mlflow/mlflow/issues/8233#issuecomment-1511242999
But I've never had to `export MLFLOW_TRACKING_URI=...` before. Other scripts that use `with mlflow.start_run() as run:` seem to integrate with my local databricks cli tool (where I have set up my tokens etc.) whenever I specify `mlflow.set_tracking_uri("databricks")` or `os.environ["MLFLOW_TRACKING_URI"] = "databricks"`.

Any help? Please
