### ISSUE TITLE
[SETUP-BUG] MLFLOW database session expires for AWS RDS Serverless database

### ISSUE THREAD

**Issue by 1pyroaqua** [mlflow/mlflow#4196]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.14.1
- **Python version**:   3.7
   - mlflow==1.14.1
   - pg8000==1.16.5
- **Exact command to reproduce**:
   ```shell
   mlflow server \
      --host 0.0.0.0 \
      --port 5000 \
      --backend-store-uri "postgresql+pg8000://${USERNAME}:${URL_COMPATIBLE_PASSWORD}@${HOST}:${PORT}/${DATABASE_NAME}" \
    --default-artifact-root ${DEFAULT_ARTIFACT_ROOT}
   ```

### Describe the problem

When using AWS RDS Serverless (postgres) as the backend data store, the MLFLOW server doesn't create a new database session whenever the Serverless database comes online after pausing due to no activity. Currently running MLFLOW  on a AWS ECS cluster. So, whenever I encounter the issue, I kill the existing ECS task and create a new one and the error goes away.

### Other info / logs

```shell
2021-03-22 13:24:412021/03/22 13:24:41 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/experiments/list [GET]
2021-03-22 13:24:41Traceback (most recent call last):
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 80, in make_managed_session
2021-03-22 13:24:41yield session
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 258, in list_experiments
2021-03-22 13:24:41for exp in self._list_experiments(session=session, view_type=view_type, eager=True)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 252, in _list_experiments
2021-03-22 13:24:41return session.query(SqlExperiment).options(*query_options).filter(*conditions).all()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
2021-03-22 13:24:41return list(self)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
2021-03-22 13:24:41return self._execute_and_instances(context)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
2021-03-22 13:24:41querycontext, self._connection_from_session, close_with_result=True
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
2021-03-22 13:24:41mapper=self._bind_mapper(), clause=querycontext.statement, **kw
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
2021-03-22 13:24:41conn = self.session.connection(**kw)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
2021-03-22 13:24:41execution_options=execution_options,
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
2021-03-22 13:24:41engine, execution_options
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
2021-03-22 13:24:41conn = bind._contextual_connect()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
2021-03-22 13:24:41self._wrap_pool_connect(self.pool.connect, None),
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
2021-03-22 13:24:41return fn()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
2021-03-22 13:24:41return _ConnectionFairy._checkout(self)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 809, in _checkout
2021-03-22 13:24:41result = pool._dialect.do_ping(fairy.connection)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 575, in do_ping
2021-03-22 13:24:41cursor.execute(self._dialect_specific_select_one)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 340, in execute
2021-03-22 13:24:41self._c.execute_unnamed(self, "begin transaction")
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 1213, in execute_unnamed
2021-03-22 13:24:41self._flush()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/socket.py", line 607, in write
2021-03-22 13:24:41return self._sock.send(b)
2021-03-22 13:24:41TimeoutError: [Errno 110] Connection timed out
2021-03-22 13:24:41During handling of the above exception, another exception occurred:
2021-03-22 13:24:41Traceback (most recent call last):
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 214, in wrapper
2021-03-22 13:24:41return func(*args, **kwargs)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 510, in _list_experiments
2021-03-22 13:24:41experiment_entities = _get_tracking_store().list_experiments(request_message.view_type)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 258, in list_experiments
2021-03-22 13:24:41for exp in self._list_experiments(session=session, view_type=view_type, eager=True)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
2021-03-22 13:24:41self.gen.throw(type, value, traceback)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 87, in make_managed_session
2021-03-22 13:24:41raise MlflowException(message=e, error_code=INTERNAL_ERROR)
2021-03-22 13:24:41mlflow.exceptions.MlflowException: [Errno 110] Connection timed out
2021-03-22 13:24:41During handling of the above exception, another exception occurred:
2021-03-22 13:24:41Traceback (most recent call last):
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
2021-03-22 13:24:41response = self.full_dispatch_request()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-03-22 13:24:41rv = self.handle_user_exception(e)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-03-22 13:24:41reraise(exc_type, exc_value, tb)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
2021-03-22 13:24:41raise value
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-03-22 13:24:41rv = self.dispatch_request()
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
2021-03-22 13:24:41return self.view_functions[rule.endpoint](**req.view_args)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 217, in wrapper
2021-03-22 13:24:41response.set_data(e.serialize_as_json())
2021-03-22 13:24:41File "/usr/local/lib/python3.7/site-packages/mlflow/exceptions.py", line 60, in serialize_as_json
2021-03-22 13:24:41return json.dumps(exception_dict)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
2021-03-22 13:24:41return _default_encoder.encode(obj)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
2021-03-22 13:24:41chunks = self.iterencode(o, _one_shot=True)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
2021-03-22 13:24:41return _iterencode(o, 0)
2021-03-22 13:24:41File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
2021-03-22 13:24:41raise TypeError(f'Object of type {o.__class__.__name__} '
2021-03-22 13:24:41TypeError: Object of type TimeoutError is not JSON serializable
```

**Comment by dmatrix** [comment]
@1pyroaqua Thanks for sharing this bit with us. I just want to make sure that we understand the problem. Scenario is as follows:

- Your AWS RDS Serverless (postgres) is up and running to start with
- You launch mlflow tracking server with backend pointing to this postgres
- The tracking server creates a DB session okay
- Your AWS RDS Serverles (postress) is shutdown because of no activity
- When using the tracking server, thereafter, to log any MLflow entities, because of the defunct session to the defunct postgres server, not new DB sessions is created by the Tracking server, resulting into an error, namely TimeOut Session. 

Is that the scenario?

**Comment by 1pyroaqua** [comment]
@dmatrix  Yes. That's exactly the scenario that I'm facing currently.
