### ISSUE TITLE
ARTIFICATS - Something went wrong with this section. If this error persists, please report an issue here

### ISSUE THREAD

**Issue by moezali1** [mlflow/mlflow#4257]
OS: Windows 10 Home
Processor: Intel(R) Core(TM), i7-8550U CPU @ 1.80 GHz 1.99 GHz
System type: 64 bit
Python: Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
mlflow==1.15.0

ERROR: Everything is fine but when I initiate the server on localhost:5000 and click on the artifacts folder it gives me an error.

![image](https://user-images.githubusercontent.com/54699234/115155598-be910380-a04e-11eb-9b4b-0671a4320c17.png)

When I click on model, it gives me this error:

![image](https://user-images.githubusercontent.com/54699234/115155613-c94b9880-a04e-11eb-81fd-94f5d2b751a4.png)

I wasn't getting this error until yesterday. No change in my environment or installations.

**Comment by moezali1** [comment]
This is the log from dev console of chrome:

Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
ActionUtils.js:73 XHR failed Object
error @ ActionUtils.js:73
:5000/#/experiments/1:1 Uncaught (in promise) e
:5000/ajax-api/2.0/preview/mlflow/model-versions/search?filter=run_id%3D%2737b64a624ad1405e88d683f0958d2e48%27:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
ActionUtils.js:73 XHR failed Object
error @ ActionUtils.js:73
:5000/#/experiments/…e88d683f0958d2e48:1 Uncaught (in promise) e
:5000/ajax-api/2.0/preview/mlflow/registered-models/list:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
ActionUtils.js:73 XHR failed Object
error @ ActionUtils.js:73
:5000/#/experiments/…e88d683f0958d2e48:1 Uncaught (in promise) e
react-dom.production.min.js:3282 TypeError: e.forEach is not a function
    at t.a.getSchemaRowData (SchemaTable.js:48)
    at t.renderSchemaTable (SchemaTable.js:39)
    at t.value (SchemaTable.js:79)
    at h (react-dom.production.min.js:2740)
    at beginWork (react-dom.production.min.js:2916)
    at o (react-dom.production.min.js:4051)
    at i (react-dom.production.min.js:4068)
    at w (react-dom.production.min.js:4296)
    at _ (react-dom.production.min.js:4263)
    at b (react-dom.production.min.js:4254)
_r @ react-dom.production.min.js:3282
SectionErrorBoundary.js:16 TypeError: e.forEach is not a function
    at t.a.getSchemaRowData (SchemaTable.js:48)
    at t.renderSchemaTable (SchemaTable.js:39)
    at t.value (SchemaTable.js:79)
    at h (react-dom.production.min.js:2740)
    at beginWork (react-dom.production.min.js:2916)
    at o (react-dom.production.min.js:4051)
    at i (react-dom.production.min.js:4068)
    at w (react-dom.production.min.js:4296)
    at _ (react-dom.production.min.js:4263)
    at b (react-dom.production.min.js:4254) Object
value @ SectionErrorBoundary.js:16
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://localhost:5000/static-files/bootstrap/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**IMAGE:**
![image](https://user-images.githubusercontent.com/54699234/115155925-01071000-a050-11eb-98ec-d5fad57e809f.png)

**Comment by moezali1** [comment]
after degrading the mlflow version to 1.13 it's working fine, which means the bug is in >1.14 onwards.

**Comment by moezali1** [comment]
Here is my Chrome build if needed to triage.

![image](https://user-images.githubusercontent.com/54699234/115240995-4f6aec00-a0ee-11eb-8ed2-aa7fa8faf7a3.png)

**Comment by dmatrix** [comment]
@moezali1 Thanks for filing this. Can you try this simple experiment for me on your Windows laptop to see if you see the same problem?

```
import warnings

import numpy as np
import mlflow.sklearn
from mlflow.tracking import MlflowClient
from sklearn.linear_model import LinearRegression

if __name__ == "__main__":

    warnings.filterwarnings("ignore")
    print(mlflow.__version__)

    def print_auto_logged_info(r):
        tags = {k: v for k, v in r.data.tags.items() if not k.startswith("mlflow.")}
        artifacts = [f.path for f in MlflowClient().list_artifacts(r.info.run_id, "model")]
        print("run_id: {}".format(r.info.run_id))
        print("artifacts: {}".format(artifacts))
        print("params: {}".format(r.data.params))
        print("metrics: {}".format(r.data.metrics))
        print("tags: {}".format(tags))

    # prepare training data
    X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    y = np.dot(X, np.array([1, 2])) + 3

    # Auto log all the parameters, metrics, and artifacts
    mlflow.autolog()
    model = LinearRegression()
    with mlflow.start_run() as run:
        model.fit(X, y)

    # fetch the auto logged parameters and metrics
    print_auto_logged_info(mlflow.get_run(run_id=run.info.run_id))
```

And then launch the UI to see if you can see the metrics, artifacts in the UI. Do you get the same problem?

Also, do you have access to a Mac? I can't reproduce this on my Mac. I suspect could be a Chrome issue on Windows?

cc: @harupy @xanderwebs Any ideas why this is happening on Windows Chrome and not Mac?

**Comment by moezali1** [comment]
This is what I get when I run this script on command line.

(base) C:\Users\moezs\pycaret-demo-mlflow>python try.py
1.13
2021/04/19 22:38:29 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2021/04/19 22:38:30 WARNING mlflow.tracking.context.git_context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: No module named 'repository'
Traceback (most recent call last):
  File "try.py", line 29, in <module>
    with mlflow.start_run() as run:
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\tracking\fluent.py", line 237, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\tracking\client.py", line 252, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 94, in create_run
    tags=[RunTag(key, value) for (key, value) in tags.items()],
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 457, in create_run
    experiment = self.get_experiment(experiment_id)
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 338, in get_experiment
    experiment = self._get_experiment(experiment_id)
  File "C:\Users\moezs\Anaconda3\lib\site-packages\mlflow\store\tracking\file_store.py", line 309, in _get_experiment
    databricks_pb2.RESOURCE_DOES_NOT_EXIST,
mlflow.exceptions.MlflowException: Could not find experiment with ID 0

(base) C:\Users\moezs\pycaret-demo-mlflow>

**Comment by moezali1** [comment]
Also, I don't think it's related to Chrome as I can reproduce the same issue on Microsoft Edge as well.

**Comment by moezali1** [comment]
I am linking these two open issues, It seems like all these are same issues.

#3951 
#3952

**Comment by udaypratapyati** [comment]
Facing the same issue as pointed out by @moezali1 

`        HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

Wonder if i need some code change in the below code **snippent (pycaret)**

```
data = get_data('juice')
s = setup(data=data, target='Purchase', 
          **log_experiment=True, experiment_name='JUICE_DEMO_2',**
          session_id=123, silent=True)

selected_models = [ create_model(model) for model in ['lr', 'dt']]
```
        
**However if i run the below script with the same run configuration of mlflow, it works like a charm.**


**Run configuration used**
`mlflow ui --backend-store-uri sqlite:////home/user/mlflow.db`

**Script:**

```
import warnings
import numpy as np
import mlflow.sklearn
from mlflow.tracking import MlflowClient
from sklearn.linear_model import LinearRegression

if __name__ == "__main__":

    warnings.filterwarnings("ignore")
    print(mlflow.__version__)

    # prepare training data
    X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    y = np.dot(X, np.array([1, 2])) + 3

    # Auto log all the parameters, metrics, and artifacts
    mlflow.set_tracking_uri("sqlite:////home/user/mlflow.db")                      #Tracking URI set
    mlflow.set_experiment("MY_EXP")                                                       #Exp name set
    mlflow.autolog()
    model = LinearRegression()
    with mlflow.start_run(run_name="EXP1") as run:                                 #Exp run set
        model.fit(X, y)

    print("Done!!!")
```

Can someone help me out with a work around for this case (if any) ?

**Comment by dmatrix** [comment]
@moezali1 This code with model [signature and schema](https://github.com/dmatrix/mlflow-tests/blob/master/py/mlflow/mlflow_issues/issue_4257.py).

![Uploading Screen Shot 2021-04-24 at 6.07.11 PM.png…]()

**Comment by dmatrix** [comment]
@moezali1 Can we close this issue or do you want to figure out why your signature is creating an issue?

**Comment by vitas** [comment]
have the same issue on 1.19.0. MS Edge browser
