### ISSUE TITLE
pytorch model serve gives ResolvePackageNotFound

### ISSUE THREAD

**Issue by ErikEngerd** [mlflow/mlflow#4340]
### Willingness to contribute

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- used example/pytorch from https://github.com/mlflow/mlflow.git
- Centos 7 
- MLFlow installed from binary
- MLFlow 1.16.0
- Python 3.7.9 (NOTE: python 3.6 is used from the MLproject file)
- mlflow models serve -m s3://ml-bucket/YOURIDHERE/artifacts/pytorch-model

### Describe the problem

Using the standard pytorch example in examples/pytorch. 
Needed some modifications to get it to work: 
1. add boto3 to the conda.yaml file
2. line 238 of mnist_tensorboard_artifact, replated eval_data by eval_data.cuda()

Running the example using mlflow run . -Pepochs=1 works and gives results in s3 and mlflow. 
Now trying the serve the model fails with the following error

`2021/05/09 20:03:27 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/05/09 20:03:28 INFO mlflow.utils.conda: === Creating conda environment mlflow-43ca95bd58d044f041c10a60bd564ce0673c7489 ===
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - torchvision=0.9.1+cu102
  - pytorch=1.8.1+cu102

Traceback (most recent call last):
  File "/home/erik/miniconda3/envs/ds/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/mlflow/models/cli.py", line 56, in serve
    ).serve(model_uri=model_uri, port=port, host=host)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 92, in serve
    conda_env_path, command, self._install_mlflow, command_env=command_env
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 149, in _execute_in_conda_env
    conda_env_name = get_or_create_conda_env(conda_env_path, env_id=env_id)
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/mlflow/utils/conda.py", line 95, in get_or_create_conda_env
    stream_output=True,
  File "/home/erik/miniconda3/envs/ds/lib/python3.7/site-packages/mlflow/utils/process.py", line 40, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1
`
Clearly, it is looking for torchvision=0.9.1+cu102 and pytorch=1.8.1+cu102 but these versions do not exist. Also they are different from the conda.yaml file. 

Interestingly, the conda.yaml file uploaded to S3 is also wrong: 

`
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.6.13
- pytorch=1.8.1+cu102
- torchvision=0.9.1+cu102
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
name: mlflow-env
`

### Code to reproduce issue

See the github examples. 

### Other info / logs

-

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@ErikEngerd Thanks for filing this. 

I was able to run the same example without any issues or install packages, and the conda.yml is no different.
`mlflow run . -P epochs=1` 

![Screen Shot 2021-05-13 at 9 52 48 AM](https://user-images.githubusercontent.com/1117597/118158856-2f6ad780-b3d1-11eb-9255-a39263f9b374.png)
![Screen Shot 2021-05-13 at 9 53 12 AM](https://user-images.githubusercontent.com/1117597/118158869-32fe5e80-b3d1-11eb-80f4-58741f4bfebf.png)
