### ISSUE TITLE
[BUG] log_artifact() not working on remote server: AttributeError: 'NoneType' object has no attribute 'time'

### ISSUE THREAD

**Issue by TimoSommer** [mlflow/mlflow#4345]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise Linux release 8.2 (Ootpa) (Remote Server)
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.16.0
- **Python version**: 3.8.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Mlflow gives a strange error if I log a numpy array as artifact while running autolog() on a remote server. On my local machine there  is no error. This behaviour seems to be connected to not having enough time for the logging because either waiting a few seconds or logging a smaller array doesn't reproduce the issue for the minimal working example. However, in my real script where I logged several arrays I noticed that even waiting 2 min was not enough and I could not make it work there. The exception arises the moment the script is closed.
Note that this is a different issue than #4327. 
It seems to be a paramiko issue (https://stackoverflow.com/questions/60037299/attributeerror-nonetype-object-has-no-attribute-time-paramiko) but I was wondering if there is anything one can do from the mlflow point of view and it is weird that it only happens on the remote server. Btw my paramiko version is 2.7.2.

### Code to reproduce issue
```python
import mlflow
import numpy as np
import tempfile
import time
import os

# Define functions for connecting to mlflow server.
def load_env(env_path: str):
    """Loads an .env file in your home directory.
    To access the mlflow api, you need log in credentials. These can be stored in a local environment file which you
    should protect with `chmod 600 .env`.
    In this .env file you should define:
    MLFLOW_TRACKING_USERNAME=your_username
    MLFLOW_TRACKING_PASSWORD=your_password
    MLFLOW_TRACKING_URI=***

  Returns:
      env: (dict) A dictionary containing the defined key value pairs.
  """
  home = os.path.expanduser("~")
  with open(env_path, 'r') as f:
      env = dict()
      for line in f.readlines():
          key, value = line.split('=')
          env[key] = value.split('\n')[0]
      return env

def export_env(env_path: str):
    """Loads your .env file and exports the three variables important for mlflow.
    MLFLOW_TRACKING_USERNAME, MLFLOW_TRACKING_PASSWORD, MLFLOW_TRACKING_URI
    """
    env = load_env(env_path)
    for key in ["MLFLOW_TRACKING_USERNAME", "MLFLOW_TRACKING_PASSWORD", "MLFLOW_TRACKING_URI"]:
        os.environ[key] = env[key]

def log_array(a, name: str):
    """Logs an array as artifact to the currently active run.
    Args:
        a: (anything convertible to np.array) Array to store as artifact.
        name: (str) Name to give the folder and file under th current mlflow run.
    """
    a = np.array(a)
    tmpdir = tempfile.mkdtemp()
    save_path = os.path.join(tmpdir, name+".npy")
    np.save(save_path, a)
    mlflow.log_artifact(save_path, 'meta_data')
    return

# Export environment variables for the ssh connection of MLflow.
env_path = os.path.join(os.path.expanduser('~'), '.env')
export_env(env_path)

# This is the important part.
mlflow.autolog()
a = np.ones(1000)    # 10 is not enough to break it here
log_array(a, 'a')
# time.sleep(15)        # workaround fixes exception
```

### Other info / logs
Traceback: 
```
Exception ignored in: <function Connection.__del__ at 0x14cbda767f70>
Traceback (most recent call last):
  File "/home/kit/stud/uoeci/conda/envs/Masterarbeit/lib/python3.8/site-packages/pysftp/__init__.py", line 1013, in __del__
  File "/home/kit/stud/uoeci/conda/envs/Masterarbeit/lib/python3.8/site-packages/pysftp/__init__.py", line 785, in close
  File "/home/kit/stud/uoeci/conda/envs/Masterarbeit/lib/python3.8/site-packages/paramiko/sftp_client.py", line 195, in close
  File "/home/kit/stud/uoeci/conda/envs/Masterarbeit/lib/python3.8/site-packages/paramiko/channel.py", line 671, in close
  File "/home/kit/stud/uoeci/conda/envs/Masterarbeit/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@TimoSommer Thanks for filing this. Where is your remote server running? Can you even log anything other than log_artifact? Am wondering if the client is timing out. Try logging metrics and parameters as a test to see if you log
it from your client to the remote tracking server.

**Comment by TimoSommer** [comment]
Sorry, I don't know exactly how to answer this question. It's a server from my institute. I have checked, logging metrics and parameters works exactly as expected. Also as I described above, logging a small artifact (like a np array of size 10) works in this example. Logging an array of size 1000 leads to the error. When waiting for 15s before closing the script even the array with 1000 entries is logged well. But in my real script, where I log around 25 arrays of size ~100, not even waiting for 120 seconds resolved the issue.
