### ISSUE TITLE
the model can't serve and how to slove?

### ISSUE THREAD

**Issue by itolPride** [mlflow/mlflow#4347]
pride@ubuntu:~/code/mlflow-master/examples$ python sklearn_logistic_regression/train.py 
Score: 0.6666666666666666
Model saved in run 8cd9354bea59432fb71fa575a5a3efd9
pride@ubuntu:~/code/mlflow-master/examples$ mlflow models serve -m runs:/8cd9354bea59432fb71fa575a5a3efd9/model --port 1234
2021/05/12 01:31:24 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/05/12 01:31:31 INFO mlflow.utils.conda: === Creating conda environment mlflow-7cddf73fb0d259cce996e88d1483ae63674b251e ===
Collecting package metadata (repodata.json): / Traceback (most recent call last):
  File "/home/pride/.local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pride/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pride/.local/lib/python3.6/site-packages/mlflow/models/cli.py", line 56, in serve
    ).serve(model_uri=model_uri, port=port, host=host)
  File "/home/pride/.local/lib/python3.6/site-packages/mlflow/pyfunc/backend.py", line 92, in serve
    conda_env_path, command, self._install_mlflow, command_env=command_env
  File "/home/pride/.local/lib/python3.6/site-packages/mlflow/pyfunc/backend.py", line 149, in _execute_in_conda_env
    conda_env_name = get_or_create_conda_env(conda_env_path, env_id=env_id)
  File "/home/pride/.local/lib/python3.6/site-packages/mlflow/utils/conda.py", line 95, in get_or_create_conda_env
    stream_output=True,
  File "/home/pride/.local/lib/python3.6/site-packages/mlflow/utils/process.py", line 40, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: -9

**Comment by ByronHsu** [comment]
same here
