### ISSUE TITLE
mlflow is not a package

### ISSUE THREAD

**Issue by paulaceccon** [mlflow/mlflow#4392]
I'm trying to get started with mlflow, but every example I try fails. Example:

```
import numpy as np
from sklearn.linear_model import LogisticRegression

import mlflow
import mlflow.sklearn

if __name__ == "__main__":
    X = np.array([-2, -1, 0, 1, 2, 1]).reshape(-1, 1)
    y = np.array([0, 0, 1, 1, 1, 0])
    lr = LogisticRegression()
    lr.fit(X, y)
    score = lr.score(X, y)
    print("Score: %s" % score)
    mlflow.log_metric("score", score)
    mlflow.sklearn.log_model(lr, "model")
    print("Model saved in run %s" % mlflow.active_run().info.run_uuid)
```

```
> python3 mlflow.py
Traceback (most recent call last):
  File "mlflow.py", line 4, in <module>
    import mlflow
  File "/home/paula/Área de Trabalho/mlflow/mlflow.py", line 5, in <module>
    import mlflow.sklearn
ModuleNotFoundError: No module named 'mlflow.sklearn'; 'mlflow' is not a package
```

Trying to use a project lead to the same issue:

```
> mlflow run . --no-conda
2021/05/25 16:02:42 INFO mlflow.projects.utils: === Created directory /tmp/tmpz4z6ll1m for downloading remote URIs passed to arguments of type 'path' ===
2021/05/25 16:02:42 INFO mlflow.projects.backend.local: === Running command 'python3 mlflow.py' in run with ID 'a1da87031413431a8aab252381cf7c63' === 
Traceback (most recent call last):
  File "mlflow.py", line 4, in <module>
    import mlflow
  File "/home/paula/Área de Trabalho/mlflow/mlflow.py", line 5, in <module>
    import mlflow.sklearn
ModuleNotFoundError: No module named 'mlflow.sklearn'; 'mlflow' is not a package
2021/05/25 16:02:43 ERROR mlflow.cli: === Run (ID 'a1da87031413431a8aab252381cf7c63') failed ===
```

> mlflow, version 1.17.0

**Comment by harupy** [comment]
@paulaceccon I think it's because your file name is `mlflow.py`.
