### ISSUE TITLE
Cannot pass  kwargs to keras_model.save method.

### ISSUE THREAD

**Issue by zhixingheyi-tian** [mlflow/mlflow#4463]
We use Horovod to  train Keras model and use Mlflow to register model,

From the  MLflow guide doc:
```
mlflow.keras.log_model(keras_model, artifact_path, conda_env=None, custom_objects=None, keras_module=None, registered_model_name=None, signature: Optional[mlflow.models.signature.ModelSignature] = None, input_example: Optional[Union[pandas.core.frame.DataFrame, numpy.ndarray, dict, list]] = None, await_registration_for=300, **kwargs)

kwargs – kwargs to pass to keras_model.save method.

```
So we passed extra argument _floatx="float32"
```
>>> mlflow.keras.log_model(regmodel, "kwargs-model", None, None, None, "kwargs-model-reg", None, None, 300, _floatx="float32")
```
But encounter
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda2/envs/keras/lib/python3.8/site-packages/mlflow/keras.py", line 377, in log_model
    Model.log(
  File "/root/miniconda2/envs/keras/lib/python3.8/site-packages/mlflow/models/model.py", line 182, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/root/miniconda2/envs/keras/lib/python3.8/site-packages/mlflow/keras.py", line 260, in save_model
    keras_model.save(model_path, **kwargs)
TypeError: save() got an unexpected keyword argument '_floatx'

```
We have got the cause. Is it a bug?

@harupy @smurching 

Thanks.

**Comment by harupy** [comment]
@zhixingheyi-tian Why do you need to pass `_floatx`?

**Comment by zhixingheyi-tian** [comment]
@harupy @smurching 

Based on the databricks example of https://docs.databricks.com/_static/notebooks/deep-learning/horovod-spark-estimator-keras.html，
We add the MLflow integration.
We have successfully registered model to MLflow with below code
```
keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])
regmodel.keras_model.getModel()
mlflow.keras.log_model(regmodel, "Keras-Sequential-model", registered_model_name="Keras-Sequential-model-reg")
```

But when we loaded model from MLflow to predict  Spark DataFrame, need other arguments: floatx, metadata.

```
model_uri = "models:/Keras-Sequential-model-reg/1"
loaded_model = mlflow.keras.load_model(model_uri)


metadata = keras_model._get_metadata()
floatx = keras_model._get_floatx()
keras_model_from_reg = hvd.KerasModel(model=loaded_model,
                                      feature_columns=['features'],
                                      label_columns=['label_vec'],
                                     _floatx = floatx,
                                     _metadata = metadata)
```

So we wonder whether can pass the needed  "floatx, metadata" to log_model and save them with the model. 

Another point I’m not sure is:  Whether the two "floatx, metadata" kwargs  can be loaded out  from  MLflow when using mlflow.keras.load_model API.


Thanks.

**Comment by Ankur-singh** [comment]
Any updates on the same? I am facing a similar issue but I am using Pytorch. 

I have save my pytorch model (along with transforms) as a `PythonFunction`. I want to load the model in CPU as well as GPU. Is there any provision of passing extra arguments like `use_gpu=True` while logging the model. Ideally, I want to use this extra argument to during `load_model` to load the model in CPU or GPU.

**Comment by B-Step62** [comment]
`_floatx` is not a valid argument to Keras `Model.save()`, so this is not an MLflow bug, and the standalone `mlflow.keras` flavor referenced here has since been removed (current `mlflow.keras` targets Keras 3). Closing.
