### ISSUE TITLE
[BUG] Loading a registered model in PySpark and executing it as UDF results in AttributeError exception

### ISSUE THREAD

**Issue by uvnikgupta** [mlflow/mlflow#4548]
I executed the following steps:
1. I am using Python v3.9.5, pyspark v3.0.3 and mlflow v1.18.0
2. Created a simple linear regression model using <code>sklearn.linear_model.LineraRegression</code> and housing_median_age as the only feature from the sklearn housing data set. 
3. Used <code>mlflow.sklearn.log_model()</code> to log this model
4. From the mlflow UI, registered this model as "linreg" and promoted it to Staging
5. In the pyspark code, loaded this model using <code>mlflow.pyfunc.spark_udf()</code>
6. Called this model using <code>df.withColumn('predictions', model(f.col("housing_median_age")))</code>
7. Executed <code>df.show()</code> which resulted in the following error:

<code>
      21/07/11 05:46:20 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 4)
      org.apache.spark.api.python.PythonException: Traceback (most recent call last):
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 588, in main
          func, profiler, deserializer, serializer = read_udfs(pickleSer, infile, eval_type)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 447, in read_udfs
          udfs.append(read_single_udf(pickleSer, infile, eval_type, runner_conf, udf_index=i))
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 249, in read_single_udf
          f, return_type = read_command(pickleSer, infile)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
          command = serializer._read_with_length(file)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 160, in _read_with_length
          return self.loads(obj)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 430, in loads
          return pickle.loads(obj, encoding=encoding)
      AttributeError: Can't get attribute '_fill_function' on \<module 'pyspark.cloudpickle' from '/usr/local/spark/python/lib/pyspark.zip/pyspark/cloudpickle/__init__.py'\>
</code>
      
	      at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:517)
	      at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:99)
	      at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:49)
	      at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:470)
	      at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	      at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	      at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	      at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	      at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	      at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	      at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	      at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	      at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	      at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	      at org.apache.spark.scheduler.Task.run(Task.scala:131)
	      at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	      at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	      at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	      at java.base/java.lang.Thread.run(Thread.java:829)
      21/07/11 05:46:20 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 4) (mltoolkit-6b7455f648-6lkxr executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 588, in main
          func, profiler, deserializer, serializer = read_udfs(pickleSer, infile, eval_type)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 447, in read_udfs
          udfs.append(read_single_udf(pickleSer, infile, eval_type, runner_conf, udf_index=i))
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 249, in read_single_udf
          f, return_type = read_command(pickleSer, infile)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
          command = serializer._read_with_length(file)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 160, in _read_with_length
          return self.loads(obj)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 430, in loads
          return pickle.loads(obj, encoding=encoding)
      AttributeError: Can't get attribute '_fill_function' on <module 'pyspark.cloudpickle' from '/usr/local/spark/python/lib/pyspark.zip/pyspark/cloudpickle/__init__.py'>
      
	      at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:517)
	      at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:99)
	      at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:49)
	      at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:470)
	      at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	      at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	      at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	      at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	      at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	      at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	      at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	      at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	      at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	      at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	      at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	      at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	      at org.apache.spark.scheduler.Task.run(Task.scala:131)
	      at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	      at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	      at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	      at java.base/java.lang.Thread.run(Thread.java:829)
      
      21/07/11 05:46:20 ERROR TaskSetManager: Task 0 in stage 4.0 failed 1 times; aborting job
      ---------------------------------------------------------------------------
      PythonException                           Traceback (most recent call last)
      /tmp/ipykernel_145/2168557162.py in <module>
            3 
            4 df = housing.withColumn('predictions', model(f.col("housing_median_age")))
      ----> 5 df.show()
      
      /opt/conda/lib/python3.9/site-packages/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
          438         """
          439         if isinstance(truncate, bool) and truncate:
      --> 440             print(self._jdf.showString(n, 20, vertical))
          441         else:
          442             print(self._jdf.showString(n, int(truncate), vertical))
      
      /opt/conda/lib/python3.9/site-packages/py4j/java_gateway.py in __call__(self, *args)
         1302 
         1303         answer = self.gateway_client.send_command(command)
      -> 1304         return_value = get_return_value(
         1305             answer, self.gateway_client, self.target_id, self.name)
         1306 
      
      /opt/conda/lib/python3.9/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
          132                 # Hide where the exception came from that shows a non-Pythonic
          133                 # JVM exception message.
      --> 134                 raise_from(converted)
          135             else:
          136                 raise
      
      /opt/conda/lib/python3.9/site-packages/pyspark/sql/utils.py in raise_from(e)
      
      PythonException: 
        An exception was thrown from the Python worker. Please see the stack trace below.
      Traceback (most recent call last):
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 588, in main
          func, profiler, deserializer, serializer = read_udfs(pickleSer, infile, eval_type)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 447, in read_udfs
          udfs.append(read_single_udf(pickleSer, infile, eval_type, runner_conf, udf_index=i))
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 249, in read_single_udf
          f, return_type = read_command(pickleSer, infile)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
          command = serializer._read_with_length(file)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 160, in _read_with_length
          return self.loads(obj)
        File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 430, in loads
          return pickle.loads(obj, encoding=encoding)
      AttributeError: Can't get attribute '_fill_function' on <module 'pyspark.cloudpickle' from '/usr/local/spark/python/lib/pyspark.zip/pyspark/cloudpickle/__init__.py'>

**Comment by tomasatdatabricks** [comment]
Hi @uvnikgupta , this error does seem to be a Spark error rather than mlflow error given the stacktrace, I found a similar issue with koalas here: https://stackoverflow.com/questions/66746285/koalas-throws-cant-get-attribute-fill-function-on-module-pyspark-cloudpic. Looks like updating pyspark version helped in this case.

**Comment by uvnikgupta** [comment]
@tomasatdatabricks, thanks for the hint. 
I upgraded the pyspark version to 3.1.2 and am able to run the code without any issues! Thanks again.

**Comment by uvnikgupta** [comment]
Issue solved after upgrading the pyspark version to 3.1.2
