### ISSUE TITLE
ML Flow - Pytorch lightning Multi GPU Pickling error

### ISSUE THREAD

**Issue by vijaykumarravi** [mlflow/mlflow#4636]
System Information:
'pytorch-lightning==1.3.8
'mlflow==1.19.0'

Description:
I am using mlflow autologger with pytorch_lightning. The auto logging feature works fine with it is run on a single GPU. But it fails when I try it on multiple GPUs. From the stack trace I understand that it is trying to add the MLflow callback to the list of callbacks and then it fails when it is trying to spawn a new process

Error:

AttributeError: Can't pickle local object '_create_patch_fit.<locals>.getPLCallback.<locals>.__MLflowPLCallback'
databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in safe_patch_function(*args, **kwargs)
    490                         patch_function.call(call_original, *args, **kwargs)
    491                     else:
--> 492                         patch_function(call_original, *args, **kwargs)
    493 
    494                     session.state = "succeeded"

/databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in patch_with_managed_run(original, *args, **kwargs)
    240 
    241             try:
--> 242                 result = patch_function(original, *args, **kwargs)
    243             except (Exception, KeyboardInterrupt):
    244                 # In addition to standard Python exceptions, handle keyboard interrupts to ensure

/databricks/python/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py in fit(original, self, *args, **kwargs)
    314         Patching trainer.fit method to add autolog class into callback
    315         """
--> 316         return _run_and_log_function(self, original, args, kwargs)
    317 
    318     return fit

/databricks/python/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py in _run_and_log_function(self, original, args, kwargs)
    306         if not any(isinstance(callbacks, __MLflowPLCallback) for callbacks in self.callbacks):
    307             self.callbacks += [__MLflowPLCallback()]
--> 308         result = original(self, *args, **kwargs)
    309 
    310         return result

/databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in call_original(*og_args, **og_kwargs)
    446                                 disable_warnings=False, reroute_warnings=False,
    447                             ):
--> 448                                 original_result = original(*og_args, **og_kwargs)
    449 
    450                             try_log_autologging_event(

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
    458         )
    459 
--> 460         self._run(model)
    461 
    462         assert self.state.stopped

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model)
    756 
    757         # dispatch `start_training` or `start_evaluating` or `start_predicting`
--> 758         self.dispatch()
    759 
    760         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in dispatch(self)
    797             self.accelerator.start_predicting(self)
    798         else:
--> 799             self.accelerator.start_training(self)
    800 
    801     def run_stage(self):

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py in start_training(self, trainer)
     94 
     95     def start_training(self, trainer: 'pl.Trainer') -> None:
---> 96         self.training_type_plugin.start_training(trainer)
     97 
     98     def start_evaluating(self, trainer: 'pl.Trainer') -> None:

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py in start_training(self, trainer)
    120 
    121     def start_training(self, trainer):
--> 122         mp.spawn(self.new_process, **self.mp_spawn_kwargs)
    123         # reset optimizers, since main process is never used for training and thus does not have a valid optim state
    124         trainer.optimizers = []

/databricks/python/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    197                ' torch.multiprocessing.start_process(...)' % start_method)
    198         warnings.warn(msg)
--> 199     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

/databricks/python/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    146             daemon=daemon,
    147         )
--> 148         process.start()
    149         error_queues.append(error_queue)
    150         processes.append(process)

/databricks/python/lib/python3.8/multiprocessing/process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

/databricks/python/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    282         def _Popen(process_obj):
    283             from .popen_spawn_posix import Popen
--> 284             return Popen(process_obj)
    285 
    286     class ForkServerProcess(process.BaseProcess):

/databricks/python/lib/python3.8/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
     30     def __init__(self, process_obj):
     31         self._fds = []
---> 32         super().__init__(process_obj)
     33 
     34     def duplicate_for_child(self, fd):

/databricks/python/lib/python3.8/multiprocessing/popen_fork.py in __init__(self, process_obj)
     17         self.returncode = None
     18         self.finalizer = None
---> 19         self._launch(process_obj)
     20 
     21     def duplicate_for_child(self, fd):

/databricks/python/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     45         try:
     46             reduction.dump(prep_data, fp)
---> 47             reduction.dump(process_obj, fp)
     48         finally:
     49             set_spawning_popen(None)

/databricks/python/lib/python3.8/multiprocessing/reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

**Comment by twsl** [comment]
Got the same issue on Databricks: `
AttributeError: Can't pickle local object '_create_patch_fit.<locals>.getPLCallback.<locals>.__MLflowPLCallback'`

To replicate, select a single node with e.g. `Standard_NC12` and try to run a minimal example with latest PyTorch Lightning (1.4.1) using `mlflow.pytorch.autolog()`. Set Trainer to use the arg `gpus=-1`.

<details>
<summary>Full output</summary>

```
<command-1357939202606115> in <module>
      1 # 4. Finetune the model
----> 2 trainer.finetune(model, datamodule=datamodule)

/databricks/python/lib/python3.8/site-packages/flash/core/trainer.py in finetune(self, model, train_dataloader, val_dataloaders, datamodule, strategy)
    155         """
    156         self._resolve_callbacks(model, strategy)
--> 157         return super().fit(model, train_dataloader, val_dataloaders, datamodule)
    158 
    159     def _resolve_callbacks(self, model, strategy):

/databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in safe_patch_function(*args, **kwargs)
    490                         patch_function.call(call_original, *args, **kwargs)
    491                     else:
--> 492                         patch_function(call_original, *args, **kwargs)
    493 
    494                     session.state = "succeeded"

/databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in patch_with_managed_run(original, *args, **kwargs)
    240 
    241             try:
--> 242                 result = patch_function(original, *args, **kwargs)
    243             except (Exception, KeyboardInterrupt):
    244                 # In addition to standard Python exceptions, handle keyboard interrupts to ensure

/databricks/python/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py in fit(original, self, *args, **kwargs)
    314         Patching trainer.fit method to add autolog class into callback
    315         """
--> 316         return _run_and_log_function(self, original, args, kwargs)
    317 
    318     return fit

/databricks/python/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py in _run_and_log_function(self, original, args, kwargs)
    306         if not any(isinstance(callbacks, __MLflowPLCallback) for callbacks in self.callbacks):
    307             self.callbacks += [__MLflowPLCallback()]
--> 308         result = original(self, *args, **kwargs)
    309 
    310         return result

/databricks/python/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py in call_original(*og_args, **og_kwargs)
    446                                 disable_warnings=False, reroute_warnings=False,
    447                             ):
--> 448                                 original_result = original(*og_args, **og_kwargs)
    449 
    450                             try_log_autologging_event(

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader)
    551         self.checkpoint_connector.resume_start()
    552 
--> 553         self._run(model)
    554 
    555         assert self.state.stopped

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model)
    916 
    917         # dispatch `start_training` or `start_evaluating` or `start_predicting`
--> 918         self._dispatch()
    919 
    920         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _dispatch(self)
    984             self.accelerator.start_predicting(self)
    985         else:
--> 986             self.accelerator.start_training(self)
    987 
    988     def run_stage(self):

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py in start_training(self, trainer)
     90 
     91     def start_training(self, trainer: "pl.Trainer") -> None:
---> 92         self.training_type_plugin.start_training(trainer)
     93 
     94     def start_evaluating(self, trainer: "pl.Trainer") -> None:

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py in start_training(self, trainer)
    156 
    157     def start_training(self, trainer):
--> 158         mp.spawn(self.new_process, **self.mp_spawn_kwargs)
    159         # reset optimizers, since main process is never used for training and thus does not have a valid optim state
    160         trainer.optimizers = []

/databricks/python/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    228                ' torch.multiprocessing.start_processes(...)' % start_method)
    229         warnings.warn(msg)
--> 230     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

/databricks/python/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    177             daemon=daemon,
    178         )
--> 179         process.start()
    180         error_queues.append(error_queue)
    181         processes.append(process)

/databricks/python/lib/python3.8/multiprocessing/process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

/databricks/python/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    282         def _Popen(process_obj):
    283             from .popen_spawn_posix import Popen
--> 284             return Popen(process_obj)
    285 
    286     class ForkServerProcess(process.BaseProcess):

/databricks/python/lib/python3.8/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
     30     def __init__(self, process_obj):
     31         self._fds = []
---> 32         super().__init__(process_obj)
     33 
     34     def duplicate_for_child(self, fd):

/databricks/python/lib/python3.8/multiprocessing/popen_fork.py in __init__(self, process_obj)
     17         self.returncode = None
     18         self.finalizer = None
---> 19         self._launch(process_obj)
     20 
     21     def duplicate_for_child(self, fd):

/databricks/python/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     45         try:
     46             reduction.dump(prep_data, fp)
---> 47             reduction.dump(process_obj, fp)
     48         finally:
     49             set_spawning_popen(None)

/databricks/python/lib/python3.8/multiprocessing/reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object '_create_patch_fit.<locals>.getPLCallback.<locals>.__MLflowPLCallback'
```

</details>

**Comment by vjkravi** [comment]
I was able to resolve the above issue by starting the mlflow.run() and not use autolog() and then initializing the Trainer object. But when doing that, I am seeing a new error specific to databricks - 

AttributeError: Can't pickle local object '_get_databricks_rest_store.<locals>.<lambda>'

with mlflow.start_run(run_name='mlflow_debug_run') as run:
    experiment_id = run.info.experiment_id
    # get the experiment name
    exp_name = mlflow.get_experiment(experiment_id).name
    # get the mlflow tracking uri
    mlflow_uri = mlflow.get_tracking_uri()
    mlf_logger = MLFlowLogger(experiment_name=exp_name, tracking_uri=mlflow_uri)
    # link the mlflowlogger run ID to the azureml run ID
    mlf_logger._run_id = run.info.run_id
    model = LightningMNISTClassifier()
    trainer = pl.Trainer(gpus=2, max_epochs=10, logger=mlf_logger)
    trainer.fit(model)

**Comment by Vadbeg** [comment]
Yep, got similar one with Databricks trying to perform multigpu training.
<details><summary>Stacktace</summary>
<p>

```
Global seed set to 27
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    cli = LightningCLI(model_class=DeepGrowModel, save_config_callback=None)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 289, in __init__
    self.fit()
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 432, in fit
    self.trainer.fit(**self.fit_kwargs)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 158, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/vadzim_tsitko/Environments/deppgrow-2d-env/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_get_databricks_rest_store.<locals>.<lambda>'
```

</p>
</details>

**Comment by vjkravi** [comment]
I think this commit fixes the _get_databricks_rest_store.<locals>.<lambda> issue. But specifically in databricks you have to run your code as a script and not as a notebook.

https://github.com/mlflow/mlflow/commit/3aea023d08567b86983e752ac536f65db220c4e9
