### ISSUE TITLE
[BUG] mlflow models build-docker fails to create environment

### ISSUE THREAD

**Issue by flaviolisdero** [mlflow/mlflow#4802]
I am using mlflow version 1.20.2 and docker version 20.10.7. I am able to serve my mlflow model

> mlflow models serve -m models:/my_model/Staging

however when I run

> mlflow models build-docker -m models:/my_model/Staging -n "model_name" --install-mlflow

I get the following error

> #17 51.50 Installing pip dependencies: ...working... Traceback (most recent call last):
> #17 197.4   File "<string>", line 1, in <module>
> #17 197.4   File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 101, in _install_pyfunc_deps
> #17 197.4     raise Exception("Failed to create model environment.")
> #17 197.4 Exception: Failed to create model environment.
> #17 197.5 creating and activating custom environment
> #17 ERROR: executor failed running [/bin/sh -c python -c                 'from mlflow.models.container import _install_pyfunc_deps;                _install_pyfunc_deps("/opt/ml/model", install_mlflow=True)']: exit code: 1
> ------
>  > [12/12] RUN python -c                 'from mlflow.models.container import _install_pyfunc_deps;                _install_pyfunc_deps("/opt/ml/model", install_mlflow=True)':
> ------
> executor failed running [/bin/sh -c python -c                 'from mlflow.models.container import _install_pyfunc_deps;                _install_pyfunc_deps("/opt/ml/model", install_mlflow=True)']: exit code: 1
> Traceback (most recent call last):
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/bin/mlflow", line 8, in <module>
>     sys.exit(cli())
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/mlflow/models/cli.py", line 159, in build_docker
>     _get_flavor_backend(model_uri, docker_build=True).build_image(
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/mlflow/pyfunc/backend.py", line 137, in build_image
>     _build_image(
>   File "/Users/flavio.lisdero/Desktop/MPRNet_lightning/.venv/lib/python3.8/site-packages/mlflow/models/docker_utils.py", line 132, in _build_image
>     raise RuntimeError("Docker build failed.")

**Comment by FahriBilici** [comment]
I have same problem
