### ISSUE TITLE
[BUG] mlflow fails to create conda environments with hash-pinned pip packages

### ISSUE THREAD

**Issue by mmaitre314** [mlflow/mlflow#4886]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:1.20.2
- **Python version**:3.8
- **npm version, if running the dev UI**:N/A
- **Exact command to reproduce**:mlflow models serve -m runs:/5f8aee52fcb442388368af4da658b398/model

### Describe the problem

We run `pip install` in [hash-checking mode](https://pip.pypa.io/en/stable/cli/pip_install/#hash-checking-mode) to prevent package tampering. MLFlow does not support this by default so I provided the `requirements.txt` file explicitly:
```
    mlflow.sklearn.log_model(
        model,
        artifact_path = "model",
        signature = mlflow.models.infer_signature(X_train[:10], y_train[:10]),
        input_example = X_train[:10],
        pip_requirements = "requirements.txt")
```
Instead of using the `requirements.txt` file as-is, MLFlow added an extra `mlflow` entry in the list of PIP requirements. This `mlflow` entry has no version or hash, which breaks `pip install` when trying to serve the model. The fix is likely not to add that extra entry when the `mlflow` package is already present in the requirement list.

conda.yaml logged in model artifacts:
```
channels:
- conda-forge
dependencies:
- python=3.8.8
- pip
- pip:
  - mlflow
  - adal==1.2.7 --hash=sha256:2a7451ed7441ddbc57703042204a3e30ef747478eea022c70f789fc7f084bc3d
    --hash=sha256:d74f45b81317454d96e982fd1c50e6fb5c99ac2223728aea8764433a39f566f1
  - alembic==1.4.1 --hash=sha256:791a5686953c4b366d3228c5377196db2f534475bb38d26f70eb69668efd9028
  - azure-common==1.1.27 --hash=sha256:426673962740dbe9aab052a4b52df39c07767decd3f25fdc87c9d4c566a04934
    --hash=sha256:9f3f5d991023acbd93050cf53c4e863c6973ded7e236c69e99c8ff5c7bad41ef
<snip>
  - werkzeug==2.0.2 --hash=sha256:63d3dc1cf60e7b7e35e97fa9861f7397283b75d765afcaefd993d6046899de8f
    --hash=sha256:aa2bb6fc8dee8d6c504c0ac1e7f5f7dc5810a9903e793b6f715a9f015bdadb9a
  - zipp==3.6.0 --hash=sha256:71c644c5369f4a6e07636f0aa966270449561fcea2e3d6747b8d23efaa9d7832
    --hash=sha256:9fe5ea21568a0a70e50f273397638d39b03353731e6cbbb3fd8502a33fec40bc
name: mlflow-env
```

Command error:
```
(.venv) (base) C:\Source\local_training_mlflow_project>mlflow models serve -m runs:/5f8aee52fcb442388368af4da658b398/model
2021/10/11 23:28:11 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/10/11 23:28:15 INFO mlflow.utils.conda: === Creating conda environment mlflow-895112428d2cf8da9ab88b552b55b1ea2f22dc1c ===
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
openssl-1.1.1l       | 5.7 MB    | ############################################################################################################################### | 100%
python-3.8.8         | 19.2 MB   | ############################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['C:\\Users\\mmaitre\\Anaconda3\\envs\\mlflow-895112428d2cf8da9ab88b552b55b1ea2f22dc1c\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Source\\local_training_mlflow_project\\mlruns\\0\\5f8aee52fcb442388368af4da658b398\\artifacts\\model\\condaenv.4kpb_18z.requirements.txt']
Pip subprocess output:
Collecting mlflow

Pip subprocess error:
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    mlflow from https://files.pythonhosted.org/packages/ac/60/cc5ad7b761f31854d3158dc420e62d5adaa283e5d65efebf029ae2c400c2/mlflow-1.20.2-py3-none-any.whl#sha256=963c22532e82a93450674ab97d62f9e528ed0906b580fadb7c003e696197557c (from -r C:\Source\local_training_mlflow_project\mlruns\0\5f8aee52fcb442388368af4da658b398\artifacts\model\condaenv.4kpb_18z.requirements.txt (line 1))

failed

CondaEnvException: Pip failed

Traceback (most recent call last):
  File "C:\Users\mmaitre\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mmaitre\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Source\local_training_mlflow_project\.venv\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\mlflow\models\cli.py", line 54, in serve
    return _get_flavor_backend(
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\mlflow\pyfunc\backend.py", line 91, in serve
    return _execute_in_conda_env(
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\mlflow\pyfunc\backend.py", line 149, in _execute_in_conda_env
    conda_env_name = get_or_create_conda_env(conda_env_path, env_id=env_id)
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\mlflow\utils\conda.py", line 93, in get_or_create_conda_env
    process.exec_cmd(
  File "C:\Source\local_training_mlflow_project\.venv\lib\site-packages\mlflow\utils\process.py", line 40, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1
```

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

- train.py:
```
import mlflow
import sklearn

mlflow.sklearn.autolog(log_models=False) # Use explicit model logging to control pip requirements

# Load data
X, y = sklearn.datasets.load_diabetes(return_X_y = True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.2, random_state=0)

# Train model
with mlflow.start_run() as run:
    print(f"MLFlow run ID: {run.info.run_id}")

    model = sklearn.linear_model.Ridge(alpha=0.03)
    model.fit(X_train, y_train)

    mlflow.sklearn.log_model(
        model,
        artifact_path = "model",
        signature = mlflow.models.infer_signature(X_train[:10], y_train[:10]),
        input_example = X_train[:10],
        pip_requirements = "requirements.txt")
```

- requirements.in:
```
pandas==1.3.2
scikit-learn==0.24.2
mlflow==1.20.2
azureml-mlflow==1.34.0
```

Requirement pinning:
```
pip install pip-tools
pip-compile --generate-hashes --output-file=requirements.txt requirements.in
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Closing now that https://github.com/mlflow/mlflow/pull/5058 is merged.
