### ISSUE TITLE
Error logging to remote tracking server with Cloudflare Access

### ISSUE THREAD

**Issue by xlim7** [mlflow/mlflow#4955]
Our MLflow tracking server is deployed to Google App Engine and is protected by Cloudflare Access that requires users to login with their Okta account. However, we are getting the following error when logging using the Python API. Is there any way we can get around this issue? Thank you!

Python code:
```
import mlflow

client = mlflow.tracking.MlflowClient(tracking_uri=MLFLOW_TRACKING_URI)
experiment = client.get_experiment_by_name(EXPERIMENT_NAME)
```

Error:
```
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 263, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 55, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 170, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 137, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint was successful but the response body was not in a valid JSON format. Response body: '<!DOCTYPE html>
<html>
  <head>
    <title>Sign in ã» Cloudflare Access</title>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />
...
```

**Comment by sivanagendra123** [comment]
could you help me for this error

**Comment by ajaymaity** [comment]
How did you solve this error? I am having similar issue.
