### ISSUE TITLE
[SETUP-BUG] What's the best way to run `mlflow sagemaker build-and-push-container`?

### ISSUE THREAD

**Issue by zhangchi1** [mlflow/mlflow#4996]
### System information
- **image: python:3.8-slim**:
- **MLflow installed from (source or binary)**:
- **mlflow==1.20.2**:
- **Python version: 3.8**:
- **Exact command to reproduce**:
```
pip3 install mlflow==1.20.2
mlflow sagemaker build-and-push-container --build -c mlflow-pyfunc:1.20.2
```

### Describe the problem
We are trying to build and push mlflow sagemaker docker image to AWS ECR, in our CI/CD pipeline using image: python:3.8-slim. However, once we installed mlflow and run `mlflow sagemaker build-and-push-container` , we got the following error: (Check Logs section).
We are wondering if running `mlflow sagemaker build-and-push-container` require docker cmd installed? If so, does the community have any suggestion on what base image to use so that we can easily install mlflow, and docker, in order to run this cmd `mlflow sagemaker build-and-push-container`?

Thanks, 

### Other info / logs
```
/tmp/tmpyoqzwmvf/
/tmp/tmpyoqzwmvf/Dockerfile
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlflow/sagemaker/cli.py", line 534, in build_and_push_container
    mlflow.models.docker_utils._build_image(
  File "/usr/local/lib/python3.8/site-packages/mlflow/models/docker_utils.py", line 127, in _build_image
    proc = Popen(commands, cwd=cwd, stdout=PIPE, stderr=STDOUT, universal_newlines=True,)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

**Comment by sniafas** [comment]
Hi I would recommend the following

### Build the container

`mlflow sagemaker build-and-push-container --build`

### Deploy the container 

```
mlflow sagemaker deploy -a "container_name" 
-m "models:/model_name/Production" 
-e "arn:aws:iam::<id>:role/service-role/AmazonSageMaker-ExecutionRole-<id>"
-i "<id>.dkr.ecr.<location>.amazonaws.com/mlflow-pyfunc:<mlf_version>"
--region-name "<aws_region>" 
--mode "create" 
-t "aws_machine_type>" 
-c 1 
-f "python_function"
```
