### ISSUE TITLE
[BUG] 'log_artifact' and 'log_model' methods does not support files bigger than 5GB on s3

### ISSUE THREAD

**Issue by piotrkolanowski** [mlflow/mlflow#5083]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 11.6
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.20.2
- **Python version**: 3.8.8
- **npm version, if running the dev UI**: --
- **Exact command to reproduce**: --

### Describe the problem
If you try to log_model or log_artifact bigger than 5 GB it fails with 
```
mlflow.exceptions.MlflowException: API request failed with exception 400 Client Error
```
It doesn't happen for files that are smaller than 5 GB (even slightly like 4.9 GB file).

This probably happens due to use of "upload_file" method from boto3 in 
```
mlflow.store.artifact.artifact_repo.S3ArtifactRepository._upload_file 
```
method, which seems to upload the file with single PUT method.

The size of the file uploaded in the single put method is limited to 5GB.
A solution would be to use multipart upload for bigger files: https://stackoverflow.com/questions/43021266/aws-s3-max-file-and-upload-sizes

Uploading files bigger than 5GB is required for speech recognition models for example.

### Code to reproduce issue
mlflow.log_artifact("/file/bigger/than/5/GB.txt", "model")

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sebastiaanboer-db** [comment]
@piotrkolanowski I've tried uploading a 10gb file and have been unable to reproduce this issue. The upload_file function automatically uses multipart upload under the hood when necessary ([boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html)). Could you enable debug logs for boto3 so we can see what is going on? Something like this:
```
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

# The rest of your code
```

**Comment by piotrkolanowski** [comment]
Hi @sebastiaanboer-db, thanks fo looking into this issue. 

using the code

```
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

mlflow.log_artifact("/Users/the_user/tiny.txt", "model")  # ca. 4 B  
mlflow.log_artifact("/Users/the_user/big.txt", "model")  # ca. 5.4 GB
```
The small file gets uploaded, the big one does not (also all files unter 5GB can be uploaded, above cannot).

The logs:
```
DEBUG:urllib3.connectionpool:https://the-bucket.s3.eu-central-1.amazonaws.com:443 "PUT /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/tiny.txt?X-Amz-Security-Token=... HTTP/1.1" 200 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-project.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-project.cloud.databricks.com:443 "POST /api/2.0/mlflow/artifacts/credentials-for-write HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...'): Retry(total=4, connect=5, read=4, redirect=5, status=5)
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...'): Retry(total=3, connect=5, read=3, redirect=5, status=5)
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...'): Retry(total=2, connect=5, read=2, redirect=5, status=5)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...'): Retry(total=1, connect=5, read=1, redirect=5, status=5)
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=5, read=1, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (5): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...'): Retry(total=0, connect=5, read=0, redirect=5, status=5)
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=5, read=0, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))': /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (6): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-project.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-project.cloud.databricks.com:443 "POST /api/2.0/mlflow/runs/update HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/http/client.py", line 1071, in _send_output
    self.send(chunk)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  [Previous line repeated 2 more times]
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='the-bucket.s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=... (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 253, in cloud_storage_http_request
    method, url, max_retries, backoff_factor, retry_codes, timeout=timeout, **kwargs
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 74, in _get_http_response_with_retries
    response = http.request(method, url, **kwargs)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='the-bucket.s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=... (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 254, in _signed_url_upload_file
    "put", signed_write_uri, data=file, headers=headers
  File "/Users/the_user/.pyenv/versions/3.7.9/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 257, in cloud_storage_http_request
    raise MlflowException("API request failed with exception %s" % e)
mlflow.exceptions.MlflowException: API request failed with exception HTTPSConnectionPool(host='the-bucket.s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=... (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 551, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 336, in log_artifact
    dst_run_relative_artifact_path=run_relative_artifact_path,
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 275, in _upload_to_cloud
    self._signed_url_upload_file(cloud_credential_info, src_file_path)
  File "/Users/the_user/workspace/the_project/venv/lib/python3.7/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 258, in _signed_url_upload_file
    raise MlflowException(err)
mlflow.exceptions.MlflowException: API request failed with exception HTTPSConnectionPool(host='the-bucket.s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /location-prod/4711.jobs/mlflow-tracking/0815/0816/artifacts/model/big.txt?X-Amz-Security-Token=... (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))
```

**Comment by sebastiaanboer-db** [comment]
Nothing immediately stands out to me. Could you enable boto3 logging explicitly as well, something like the snippet below?
```
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
logging.getLogger('boto3').setLevel(logging.DEBUG)
```

Boto3's github repo also doesn't show related issues, other than updating boto3 to the latest version. Could you try that as well?

**Comment by piotrkolanowski** [comment]
Thanks for looking into this. 

Good point with newest boto3. To make a clean test I created new venv with python 3.8.12 and 
installed newest mlflow and boto3 available only.
Still does not work on the big files while working on small ones. 
The error message is different though.
Unfortunatelly log doesn't contain anything boto3 / botocore specific. 
I've set the logging level on boto3 / botocore to debug and it dit work fine (has logged a lot) on simple 
boto3_client.list_buckets() test. During the test with mlflow it does not log anything for boto3 / botocore.
Does mlflow override the logging settings for boto3 / used libs?

### python:
Python 3.8.12 (default, Oct 13 2021, 06:42:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin

### fresh venv, with mlflow and boto3 installed.

### pip freeze:
alembic==1.4.1
boto3==1.20.27
botocore==1.23.27
certifi==2021.10.8
charset-normalizer==2.0.9
click==8.0.3
cloudpickle==2.0.0
databricks-cli==0.16.2
docker==5.0.3
entrypoints==0.3
Flask==2.0.2
gitdb==4.0.9
GitPython==3.1.24
greenlet==1.1.2
gunicorn==20.1.0
idna==3.3
importlib-metadata==4.10.0
itsdangerous==2.0.1
Jinja2==3.0.3
jmespath==0.10.0
Mako==1.1.6
MarkupSafe==2.0.1
mlflow==1.22.0
numpy==1.22.0
packaging==21.3
pandas==1.3.5
prometheus-client==0.12.0
prometheus-flask-exporter==0.18.7
protobuf==3.19.1
pyparsing==3.0.6
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.3
PyYAML==6.0
querystring-parser==1.2.4
requests==2.27.0
s3transfer==0.5.0
six==1.16.0
smmap==5.0.0
SQLAlchemy==1.4.29
sqlparse==0.4.2
tabulate==0.8.9
typing_extensions==4.0.1
urllib3==1.26.7
websocket-client==1.2.3
Werkzeug==2.0.2
zipp==3.7.0

### full code

```
import mlflow
import logging
import boto3
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
logging.getLogger('boto3').setLevel(logging.DEBUG)
boto3.set_stream_logger('boto3', logging.DEBUG)
boto3.set_stream_logger('botocore', logging.DEBUG)

with mlflow.start_run(run_name="run_name", experiment_id="4711") as run:
    print(run.info.run_id)
    mlflow.log_artifact("/Users/the_user/big.txt", "model")  # ca. 5.4 GB
```

### log

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-workspace.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-workspace.cloud.databricks.com:443 "POST /api/2.0/mlflow/runs/create HTTP/1.1" 200 None
4712
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-workspace.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-workspace.cloud.databricks.com:443 "GET /api/2.0/mlflow/runs/get?run_uuid=4712&run_id=4712 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-workspace.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-workspace.cloud.databricks.com:443 "GET /api/2.0/mlflow/runs/get?run_id=4712 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-workspace.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-workspace.cloud.databricks.com:443 "POST /api/2.0/mlflow/artifacts/credentials-for-write HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-bucket.s3.eu-central-1.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://the-bucket.s3.eu-central-1.amazonaws.com:443 "PUT /location-prod/4711.jobs/mlflow-tracking/0815/4712/artifacts/big.txt?X-Amz-Security-Token=... HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): the-workspace.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://the-workspace.cloud.databricks.com:443 "POST /api/2.0/mlflow/runs/update HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 278, in cloud_storage_http_request
    yield response
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 256, in _signed_url_upload_file
    response.raise_for_status()
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://the-bucket.s3.eu-central-1.amazonaws.com/location-prod/4711.jobs/mlflow-tracking/0815/4712/artifacts/big.txt?X-Amz-Security-Token=...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 256, in _signed_url_upload_file
    response.raise_for_status()
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 280, in cloud_storage_http_request
    raise MlflowException("API request failed with exception %s" % e)
mlflow.exceptions.MlflowException: API request failed with exception 400 Client Error: Bad Request for url: https://the-bucket.s3.eu-central-1.amazonaws.com/location-prod/4711.jobs/mlflow-tracking/0815/4712/artifacts/big.txt?X-Amz-Security-Token=...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 605, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 334, in log_artifact
    self._upload_to_cloud(
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 275, in _upload_to_cloud
    self._signed_url_upload_file(cloud_credential_info, src_file_path)
  File "/Users/the_user/workspace/the_project/venv38/lib/python3.8/site-packages/mlflow/store/artifact/databricks_artifact_repo.py", line 258, in _signed_url_upload_file
    raise MlflowException(err)
mlflow.exceptions.MlflowException: API request failed with exception 400 Client Error: Bad Request for url: https://the-bucket.s3.eu-central-1.amazonaws.com/location-prod/4711.jobs/mlflow-tracking/0815/4712/artifacts/big.txt?X-Amz-Security-Token=...

**Comment by sebastiaanboer-db** [comment]
Ah I see! I thought this was for the s3 artifact repository directly, but it looks like the issue occurs when using the databricks artifact repository on S3. The latter doesn't currently support multipart upload (for the reason you mentioned in the description). Implementation is in `mlflow/store/artifact/databricks_artifact_repo.py`. Could you plz update the title / description to mention the databricks artifact repository?

**Comment by piotrkolanowski** [comment]
@dbczumar @sebastiaanboer-db I've updated the title and description to mention the databricks artifact repository. 
Please include the fix for this bug in the next patch / release, as it becomes urgent issue for us.

**Comment by tongyliu** [comment]
Hey @dbczumar and @sebastiaanboer-db, do you have any estimate on when the fix for this will be made? We're running into the same issue at Nextdoor when trying to upload a large (~10gb) model artifact. Let me know if you need any more info.

**Comment by ElefHead** [comment]
It looks like for [AWS or GCP based stores the method of transferring data is using a REST api](https://github.com/mlflow/mlflow/blob/8ba9c3dbf1dffa73c70a2d5f40689a8e72df8210/mlflow/store/artifact/databricks_artifact_repo.py#L346) using a PUT operation.
The [AWS documentation for uploading objects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html) says that with a single PUT operation, we can upload only up to 5GB.  
Converting this to boto3 based multipart upload would be extremely helpful.

**Comment by piyushdaftary** [comment]
@dbczumar / @sebastiaanboer-db : Wanted to check if you guys are working on the Bug fix? Else I will be happy to contribute fix for the issue. Thanks
