### ISSUE TITLE
[BUG] MLflow UI fails to list experiments in local sqllite store

### ISSUE THREAD

**Issue by maitre-matt** [mlflow/mlflow#5110]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.21.0
- **Python version**: 3.9
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: see problem description

### Describe the problem

Investigating https://github.com/mlflow/mlflow/issues/5100, I am trying to run MLflow with local sqlite backend store and local file artifact store but the stores do not seem to get properly initialized and `mlflow ui` fails to list the experiments. It looks like store initialization should have created `.\mlruns\0\meta.yaml` but did not.

Commands:
```
conda env create -f conda.yaml
conda activate MLflowTracking
mkdir mlruns
set MLFLOW_TRACKING_URI=sqlite:///./mlruns/sqlite.db
python train.py
mlflow ui
```

Error:
```
INFO:waitress:Serving on http://127.0.0.1:5000
WARNING:waitress.queue:Task queue depth is 1
WARNING:root:Malformed experiment '0'. Detailed error Yaml file '.\mlruns\0\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\mmaitre\Miniconda3\envs\MLflowTracking\lib\site-packages\mlflow\store\tracking\file_store.py", line 257, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "C:\Users\mmaitre\Miniconda3\envs\MLflowTracking\lib\site-packages\mlflow\store\tracking\file_store.py", line 340, in _get_experiment
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\mmaitre\Miniconda3\envs\MLflowTracking\lib\site-packages\mlflow\utils\file_utils.py", line 175, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '.\mlruns\0\meta.yaml' does not exist.
```

### Code to reproduce issue

Miniconda environment `conda.yaml`:
```
name: MLflowTracking
channels:
- nodefaults
dependencies:
- python=3.9
- pip
- pip:
  - matplotlib==3.4.3
  - scikit-learn==0.24.2
  - mlflow==1.21.0
```

Training script `train.py`:
```
import mlflow
import sklearn
import logging

mlflow.autolog(log_input_examples=True)

iris = sklearn.datasets.load_iris()

with mlflow.start_run() as run:
    print(f'MLflow run ID: {run.info.run_id}')
    model = sklearn.svm.SVC()
    model.fit(iris.data, iris.target)

try:
    mlflow.register_model(f'runs:/{run.info.run_id}/model', 'sklearn_svm_iris')
except mlflow.exceptions.MlflowException:
    logging.warning('Model registration skipped')
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ShnDanYao** [comment]
Hi! Have you solved this question?  I meet it too.

**Comment by superkido511** [comment]
@maitre-matt I got this problem too
