### ISSUE TITLE
`mlflow_transition_model_version_stage` (R) fails with HTTP `500` [BUG]

### ISSUE THREAD

**Issue by mrkaye97** [mlflow/mlflow#5199]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Monterrey (MLFlow hosted on Linux -- Docker + Heroku)
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

Trying to run `mlflow::mlflow_transition_model_version_stage` as follows:

```r
mlflow_transition_model_version_stage(
    name = "foo",
    version = 1,
    stage = "Staging"
)
```

gives me the following errors. In R, I see this:

```r
Error: API request to endpoint 'model-versions/transition-stage' failed with error code 500. Reponse body: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
'
```

and in my Heroku logs, I see this:

```bash
2021-12-25T04:55:31.636699+00:00 heroku[router]: at=info method=POST path="/api/2.0/mlflow/model-versions/transition-stage" host=<<my host>> request_id=<<rid>> fwd=... dyno=web.1 connect=0ms service=2ms status=500 bytes=463 protocol=https
2021-12-25T04:55:31.635410+00:00 app[web.1]: 2021/12/25 04:55:31 ERROR mlflow.server: Exception on /api/2.0/mlflow/model-versions/transition-stage [POST]
2021-12-25T04:55:31.635418+00:00 app[web.1]: Traceback (most recent call last):
2021-12-25T04:55:31.635419+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 585, in _ConvertFieldValuePair
2021-12-25T04:55:31.635420+00:00 app[web.1]:     setattr(message, field.name, _ConvertScalarFieldValue(value, field))
2021-12-25T04:55:31.635420+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 720, in _ConvertScalarFieldValue
2021-12-25T04:55:31.635421+00:00 app[web.1]:     return _ConvertBool(value, require_str)
2021-12-25T04:55:31.635421+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 838, in _ConvertBool
2021-12-25T04:55:31.635422+00:00 app[web.1]:     raise ParseError('Expected true or false without quotes.')
2021-12-25T04:55:31.635423+00:00 app[web.1]: google.protobuf.json_format.ParseError: Expected true or false without quotes.
2021-12-25T04:55:31.635423+00:00 app[web.1]: 
2021-12-25T04:55:31.635424+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-12-25T04:55:31.635424+00:00 app[web.1]: 
2021-12-25T04:55:31.635424+00:00 app[web.1]: Traceback (most recent call last):
2021-12-25T04:55:31.635425+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2021-12-25T04:55:31.635425+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-12-25T04:55:31.635426+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2021-12-25T04:55:31.635426+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-12-25T04:55:31.635426+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2021-12-25T04:55:31.635427+00:00 app[web.1]:     rv = self.dispatch_request()
2021-12-25T04:55:31.635427+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2021-12-25T04:55:31.635427+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-12-25T04:55:31.635428+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/mlflow/server/handlers.py", line 238, in wrapper
2021-12-25T04:55:31.635428+00:00 app[web.1]:     return func(*args, **kwargs)
2021-12-25T04:55:31.635428+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/mlflow/server/handlers.py", line 767, in _transition_stage
2021-12-25T04:55:31.635429+00:00 app[web.1]:     request_message = _get_request_message(TransitionModelVersionStage())
2021-12-25T04:55:31.635429+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/mlflow/server/handlers.py", line 219, in _get_request_message
2021-12-25T04:55:31.635429+00:00 app[web.1]:     parse_dict(request_json, request_message)
2021-12-25T04:55:31.635430+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/mlflow/utils/proto_json_utils.py", line 153, in parse_dict
2021-12-25T04:55:31.635430+00:00 app[web.1]:     ParseDict(js_dict=js_dict, message=message, ignore_unknown_fields=True)
2021-12-25T04:55:31.635430+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 445, in ParseDict
2021-12-25T04:55:31.635431+00:00 app[web.1]:     parser.ConvertMessage(js_dict, message)
2021-12-25T04:55:31.635431+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 476, in ConvertMessage
2021-12-25T04:55:31.635431+00:00 app[web.1]:     self._ConvertFieldValuePair(value, message)
2021-12-25T04:55:31.635432+00:00 app[web.1]:   File "/opt/conda/lib/python3.9/site-packages/google/protobuf/json_format.py", line 588, in _ConvertFieldValuePair
2021-12-25T04:55:31.635432+00:00 app[web.1]:     raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
2021-12-25T04:55:31.635433+00:00 app[web.1]: google.protobuf.json_format.ParseError: Failed to parse archive_existing_versions field: Expected true or false without quotes..
```

I'm not sure how to repro this more cleanly, but it seems like a bug. I tried explicitly setting the `archive_existing_versions` argument to a bunch of different things (i.e. `TRUE`, `FALSE`, `"true"`, `"false"`, etc.) to no avail.

And while we're at I also noticed a small typo in the R package documentation under `?mlflow_transition_model_version_stage`: `Transition 'model_version' to this tage.` --> `Transition 'model_version' to this stage.`. It'd also be helpful to list out what the allowed stages are in the docs and to use something like `match.arg()` [at this point in the code](https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/R/model-registry.R#L302-L306) to match against the allowed stages (I'd be happy to PR this change -- it'd be easy). 

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mrkaye97** [comment]
As it turns out, there's a bug in `mlflow_rest` here: https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/R/tracking-rest.R#L68

The issue is that that ^ line is converting boolean values to characters, so `TRUE` is converted to `"TRUE"`, which then fails. An easy (albeit hacky, since it still leaves us open to more bugs) fix, would be to do something like this:

```r
POST = function(){
  httr::POST( api_url,
        body = if (is.null(data)) NULL else rapply(data, function(.x) ifelse(!is.logical(.x), as.character(.x), .x), how = "replace"),
        encode = "json",
        mlflow:::mlflow_rest_timeout(),
        config = rest_config$config,
        req_headers
  )
},
...
```

Where we first check the data type of the thing we're trying to convert to a character before converting, just to make sure we don't coerce a boolean to a string. _However_, this brings up another question: Why are we coercing these types anyways? As far as I can tell, the following also works:

```r
POST = function(){
  httr::POST( api_url,
        body = if (is.null(data)) NULL else data,
        encode = "json",
        mlflow:::mlflow_rest_timeout(),
        config = rest_config$config,
        req_headers
  )
},
...
```

so maybe it makes sense to just get rid of the type coercion? Why is this type coercion here in the first place? Any pointers on this front would be great.

Separately, I'm happy to PR fixes for these issues. If I do, what is the best way to test any changes I make? I see we have some test infrastructure set up in `testthat/`, and I see there's already a test for this function here: https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/tests/testthat/test-model-registry.R#L294-L313, but I'm not sure how this test is passing, given that (unless I'm missing something big), it's pretty broken.

Thanks for any pointers on this, and let me know if I can help out!

**Comment by mrkaye97** [comment]
One other comment on this before I forget: It's concerning to me that I can get a `500` for what boils down to a bad parameter data type. This should probably return a `400` instead I assume. As it is right now, there's no way for me (the user) to figure out what went wrong without digging into the logs + the API call itself, which seems problematic. Is there any kind of JSON validation (e.g. against a schema maybe?) happening behind the scenes?

**Comment by kriscon-db** [comment]
Hi Matt.  I took a look into this and I don't think your proposed solution will work.  The HTTR POST call documentation here: https://httr.r-lib.org/reference/POST.html, says that the body needs to be a character or raw vector, so the proposed change will break the mlflow_rest function for POST calls.

Additionally, I have tested the code w/in a Databricks R notebook and the model state transition function works as expected.  I'm not really sure about the specifics of the local instance you were testing on, but it seems likely that the problem lies somewhere in that that setup.  I did land a PR that addressed the documentation issues you raised here though.

**Comment by mrkaye97** [comment]
hey @kriscon-db! thanks for circling back to this. we've been through so many versions and changes now that maybe this is fixed, I'm not sure. 

Re: proposed solution for the R package, I think it will work :) I think because the `encode = "json"` is set, but I'd encourage you to try it out. I tested and it worked fine.

For reference, here's my implementation of the API call in our lightMLFlow package: https://github.com/collegevine/lightMLFlow/blob/main/R/rest.R#L110-L123

**Comment by kriscon-db** [comment]
> Re: proposed solution for the R package, I think it will work :) I think because the `encode = "json"` is set, but I'd encourage you to try it out. I tested and it worked fine.

I did try out an implementation but saw that it broke some other tests (mlflow_log_batch specifically).  I think the stage transition test mocks the `mlflow_rest` function which is why making a change at that deep of a level doesn't actually change the behavior of the test.  You can propose a change to mlflow by making a fork of mlflow, and creating a PR that adds the changes you are proposing to correct the behavior you are observing and have the CI run all of the unit tests.  At that point, you can have someone who is more knowledgable in R read through the changes and advise on next steps.

**Comment by mrkaye97** [comment]
>  saw that it broke some other tests (mlflow_log_batch specifically)

Aha okay, that makes sense! I didn't try running the actual test suite -- I just tested out API calls against a local server manually.

Going to close this now, since honestly I don't think it's worth making changes like this to the package -- IMO it needs a bigger overhaul :/ and we've been using our own API wrapper package instead
