### ISSUE TITLE
Unable to log a TensorFlow SavedModel

### ISSUE THREAD

**Issue by luana-be** [mlflow/mlflow#5247]
I'm working with MLflow version **1.22.0** and I'm trying to log a TensorFlow model which is in the SavedModel format. When I run the command:

`mlflow.tensorflow.log_model(tf_saved_model_dir=export_dir, tf_meta_graph_tags=["serve"], artifact_path="mlruns/0/0dcc80caa5be4574a92a26306e24cdb8/artifacts/model", tf_signature_def_key=None)`

I get the following error:

```
2022/01/10 14:37:29 INFO mlflow.tensorflow: Validating the specified TensorFlow model by attempting to load it in a new TensorFlow graph...
WARNING:tensorflow:From /mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py:405: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 62, in wrapper
    return func(**kwargs)
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py", line 193, in log_model
    extra_pip_requirements=extra_pip_requirements,
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/models/model.py", line 187, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 62, in wrapper
    return func(**kwargs)
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py", line 263, in save_model
    tf_signature_def_key=tf_signature_def_key,
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py", line 330, in _validate_saved_model
    tf_signature_def_key=tf_signature_def_key,
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py", line 405, in _load_tensorflow_saved_model
    tags=tf_meta_graph_tags, export_dir=tf_saved_model_dir
  File "/mnt/3/shares/biobert/miniconda3/envs/biobert/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
TypeError: load() missing 1 required positional argument: 'sess'
```

A similar issue is occurring with the command **mlflow.tensorflow.save_model** as well. Was "**sess**" required in previous versions? I found some references to this parameter in the MLflow Documentation.

Note that I'm able to load the model with the TensorFlow library, without passing through MLflow.

Thank you in advance for your help!

**Comment by abaveja313** [comment]
I am having this same issue

**Comment by jingnanxue** [comment]
I met the same problem. It turned out that the new version of mlflow doesn't support tensorflow 1.x SavedModel. You can either downgrade the mlflow to previous version (1.14.1 worked for me) or read a tensorflow 2.x SavedModel file.
