### ISSUE TITLE
[BUG] mlflow destructor fails when using TensorFlow MirroredStrategy

### ISSUE THREAD

**Issue by LucasCampos** [mlflow/mlflow#5262]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.22.0
- **Python version**: Python 3.8.12
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: python example.py
- **Tensorflow version**: 2.7

### Describe the problem
Whenever I try to use mlflow with TensorFlow's mirrored strategy, the destructor throws an exception related to Multiprocessing.

### Code to reproduce issue
```python
#! /usr/bin/env python

import mlflow
import tensorflow as tf

if tf.config.list_physical_devices('GPU'):
    strategy = tf.distribute.MirroredStrategy()
else:  # Use the Default Strategy
    strategy = tf.distribute.get_strategy()


def main():

    mlflow.start_run(run_name="train")
    return

if __name__ == "__main__":
    main()
```

## Output

```
Exception ignored in: <function Pool.__del__ at 0x7f791ce11820>
Traceback (most recent call last):
  File "/home/homeGlobal/lcampos/anaconda3/envs/base-tf-cuda-env/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/homeGlobal/lcampos/anaconda3/envs/base-tf-cuda-env/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

## Conda environment
https://gist.github.com/LucasCampos/129db886abca17a76561edc912670e2a

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by dbczumar** [comment]
@LucasCampos Thank you for raising this. Please let me know if you're able to investigate. To confirm, once `import mlflow` is removed, the error no longer occurs?

**Comment by LucasCampos** [comment]
> Please let me know if you're still able to investigate further, as indicated above.

I would be happy to, but would need quite a lot of guidance, if that is okay to the MLflow community.

> To confirm, once `import mlflow` is removed, the error no longer occurs?

Yes. The error is gone if I remove `import mlflow` or if I remove the `MirroredStrategy`.

**Comment by dbczumar** [comment]
@LucasCampos Thank you! We're happy to help with diagnosing MLflow-specific failures and creating a fix. If possible, it would be very useful to identify the line(s) responsible for the destructor failure; we can advise from there :).

**Comment by jiyoon0630** [comment]
I have same error when using tf.distribute.MirroredStrategy and mlflow.
As @LucasCampos said, importing mlflow library causes attribute error. 
Is there any further update regarding this issue?

Here is my code.
```
import tensorflow as tf
import mlflow

strategy = tf.distribute.MirroredStrategy()

def main():
    print("hello")
    
if __name__ == '__main__':
    main()
```

Dependancies:
python 3.8.10
tensorflow 2.5.0+nv
mlflow 1.27.0
