### ISSUE TITLE
[BUG] MLFlow + Wasabi + Prophet not working

### ISSUE THREAD

**Issue by JMGGarcia** [mlflow/mlflow#5330]
### Willingness to contribute

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
OS: Fedora 31
MLFlow version: 1.22.0
Python: 3.7.9

Train a model and store it in a

### Describe the problem
I've trained a Prophet model and store it in a Wasabi bucket without a problem using MLFlow's Python API. When I load it, I get an exception. I have no problem when using a personal S3 bucket, but using a Wasabi server gives problems. 

### Logs
```
Traceback (most recent call last):
  File "run_mlflow_predictions.py", line 93, in <module>
    df_forecast = load_model(run_id)
  File "run_mlflow_predictions.py", line 73, in load_model
    loaded_model = prophet.load_model(model_path)
  File "xxx/mlflow/venv/lib64/python3.7/site-packages/mlflow/prophet.py", line 285, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "xxx/mlflow/venv/lib64/python3.7/site-packages/mlflow/tracking/artifact_utils.py", line 96, in _download_artifact_from_uri
    artifact_path=artifact_path, dst_path=output_path
  File "xxx/venv/lib64/python3.7/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 125, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
  File "xxx/venv/lib64/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 179, in download_artifacts
    if self._is_directory(artifact_path):
  File "xxx/venv/lib64/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 61, in _is_directory
    listing = self.list_artifacts(artifact_path)
  File "xxx/venv/lib64/python3.7/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 47, in list_artifacts
    head, tail = self.artifact_uri.split(sep, maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by thistleknot** [comment]
how has this been an issue for 2+ years?

the error is here
url, tail = self.artifact_uri.split(endpoint, maxsplit=1)
it’s within the
C:\wsl\nuner\lib\site-packages\mlflow\store\artifact\http_artifact_repo.py:84, in HttpArtifactRepository.list_artifacts(self, path) 82 def list_artifacts(self, path=None):
which means the code has a bug… and from what I can tell it’s over 2 years old
