### ISSUE TITLE
[BUG] INTERNAL_SERVER_ERROR when using MSSQL as backend store

### ISSUE THREAD

**Issue by dianacarvalho1** [mlflow/mlflow#5360]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Big Sur
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: version 1.23.1
- **Python version**: Python 3.9.9
- **npm version, if running the dev UI**: -

### Describe the problem
When running a tracking ui with `mlflow ui --backend-store-uri  <connection_str>` and specifying the backend store a MSSQL database, there is a problem when trying to access the UI. 
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/63718157/153061210-2ca9fdc5-1090-4468-a99d-02dfa7f6f227.png">

### Code to reproduce issue
Start the tracking UI with a backend store a MSSQL database.
Or do:
````
mlflow.set_tracking_uri(connection_str_to_mssql_db)
mlflow.search_runs(experiment_ids=[0], order_by= ['attributes.start_time DESC'])
````

### Other info / logs
In the logs, there is the following error:
````
2022/02/08 14:30:14 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified. (145) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 79, in make_managed_session
    yield session
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 788, in _search_runs
    query.distinct()
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified. (145) (SQLExecDirectW)')
[SQL: SELECT DISTINCT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id, CASE WHEN (runs.start_time IS NULL) THEN ? ELSE ? END AS anon_1 
FROM runs 
WHERE runs.experiment_id IN (?) AND runs.lifecycle_stage IN (?) ORDER BY CASE WHEN (runs.start_time IS NULL) THEN ? ELSE ? END, runs.start_time DESC, runs.run_uuid
 OFFSET ? ROWS
 FETCH FIRST ? ROWS ONLY]
[parameters: (1, 0, '0', 'active', 1, 0, 0, 100)]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/server/handlers.py", line 238, in wrapper
    return func(*args, **kwargs)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/server/handlers.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/server/handlers.py", line 549, in _search_runs
    run_entities = _get_tracking_store().search_runs(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/store/tracking/abstract_store.py", line 242, in search_runs
    runs, token = self._search_runs(
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 802, in _search_runs
    next_page_token = compute_next_token(len(runs))
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 86, in make_managed_session
    raise MlflowException(message=e, error_code=INTERNAL_ERROR)
mlflow.exceptions.MlflowException: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified. (145) (SQLExecDirectW)')
[SQL: SELECT DISTINCT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id, CASE WHEN (runs.start_time IS NULL) THEN ? ELSE ? END AS anon_1 
FROM runs 
WHERE runs.experiment_id IN (?) AND runs.lifecycle_stage IN (?) ORDER BY CASE WHEN (runs.start_time IS NULL) THEN ? ELSE ? END, runs.start_time DESC, runs.run_uuid
 OFFSET ? ROWS
 FETCH FIRST ? ROWS ONLY]
[parameters: (1, 0, '0', 'active', 1, 0, 0, 100)]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/server/handlers.py", line 241, in wrapper
    response.set_data(e.serialize_as_json())
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/site-packages/mlflow/exceptions.py", line 60, in serialize_as_json
    return json.dumps(exception_dict)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/dianacarvalho/opt/anaconda3/envs/vpdc-complete/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProgrammingError is not JSON serializable
````
### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by dianacarvalho1** [comment]
I believe this is a sqlalchemy bug instead so opened an issue [there](https://github.com/sqlalchemy/sqlalchemy/issues/7696) as well.
