### ISSUE TITLE
[BUG] MLFLow proxy artifact does not work on blob azure

### ISSUE THREAD

**Issue by antoinevokleber** [mlflow/mlflow#5480]
Hi All,
i use MLflow 1.24.0 on kubernetes Server

on my docker image, i use python 3.8 
my script to launch server mflow : 
```
mlflow server '--backend-store-uri=postgresql://********@10.0.1.15:5432/mlflow_db' --artifacts-destination wasbs://mlartifacts@********.blob.core.windows.net/ --serve-artifacts --host 0.0.0.0 --port 80
```

On my client linux (python 3.6, debian 4.19), i use example mlflow ElasticnetWineModel to save model on my server with tracking uri of my server.

I have some metrics, logs on the mlflow interface. However, I don't see any artifacts on the user interface MlFlow and the azure blob.
When on my client, i have added environment variable (AZURE_STORAGE_ACCESS_KEY and AZURE_STORAGE_CONNECTION_STRING) for the connection on blob azure, the artifacts are visible from UI and blob Azure.

This seems to mean that the proxy process is not working. It is always the client that sends the artifacts, right?

i have try with different option to launch the server (--default-artifact-root wasbs://mlartifacts@********.blob.core.windows.net/)

run without env variable:
```
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.793164022927685
  MAE: 0.6271946374319586
  R2: 0.10862644997792636
wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/6/955dc732b1a2484d9aa0dcc2b6b838d0/artifacts
WARNING:azure.identity._credentials.chained:DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-05-17T07:28:42.0742305Z and was inactive for 90.00:00:00.\r\nTrace ID: 93e04446-3703-4d99-8890-a5bc7c9cb300\r\nCorrelation ID: c372a377-3dcb-4fab-8c9b-d040c5fe4071\r\nTimestamp: 2022-03-11 07:53:48Z","error_codes":[700082],"timestamp":"2022-03-11 07:53:48Z","trace_id":"93e04446-3703-4d99-8890-a5bc7c9cb300","correlation_id":"c372a377-3dcb-4fab-8c9b-d040c5fe4071","error_uri":"https://login.microsoftonline.com/error?code=700082"}
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 75, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 650, in get_raw_token
    tenant_dest, resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 1019, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 347, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 127, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 184, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 160, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 339, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-05-17T07:28:42.0742305Z and was inactive for 90.00:00:00.\r\nTrace ID: 93e04446-3703-4d99-8890-a5bc7c9cb300\r\nCorrelation ID: c372a377-3dcb-4fab-8c9b-d040c5fe4071\r\nTimestamp: 2022-03-11 07:53:48Z","error_codes":[700082],"timestamp":"2022-03-11 07:53:48Z","trace_id":"93e04446-3703-4d99-8890-a5bc7c9cb300","correlation_id":"c372a377-3dcb-4fab-8c9b-d040c5fe4071","error_uri":"https://login.microsoftonline.com/error?code=700082"}
To open an issue, please run: 'az feedback'

To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

```

the artifacts are nt present on the blob azure.

Run with Env variable to access blob azure:

**Hint : the variable AZURE_STORAGE_ACCESS_KEy is not necessary. but we need AZURE_STORAGE_CONNECTION_STRING. i think it's a problem. In a proxy process for me, the storage of artifacts is transparent and not directly accessible.**
```
export AZURE_STORAGE_CONNECTION_STRING='*************************intSuffix=core.windows.net'
export AZURE_STORAGE_ACCESS_KEY='************'
python train.py 0.5 0.5
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.793164022927685
  MAE: 0.6271946374319586
  R2: 0.10862644997792636

wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/6/6e0786f6c4c54d36b629543aaad25fe1/artifacts
Registered model 'ElasticnetWineModel' already exists. Creating a new version of this model...
2022/03/11 07:56:17 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: ElasticnetWineModel, version 11
Created version '11' of model 'ElasticnetWineModel'.
```

the artifacts are in this case present on the blob

On the mlflow Ui, I can see the artifact model. the server has access to the azure blob.
![image](https://user-images.githubusercontent.com/44051139/157826874-18149755-c6a3-4ca0-be75-696f1a90d2ce.png)

thanks for your help

**Comment by BenWilson2** [comment]
Hi @antoinevokleber are you attempting to log new runs to an existing experiment after changing the artifact handling with the MLflow tracking server to use proxied mode?

**Comment by BenWilson2** [comment]
Could you try with:
`mlflow server '--backend-store-uri=postgresql://********@10.0.1.15:5432/mlflow_db' --artifacts-destination wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/ --serve-artifacts --host 0.0.0.0 --port 80 --gunicorn-opts "--log-level debug"`

In order to remove the duplicated artifacts-destination and default-artifact-root destination entries and to enable debug mode on API calls?

**Comment by antoinevokleber** [comment]
Hi,
Below the log:
```
+ mlflow server '--backend-store-uri=postgresql://lincoln:L!ncolnTecsas94@10.0.1.15:5432/mlflow_db' --artifacts-destination wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/ --serve-artifacts --host 0.0.0.0 --port 80 --gunicorn-opts '--log-level debug'
[2022-03-15 07:13:14 +0000] [9] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:80']
  backlog: 2048
  workers: 4
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: mlflow.server:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fd3bcee88b0>
  on_reload: <function OnReload.on_reload at 0x7fd3bcee89d0>
  when_ready: <function WhenReady.when_ready at 0x7fd3bcee8af0>
  pre_fork: <function Prefork.pre_fork at 0x7fd3bcee8c10>
  post_fork: <function Postfork.post_fork at 0x7fd3bcee8d30>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fd3bcee8e50>
  worker_int: <function WorkerInt.worker_int at 0x7fd3bcee8f70>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fd3bce7d0d0>
  pre_exec: <function PreExec.pre_exec at 0x7fd3bce7d1f0>
  pre_request: <function PreRequest.pre_request at 0x7fd3bce7d310>
  post_request: <function PostRequest.post_request at 0x7fd3bce7d3a0>
  child_exit: <function ChildExit.child_exit at 0x7fd3bce7d4c0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fd3bce7d5e0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fd3bce7d700>
  on_exit: <function OnExit.on_exit at 0x7fd3bce7d820>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-03-15 07:13:14 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-03-15 07:13:14 +0000] [9] [DEBUG] Arbiter booted
[2022-03-15 07:13:14 +0000] [9] [INFO] Listening at: http://0.0.0.0:80 (9)
[2022-03-15 07:13:14 +0000] [9] [INFO] Using worker: sync
[2022-03-15 07:13:14 +0000] [11] [INFO] Booting worker with pid: 11
[2022-03-15 07:13:14 +0000] [12] [INFO] Booting worker with pid: 12
[2022-03-15 07:13:14 +0000] [13] [INFO] Booting worker with pid: 13
[2022-03-15 07:13:14 +0000] [14] [INFO] Booting worker with pid: 14
[2022-03-15 07:13:14 +0000] [9] [DEBUG] 4 workers
[2022-03-15 07:18:05 +0000] [14] [DEBUG] POST /GponForm/diag_Form
[2022-03-15 09:11:15 +0000] [14] [DEBUG] GET /api/2.0/mlflow/experiments/get-by-name
[2022-03-15 09:11:16 +0000] [14] [DEBUG] POST /api/2.0/mlflow/runs/create
[2022-03-15 09:11:16 +0000] [13] [DEBUG] POST /api/2.0/mlflow/runs/log-parameter
[2022-03-15 09:11:16 +0000] [11] [DEBUG] POST /api/2.0/mlflow/runs/log-parameter
[2022-03-15 09:11:17 +0000] [14] [DEBUG] POST /api/2.0/mlflow/runs/log-metric
[2022-03-15 09:11:17 +0000] [12] [DEBUG] POST /api/2.0/mlflow/runs/log-metric
[2022-03-15 09:11:18 +0000] [14] [DEBUG] POST /api/2.0/mlflow/runs/log-metric
[2022-03-15 09:11:18 +0000] [14] [DEBUG] GET /api/2.0/mlflow/runs/get
[2022-03-15 09:11:20 +0000] [14] [DEBUG] GET /api/2.0/mlflow/runs/get
[2022-03-15 09:11:24 +0000] [13] [DEBUG] POST /api/2.0/mlflow/runs/update
```
for your information, i have created environment variable on the server:
- AZURE_STORAGE_CONNECTION_STRING : connection string to account storage blob
- AZURE_STORAGE_ACCESS_KEY : password for the connection adsl
- MLFLOW_ARTIFACT_PATH  = wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/

**Comment by dbczumar** [comment]
@antoinevokleber What issue(s) are you seeing when you run with the latest configuration suggested by @BenWilson2 ? To confirm, did you create another new experiment after updating the configuration? This is necessary because all of the preexisting experiments will continue to reference `wasbs:/` in the artifact root, causing the MLflow client to attempt to write to Azure Blob Storage directly, rather than uploading artifacts through the MLflow server.

```
mlflow server '--backend-store-uri=postgresql://************@10.0.1.15:5432/mlflow_db' --artifacts-destination wasbs://mlartifacts@pocmlopsvelo.blob.core.windows.net/ --serve-artifacts --host 0.0.0.0 --port 80 --gunicorn-opts '--log-level debug'
```

**Comment by antoinevokleber** [comment]
Hello, yes i have create a new experiment . The problem is that the upload of artifacts from the client required access to the server storage and moreover required to know the connection string, which in my opinion is anti pattern with the proxy artifact mlflow. The user in this architecture proxy don't need to know server storage.
