### ISSUE TITLE
Issue with retrieving model from ray

### ISSUE THREAD

**Issue by rajesh-chawla** [mlflow/mlflow#5678]
Hi folks,

I'm having issues retrieving a mlflow model from a ray cluster using mlflow deployment. In the stack trace I see. 
```
(ServeController pid=17178) PermissionError: [Errno 13] Permission denied: '/mlruns'
```

I've started a ray cluster using the commands:
```
ray start --head
serve start
```

The specific command I'm executing is:
```
mlflow deployments create -t ray-serve -m models:/White-Wine/4 --name RajeshOnnxWine
```

Items I've tried / done:

- tried setting MLFLOW_TRACKING_URI to http://localhost:5001, which is where I view the MLFlow UI
- tried setting MLFLOW_TRACKING_URI  to 'postgresql://postgres@groq1.entanglement.ai:6789/mlflow', which is the location of the model repository in PostgreSQL
- verified that where I run mlflow has access to the artifact root.

Any thoughts on how to avoid the error for Permission denied on /mlruns.

Regards,
Rajesh

**Comment by harupy** [comment]
@rajesh-chawla Can you share the full stack trace?

**Comment by rajesh-chawla** [comment]
@harupy -- Please see the stack trace below
```
2022-04-12 07:50:36,853 INFO api.py:262 -- Updating deployment 'RajeshOnnxWine'. component=serve deployment=RajeshOnnxWi
ne
(ServeController pid=17178) 2022-04-12 07:50:36,906     INFO deployment_state.py:920 -- Adding 1 replicas to dep
loyment 'RajeshOnnxWine'. component=serve deployment=RajeshOnnxWine
(ServeController pid=17178) 2022-04-12 07:50:37,950     ERROR deployment_state.py:284 -- Exception in deployment
 'RajeshOnnxWine'
(ServeController pid=17178) Traceback (most recent call last):
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/deployment_state.py
", line 278, in check_ready
(ServeController pid=17178)     deployment_config, version = ray.get(ready)[0]
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/_private/client_mode_hook
.py", line 105, in wrapper
(ServeController pid=17178)     return func(*args, **kwargs)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/worker.py", line 1763, in
 get
(ServeController pid=17178)     raise value.as_instanceof_cause()
(ServeController pid=17178) ray.exceptions.RayTaskError(PermissionError): ray::RayServeWrappedReplica.reco
nfigure() (pid=59118, ip=10.81.1.40, repr=<ray.serve.replica.RajeshOnnxWine object at 0x7fef987cc8b0>)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 432, in result
(ServeController pid=17178)     return self.__get_result()
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 388, in __get_result
(ServeController pid=17178)     raise self._exception
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 1
43, in reconfigure
(ServeController pid=17178)     await self._initialize_replica()
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 9
0, in initialize_replica
(ServeController pid=17178)     await sync_to_async(_callable.__init__)(*init_args,
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow_ray_serve/__init__.py"
, line 48, in __init__
(ServeController pid=17178)     self.model = mlflow.pyfunc.load_model(model_uri=model_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", l
ine 691, in load_model
(ServeController pid=17178)     local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=d
st_path)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/artifact_util
s.py", line 95, in _download_artifact_from_uri
(ServeController pid=17178)     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 107, in get_artifact_repository
(ServeController pid=17178)     return _artifact_repository_registry.get_artifact_repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 73, in get_artifact_repository
(ServeController pid=17178)     return repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 35, in __init__
(ServeController pid=17178)     uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 53, in get_underlying_uri
(ServeController pid=17178)     client = MlflowClient(registry_uri=databricks_profile_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/client.py", l
ine 70, in __init__
(ServeController pid=17178)     self._tracking_client = TrackingServiceClient(final_tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 48, in __init__
(ServeController pid=17178)     self.store
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 52, in store
(ServeController pid=17178)     return utils._get_store(self.tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 155, in _get_store
(ServeController pid=17178)     return _tracking_store_registry.get_store(store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 39, in get_store
(ServeController pid=17178)     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 49, in _get_store_with_resolved_uri
(ServeController pid=17178)     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 109, in _get_file_store
(ServeController pid=17178)     return FileStore(store_uri, store_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/tracking/file_st
ore.py", line 140, in __init__
(ServeController pid=17178)     mkdir(self.root_directory)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 114, in mkdir
(ServeController pid=17178)     raise e
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 111, in mkdir
(ServeController pid=17178)     os.makedirs(target)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/os
.py", line 223, in makedirs
(ServeController pid=17178)     mkdir(name, mode)
(ServeController pid=17178) PermissionError: [Errno 13] Permission denied: '/mlruns'
(ServeController pid=17178) 2022-04-12 07:50:38,162     INFO deployment_state.py:920 -- Adding 1 replicas to dep
loyment 'RajeshOnnxWine'. component=serve deployment=RajeshOnnxWine
(ServeController pid=17178) 2022-04-12 07:50:39,297     ERROR deployment_state.py:284 -- Exception in deployment
 'RajeshOnnxWine'
(ServeController pid=17178) Traceback (most recent call last):
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/deployment_state.py
", line 278, in check_ready
(ServeController pid=17178)     deployment_config, version = ray.get(ready)[0]
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/_private/client_mode_hook
.py", line 105, in wrapper
(ServeController pid=17178)     return func(*args, **kwargs)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/worker.py", line 1763, in
 get
(ServeController pid=17178)     raise value.as_instanceof_cause()
(ServeController pid=17178) ray.exceptions.RayTaskError(PermissionError): ray::RayServeWrappedReplica.reco
nfigure() (pid=3410, ip=10.81.1.40, repr=<ray.serve.replica.RajeshOnnxWine object at 0x7f76ac3a98b0>)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 432, in result
(ServeController pid=17178)     return self.__get_result()
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 388, in __get_result
(ServeController pid=17178)     raise self._exception
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 1
43, in reconfigure
(ServeController pid=17178)     await self._initialize_replica()
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 9
0, in initialize_replica
(ServeController pid=17178)     await sync_to_async(_callable.__init__)(*init_args,
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow_ray_serve/__init__.py"
, line 48, in __init__
(ServeController pid=17178)     self.model = mlflow.pyfunc.load_model(model_uri=model_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", l
ine 691, in load_model
(ServeController pid=17178)     local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=d
st_path)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/artifact_util
s.py", line 95, in _download_artifact_from_uri
(ServeController pid=17178)     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 107, in get_artifact_repository
(ServeController pid=17178)     return _artifact_repository_registry.get_artifact_repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 73, in get_artifact_repository
(ServeController pid=17178)     return repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 35, in __init__
(ServeController pid=17178)     uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 53, in get_underlying_uri
(ServeController pid=17178)     client = MlflowClient(registry_uri=databricks_profile_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/client.py", l
ine 70, in __init__
(ServeController pid=17178)     self._tracking_client = TrackingServiceClient(final_tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 48, in __init__
(ServeController pid=17178)     self.store
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 52, in store
(ServeController pid=17178)     return utils._get_store(self.tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 155, in _get_store
(ServeController pid=17178)     return _tracking_store_registry.get_store(store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 39, in get_store
(ServeController pid=17178)     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 49, in _get_store_with_resolved_uri
(ServeController pid=17178)     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 109, in _get_file_store
(ServeController pid=17178)     return FileStore(store_uri, store_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/tracking/file_st
ore.py", line 140, in __init__
(ServeController pid=17178)     mkdir(self.root_directory)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 114, in mkdir
(ServeController pid=17178)     raise e
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 111, in mkdir
(ServeController pid=17178)     os.makedirs(target)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/os
.py", line 223, in makedirs
(ServeController pid=17178)     mkdir(name, mode)
(ServeController pid=17178) PermissionError: [Errno 13] Permission denied: '/mlruns'
(ServeController pid=17178) 2022-04-12 07:50:39,505     INFO deployment_state.py:920 -- Adding 1 replicas to dep
loyment 'RajeshOnnxWine'. component=serve deployment=RajeshOnnxWine
Traceback (most recent call last):
  File "/data/venv/vmray/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/venv/vmray/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/deployments/cli.py", line 133, in create_deployment
    deployment = client.create_deployment(name, model_uri, flavor, config=config_dict)
  File "/data/venv/vmray/lib/python3.8/site-packages/mlflow_ray_serve/__init__.py", line 96, in create_deployment
    MLflowDeployment.options(name=name, **config).deploy(model_uri)
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/api.py", line 852, in deploy
    return _get_global_client().deploy(
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/api.py", line 96, in check
    return f(self, *args, **kwargs)
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/api.py", line 268, in deploy
    self._wait_for_goal(goal_id)
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/api.py", line 195, in _wait_for_goal
    async_goal_exception = ray.get(ready)[0]
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ServeController.wait_for_goal() (pid=17178, ip=10.81.1.40)
  File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/utils.py", line 241, in wrap_to_ray_error
    raise exception
RuntimeError: Failed to reach deployment goal. Check the serve logs for details.
(ServeController pid=17178) 2022-04-12 07:50:40,640     ERROR deployment_state.py:284 -- Exception in deployment
 'RajeshOnnxWine'
(ServeController pid=17178) Traceback (most recent call last):
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/deployment_state.py
", line 278, in check_ready
(ServeController pid=17178)     deployment_config, version = ray.get(ready)[0]
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/_private/client_mode_hook
.py", line 105, in wrapper
(ServeController pid=17178)     return func(*args, **kwargs)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/worker.py", line 1763, in
 get
(ServeController pid=17178)     raise value.as_instanceof_cause()
(ServeController pid=17178) ray.exceptions.RayTaskError(PermissionError): ray::RayServeWrappedReplica.reco
nfigure() (pid=13404, ip=10.81.1.40, repr=<ray.serve.replica.RajeshOnnxWine object at 0x7f7d3c1aa8b0>)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 432, in result
(ServeController pid=17178)     return self.__get_result()
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/co
ncurrent/futures/_base.py", line 388, in __get_result
(ServeController pid=17178)     raise self._exception
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 1
43, in reconfigure
(ServeController pid=17178)     await self._initialize_replica()
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/ray/serve/replica.py", line 9
0, in initialize_replica
(ServeController pid=17178)     await sync_to_async(_callable.__init__)(*init_args,
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow_ray_serve/__init__.py"
, line 48, in __init__
(ServeController pid=17178)     self.model = mlflow.pyfunc.load_model(model_uri=model_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", l
ine 691, in load_model
(ServeController pid=17178)     local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=d
st_path)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/artifact_util
s.py", line 95, in _download_artifact_from_uri
(ServeController pid=17178)     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 107, in get_artifact_repository
(ServeController pid=17178)     return _artifact_repository_registry.get_artifact_repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/artifac
t_repository_registry.py", line 73, in get_artifact_repository
(ServeController pid=17178)     return repository(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 35, in __init__
(ServeController pid=17178)     uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/artifact/models_
artifact_repo.py", line 53, in get_underlying_uri
(ServeController pid=17178)     client = MlflowClient(registry_uri=databricks_profile_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/client.py", l
ine 70, in __init__
(ServeController pid=17178)     self._tracking_client = TrackingServiceClient(final_tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 48, in __init__
(ServeController pid=17178)     self.store
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/client.py", line 52, in store
(ServeController pid=17178)     return utils._get_store(self.tracking_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 155, in _get_store
(ServeController pid=17178)     return _tracking_store_registry.get_store(store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 39, in get_store
(ServeController pid=17178)     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/registry.py", line 49, in _get_store_with_resolved_uri
(ServeController pid=17178)     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/tracking/_tracking_ser
vice/utils.py", line 109, in _get_file_store
(ServeController pid=17178)     return FileStore(store_uri, store_uri)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/store/tracking/file_st
ore.py", line 140, in __init__
(ServeController pid=17178)     mkdir(self.root_directory)
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 114, in mkdir
(ServeController pid=17178)     raise e
(ServeController pid=17178)   File "/data/venv/vmray/lib/python3.8/site-packages/mlflow/utils/file_utils.py",
line 111, in mkdir
(ServeController pid=17178)     os.makedirs(target)
(ServeController pid=17178)   File "/nix/store/wjxg0zib7n27fw605h1h1l4jjnqyzfjy-python3-3.8.8/lib/python3.8/os
.py", line 223, in makedirs
(ServeController pid=17178)     mkdir(name, mode)
(ServeController pid=17178) PermissionError: [Errno 13] Permission denied: '/mlruns'
(ServeController pid=17178) 2022-04-12 07:50:40,643     INFO deployment_state.py:1189 -- Deployment 'RajeshOnnxW
```

**Comment by rajesh-chawla** [comment]
Resolved issue.

**Comment by hekuranc** [comment]
> Resolved issue.

How ?
