### ISSUE TITLE
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool

### ISSUE THREAD

**Issue by saichandrapandraju** [mlflow/mlflow#5698]
Hi,

I'm using Minio server as artifact store for logging models. But I'm getting following error while uploading artifacts to Minio - 

```
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/httpsession.py", line 439, in send
    urllib_response = conn.urlopen(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='localhost', port=3128): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 109, in <module>
    mlflow.log_figure(ax.figure, f"{explain_files}/{feature_importance_plot}")
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 761, in log_figure
    MlflowClient().log_figure(run_id, figure, artifact_file)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1162, in log_figure
    raise TypeError("Unsupported figure object type: '{}'".format(type(figure)))
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1020, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 124, in log_artifact
    self._upload_file(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 117, in _upload_file
    s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/boto3/s3/inject.py", line 131, in upload_file
    return transfer.upload_file(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    future.result()
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/client.py", line 731, in _make_api_call
    http, parsed_response = self._make_request(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/client.py", line 751, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/endpoint.py", line 183, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/endpoint.py", line 305, in _needs_retry
    responses = self._event_emitter.emit(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/hooks.py", line 358, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/hooks.py", line 229, in emit
    return self._emit(event_name, kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/hooks.py", line 212, in _emit
    response = handler(**kwargs)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 194, in __call__
    if self._checker(**checker_kwargs):
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 267, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 294, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 333, in __call__
    checker_response = checker(attempt_number, response,
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 233, in __call__
    return self._check_caught_exception(
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/retryhandler.py", line 376, in _check_caught_exception
    raise caught_exception
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/endpoint.py", line 249, in _do_get_response
    http_response = self._send(request)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/endpoint.py", line 321, in _send
    return self.http_session.send(request)
  File "/data/codeapi/miniconda/envs/mlflow-ee9476d22fc77d7d219b7d660f6606ebe40112cb/lib/python3.8/site-packages/botocore/httpsession.py", line 474, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://10.156.89.15:9001/mlflow-artifacts/2644e4fddba64407ba08afd0078348ee/artifacts/model/model.pkl"
```
Could anyone suggest solution for this .. ?

**Comment by dbczumar** [comment]
Hi @saichandrapandraju, it looks like your MLflow server is having trouble using the boto client library to write to S3. I would recommend investigating `AWSHTTPConnectionPool(host='localhost', port=3128): Read timed out. (read timeout=60)` in the context of boto3 and Minio.

**Comment by saichandrapandraju** [comment]
Hi @dbczumar ,

Yes you're correct. 
I tested uploading sample file using boto3 client without MLFlow. It is due to proxy that boto3 is not able to write to Minio. If I set `NO_PROXY` env variable to Minio host name, boto3 is able to write to S3(Minio).

However, it seems I cannot use `NO_PROXY` with MLFlow because I'm using MLFlow's conda features in my workflow and now conda is throwing below error - 
```
ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.
```
Is there any other way to progress further...?

**Comment by WeichenXu123** [comment]
Conda does not allow environment contains "NO_PROXY" key. see https://github.com/conda/conda/issues/1094

@dbczumar What about adding a "MLFLOW_NO_PROXY" environment support for mlflow, i.e, mlflow check whether there's a "MLFLOW_NO_PROXY" env, if there is, then set "NO_PROXY" env when running boto3 client.

**Comment by WeichenXu123** [comment]
@saichandrapandraju Are you interested in contributing code to mlflow to fix this issue ? :) We propose this solution to address it:
adding a "MLFLOW_NO_PROXY" environment support for mlflow, i.e, mlflow check whether there's a "MLFLOW_NO_PROXY" env, if there is, then set "NO_PROXY" env when running boto3 client.

**Comment by saichandrapandraju** [comment]
Hi @WeichenXu123 ,
It seems conda supports NO_PROXY after referring [conda/conda#11022](https://github.com/conda/conda/issues/11022)

My issue got resolved after adding our company's repository url to `NO_PROXY` in addition to Minio server host name. 
It will be something like - 
`export NO_PROXY=<company_name>artifactory.ad.<company_name>.com,<minio_host_name>`
