### ISSUE TITLE
[BUG] Metric Logging: Specifying timestamp ms as a float, blows up after logging, while viewing the ui

### ISSUE THREAD

**Issue by ntakouris** [mlflow/mlflow#5738]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: [pytorch nvidia container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)
- **MLflow installed from (source or binary)**: binary (pip)
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 1.25.1

### Describe the problem

The below code chunk works:

```py
       metric_payload = {'a': 0.1}

        now_time = time.time() # this is a float
        metric_entities_list = [
            Metric(k, v, now_time, step or 0) for k, v in metric_payload.items()
        ]

        self.client.log_batch(run_id, metric_entities_list)
```

But then, if you try to launch the ui and browse the experiments, you get the following stack trace back:

`
ypeError: 1650537874.5486026 has type float, but expected one of: int
2022/04/21 10:45:35 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "/home/lambda/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lambda/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lambda/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lambda/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 327, in wrapper
    return func(*args, **kwargs)
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 385, in wrapper
    return func(*args, **kwargs)
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 650, in _search_runs
    response_message.runs.extend([r.to_proto() for r in run_entities])
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 650, in <listcomp>
    response_message.runs.extend([r.to_proto() for r in run_entities])
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/entities/run.py", line 41, in to_proto
    run.data.MergeFrom(self.data.to_proto())
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/entities/run_data.py", line 62, in to_proto
    run_data.metrics.extend([m.to_proto() for m in self._metric_objs])
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/entities/run_data.py", line 62, in <listcomp>
    run_data.metrics.extend([m.to_proto() for m in self._metric_objs])
  File "/home/lambda/.local/lib/python3.8/site-packages/mlflow/entities/metric.py", line 40, in to_proto
    metric.timestamp = self.timestamp
TypeError: 1650537874.5486026 has type float, but expected one of: int
`
This is particularly annoying, because it seems that it also renders the schema of the database unusable. Perhaps you can add a check before inserting float data, or just cast to int at the backend query side.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ x ] `area/server-infra`: MLflow Tracking server backend
- [  x ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [  X ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ X ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by WeichenXu123** [comment]
@ntakouris 

I created a draft PR, https://github.com/mlflow/mlflow/pull/5750 ,
you can take over it :)

thank you!

**Comment by dbczumar** [comment]
@WeichenXu123 @harupy @ntakouris Are there any recent updates here?

**Comment by WeichenXu123** [comment]
@ntakouris Do you have PR created ? If you are busy I can take over this .

**Comment by ntakouris** [comment]
@WeichenXu123 Please feel free to take over.
