### ISSUE TITLE
[BUG] mlflow.pyfunc.get_model_dependencies raises exception when using `model:/<model_name>/<version>`

### ISSUE THREAD

**Issue by lineback** [mlflow/mlflow#5850]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  docker container from  continuumio/miniconda3:4.11.0
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**:  mlflow, version 1.25.1
- **Python version**:  Python 3.9.12
- **npm version, if running the dev UI**:

### Describe the problem

`mlflow.pyfunc.get_model_dependencies` raises an exception when using a model uri like `models:/<model_name>/<version>`.   If I use the original run like `run:/<run-id>/path/to/model` it works as expected.

### Code to reproduce issue

```python
import mlflow
logged_model = 'models:/MyModel/1'
deps = mlflow.pyfunc.get_model_dependencies(logged_model, format="conda")
```

### Other info / logs

```
Traceback (most recent call last):
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/utils/model_utils.py", line 57, in _get_flavor_configuration_from_uri
    ml_model_file = _download_artifact_from_uri(
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/tracking/artifact_utils.py", line 95, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 107, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 73, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 35, in __init__
    uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 54, in get_underlying_uri
    (name, version) = get_model_name_and_version(client, uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/utils/models.py", line 71, in get_model_name_and_version
    (model_name, model_version, model_stage) = _parse_model_uri(models_uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/store/artifact/utils/models.py", line 57, in _parse_model_uri
    raise MlflowException(_improper_model_uri_msg(uri))
mlflow.exceptions.MlflowException: Not a proper models:/ URI: models:/MyModel/1/MLmodel. Models URIs must be of the form 'models:/<model_name>/suffix' where suffix is a model version, stage, or the string 'latest'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/outrider-mlflow/examples/model_inference/get_model_env.py", line 25, in <module>
    deps = mlflow.pyfunc.get_model_dependencies(logged_model, format="conda")
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 808, in get_model_dependencies
    dep_file = _get_model_dependencies(model_uri, format)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 786, in _get_model_dependencies
    conda_yml_path = _download_model_conda_env(model_uri)
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 738, in _download_model_conda_env
    conda_yml_file_name = _get_flavor_configuration_from_uri(model_uri, FLAVOR_NAME)[ENV]
  File "/home/dev/.conda/envs/mlflow-model-inference/lib/python3.9/site-packages/mlflow/utils/model_utils.py", line 61, in _get_flavor_configuration_from_uri
    raise MlflowException(
mlflow.exceptions.MlflowException: Failed to download an "MLmodel" model file from "models:/MyModel/1": Not a proper models:/ URI: models:/MyModel/1/MLmodel. Models URIs must be of the form 'models:/<model_name>/suffix' where suffix is a model version, stage, or the string 'latest'.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by lineback** [comment]
When trying to fetch the model configuration file in [_get_flavor_configuration_from_uri](https://github.com/mlflow/mlflow/blob/c1722fd13aa0428b64ff0575c24a43efef0c9bdc/mlflow/utils/model_utils.py#L45) `MLmodel` is appended to the model uri.  Because of [this check](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/artifact_utils.py#L87) in `_ _download_artifact_from_uri` the model uri plush artifact path are passed through to `_parse_model_uri` causing the error.

**Comment by harupy** [comment]
@lineback I was able to reproduce the issue. Looks like we need to resolve `models:/MyModel/1` first, and then append `MLmodel`.

**Comment by harupy** [comment]
@lineback Would you be interested in fixing this issue?

**Comment by harupy** [comment]
cc @WeichenXu123

**Comment by lineback** [comment]
@harupy yes, I can work on it.

**Comment by harupy** [comment]
@lineback Looking forward to your PR!
