### ISSUE TITLE
[BUG] tracking metrics in multiple threadings style.

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#5979]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.7
- **Python version**:  3.8
- **yarn version, if running the dev UI**:

### Describe the problem

I want to monitor GPU and CPU usage using mlflow. I used a seperate thread to monitor GPU and CPU information. 
However, it seems that mlflow does not support multi-thread log_metrics? 

### Code to reproduce issue

My code is as follows.

```
def record_cgpu_info(outfile) -> Tuple:
    """Record CPU and GPU information to `outfile`.

    Args:
        outfile: The format of `outfile` is: slurm-[JOB_ID].out

    Returns:
        gpu_name, gpu_usage, gpu_util

    Examples:

        >>> record_gpu_info('slurm-98234.out')

    """
    t = threading.currentThread()
    t.do_run = True

    if outfile:
        cpu_count = psutil.cpu_count()
        log_param('cpu_count', cpu_count)

        pid = os.getpid()
        python_process = psutil.Process(pid)

        jobid_gpuid = outfile.split('-')[-1]
        tmp_split = jobid_gpuid.split('_')[-1]
        if len(tmp_split) == 2:
            gpuid = tmp_split[-1]
        else:
            gpuid = 0
        nvidia_smi.nvmlInit()
        handle = nvidia_smi.nvmlDeviceGetHandleByIndex(gpuid)
        gpuname = nvidia_smi.nvmlDeviceGetName(handle)
        gpuname = gpuname.decode("utf-8")
        log_param('gpuname', gpuname)
        # log_dict['gpuname'] = gpuname

        # log_dict['gpu_mem_usage'] = gpu_mem_usage
        # gpu_util = 0
        i = 0
        period = 2  # 2 seconds
        while i<60*20:  # stop signal passed from t, monitor 20 minutes
            if t.do_run:
                memoryUse = python_process.memory_info().rss / 2. ** 30  # memory use in GB...I think
                log_metric('cpu_mem_used_GB_in_process_rss', memoryUse, step=i)
                memoryUse = python_process.memory_info().vms / 2. ** 30  # memory use in GB...I think
                log_metric('cpu_mem_used_GB_in_process_vms', memoryUse, step=i)
                cpu_percent = psutil.cpu_percent()
                log_metric('cpu_util_used_percent', cpu_percent, step=i)
                cpu_mem_used = psutil.virtual_memory().percent
                log_metric('cpu_mem_used_percent', cpu_mem_used, step=i)

                res = nvidia_smi.nvmlDeviceGetUtilizationRates(handle)
                log_metric("gpu_util", res.gpu, step=i)

                info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
                gpu_mem_used = _bytes_to_megabytes(info.used)
                log_metric('gpu_mem_used_MB', gpu_mem_used, step=i)

                time.sleep(period)
                i += period
            else:
                print('record_cgpu_info do_run is True, let stop the process')
                break
        print('It is time to stop this process: record_cgpu_info')
        return None

    else:
        print('outfile is None, can not show GPU memory info')
        return None, None, None

def run():
    ......

mlflow.set_experiment("ex1")
outfile = 'slurm-32123.out'
with mlflow.start_run(run_name='run1'):
    p1 = threading.Thread(target=record_cgpu_info, args=(outfile,))
    p1.start()
    run()  
```

### Other info / logs

The code works well most times. But sometimes the error occured: 
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/jjia/.conda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jjia/.conda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/jjia/ssc_scoring/ssc_scoring/../ssc_scoring/mymodules/tool.py", line 603, in record_cgpu_info
    log_metric('cpu_mem_used_GB_in_process_vms', memoryUse, step=i)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 583, in log_metric
    MlflowClient().log_metric(run_id, key, value, int(time.time() * 1000), step or 0)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/tracking/client.py", line 690, in log_metric
    self._tracking_client.log_metric(run_id, key, value, timestamp, step)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 226, in log_metric
    self.store.log_metric(run_id, metric)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 191, in log_metric
    self._call_endpoint(LogMetric, req_body)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/jjia/.conda/envs/py38/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 185, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (sqlite3.OperationalError) database is locked
[SQL: SELECT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id 
FROM runs 
WHERE runs.run_uuid = ?]
[parameters: ('7a4be02f5f0b4eecb6b07d47f075646b',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Jingnan-Jia https://github.com/mlflow/mlflow/issues/3592#issuecomment-717807135 might be helpful.
