### ISSUE TITLE
[BUG]spark serve model fails with custom function added to the pyspark MLpipeline 

### ISSUE THREAD

**Issue by Hiteshsaai** [mlflow/mlflow#6008]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.25.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS
- **Python version**: 3.8.12
- **yarn version, if running the dev UI**: NA

### Describe the problem

I created a custom Transformer and added that to the MLlib pipeline in pypark and saved the model using 
```mlflow.spark.save_model()``` , I am able to load the model using ```mlflow.spark.load_model()``` and test a sample input successfully in the pipeline but when i try to run it on mlfow server i am getting 

```AttributeError: module '__main__' has no attribute 'SetValueTransformer'```

### Code to reproduce issue

```
from pyspark.sql import SparkSession
from pyspark.sql import DataFrame
from pyspark.ml import Pipeline, Transformer
from pyspark.ml.feature import Imputer
from pyspark.ml.feature import StringIndexer
from pyspark.ml.feature import OneHotEncoder
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.classification import RandomForestClassifier
import mlflow 
from pyspark import keyword_only
from pyspark.ml import Transformer
from pyspark.ml.param.shared import HasOutputCols, Param, Params, TypeConverters
from pyspark.ml.util import DefaultParamsReadable, DefaultParamsWritable
from pyspark.sql.functions import lit # for the dummy _transform


spark = SparkSession.builder.appName('ml').config("spark.driver.bindAddress", "127.0.0.1").getOrCreate()


df  = spark.read.csv("drug200.csv", header=True, inferSchema=True)


# CUSTOM TRANSFORMER WITH SAVING --------------
class SetValueTransformer(
    Transformer, HasOutputCols, DefaultParamsReadable, DefaultParamsWritable,
):
    colName = Param(
        Params._dummy(),
        "colName",
        "value which we need to replace the null with",
        typeConverter=TypeConverters.toString
    )

    Na_thresh = Param(
        Params._dummy(),
        "Na_thresh",
        "used to filter the rows",
        typeConverter=TypeConverters.toFloat,
    )

    # custom_params =  Param(
    #     Params._dummy(),
    #     "Na_thresh",
    #     "used to filter the rows",
    #     typeConverter=TypeConverters.toDict
    # )

    @keyword_only
    def __init__(self, colName=None, Na_thresh=0.0):
        super(SetValueTransformer, self).__init__()
        self._setDefault(colName=None)
        self._setDefault(Na_thresh=0.0)
        kwargs = self._input_kwargs
        self._set(**kwargs)
        # custom_stage0 = Custom_transformation(inputCols = ['Na_to_k'], outputCols = '', custom_params = {'na_thresh': 9})


    @keyword_only
    def setParams(self, colName=None, Na_thresh=0.0):
        """
        setParams(self, outputCols=None, value=0.0)
        Sets params for this SetValueTransformer.
        """
        kwargs = self._input_kwargs
        return self._set(**kwargs)

    def setThresh(self, thresh):
        """
        Sets the value of :py:attr:`value`.
        """
        return self._set(Na_thresh=thresh)

    def getThresh(self):
        """
        Gets the value of :py:attr:`value` or its default value.
        """
        return self.getOrDefault(self.Na_thresh)

    def setColName(self, col):
        return self._set(colName=col)
    
    
    def getColName(self):
        return self.getOrDefault(self.colName)

    def _transform(self, df):

        df = df.na.drop(subset=["Sex","BP", "Cholesterol", 'Drug'])
        df = df.filter(df[self.getColName()] > self.getThresh())
        # df = df.drop(*[x for x in df.columns if any(y in x for y in self.banned_list)])
        return df



## Initiating the custom preprocess 
# stage0 = CustomDataPreprocess("Na_to_K", 9)


stage1 = SetValueTransformer(colName = "Na_to_k", Na_thresh = 8)
stage2 = Imputer(inputCols= ['Na_to_K'], outputCols = [ "impute_{}".format(c) for c in ['Na_to_K']]).setStrategy('mean')
stage3 = StringIndexer(inputCol = "Sex", outputCol = 'sexIndex') 
stage4 = StringIndexer(inputCol="Cholesterol", outputCol='cholesterolIndex') 
stage5 = StringIndexer(inputCol="Drug", outputCol='drugIndex') 
stage6 = StringIndexer(inputCol="BP", outputCol='bpIndex') 
stage7 = OneHotEncoder(inputCol= 'bpIndex', outputCol='bpOHE')
stage8 = VectorAssembler(inputCols=["Age", "sexIndex","bpOHE","cholesterolIndex","impute_Na_to_K"], outputCol= 'features')
stage9  = RandomForestClassifier(featuresCol='features', labelCol='drugIndex',  numTrees= 100)

# custom_stage0 = Custom_transformation(inputCols = ['Na_to_k'], outputCols = '', custom_params = {'na_thresh': 9})



## Adding the custom preprocess with other steps
pipeline = Pipeline(stages=[stage1, stage2, stage3, stage4, stage5, stage6, stage7, stage8, stage9])

## Split the data 
train_df, test_df = df.randomSplit([0.75,0.25])


## Fitting Training data
model = pipeline.fit(train_df)

# ## Getting prediction from hold out test data
# predictions = model.transform(test_df)
# predictResult = predictions.select("prediction")
# predictResult.show()


mlflow.spark.save_model(model, 'model_with_custom_preprocess')
```

### Other info / logs

```/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py:2322: FutureWarning: `--no-conda` is deprecated and will be removed in a future MLflow release. Use `--env-manager=local` instead.
  value = self.callback(ctx, self, value)
2022/05/31 17:08:45 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/05/31 17:08:45 INFO mlflow.pyfunc.backend: === Running command 'gunicorn --timeout=60 -b 0.0.0.0:15 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
[2022-05-31 17:08:45 -0700] [30992] [INFO] Starting gunicorn 20.1.0
[2022-05-31 17:08:45 -0700] [30992] [INFO] Listening at: http://0.0.0.0:15 (30992)
[2022-05-31 17:08:45 -0700] [30992] [INFO] Using worker: sync
[2022-05-31 17:08:45 -0700] [30994] [INFO] Booting worker with pid: 30994
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/05/31 17:08:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022/05/31 17:08:49 INFO mlflow.spark: File '/Users/i29140/Documents/MLE/spark/TESTING_spark_mlflow_preprocess_/sparkml' is already on DFS, copy is not necessary.
[2022-05-31 17:08:51 -0700] [30994] [ERROR] Exception in worker process         
Traceback (most recent call last):
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/pyfunc/scoring_server/wsgi.py", line 6, in <module>
    app = scoring_server.init(load_model(os.environ[scoring_server._SERVER_MODEL_PATH]))
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 733, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/spark.py", line 737, in _load_pyfunc
    return _PyFuncModelWrapper(spark, _load_model(model_uri=path))
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/spark.py", line 656, in _load_model
    return PipelineModel.load(model_uri)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/pyspark/ml/util.py", line 332, in load
    return cls.read().load(path)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/pyspark/ml/pipeline.py", line 260, in load
    uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/pyspark/ml/pipeline.py", line 396, in load
    stage = DefaultParamsReader.loadParamsInstance(stagePath, sc)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/pyspark/ml/util.py", line 590, in loadParamsInstance
    py_type = DefaultParamsReader.__get_class(pythonClassName)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/pyspark/ml/util.py", line 501, in __get_class
    m = getattr(m, comp)
**AttributeError: module '__main__' has no attribute 'SetValueTransformer'**
[2022-05-31 17:08:51 -0700] [30994] [INFO] Worker exiting (pid: 30994)
[2022-05-31 17:08:51 -0700] [30992] [INFO] Shutting down: Master
[2022-05-31 17:08:51 -0700] [30992] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/Users/i29140/opt/anaconda3/envs/spark/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/models/cli.py", line 65, in serve
    return _get_flavor_backend(
  File "/Users/i29140/opt/anaconda3/envs/spark/lib/python3.8/site-packages/mlflow/pyfunc/backend.py", line 197, in serve
    raise Exception(
Exception: Command '['bash', '-c', 'exec gunicorn --timeout=60 -b 0.0.0.0:15 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app']' returned non zero return code. Return code = 3
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Hiteshsaai Have you tried using the `code_paths` argument?

https://github.com/mlflow/mlflow/blob/aa2d955e10d0c19ed80dab1b7ccef7517ba15634/mlflow/spark.py#L496

**Comment by Hiteshsaai** [comment]
> @Hiteshsaai Have you already tried using the `code_paths` argument?
> 
> https://github.com/mlflow/mlflow/blob/aa2d955e10d0c19ed80dab1b7ccef7517ba15634/mlflow/spark.py#L496
> 
> This argument allows you to log a model with custom modules.

No i have not tried using that @harupy . Can you help with how to use that ?

**Comment by harupy** [comment]
Here's example code:

```python
# custom_transformer.py

class SetValueTransformer:
    ...
```

```python
# main.py


...
mlflow.spark.save_model(model, 'model_with_custom_preprocess', code_paths=["/path/to/custom_transformer.py"])
```

**Comment by timo-engnz** [comment]
I am able to save my model to MLFLOW

PYSPARK 3.2.1
MLFLOW 2.2.1

`with mlflow.start_run(experiment_id=EXPERIMENT_ID) as run:
        print("MLflow:")
        print("  run_id:",run.info.run_id)
        print("  experiment_id:",run.info.experiment_id)
        mlflow.log_param('overridePerc',0.15)
        mlflow.set_tag("version.mlflow", mlflow.__version__)
        mlflow.log_param('overridePerc',0.15)
        mlflow.spark.log_model(model, "model", signature=_signature,code_paths=["./CustomTransformer.py","./lib"], pip_requirements=["-c requirements.txt"])`

MLFLOW shows the model is okay

![image](https://user-images.githubusercontent.com/40694702/213715843-453598ae-ceb0-404c-80aa-d6de917b2b27.png)

But When I load the model, and try predict, I get the below error:


![image](https://user-images.githubusercontent.com/40694702/213716489-7bfcc99f-aae3-41e0-82b0-d4bd80ad62dc.png)

Exception:
`PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 603, in main
    func, profiler, deserializer, serializer = read_udfs(pickleSer, infile, eval_type)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 449, in read_udfs
    udfs.append(read_single_udf(pickleSer, infile, eval_type, runner_conf, udf_index=i))
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 251, in read_single_udf
    f, return_type = read_command(pickleSer, infile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 73, in read_command
    command = serializer.loads(command.value)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 430, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'CustomTransformer'`
