### ISSUE TITLE
[BUG] `AttributeError` on import with protobuf 3.18.1

### ISSUE THREAD

**Issue by charlesbluca** [mlflow/mlflow#6072]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.9
- **yarn version, if running the dev UI**: n/a

### Describe the problem

With MLflow 1.26.1, I am getting an `AttributeError` at import when using older versions of protobuf (in my case, 3.18.1) that are still permitted by the conda recipe's `protobuf >=3.7.0` constraint.

This seems to be a relatively new issue that does not impact MLflow 1.26.0; this also only seems to be impacting Windows, as the same environment on Linux machines does not result in failures.

### Code to reproduce issue

Create a conda environment on Windows with latest MLflow and an older version of protobuf:

```
$ conda create -n mlflow-repro python=3.9 mlflow=1.26.1 protobuf=3.18.1
$ conda activate mlflow-repro
```

Attempt to run `mlflow`:

```
$ mlflow
```

### Other info / logs

```python-traceback
Traceback (most recent call last):
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\Scripts\mlflow-script.py", line 6, in <module>
    from mlflow.cli import cli
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\__init__.py", line 32, in <module>
    import mlflow.tracking._model_registry.fluent
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\tracking\__init__.py", line 8, in <module>
    from mlflow.tracking.client import MlflowClient
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\tracking\client.py", line 16, in <module>
    from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\__init__.py", line 6, in <module>
    from mlflow.entities.experiment import Experiment
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\experiment.py", line 2, in <module>
    from mlflow.entities.experiment_tag import ExperimentTag
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\experiment_tag.py", line 2, in <module>
    from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\protos\service_pb2.py", line 18, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\protos\scalapb\scalapb_pb2.py", line 22, in <module>
    options = DESCRIPTOR.extensions_by_name['options']
AttributeError: 'NoneType' object has no attribute 'extensions_by_name'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@charlesbluca Are you certain that invoking `mlflow` within your shell is resolving to the expected binary? I.e. does `which mlflow` produce the expected result? What happens if you run `python -c "import protobuf; print(protobuf.__version__); import mlflow"`?

**Comment by charlesbluca** [comment]
> Are you certain that invoking mlflow within your shell is resolving to the expected binary?

Looks like we're resolving to:

```powershell
(mlflow-test) PS C:\Users\geniu> Get-Command mlflow

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     mlflow.exe                                         0.0.0.0    C:\Users\geniu\mambaforge\envs\mlflow-test\Scripts\mlflow.exe
```

Is that expected?

> What happens if you run python -c "import google.protobuf; print(google.protobuf.__version__); import mlflow"

I get the same `AttributeError` as above:

```powershell
(mlflow-test) PS C:\Users\geniu> python -c "import google.protobuf; print(google.protobuf.__version__); import mlflow"
3.18.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\__init__.py", line 32, in <module>
    import mlflow.tracking._model_registry.fluent
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\tracking\__init__.py", line 8, in <module>
    from mlflow.tracking.client import MlflowClient
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\tracking\client.py", line 16, in <module>
    from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\__init__.py", line 6, in <module>
    from mlflow.entities.experiment import Experiment
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\experiment.py", line 2, in <module>
    from mlflow.entities.experiment_tag import ExperimentTag
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\entities\experiment_tag.py", line 2, in <module>
    from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\protos\service_pb2.py", line 18, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "C:\Users\geniu\mambaforge\envs\mlflow-test\lib\site-packages\mlflow\protos\scalapb\scalapb_pb2.py", line 22, in <module>
    options = DESCRIPTOR.extensions_by_name['options']
AttributeError: 'NoneType' object has no attribute 'extensions_by_name'
```

**Comment by dbczumar** [comment]
@charlesbluca Thanks for confirming! Out of curiosity, what happens if you install `protobuf==3.18.1` from PyPI rather that Anaconda?

**Comment by starovoitovs** [comment]
Installing `protobuf==3.20.1` solved the issue.
