### ISSUE TITLE
[BUG] Nested `MlflowException` when calling `mlflow.set_experiment()` on a RestStore endpoint that requires authentication

### ISSUE THREAD

**Issue by balvisio** [mlflow/mlflow#6105]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 8
- **Python version**: Python 3.9.12
- **yarn version, if running the dev UI**:

### Describe the problem

**Note**: This might be not considered a bug but more of an improvement or optimization.

When setting a RestStore that requires authentication but the credentials are NOT set:
```python
mlflow.set_tracking_uri(mlflow_params.tracking_uri) # This endpoint requires auth
try:
    mlflow.set_experiment(mlflow_params.experiment)
except MlflowException as e:
    log.exception(msg="An error occurred while setting MLflow experiment")
```

The following nested exceptions occur:
```python-traceback
ERROR:root:An error occurred while setting MLflow experiment
Traceback (most recent call last):
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 285, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 191, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 401 != 200. Response body: '<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno/repos/my-repo/model/training.py", line 297, in train_model
    mlflow.set_experiment(mlflow_params.experiment)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 110, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/client.py", line 462, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 162, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 297, in get_experiment_by_name
    for experiment in self.list_experiments(ViewType.ALL):
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 77, in list_experiments
    response_proto = self._call_endpoint(ListExperiments, req_body)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 191, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/list failed with error code 401 != 200. Response body: '<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
'
```

As it can be seen the in the output above, an exception occurs as the first exception is being handled. The reason is that in `get_experiment_by_name()` in `mlflow/store/tracking/rest_store.py` [https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/rest_store.py#L102](url) when the first exception is handled the code call `list_experiments()` that makes a second call to the API endpoint again raising the same exception a second time.

IMHO, if the HTTP status returned by the call is not transient, the exception should be raised instead of trying to call `list_experiments()`.

### Code to reproduce issue

```python
mlflow.set_tracking_uri(mlflow_params.tracking_uri)
try:
    mlflow.set_experiment(mlflow_params.experiment)
except MlflowException as e:
    log.exception(msg="An error occurred while setting MLflow experiment")
```

### Other info / logs

```python-traceback
ERROR:root:An error occurred while setting MLflow experiment
Traceback (most recent call last):
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 285, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 191, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 401 != 200. Response body: '<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno/repos/my-repo/model/training.py", line 297, in train_model
    mlflow.set_experiment(mlflow_params.experiment)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 110, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/client.py", line 462, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 162, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 297, in get_experiment_by_name
    for experiment in self.list_experiments(ViewType.ALL):
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 77, in list_experiments
    response_proto = self._call_endpoint(ListExperiments, req_body)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/bruno/anaconda3/envs/mlflow-env/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 191, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/list failed with error code 401 != 200. Response body: '<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by balvisio** [comment]
Created PR: https://github.com/mlflow/mlflow/pull/6106

**Comment by dbczumar** [comment]
Addressed via https://github.com/mlflow/mlflow/pull/6106. Thanks @balvisio !
