### ISSUE TITLE
[BUG] `mlflow gc` fails in deleting runs from postgres backend store due to foreign key constraints

### ISSUE THREAD

**Issue by Jason-CKY** [mlflow/mlflow#6127]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker
- **Python version**: 3.9.5
- **yarn version, if running the dev UI**:

### Describe the problem

The code to delete runs tries to delete the record from `runs` table directly, which fails due to the foreign-key constraints in related tables like `metrics`, `latest_metrics`, and 'tags'.

https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/sqlalchemy_store.py#L585-L592

Either make the database schema ON DELETE CASCADE, or run the following adapted from https://stackoverflow.com/questions/60088889/how-do-you-permanently-delete-an-experiment-in-mlflow

```
DELETE FROM latest_metrics WHERE run_uuid=<id>;
DELETE FROM metrics WHERE run_uuid=<id>;
DELETE FROM tags WHERE run_uuid=<id>;
DELETE FROM runs WHERE run_uuid=<id>;
```

### Code to reproduce issue

Run the docker-compose file at https://github.com/Jason-CKY/MLOps-workflows/blob/main/docker-compose-mlflow.yml,
exec into the mlflow container and run `mlflow gc`

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by Jason-CKY** [comment]
To give some more context, I got the following warning:
`/opt/conda/lib/python3.9/site-packages/mlflow/store/db/utils.py:80: SAWarning: DELETE statement on table 'metrics' expected to delete 1 row(s); 0 were matched. Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning`.

The mis-match caused the metrics to not be deleted, which caused the run to error out due to ForeignKeyViolation.
```
psycopg2.errors.ForeignKeyViolation: update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics" 
```

**Comment by dbczumar** [comment]
@Jason-CKY Apologies for the delay, and thank you for raising this issue. MLflow currently defines cascading deletes on metadata associated with runs (i.e. metrics, params, tags, latest metrics; for example: https://github.com/mlflow/mlflow/blob/9a25f04787b7703c382fa7c3cd25b78ce0eed380/mlflow/store/tracking/dbmodels/models.py#L320). As you noted, I suspect that the issue has something to do with

```
/opt/conda/lib/python3.9/site-packages/mlflow/store/db/utils.py:80: SAWarning: DELETE statement on table 'metrics' expected to delete 1 row(s); 0 were matched. Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
```

Can you provide more information about when this issue surfaced - i.e. did it occur immediately after running `mlflow gc`? Did you run any commands before `mlflow gc` that might be relevant? If possible, a small reproducible example would also be very helpful.

Thank you for using MLflow!

**Comment by Jason-CKY** [comment]
Was able to narrow down the problem. The issue is with an outdated postgresql database (version 11). I think the SELECT command truncates the number of decimals that is returned beyond a certain number of decimal places, thus causing a mismatch if you were to log a metric with too many decimal places. It can be fixed by upgrading the postgresql database to a later version (e.g. v13)

To reproduce:
```
git clone https://github.com/Jason-CKY/mlflow-quickstart.git
cd mlflow-quickstart
docker-compose up -d
docker exec mlflow bash -c "MLFLOW_TRACKING_URI=http://localhost:5000 mlflow gc --backend-store-uri postgresql://user:password@postgres:5432/db 
```

```
2022-06-30 05:44:44,247 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-06-30 05:44:44,247 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-06-30 05:44:44,249 INFO sqlalchemy.engine.Engine select current_schema()
2022-06-30 05:44:44,249 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-06-30 05:44:44,249 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-06-30 05:44:44,250 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-06-30 05:44:44,252 INFO sqlalchemy.engine.Engine SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')
2022-06-30 05:44:44,252 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {'schema': 'public'}
2022-06-30 05:44:44,268 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-06-30 05:44:44,268 INFO sqlalchemy.engine.Engine [generated in 0.00022s] {'name': 'alembic_version'}
2022-06-30 05:44:44,270 INFO sqlalchemy.engine.Engine SELECT alembic_version.version_num 
FROM alembic_version
2022-06-30 05:44:44,270 INFO sqlalchemy.engine.Engine [generated in 0.00013s] {}
2022-06-30 05:44:44,282 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-30 05:44:44,284 INFO sqlalchemy.engine.Engine SELECT experiments.experiment_id AS experiments_experiment_id, experiments.name AS experiments_name, experiments.artifact_location AS experiments_artifact_location, experiments.lifecycle_stage AS experiments_lifecycle_stage 
FROM experiments 
WHERE experiments.lifecycle_stage IN (%(lifecycle_stage_1_1)s, %(lifecycle_stage_1_2)s)
2022-06-30 05:44:44,284 INFO sqlalchemy.engine.Engine [generated in 0.00031s] {'lifecycle_stage_1_1': 'active', 'lifecycle_stage_1_2': 'deleted'}
2022-06-30 05:44:44,288 INFO sqlalchemy.engine.Engine SELECT experiment_tags.key AS experiment_tags_key, experiment_tags.value AS experiment_tags_value, experiment_tags.experiment_id AS experiment_tags_experiment_id, anon_1.experiments_experiment_id AS anon_1_experiments_experiment_id 
FROM (SELECT experiments.experiment_id AS experiments_experiment_id 
FROM experiments 
WHERE experiments.lifecycle_stage IN (%(lifecycle_stage_1_1)s, %(lifecycle_stage_1_2)s)) AS anon_1 JOIN experiment_tags ON anon_1.experiments_experiment_id = experiment_tags.experiment_id
2022-06-30 05:44:44,288 INFO sqlalchemy.engine.Engine [generated in 0.00036s] {'lifecycle_stage_1_1': 'active', 'lifecycle_stage_1_2': 'deleted'}
2022-06-30 05:44:44,290 INFO sqlalchemy.engine.Engine COMMIT
2022-06-30 05:44:44,292 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-30 05:44:44,293 INFO sqlalchemy.engine.Engine SELECT runs.run_uuid AS runs_run_uuid 
FROM runs 
WHERE runs.lifecycle_stage = %(lifecycle_stage_1)s
2022-06-30 05:44:44,293 INFO sqlalchemy.engine.Engine [generated in 0.00013s] {'lifecycle_stage_1': 'deleted'}
2022-06-30 05:44:44,294 INFO sqlalchemy.engine.Engine COMMIT
2022-06-30 05:44:44,296 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-30 05:44:44,300 INFO sqlalchemy.engine.Engine SELECT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id 
FROM runs 
WHERE runs.run_uuid = %(run_uuid_1)s
2022-06-30 05:44:44,300 INFO sqlalchemy.engine.Engine [generated in 0.00039s] {'run_uuid_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,305 INFO sqlalchemy.engine.Engine SELECT params.run_uuid AS params_run_uuid, params.key AS params_key, params.value AS params_value 
FROM params 
WHERE params.run_uuid IN (%(primary_keys_1)s)
2022-06-30 05:44:44,305 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {'primary_keys_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,309 INFO sqlalchemy.engine.Engine SELECT tags.run_uuid AS tags_run_uuid, tags.key AS tags_key, tags.value AS tags_value 
FROM tags 
WHERE tags.run_uuid IN (%(primary_keys_1)s)
2022-06-30 05:44:44,309 INFO sqlalchemy.engine.Engine [generated in 0.00030s] {'primary_keys_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,313 INFO sqlalchemy.engine.Engine SELECT latest_metrics.run_uuid AS latest_metrics_run_uuid, latest_metrics.key AS latest_metrics_key, latest_metrics.value AS latest_metrics_value, latest_metrics.timestamp AS latest_metrics_timestamp, latest_metrics.step AS latest_metrics_step, latest_metrics.is_nan AS latest_metrics_is_nan 
FROM latest_metrics 
WHERE latest_metrics.run_uuid IN (%(primary_keys_1)s)
2022-06-30 05:44:44,313 INFO sqlalchemy.engine.Engine [generated in 0.00024s] {'primary_keys_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,357 INFO sqlalchemy.engine.Engine COMMIT
2022-06-30 05:44:44,359 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-30 05:44:44,359 INFO sqlalchemy.engine.Engine SELECT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id 
FROM runs 
WHERE runs.run_uuid = %(run_uuid_1)s
2022-06-30 05:44:44,360 INFO sqlalchemy.engine.Engine [generated in 0.00013s] {'run_uuid_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,362 INFO sqlalchemy.engine.Engine SELECT tags.key AS tags_key, tags.value AS tags_value, tags.run_uuid AS tags_run_uuid 
FROM tags 
WHERE %(param_1)s = tags.run_uuid
2022-06-30 05:44:44,362 INFO sqlalchemy.engine.Engine [generated in 0.00017s] {'param_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,364 INFO sqlalchemy.engine.Engine SELECT metrics.key AS metrics_key, metrics.value AS metrics_value, metrics.timestamp AS metrics_timestamp, metrics.step AS metrics_step, metrics.is_nan AS metrics_is_nan, metrics.run_uuid AS metrics_run_uuid 
FROM metrics 
WHERE %(param_1)s = metrics.run_uuid
2022-06-30 05:44:44,364 INFO sqlalchemy.engine.Engine [generated in 0.00012s] {'param_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,365 INFO sqlalchemy.engine.Engine SELECT latest_metrics.key AS latest_metrics_key, latest_metrics.value AS latest_metrics_value, latest_metrics.timestamp AS latest_metrics_timestamp, latest_metrics.step AS latest_metrics_step, latest_metrics.is_nan AS latest_metrics_is_nan, latest_metrics.run_uuid AS latest_metrics_run_uuid 
FROM latest_metrics 
WHERE %(param_1)s = latest_metrics.run_uuid
2022-06-30 05:44:44,365 INFO sqlalchemy.engine.Engine [generated in 0.00011s] {'param_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,366 INFO sqlalchemy.engine.Engine SELECT params.key AS params_key, params.value AS params_value, params.run_uuid AS params_run_uuid 
FROM params 
WHERE %(param_1)s = params.run_uuid
2022-06-30 05:44:44,367 INFO sqlalchemy.engine.Engine [generated in 0.00013s] {'param_1': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,369 INFO sqlalchemy.engine.Engine DELETE FROM latest_metrics WHERE latest_metrics.key = %(key)s AND latest_metrics.run_uuid = %(run_uuid)s
2022-06-30 05:44:44,369 INFO sqlalchemy.engine.Engine [generated in 0.00012s] {'key': 'delete-me', 'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,371 INFO sqlalchemy.engine.Engine DELETE FROM metrics WHERE metrics.key = %(key)s AND metrics.timestamp = %(timestamp)s AND metrics.step = %(step)s AND metrics.run_uuid = %(run_uuid)s AND metrics.value = %(value)s AND metrics.is_nan = %(is_nan)s
2022-06-30 05:44:44,371 INFO sqlalchemy.engine.Engine [generated in 0.00017s] {'key': 'delete-me', 'timestamp': 1656567448236, 'step': 0, 'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb', 'value': 0.415616846531435, 'is_nan': False}
/usr/local/lib/python3.9/site-packages/mlflow/store/db/utils.py:80: SAWarning: DELETE statement on table 'metrics' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
  session.commit()
2022-06-30 05:44:44,373 INFO sqlalchemy.engine.Engine DELETE FROM tags WHERE tags.key = %(key)s AND tags.run_uuid = %(run_uuid)s
2022-06-30 05:44:44,373 INFO sqlalchemy.engine.Engine [generated in 0.00018s] ({'key': 'mlflow.source.name', 'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}, {'key': 'mlflow.source.type', 'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}, {'key': 'mlflow.user', 'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'})
2022-06-30 05:44:44,374 INFO sqlalchemy.engine.Engine DELETE FROM runs WHERE runs.run_uuid = %(run_uuid)s
2022-06-30 05:44:44,374 INFO sqlalchemy.engine.Engine [generated in 0.00015s] {'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}
2022-06-30 05:44:44,376 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(0b3534e4a7e4475cb5c06cc5427911bb) is still referenced from table "metrics".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 80, in make_managed_session
    session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 667, in execute
    util.preloaded.orm_persistence.delete_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 343, in delete_obj
    _emit_delete_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1468, in _emit_delete_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(0b3534e4a7e4475cb5c06cc5427911bb) is still referenced from table "metrics".

[SQL: DELETE FROM runs WHERE runs.run_uuid = %(run_uuid)s]
[parameters: {'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mlflow/cli.py", line 495, in gc
    backend_store._hard_delete_run(run_id)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 573, in _hard_delete_run
    session.delete(run)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 86, in make_managed_session
    raise MlflowException(message=e, error_code=BAD_REQUEST)
mlflow.exceptions.MlflowException: (psycopg2.errors.ForeignKeyViolation) update or delete on table "runs" violates foreign key constraint "metrics_run_uuid_fkey" on table "metrics"
DETAIL:  Key (run_uuid)=(0b3534e4a7e4475cb5c06cc5427911bb) is still referenced from table "metrics".

[SQL: DELETE FROM runs WHERE runs.run_uuid = %(run_uuid)s]
[parameters: {'run_uuid': '0b3534e4a7e4475cb5c06cc5427911bb'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```
