### ISSUE TITLE
Logging artifacts fail when running MLFlow server in a docker container

### ISSUE THREAD

**Issue by bertomartin** [mlflow/mlflow#617]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: stock
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**: 3.7
- **npm version (if running the dev UI):N/A
- **Exact command to reproduce**:

### Describe the problem
I'm trying to use a minio server to log large artfiacts locally. I've setup MLFlow Server within a docker container. It's stated in the docs here (https://www.mlflow.org/docs/latest/tracking.html#amazon-s3) that we can set this up by setting an environment variable:
```bash
export MLFLOW_S3_ENDPOINT_URL=http://1.2.3.4:9000
```
After executing my "example.py" file, I get the errors below. I setup this environment variable both in the container and on my local machine where I'm running the mlflow client from. I browsed the source code, but it doesn't seem like any of the repositories are expecting an endpoint in this format for storing large artifacts. 

I basically just want to understand how to use a minio server (as the docs seem to state) as a local artifact store as it's not possible to store artifacts when you're running the mlflow server within a docker container

### Source code / logs
```python
$ python example.py
logging artifacts to:  /opt/mlflow/artifactStore/0/cda16318c26740768ca17876aafe7a38/artifacts
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    log_artifact("output.txt")
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 212, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/site-packages/mlflow/tracking/client.py", line 155, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/site-packages/mlflow/store/local_artifact_repo.py", line 21, in log_artifact
    mkdir(artifact_dir)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 104, in mkdir
    raise e
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 101, in mkdir
    os.makedirs(target)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/trpfb50/anaconda/envs/py36/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/mlflow'
```

**Comment by bertomartin** [comment]
@harmw The location is within a docker container that's isolated from the local environment. So it isn't accessible. My question is how would one achieve such a setup using docker. The documentation seems to suggest that you can use a minio server as an artifact repo, but it's not clear how to do that.

**Comment by oriolmirosa** [comment]
I'm having the same issue. @bertomartin, have you been able to find a solution?

**Comment by flmu** [comment]
I have provided a demo for this problem. You can find my demo in the following repository:
https://github.com/flmu/mlflow-tracking-server

**Comment by bertomartin** [comment]
@flmu thanks, I'll check it out. was trying to get things working locally with minio (https://www.minio.io/). It basically mimics s3, but not much success so far.
