### ISSUE TITLE
Issues with mlflow sagemaker deploy

### ISSUE THREAD

**Issue by hollytb** [mlflow/mlflow#6255]
### System information

j

### Code to reproduce issue

bb

### Describe the problem

I want to deploy a mlflow spark app to sagemaker. Is this possible? As I sucessfully push a image to ECR with

`mlflow sagemaker build-and-push-container` 

and then when I attempt to deploy this image with 

'mlflow sagemaker deploy...'

It fails due to a time out when trying to create the endpoint. When I log at the in cloud watch multiple errors appear, one is for example:
`py4j.protocol.Py4JJavaError: An error occurred while calling o75.load.` or 

`2022/07/15 13:41:44 [error] 453#453: *21 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.32.0.2, server: , request: "GET /ping HTTP/1.1", upstream: "http://127.0.0.1:8000/ping", host: "model.aws.local:8080"` or 

`gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>` or 
`CondaValueError: prefix already exists: /miniconda/envs/custom_env`

I use libraries like:
`from pyspark.sql import SparkSession

import pyspark.sql.types as T 
import pyspark.sql.functions as F
from pyparsing import col
from pyspark.sql.window import Window
from pyspark.ml.feature import Bucketizer
from pyspark.ml.evaluation import RegressionEvaluator
from pandas import DataFrame

import mlflow
import mlflow.spark`

I use versions 
java - 18.0.333
spark 3.1.2
hadoop 3.2
And all other necessary pip installations. Any help would be nice

**Comment by harupy** [comment]
> When I log at the in cloud watch multiple errors appear, one is for example:

@hollytb Could you share the full failure logs?

**Comment by hollytb** [comment]
@harupy Thanks for your help, I've uploaded a csv of the logged error to the comment

**Comment by harupy** [comment]
@hollytb Can you try deploying a non-spark model (e.g. scikit-learn model) and check if it succeeds?

**Comment by harupy** [comment]
@hollytb https://github.com/mlflow/mlflow/issues/726 seems related. Using a larger instance might help (as described in https://github.com/mlflow/mlflow/issues/726#issuecomment-442187169).

**Comment by harupy** [comment]
@hollytb You can also try running this command to check if model serving works locally:

```bash
# Run the script you attached to log a model first, then run
mlflow sagemaker run-local -m runs:/<run_id>/model
```

**Comment by harupy** [comment]
@hollytb I was able to reproduce `CondaValueError: prefix already exists: /miniconda/envs/custom_env` by using `docker run --retry=always`. I think SageMaker retries running the container and the entry point (that calls `conda env create -n custom_env`) is executed multiple times.

**Comment by hollytb** [comment]
@harupy when I check if the model is serving locally is fails with the error:
`2022/07/18 11:04:27 INFO mlflow.sagemaker: executing: docker run -v C:\Users\....\mlruns\5\0a92547...\artifacts\model:/opt/ml/model/ -p 5000:8080 -e MLFLOW_DEPLOYMENT_FLAVOR_NAME=python_function -e SERVING_ENVIRONMENT=SageMaker --rm mlflow-pyfunc serve
docker: Error response from daemon: driver failed programming external connectivity on endpoint epic_kapitsa (8d05038a9156c5aba360d24c3756d249171b95bfd0f4cd9ff8c2168d6b4d3f7a): Bind for 0.0.0.0:5000 failed: port is already allocated.` Would this be causing the deploy stage to fail?

**Comment by hollytb** [comment]
@harupy  using a larger instance didn't work, would the parameters,  instance count and flavor, have a impact? 

When I check if the model is serving locally, the output doesn't come to a end, it continues to outputthe following lines:

`2022-07-18 10:40:26 +0000] [459] [INFO] Starting gunicorn 20.1.0
[2022-07-18 10:40:26 +0000] [459] [INFO] Listening at: http://127.0.0.1:8000 (459)
[2022-07-18 10:40:26 +0000] [459] [INFO] Using worker: gevent
[2022-07-18 10:40:26 +0000] [472] [INFO] Booting worker with pid: 472
[2022-07-18 10:40:26 +0000] [473] [INFO] Booting worker with pid: 473
[2022-07-18 10:40:26 +0000] [474] [INFO] Booting worker with pid: 474
[2022-07-18 10:40:26 +0000] [475] [INFO] Booting worker with pid: 475
[2022-07-18 10:40:26 +0000] [476] [INFO] Booting worker with pid: 476
[2022-07-18 10:40:26 +0000] [477] [INFO] Booting worker with pid: 477
[2022-07-18 10:40:26 +0000] [478] [INFO] Booting worker with pid: 478
[2022-07-18 10:40:26 +0000] [479] [INFO] Booting worker with pid: 479
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:472)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:473)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:474)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:475)
[2022-07-18 10:41:28 +0000] [475] [INFO] Worker exiting (pid: 475)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:476)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:477)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:478)
[2022-07-18 10:41:28 +0000] [459] [CRITICAL] WORKER TIMEOUT (pid:479)
[2022-07-18 10:41:28 +0000] [474] [INFO] Worker exiting (pid: 474)
[2022-07-18 10:41:28 +0000] [479] [INFO] Worker exiting (pid: 479)
[2022-07-18 10:41:28 +0000] [478] [INFO] Worker exiting (pid: 478)
[2022-07-18 10:41:28 +0000] [473] [INFO] Worker exiting (pid: 473)
[2022-07-18 10:41:28 +0000] [476] [INFO] Worker exiting (pid: 476)
[2022-07-18 10:41:28 +0000] [477] [INFO] Worker exiting (pid: 477)
[2022-07-18 10:41:28 +0000] [472] [INFO] Worker exiting (pid: 472)
[2022-07-18 10:41:30 +0000] [459] [WARNING] Worker with pid 473 was terminated due to signal 9
...
[2022-07-18 10:45:20 +0000] [459] [WARNING] Worker with pid 1157 was terminated due to signal 9
[2022-07-18 10:45:20 +0000] [1238] [INFO] Booting worker with pid: 1238
[2022-07-18 10:45:22 +0000] [1237] [INFO] Booting worker with pid: 1237
[2022-07-18 10:45:22 +0000] [1236] [INFO] Booting worker with pid: 1236
[2022-07-18 10:45:28 +0000] [459] [WARNING] Worker with pid 1143 was terminated due to signal 9
[2022-07-18 10:45:28 +0000] [1239] [INFO] Booting worker with pid: 1239
[2022-07-18 10:45:38 +0000] [459] [WARNING] Worker with pid 1136 was terminated due to signal 9
[2022-07-18 10:45:41 +0000] [1276] [INFO] Booting worker with pid: 1276
[2022-07-18 10:45:42 +0000] [459] [WARNING] Worker with pid 1142 was terminated due to signal 9
[2022-07-18 10:45:42 +0000] [1281] [INFO] Booting worker with pid: 1281`

**Comment by hollytb** [comment]
@harupy So far one error has occured while running the above command:
` Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/tmpg1bflz7u/connection3712313196413081753.info
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
        at java.nio.file.Files.createTempFile(Files.java:852)
        at org.apache.spark.api.python.PythonGatewayServer$.main(PythonGatewayServer.scala:52)
        at org.apache.spark.api.python.PythonGatewayServer.main(PythonGatewayServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)[2022-07-18 10:50:26 +0000] [459]
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) `

**Comment by harupy** [comment]
@hollytb I ran the same command on Linux and it worked fine. This might be because

**Comment by hollytb** [comment]
@harupy unfortunately not. Would using mleap to serialize the model format for sagemaker be a potential solution, rather than logging the model through: mlflow.spark.log_model? I've read a few resources suggesting logging in the mleap format. [https://docs.microsoft.com/en-us/azure/databricks/_static/notebooks/mlflow/mlflow-mleap-training.html ](url) [https://sagemaker-examples.readthedocs.io/en/latest/sagemaker-python-sdk/sparkml_serving_emr_mleap_abalone/sparkml_serving_emr_mleap_abalone.html](url)

**Comment by harupy** [comment]
@hollytb Mleap might work. Have you tried WSL (https://docs.microsoft.com/en-us/windows/wsl/install)?

**Comment by jseo0703** [comment]
Is this issue not solved? I am having the same problem with databricks service endpoint creation.

**Comment by B-Step62** [comment]
Closing due to inactivity and insufficient detail to reproduce. Feel free to reopen with full logs and environment details.
