### ISSUE TITLE
[BUG] Can't pickle <function r2_score at 0x7f1b594cf310>: it's not the same object as sklearn.metrics._regression.r2_score

### ISSUE THREAD

**Issue by tsungjung411** [mlflow/mlflow#6268]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **Python version**: Python 3.9.7
- **yarn version, if running the dev UI**: N/A

## Root cause
cannot pickle a model on the local side
(unable to serialize a model on the local side)

<br>

## Expected behavior
can pickle a model (can serialize a model)  on the local side

<br>

### for classification
got via the `python` command
> _pickle.PicklingError: Can't pickle <function accuracy_score at 0x7efad52c2280>: it's not the same object as sklearn.metrics._classification.accuracy_score

got via the ipykernel (Notebook kernel)
> PicklingError: Can't pickle <function accuracy_score at 0x7f17a5ca2a60>: it's not the same object as sklearn.metrics._classification.accuracy_score

### for regression:
got via the `python` command
> _pickle.PicklingError: Can't pickle <function r2_score at 0x7f162c7fd0d0>: it's not the same object as sklearn.metrics._regression.r2_score

got via the ipykernel (Notebook kernel)
> PicklingError: Can't pickle <function r2_score at 0x7ff325880f70>: it's not the same object as sklearn.metrics._regression.r2_score

<br>

### for classification
```python
import mlflow
mlflow.autolog()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from autosklearn.classification import AutoSklearnClassifier

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
#model = RandomForestClassifier() # pass
model = AutoSklearnClassifier(    # failed
    memory_limit = 1024 * 12,     # (in MB) (default: 3072 MB)
    time_left_for_this_task = 60, # 60 sec.
    per_run_time_limit = 15)      # 15 sec.
model.fit(train_X, train_y)

# inference
print('score:', model.score(test_X, test_y))

# save the model to the local disk
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
    print('Model saved successfully')
```
![image](https://user-images.githubusercontent.com/14820019/179656515-0e30a54a-ec3b-4788-bfab-261cda18b562.png)

### for regression:
```python
import mlflow
mlflow.autolog()

from sklearn.linear_model import LinearRegression
from autosklearn.regression import AutoSklearnRegressor

train_X = [[1], [3], [5], [7], [9]]
train_y = [2, 6, 10, 14, 18]

# training
# model = LinearRegression()      # pass
model = AutoSklearnRegressor(     # failed
    memory_limit = 1024 * 12,     # (in MB) (default: 3072 MB)
    time_left_for_this_task = 60, # 60 sec.
    per_run_time_limit = 15)      # 15 sec.
model.fit(train_X, train_y)

# inference
test_X = [[2], [4], [6], [8], [10]]
test_y = [4, 8, 12, 16, 20]
print('score:', model.score(test_X, test_y))

# save the model to the local disk
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
    print('Model saved successfully')
```
![image](https://user-images.githubusercontent.com/14820019/179656547-231ab6e8-a962-400a-8af7-4032a9f1d781.png)

### Tracking information

MLflow version: 1.27.0
Tracking URI: file:///workspace/mlruns
Artifact URI: file:///workspace/mlruns/0/37326b5ea62046bcbd9b7eb8ab26cf23/artifacts

## snapshot
![image](https://user-images.githubusercontent.com/14820019/179663349-872110ce-57f2-4fd3-8bc2-00aab83baa33.png)

### Code to reproduce issue

```python
import mlflow
import sklearn.metrics
import pickle

cannot_pickle = True

if cannot_pickle:
    # failed
    mlflow.sklearn.autolog()
    r2_public = sklearn.metrics.r2_score
    r2_private = sklearn.metrics._regression.r2_score
else:
    # pass
    r2_public = sklearn.metrics.r2_score
    r2_private = sklearn.metrics._regression.r2_score
    mlflow.sklearn.autolog()

print('sklearn.metrics.r2_score:')
print('__hash__:', r2_public.__hash__)
print('__code__:', r2_public.__code__)
print('-' * 60)
print('sklearn.metrics._regression.r2_score:')
print('__hash__:', r2_private.__hash__)
print('__code__:', r2_private.__code__)
print('-' * 60)

with open('r2.pkl', 'wb') as f:
    pickle.dump(r2_public, f)
    print('r2.pkl saved successfully')
```

### Other info / logs

```python-traceback
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
/tmp/ipykernel_836/453514921.py in <module>
     26 
     27 with open('r2.pkl', 'wb') as f:
---> 28     pickle.dump(r2_public, f)
     29     print('r2.pkl saved successfully')

PicklingError: Can't pickle <function r2_score at 0x7f1b594cf310>: it's not the same object as sklearn.metrics._regression.r2_score
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
I was able to reproduce the issue. I think the cause is `mlflow.sklearn.autolog` patches `accuracy_score`.

**Comment by harupy** [comment]
Checking what happens if we don't patch the sklearn's metric functions.

**Comment by harupy** [comment]
```diff
diff --git a/mlflow/sklearn/__init__.py b/mlflow/sklearn/__init__.py
index da1fd1d3b..497b0f2cc 100644
--- a/mlflow/sklearn/__init__.py
+++ b/mlflow/sklearn/__init__.py
@@ -1697,12 +1697,14 @@ def _autolog(
 
     if log_post_training_metrics:
         for metric_name in _get_metric_name_list():
-            safe_patch(
-                flavor_name, sklearn.metrics, metric_name, patched_metric_api, manage_run=False
-            )
+            pass
+            # safe_patch(
+            #     flavor_name, sklearn.metrics, metric_name, patched_metric_api, manage_run=False
+            # )
 
         for scorer in sklearn.metrics.SCORERS.values():
-            safe_patch(flavor_name, scorer, "_score_func", patched_metric_api, manage_run=False)
+            pass
+            # safe_patch(flavor_name, scorer, "_score_func", patched_metric_api, manage_run=False)
 
     def patched_fn_with_autolog_disabled(original, *args, **kwargs):
         with disable_autologging():
```

**Comment by harupy** [comment]
@tsungjung411 `mlflow.sklearn.autolog(log_post_training_metrics=False)` can prevent the issue.

**Comment by tsungjung411** [comment]
The solution is not acceptable. We still need the post training metrics. There is something wrong in mlflow.

## pickle a model: pass
```python
import mlflow

#mlflow.autolog() # failed

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from autosklearn.classification import AutoSklearnClassifier

mlflow.autolog() # pass

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
# model = RandomForestClassifier() # pass
model = AutoSklearnClassifier(  # failed
    memory_limit=1024 * 12,  # (in MB) (default: 3072 MB)
    time_left_for_this_task=30,  # 60 sec.
    per_run_time_limit=3,
)  # 15 sec.
model.fit(train_X, train_y)

# inference
print("score:", model.score(test_X, test_y))

# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```

## pickle a model: failed
```python
import mlflow

mlflow.autolog() # failed

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from autosklearn.classification import AutoSklearnClassifier

#mlflow.autolog() # pass

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
# model = RandomForestClassifier() # pass
model = AutoSklearnClassifier(  # failed
    memory_limit=1024 * 12,  # (in MB) (default: 3072 MB)
    time_left_for_this_task=30,  # 60 sec.
    per_run_time_limit=3,
)  # 15 sec.
model.fit(train_X, train_y)

# inference
print("score:", model.score(test_X, test_y))

# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```

## difference
The difference is the order of mlflow.autolog() and import-AutoSklearnClassifier statement.
- pass
  ```python
  ...
  from autosklearn.classification import AutoSklearnClassifier
  mlflow.autolog() # pass
  ...
  ```
- failed
  ```python
  ...
  mlflow.autolog() # failed
  from autosklearn.classification import AutoSklearnClassifier
  ...
  ```

**Comment by harupy** [comment]
@tsungjung411 What does `failed` and `pass` mean?

**Comment by tsungjung411** [comment]
**failed**: the program will be stopped due to an error, and cannot output a model to the local disk
```
Traceback (most recent call last):
  File ".../ml_sklearn/doc/examples/mlflow/pass.py", line 31, in <module>
    pickle.dump(model, f)
_pickle.PicklingError: Can't pickle <function accuracy_score at 0x7fe3863f8310>: it's not the same object as sklearn.metrics._classification.accuracy_score
```

**pass**: the program can output a model to the local disk successfullly

**Comment by harupy** [comment]
Executing `mlflow.autolog()` after the import statements didn't work. I got `_pickle.PicklingError: Can't pickle <function accuracy_score at 0x7fe3863f8310>: it's not the same object as sklearn.metrics._classification.accuracy_score`.

**Comment by harupy** [comment]
btw sklearn autologging may not work properly with `AutoSklearnClassifier`.

**Comment by tsungjung411** [comment]
`AutoSklearnClassifier` and `AutoSklearnRegressor` are ensemble classes that combine multiple scikit-learn (sklearn) models into one model. Auto-sklearn just uses scikit-learn packages.

**Comment by tsungjung411** [comment]
I have found an easy way to reproduce this case without the auto-sklearn package.

```python
import mlflow

#mlflow.autolog() # failed

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

class MyRF(RandomForestClassifier):
    def __init__(self):
        super(MyRF, self).__init__()
        self.accu = accuracy_score

mlflow.autolog() # also failed

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
model = MyRF()
model.fit(train_X, train_y)

# inference
print("score:", model.score(test_X, test_y))

# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```
![image](https://user-images.githubusercontent.com/14820019/179890803-e383bc5c-9188-4b43-b658-36b58e84f3af.png)

- The key point is `self.accu = accuracy_score`.
- Without the statement, the model can be saved successfully.

**Comment by harupy** [comment]
The code you attached worked.

**Comment by tsungjung411** [comment]
Sorry, I forgot to restart the kernerl from Notebook.

Please have a trial again. `mlflow.autolog()` precedes `import accuracy_score`.
```
import mlflow

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

mlflow.autolog()  # failed
from sklearn.metrics import accuracy_score
#mlflow.autolog() # here can work

class MyRF(RandomForestClassifier):
    def __init__(self):
        super(MyRF, self).__init__()
        self.accu = accuracy_score


X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
model = MyRF()
model.fit(train_X, train_y)

# inference
print("score:", model.score(test_X, test_y))

# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```
![image](https://user-images.githubusercontent.com/14820019/179893704-593156d8-f35b-4b1f-abec-5ded852c65fc.png)

**Comment by tsungjung411** [comment]
Regression metrics have the same situation.

```python
import mlflow
from sklearn.ensemble import RandomForestRegressor

mlflow.autolog()  # failed
from sklearn.metrics import r2_score
#mlflow.autolog()  # here can work


class MyRF(RandomForestRegressor):
    def __init__(self):
        super(MyRF, self).__init__()
        self.r2 = r2_score

# training
model = MyRF()
model.fit(X=[[1], [2], [3]], y=[2, 4, 6])


# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```

![image](https://user-images.githubusercontent.com/14820019/179896048-0e522176-ada8-466c-80f0-266d3dd67791.png)

**Comment by harupy** [comment]
In the successful case, `accuracy_score` is the original `accuracy_score` so works.
In the failed case, `accuracy_score` is the patched `accuracy_score` so doesn't work.

**Comment by tsungjung411** [comment]
Some of Scikit-learn's other APIs are also patched, such as `fit`, `score`, but they can still be pickled.

## show patched hashes before and after `mlflow.autolog()`.
```python
import mlflow
from sklearn.ensemble import RandomForestRegressor

print(RandomForestRegressor.fit)
print(RandomForestRegressor.score)
mlflow.autolog()
print(RandomForestRegressor.fit)
print(RandomForestRegressor.score)
```
![image](https://user-images.githubusercontent.com/14820019/179901927-69987966-83be-42c7-97e2-23111b7a5d30.png)

<br>

## save a patched object to Python pickle
```python
import mlflow

mlflow.autolog()  # can work
from sklearn.ensemble import RandomForestRegressor
#mlflow.autolog()  # can work

# training
model = RandomForestRegressor()
model.fit(X=[[1], [3], [5]], y=[2, 6, 10])
print(model.score(X=[[2], [4]], y=[4, 8]))

# save the model to the local disk
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model saved successfully")
```
![image](https://user-images.githubusercontent.com/14820019/179902387-c00046d5-511f-4b24-8865-026dcda254c6.png)

**Comment by harupy** [comment]
`fit` is a method, but `accuracy_score` is not. I'm not sure why pickle complains.

**Comment by tsungjung411** [comment]
## code
### `base.py`
```python
def r2_score():
    print('calling r2_score()')
    return 1.0
```

### `utils.py`
```python
from base import r2_score
```

### `main.py`
```python
from functools import wraps
import utils

def patch(func):
    @wraps(func)
    def wrapper():
        print('>>> [ENTER]')
        score = func()
        print('<<< [EXIT]')
        return score
    return wrapper

# before patching
print('score: {} ({})'.format(
    utils.r2_score(),
    utils.r2_score.__hash__
))
print('-' * 60)

# patching
setattr(utils, 
        'r2_score', 
        patch(getattr(utils, 'r2_score')))

# after patching
print('score: {} ({})'.format(
    utils.r2_score(),
    utils.r2_score.__hash__
))
print('-' * 60)


import pickle
with open('r2.pkl', 'wb') as f:
    pickle.dump(utils.r2_score, f)

print('save successfully')
```

<br>

## run
[cannot_pickle_model.zip](https://github.com/mlflow/mlflow/files/9147180/cannot_pickle_model.zip)

```
$ python main.py 
calling r2_score()
score: 1.0 (<method-wrapper '__hash__' of function object at 0x7f0aaa403040>)
------------------------------------------------------------
>>> [ENTER]
calling r2_score()
<<< [EXIT]
score: 1.0 (<method-wrapper '__hash__' of function object at 0x7f0aaa45af70>)
------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/cannot_pickle/main.py", line 35, in <module>
    pickle.dump(utils.r2_score, f)
_pickle.PicklingError: Can't pickle <function r2_score at 0x7f0aaa45af70>: it's not the same object as base.r2_score
```

**Comment by harupy** [comment]
`cloudpickle` worked:

```
import mlflow

mlflow.autolog()  # failed

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from autosklearn.classification import AutoSklearnClassifier

# mlflow.autolog()  # pass

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

# training
# model = RandomForestClassifier() # pass
model = AutoSklearnClassifier(  # failed
    memory_limit=1024 * 12,  # (in MB) (default: 3072 MB)
    time_left_for_this_task=60,  # 60 sec.
    per_run_time_limit=15,  # 15 sec.
)  # 15 sec.
model.fit(train_X, train_y)

# inference
print("score:", model.score(test_X, test_y))

# save the model to the local disk
import cloudpickle

with open("model.pkl", "wb") as f:
    cloudpickle.dump(model, f)
print("Model saved successfully")
```

Output:

```
2022/07/26 14:23:20 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.
2022/07/26 14:23:20 INFO mlflow.pyspark.ml: No SparkSession detected. Autologging will log pyspark.ml models contained in the default allowlist. To specify a custom allowlist, initialize a SparkSession prior to calling mlflow.pyspark.ml.autolog() and specify the path to your allowlist file via the spark.mlflow.pysparkml.autolog.logModelAllowlistFile conf.
2022/07/26 14:23:20 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.ml.
2022/07/26 14:23:20 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/07/26 14:23:24 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ad52984e82214f91a7fd1847c7592311', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2022/07/26 14:23:24 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2022/07/26 14:23:24 WARNING mlflow.sklearn: Failed to infer model signature: 'StandardScalerComponent' object has no attribute 'predict'
2022/07/26 14:23:25 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '24d241776eb144e5b043eaaf532201b1', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2022/07/26 14:23:25 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2022/07/26 14:23:25 WARNING mlflow.sklearn: Failed to infer model signature: the trained model does not specify a `predict` function, which is required in order to infer the signature
score: 0.9736842105263158
Model saved successfully
```

**Comment by harupy** [comment]
@tsungjung411 Feel free to reopen the issue if you need further help.

**Comment by tsungjung411** [comment]
Wow! Awesome!

![image](https://user-images.githubusercontent.com/14820019/180970287-66833970-2295-444c-8cff-d3156549e8f1.png)

**Comment by tsungjung411** [comment]
## Another workaround:
just add the import statement to the head (before `mlflow.autolog()`)

```python
from autosklearn.classification import AutoSklearnClassifier   # import first
import mlflow

mlflow.autolog()  # failed

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from autosklearn.classification import AutoSklearnClassifier  # originally imported
...
(original code)
...
```

**Comment by tsungjung411** [comment]
## same issue also happened in [AutoGluon](https://auto.gluon.ai/0.1.0/install.html)
```
[2022-10-03 14:56:25][Level 25][abstract_trainer.py#60] AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
[2022-10-03 14:56:25][INFO][abstract_trainer.py#66] 	To change this, specify the eval_metric parameter of Predictor()
Traceback (most recent call last):
  File "/workspace/main.py", line 136, in <module>
    main()
  File "/workspace/main.py", line 36, in main
    train(context)
  File "/workspace/trainer.py", line 38, in train
    model_instance.fit()
  File "/workspace/model/abstract_model.py", line 156, in fit
    self._model.fit(self._x, self._y)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py", line 548, in safe_patch_function
    patch_function(call_original, *args, **kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py", line 254, in patch_with_managed_run
    result = patch_function(original, *args, **kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/sklearn/__init__.py", line 1481, in patched_fit
    result = fit_impl(original, self, *args, **kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/sklearn/__init__.py", line 1285, in fit_mlflow
    fit_output = original(self, *args, **kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py", line 529, in call_original
    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py", line 471, in call_original_fn_with_event_logging
    original_fn_result = original_fn(*og_args, **og_kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py", line 526, in _original_fn
    original_result = original(*_og_args, **_og_kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/workspace/model/local_ag_tabular_predictor.py", line 123, in fit
    self.__predctor.fit(train_data, **self.__fit_params)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/utils/decorators.py", line 30, in _call
    return f(*gargs, **gkwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/predictor/predictor.py", line 831, in fit
    self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/learner/abstract_learner.py", line 118, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/learner/default_learner.py", line 125, in _fit
    self.save()
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/learner/abstract_learner.py", line 88, in save
    save_pkl.save(path=self.save_path, object=self)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/common/savers/save_pkl.py", line 21, in save
    save_with_fn(validated_path, object, pickle_fn, format=format, verbose=verbose, compression_fn=compression_fn,
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/common/savers/save_pkl.py", line 38, in save_with_fn
    pickle_fn(object, fout)
  File "/usr/local/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/common/savers/save_pkl.py", line 20, in <lambda>
    pickle_fn = lambda o, buffer: pickle.dump(o, buffer, protocol=4)
_pickle.PicklingError: Can't pickle <function accuracy_score at 0x7fe245c7d430>: it's not the same object as sklearn.metrics._classification.accuracy_score
```
But we can't modify the code in autogluon

**Comment by rodrigo-georgian** [comment]
What is the solution for AutoGluon? I'm okay with disabling the metrics in mlflow but none of the suggestions above for imports worked for me.

**Comment by shchur** [comment]
@rodrigo-georgian calling `mlflow.autolog(disable=True)` before AutoGluon is imported fixed the issue for me (see https://github.com/autogluon/autogluon/issues/4914#issuecomment-2677909499).
