### ISSUE TITLE
How to do model serve for unsupervised models?

### ISSUE THREAD

**Issue by RavitejaBadugu** [mlflow/mlflow#6273]
I am using the code from [This URL. A basic example of using mlflow](https://github.com/RamVegiraju/mlflow-serving/blob/master/train.py).
When I change the model and instead of using the supervised approach when I change it to unsupervised. (Just for checking how to use for unsupervised). The updated code is
```
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
import mlflow
import mlflow.sklearn

if __name__ == "__main__":
    #Load data
    boston = datasets.load_boston()
    df = pd.DataFrame(boston.data, columns = boston.feature_names)
    df['MEDV'] = boston.target
    
    #Split Model
    X = df.drop(['MEDV'], axis = 1) 
    y = df['MEDV']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)
    
    #Model Creation
    lm = NearestNeighbors()
    lm.fit(X_train)
    mlflow.sklearn.log_model(lm, "model")
    print("Model saved in run %s" % mlflow.active_run().info.run_uuid)
```
But in artifacts MLmodel file is not having **python_function**
```
artifact_path: model
flavors:
  sklearn:
    code: null
    pickled_model: model.pkl
    serialization_format: cloudpickle
    sklearn_version: 1.1.1
mlflow_version: 1.27.0
model_uuid: cbb3594ef15f435da76e33a799879b87
run_id: f7eec4947499444db1903e7d609274e0
utc_time_created: '2022-07-19 17:25:44.951115'
```
When I  run the command:
```
mlflow models serve --model-uri runs:/f7eec4947499444db1903e7d609274e0/model --no-conda
```
The error I am getting is
```
`--env-manager=local` instead.
  value = self.callback(ctx, self, value)
Traceback (most recent call last):
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ravi1\anaconda3\envs\restaurant\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\mlflow\models\cli.py", line 68, in serve
    return _get_flavor_backend(
  File "C:\Users\ravi1\anaconda3\envs\restaurant\lib\site-packages\mlflow\models\cli.py", line 219, in _get_flavor_backend
    raise Exception("No suitable flavor backend was found for the model.")
Exception: No suitable flavor backend was found for the model.
```
When I change it to supervised training. Everything is working fine.
So, how to use mlflow for unsupervised models?

**Comment by harupy** [comment]
Hi @RavitejaBadugu, we currently don't support serving a scikit-learn model that doesn't implement `predict`.

**Comment by harupy** [comment]
You can extend `NearestNeighbors` like this:

```python
class MyNearestNeighbors(NearestNeighbors):
    def predict(...):
        ...
```

**Comment by harupy** [comment]
@RavitejaBadugu Feel free to reopen the issue if extending a class to implement a predict method doesn't help.
