### ISSUE TITLE
[BUG] Spark UDF `env_manager` breaks when run locally

### ISSUE THREAD

**Issue by jerrylian-db** [mlflow/mlflow#6298]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.1.dev0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Monterey 12.4
- **Python version**: v3.7.13. My environment is the same environment as what is installed latest via `dev/dev-env-setup.sh -d .venvs/mlflow-dev -q`
- **pyspark version**: 3.3.0

### Describe the problem

I am trying to use the `env_manager` option for loading a model and scoring a dataframe via the Spark UDF. However, when I trained a model and the loaded it via Spark UDF (see reproduce code below), I got the following error which I don't know how to solve. This is not an issue when run in Databricks.

```
An error occurred while calling o90.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (10.0.0.30 executor driver): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
```

### Code to reproduce issue

```python
import mlflow
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from pyspark.sql.functions import struct
from pyspark.sql import SparkSession

mlflow.set_experiment("demo")
with mlflow.start_run() as run:
    X, y = load_diabetes(as_frame=True, return_X_y=True)
    model = LinearRegression().fit(X, y)
    mlflow.sklearn.log_model(model, artifact_path="train/model")

model_uri = "runs:/{run_id}/train/model".format(run_id=run.info.run_id)
X, _ = load_diabetes(as_frame=True, return_X_y=True)

spark = (
    SparkSession.builder.master("local[*]")
    .config("spark.jars.packages", "io.delta:delta-core_2.12:1.2.1")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config(
        "spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    )
    .getOrCreate()
)

input_sdf = spark.createDataFrame(X)
predict = mlflow.pyfunc.spark_udf(spark, model_uri, env_manager="conda")
scored_sdf = input_sdf.withColumn("prediction", predict(struct(*input_sdf.columns)))
scored_sdf.head(1)

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Thanks @jerrylian-db. Is there any additional stack trace information for:

```
An error occurred while calling o90.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (10.0.0.30 executor driver): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
```

?

**Comment by jerrylian-db** [comment]
Here's the full stack trace:
```
2022/07/21 16:13:52 INFO mlflow.pyfunc: This UDF will use Conda to recreate the model's software environment for inference. This may take extra time during execution.
2022/07/21 16:13:52 WARNING mlflow.pyfunc: In order to run inference code in restored python environment, PySpark UDF processes spawn MLflow Model servers as child processes. Due to system limitations with handling SIGKILL signals, these MLflow Model server child processes cannot be cleaned up if the Spark Job is canceled.
2022/07/21 16:13:53 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/07/21 16:13:54 INFO mlflow.utils.conda: === Creating conda environment /var/folders/qw/z137wp9572vd__7v3jmd1stc0000gp/T/tmpcdhyhv5p/envs/conda_envs/mlflow-9c9dd60098d21433615a854e1a7491b91ed5775c-a6884002b2a4e8ca80a4e9d29b7b062a11125029 ===
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
tk-8.6.12            | 3.4 MB    | ########## | 100% 
ca-certificates-2022 | 149 KB    | ########## | 100% 
ncurses-6.3          | 915 KB    | ########## | 100% 
sqlite-3.39.1        | 1.8 MB    | ########## | 100% 
python-3.7.13        | 20.3 MB   | ########## | 100% 
xz-5.2.5             | 228 KB    | ########## | 100% 
pip-22.1.2           | 1.5 MB    | ########## | 100% 
openssl-1.1.1q       | 1.9 MB    | ########## | 100% 
setuptools-63.2.0    | 1.3 MB    | ########## | 100% 
python_abi-3.7       | 4 KB      | ########## | 100% 
libzlib-1.2.12       | 63 KB     | ########## | 100% 
readline-8.1.2       | 266 KB    | ########## | 100% 
zlib-1.2.12          | 93 KB     | ########## | 100% 
wheel-0.37.1         | 31 KB     | ########## | 100% 
libcxx-14.0.6        | 1.3 MB    | ########## | 100% 
libffi-3.3           | 45 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/var/folders/qw/z137wp9572vd__7v3jmd1stc0000gp/T/tmpcdhyhv5p/envs/conda_envs/mlflow-9c9dd60098d21433615a854e1a7491b91ed5775c-a6884002b2a4e8ca80a4e9d29b7b062a11125029/bin/python', '-m', 'pip', 'install', '-U', '-r', '/var/folders/qw/z137wp9572vd__7v3jmd1stc0000gp/T/tmpcdhyhv5p/models/tmpnn91rpzw/model/condaenv.w3rq4i9l.requirements.txt']
Pip subprocess output:
Collecting mlflow
  Downloading mlflow-1.27.0-py3-none-any.whl (17.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 37.9 MB/s eta 0:00:00
Collecting cloudpickle==2.1.0
  Downloading cloudpickle-2.1.0-py3-none-any.whl (25 kB)
Collecting psutil==5.9.1
  Downloading psutil-5.9.1-cp37-cp37m-macosx_10_9_x86_64.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.0/239.0 kB 8.1 MB/s eta 0:00:00
Collecting scikit-learn==1


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda


2022/07/21 16:15:32 INFO mlflow.pyfunc.backend: === Running command 'source /Users/jerry.liang/opt/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-9c9dd60098d21433615a854e1a7491b91ed5775c-a6884002b2a4e8ca80a4e9d29b7b062a11125029 1>&2 && python -c ""'
2022/07/21 16:15:37 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/07/21 16:15:39 INFO mlflow.utils.conda: Conda environment /var/folders/qw/z137wp9572vd__7v3jmd1stc0000gp/T/tmpcdhyhv5p/envs/conda_envs/mlflow-9c9dd60098d21433615a854e1a7491b91ed5775c-a6884002b2a4e8ca80a4e9d29b7b062a11125029 already exists.
2022/07/21 16:15:39 INFO mlflow.pyfunc.backend: === Running command 'source /Users/jerry.liang/opt/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-9c9dd60098d21433615a854e1a7491b91ed5775c-a6884002b2a4e8ca80a4e9d29b7b062a11125029 1>&2 && exec gunicorn --timeout=60 -b 127.0.0.1:65280 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
objc[19262]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[19262]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/var/folders/qw/z137wp9572vd__7v3jmd1stc0000gp/T/ipykernel_19116/1022720443.py in <module>
      2 predict = mlflow.pyfunc.spark_udf(spark, model_uri, env_manager="conda")
      3 scored_sdf = input_sdf.withColumn("prediction", predict(struct(*input_sdf.columns)))
----> 4 scored_sdf.head(1)

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/pyspark/sql/dataframe.py in head(self, n)
   1924             rs = self.head(1)
   1925             return rs[0] if rs else None
-> 1926         return self.take(n)
   1927 
   1928     def first(self) -> Optional[Row]:

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/pyspark/sql/dataframe.py in take(self, num)
    866         [Row(age=2, name='Alice'), Row(age=5, name='Bob')]
    867         """
--> 868         return self.limit(num).collect()
    869 
    870     def tail(self, num: int) -> List[Row]:

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/pyspark/sql/dataframe.py in collect(self)
    815         """
    816         with SCCallSiteSync(self._sc):
--> 817             sock_info = self._jdf.collectToPython()
    818         return list(_load_from_socket(sock_info, BatchedSerializer(CPickleSerializer())))
    819 

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1320         answer = self.gateway_client.send_command(command)
   1321         return_value = get_return_value(
-> 1322             answer, self.gateway_client, self.target_id, self.name)
   1323 
   1324         for temp_arg in temp_args:

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    188     def deco(*a: Any, **kw: Any) -> Any:
    189         try:
--> 190             return f(*a, **kw)
    191         except Py4JJavaError as e:
    192             converted = convert_exception(e.java_exception)

~/mlflow/.venvs/mlflow-dev/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o90.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (10.0.0.30 executor driver): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:599)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:581)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:107)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:50)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:88)
	... 22 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:506)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:459)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:48)
	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3688)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3858)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3856)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3856)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:599)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:581)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:107)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:50)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:88)
	... 22 more
```

**Comment by dbczumar** [comment]
@jerrylian-db This looks like an OSX-specific multithreading security issue; looks like it can be remedied as follows:  https://stackoverflow.com/a/52230415. Here's another StackOverflow issue that mentions Spark UDFs specifically: https://stackoverflow.com/questions/55379298/how-to-use-pandas-udfs-on-macos-mojave-that-fails-due-to-nsplaceholderdicti.

In summary, this isn't an MLflow issue and seems to be a MacOS-specific issue introduced by security-related changes in High Sierra and above.
