### ISSUE TITLE
We'd like your feedback on MLflow Experiment Tracking

### ISSUE THREAD

**Issue by ridhimag11** [mlflow/mlflow#6348]
MLflow Experiments lets you easily track your experiments and compare runs. We're looking to further improve the tracking and comparison UX and would love to get your feedback on some prototypes we are exploring. 

If you're interested in chatting with us and giving us feedback, please [sign-up](https://forms.gle/V4kUfQ1YPB31AatP9) here 🙌

**Comment by KeyanatGiggso** [comment]
Hello team, nice registry for the tracking...

**Comment by dnsleu** [comment]
In Table View, the metrics that are displayed are the one from the last epoch. Would be nice to have the minimum / maximum achieved for that model instead of the last metric obtained.

**Comment by lester1027** [comment]
> In Table View, the metrics that are displayed are the ones from the last epoch. Would be nice to have the minimum / maximum achieved for that model instead of the last metric obtained.

Or even the number from a custom step

**Comment by aadarshsingh191198** [comment]
Why was box plot removed in MLFlow 2.3.2 from Chart View? It was present in v2.1.1.
In fact, is it possible to make the visualisations customisable? Why limit the types of charts available?

**Comment by roark** [comment]
One difficulty I find in the UI is it only loading 100 runs at a time. The charts in "Chart View" are only initially representative of a small portion of the dataset. One has to repeatedly click "load more" to see the charts fill out. It would be nice to be able to load all trials, or at least a larger number at once.

Another improvement would be if the Charts built in "Chart View" were persistent. As well as transferable to other experiments, since often I'm always building the same charts repeatedly.

Anyway, hope these recommendations are helpful. I enjoy using MLFlow, keep up the good work.

**Comment by jmcapra** [comment]
Feedback - add a "hide most recent run" button for the Parallel Coordinates chart - the most recent run tends to populate this chart with null values, greatly reducing the resolution of the true parameter values.

**Comment by jmcapra** [comment]
Another feature request - some way to show calculated summary statistics, e.g. average accuracy across all runs. E.g. a new chart type, "Statistics" or "Table", which updates based on the SQL-style filter in the search box and can show the average of any metrics.

**Comment by ridhimag11** [comment]
Thanks for sharing your this feedback @jmcapra. Would you be up for a brief chat about this issues and any other feedback on MLflow?

**Comment by jmcapra** [comment]
Hi @ridhimag11, I'd be happy to. I've booked some time with you next week. 

Another tiny bug: I have a run named "ConvNet - Augmented - FFT/Wavelet" but it is interpreted as a file path and just shows as "Wavelet" in some sections.
<img width="531" alt="image" src="https://github.com/mlflow/mlflow/assets/35404590/ab2d3151-c77d-4753-8650-a0c3d8ee6b53">

Another feature request: The ability to sort the z-level of different runs in the parallel coordinates plot (and line charts). I think it's currently sorted by most recent run, however I think a better default would be to sort by the performance metric, so the best performing models are on top/in front.

**Comment by nkrot** [comment]
how to remove the banner 'We’ve made several improvements to the new runs comparison experience.... If you prefer to use this experience, we'd love to know more.' ?

**Comment by khushal2911** [comment]
I can see the following experiment being run on localhost:5000 but there are no files saved at the given location.
Experiment ID: 1
Artifact Location: /home/ubuntu/notebooks/07-project/training_tracking_registry/mlruns/1

What could be the possible issue ? I'm using mlflow 2.3.1 on python3.10.0

**Comment by samthompsonAQ** [comment]
It would be nice to be able to group experiments via project.

**Comment by bsridatta** [comment]
Thanks for this issue. Is there any reason why the plots are not displayed by default like the chat_view when comparing? It is pretty hard to open and analyse each metrics and impossible to compare metrics of the same run. Am I missing something? 

![image](https://github.com/mlflow/mlflow/assets/17333185/6b3eaa0d-e881-45c9-b1db-46f202cd33cb)

**Comment by Bonnevie** [comment]
Just upgraded to the version with chart view, and it's very cool and nice to be able to see comparisons side by side now :)
A bit of feedback:
More color diversity would be great, a lot of my charts end up looking like this by accident (two grays, two blues)
![image](https://github.com/mlflow/mlflow/assets/5861991/6189d900-924a-4dac-a8e0-637ddf61c340)
On a cold start of the chart page, a lot of charts are generated, would be convenient if there was an option to "clear the dashboard".
Would be very useful if selecting an experiment from the sidebar would highlight the corresponding chart elements, seeing as occlusion sometimes prevents clicking the element directly in the chart.
Another useful feature would be a paired zoom, e.g. focusing on the same step range across all charts.

**Comment by aboomer07** [comment]
I think it would be helpful to be able to see the dataset hashes in the run comparison view so we can easily see what, if any, datasets have changed between runs!

**Comment by ReHoss** [comment]
+1 @claudiofernandez ; please add "Show diffs". Very important feature. @harupy

**Comment by phelps-matthew** [comment]
I'd really appreciate dark mode.

**Comment by a3sha2** [comment]
pls hide the  artifactory location s3://aml....
![Screenshot 2023-11-19 at 7 29 22 PM](https://github.com/mlflow/mlflow/assets/8614410/5bdd063e-ca3f-46c5-b345-fc399c9e59c2)

**Comment by ReHoss** [comment]
> pls hide the artifactory location s3://aml....
> 
> ![Screenshot 2023-11-19 at 7 30 57 PM](https://user-images.githubusercontent.com/8614410/284102019-61aa52ef-8ed7-4c55-a4bf-55d4bd9c9238.png)

I personally find it very useful to see where data is stored!

**Comment by emsi** [comment]
I find the new useless. It lacks the ability to select runs (there's only option to select 5, 10, 100 etc). Since I can't select runs to analyze it's of no use for me.

**Comment by hubertzub-db** [comment]
> I find the new useless. It lacks the ability to select runs (there's only option to select 5, 10, 100 etc). Since I can't select runs to analyze it's of no use for me.

@emsi drive-by comment: you can use "Eye" icon in order to add/remove runs from the comparison.

**Comment by emsi** [comment]
> @emsi drive-by comment: you can use "Eye" icon in order to add/remove runs from the comparison.


There are selctbox which are NOT honored when entering comparison and I end up in comparison with dozens to uncheck with eye now? So instead of checking 3 I have to un-eye 50? That's not convenient.

**Comment by alena-m** [comment]
Hi, is it possible to add token numbers to all parts of prompts? Currently we can only see the total number of tokens, but in addition to the total number it would be useful to see the tokens for each part separately.
![image](https://github.com/mlflow/mlflow/assets/22996008/5b0fcb77-4a80-4316-b7a9-da7ef3f7dc02)

**Comment by alena-m** [comment]
Is it possible to add the ability to change the row width in the Evaluation table? Sometimes the output is too long for cells, but I still want to compare them side by side.
<img width="1154" alt="image" src="https://github.com/mlflow/mlflow/assets/22996008/e312efb8-809a-4d4e-992a-95cc2eb3d28a">

**Comment by alena-m** [comment]
Is it possible to automatically fill in variable values from the previous run when we do "Duplicate run" for Prompt Engineering? If we have many variables it is tedious to fill them again and again.
![image](https://github.com/mlflow/mlflow/assets/22996008/d267375d-b2b8-486b-b3a0-2102cb7dd9fb)

**Comment by kyoungrok0517** [comment]
I think showing the `min` values of `train_loss` and `val_loss` in the main table would be more helpful.

**Comment by ridhimag11** [comment]
Hi @mendelson - can you share a screenshot of what you're seeing regarding the missing datasets. AFAIK, you should still be able to see the dataset dropdown in the list view.

**Comment by emsi** [comment]
![image](https://github.com/mlflow/mlflow/assets/433383/39546bb9-ad78-4971-a622-8e62ee2310be)

Why are data points labeled with values? That makes no sense. I can obtain the value either at glance or by hovering the mouse on the point yet I have no idea to which run and experiment the data belongs to! I can't make sense of the plot not knowing where the data point came from.
The labels should be either run, experiment, a combination of both or preferably allow to enter custom template.

**Comment by mendelson** [comment]
@ridhimag11 it is possible that I'm missing something, so any advices are welcome. I'm using 2.10.0.

I see there is a `Datasets` dropdown and, when I select one of them, it is possible to see which runs used those data (please note that the `Dataset` filter has a value selected).

![Captura de Tela 2024-02-05 às 18 09 26](https://github.com/mlflow/mlflow/assets/3266556/e8f46149-f706-428e-aab8-3639185ac090)

But it seems like I cannot do it the other way: given a specific run, how can I check which datasets were used?

![Captura de Tela 2024-02-05 às 18 07 43](https://github.com/mlflow/mlflow/assets/3266556/3fdc9726-53b6-4ec8-94ab-8e7f8364780a)

**Comment by ridhimag11** [comment]
@mendelson thank you for sharing this. Super helpful. We are planning to roll-out a new version of the run details page in the next few weeks, which will have the dataset values shown more clearly. We'll send you an update when that launches. 

In the meantime, for seeing the dataset values for a run, you can add the dataset column from the "Columns" dropdown in the header. Let me know if you have any further questions.

**Comment by ridhimag11** [comment]
hi @emsi thanks for the feedback. This is a known issue and we plan to roll out some updates for a fix in the next few weeks.

**Comment by mendelson** [comment]
@ridhimag11 thanks for the reply! I'm looking forward to the new version.

Regarding the datasets in the `Columns` dropdown, would you please be able to show me where that is? The `Columns` dropdown I'm looking at has no further options besides the one I already see in the run details.

![Captura de Tela 2024-02-06 às 15 15 45](https://github.com/mlflow/mlflow/assets/3266556/4bd6cbb0-08c3-4c70-b9ef-dd092dd418b3)

**Comment by hubertzub-db** [comment]
@mendelson hey, a quick update: datasets should be back in freshly released 2.10.1 patch: 
https://github.com/mlflow/mlflow/releases/tag/v2.10.1

**Comment by mendelson** [comment]
Wow! @ridhimag11 @hubertzub-db thanks for the quick response and fix. I have updated to 2.10.1 and now I can see the datasets for each run. Great job!

Also, I have just realized the aliases are not showing on the UI when I access the versions of a registered model. In order to do that, I have to enter on each version at a time to see its alias. Is this an already mapped fix or am I missing something?

![Captura de Tela 2024-02-08 às 11 47 46](https://github.com/mlflow/mlflow/assets/3266556/5fae1c6f-e475-48a1-af22-b5d1d09d7e69)

![Captura de Tela 2024-02-08 às 11 50 06](https://github.com/mlflow/mlflow/assets/3266556/0f93a9cc-877e-4327-a4ce-298ae8d4ab23)

**Comment by hubertzub-db** [comment]
@mendelson oh we've seen similar report in https://github.com/mlflow/mlflow/issues/10961 however we weren't able to reproduce it. 
Is it possible for you to enter the page with missing aliases with browser's developer tools open and send traces from browser's "Network" tab? That would be great and would heavily help with debugging.

**Comment by alvaropp** [comment]
I'm looking at the table listing runs in a given experiment and trying to order the runs by some parameter and it seems that it's not using natural sorting. I would expect the parameter values in the highlighted column to be sorted from smaller to larger.
<img width="1006" alt="Screenshot 2024-02-19 at 08 52 00" src="https://github.com/mlflow/mlflow/assets/4785303/a13b7f74-8b24-4ad4-9278-d8538875f26b">

**Comment by hubertzub-db** [comment]
Hi @alvaropp, thanks for flagging this.
It's a long standing issue caused by parameters actually being stored and handled as text string values instead of numbers (the param values are sorted "properly" when considering them in text string order). As we know it's inconvenient (apologies 🙏)  , the fix was was discussed and it turned out to be far from trivial. The actual improvement would need a lot of substantial changes in the parameter handling and persistence code, changing the platform's foundational logic. The problem will be revisited on a major version release.
Until then, you might be able to use a following workaround: try to log a metric that mirrors the parameter's value, then sort by this metric. Metric values are numbers so the ordering should behave properly.

**Comment by gau-nernst** [comment]
In 2.11.*, line chart data is sub-sampled. This makes MLFlow unuseable for me. Had to downgrade to 2.10. I couldn't find a setting to change sub-sampling setting (or if that is possible at all?).

2.11.3 - Uneven sampling rate, very low sampling rate. For some data, only the last data point is shown
![image](https://github.com/mlflow/mlflow/assets/26946864/6189a387-f1aa-435b-871b-37cf25a701c8)

2.10.2 - Showing the same data as above
![image](https://github.com/mlflow/mlflow/assets/26946864/8b530e4e-304e-4e15-ae6a-87d0a268c675)

**Comment by 0tist** [comment]
I'd like to see the experiment IDs again, can view them for MLFlow UI 2.11.1

![Screenshot 2024-04-01 at 6 51 05 PM](https://github.com/mlflow/mlflow/assets/42416623/75d65413-1dbf-4804-8b15-82660a61699d)

**Comment by nathalie321** [comment]
In mlflow ui 2.12.1, log_table doesn't display the image, but instead it shows up as [object Object].

**Comment by astrojuanlu** [comment]
My first experience is being a bit rough. I'm copy-pasting the "New run using notebook" on IPython, seemingly everything works, and yet my runs are all marked as "❌ Failed", no idea why. Maybe the `WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme` is the culprit, but (1) it's colored in the same way as the rest, so it was difficult to see initially, and (2) how am I supposed to change it? I'm just copy pasting instructions, I assumed everything to be correct!

**Comment by turbotimon** [comment]
I love MLFlow and use it whenever i can as it can replace several other separate tools.

I think a nice feature would be to download the current table view of an experiment as a CSV:
![image](https://github.com/mlflow/mlflow/assets/57718207/bcc027a2-b08e-4992-b542-a488bd40c7cf)

**Comment by turbotimon** [comment]
> My first experience is being a bit rough. I'm copy-pasting the "New run using notebook" on IPython, seemingly everything works, and yet my runs are all marked as "❌ Failed", no idea why. Maybe the `WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme` is the culprit, but (1) it's colored in the same way as the rest, so it was difficult to see initially, and (2) how am I supposed to change it? I'm just copy pasting instructions, I assumed everything to be correct!

I think it is a little bit hard to reproduce or help you without further information:
- To which notebook do you refer exactely? To [this](https://mlflow.org/docs/latest/getting-started/intro-quickstart/notebooks/tracking_quickstart.html)?
- Which tracking URI did you set (or is set in the notebook)?
- On which system are you (Windows/Linux/Mac)?

However, it may not the best place to discuss this here in this ticket. So you may open a discussion [here](https://github.com/mlflow/mlflow/discussions/categories/q-a) or in an other forum.

**Comment by root20** [comment]
Is it possible to adjust width of each frame?
I cannot distinguish experiments with long "Run name" as shown in the below capture.

<img width="714" alt="image" src="https://github.com/mlflow/mlflow/assets/8732466/8c0499a1-3b60-4a77-ae54-574a6dfa8f00">

**Comment by hubertzub-db** [comment]
@root20 a draggable pane have been implemented in this place to enable showing longer run names, however it's still behind experimental flag. If you're running tracking UI from the development build, you can change result of [this function](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/common/utils/FeatureUtils.ts#L33) to `true`. Otherwise, it will be enabled in the next major release.

**Comment by wzm2256** [comment]
I constantly run into errors when using tracking, and I need to refresh again and again and hope it can get back to work

```
[2024-07-30 23:21:39 +0200] [253452] [ERROR] Error handling request /ajax-api/2.0/mlflow/runs/searc[13/1663]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/conda/lib/python3.10/site-packages/mlflow/server/handlers.py", line 562, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/server/handlers.py", line 603, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/server/handlers.py", line 998, in _search_runs
    run_entities = _get_tracking_store().search_runs(
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/abstract_store.py", line 548, in searc
h_runs
    runs, token = self._search_runs(
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 942, in _search_r
uns
    runs.extend(self._get_run_from_info(r) for r in run_infos)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 942, in <genexpr>
    runs.extend(self._get_run_from_info(r) for r in run_infos)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 686, in _get_run_
from_info
    metrics = self._get_all_metrics(run_info)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 778, in _get_all_
metrics
    self._get_metric_from_file(parent_path, metric_file, run_info.experiment_id)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 758, in _get_metr
ic_from_file
    for line in read_file_lines(parent_path, metric_name)
  File "/opt/conda/lib/python3.10/site-packages/mlflow/utils/file_utils.py", line 447, in read_file_lines
    return f.readlines()
  File "/opt/conda/lib/python3.10/codecs.py", line 709, in readlines
    return self.reader.readlines(sizehint)
  File "/opt/conda/lib/python3.10/codecs.py", line 618, in readlines
    data = self.read()
  File "/opt/conda/lib/python3.10/codecs.py", line 496, in read
    newdata = self.stream.read()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
```

**Comment by Furkan-rgb** [comment]
Hey guys, can we have the "hide experiment list" toggle state saved in cache? So it doesn't reopen when you refresh the page?
![image](https://github.com/user-attachments/assets/91d2e71d-a53d-45bf-b259-161148684e10)

**Comment by raulcarlomagno** [comment]
hello!!!
one useful feature is to be able to group experiments in a folder, for example to be able to group them by project

**Comment by InAnYan** [comment]
Hi! I'm using MLflow to observe LlamaIndex Workflows.

IDK if anyone raised this, but I would really like MLflow to be able to show traces and other logs for in-progress apps.

For example, Arize Phoenix (I understand that Phoenix and MLflow may have different purposes/feature sets) supports this.

There is also an `MLFLOW_TRACE_TIMEOUT_SECONDS` environment variable (https://www.mlflow.org/docs/latest/tracing/faq#q-the-model-execution-gets-stuck-and-my-trace-is-in-progress-forever), but I find it a bit hard to use, as I have to apply this variable "inside" the program that needs observability (not in MLflow "server" or UI).

**Comment by chillerb** [comment]
Hi and thanks for maintaining mlflow! Not sure if this is the right place to post this, but I would love on-toggle log scaling for the metric charts. Depending on the loss, it's sometimes difficult to see if the model is still improving.

**Comment by hubertzub-db** [comment]
@JulesGM 
Thanks for the feedback! Drag-and-drop columns are in our backlog, can't guarantee any prioritization but it's on radar.

@chillerb 
You can enable log scale on chart's Y axis in the chart settings:

https://github.com/user-attachments/assets/0af71a70-bc21-448f-8bd9-d54a6c66eb47

**Comment by iampelle** [comment]
To keep the table of metrics more tidy, it would be nice to set number of decimals to round to, like you can in Exccel/Google sheets. Have all these decimals makes it harder to read and compare imo.

<img width="1834" height="702" alt="Image" src="https://github.com/user-attachments/assets/08026539-ec08-47cb-9440-4c5ae88fdfee" />

**Comment by ET-NoahDolev** [comment]
We need a better way to explore experiments - at least the last run dates, latest metric values, last updated etc, so we can sort and find runs within experiments. A long row of experiment names make finding things complex. Also, we might want to compare results from runs across different experiments.
