### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LukasLohm** [mlflow/mlflow#6401]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MS Azure on Databricks
- **Python version**:3.7.5
- **yarn version, if running the dev UI**:

### Describe the problem

I want to register my pyfunc model (XGb + Data Preprocessing) and get an error while starting the model serving process it fails and remains in the status pending.

Looking into the logs I saw that it says "ModuleNotFoundError: No module named 'xgboost'" even though i installed it in my notebook. Do I have to install something into my mlflow on databricks as well?

### Tracking information

MLflow version: 1.27.0
Tracking URI: databricks
Artifact URI: dbfs:/databricks/mlflow-tracking/123456789/123456789abcdefgh/artifacts

### Code to reproduce issue

```python
# Train the model and start the mlflow run to track, log and save model
import datetime as dt
from sklearn import preprocessing
import sklearn
from mlflow.models.signature import infer_signature
from mlflow.utils.environment import _mlflow_conda_env
import mlflow.pyfunc
import mlflow.sklearn
from sklearn.metrics import roc_auc_score
import cloudpickle
from xgboost import XGBClassifier
from sklearn import metrics

class ModelWrapper(mlflow.pyfunc.PythonModel):
    def __init__(self, model):
        super().__init__()
        self.model = model
    
    def predict(self, context, model_input):
        return self.model.predict_proba(model_input)[:,1]#, self.model.predict(model_input)
    
    def save_model(self, model_input):
        df = pd.read_json(model_input, orient = 'index')
        
        #convert strings to datetimes
        df['StartDate'] = pd.to_datetime(df['StartDate'], format="%m-%d-%Y")
        df['CancelDate'] = pd.to_datetime(df['CancelDate'], format="%m-%d-%Y", errors="coerce")
        df['LastServiceDate'] = pd.to_datetime(df['LastServiceDate'], format="%Y-%m-%d")
        
        #convert datetimes to numeric
        df['StartDate'] = df['StartDate'].map(dt.datetime.toordinal)
        df['CancelDate'] = df['CancelDate'].map(dt.datetime.toordinal)
        df['LastServiceDate'] = df['LastServiceDate'].map(dt.datetime.toordinal)
        
        #Convertin the predictor variable in a binary numeric variable
        df['Churned'].replace(to_replace='yes', value=1, inplace=True)
        df['Churned'].replace(to_replace='no',  value=0, inplace=True)
        df['Churned'] = pd.to_numeric(df['Churned'])
        
        #label encode categorical variables
        le = preprocessing.LabelEncoder()

        df['Territory'] = le.fit_transform(df['Territory'])
        df['Country'] = le.fit_transform(df['Country'])
        df['DeviceType'] = le.fit_transform(df['DeviceType'])
        df['HasRenewed'] = le.fit_transform(df['HasRenewed'])
        df['PlanType'] = le.fit_transform(df['PlanType'])
        df['StartMonth'] = le.fit_transform(df['StartMonth'])
        df['StartWeek'] = le.fit_transform(df['StartWeek'])
        df['Promotion'] = le.fit_transform(df['Promotion'])
        
        #convert id to int
        df['AccountID'] = df['AccountID'].str[2:]
        df['AccountID'] = pd.to_numeric(df['AccountID'])


with mlflow.start_run(experiment_id = experiment_id):
    model = XGBClassifier(learning_rate =learning_rate,
                          n_estimators=n_estimators,
                          max_depth=max_depth,
                          min_child_weight=min_child_weight,
                          gamma=gamma,
                          subsample=subsample,
                          colsample_bytree=colsample_bytree,)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    predsProba = model.predict_proba(X_test)
    Accuracy_Score = metrics.accuracy_score(y_test, preds)
    auc_score = roc_auc_score(y_test, preds)
    wrappedModel = ModelWrapper(model)
    
    # Log the model with a signature that defines the schema of the model's inputs and outputs. 
    # When the model is deployed, this signature will be used to validate inputs.
    signature = infer_signature(X_train, wrappedModel.predict(None, X_train))
    
    #log mlflow objects
    mlflow.log_metric("AUC", auc_score)
    mlflow.log_metric("Accuracy Score", Accuracy_Score)
    mlflow.log_param("learning_rate", learning_rate)
    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)
    mlflow.log_param("min_child_weight", min_child_weight)
    mlflow.log_param("gamma", gamma)
    mlflow.log_param("subsample", subsample)
    mlflow.log_param("colsample_bytree", colsample_bytree)
    
    #save the conda version and necessary dependencies
    conda_env =  _mlflow_conda_env(
        additional_conda_deps=None,
        additional_pip_deps=["cloudpickle=={}".format(cloudpickle.__version__), "scikit-learn=={}".format(sklearn.__version__)],
        additional_conda_channels=None,
    )
    
    mlflow.pyfunc.log_model("XG_Boost", python_model=wrappedModel, conda_env=conda_env, signature=signature)
    
    #mlflow.sklearn.log_model(model, "model")
    modelpath = "/Users/kcz@qlik.com/mlflow/Model22"
    #mlflow.sklearn.save_model(model, modelpath)```

### Stack trace

[2022-08-04 07:52:17 +0000] [22889] [INFO] Shutting down: Master
[2022-08-04 07:52:17 +0000] [22889] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/databricks/conda/envs/model-7/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/mlflow/models/cli.py", line 71, in serve
    model_uri=model_uri, port=port, host=host, timeout=timeout, enable_mlserver=enable_mlserver
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 263, in serve
    command, rc
Exception: Command '['bash', '-c', 'exec gunicorn --timeout=60 -b unix:/tmp/7.sock:1 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app']' returned non zero return code. Return code = 3
Thu Aug  4 07:52:26 UTC 2022
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

### Other info / logs

] Worker with pid 22895 was terminated due to signal 15
[2022-08-04 07:52:17 +0000] [22889] [INFO] Shutting down: Master
[2022-08-04 07:52:17 +0000] [22889] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/databricks/conda/envs/model-7/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/mlflow/models/cli.py", line 71, in serve
    model_uri=model_uri, port=port, host=host, timeout=timeout, enable_mlserver=enable_mlserver
  File "/databricks/conda/envs/model-7/lib/python3.7/site-packages/mlflow/pyfunc/backend.py", line 263, in serve
    command, rc
Exception: Command '['bash', '-c', 'exec gunicorn --timeout=60 -b unix:/tmp/7.sock:1 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app']' returned non zero return code. Return code = 3
Thu Aug  4 07:52:26 UTC 2022
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/databricks/chauffeur/model-runner/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'westeurope-c2.azuredatabricks.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Ran pip subprocess with arguments:
['/databricks/conda/envs/model-7/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/tmpqdnznv7_/XG_Boost/condaenv.j4wyncaw.requirements.txt']
Pip subprocess output:
Collecting mlflow
  Using cached mlflow-1.27.0-py3-none-any.whl (17.9 MB)
Collecting cloudpickle==2.1.0
  Using cached cloudpickle-2.1.0-py3-none-any.whl (25 kB)
Collecting scikit-learn==0.22.1
  Using cached scikit_learn-0.22.1-cp37-cp37m-manylinux1_x86_64.whl (7.0 MB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting querystring-parser
  Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Collecting pytz
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting protobuf>=3.12.0
  Using cached protobuf-4.21.4-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
Collecting sqlalchemy>=1.4.0
  Using cached SQLAlchemy-1.4.39-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting prometheus-flask-exporter
  Using cached prometheus_flask_exporter-0.20.3-py3-none-any.whl (18 kB)
Collecting alembic
  Using cached alembic-1.8.1-py3-none-any.whl (209 kB)
Collecting docker>=4.0.0
  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
Processing /root/.cache/pip/wheels/55/c3/db/33705569425fd2bdc9ea73051a8053fa26965c2bce8a146747/databricks_cli-0.17.0-py3-none-any.whl
Collecting gitpython>=2.1.0
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
Collecting Flask
  Using cached Flask-2.2.1-py3-none-any.whl (101 kB)
Collecting sqlparse>=0.3.1
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Collecting pandas
  Using cached pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting gunicorn; platform_system != "Windows"
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting importlib-metadata!=4.7.0,>=3.7.0
  Using cached importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
Collecting requests>=2.17.3
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))
  Using cached greenlet-1.1.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (150 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.14.1-py3-none-any.whl (59 kB)
Collecting importlib-resources; python_version < "3.9"
  Using cached importlib_resources-5.9.0-py3-none-any.whl (33 kB)
Collecting Mako
  Using cached Mako-1.2.1-py3-none-any.whl (78 kB)
Collecting websocket-client>=0.32.0
  Using cached websocket_client-1.3.3-py3-none-any.whl (54 kB)
Collecting pyjwt>=1.7.0
  Using cached PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting tabulate>=0.7.7
  Using cached tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting oauthlib>=3.1.0
  Using cached oauthlib-3.2.0-py3-none-any.whl (151 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting typing-extensions>=3.7.4.3; python_version < "3.8"
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Werkzeug>=2.2.0
  Using cached Werkzeug-2.2.1-py3-none-any.whl (232 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied, skipping upgrade: setuptools>=3.0 in /databricks/conda/envs/model-7/lib/python3.7/site-packages (from gunicorn; platform_system != "Windows"->mlflow->-r /tmp/tmpqdnznv7_/XG_Boost/condaenv.j4wyncaw.requirements.txt (line 1)) (63.3.0)
Collecting zipp>=0.5
  Using cached zipp-3.8.1-py3-none-any.whl (5.6 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-2.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Installing collected packages: entrypoints, six, querystring-parser, pytz, numpy, protobuf, typing-extensions, zipp, importlib-metadata, greenlet, sqlalchemy, itsdangerous, click, MarkupSafe, Werkzeug, Jinja2, Flask, prometheus-client, prometheus-flask-exporter, importlib-resources, Mako, alembic, websocket-client, urllib3, certifi, charset-normalizer, idna, requests, docker, cloudpickle, pyjwt, tabulate, oauthlib, databricks-cli, smmap, gitdb, gitpython, pyyaml, sqlparse, python-dateutil, pandas, pyparsing, packaging, scipy, gunicorn, mlflow, joblib, scikit-learn
Successfully installed Flask-2.2.1 Jinja2-3.1.2 Mako-1.2.1 MarkupSafe-2.1.1 Werkzeug-2.2.1 alembic-1.8.1 certifi-2022.6.15 charset-normalizer-2.1.0 click-8.1.3 cloudpickle-2.1.0 databricks-cli-0.17.0 docker-5.0.3 entrypoints-0.4 gitdb-4.0.9 gitpython-3.1.27 greenlet-1.1.2 gunicorn-20.1.0 idna-3.3 importlib-metadata-4.12.0 importlib-resources-5.9.0 itsdangerous-2.1.2 joblib-1.1.0 mlflow-1.27.0 numpy-1.21.6 oauthlib-3.2.0 packaging-21.3 pandas-1.3.5 prometheus-client-0.14.1 prometheus-flask-exporter-0.20.3 protobuf-4.21.4 pyjwt-2.4.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.1 pyyaml-6.0 querystring-parser-1.2.4 requests-2.28.1 scikit-learn-0.22.1 scipy-1.7.3 six-1.16.0 smmap-5.0.0 sqlalchemy-1.4.39 sqlparse-0.4.2 tabulate-0.8.10 typing-extensions-4.3.0 urllib3-1.26.11 websocket-client-1.3.3 zipp-3.8.1


### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @LukasLohm, the issue appears to be that your model environment does not specify the `xgboost` dependency. This is happening because the `conda_env` that you're passing to `mlflow.pyfunc.log_model()` does not contain `xgboost`. I recommend removing `conda_env` when calling `mlflow.pyfunc.log_model()`; MLflow will automatically infer which dependencies are necessary for the model to run and will add them to the model's environment. If this is not working, please let me know; alternatively, you can add `xgboost` to the list of `additional_pip_deps` passed to `_mlflow_conda_env` if you still wish to specify a `conda_env`. Thank you for using MLflow!

**Comment by LukasLohm** [comment]
thank you @dbczumar ! :)
