### ISSUE TITLE
[BUG] mlflow models predict SyntaxError on Windows

### ISSUE THREAD

**Issue by amymsft** [mlflow/mlflow#6427]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 
- **Python version**: 3.9.10
- **yarn version, if running the dev UI**:

### Describe the problem

`mlflow models predict` hits a `SyntaxError: EOL while scanning string literal` in Windows using Anaconda Prompt. But if I run the command it prints out from the log: "mlflow.pyfunc.backend === Running command ..........", that command works. 
![image](https://user-images.githubusercontent.com/94562419/183718591-820fa9fd-19ad-46e2-90f4-54787c1342f3.png)

Success when not using `mlflow models predict`
![image](https://user-images.githubusercontent.com/94562419/183719489-84995d67-fa69-49a3-9fea-b7a46f852bf0.png)

### Code to reproduce issue

```python
mlflow models predict ... # Windows Anaconda Prompt
```

### Stack trace

```python
(localbea) C:\Users\amymsft\Job_boring_plate_0vswtx3l_OutputsAndLogs\aml-batch-endpoint-mlflow\localbea>mlflow models predict --model-uri ./modelbeaclone --input-path c:/users/amymsft/source/datasets/fashionmnist/q*.csv --content-type csv
C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2022/08/09 10:19:16 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/08/09 10:19:20 INFO mlflow.utils.conda: Conda environment mlflow-59f9751ca71c55c6992f804aa7c1774fc8903b7d already exists.
2022/08/09 10:19:20 INFO mlflow.pyfunc.backend: === Running command 'conda activate mlflow-59f9751ca71c55c6992f804aa7c1774fc8903b7d & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/amymsft/Job_boring_plate_0vswtx3l_OutputsAndLogs/aml-batch-endpoint-mlflow/localbea/modelbeaclone', input_path='c:/users/amymsft/source/datasets/fashionmnist\\quicky_indexFalse.csv', output_path=None, content_type='csv', json_format='split')"'
  File "<string>", line 1
    "from
         ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "C:\Users\amymsft\.conda\envs\localbea\Scripts\mlflow-script.py", line 10, in <module>
    sys.exit(cli())
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\mlflow\models\cli.py", line 125, in predict
    return _get_flavor_backend(
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\mlflow\pyfunc\backend.py", line 126, in predict
    return _execute_in_conda_env(
  File "C:\Users\amymsft\.conda\envs\localbea\lib\site-packages\mlflow\pyfunc\backend.py", line 389, in _execute_in_conda_env
    raise Exception(
Exception: Command 'conda activate mlflow-59f9751ca71c55c6992f804aa7c1774fc8903b7d & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/amymsft/Job_boring_plate_0vswtx3l_OutputsAndLogs/aml-batch-endpoint-mlflow/localbea/modelbeaclone', input_path='c:/users/amymsft/source/datasets/fashionmnist\\quicky_indexFalse.csv', output_path=None, content_type='csv', json_format='split')"' returned non zero return code. Return code = 1
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@amymsft I'm unfortunately unable to reproduce the issue locally. If possible, do you have any additional information about the file in which this syntax error occurs?

**Comment by B-Step62** [comment]
This is a Windows conda command-quoting issue on MLflow 1.26; `virtualenv` is now the default env manager and the predict CLI has changed substantially since. Closing as not reproducible, feel free to reopen if it recurs on a current version.
