### ISSUE TITLE
[BUG]Blocked a frame with origin "http://127.0.0.1:5000" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by Euraxluo** [mlflow/mlflow#6434]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows
- **Python version**: python3.9
- **yarn version, if running the dev UI**:

### Describe the problem

AppErrorBoundary.js:19 DOMException: Blocked a frame with origin "http://127.0.0.1:5000" from accessing a cross-origin frame.
    at Function.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:4837071)
    at n.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:6358085)
    at vs (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2610200)
    at Dl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2627080)
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594)
    at Ko (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2568947)
    at Nl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2623815)
    at bl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2619901)
    at http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2569170
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594) Object

### Steps to reproduce the bug

1. `mlflow ui`
2. open index.html:
all code:
 ```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<iframe src="http://127.0.0.1:5000/", height="1920", width="1080"></iframe>
</body>
</html>
```

### Code to generate data required to reproduce the bug

![image](https://user-images.githubusercontent.com/34028978/183851965-5c3d5048-bb70-40fe-b439-f292e6c350f2.png)
![image](https://user-images.githubusercontent.com/34028978/183851989-0c7b5b10-73bc-4884-ada9-723bf4e00951.png)
![image](https://user-images.githubusercontent.com/34028978/183852051-3a942bfe-fb0a-4804-beaa-7e4c4a11e3fd.png)

### Is the console panel in DevTools showing errors relevant to the bug?

react-dom.production.min.js:216 DOMException: Blocked a frame with origin "http://127.0.0.1:5000" from accessing a cross-origin frame.
    at Function.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:4837071)
    at n.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:6358085)
    at vs (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2610200)
    at Dl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2627080)
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594)
    at Ko (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2568947)
    at Nl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2623815)
    at bl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2619901)
    at http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2569170
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594)
cs @ react-dom.production.min.js:216
AppErrorBoundary.js:19 DOMException: Blocked a frame with origin "http://127.0.0.1:5000" from accessing a cross-origin frame.
    at Function.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:4837071)
    at n.value (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:6358085)
    at vs (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2610200)
    at Dl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2627080)
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594)
    at Ko (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2568947)
    at Nl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2623815)
    at bl (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2619901)
    at http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:2569170
    at t.unstable_runWithPriority (http://127.0.0.1:5000/static-files/static/js/main.97f0d444.js:2:3481594) Object

### Does the network panel in DevTools contain failed requests relevant to the bug?

![image](https://user-images.githubusercontent.com/34028978/183852226-3e30e5a0-0393-40ad-bd33-ac73c416ed80.png)

**Comment by dbczumar** [comment]
Hi @Euraxluo, cross-origin iframe embedding isn't supported; see https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame. Can you try changing the port to `3000` from `5000`?

**Comment by Euraxluo** [comment]
i use K8S ingress  Solved cross -domain problems

**Comment by cfregly** [comment]
@Euraxluo Can you share how you solved the cross-domain problem in this case, specifically?

**Comment by jmahlik** [comment]
> @Euraxluo Can you share how you solved the cross-domain problem in this case, specifically?

If you're referencing the problem with cors running mlflow behind a k8's nginx ingress controller with `networking.k8s.io/v1`. 

Adding the annotation `nginx.ingress.kubernetes.io/enable-cors: "true"` seems to get around the cors issue with serving static files. Additional annotations might be needed if the defaults this turns on don't work for you.

https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#enable-cors

**Comment by evanbung** [comment]
This error "Blocked a frame with origin from accessing a cross-origin frame" is not a bug. The same-origin policy is a security mechanism that ensures that window objects only have access to the informations they are authorized to get. To fix this issue, ensure that both the parent page and the iframe content are served from the same domain or implement Cross-Origin Communication techniques such as postMessage to safely communicate and exchange data between the two frames. 

The window.postMessage() method provides a controlled mechanism to securely circumvent this [Same-Origin Policy](https://net-informations.com/js/err/sop.htm) restriction. The window.postMessage() safely enables cross-origin communication between Window objects; e.g: between a page and an iframe embedded within it.

postMessage(message, targetOrigin)
postMessage(message, targetOrigin, [transfer])

targetOrigin - specifies what the origin of targetWindow must be for the event to be dispatched, either as the literal string "*" (indicating no preference) or as a URI.

If you don't have control over the content in the iframe, you won't be able to directly access its elements due to security restrictions.
