### ISSUE TITLE
[BUG] Error loading Pyspark model from databricks connect

### ISSUE THREAD

**Issue by CarlaFernandez** [mlflow/mlflow#6625]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.1

### System information

- Windows 10 Pro, Version 21H2, OS compilation 19044.1889, Windows Feature Experience Pack 120.2212.4180.0
- Python 3.8
- Databricks cluster  runtime: 9.1 LTS ML (includes Apache Spark 3.1.2, Scala 2.12)
- Databricks Connect version 9.1.16
- Pyspark version: 3.1

### Describe the problem

I'm using Databricks Connect version 9.1.16 to connect to a databricks external cluster and download a Pyspark ML pipeline that's been trained and saved using mlflow.

The `code to reproduce` works when executed from a Databricks notebook (and provided the real model uri), but fail when executed from my local machine via databricks connect. And I get the same error on any model I want to load.

### Code to reproduce issue

```python
import mlflow
mlflow.set_tracking_uri("databricks")
model = mlflow.spark.load_model(model_uri="models:/model_name/model_version")
```

### Stack trace

```python
2022/08/26 11:54:18 INFO mlflow.spark: 'models:/model_name/model_version' resolved as 'dbfs://databricks/databricks/mlflow-registry/model_id/models/model'
2022/08/26 11:54:25 INFO mlflow.spark: URI 'dbfs://databricks/databricks/mlflow-registry/model_id/models/model/sparkml' does not point to the current DFS.
2022/08/26 11:54:25 INFO mlflow.spark: File 'dbfs://databricks/databricks/mlflow-registry/model_id/models/model/sparkml' not found on DFS. Will attempt to upload the file.
2022/08/26 11:55:06 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/model_id
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
c:\Users\carlafernandez\Documents\my_notebook.ipynb Celda 5 in <cell line: 2>()
      1 mlflow.set_tracking_uri("databricks")
----> 2 model_h = mlflow.spark.load_model(model_uri="models:/model_name/model_version")

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\mlflow\spark.py:711, in load_model(model_uri, dfs_tmpdir)
    708 local_model_path = _download_artifact_from_uri(model_uri)
    709 _add_code_from_conf_to_system_path(local_model_path, flavor_conf)
--> 711 return _load_model(model_uri=model_uri, dfs_tmpdir_base=dfs_tmpdir)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\mlflow\spark.py:660, in _load_model(model_uri, dfs_tmpdir_base)
    658     return _load_model_databricks(model_uri, dfs_tmpdir)
    659 model_uri = _HadoopFileSystem.maybe_copy_from_uri(model_uri, dfs_tmpdir)
--> 660 return PipelineModel.load(model_uri)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\pyspark\ml\util.py:463, in MLReadable.load(cls, path)
    460 @classmethod
    461 def load(cls, path):
    462     """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 463     return cls.read().load(path)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\pyspark\ml\pipeline.py:258, in PipelineModelReader.load(self, path)
    256 metadata = DefaultParamsReader.loadMetadata(path, self.sc)
    257 if 'language' not in metadata['paramMap'] or metadata['paramMap']['language'] != 'Python':
--> 258     return JavaMLReader(self.cls).load(path)
    259 else:
    260     uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\pyspark\ml\util.py:413, in JavaMLReader.load(self, path)
    411 if not isinstance(path, str):
    412     raise TypeError("path should be a string, got type %s" % type(path))
--> 413 java_obj = self._jread.load(path)
    414 if not hasattr(self._clazz, "_from_java"):
    415     raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"
    416                               % self._clazz)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\py4j\java_gateway.py:1304, in JavaMember.__call__(self, *args)
   1298 command = proto.CALL_COMMAND_NAME +\
   1299     self.command_header +\
   1300     args_command +\
   1301     proto.END_COMMAND_PART
   1303 answer = self.gateway_client.send_command(command)
-> 1304 return_value = get_return_value(
   1305     answer, self.gateway_client, self.target_id, self.name)
   1307 for temp_arg in temp_args:
   1308     temp_arg._detach()

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\pyspark\sql\utils.py:117, in capture_sql_exception.<locals>.deco(*a, **kw)
    115 def deco(*a, **kw):
    116     try:
--> 117         return f(*a, **kw)
    118     except py4j.protocol.Py4JJavaError as e:
    119         converted = convert_exception(e.java_exception)

File c:\Users\carlafernandez\miniconda3\envs\prueba_databricks_connect\lib\site-packages\py4j\protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o645.load.
: java.io.StreamCorruptedException: invalid type code: 00
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1698)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
    at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:488)
    at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2093)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1655)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2093)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1655)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
    at org.apache.spark.sql.util.ProtoSerializer.$anonfun$deserializeObject$1(ProtoSerializer.scala:6631)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at org.apache.spark.sql.util.ProtoSerializer.deserializeObject(ProtoSerializer.scala:6616)
    at com.databricks.service.SparkServiceRPCHandler.execute0(SparkServiceRPCHandler.scala:728)
    at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC0$1(SparkServiceRPCHandler.scala:477)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:372)
    at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:323)
    at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:309)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC$1(SparkServiceRPCHandler.scala:359)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:336)
    at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:167)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
    at org.eclipse.jetty.server.Server.handle(Server.java:516)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
    at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
    at java.lang.Thread.run(Thread.java:748)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I guess this issue is because of local installed spark client has different version with the remote connected cluster.

**Comment by CarlaFernandez** [comment]
Thanks @dbczumar , I will try, but it might take a bit since I don't currently have permissions to create or modify clusters.

@WeichenXu123 I do have a different pyspark version in my local machine than required (3.2.2 vs 3.1 which is required by databricks runtime 9.1), but it's on a different virtual environment. In the venv where I use databricks-connect I don't have pyspark installed. Do you think it might affect anyway?

**Comment by CarlaFernandez** [comment]
@WeichenXu123 thanks, basically, the parsing and planning of the job runs on your local machine. Then, the logical representation of the job is sent to the Spark server running in Databricks for execution in the cluster. That's why you don't actually shouldn't have pyspark installed in the same environment as databricks-connect. I've tried downgrading my (other) pyspark to match the version in the Databricks runtime, but still doesn't work.

@dbczumar I'm just now reading the Databricks Connect documentation (https://docs.databricks.com/dev-tools/databricks-connect.html) and apparently Databricks Runtime 11 is not yet supported:

![image](https://user-images.githubusercontent.com/9136877/187883103-ec4144a0-ec1f-47b6-b599-d7d21bebc7a6.png)

So I don't think I'll be able to try what you propose, since my error occurs specifically only through databricks-connect. Any other ideas? Thank you very much

**Comment by WeichenXu123** [comment]
OK. I suggest you file a databricks ES ticket, it looks like pyspark py4j issues. I am not familiar with databricks-connect.

**Comment by CarlaFernandez** [comment]
Will do, thanks!

**Comment by Isarien** [comment]
@CarlaFernandez Did you solve your problem.
I have the same problem, only with pyspark model. sklearn model are corectly loaded

**Comment by CarlaFernandez** [comment]
Hi, actually we didn't file a databricks ticket in the end. We ended up executing the parts of the code that require loading such  models from notebooks and/or jobs instead of using databricks-connect. Perhaps you can also try executing it via the new [databricks extension for VS code ](https://docs.databricks.com/dev-tools/vscode-ext.html) and see if it's fixed there?

**Comment by codebydant** [comment]
Same problem with 

```bash
databricks-connect==9.1.34
databricks-connect==9.1.33
databricks-connect==9.1.30
```

When running 

```python

from pyspark.ml.clustering import KMeans

kmeans = self.KMeans().setK(3).setSeed(1)
kmeans.fit(data)
```

## Error

```bash
Traceback (most recent call last):
  File "/home/user/Downloads/repo/src/services/src/clustering.py", line 25, in fit
    self.model = kmeans.fit(data)
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/pyspark/ml/base.py", line 161, in fit
    return self._fit(dataset)
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/pyspark/ml/wrapper.py", line 339, in _fit
    java_model = self._fit_java(dataset)
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/pyspark/ml/wrapper.py", line 336, in _fit_java
    return self._java_obj.fit(dataset._jdf)
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/pyspark/sql/utils.py", line 117, in deco
    return f(*a, **kw)
  File "/home/user/Downloads/repo/venv/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o63.fit.
: java.io.StreamCorruptedException: invalid type code: 0B
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2119)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1657)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.sql.util.ProtoSerializer.$anonfun$deserializeObject$1(ProtoSerializer.scala:6631)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeObject(ProtoSerializer.scala:6616)
	at com.databricks.service.SparkServiceRPCHandler.execute0(SparkServiceRPCHandler.scala:728)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC0$1(SparkServiceRPCHandler.scala:477)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:372)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:323)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:309)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC$1(SparkServiceRPCHandler.scala:359)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:336)
	at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:167)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:750)

```

This works in a notebook in databricks

**Comment by B-Step62** [comment]
This is specific to loading a Spark model over databricks-connect on an old runtime and is not reproducible against current MLflow. Closing, feel free to reopen with a reproducible example on a current version.
