### ISSUE TITLE
[BUG] Default model evaluator cannot log TreeEnsemble shap explainer

### ISSUE THREAD

**Issue by jerrylian-db** [mlflow/mlflow#6771]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

latest master - commit: f65429478255b88a211d7dd262c159b4939b44b2

### System information

Databricks MLR 11.X

### Describe the problem

I ran the [model validation example](https://github.com/mlflow/mlflow/blob/master/examples/evaluation/evaluate_with_model_validation.py) off of the latest master. The Tree shap explainer failed to be logged. See screenshot below:

<img width="1688" alt="Screen Shot 2022-09-12 at 7 25 44 PM" src="https://user-images.githubusercontent.com/66143562/189793641-66c6dde0-9f9d-4f0f-bbe1-e20acaa16093.png">

### Code to reproduce issue

import xgboost
import shap
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
import mlflow
from mlflow.models import MetricThreshold
from mlflow.models.evaluation.validation import ModelValidationFailedException

# load UCI Adult Data Set; segment it into training and test sets
X, y = shap.datasets.adult()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# train a candidate XGBoost model
candidate_model = xgboost.XGBClassifier().fit(X_train, y_train)

# train a baseline dummy model
baseline_model = DummyClassifier(strategy="uniform").fit(X_train, y_train)

# construct an evaluation dataset from the test set
eval_data = X_test
eval_data["label"] = y_test

# Define a custom metric to evaluate against
def double_positive(_, builtin_metrics):
    return {
        "double_positive": builtin_metrics["true_positives"] * 2,
    }

# Define criteria for model to be validated against
thresholds = {
    # Specify metric value threshold
    "precision_score": MetricThreshold(
        threshold=0.7, higher_is_better=True
    ),  # precision should be >=0.7
    # Specify model comparison thresholds
    "recall_score": MetricThreshold(
        min_absolute_change=0.1,  # recall should be at least 0.1 greater than baseline model recall
        min_relative_change=0.1,  # recall should be at least 10 percent greater than baseline model recall
        higher_is_better=True,
    ),
    # Specify both metric value and model comparison thresholds
    "accuracy_score": MetricThreshold(
        threshold=0.8,  # accuracy should be >=0.8
        min_absolute_change=0.05,  # accuracy should be at least 0.05 greater than baseline model accuracy
        min_relative_change=0.05,  # accuracy should be at least 5 percent greater than baseline model accuracy
        higher_is_better=True,
    ),
    # Specify threshold for custom metric
    "double_positive": MetricThreshold(
        threshold=1e5, higher_is_better=False  # double_positive should be <=1e5
    ),
}

with mlflow.start_run() as run:
    candidate_model_uri = mlflow.sklearn.log_model(candidate_model, "candidate_model").model_uri
    # Note: in most model validation use-cases the baseline model should instead be a previously
    # trained model (such as the current production model), specified directly in the
    # mlflow.evaluate() call via model URI.
    baseline_model_uri = mlflow.sklearn.log_model(baseline_model, "baseline_model").model_uri

    mlflow.evaluate(
        candidate_model_uri,
        eval_data,
        targets="label",
        model_type="classifier",
        dataset_name="adult",
        evaluators=["default"],
        validation_thresholds=thresholds,
        custom_metrics=[double_positive],
        baseline_model=baseline_model_uri,
    )
    # If you would like to catch model validation failures, you can add try except clauses around
    # the mlflow.evaluate() call and catch the ModelValidationFailedException, imported at the top
    # of this file.

### Stack trace

Full trace back:
```
2022/09/13 02:27:06 WARNING mlflow.models.evaluation.default_evaluator: Logging explainer failed. Reason: AttributeError("'TreeEnsemble' object has no attribute 'save'").Set logging level to DEBUG to see the full traceback.
2022/09/13 02:27:06 DEBUG mlflow.models.evaluation.default_evaluator: 
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4113bd0b-94f3-4aa5-9ee2-47edf7480f42/lib/python3.9/site-packages/mlflow/models/evaluation/default_evaluator.py", line 665, in _log_model_explainability
    mlflow.shap.log_explainer(explainer, artifact_path=self._gen_log_key("explainer"))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4113bd0b-94f3-4aa5-9ee2-47edf7480f42/lib/python3.9/site-packages/mlflow/shap.py", line 351, in log_explainer
    Model.log(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4113bd0b-94f3-4aa5-9ee2-47edf7480f42/lib/python3.9/site-packages/mlflow/models/model.py", line 372, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4113bd0b-94f3-4aa5-9ee2-47edf7480f42/lib/python3.9/site-packages/mlflow/shap.py", line 464, in save_explainer
    explainer.save(explainer_output_file_handle)
  File "/databricks/python/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 419, in save
    s.save("model", self.model, model_saver)
  File "/databricks/python/lib/python3.9/site-packages/shap/_serializable.py", line 87, in save
    if len(inspect.getfullargspec(value.save)[0]) == 3: # backward compat for MLflow, can remove 4/1/2021
AttributeError: 'TreeEnsemble' object has no attribute 'save'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Seems related to https://github.com/slundberg/shap/issues/2122.

**Comment by aljabadi** [comment]
Facing the same issue using `mlflow==2.1.1`

**Comment by natasha-savic-msft** [comment]
Facing same issue with MLFlow: https://mlflow.org/docs/latest/python_api/mlflow.shap.html#mlflow.shap.log_explainer .

I cannot automate the shap explainer pipeline with MLFlow :(

**Comment by macari-dev** [comment]
Any news about this issue?

**Comment by aviralsharma2021** [comment]
Is this issue solved? I am facing the same trying to log KernelExplainer

**Comment by jacesca** [comment]
Here, I am facing the same error. Do we have an expected date to be solved?

**Comment by liyenhsu** [comment]
Hi, I'm also getting the same error with the latest mlflow version 2.14.1

**Comment by manuelgilm** [comment]
Hi, I am facing the same issue with mlflow version = "2.15.1" (latest)

**Comment by DaniBrkr** [comment]
The SHAP GradientExplainer seems to suffer from a similar issue in 2.17.1
`'GradientExplainer' object has no attribute 'model'` when using mlflow.shap.log_explainer()

**Comment by chamaoskurumi** [comment]
2.17.2 with the same `WARNING mlflow.models.evaluation.default_evaluator: Logging explainer failed.`
