### ISSUE TITLE
[BUG] keras.log_model tensorflow_probabilistic raises an error

### ISSUE THREAD

**Issue by forons** [mlflow/mlflow#6873]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26.0

### System information

- MacOS Monterey with M1 Chip
- 3.8.13

### Describe the problem

I have a keras model that has a tfp.layers.DistributionLambda(tfd.Poisson)(input) (https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DistributionLambda, https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Poisson for reference).

In order to store the model locally, I save it just by doing: `model.save(destination_path)`.
Then, to load it, I simply do: 
```
import keras
import tensorflow as tf
keras.models.load_model(file_path, compile=False, custom_objects={'exp': tf.exp})
```

Instead, when I try to log it to mlflow by doing: `mlflow.keras.log_model(keras_model, path)` I get the following error:
```
Traceback (most recent call last):
  File "/Users/user/dev/project/src/utils/mlflow_utils.py", line 54, in log
    model_info = mlflow.keras.log_model(model, 'model', keras_module=keras, custom_objects={'exp': tf.exp})
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py", line 416, in log_model
    return Model.log(
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/models/model.py", line 294, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py", line 268, in save_model
    keras_model.save(model_path, **kwargs)
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py", line 224, in __call__
    distribution, _ = super(DistributionLambda, self).__call__(
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: Iterating over a symbolic `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
python-BaseException
```

I also tried by adding the `custom_objects` parameter (so by doing `mlflow.keras.log_model(keras_model, path, custom_objects={'exp': tf.exp})`, but I still get the same error.

Could you please help me?

### Code to reproduce issue

```python

import mlflow
import tensorflow as tf
import tensorflow_probability as tfp
from sklearn.datasets import load_iris

tfd = tfp.distributions

X, y = load_iris(return_X_y=True)

inputs = tf.keras.layers.Input(shape=(X.shape[1],))
x = tf.keras.layers.Dense(30, "relu")(inputs)
output = tf.keras.layers.Dense(1, activation=tf.exp)(x)
p_y = tfp.layers.DistributionLambda(tfd.Poisson)(output)
model = tf.keras.Model(inputs=inputs, outputs=p_y)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)

def nll(y_true, y_pred):
    return -y_pred.log_prob(y_true)

model.compile(optimizer, loss=nll)
model.fit(x=X.astype(float), y=y.astype(float), epochs=5)


active_experiment = "active-custom-experiment"
mlflow.set_experiment(active_experiment)
with mlflow.start_run():
    mlflow.keras.log_model(model, "model")

### Stack trace

```
---------------------------------------------------------------------------
OperatorNotAllowedInGraphError            Traceback (most recent call last)
Input In [25], in <cell line: 2>()
      1 mlflow.set_experiment(active_experiment)
      2 with mlflow.start_run():
----> 3     mlflow.keras.log_model(model, 'model')

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py:416, in log_model(keras_model, artifact_path, conda_env, code_paths, custom_objects, keras_module, registered_model_name, signature, input_example, await_registration_for, pip_requirements, extra_pip_requirements, **kwargs)
    404 if signature is not None:
    405     warnings.warn(
    406         "The pyfunc inference behavior of Keras models logged "
    407         "with signatures differs from the behavior of Keras "
   (...)
    414         "a Pandas DataFrame output in response to a Pandas DataFrame input."
    415     )
--> 416 return Model.log(
    417     artifact_path=artifact_path,
    418     flavor=mlflow.keras,
    419     keras_model=keras_model,
    420     conda_env=conda_env,
    421     code_paths=code_paths,
    422     custom_objects=custom_objects,
    423     keras_module=keras_module,
    424     registered_model_name=registered_model_name,
    425     signature=signature,
    426     input_example=input_example,
    427     await_registration_for=await_registration_for,
    428     pip_requirements=pip_requirements,
    429     extra_pip_requirements=extra_pip_requirements,
    430     **kwargs,
    431 )

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/models/model.py:294, in Model.log(cls, artifact_path, flavor, registered_model_name, await_registration_for, **kwargs)
    292 run_id = mlflow.tracking.fluent._get_or_start_run().info.run_id
    293 mlflow_model = cls(artifact_path=artifact_path, run_id=run_id)
--> 294 flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
    295 mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
    296 try:

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py:268, in save_model(keras_model, path, conda_env, code_paths, mlflow_model, custom_objects, keras_module, signature, input_example, pip_requirements, extra_pip_requirements, **kwargs)
    266         shutil.copyfile(src=f.name, dst=model_path)
    267 else:
--> 268     keras_model.save(model_path, **kwargs)
    270 # update flavor info to mlflow_model
    271 mlflow_model.add_flavor(
    272     FLAVOR_NAME,
    273     keras_module=keras_module.__name__,
   (...)
    277     code=code_dir_subpath,
    278 )

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~/miniforge3/envs/py38/lib/python3.8/contextlib.py:120, in _GeneratorContextManager.__exit__(self, type, value, traceback)
    118 if type is None:
    119     try:
--> 120         next(self.gen)
    121     except StopIteration:
    122         return False

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py:224, in DistributionLambda.__call__(self, inputs, *args, **kwargs)
    222 def __call__(self, inputs, *args, **kwargs):
    223   self._enter_dunder_call = True
--> 224   distribution, _ = super(DistributionLambda, self).__call__(
    225       inputs, *args, **kwargs)
    226   self._enter_dunder_call = False
    227   return distribution

OperatorNotAllowedInGraphError: Iterating over a symbolic `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Additional types were added in recent releases. Could you try using MLflow 1.29.0?

**Comment by forons** [comment]
Yes, I tried, but the output unfortunately is still the same.

**Comment by BenWilson2** [comment]
Ah, my apologies on asking you to test this. 
What you might want to try is to utilize the `custom_objects` argument in logging in the exact manner that you did when saving in native Keras format. 
See the following test for an example: https://github.com/mlflow/mlflow/blob/3f92b645b668e06764bb8ad3c8d1e5ceeb4d97ce/tests/keras/test_keras_model_export.py#L353-L368

**Comment by forons** [comment]
What exactly is the `custom_layer` that the function is taking as argument?

**Comment by BenWilson2** [comment]
This https://github.com/mlflow/mlflow/blob/3f92b645b668e06764bb8ad3c8d1e5ceeb4d97ce/tests/keras/test_keras_model_export.py#L133-L159

**Comment by forons** [comment]
Yes, I confirm that in the custom_objects dictionary I am not passing as value the instance of the class, but it's reference, as you are showing in the example.

**Comment by BenWilson2** [comment]
In your example:
```
active_experiment = "active-custom-experiment"
mlflow.set_experiment(active_experiment)
with mlflow.start_run():
    mlflow.keras.log_model(model, "model")
```
you're not passing a dict to `custom_objects` in `mlflow.keras.log_model()`. Are you saying that you tried that and it's throwing the iterable exception?

**Comment by forons** [comment]
By running this code:
```
active_experiment = "active-custom-experiment"
mlflow.set_experiment(active_experiment)
with mlflow.start_run():
    mlflow.keras.log_model(model, "model", custom_objects={'exp': tf.exp, 'DistributionLambda': tfp.layers.DistributionLambda})
```
The error thrown is the same:
`OperatorNotAllowedInGraphError: Iterating over a symbolic `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

**Comment by BenWilson2** [comment]
Thinking out loud here... is it the loss function that needs to be passed? 
Could you try decorating that function with `@tf.function` and then passing the ref to that function to the custom_objects?

**Comment by forons** [comment]
By decorating that function with `@tf.function` and running `mlflow.keras.log_model(model, "model", custom_objects={'exp': tf.exp, 'DistributionLambda': tfp.layers.DistributionLambda, 'nll': nll})` as you suggested lead to this error instead:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [25], in <cell line: 23>()
     20     return -y_pred.log_prob(y_true)
     22 model.compile(optimizer, loss=nll)
---> 23 model.fit(x=X.astype(float), y=y.astype(float), epochs=100)
     26 active_experiment = "active-custom-experiment"
     27 mlflow.set_experiment(active_experiment)

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File /var/folders/mt/ftnr40_x3s98d981q72ld_1m0000gn/T/__autograph_generated_filei6174rj8.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

ValueError: in user code:

    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/engine/training.py", line 893, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 539, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 640, in apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    File "/Users/user/miniforge3/envs/py38/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/utils.py", line 73, in filter_empty_gradients
        raise ValueError(f"No gradients provided for any variable: {variable}. "

    ValueError: No gradients provided for any variable: (['dense_30/kernel:0', 'dense_30/bias:0', 'dense_31/kernel:0', 'dense_31/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'dense_30/kernel:0' shape=(4, 30) dtype=float32>), (None, <tf.Variable 'dense_30/bias:0' shape=(30,) dtype=float32>), (None, <tf.Variable 'dense_31/kernel:0' shape=(30, 1) dtype=float32>), (None, <tf.Variable 'dense_31/bias:0' shape=(1,) dtype=float32>)).
```

**Comment by BenWilson2** [comment]
Can you attempt to load the model specifying that the compilation is to turn off? compile=False in the load from the mlflow instance?

**Comment by forons** [comment]
Just to be clear, the error `ValueError: No gradients provided for any variable:` appears even before trying to upload the model to mlflow.
To answer your question, I am already able to load models from mlflow but I cannot try to load this one, because I am not able to log it.
Sorry it wasn't clear.

**Comment by BenWilson2** [comment]
right, but can you specify that same arg `compile=False` to get it to log? 
If that doesn't work, I'm not entirely sure what to recommend...

**Comment by forons** [comment]
I removed the decorator `@tf.function` from the loss function, and I tried to log the model with the parameter `compile=False`:
```
mlflow.keras.log_model(model, "model", custom_objects={'exp': tf.exp, 'DistributionLambda': tfp.layers.DistributionLambda, 'nll': nll}, compile=False)
```
However, I still get an exception:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 28>()
     27 mlflow.set_experiment(active_experiment)
     28 with mlflow.start_run():
---> 29     mlflow.keras.log_model(model, "model", custom_objects={'exp': tf.exp, 'DistributionLambda': tfp.layers.DistributionLambda, 'nll': nll}, compile=False)

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py:416, in log_model(keras_model, artifact_path, conda_env, code_paths, custom_objects, keras_module, registered_model_name, signature, input_example, await_registration_for, pip_requirements, extra_pip_requirements, **kwargs)
    404 if signature is not None:
    405     warnings.warn(
    406         "The pyfunc inference behavior of Keras models logged "
    407         "with signatures differs from the behavior of Keras "
   (...)
    414         "a Pandas DataFrame output in response to a Pandas DataFrame input."
    415     )
--> 416 return Model.log(
    417     artifact_path=artifact_path,
    418     flavor=mlflow.keras,
    419     keras_model=keras_model,
    420     conda_env=conda_env,
    421     code_paths=code_paths,
    422     custom_objects=custom_objects,
    423     keras_module=keras_module,
    424     registered_model_name=registered_model_name,
    425     signature=signature,
    426     input_example=input_example,
    427     await_registration_for=await_registration_for,
    428     pip_requirements=pip_requirements,
    429     extra_pip_requirements=extra_pip_requirements,
    430     **kwargs,
    431 )

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/models/model.py:372, in Model.log(cls, artifact_path, flavor, registered_model_name, await_registration_for, **kwargs)
    370 run_id = mlflow.tracking.fluent._get_or_start_run().info.run_id
    371 mlflow_model = cls(artifact_path=artifact_path, run_id=run_id)
--> 372 flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
    373 mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
    374 try:

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/mlflow/keras.py:268, in save_model(keras_model, path, conda_env, code_paths, mlflow_model, custom_objects, keras_module, signature, input_example, pip_requirements, extra_pip_requirements, **kwargs)
    266         shutil.copyfile(src=f.name, dst=model_path)
    267 else:
--> 268     keras_model.save(model_path, **kwargs)
    270 # update flavor info to mlflow_model
    271 mlflow_model.add_flavor(
    272     FLAVOR_NAME,
    273     keras_module=keras_module.__name__,
   (...)
    277     code=code_dir_subpath,
    278 )

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~/miniforge3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py:64, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     62 filtered_tb = None
     63 try:
---> 64   return fn(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)

TypeError: save() got an unexpected keyword argument 'compile'
```

**Comment by B-Step62** [comment]
The Keras flavor has since been reworked (`mlflow.keras` now targets Keras 3), so this error on the old tf.keras `log_model` path no longer applies. Closing, feel free to reopen with a reproducible example on a current version if a TFP custom layer still fails.
