### ISSUE TITLE
AttributeError: module 'mlflow.tensorflow' has no attribute 'log_saved_model'

### ISSUE THREAD

**Issue by jimthompson5802** [mlflow/mlflow#709]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:  Attempting to run example in `mlflow/mlflow-apps/apps/dnn-regression`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Running Docker Container (see Dockerfile) later in this posting on MacOS 10.14.1
- **MLflow installed from (source or binary)**:  Installed from binary 
- **MLflow version (run ``mlflow --version``)**:  mlflow, version 0.8.0
- **Python version**: Python 3.6.2 :: Anaconda, Inc.
- **npm version (if running the dev UI): N/A
- **Exact command to reproduce**:
```
# create work area
mkdir my-apps

# navigate to mlflow-apps root directory and save location in environment variable
cd mlflow-apps/
export PROJECT_DIR=`pwd`

# navigate to work area
cd ../my_apps

# create temporary directory
temp="$(mktemp -d)"

# download training data
mlflow run $PROJECT_DIR -P dest-dir=$temp

# perform model training
mlflow run $PROJECT_DIR/apps/dnn-regression -P train="$temp/train_diamonds.parquet" -P test="$temp/test_diamonds.parquet" -P label-col="price" -P hidden-units="10,10" -P model-dir="." -e main

```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.
Received this error message:
```
Traceback (most recent call last):
  File "main_dnn.py", line 56, in <module>
    args.training_data_path, args.test_data_path)
  File "/home/ds_user/my_workarea/mlflow-apps/apps/dnn-regression/train_dnn.py", line 99, in train
    tensorflow.log_saved_model(saved_model_dir=saved_estimator_path,
AttributeError: module 'mlflow.tensorflow' has no attribute 'log_saved_model'
```
I've attempted to find the function `tensorflow.log_saved_model()` definition but unable to find the definition.  As a result, I'm unsure how to resolve the problem

### Source code / logs
Run-time Log
```
ds_user@0487fbc87e20:~/my_workarea/my_apps$ mlflow run $PROJECT_DIR/apps/dnn-regression -P train="$temp/train_diamonds.parquet" -P test="$temp/test_diamonds.parquet" -P label-col="price" -P hidden-units="10,10" -P model-dir="." -e main
=== Created directory /tmp/tmpk8082sjc for downloading remote URIs passed to arguments of type 'path' ===
=== Running command 'source activate mlflow-3aeddf0774950c8857851841ef8b38289de49425 && python main_dnn.py /home/ds_user/my_workarea/my_apps /tmp/tmp.NQAPCCKBjL/train_diamonds.parquet /tmp/tmp.NQAPCCKBjL/test_diamonds.parquet 10,10 100 128 price' in run with ID '7d503fbab6d44646944129aab772ffe9' === 
train:                 /tmp/tmp.NQAPCCKBjL/train_diamonds.parquet
test:                  /tmp/tmp.NQAPCCKBjL/test_diamonds.parquet
hidden-units:          10
hidden-units:          10
steps:                 100
batch_size:            128
label-col:             price
feat-cols:             carat
feat-cols:             cut
feat-cols:             color
feat-cols:             clarity
feat-cols:             depth
feat-cols:             table
feat-cols:             x
feat-cols:             y
feat-cols:             z
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpfw816x4c
2018-11-12 21:30:00.148085: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Test RMSE: 3900.4166444112097
Training Set R2 -0.004844327292756523
Test Set R2 0.03431445976217051
WARNING:tensorflow:Export includes no default signature!
Traceback (most recent call last):
  File "main_dnn.py", line 56, in <module>
    args.training_data_path, args.test_data_path)
  File "/home/ds_user/my_workarea/mlflow-apps/apps/dnn-regression/train_dnn.py", line 99, in train
    tensorflow.log_saved_model(saved_model_dir=saved_estimator_path,
AttributeError: module 'mlflow.tensorflow' has no attribute 'log_saved_model'
=== Run (ID '7d503fbab6d44646944129aab772ffe9') failed ===
```
### Dockerfile:
```
FROM continuumio/miniconda3:4.3.27

#
# get development tools needed for xgboost
#
RUN apt-get update -y && apt-get install -y build-essential     

#
# install requirements for MLFLOW
#
COPY dev-requirements.txt /tmp/
RUN /opt/conda/bin/pip install --requirement /tmp/dev-requirements.txt \
    && rm /tmp/dev-requirements.txt

# specify run-time user
# make uid/gid match ec2-user on AWS
# on MacOS docker mask uid/gid in and out of container
RUN groupadd -g 500 ds_user && \
    useradd -u 500 -g 500 ds_user && \
    mkdir -p /home/ds_user && \
    chown ds_user:ds_user /home/ds_user && \
    mkdir /my_workarea && \
    chown ds_user:ds_user /my_workarea

# set user
USER ds_user
```

#### dev-requirements.txt file used in above COPY operation
```
#
# based on list from mlflow-apps
#
prospector[with_pyroma]==0.12.7
pylint==1.8.2
xgboost
pytest
pyarrow
pandas
numpy
rstcheck
scikit-learn
mlflow
tensorflow
```

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by smurching** [comment]
Hi @jimthompson5802, this issue is caused by the use of old (deprecated & removed) MLflow APIs  in https://github.com/mlflow/mlflow-apps, which should be fixed now that https://github.com/mlflow/mlflow-apps/pull/22 is merged. Rerunning the commands in your original post now work for me - let me know if they work for you & we can close this issue, thanks!

**Comment by jimthompson5802** [comment]
@smurching Yes, I'm good right now.  And I understand how mlflow evolved from early days.  This is particular issue was opened before you and I had our discussion regarding [mlflow/mlflow-apps#22](https://github.com/mlflow/mlflow-apps/pull/22).  So I'm closing this issue.
