### ISSUE TITLE
[BUG] mlflow sagemaker build-and-push-concontainer cmd fail with docker 4.13.0 version on mac m1 pro 16

### ISSUE THREAD

**Issue by QAM** [mlflow/mlflow#7155]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.30.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MAC M1 PRO 16, 12.6.1
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**:

### Describe the problem

I run the cmd "mlflow sagemaker build-and-push-container  --build" with docker version 4.13.0

Got the error version api can't be fetched.

i downgrade docker software version from 4.13.0 to 4.12.0 and it works.

### Code to reproduce issue

```
mlflow sagemaker build-and-push-container  --build
```

### Stack trace

2022/10/25 09:44:29 INFO mlflow.models.docker_utils: Building docker image with name mlflow-pyfunc
Traceback (most recent call last):
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Users/lchen/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/mlflow/sagemaker/cli.py", line 605, in build_and_push_container
    mlflow.models.docker_utils._build_image(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/mlflow/models/docker_utils.py", line 224, in _build_image
    _build_image_from_context(context_dir=cwd, image_name=image_name)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/mlflow/models/docker_utils.py", line 230, in _build_image_from_context
    client = docker.from_env()
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/lchen/Library/Caches/pypoetry/virtualenvs/land-valuation-model-dJtFYf8y-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')).

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@QAM Found https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version, which reports a similar issue.

**Comment by QAM** [comment]
@harupy ya. This is for linux. And as I mentioned, the issue happened after docker recent release on 2022/10/19 4.13.0.
However, it works with version 4.12.0 released on 2022/9/1

**Comment by harupy** [comment]
@QAM Have you already seen https://github.com/docker/docker-py/issues/3059?

**Comment by harupy** [comment]
This is a docker-py's issue.

**Comment by QAM** [comment]
@harupy From the description, docker issue also happens on docker 4.12.0.
I am not really sure they are related.
I also test the cmd locally.
```
python -c "import docker; client=docker.from_env()"
```

Works great.
Might need to check this again.
