### ISSUE TITLE
[BUG] pipeline example doesn't run

### ISSUE THREAD

**Issue by alexanderkainsky** [mlflow/mlflow#7172]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.30

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 20.04
- **Python version**: 3.9.14
- **yarn version, if running the dev UI**: n/a

### Describe the problem

Pipeline example errors with:

mlflow.exceptions.MlflowException: Exactly one of `experiment_name` or `experiment_id` must be specified

### Tracking information

MLflow version: 1.30.0
Tracking URI: file:///home/kaina/work/repo/mlp-regression-template/mlruns
Artifact URI: file:///home/kaina/work/repo/mlp-regression-template/mlruns/0/eded7004b3534c279f508d41177d8dd7/artifacts

### Code to reproduce issue

straight from the website:

git clone https://github.com/mlflow/mlp-regression-template
cd mlp-regression-template
mlflow pipelines run --profile local

### Stack trace

```
2022/10/26 10:25:42 INFO mlflow.pipelines.pipeline: Creating MLflow Pipeline 'mlp-regression-template' with profile: 'local'
Traceback (most recent call last):
  File "/home/kaina/.pyenv/versions/core/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/cli.py", line 46, in run
    Pipeline(profile=profile).run(step)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/pipeline.py", line 452, in __new__
    return pipeline_class_module(pipeline_root_path, profile)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/pipeline.py", line 54, in __init__
    self._steps = self._resolve_pipeline_steps()
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/pipeline.py", line 323, in _resolve_pipeline_steps
    return [
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/pipeline.py", line 324, in <listcomp>
    s.from_pipeline_config(pipeline_config, self._pipeline_root_path)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/steps/transform.py", line 203, in from_pipeline_config
    return cls(step_config, pipeline_root)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/steps/transform.py", line 52, in __init__
    self.tracking_config = TrackingConfig.from_dict(self.step_config)
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/utils/tracking.py", line 110, in from_dict
    return TrackingConfig(
  File "/home/kaina/.pyenv/versions/3.9.14/envs/core/lib/python3.9/site-packages/mlflow/pipelines/utils/tracking.py", line 72, in __init__
    raise MlflowException(
mlflow.exceptions.MlflowException: Exactly one of `experiment_name` or `experiment_id` must be specified
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@alexanderkainsky I was able to reproduce the issue.

```
git clone https://github.com/mlflow/mlp-regression-example
cd mlp-regression-example
mlflow pipelines run --profile local
```


@dbczumar Is https://github.com/mlflow/mlp-regression-template outdated?

**Comment by harupy** [comment]
I see, to make https://github.com/mlflow/mlp-regression-template work, we need to fix some fields in the profile?

**Comment by harupy** [comment]
I see, https://github.com/mlflow/mlp-regression-template doesn't work by default. We need to fix some fields (e.g. experiment name) in the profile.

**Comment by harupy** [comment]
@alexanderkainsky 

Where did you find this command?

```
git clone https://github.com/mlflow/mlp-regression-template
cd mlp-regression-template
mlflow pipelines run --profile local
```

**Comment by alexanderkainsky** [comment]
https://mlflow.org/docs/latest/pipelines.html

**Comment by harupy** [comment]
This section might look like `mlp-regression-template` works without any modifications:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/17039389/198171715-7982ad2d-d7e6-4f42-ad73-1f7d7066dc2a.png">

Comment indicating it requires changes might help. @dbczumar @jinzhang21

**Comment by jinzhang21** [comment]
This was a mistake. It should be `mlp-regression-example`, not `mlp-regression-template`, which is meant to be used by adapting to real use cases. I'll file a PR to fix the comment.

**Comment by harupy** [comment]
@jinzhang21 Thanks!

**Comment by jinzhang21** [comment]
Merged PR https://github.com/mlflow/mlflow/pull/7059 to update the user guide.

**Comment by alexanderkainsky** [comment]
Thank you!
