### ISSUE TITLE
[BUG] log_explanation failed because of type caset

### ISSUE THREAD

**Issue by kuromt** [mlflow/mlflow#7215]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29.0
- Tracking server: 1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

mlflow.shap.log_explanation raise Error. (Look at Stack trace)

I debug the error, and I found that `convert_to_data` in KernelShap changes data types from float32 to float64.
https://github.com/slundberg/shap/blob/17435fc9a39c4817a49ce714c5086e65e2a8fd50/shap/explainers/_kernel.py#L69

My MLflow Model registed in MLflow Model Registry has `float` input schemas which mean `float32` in Mlflow. 
https://github.com/mlflow/mlflow/blob/71bbe5e313f0b79d0d3e9b6b9d7cd9bb8038c561/mlflow/types/schema.py#L34

So MLflow expect input data has float32 data.
I confirmed that the dtype input data loaded  with `pd.read_csv` has flaot32, but in KernelShap, it raise MLflow Exception.

```
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/models/utils.py", line 425, in _enforce_mlflow_datatype
    raise MlflowException(
mlflow.exceptions.MlflowException: Incompatible input types for column xxxx Can not safely convert float64 to float32.
```

So, I found the bug raises when

- Model Input Schema supposes columns is `float` type.
- The columns data are actually `float32` type
- log_explaination with above data, it causes Error

### Code to reproduce issue

it depends on data.

```python
log_explanation(model.predict, train_data)
```

### Stack trace

```python
>>> log_explanation(model.predict, train_data)
Provided model function fails when applied to the provided data set.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/shap.py", line 277, in log_explanation
    explainer = shap.KernelExplainer(predict_function, background_data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/shap/explainers/_kernel.py", line 69, in __init__
    model_null = match_model_to_data(self.model, self.data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/shap/utils/_legacy.py", line 112, in match_model_to_data
    out_val = model.f(data.data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 372, in predict
    data = _enforce_schema(data, input_schema)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/models/utils.py", line 545, in _enforce_schema
    raise MlflowException(message)
mlflow.exceptions.MlflowException: Model is missing inputs  ['xxxx', 'xxxx', 'xxxx', 'xxxx', .......]. Note that there were extra inputs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
I'm afraid that I can't reproduce this. 
Could you take a look at the below unit test and see if I'm capturing what you're reporting as an issue?

``` python
def test_float_precision_kernel_explainer():

    # Train on 32bit float, explain on 64bit float

    num_rows = 50

    X, y = get_diabetes()
    X_cast = X.astype('float32')  # training set cast to 32bit float

    X_cast, y = X_cast.iloc[:num_rows], y[:num_rows]
    X = X.iloc[:num_rows]
    X = X.astype('float64')  # SHAP kernel explainer on 64bit float

    model = RandomForestRegressor()
    model.fit(X_cast, y)  # fit on 32bit float

    with mlflow.start_run() as run:
        explanation_uri = mlflow.shap.log_explanation(model.predict, X)

    artifact_path = "model_explanations_shap"
    artifacts = set(yield_artifacts(run.info.run_id))

    assert explanation_uri == os.path.join(run.info.artifact_uri, artifact_path)
    assert artifacts == {
        os.path.join(artifact_path, "base_values.npy"),
        os.path.join(artifact_path, "shap_values.npy"),
        os.path.join(artifact_path, "summary_bar_plot.png"),
    }

    explainer = shap.KernelExplainer(model.predict, shap.kmeans(X, num_rows))
    shap_values_expected = explainer.shap_values(X)

    base_values = np.load(os.path.join(explanation_uri, "base_values.npy"))
    shap_values = np.load(os.path.join(explanation_uri, "shap_values.npy"))
    np.testing.assert_array_equal(base_values, explainer.expected_value)
    np.testing.assert_array_equal(shap_values, shap_values_expected)

    # Train on 64bit float, explain on 32bit float

    num_rows = 50

    X, y = get_diabetes()
    X_cast = X.astype('float64')  # cast training set to 64bit float

    X_cast, y = X_cast.iloc[:num_rows], y[:num_rows]
    X = X.iloc[:num_rows]
    X = X.astype('float32')  # shap validation on 32bit float

    model = RandomForestRegressor()
    model.fit(X_cast, y)  # fit on 64bit float

    with mlflow.start_run() as run:
        explanation_uri = mlflow.shap.log_explanation(model.predict, X)

    artifact_path = "model_explanations_shap"
    artifacts = set(yield_artifacts(run.info.run_id))

    assert explanation_uri == os.path.join(run.info.artifact_uri, artifact_path)
    assert artifacts == {
        os.path.join(artifact_path, "base_values.npy"),
        os.path.join(artifact_path, "shap_values.npy"),
        os.path.join(artifact_path, "summary_bar_plot.png"),
    }

    explainer = shap.KernelExplainer(model.predict, shap.kmeans(X, num_rows))
    shap_values_expected = explainer.shap_values(X)

    base_values = np.load(os.path.join(explanation_uri, "base_values.npy"))
    shap_values = np.load(os.path.join(explanation_uri, "shap_values.npy"))
    np.testing.assert_array_equal(base_values, explainer.expected_value)
    np.testing.assert_array_equal(shap_values, shap_values_expected)



```

**Comment by BenWilson2** [comment]
The exception that you're getting is raised from here:

https://github.com/mlflow/mlflow/blob/6bddc546abb9001120fe09a1329e53b8eafcaf8f/mlflow/models/utils.py#L543-L549

Can you verify that you're passing in all of the required columns (see my example above for guidance).

**Comment by kuromt** [comment]
I reproduce the problem. I think that it causes when model signature is registed.

- disable autolog, work fine

```
import os

import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from lightgbm import LGBMRegressor

import mlflow
from mlflow import MlflowClient

# prepare training data
X, y = dataset = load_diabetes(return_X_y=True, as_frame=True)
X = pd.DataFrame(dataset.data[:50, :8], columns=dataset.feature_names[:8])
y = dataset.target[:50]

# train a model
model = LGBMRegressor()
model.fit(X, y)

# register model
mlflow.lightgbm.log_model(model, "diabates_lgbm_model")

# register to model registry
# operation in webui

# load_model
model_uri="models:/diabates_lgbm_model/1"
from mlflow.pyfunc import load_model as mlflow_load_model
load_model = mlflow_load_model(model_uri)

mlflow.shap.log_explanation(load_model.predict, X)
```

result
```
Usage of np.ndarray subset (sliced data) is not recommended due to it will double the peak memory cost in LightGBM.
  8%|███████▌                                                                                          | 34/442 [00:20<03:58,  1.71it/s]Usage of np.ndarray subset (sliced data) is not recommended due to it will double the peak memory cost in LightGBM.
  8%|███████▊                                                                                          | 35/442 [00:21<04:04,  1.67it/s]Usage of np.ndarray subset (sliced data) is not recommended due to it will double the peak memory cost in LightGBM.
  8%|███████▉                                                                                          | 36/442 [00:21<03:56,  1.72it/s]Usage of np.ndarray subset (sliced data) is not recommended due to it will double the peak memory cost in LightGBM.
```


- With autolog, raise error

```
import os

import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from lightgbm import LGBMRegressor

import mlflow
from mlflow import MlflowClient

# prepare training data
X, y = dataset = load_diabetes(return_X_y=True, as_frame=True)
X = pd.DataFrame(dataset.data[:50, :8], columns=dataset.feature_names[:8])
y = dataset.target[:50]

mlflow.lightgbm.autolog()

# train a model
model = LGBMRegressor()


with mlflow.start_run():
  model.fit(X, y)

# register to model registry
# operation in webui

# load_model
model_uri="models:/diabates_lgbm_model/2"
from mlflow.pyfunc import load_model as mlflow_load_model
load_model = mlflow_load_model(model_uri)
mlflow.shap.log_explanation(load_model.predict, X)
```

result
```
Provided model function fails when applied to the provided data set.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/shap.py", line 277, in log_explanation
    explainer = shap.KernelExplainer(predict_function, background_data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/shap/explainers/_kernel.py", line 69, in __init__
    model_null = match_model_to_data(self.model, self.data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/shap/utils/_legacy.py", line 112, in match_model_to_data
    out_val = model.f(data.data)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 372, in predict
    data = _enforce_schema(data, input_schema)
  File "/Users/nkuromat/git/hoge/.venv/lib/python3.8/site-packages/mlflow/models/utils.py", line 545, in _enforce_schema
    raise MlflowException(message)
mlflow.exceptions.MlflowException: Model is missing inputs ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']. Note that there were extra inputs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

In my environment, run with shap==0.40

```
$ pip freeze |grep -e mlflow -e shap
mlflow==1.29.0
shap==0.40.0
```

**Comment by kuromt** [comment]
I found a workaround.

```
load_model.metadata.signature = None
```

**Comment by kuromt** [comment]
@BenWilson2 What do you think about the error? 
Should MLflow support explain with loaded model?

**Comment by BenWilson2** [comment]
I was able to reproduce what you're seeing. That being said, the APIs aren't really designed for what you're trying to do. There ARE ways to wrap an `Explainer` in a `pyfunc`. 

```python
from sklearn.datasets import load_diabetes
from lightgbm import LGBMRegressor
import shap
import mlflow
from mlflow.tracking.artifact_utils import _download_artifact_from_uri

mlflow.set_tracking_uri("http://127.0.0.1:5000")

# prepare training data
X, y = load_diabetes(return_X_y=True, as_frame=True)

mlflow.lightgbm.autolog(log_input_examples=True, log_model_signatures=True)

with mlflow.start_run():
    
    model = LGBMRegressor().fit(X, y)
    
#     mlflow.shap.log_explanation(pyfunc_model.predict, X) # This throws. As it should.

    explainer_original = shap.Explainer(model.predict, X, algorithm="permutation")

    mlflow.shap.log_explainer(explainer_original, "test_explainer")
    
    explainer_uri = mlflow.get_artifact_uri("test_explainer")
    explainer_path = _download_artifact_from_uri(explainer_uri)
    
    explainer_pyfunc = mlflow.shap._load_pyfunc(explainer_path)
    
#     mlflow.shap.log_explanation(explainer_pyfunc.predict, X) # This fails, as it should.
    
    mlflow.shap.log_explanation(model.predict, X)

```

There ARE ways to perform logging of Explainer details to a run while still supporting model signature inference.

```python
import xgboost
import shap
import json
import mlflow
from sklearn.model_selection import train_test_split

mlflow.xgboost.autolog(log_input_examples=True, log_model_signatures=True)

with mlflow.start_run() as run:
    
    # Load the UCI Adult Dataset
    X, y = shap.datasets.adult()

    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

    # Fit an XGBoost binary classifier on the training data split
    model = xgboost.XGBClassifier().fit(X_train, y_train)

    # Build the Evaluation Dataset from the test set
    eval_data = X_test
    eval_data["label"] = y_test

    # Log the baseline model to MLflow
    model_uri = mlflow.get_artifact_uri("model")
    
    # Evaluate the logged model
    result = mlflow.evaluate(
        model_uri,
        eval_data,
        targets="label",
        model_type="classifier",
        evaluators=["default"],
    )

from mlflow import MlflowClient

client = mlflow.MlflowClient()

print(json.dumps(
        {key: json.loads(x) for key, x in json.loads(
            client.get_run(run.info.run_id).data.tags.get("mlflow.log-model.history"))[0]["signature"].items()
        }, indent=2)
     )

```

```shell
{
  "inputs": [
    {
      "name": "Age",
      "type": "float"
    },
    {
      "name": "Workclass",
      "type": "integer"
    },
    {
      "name": "Education-Num",
      "type": "float"
    },
    {
      "name": "Marital Status",
      "type": "integer"
    },
    {
      "name": "Occupation",
      "type": "integer"
    },
    {
      "name": "Relationship",
      "type": "long"
    },
    {
      "name": "Race",
      "type": "integer"
    },
    {
      "name": "Sex",
      "type": "integer"
    },
    {
      "name": "Capital Gain",
      "type": "float"
    },
    {
      "name": "Capital Loss",
      "type": "float"
    },
    {
      "name": "Hours per week",
      "type": "float"
    },
    {
      "name": "Country",
      "type": "integer"
    }
  ],
  "outputs": [
    {
      "type": "tensor",
      "tensor-spec": {
        "dtype": "int64",
        "shape": [
          -1
        ]
      }
    }
  ]
}

```

There aren't ways of loading an arbitrary `pyfunc` model and running explanations on it (since the structure of the passed-in data is going to be different (which is the exception that you're seeing). This is by design. Please see the two examples above for the approved ways of trying to do what you're doing. 
We currently do not have any plans to support the use case that you originally were trying to do.

**Comment by stb-f5c** [comment]
> ```python
> mlflow.shap.log_explainer(explainer_original, "test_explainer")
> ```

When I log the explainer in the following code` mlflow.shap.log_explainer(explainer_original, "test_explainer")`
It replies: "Unable to serialize underlying model using MLflow, will use SHAP serialization", do I need to change my code regarding this mlflow.pyfunc.PyFuncModel?

**Comment by stb-f5c** [comment]
> ```python
> mlflow.shap.log_explanation(model.predict, X)
> ```

I am following your example, until the last command which gives me error similar to what @kuromt mentioned above :

Model is missing inputs [HERE is a list of input varialbe names]. Note that there were extra inputs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Any tips what should I change to fix the issue here?
