### ISSUE TITLE
[BUG] mlflow.spark.load_model fails with NotADirectoryError 

### ISSUE THREAD

**Issue by pravingadakh** [mlflow/mlflow#7304]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.24.0
- Tracking server: 1.24.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:
- pyspark: 2.4.8
- python: 3.7.0

### Describe the problem

I am trying to log a simple pyspark pipeline model and load it. The load_model API is failing with NotADirectoryError.

### Code to reproduce issue

```python
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import HashingTF, Tokenizer
training = spark.createDataFrame([
    (0, "a b c d e spark", 1.0),
    (1, "b d", 0.0),
    (2, "spark f g h", 1.0),
    (3, "hadoop mapreduce", 0.0) ], ["id", "text", "label"])
tokenizer = Tokenizer(inputCol="text", outputCol="words")
hashingTF = HashingTF(inputCol=tokenizer.getOutputCol(), outputCol="features")
lr = LogisticRegression(maxIter=10, regParam=0.001)
pipeline = Pipeline(stages=[tokenizer, hashingTF, lr])
model = pipeline.fit(training)

import mlflow
import mlflow.spark
import logging
logging.getLogger("mlflow").setLevel(logging.DEBUG)

mlflow.set_experiment("pyspark_mlflow")
mlflow.spark.log_model(model, "spark-model")
```

```
model = mlflow.spark.load_model("runs:/<run_id>/spark-model")
```

### Stack trace

following warning I see while logging the model, however the model gets logged 
```
2022/11/10 10:47:10 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpjdiqg1b4, flavor: spark), fall back to return ['pyspark==2.4.8']. Set logging level to DEBUG to see the full traceback.
2022/11/10 10:47:10 DEBUG mlflow.utils.environment: 
Traceback (most recent call last):
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/environment.py", line 195, in infer_pip_requirements
    return _infer_requirements(model_uri, flavor)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/requirements_utils.py", line 332, in _infer_requirements
    modules = _capture_imported_modules(model_uri, flavor)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/requirements_utils.py", line 264, in _capture_imported_modules
    json.dumps(sys.path),
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/requirements_utils.py", line 205, in _run_command
    raise MlflowException(msg)
mlflow.exceptions.MlflowException: Encountered an unexpected error while running ['/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/bin/python', '/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/_capture_modules.py', '--model-path', '/tmp/tmpjdiqg1b4', '--flavor', 'spark', '--output-file', '/tmp/tmpgk7ffuhu/imported_modules.txt', '--sys-path', '["/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/tmp", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/git/ext/gitdb", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/spark-8bfe0ab9-f148-48e7-b80f-ce0f99873adf/userFiles-9d4c6fa2-5a2f-4d72-ab25-c2a5b074bb44", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/py4j-0.10.7-src.zip", "/usr/lib/spark/python/lib/pyspark.zip", "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/file", "/usr/hdp/current/spark/python/lib/pyspark.zip", "/usr/hdp/current/spark/python/lib/py4j-0.10.7-src.zip", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python37.zip", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/lib-dynload", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/IPython/extensions", "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/gitdb/ext/smmap"]']
exit status: 1
stdout: 
stderr: Traceback (most recent call last):
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/_capture_modules.py", line 134, in <module>
    main()
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/_capture_modules.py", line 109, in main
    mlflow.pyfunc.load_model(model_path)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 710, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/utils/_capture_modules.py", line 106, in _load_pyfunc_patch
    return original(*args, **kwargs)
<img width="358" alt="Screenshot 2022-11-10 at 4 37 54 PM" src="https://user-images.githubusercontent.com/13175315/201075669-fce1322a-dd6f-4a15-9248-81d2f36f6463.png">

  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/spark.py", line 709, in _load_pyfunc
    .master("local[1]")
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip/pyspark/sql/session.py", line 173, in getOrCreate
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip/pyspark/context.py", line 367, in getOrCreate
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip/pyspark/context.py", line 136, in __init__
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip/pyspark/context.py", line 198, in _do_init
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/pyspark.zip/pyspark/context.py", line 306, in _initialize_context
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
org.apache.livy.rsc.driver.SparkEntries.sc(SparkEntries.java:51)
org.apache.livy.rsc.driver.SparkEntries.sparkSession(SparkEntries.java:72)
org.apache.livy.repl.AbstractSparkInterpreter.postStart(AbstractSparkInterpreter.scala:69)
org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply$mcV$sp(SparkInterpreter.scala:95)
org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:70)
org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:70)
org.apache.livy.repl.AbstractSparkInterpreter.restoreContextClassLoader(AbstractSparkInterpreter.scala:340)
org.apache.livy.repl.SparkInterpreter.start(SparkInterpreter.scala:70)
org.apache.livy.repl.Session$$anonfun$1.apply(Session.scala:128)
org.apache.livy.repl.Session$$anonfun$1.apply(Session.scala:122)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2498)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2494)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2494)
	at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:2583)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:86)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

While loading the I'm seeing following error 

```
An error was encountered:
[Errno 20] Not a directory: '/tmp/tmpr4x31fth/sparkml/metadata'
Traceback (most recent call last):
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/spark.py", line 682, in load_model
    return _load_model(model_uri=model_uri, dfs_tmpdir_base=dfs_tmpdir)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/spark.py", line 633, in _load_model
    model_uri = _HadoopFileSystem.maybe_copy_from_uri(model_uri, dfs_tmpdir)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/spark.py", line 371, in maybe_copy_from_uri
    return cls.maybe_copy_from_local_file(_download_artifact_from_uri(src_uri), dst_path)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/tracking/artifact_utils.py", line 96, in _download_artifact_from_uri
    artifact_path=artifact_path, dst_path=output_path
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 243, in download_artifacts
    src_artifact_dir_path=artifact_path, dst_local_dir_path=dst_path
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 210, in async_download_artifact_dir
    dst_local_dir_path=dst_local_dir_path,
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 215, in async_download_artifact_dir
    dst_local_dir_path=dst_local_dir_path,
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 155, in async_download_artifact
    src_artifact_path=src_artifact_path, dst_local_dir_path=dst_local_dir_path
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repo.py", line 107, in _create_download_destination
    os.makedirs(local_dir_path, exist_ok=True)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1668075950962_0002/container_e01_1668075950962_0002_01_000001/mllibs/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmpr4x31fth/sparkml/metadata'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@pravingadakh Thanks for reporing this issue. Let me check if I can reproduce it.

**Comment by pravingadakh** [comment]
@harupy Were you able to reproduce it?

**Comment by harupy** [comment]
@pravingadakh I wasn't able to reproduce the issue with the latest version of MLflow. You can try MLflow 1.30.0.

**Comment by pravingadakh** [comment]
@harupy The MLflow version (1.24.0) that we use is part of the managed offering at our organization and I can not change the version. Do you think I am missing anything here or if it is a legit issue then can we patch it or something?

**Comment by pravingadakh** [comment]
Also do you think this is related to https://github.com/mlflow/mlflow/issues/6450 issue?

**Comment by harupy** [comment]
I don't think you're missing anything.

**Comment by harupy** [comment]
Unfortunately, we don't have a plan to make a patch release for MLflow 1.24.

**Comment by pravingadakh** [comment]
@harupy I wasn't expecting MLflow community to fix it. We just need help in identifying the root cause and maybe fix it ourselves.

**Comment by harupy** [comment]
@pravingadakh I ran this command, but I wasn't able to reproduce the error:

```bash
> cat a.py
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import HashingTF, Tokenizer
import mlflow
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
training = spark.createDataFrame(
    [
        (0, "a b c d e spark", 1.0),
        (1, "b d", 0.0),
        (2, "spark f g h", 1.0),
        (3, "hadoop mapreduce", 0.0),
    ],
    ["id", "text", "label"],
)
tokenizer = Tokenizer(inputCol="text", outputCol="words")
hashingTF = HashingTF(inputCol=tokenizer.getOutputCol(), outputCol="features")
lr = LogisticRegression(maxIter=10, regParam=0.001)
pipeline = Pipeline(stages=[tokenizer, hashingTF, lr])
model = pipeline.fit(training)

with mlflow.start_run():
    mi = mlflow.spark.log_model(model, "spark-model")
    mlflow.spark.load_model(mi.model_uri)


> docker run --rm -w /mlflow -v $(pwd)/a.py:/mlflow/a.py python:3.8 bash -c "apt update -y && apt install -y openjdk-11-jdk && pip install 'protobuf<4' mlflow==1.24.0 pyspark && python a.py"


```

**Comment by harupy** [comment]
Maybe your pyspark version is too old.

**Comment by pravingadakh** [comment]
@harupy I've found the root cause for the issue. There was a bug with the custom ArtifactRepository plugin that we use with MLflow. This is can be closed. Thank you for spending your time on this.
