### ISSUE TITLE
[BUG] pytorch autologging silently fails with fairscale distributed training strategy

### ISSUE THREAD

**Issue by pavanchhatpar** [mlflow/mlflow#7320]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 1.30.0

### System information

Python 3.8.10
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
DBR 9.1 LTS ML (GPU)
torch 1.9 (comes pre-installed in DBR)
pytorch_lightning 1.8.1
fairscale 0.4.12

## Autologging warning
- Using `mlflow.pytorch.autolog` fails silently with an autologging warning mentioned below, which is why despite a successful `trainer.fit` call mlflow does not log the model or even the model summary
- I can confirm training completes successfully and also the trained checkpoint is available through pytorch lightning's default checkpointing mechanism and I'm able to log them as artifacts
- Looking at the warning and lack of any artifact I believe it originates in the following block of code https://github.com/mlflow/mlflow/blob/74f8ca6669273d02060c3bf9d85870262be734cd/mlflow/pytorch/_pytorch_autolog.py#L372-L376
- `ModelSummary` expects `model` to be a `LightningModule` where attribute `example_input_array` will always be present even if its `None` and hence it tries to query it without any checks here https://github.com/Lightning-AI/lightning/blob/0dfb3d28ce858e5d709cba468b374a3d41329655/src/pytorch_lightning/utilities/model_summary/model_summary.py#L245
- When training with fairscale strategy `model` is wrapped into a different class and hence `example_input_array` attribute is not present

## log_model Exception
 - I tried to use `log_model` outside of autologging since its invoked after the failing `ModelSummary` making it unreachable
 - The exception message is an open github issue https://github.com/pytorch/pytorch/issues/76927
 - There was a suggestion to save `model.module` instead of model but it didn't work either
 - pytorch lightning is able to create a checkpoint for this model so its definitely possible to overcome the error

I found this bug while working on databricks but I don't think its restricted to it or affects only this integration, its in general an issue for pytorch with mlflow

### Code to reproduce issue

```python
import os
import mlflow
import torch
from torch.utils.data import DataLoader, Dataset
import tempfile
import pickle

from pytorch_lightning import LightningModule, Trainer
import pytorch_lightning as pl
from pytorch_lightning.utilities.model_summary import ModelSummary

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.AdamW(self.trainer.model.parameters(), lr=0.1)

def run():
    pl.seed_everything(1)
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    tmpdir = tempfile.mkdtemp()
    print(f"log location: {tmpdir}")
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=tmpdir,
        num_sanity_val_steps=0,
        max_epochs=2,
        accelerator="gpu",
        devices=2,
        auto_select_gpus=True,
        strategy="fsdp", # can also try ddp_sharded to reproduce issue
    )
    if trainer.is_global_zero:
        print("MLFlow init")
        mlflow.pytorch.autolog(log_models=False) # True does not matter since code breaks before model logging
        run = mlflow.start_run()
    else:
        print("mlflow run exists on rank 0 process")
    try:
        trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
        # trainer.test(model, dataloaders=test_data)
    finally:
        if trainer.is_global_zero:
            print('Uploading lightning logs. May take time')
            mlflow.log_artifacts(tmpdir, 'pl_logs') # this works
            mlflow.pytorch.log_model(trainer.model, "model") # this fails
            mlflow.end_run()
        

if __name__ == "__main__":
    run()
```

### Stack trace

 - With strategy `fsdp`
   - Silent warning about unexpected error in autologging at the end of `trainer.fit` call
     ```python
     2022/11/11 20:58:54 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during pytorch autologging: '_DDPFullyShardedStrategyModuleWrapper' object has no attribute 'example_input_array'
     ```
   - Exception when manually tried logging model using `mlflow.pytorch.log_model`
     ```python
      Traceback (most recent call last):
        File "/tmp/boring_model_fairscale.py", line 85, in <module>
          run()
        File "/tmp/boring_model_fairscale.py", line 79, in run
          mlflow.pytorch.log_model(trainer.model, "model") # this fails
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 306, in log_model
          return Model.log(
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/models/model.py", line 373, in log
          flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 512, in save_model
          torch.save(pytorch_model, model_path, pickle_module=pickle_module, **kwargs)
        File "/databricks/python/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
          _save(obj, opened_zipfile, pickle_module, pickle_protocol)
        File "/databricks/python/lib/python3.8/site-packages/torch/serialization.py", line 484, in _save
          pickler.dump(obj)
        File "/databricks/python/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
          return Pickler.dump(self, obj)
      TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroupNCCL' object
     ```
 - When switching strategy to `ddp_sharded`
   - Silent warning about unexpected error in autologging at the end of `trainer.fit` call
      ```python
      WARNING mlflow.utils.autologging_utils: Encountered unexpected error during pytorch autologging: '_LightningModuleWrapperBase' object has no attribute 'example_input_array'
      ```
   - Exception when manually tried logging model using `mlflow.pytorch.log_model`
      ```python
      Traceback (most recent call last):
        File "/tmp/boring_model_fairscale.py", line 85, in <module>
          run()
        File "/tmp/boring_model_fairscale.py", line 79, in run
          mlflow.pytorch.log_model(trainer.model, "model") # this fails
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 306, in log_model
          return Model.log(
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/models/model.py", line 373, in log
          flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-182eddcc-afbc-4ba1-b007-1f003d511f52/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 512, in save_model
          torch.save(pytorch_model, model_path, pickle_module=pickle_module, **kwargs)
        File "/databricks/python/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
          _save(obj, opened_zipfile, pickle_module, pickle_protocol)
        File "/databricks/python/lib/python3.8/site-packages/torch/serialization.py", line 484, in _save
          pickler.dump(obj)
        File "/databricks/python/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
          return Pickler.dump(self, obj)
      TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroupNCCL' object
      ```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@pavanchhatpar 

> When training with fairscale strategy model is wrapped into a different class and hence example_input_array attribute is not present

Is it possible to unwrap the model?

**Comment by pavanchhatpar** [comment]
> > When training with fairscale strategy model is wrapped into a different class and hence example_input_array attribute is not present
> 
> Is it possible to unwrap the model?

Looks like `trainer.strategy.lightning_module` returns underlying lightning module. I think a cleaner way of doing model summary is through `on_fit_end` method of a callback where `pl_module` is already available unwrapped alongside `trainer` object. The default `ModelSummary` callback also does that.

Either approach will prevent the code from breaking and let `patched_fit` proceed to log model where it will break again. I noticed that with strategy `fsdp` model parameter count is shown as 0 in summary which is a pytorch/ lightning problem. Also for strategies `deepspeed_*` it is recommended to use DeepSpeedSummary class instead of ModelSummary, check [here](https://pytorch-lightning.readthedocs.io/en/stable/_modules/pytorch_lightning/callbacks/model_summary.html#ModelSummary)

> > log_model Exception
> 
> Sounds like a pytorch's issue. Let us know if you find a workaround for this.

pytorch recommends passing `state_dict` to `torch.save` unlike mlflow's way of passing the `nn.Module` object which will likely contain unserializable properties in any multi-processing context. pytorch lightning recommends using `trainer.save_checkpoint` which further takes care of strategy-specific serialization nuances and works for fairscale already. To some extent, there are callbacks and hooks to patch custom behavior on this serialization method if needed. 

For loading the model it is necessary to have the class type of the model to use `BoringModel.load_from_checkpoint`. Hopefully, this helps in refactoring the serialization mech in mlflow if that is a viable option.

A very silly workaround I can think of right now is 
```python
checkpoints = sorted(glob.glob(os.path.join(trainer.default_root_dir, "lightning_logs/**/*.ckpt"), recursive=True))
latest_checkpoint = checkpoints[-1]
reloaded_cpu_model = type(trainer.strategy.lightning_module).load_from_checkpoint(latest_checkpoint, map_location='cpu')
mlflow.pytorch.log_model(reloaded_cpu_model, "model")
```

The above snippet will be implementable inside patched_fit as well. It assumes model can be loaded on CPU (RAM) entirely. It also shifts the distributed serialization responsibility to pytorch lightning where it is already working. 

For latest checkpoint I think its possible to inject a ModelCheckpoint callback and use that to reference latest checkpoint / best checkpoint paths in a better way than what I'm doing here.

**Comment by dbczumar** [comment]
@harupy any updates here?

**Comment by B-Step62** [comment]
This targets a very old stack (MLflow 1.30, torch 1.9, pytorch-lightning 1.8) and a fairscale path that relied on PL internals since changed; fairscale's sharded strategies have largely been superseded by native FSDP. Closing as obsolete, feel free to reopen if you can reproduce on a current MLflow + PyTorch Lightning.
