### ISSUE TITLE
[BUG] MLFlow experiments loading

### ISSUE THREAD

**Issue by gvelimir** [mlflow/mlflow#7356]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Python version**: 3.10

### Describe the problem

After upgrading from 1.30 to 2.0.1, the experiments could not be loaded anymore. The command for backend store upgrade could not be performed because it rejects **DynamoDB**. Even though I am aware that **DynamoDB** is not officially supported as a backend store, I managed to set it up successfully on the previous version using **dynaflow**.

### Code to reproduce issue

mlflow server --default-artifact-root {S3_URI} --backend-store-uri {DynamoDB_URI} --host 0.0.0.0

### Stack trace

2022/11/16 20:37:49 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/experiments/search [GET]
Traceback (most recent call last):
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 452, in wrapper
    return func(*args, **kwargs)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 522, in wrapper
    return func(*args, **kwargs)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 1017, in _search_experiments
    response_message.experiments.extend([e.to_proto() for e in experiment_entities])
TypeError: 'NoneType' object is not iterable

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@gvelimir Thanks for reporting this issue. Let me check if I can reproduce the issue.

**Comment by harupy** [comment]
@gvelimir Are you using https://github.com/ArrichM/dynaflow? It looks like `search_experiments` is not implemented. The reason it didn't stop working in MLflow 2.0 might be because we removed `list_experiments` in MLflow 2.0.

**Comment by gvelimir** [comment]
Yes, that's the package i'm using to create the backand strore table structure in DynamoDB. Are you saying that the fix should be applied to Dynaflow?

**Comment by harupy** [comment]
Yes.

**Comment by harupy** [comment]
https://github.com/ArrichM/dynaflow/issues/2

**Comment by amesar** [comment]
The following list methods have been replaced by corresponding search methods in 2.x. The list methods have been removed from 2.x.
- Use search_experiments() instead of list_experiments()
- Use search_runs() instead of list_run_infos()
- Use search_registered_models() instead of list_registered_models()

See https://www.mlflow.org/news/2022/11/14/2.0.1-release/index.html - Breaking changes:
- [Tracking] Remove deprecated list APIs for experiments, models, and runs from Python, Java, R, and REST APIs 
  - #6785
  - #6786
  - #6787
  - #6788
  - #6800
  -  #6868
  - @dbczumar

**Comment by B-Step62** [comment]
DynamoDB is not a supported tracking backend store (it previously worked only via the third-party `dynaflow` layer), so `mlflow db upgrade` rejecting it is expected. Closing as out of scope; supported backends are SQL databases (SQLite/Postgres/MySQL/MSSQL).
