### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'pyenv'

### ISSUE THREAD

**Issue by ztxjack** [mlflow/mlflow#7387]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version
```
mlflow, version 2.0.2.dev0
```

### System information
```
Ubuntu 20.04 LTS
conda 4.10.3
conda installed libraries
```
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
adal                      1.2.7                    pypi_0    pypi
aiofiles                  22.1.0                   pypi_0    pypi
aiohttp                   3.8.3                    pypi_0    pypi
aiokafka                  0.8.0                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alembic                   1.8.1                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argcomplete               2.0.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
azure-common              1.1.28                   pypi_0    pypi
azure-core                1.26.1                   pypi_0    pypi
azure-graphrbac           0.61.1                   pypi_0    pypi
azure-mgmt-authorization  2.0.0                    pypi_0    pypi
azure-mgmt-containerregistry 10.0.0                   pypi_0    pypi
azure-mgmt-core           1.3.2                    pypi_0    pypi
azure-mgmt-keyvault       10.1.0                   pypi_0    pypi
azure-mgmt-resource       21.2.1                   pypi_0    pypi
azure-mgmt-storage        20.1.0                   pypi_0    pypi
azureml-core              1.47.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-tempfile        1.0                      pypi_0    pypi
backports-weakref         1.0.post1                pypi_0    pypi
bcrypt                    4.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    5.0.1                    pypi_0    pypi
boto3                     1.26.15                  pypi_0    pypi
botocore                  1.29.15                  pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
brotli-bin                1.0.9                h5eee18b_7    defaults
ca-certificates           2022.10.11           h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
cryptography              38.0.3                   pypi_0    pypi
cudatoolkit               11.0.221             h6bb024c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.11.0             pyhd3eb1b0_0    defaults
databricks-cli            0.17.3                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
docker                    6.0.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0    defaults
fastapi                   0.87.0                   pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
fftw                      3.3.9                h27cfd23_1    defaults
filelock                  3.8.0                    pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
fontconfig                2.13.1               hef1e5e3_1    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.12.1               h4a9f257_0    defaults
frozenlist                1.3.3                    pypi_0    pypi
gevent                    22.10.2                  pypi_0    pypi
geventhttpclient          2.0.2                    pypi_0    pypi
giflib                    5.2.1                h7b6447c_0    defaults
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
glib                      2.63.1               h5a9c865_0    defaults
google-api-core           2.10.2                   pypi_0    pypi
google-auth               2.14.1                   pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.6.0                    pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.4.0                    pypi_0    pypi
googleapis-common-protos  1.57.0                   pypi_0    pypi
greenlet                  2.0.1                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
gunicorn                  20.1.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       58.2                 he6710b0_3    defaults
idna                      3.4                      pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
ipykernel                 6.17.1                   pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.1.1            py38h06a4308_0    defaults
jpeg                      9e                   h7f8727e_0    defaults
jsonpickle                2.2.0                    pypi_0    pypi
jsonschema                4.17.0                   pypi_0    pypi
jupyter-client            7.4.7                    pypi_0    pypi
jupyter-core              5.0.0                    pypi_0    pypi
jupyter-server            1.23.2                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
kafka-python              2.0.2                    pypi_0    pypi
kiwisolver                1.4.2            py38h295c915_0    defaults
knack                     0.10.0                   pypi_0    pypi
kubernetes                25.3.0                   pypi_0    pypi
lcms2                     2.12                 h3be6417_0    defaults
lerc                      3.0                  h295c915_0    defaults
libbrotlicommon           1.0.9                h5eee18b_7    defaults
libbrotlidec              1.0.9                h5eee18b_7    defaults
libbrotlienc              1.0.9                h5eee18b_7    defaults
libdeflate                1.8                  h7f8727e_5    defaults
libedit                   3.1.20210910         h7f8727e_0    defaults
libffi                    3.2.1             hf484d3e_1007    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgfortran-ng            11.2.0               h00389a5_1    defaults
libgfortran5              11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtiff                   4.4.0                hecacb30_2    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libuv                     1.40.0               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp                   1.2.4                h11a3e52_0    defaults
libwebp-base              1.2.4                h5eee18b_0    defaults
libxcb                    1.15                 h7f8727e_0    defaults
libxml2                   2.9.14               h74e7548_0    defaults
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.9.3                h295c915_1    defaults
mako                      1.2.4                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3            py38h06a4308_0    defaults
matplotlib-base           3.5.3            py38hf590b9c_0    defaults
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h7f8727e_0    defaults
mkl_fft                   1.3.1            py38hd3c417c_0    defaults
mkl_random                1.2.2            py38h51133e4_0    defaults
mlflow                    2.0.2.dev0               pypi_0    pypi
mlserver                  1.2.0rc5                 pypi_0    pypi
mlserver-mlflow           1.2.0rc5                 pypi_0    pypi
msal                      1.20.0                   pypi_0    pypi
msal-extensions           1.0.0                    pypi_0    pypi
msrest                    0.7.1                    pypi_0    pypi
msrestazure               0.6.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
munkres                   1.1.4                      py_0    defaults
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.5                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3    defaults
ndg-httpsclient           0.5.1                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
ninja                     1.10.2               h06a4308_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja-base                1.10.2               hd09550d_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.4           py38h14f4228_0    defaults
numpy-base                1.23.4           py38h31eccc5_0    defaults
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
orjson                    3.8.2                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
paramiko                  2.12.0                   pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.10.2                   pypi_0    pypi
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py38hace64e9_1    defaults
pip                       22.2.2           py38h06a4308_0    defaults
pkginfo                   1.8.3                    pypi_0    pypi
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.4                    pypi_0    pypi
portalocker               2.6.0                    pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
prometheus-flask-exporter 0.21.0                   pypi_0    pypi
prompt-toolkit            3.0.32                   pypi_0    pypi
protobuf                  4.21.9                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-grpc-prometheus        0.7.0                    pypi_0    pypi
pyarrow                   10.0.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyjwt                     2.6.0                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyopenssl                 22.1.0                   pypi_0    pypi
pyparsing                 3.0.9            py38h06a4308_0    defaults
pyqt                      5.9.2            py38h05f1152_4    defaults
pyrsistent                0.19.2                   pypi_0    pypi
pysftp                    0.2.9                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.8.0                h0371630_2    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-dotenv             0.21.0                   pypi_0    pypi
python-rapidjson          1.9                      pypi_0    pypi
pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qt                        5.9.7                h5867ecd_1    defaults
querystring-parser        1.2.4                    pypi_0    pypi
readline                  7.0                  h7b6447c_5    defaults
requests                  2.28.1                   pypi_0    pypi
requests-auth-aws-sigv4   0.7                      pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
scikit-learn              1.1.3            py38h6a678d5_0    defaults
scipy                     1.9.3            py38h14f4228_0    defaults
secretstorage             3.3.3                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0    defaults
shap                      0.41.0                   pypi_0    pypi
sip                       4.19.13          py38h295c915_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
slicer                    0.0.7                    pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.4.44                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0    defaults
sqlparse                  0.4.3                    pypi_0    pypi
stack-data                0.6.1                    pypi_0    pypi
starlette                 0.21.0                   pypi_0    pypi
starlette-exporter        0.14.0                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
terminado                 0.17.0                   pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0    defaults
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torchvision               0.8.0                py38_cu110    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
tornado                   6.2              py38h5eee18b_0    defaults
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
tritonclient              2.28.0                   pypi_0    pypi
typing_extensions         4.3.0            py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.12                  pypi_0    pypi
uvicorn                   0.20.0                   pypi_0    pypi
uvloop                    0.17.0                   pypi_0    pypi
virtualenv                20.16.7                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.6                h5eee18b_0    defaults
yarl                      1.8.1                    pypi_0    pypi
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
zope-event                4.5.0                    pypi_0    pypi
zope-interface            5.5.2                    pypi_0    pypi
zstd                      1.5.2                ha4553b6_0    defaults
```

### Describe the problem

I've tried the command **mflow run .**  for several examples e.g. examples/sklearn_elasticnet_wine/ , examples/pytorch/MNIST
but all got above error

### Code to reproduce issue

run "mlflow run ." under
examples/sklearn_logistic_regression

### Stack trace
```
Traceback (most recent call last):
  File "/home/jack/anaconda3/envs/mlflow/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jack/Git/mlflow/mlflow/cli.py", line 201, in run
    projects.run(
  File "/home/jack/Git/mlflow/mlflow/projects/__init__.py", line 329, in run
    submitted_run_obj = _run(
  File "/home/jack/Git/mlflow/mlflow/projects/__init__.py", line 102, in _run
    submitted_run = backend.run(
  File "/home/jack/Git/mlflow/mlflow/projects/backend/local.py", line 145, in run
    python_bin_path = _install_python(python_env.python)
  File "/home/jack/Git/mlflow/mlflow/utils/virtualenv.py", line 124, in _install_python
    else _find_latest_installable_python_version(version)
  File "/home/jack/Git/mlflow/mlflow/utils/virtualenv.py", line 100, in _find_latest_installable_python_version
    lines = _exec_cmd(
  File "/home/jack/Git/mlflow/mlflow/utils/process.py", line 95, in _exec_cmd
    process = subprocess.Popen(
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jack/anaconda3/envs/mlflow/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ztxjack** [comment]
Could someone help to look at this issue? thanks.

**Comment by harupy** [comment]
Hi @ztxjack, you can try `mlflow run . --env-manager=local` or install pyenv.

**Comment by dbczumar** [comment]
Closing this, as `pyenv` is required to run MLflow Projects with the `virtualenv` environment manager. Thanks for the suggestions, @harupy , and thank you for using MLflow, @ztxjack !

**Comment by ztxjack** [comment]
Hi @harupy , @dbczumar 
Thanks for your suggestion I think ### mlflow run . --env-manager=local  for example cases. but do you know if there is any link or document that could give some instructions on the pyenv, conda related required dependency installation? I'm using conda env instead of virtualenv but got some other errors after install a version of
### pyenv 2.3.6-15-g13d85686
when run ### mlflow run . again
```
2022/11/24 10:06:04 INFO mlflow.utils.virtualenv: Installing python 3.8.15 if it does not exist
Downloading Python-3.8.15.tar.xz...
-> https://www.python.org/ftp/python/3.8.15/Python-3.8.15.tar.xz
Installing Python-3.8.15...

BUILD FAILED (Ubuntu 20.04 using python-build 2.3.6-15-g13d85686)

Inspect or clean up the working tree at /tmp/python-build.20221124100604.608859
Results logged to /tmp/python-build.20221124100604.608859.log

Last 10 log lines:
  File "/tmp/python-build.20221124100604.608859/Python-3.8.15/Lib/ensurepip/__init__.py", line 209, in _main
    return _bootstrap(
  File "/tmp/python-build.20221124100604.608859/Python-3.8.15/Lib/ensurepip/__init__.py", line 128, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/python-build.20221124100604.608859/Python-3.8.15/Lib/ensurepip/__init__.py", line 37, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "/tmp/python-build.20221124100604.608859/Python-3.8.15/Lib/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20221124100604.608859/Python-3.8.15/python', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpdawsbq0g/setuptools-56.0.0-py3-none-any.whl\', \'/tmp/tmpdawsbq0g/pip-22.0.4-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpdawsbq0g\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1198: install] Error 1
Traceback (most recent call last):
  File "/home/jack/myenv/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/jack/myenv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/myenv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jack/myenv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jack/myenv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/myenv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/cli.py", line 201, in run
    projects.run(
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 329, in run
    submitted_run_obj = _run(
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 102, in _run
    submitted_run = backend.run(
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/projects/backend/local.py", line 145, in run
    python_bin_path = _install_python(python_env.python)
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/utils/virtualenv.py", line 132, in _install_python
    _exec_cmd(
  File "/home/jack/myenv/lib/python3.8/site-packages/mlflow/utils/process.py", line 117, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['pyenv', 'install', '--skip-existing', '3.8.15']
```

**Comment by harupy** [comment]
@ztxjack Can you open `/tmp/python-build.20221124100604.608859.log` and check what's in this file?

**Comment by harupy** [comment]
You might need to install tools for building Python: https://github.com/pyenv/pyenv/wiki

**Comment by ztxjack** [comment]
Yes, I just checked out that log file and get the problem cause which is most likely as your speculation, and so I update and install the associated ubuntu dependencies and the above error does not occur again.
But I also see a very long span of time for the requirements installation.
Either run mlflow run . by default
and with network connection error when do the quiet installation after waiting for some time
```
**Command: ['bash', '-c', 'source /home/jack/.mlflow/envs/mlflow-db35c8b4d4bccc1772371ab0a30f42857fea089b/bin/activate && python -m pip install --quiet -r requirements.604f3ec109b844728566fcd25d5a73fe.txt']
**
or try to do it manually
``` 
pip install -r requirements/dev-requirements.txt
```
but only see hang-up there for a long period of time.
Do you have any better idea on this?

**Comment by beybars1** [comment]
Hi there,
Thanks @harupy for your advice, it works with `--env-manager` flag.
How can it be resolved without `--env-manager` flag while working in the python venv? (not `virtualenv`)
