### ISSUE TITLE
"mlflow models predict" CLI command no longer works

### ISSUE THREAD

**Issue by bstollnitz** [mlflow/mlflow#7497]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.0

### System information

- OS: Ubuntu 22.04.1
- python==3.10.4

### Describe the problem

I train an MLflow model locally, and want to use the MLflow CLI to make a prediction. I'm using this project: https://github.com/bstollnitz/aml_command_sdk.

Before, I could make a prediction using this command:
mlflow models predict --model-uri "model" --input-path "test_data/images.csv" --content-type csv

Now, if I do that, I get the following error:

2022/12/07 20:13:32 INFO mlflow.pyfunc.backend: === Running command 'source /home/bstollnitz/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-1433535863ef053dea37ca28e47daf2bbabfb74f 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///home/bstollnitz/git/aml_command_cli/aml_command_cli/model', input_path='test_data/images.csv', output_path=None, content_type='csv', json_format='split')"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: _predict() got an unexpected keyword argument 'json_format'
Traceback (most recent call last):
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/models/cli.py", line 125, in predict
    return _get_flavor_backend(
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/pyfunc/backend.py", line 126, in predict
    return _execute_in_conda_env(
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/pyfunc/backend.py", line 389, in _execute_in_conda_env
    raise Exception(
Exception: Command 'source /home/bstollnitz/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-1433535863ef053dea37ca28e47daf2bbabfb74f 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///home/bstollnitz/git/aml_command_cli/aml_command_cli/model', input_path='test_data/images.csv', output_path=None, content_type='csv', json_format='split')"' returned non zero return code. Return code = 1

I'm able to work around it by using the following command:

mlflow models predict --model-uri "model" --input-path "test_data/images.csv" --content-type csv --env-manager local

This is what I think is going on: My conda environment in this project uses MLflow 1.26. If I don’t pass the “env-manager” argument, MLflow will “conda activate” an environment with MLflow 2.0 by default.  It turns out that the “predict” function in 2.0 doesn’t take a “json_format” argument, so it fails. The “env-manager” argument fixes this because it tells MLflow to use my local environment instead, with MLflow 1.26.

### Code to reproduce issue

Use this project:
https://github.com/bstollnitz/aml_command_sdk

Under "Run and Debug" on VS Code's left navigation, choose the "Train locally" run configuration and press F5.

Then execute the following:
cd aml_command_sdk
mlflow models predict --model-uri "model" --input-path "test_data/images.csv" --content-type csv

### Stack trace

2022/12/07 20:13:32 INFO mlflow.pyfunc.backend: === Running command 'source /home/bstollnitz/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-1433535863ef053dea37ca28e47daf2bbabfb74f 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///home/bstollnitz/git/aml_command_cli/aml_command_cli/model', input_path='test_data/images.csv', output_path=None, content_type='csv', json_format='split')"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: _predict() got an unexpected keyword argument 'json_format'
Traceback (most recent call last):
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/models/cli.py", line 125, in predict
    return _get_flavor_backend(
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/pyfunc/backend.py", line 126, in predict
    return _execute_in_conda_env(
  File "/home/bstollnitz/miniconda3/envs/aml_command_cli/lib/python3.10/site-packages/mlflow/pyfunc/backend.py", line 389, in _execute_in_conda_env
    raise Exception(
Exception: Command 'source /home/bstollnitz/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-1433535863ef053dea37ca28e47daf2bbabfb74f 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///home/bstollnitz/git/aml_command_cli/aml_command_cli/model', input_path='test_data/images.csv', output_path=None, content_type='csv', json_format='split')"' returned non zero return code. Return code = 1

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by bstollnitz** [comment]
Hi! The conda I used to create my model does pin MLflow to 1.26.0. Here's the file: https://github.com/bstollnitz/aml_command_sdk/blob/master/aml_command_sdk/cloud/conda.yml

And here are the contents of the file:

channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.9.10
  - pytorch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.64.0
  - mlflow==1.26.0
  - pip==21.2.4
  - pip:
      - azure-ai-ml==1.2.0
      - azureml-mlflow==1.48.0

Unfortunately I can't update to MLflow 2.0 at this point, due to other issues.
