### ISSUE TITLE
[BUG] Can't gc a run with Postgres and S3 artifact-serving

### ISSUE THREAD

**Issue by ddl-ebrown** [mlflow/mlflow#7558]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- Debian Buster Slim 10.13
- Python 3.8.14

### Describe the problem

Performing a `mlflow gc` fails to delete artifacts when the backend store is a Postgres database and the artifact store is S3.

### Tracking information

Logged from a client notebook

```
MLflow version: 2.0.1
Tracking URI: http://mlflow.domino-platform:5000/
Artifact URI: mlflow-artifacts:/1/0236553fa57241c2a08e18870a3556a1/artifacts
System information: Linux #1 SMP Wed Nov 2 17:44:17 UTC 2022
Python version: 3.9.15
MLflow version: 2.0.1
MLflow module location: /opt/conda/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: http://mlflow.domino-platform:5000/
Registry URI: http://mlflow.domino-platform:5000/
Active experiment ID: 1
Active run ID: 0236553fa57241c2a08e18870a3556a1
Active run artifact URI: mlflow-artifacts:/1/0236553fa57241c2a08e18870a3556a1/artifacts
MLflow environment variables: {
    "MLFLOW_TRACKING_URI": "http://mlflow.domino-platform:5000/",
    "MLFLOW_TRACKING_TOKEN": "eyJhbGciOiJIUzI1NiJ9.CnsKImRvbWlub19hcGlfa2V5IjogIjY1Zjk2Yzk4YjExMzE4MGZmNmI0MzMyOGNmMTVhMzdiM2JmODI1YTlkZTFlYjNkOTFhOGQ0MjZhNWJkYTllZTgiLAoiZG9taW5vX3J1bl9pZCI6ICI2MzljYmIzMjk2MjY4MTI1ZDY3NmI2MWEiLAoiZG9taW5vX3Byb2plY3RfaWQiOiAiNjM5MmJjZmY5ZTNhNTEzMzUzMmFlYWU0IiwKImRvbWlub19wcm9qZWN0X25hbWUiOiAicXVpY2stc3RhcnQiLAoidGFncyI6IHsKICAiRE9NSU5PX1BST0pFQ1RfT1dORVIiOiAiaW50ZWdyYXRpb24tdGVzdCIsCiAgIm1sZmxvdy5zb3VyY2UudHlwZSI6ICJOT1RFQk9PSyIKfX0K.wl49DmPEf8_4Wp4ZTYbuBLUg9hvUmhfmW_C6gT2ShEc"
}
MLflow dependencies: {
    "click": "8.1.3",
    "cloudpickle": "2.2.0",
    "databricks-cli": "0.17.4",
    "entrypoints": "0.4",
    "gitpython": "3.1.29",
    "pyyaml": "6.0",
    "protobuf": "4.21.12",
    "pytz": "2022.6",
    "requests": "2.28.1",
    "packaging": "22.0",
    "importlib-metadata": "5.1.0",
    "sqlparse": "0.4.3",
    "alembic": "1.9.0",
    "docker": "6.0.1",
    "Flask": "2.2.2",
    "numpy": "1.23.3",
    "scipy": "1.9.2",
    "pandas": "1.5.0",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.45",
    "scikit-learn": "1.1.2",
    "pyarrow": "8.0.0",
    "shap": "0.41.0",
    "markdown": "3.4.1",
    "matplotlib": "3.6.2",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}
```

### Code to reproduce issue

Setup tracking server with proxied artifact access (storing in S3) and a Postgres database for experiment / run storage.

Assuming the following archived run with an artifact:

> mlflow runs describe --run-id ee7b8172bf9742a0943205672682243d

```
{
    "info": {
        "artifact_uri": "mlflow-artifacts:/1/ee7b8172bf9742a0943205672682243d/artifacts",
        "end_time": 1671067796774,
        "experiment_id": "1",
        "lifecycle_stage": "deleted",
        "run_id": "ee7b8172bf9742a0943205672682243d",
        "run_name": "crawling-cow-833",
        "run_uuid": "ee7b8172bf9742a0943205672682243d",
        "start_time": 1671067734932,
        "status": "FAILED",
        "user_id": "ubuntu"
    },
    "data": {
        "metrics": {
            "foo": 1.0
        },
        "params": {
            "default": "0.2"
        },
        "tags": {
            "mlflow.source.type": "NOTEBOOK",
            "mlflow.user": "integration-test",
            "mlflow.source.name": "/opt/conda/lib/python3.9/site-packages/ipykernel_launcher.py",
            "mlflow.runName": "crawling-cow-833"
        }
    }
}
```

> mlflow artifacts list --run-id ee7b8172bf9742a0943205672682243d

```
[{
  "path": "requirements_apps.txt",
  "is_dir": false,
  "file_size": 1014
}]
```

> mlflow artifacts download --run-id ee7b8172bf9742a0943205672682243d -a requirements_apps.txt

```
/tmp/tmpm39f2uuw/requirements_apps.txt
```

> cat /tmp/tmpm39f2uuw/requirements_apps.txt

```
# Requirements for the Python/Flask app publishing example.
flask>=1.0

# Requirements for the Python/Dash app publishing example.
dash~=0.21.0
dash-core-components~=0.21.1
dash-html-components~=0.9.0
dash-renderer~=0.12.1
dash-table-experiments~=0.6.0
```

> mlflow gc --backend-store-uri postgresql://postgres:${SECRET_PASSWORD}@mlflow-postgresql:5432/mlflow --run-ids ee7b8172bf9742a0943205672682243d

```
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlflow/cli.py", line 459, in gc
    backend_store = _get_store(backend_store_uri, None)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 188, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 149, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 153, in __init__
    mkdir(local_file_uri_to_path(default_artifact_root))
  File "/usr/local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 120, in mkdir
    raise e
  File "/usr/local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 117, in mkdir
    os.makedirs(target)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './mlruns'
```

### Stack trace

```
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlflow/cli.py", line 459, in gc
    backend_store = _get_store(backend_store_uri, None)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 188, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 149, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 153, in __init__
    mkdir(local_file_uri_to_path(default_artifact_root))
  File "/usr/local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 120, in mkdir
    raise e
  File "/usr/local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 117, in mkdir
    os.makedirs(target)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './mlruns'
```

### Other info / logs

I made sure that the environment had all the MLFLOW env vars configured (so that the CLI might better understand artifacts storage configuration) -- that made no impact on the result. 

I don't think `gc` uses APIs from the tracking server, so it seems to me that `gc` should support a `--default-artifact-root` cli switch to go along  with `--backend-store-uri`

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by RodrigoCasarCQ** [comment]
same problem here

**Comment by M4nouel** [comment]
Hi @BenWilson2 @dbczumar @harupy @WeichenXu123,

If I may, here's a fix.
Could you tell me what you think about it ?

# How to test (tested on Linux)

You can place this docker compose file at the root of your MLflow repo:

<details>
  <summary>docker-compose.yml content, Click me</summary>
  
  ```yaml
version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio@sha256:beb5fd646b298e0e732c186215926d5ebf8cb0d2ff573bba17b4c4b22ec90ade
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minioPwd
        volumes:
            - minio_data:/data
        logging:
            driver: "json-file"
            options:
                max-file: 10
                max-size: 20m

    mc:
        image: minio/mc@sha256:c734ae7fd20606d4b2c0cf9ef25f22e5f4185406363b9260e7c16f6fe527cfd7
        depends_on:
            - minio
        entrypoint: >
            bash -c "until curl http://minio:9001; do sleep 1; done && 
            /usr/bin/mc alias set minio http://minio:9000 minio minioPwd && 
            /usr/bin/mc mb minio/mlflow;
            exit 0;"


    db:
        restart: always
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pgPassWd
            - POSTGRES_DB=mlflow
        volumes:
            - dbdata:/var/lib/postgresql/data
        logging:
            driver: "json-file"
            options:
                max-file: 10
                max-size: 20m

    mlflow:
        restart: always
        image: ghcr.io/mlflow/mlflow:latest
        container_name: mlflow
        depends_on:
            - mc
            - db
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=minio
            - AWS_SECRET_ACCESS_KEY=minioPwd
            - MLFLOW_HTTP_REQUEST_TIMEOUT=1200
        volumes:
          - ./:/mlflow
        command: >
            bash -c "pip install boto3 psycopg2-binary==2.9.9 && 
            mlflow server 
            --backend-store-uri postgresql://postgres:pgPassWd@db:5432/mlflow 
            --artifacts-destination s3://mlflow/ 
            --serve-artifacts --host 0.0.0.0 --gunicorn-opts '--timeout 1200'"
        logging:
            driver: "json-file"
            options:
                max-file: 10
                max-size: 20m

volumes:
    dbdata:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /tmp/mlflowgc/postgres
    minio_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /tmp/mlflowgc/minio

# to start the services:
# mkdir -p /tmp/mlflowgc/postgres /tmp/mlflowgc/minio && docker compose up
# to remove the services:
# ctrl+c and docker compose down --volumes
# don't forget the "--volumes" flag to remove the volumes as well !
# clean the data like this "sudo rm -rf /tmp/mlflowgc"

  ```
</details>


And then run this command to start locally a MLflow server with Postgres and Minio (S3 store):
```bash
mkdir -p /tmp/mlflowgc/postgres /tmp/mlflowgc/minio && docker compose up
```
Then make sure you can reach http://localhost:5000/ (MLflow server) and http://localhost:9001/buckets (Minio server, user: minio pwd: minioPwd).


In another terminal open a Python console like this:
```bash
MLFLOW_TRACKING_URI=http://localhost:5000 MLFLOW_EXPERIMENT_ID=0 python
```

Then copy/paste this code to create some runs:

```python
import tempfile
import mlflow

def test():
  with mlflow.start_run(run_name="without_artifact", tags={"contains_artifacts":"False"}) as run:
      print(f"run without artifact {run.info.run_id=}")
  with mlflow.start_run(run_name="with_artifact", tags={"contains_artifacts":"True"}) as run:
      with tempfile.NamedTemporaryFile(suffix=".txt") as fp:
          fp.write(b'Hello world!')
          fp.flush()
          mlflow.log_artifact(fp.name)
      print(f"run with artifact {run.info.run_id=}")

test()
```


You can navigate again to http://localhost:5000/ and http://localhost:9001/buckets (user: minio pwd: minioPwd), to display the runs created in MLflow and the artifact stored in Minio.
**In MLflow UI, delete the run containing the artifact,** then check that the artifact is still in Minio's "mlflow" bucket.


Now we can execute `mlflow gc`.
In another terminal, open a bash terminal within the MLflow container:
```bash
docker exec -it mlflow bash
```

This container mounts your local MLflow repo on /mlflow. `cd` within it and activate the dev venv like this:
```bash
cd /mlflow && source /mlflow/.venvs/mlflow-dev/bin/activate && python -m mlflow --version
```

And run `mlflow gc` like this:
```bash
MLFLOW_TRACKING_URI=http://localhost:5000 python -m mlflow gc \
--backend-store-uri postgresql://postgres:pgPassWd@db:5432/mlflow \
--artifacts-destination s3://mlflow/
```


Finally, navigate to Minio's "mlflow" bucket (http://localhost:9001/buckets) to check that the artifact has been removed.

**Comment by M4nouel** [comment]
Hi @BenWilson2 , could you let me know if you need a rebase ?
