### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by praksharma** [mlflow/mlflow#7563]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.5
- **MLflow installed from (source or binary)**: from pip
- **MLflow version (run ``mlflow --version``)**: 1.30.0
- **Python version**: 3.9.13

### Code to reproduce issue

```sh
╭─    ~/De/Ph/Ph/PI/16/3/1/2/3/2. 200k iterations            ✔  base  
╰─ mlflow ui                
Traceback (most recent call last):
  File "/home/hell/anaconda3/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/hell/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/hell/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/hell/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hell/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hell/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/hell/anaconda3/lib/python3.9/site-packages/mlflow/cli.py", line 312, in ui
    from mlflow.server import _run_server
  File "/home/hell/anaconda3/lib/python3.9/site-packages/mlflow/server/__init__.py", line 6, in <module>
    from flask import Flask, send_from_directory, Response
  File "/home/hell/anaconda3/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/hell/anaconda3/lib/python3.9/site-packages/jinja2/__init__.py)
```

### Describe the problem

Can't use the Mlflow. Looks like [this](https://stackoverflow.com/a/71721006/14598633) post is helpful. But still can't run Mlflow.

**Comment by harupy** [comment]
@praksharma I think updating Flask can fix the issue. See https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2.

**Comment by praksharma** [comment]
yes, installing the latest version of flask solves the issue. thank you.
