### ISSUE TITLE
[BUG] classification recipe fails in transform step due to missing positive_class specifier

### ISSUE THREAD

**Issue by floschl** [mlflow/mlflow#7641]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow: 2.1.1

### System information

- **Ubuntu 22.04**:
- **Python version 3.10 **:

### Describe the problem

I fail to run the notebook from the classification recipe:
https://github.com/mlflow/recipes-examples/blob/main/classification/notebooks/jupyter.ipynb

where the transform fails due to this error
`MlflowException: Failed to run step 'transform' of recipe 'classification'. An error was encountered while running step 'transform': Traceback (most recent call last):
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/step.py", line 139, in run
    self.step_card = self._run(output_directory=output_directory)
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/steps/transform.py", line 105, in _run
    validate_classification_config(self.task, self.positive_class, train_df, self.target_col)
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/utils/step.py", line 182, in validate_classification_config
    raise MlflowException(
mlflow.exceptions.MlflowException: `positive_class` must be specified for classification/v1 recipes.`

### Code to reproduce issue

Step to reproduce, run this notebook:
https://github.com/mlflow/recipes-examples/blob/main/classification/notebooks/jupyter.ipynb

This cell fails:
r.run("transform")

### Stack trace

The following error is produced, although positive_class is correctly noted in the recipe.yaml (https://github.com/mlflow/recipes-examples/blob/main/classification/recipe.yaml , l. 17)

`MlflowException: Failed to run step 'transform' of recipe 'classification'. An error was encountered while running step 'transform': Traceback (most recent call last):
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/step.py", line 139, in run
    self.step_card = self._run(output_directory=output_directory)
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/steps/transform.py", line 105, in _run
    validate_classification_config(self.task, self.positive_class, train_df, self.target_col)
  File "/home/schlembach/miniconda3/envs/mlflow/lib/python3.10/site-packages/mlflow/recipes/utils/step.py", line 182, in validate_classification_config
    raise MlflowException(
mlflow.exceptions.MlflowException: `positive_class` must be specified for classification/v1 recipes.`

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sunishsheth2009** [comment]
Thank you for reporting this issue. We have merged a fix in master: https://github.com/mlflow/mlflow/pull/7626
Let me know if that solves the problem for you. :)

**Comment by floschl** [comment]
Thank you very much @sunishsheth2009! The commit related to the fix looks promising. 
After installing mlflow@master state into my conda environment and runningn the classification recipe, everything works like a charm now, thanks!
Nevertheless, installing it this way lacks the static libs to launch the Tracking UI (via mlflow ui). Is there a way how I could include both the static libs and the latest commits, e.g. with a nightly build of mlflow?

**Comment by digvijaygunjal** [comment]
Is there a release plan / timeline for this fix?

**Comment by B-Step62** [comment]
MLflow Recipes is deprecated and is no longer being fixed. Closing as obsolete.
