### ISSUE TITLE
[BUG] Unable to store large artifact to Minio backend via load_artifact

### ISSUE THREAD

**Issue by agapebondservant** [mlflow/mlflow#7702]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS client, Linux server-side
- **Python version**: 3.10.3

### Describe the problem

I get a "Max Retries Exceeded" error when I attempt to log a moderately large artifact to MLFlow when using a Minio backend (deployed on AWS).  I am running a Jupyter notebook on my local machine. The file is 184MB in size. I'm able to log other files/artifacts with no issues. This occurs even after bumping up the MLFLOW_HTTP_REQUEST_TIMEOUT to a very high number (3600). The upload speed on my local machine is also very fast (~470Mbps/s).

### Tracking information

```shell

System information: Darwin Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64
Python version: 3.10.3
MLflow version: 2.0.1
MLflow module location: /Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI:redacted
Registry URI: redacted
MLflow environment variables: {
    "MLFLOW_HTTP_REQUEST_TIMEOUT": "3600"
}
MLflow dependencies: {
    "click": "8.0.4",
    "cloudpickle": "2.0.0",
    "databricks-cli": "0.16.4",
    "entrypoints": "0.4",
    "gitpython": "3.1.27",
    "pyyaml": "5.4.1",
    "protobuf": "3.19.6",
    "pytz": "2022.1",
    "requests": "2.27.1",
    "packaging": "21.3",
    "importlib-metadata": "4.11.3",
    "sqlparse": "0.4.2",
    "alembic": "1.4.1",
    "docker": "5.0.3",
    "Flask": "2.0.3",
    "numpy": "1.23.1",
    "scipy": "1.8.1",
    "pandas": "1.5.0",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.39",
    "scikit-learn": "1.1.1",
    "pyarrow": "8.0.0",
    "shap": "0.41.0",
    "markdown": "3.4.1",
    "matplotlib": "3.5.2",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}
```

### Code to reproduce issue

```
import mlflow
from mlflow import MlflowClient
with mlflow.start_run() as active_run:
    client = MlflowClient()
    artifact_run_id = active_run.info.run_id
    client.log_artifact(artifact_run_id, 'cifar_data.hkl')    # <-- cifar_data is 184MB large
```

### Stack trace

```
Traceback (most recent call last):
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 166, in http_request
    return _get_http_response_with_retries(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 97, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/5y/9xdc_js94k1dwlvwf8b6hxs80000gp/T/ipykernel_29600/3481593504.py", line 38, in upload_dataset
    client.log_artifact(artifact_run_id, 'cifar_data.hkl')
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1002, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 416, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 184, in http_request
    raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to [http://redacted/api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl](http://mlflow.tanzudatatap.ml/api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl) failed with exception HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))
Traceback (most recent call last):
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 166, in http_request
    return _get_http_response_with_retries(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 97, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/5y/9xdc_js94k1dwlvwf8b6hxs80000gp/T/ipykernel_29600/3481593504.py", line 38, in upload_dataset
    client.log_artifact(artifact_run_id, 'cifar_data.hkl')
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1002, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 416, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 184, in http_request
    raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to [http://redacted/api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl](http://mlflow.tanzudatatap.ml/api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl) failed with exception HTTPConnectionPool(host='redacted', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/ab7ff1a16e4c4d7ab5824b4de51208d7/artifacts/cifar_data.hkl (Caused by ResponseError('too many 503 error responses'))
DEBUG:urllib3.connectionpool:Resetting dropped connection: redacted

DEBUG:urllib3.connectionpool:http://redacted:80 "POST /api/2.0/mlflow/runs/update HTTP/1.1" 200 None
```

### Other info / logs

```

```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@agapebondservant Thanks for reporting! I'm taking a look.

**Comment by harupy** [comment]
@agapebondservant Can you try running your mlflow server with `--gunicorn-opts="--timeout <large value>"`?

**Comment by agapebondservant** [comment]
@harupy That did it! Thanks for your help!

**Comment by harupy** [comment]
Fantastic!
