### ISSUE TITLE
[BUG] mlflow does not work with PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by befelix** [mlflow/mlflow#7789]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1

### System information

- Ubuntu 20.04
- Python 3.10

### Describe the problem

`mlflow` internally shares docstrings by adding strings to `fun.__doc__`. However, when running in a `PYTHONOPTIMIZE=2` setting, these docstrings are `None`, leading to an exception. 

### Code to reproduce issue

```bash
PYTHONOPTIMIZE=2 mlflow --version
```

### Stack trace

```bash
Traceback (most recent call last):
  File "/home/bfe2rng/.conda/envs/test/bin/mlflow", line 5, in <module>
    from mlflow.cli import cli
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/__init__.py", line 41, in <module>
    from mlflow import projects  # pylint: disable=unused-import
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 27, in <module>
    from mlflow.projects.backend import loader
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/backend/loader.py", line 4, in <module>
    from mlflow.projects.backend.local import LocalBackend
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/projects/backend/local.py", line 31, in <module>
    from mlflow.utils.virtualenv import (
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/virtualenv.py", line 11, in <module>
    from mlflow.models.model import Model, MLMODEL_FILE_NAME
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/models/__init__.py", line 99, in <module>
    from .utils import ModelInputExample, validate_schema  # pylint: disable=unused-import
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/models/utils.py", line 701, in <module>
    def add_libraries_to_model(model_uri, run_id=None, registered_model_name=None):
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/annotations.py", line 20, in experimental
    return _experimental(api=api_or_type, api_type="function")
  File "/home/bfe2rng/.conda/envs/test/lib/python3.10/site-packages/mlflow/utils/annotations.py", line 30, in _experimental
    api.__doc__ = notice + api.__doc__
TypeError: can only concatenate str (not "NoneType") to str
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@befelix Thank you for filing this issue. Can you try out the branch at https://github.com/mlflow/mlflow/pull/7791 and let me know if this resolves the issue?

**Comment by befelix** [comment]
Oh wow, thank you for the super fast fix @dbczumar
