### ISSUE TITLE
[BUG] mlflow giving following exception: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '' 

### ISSUE THREAD

**Issue by aaparikh** [mlflow/mlflow#7795]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Ventura 13.1 (22C65)
- **Python version**: 3.9.15

### Describe the problem

I am trying to use mlflow with yolov5 to solve a computer vision usecase.
I am loading `yolov5` from pytorch hub.

The issue I am facing is, when I include a piece of code to set the tracking uri and run the code then I get an error saying that API request to endpoint failed with error code 403.

However, when I remove this piece of code and run the code then the yolov5 model is geting logged properly.

Piece of code: `mlflow.set_tracking_uri("http://localhost:5000")`

### Tracking information

`mlflow.doctor()` command output
```shell
System information: Darwin Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
Python version: 3.9.15
MLflow version: 2.1.1
MLflow module location: /Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///Users/{some_path}/Mlflow%20yolo%20implementation/mlruns
Registry URI: file:///{some_path}/Mlflow%20yolo%20implementation/mlruns
MLflow dependencies: 
  Flask: 2.2.2
  Jinja2: 3.1.2
  alembic: 1.9.2
  click: 8.1.3
  cloudpickle: 2.2.0
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.30
  gunicorn: 20.1.0
  importlib-metadata: 5.2.0
  markdown: 3.4.1
  matplotlib: 3.6.2
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.2
  protobuf: 3.20.3
  pyarrow: 10.0.1
  pytz: 2022.7
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 1.2.0
  scipy: 1.9.3
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
```

The command that was used to launch tracking server
```shell
mlflow server --backend-store-uri sqlite:///pySSD.db --default-artifact-root ./artifacts --host 127.0.0.1 --port 5555
```

### Code to reproduce issue

```python
import mlflow
import torch
import cv2

#helper function to get experiment id
def get_experiment_id(name):
    exp = mlflow.get_experiment_by_name(name)
    if exp is None:
      exp_id = mlflow.create_experiment(name)
      return exp_id
    return exp.experiment_id

#Implementing mlflow
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
exp_id = get_experiment_id("yolov5")
model_name = "YoloModel"

#This line of code, when included is causing an error
#-----------------------------------------------------
mlflow.set_tracking_uri("http://localhost:5000")
#-----------------------------------------------------

with mlflow.start_run(run_name="PARENT_RUN",experiment_id=exp_id) as parent_run:
    res = model.train(data="coco128.yaml", epochs=1, imgsz=640)
    mlflow.pytorch.log_model(
       model, 
       "model",
       registered_model_name=model_name
       )
    mlflow.end_run()

model = mlflow.pytorch.load_model(
    model_uri=f"models:/{model_name}/latest"
)

image_path = 'https://ultralytics.com/images/bus.jpg'
img=cv2.imread(image_path)
results=model(img)
results.show()
```

### Stack trace

```
YOLOv5 🚀 2022-9-5 Python-3.9.15 torch-2.0.0.dev20221222 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "/Users/atharvaparikh/some_path/Mlflow yolo implementation/final_file.py", line 19, in <module>
    with mlflow.start_run(run_name="PARENT_RUN",experiment_id=exp_id) as parent_run:
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 349, in start_run
    active_run_obj = client.create_run(
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/client.py", line 270, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 131, in create_run
    return self.store.create_run(
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
```

### Other info / logs

Logs generated when following command is run
`mlflow server --backend-store-uri sqlite:///pySSD.db --default-artifact-root ./artifacts --host 127.0.0.1 --port 5555
`:
```
[2023-02-06 10:46:06 +0530] [7494] [INFO] Starting gunicorn 20.1.0
[2023-02-06 10:46:06 +0530] [7494] [INFO] Listening at: http://127.0.0.1:5555 (7494)
[2023-02-06 10:46:06 +0530] [7494] [INFO] Using worker: sync
[2023-02-06 10:46:06 +0530] [7495] [INFO] Booting worker with pid: 7495
[2023-02-06 10:46:06 +0530] [7496] [INFO] Booting worker with pid: 7496
[2023-02-06 10:46:06 +0530] [7497] [INFO] Booting worker with pid: 7497
[2023-02-06 10:46:06 +0530] [7498] [INFO] Booting worker with pid: 7498
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by subramaniam02** [comment]
@aaparikh Based on the details provided, Tracking server is running on port number `5555`.  mlflow.set_tracking_uri is using port number `5000`  change it to `5555`.

**Comment by aaparikh** [comment]
Hey, thanks for the suggestion.
I did change the uri but another error appeared that says
`mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: No Experiment with id=433051632486373249 exists`

Following is the traceback that occured.
```shell
Traceback (most recent call last):
  File "/Users/{some_path}/Mlflow yolo implementation/final_file.py", line 20, in <module>
    with mlflow.start_run(run_name="PARENT_RUN",experiment_id=exp_id) as parent_run:
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 349, in start_run
    active_run_obj = client.create_run(
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/client.py", line 270, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 131, in create_run
    return self.store.create_run(
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/atharvaparikh/miniconda3/envs/torch/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: No Experiment with id=433051632486373249 exists
```

**Comment by subramaniam02** [comment]
`mlflow.set_tracking_uri("http://localhost:5000")` should be done before any mlflow operation.
```
import mlflow
import torch
import cv2



#This line of code, when included is causing an error
#-----------------------------------------------------
mlflow.set_tracking_uri("http://localhost:5000")
#-----------------------------------------------------

#helper function to get experiment id
def get_experiment_id(name):
    exp = mlflow.get_experiment_by_name(name)
    if exp is None:
      exp_id = mlflow.create_experiment(name)
      return exp_id
    return exp.experiment_id

#Implementing mlflow
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
exp_id = get_experiment_id("yolov5")
model_name = "YoloModel"

with mlflow.start_run(run_name="PARENT_RUN",experiment_id=exp_id) as parent_run:
    res = model.train(data="coco128.yaml", epochs=1, imgsz=640)
    mlflow.pytorch.log_model(
       model, 
       "model",
       registered_model_name=model_name
       )
    mlflow.end_run()

model = mlflow.pytorch.load_model(
    model_uri=f"models:/{model_name}/latest"
)

image_path = 'https://ultralytics.com/images/bus.jpg'
img=cv2.imread(image_path)
results=model(img)
results.show()
```

**Comment by dbczumar** [comment]
Thank you, @subramaniam02! @aaparikh Since the issue appears to be resolved, I'm going to go ahead and close it. Please feel free to reopen this if the problem persists.

**Comment by DeependraParichha1004** [comment]
mlflow, version 2.3.1
Python 3.8.10
If I'm setting the URI  of dagshub then it gives the below error, but when it is set to a local file(system) it is working perfectly fine.

**My code**:-

import os
import warnings
import sys

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from urllib.parse import urlparse
import mlflow
from mlflow.models.signature import infer_signature
import mlflow.sklearn

import logging

logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)

def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2

if __name__ == "__main__":
    warnings.filterwarnings("ignore")
    np.random.seed(40)

    # Read the wine-quality csv file from the URL
    csv_url = (
        "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-red.csv"
    )
    try:
        data = pd.read_csv("wine-quality.csv", sep=",")
    except Exception as e:
        logger.exception(
            "Unable to download training & test CSV, check your internet connection. Error: %s", e
        )

    # Split the data into training and test sets. (0.75, 0.25) split.
    train, test = train_test_split(data)

    # The predicted column is "quality" which is a scalar from [3, 9]
    train_x = train.drop(["quality"], axis=1)
    test_x = test.drop(["quality"], axis=1)
    train_y = train[["quality"]]
    test_y = test[["quality"]]

    alpha = 0.5
    l1_ratio = 0.5

    with mlflow.start_run():
        lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
        lr.fit(train_x, train_y)

        predicted_qualities = lr.predict(test_x)

        (rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)

        print("Elasticnet model (alpha={:f}, l1_ratio={:f}):".format(alpha, l1_ratio))
        print("  RMSE: %s" % rmse)
        print("  MAE: %s" % mae)
        print("  R2: %s" % r2)

        mlflow.log_param("alpha", alpha)
        mlflow.log_param("l1_ratio", l1_ratio)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("r2", r2)
        mlflow.log_metric("mae", mae)

        
        # # For remote server only (Dagshub)
        remote_server_uri = "https://dagshub.com/DeependraParichha1004/MLflow.mlflow"
        mlflow.set_tracking_uri(remote_server_uri)
        
        tracking_url_type_store = urlparse(mlflow.get_tracking_uri()).scheme

        # Model registry does not work with file store
        if tracking_url_type_store != "file":
            # Register the model
            # There are other ways to use the Model Registry, which depends on the use case,
            # please refer to the doc for more information:
            # https://mlflow.org/docs/latest/model-registry.html#api-workflow
            mlflow.sklearn.log_model(
                lr, "model", registered_model_name="ElasticnetWineModel")
        else:
            mlflow.sklearn.log_model(lr, "model")


**Error**:-
Traceback (most recent call last):
  File "example.py", line 100, in <module>
    mlflow.sklearn.log_model(
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\sklearn\__init__.py", line 424, in log_model
    return Model.log(
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\models\model.py", line 548, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\fluent.py", line 818, in log_artifacts        
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\client.py", line 1074, in log_artifacts       
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 412, in _get_artifact_repo
    run = self.get_run(run_id)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 134, in get_run    
    response_proto = self._call_endpoint(GetRun, req_body)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\utils\rest_utils.py", line 303, in call_endpoint       
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\utils\rest_utils.py", line 233, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/get failed with error code 400 != 200. Response body: '"repo not associated with run"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    end_run(RunStatus.to_string(status))
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\fluent.py", line 394, in end_run
    MlflowClient().set_terminated(run.info.run_id, status)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\client.py", line 1543, in set_terminated
    self._tracking_client.set_terminated(run_id, status, end_time)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 485, in set_terminated
    self.store.update_run_info(
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 148, in update_run_info
    response_proto = self._call_endpoint(UpdateRun, req_body)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\utils\rest_utils.py", line 303, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\OneDrive\Desktop\Git\madewithml\venv\lib\site-packages\mlflow\utils\rest_utils.py", line 233, in verify_rest_response    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/update failed with error code 403 != 200.

**Comment by yalegria** [comment]
I got this error while executing a python file in a venv environment.

**Comment by Nisargak18** [comment]
heyy!!!
I got these errors
File "C:\Users\kavya\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "c:\users\kavya\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "c:\users\kavya\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 66, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 402, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 265, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
Traceback (most recent call last):
  File "C:\Users\kavya\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 60, in <module>
    raise e
  File "C:\Users\kavya\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "c:\users\kavya\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "c:\users\kavya\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 66, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 402, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\kavya\miniconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 265, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
(kidney)
