### ISSUE TITLE
Spark dataframes with columns containing vectors cannot be scored with MLflow PySpark model UDFs

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#782]
### Describe the problem
MLflow models can be represented as Spark UDFs for inference. However, the UDF representation of a PySpark model is unable to evaluate Spark DataFrames whose columns contain vectors. For example, consider the following DataFrame definition:

```
nested_df = spark.createDataFrame([
  ("This is a test".split(" "), )
], ["0"])
```

The DataFrame `nested_df` contains a single row and column. The row contains a *vector* of strings. When `nested_df` is evaluated by a Spark UDF representation of an PySpark model, this *vector* is converted to a numpy array and embedded within a Pandas DataFrame. When the UDF invokes the PySpark model, it attempts to convert the Pandas DataFrame to a Spark DataFrame; however, this process fails because Spark cannot handle the embedded numpy array.

### Source code / logs

Code to reproduce the issue:

```
import mlflow.spark

from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression

from pyspark.ml.feature import Word2Vec
import pyspark

word_df = spark.createDataFrame([
  ("This is a test".split(" "), )
], ["0"])
w2v = Word2Vec(inputCol="0", outputCol="prediction", minCount=0)

pipeline = Pipeline(stages=[w2v])
model = pipeline.fit(word_df)

mlflow.set_experiment("repro-exp")
with mlflow.start_run():
  mlflow.spark.log_model(model, "spark-model")
  run_id = mlflow.active_run().info.run_uuid

import mlflow.pyfunc
from pyspark.sql.types import DoubleType, StringType, ArrayType
w2v_udf = mlflow.pyfunc.spark_udf(spark, "spark-model", run_id)
preds = word_df.withColumn("prediction", w2v_udf("0"))

preds.collect()
```

Stack trace:

```
  File "/databricks/spark/python/pyspark/sql/types.py", line 1068, in _infer_type
    return _infer_schema(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1094, in _infer_schema
    raise TypeError("Can not infer schema for type: %s" % type(row))
TypeError: Can not infer schema for type: <class 'numpy.ndarray'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 262, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 257, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 261, in dump_stream
    for series in iterator:
  File "<string>", line 1, in <lambda>
  File "/databricks/spark/python/pyspark/worker.py", line 95, in <lambda>
    return lambda *a: (verify_result_length(*a), arrow_return_type)
  File "/databricks/spark/python/pyspark/worker.py", line 86, in verify_result_length
    result = f(*a)
  File "/databricks/spark/python/pyspark/util.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/databricks/python/lib/python3.5/site-packages/mlflow/pyfunc/__init__.py", line 275, in predict
    result = model.predict(pdf)
  File "/databricks/python/lib/python3.5/site-packages/mlflow/spark.py", line 339, in predict
    spark_df = self.spark.createDataFrame(pandas_df)
  File "/databricks/spark/python/pyspark/sql/session.py", line 729, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 429, in _createFromLocal
    data, schema = self._wrap_data_schema(data, schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 408, in _wrap_data_schema
    struct = self._inferSchemaFromList(data, names=schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 344, in _inferSchemaFromList
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/databricks/spark/python/pyspark/sql/session.py", line 344, in <genexpr>
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/databricks/spark/python/pyspark/sql/types.py", line 1096, in _infer_schema
    fields = [StructField(k, _infer_type(v), True) for k, v in items]
  File "/databricks/spark/python/pyspark/sql/types.py", line 1096, in <listcomp>
    fields = [StructField(k, _infer_type(v), True) for k, v in items]
  File "/databricks/spark/python/pyspark/sql/types.py", line 1070, in _infer_type
    raise TypeError("not supported type: %s" % type(obj))
TypeError: not supported type: <class 'numpy.ndarray'>

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:317)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:174)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:124)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:271)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonExec$$anon$2.<init>(ArrowEvalPythonExec.scala:95)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonExec.evaluate(ArrowEvalPythonExec.scala:93)
	at org.apache.spark.sql.execution.python.EvalPythonExec$$anonfun$doExecute$1.apply(EvalPythonExec.scala:131)
	at org.apache.spark.sql.execution.python.EvalPythonExec$$anonfun$doExecute$1.apply(EvalPythonExec.scala:93)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:812)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:812)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KobaKhit** [comment]
Are there plans on resolving this issue? [I found a line where pandas dataframe is being passed to `model.predict` in `mlflow.pyspark.spark_udf`](https://github.com/mlflow/mlflow/blob/18d9778376ae4863832370c0f958d3e6d5268a77/mlflow/pyfunc/__init__.py#L467)[1]  and [a line where spark is trying to create the Spark DataFrame](https://github.com/mlflow/mlflow/blob/fdcf3402123bccfa88b376a5efcf13be4a65fd2f/mlflow/spark.py#L455)[2]

I was able to make it work with your example above by replacing the predict method in [2].  

**original**
``` python
def predict(self, pandas_df):
        """
        Generate predictions given input data in a pandas DataFrame.
        :param pandas_df: pandas DataFrame containing input data.
        :return: List with model predictions.
        """
        spark_df = self.spark.createDataFrame(pandas_df)
        return [x.prediction for x in
                self.spark_model.transform(spark_df).select("prediction").collect()]
```

**new** - added applymap and `x.prediction.values`
```python
def predict(self, pandas_df):
        """
        Generate predictions given input data in a pandas DataFrame.

        :param pandas_df: pandas DataFrame containing input data.
        :return: List with model predictions.
        """
        # raise Exception(type(pandas_df[pandas_df.columns[0]][0]))
        # raise Exception(pandas_df.columns)
        pandas_df = pandas_df.applymap(lambda x: x.tolist()) # new operation
        spark_df = self.spark.createDataFrame(pandas_df)
        return [x.prediction.values for x in
                self.spark_model.transform(spark_df).select("prediction").collect()]
```
