### ISSUE TITLE
[BUG] model.log giving a pickling error on 'torch._C.Generator' object

### ISSUE THREAD

**Issue by aaparikh** [mlflow/mlflow#7820]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Ventura 13.1 (22C65), Pop OS LTS  22.04, Ubuntu 20.04.5 LTS (Focal Fossa)
- **Python version**: 3.9.5

### Describe the problem

I am trying to log a custom pyfunc model using mlflow but am getting a pickling error.
Basically, i am trying to load in a yolo model using the latest ultralytics module ([ultralytics](https://github.com/ultralytics/ultralytics))

Process is:
1. create a pyfunc object and load the model inside it.
2. do a test prediction to check if the loaded model works.
3. **log the model to use it later.** _(This is where I am facing error)_
4. validate the model to get the metrics for logging into mlflow.
5. load the saved model and then use it for predictions.

But when I try to log the model after training it, I get a pickling error saying
`TypeError: cannot pickle 'torch._C.Generator' object`

### Tracking information

`mlflow.doctor()`
```shell
System information: Darwin Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
Python version: 3.9.5
MLflow version: 2.1.1
MLflow module location: /Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///{path}/yolo_mlflow/mlruns
Registry URI: file:///{path}/mlruns
MLflow dependencies: 
  Flask: 2.2.2
  Jinja2: 3.1.2
  alembic: 1.9.3
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.30
  gunicorn: 20.1.0
  importlib-metadata: 5.2.0
  markdown: 3.4.1
  matplotlib: 3.6.3
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.3
  protobuf: 4.21.12
  pyarrow: 10.0.1
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.1
  scipy: 1.10.0
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
```

### Code to reproduce issue

If you want to jump at part giving the error, search `ERROR` and work backwards from there

```
# Importing the necessary libraries
import mlflow
from ultralytics import YOLO
import cv2
import numpy as np
import json
import os

#Function to get the experiment id
def get_experiment_id(name):
    exp = mlflow.get_experiment_by_name(name)
    if exp is None:
      exp_id = mlflow.create_experiment(name)
      return exp_id
    return exp.experiment_id

#Function to plot the annotated images
def plot_annotated_images(results, imgs, classes=json.load(open('coco_label.json'))):
    annotated_imgs = []
    for result, img in zip(results, imgs):
        boxes = result.boxes
        for box in boxes:
            class_of_box = classes[str(int(box.cls))]
            pred_confidence = float(box.conf) * 100
            bbox = np.asarray(box.xyxy[0])
            print(f'\n\nClass: {class_of_box}, \t Confidence: {pred_confidence} %')
            print(f'Bounding box coordinates: {bbox}\n')
            # print(f'Type of bbox: {type(bbox)}') #numpy array
            # print(f'Type of elements in bbox: {type(bbox[0])}') #float type 
            x1 = int(bbox[0])
            y1 = int(bbox[1])
            x2 = int(bbox[2])
            y2 = int(bbox[3])
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(img, f'{class_of_box} {pred_confidence}%', (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
        annotated_imgs.append(img)
    return annotated_imgs

#Function to write the annotated images
def write_annotated_images(annotated_imgs, path):
    #cheeck if path exists
    if not os.path.exists(path):
        os.mkdir(path)
    for i, img in enumerate(annotated_imgs):
        cv2.imwrite(f'{path}/annotated_img_{i}.jpg', img)

#Function to select the model to use
def select_model_to_use():
    """
    This function will be used to select the model to use for training and inference.
    """
    print("List of available models: \n")
    print("1. yolov5lu")
    print("2. yolov5mu")
    print("3. yolov5su")
    print("4. yolov5xu")
    print("5. yolovnu")
    print("6. yolov8l")
    print("7. yolov8m")
    print("8. yolov8s")
    print("9. yolov8x")
    print("10. yolov8n")
    print("11. yolov8x6")

    model = input("Enter number representing the model to use: ")
    if model == '1':
        model_name = 'yolov5lu.pt'
    elif model == '2':
        model_name = 'yolov5mu.pt'
    elif model == '3':
        model_name = 'yolov5su.pt'
    elif model == '4':
        model_name = 'yolov5xu.pt'
    elif model == '5':
        model_name = 'yolovnu.pt'
    elif model == '6':
        model_name = 'yolov8l.pt'
    elif model == '7':
        model_name = 'yolov8m.pt'
    elif model == '8':
        model_name = 'yolov8s.pt'
    elif model == '9':
        model_name = 'yolov8x.pt'
    elif model == '10':
        model_name = 'yolov8n.pt'
    elif model == '11':
        model_name = 'yolov8x6.pt'
    else:
        print("Invalid model selected. Please select a valid model.")
        model_name = select_model_to_use()
    return model_name


#Class to wrap the model
class ModelDetectorWrapper(mlflow.pyfunc.PythonModel):
    def load_model(self, path):
        self.model = YOLO(path)

    def train_model(self, data="coco128.yaml", epochs=1, imgsz=640):
        self.model.train(
            data=data, 
            epochs=epochs, 
            imgsz=imgsz,
            batch_size=16,
            save_dir='runs/train',)
        
    def predict(self, context, imgs):
        #retuen data in required format
        objs = self.model(imgs)
        return objs

    def validate_for_metrics(self):
        metrics = self.model.val()

        #Print the metrics
        print(f'Average precision: Type: {type(metrics.box.ap)},\n Value: {metrics.box.ap}')
        print(f'Average precision 50: Type: {type(metrics.box.ap50)},\n Value: {metrics.box.ap50}')
        print(f'Mean Average precision: Type: {type(metrics.box.map)},\n Value: {metrics.box.map}')
        print(f'Mean Average precision 50: Type: {type(metrics.box.map50)},\n Value: {metrics.box.map50}')
        print(f'Mean Average precision 75: Type: {type(metrics.box.map75)},\n Value: {metrics.box.map75}')
        print(f'Mean Average precision 50-95: Type: {type(metrics.box.maps)},\n Value: {metrics.box.maps}')
        print(f'Mean precision: Type: {type(metrics.box.mp)},\n Value: {metrics.box.mp}')
        print(f'Mean recall: Type: {type(metrics.box.mr)},\n Value: {metrics.box.mr}')

        return metrics


def main():
    exp_id = get_experiment_id(input("Enter the experiment name: "))
    model_name = select_model_to_use()

    model_name_for_experiment = model_name.split('.')[0] + '_experiment'
    mlflow.set_experiment(exp_id)

    with mlflow.start_run(run_name=model_name_for_experiment):

         #Load the model
        pyf_model = ModelDetectorWrapper()
        pyf_model.load_model(model_name)

        #Train the model
        pyf_model.train_model() 

        sample_img_bus = cv2.imread('images/bus.jpg')
        sample_results = pyf_model.predict(None, sample_img_bus)
        print(f'The sample results obtained on the bus image are:\n {sample_results}')

        #Logging the model 
        #---------------------------------------------------------------- (THIS PART IS GIVING AN ERROR)
        mlflow.pyfunc.log_model(
            model_name_for_experiment, 
            python_model=pyf_model,
            registered_model_name=model_name_for_experiment)
        
        #Validate the model
        metrics = pyf_model.validate_for_metrics()

        #Log the metrics
        mlflow.log_metric("map", metrics.box.map)
        mlflow.log_metric("map50", metrics.box.map50)
        mlflow.log_metric("map75", metrics.box.map75)
        mlflow.log_metric("mp", metrics.box.mp)
        mlflow.log_metric("mr", metrics.box.mr)

        mlflow.end_run()

    #Load the model
    mlflow.pyfunc.load_model(f'models:/{model_name_for_experiment}/latest')

    #Predict the model
    imgs = os.listdir('images')
    imgs = [cv2.imread(f'images/{img}') for img in imgs]
    results = pyf_model.predict(None,imgs)
    
    annotated_imgs = plot_annotated_images(results, imgs)

    #Write the annotated images
    write_annotated_images(annotated_imgs, 'annotated_images')

if __name__ == '__main__':
    main()
```

_Note: please use any images in place of images passed on in the code for testing._

### Stack trace

```
Traceback (most recent call last):
  File "/Users/{path}/yolo_mlflow/final_implementations.py", line 177, in <module>
    
  File "/Users/{path}/yolo_mlflow/final_implementations.py", line 144, in main
    sample_img_bus = cv2.imread('images/bus.jpg')
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1578, in log_model
    return Model.log(
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/mlflow/models/model.py", line 486, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1458, in save_model
    return mlflow.pyfunc.model._save_model_with_class_artifacts_params(
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/mlflow/pyfunc/model.py", line 164, in _save_model_with_class_artifacts_params
    cloudpickle.dump(python_model, out)
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/Users/{path}/yolo_mlflow/env/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'torch._C.Generator' object
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @aaparikh, thank you for raising this issue. The problem appears to be that your PyTorch model is attached as an attribute of your `ModelDetectorWrapper` custom pyfunc model. MLflow uses cloudpickle to serialize this custom model class, which means that it's also trying to serialize your PyTorch model with cloudpickle.

To fix the issue, we recommend using the `artifacts` argument of `mlflow.pyfunc.log_model()` to specify the path to your serialized PyTorch model and then defining a `load_context()` method in your `ModelDetectorWrapper` to automatically load the serialized model when `mlflow.pyfunc.load_model()` is called. For reference, here's a similar example from the MLflow docs: https://mlflow.org/docs/latest/models.html#example-saving-an-xgboost-model-in-mlflow-format.

Thank you for using MLflow!

**Comment by aaparikh** [comment]
Thank you 👍🏻
