### ISSUE TITLE
MLFlow Database URL doesnt support direct special characters

### ISSUE THREAD

**Issue by nov301996** [mlflow/mlflow#7851]
### Discussed in https://github.com/mlflow/mlflow/discussions/7850

<div type='discussions-op-text'>

<sup>Originally posted by **nov301996** February 16, 2023</sup>
Hello,

The current MLFLow version is failing to start when i use special characters in my password. If I am ignoring usage of '_[]:=?' the MLFlow server is starting up.

We need to pass the special characters to the password, so how to put an escape to those special characters by not getting the below error and pass to the actual password to the system

The following is the format of the MLFlow DB URL : 

postgresql+psycopg2://{{userName}:{password}//{{database}}?host={{ip}}&sslmode=verify-ca&sslrootcert={{sslRootCert}}&sslcert={{sslCert}}&sslkey={{sslKey}}

And password contains : _[]:=?

The following is the error:

ERROR mlflow.cli: Invalid IPv6 URLTraceback (most recent call last): 
 File "/app/mlflow/cli.py", line 461, in server    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root) 
 File "/app/mlflow/server/handlers.py", line 267, in initialize_backend_stores    _get_tracking_store(backend_store_uri, default_artifact_root)  
File "/app/mlflow/server/handlers.py", line 246, in _get_tracking_store    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)  
File "/app/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)  
File "/app/mlflow/tracking/_tracking_service/registry.py", line 48, in _get_store_with_resolved_uri    builder = self.get_store_builder(resolved_store_uri)  
File "/app/mlflow/tracking/registry.py", line 73, in get_store_builder    scheme = store_uri if store_uri == "databricks" else get_uri_scheme(store_uri)  
File "/app/mlflow/utils/uri.py", line 166, in get_uri_scheme    scheme = urllib.parse.urlparse(uri_or_path).scheme  
File "/usr/local/lib/python3.7/urllib/parse.py", line 371, in urlparse    splitresult = urlsplit(url, scheme, allow_fragments) 
File "/usr/local/lib/python3.7/urllib/parse.py", line 469, in urlsplit    
raise ValueError("Invalid IPv6 URL")ValueError: Invalid IPv6 URL

Can someone in MLFlow Community/Contributors please help us resolve this error.</div>

**Comment by hattajr** [comment]
Hi, have you tried to use backslash `\` before each special character?
And also I think the error was raised because of invalid IP, not an invalid password (?)

**Comment by BenWilson2** [comment]
This error is raising due to the special characters (the ValueError raised is a red herring). Can you follow the guide here: https://pip.pypa.io/en/stable/topics/authentication/#percent-encoding-special-characters to do percent-encoding of your password to properly escape these reserved characters for urlencoding with urllib?

**Comment by kuzm1ch** [comment]
@BenWilson2  I had  a similar issue with random password "(f]#o*Ej:3Il_|lyO:4N%_5JtH3H" provided by AWS RDS. 

Yes, as a solution this password can be percent-encoded manually before usage, but it doesn't work with automatic password rotation. 

Is there a way to add percent-encoded to password before it was consumed and put into db connection url.
