### ISSUE TITLE
MLFlow run is not support github tokens

### ISSUE THREAD

**Issue by weldpua2008** [mlflow/mlflow#786]
### System information
- **OS Platform and Distribution**: Debian 8
- **MLflow installed from (source or binary)**: pip3.6 install mlflow 
- **MLflow version (run ``mlflow --version``)**: `mlflow, version 0.8.1`
- **Python version**:  `Python 2.7.9`
- **Exact command to reproduce**:
mlflow run https://github.com/private/data-science.git#mlflow_test/sklearn_elasticnet_wine -P alpha=0.1

### Describe the problem
We have a GitHub private repository and our GitHub user are authenticated by tokens. When I run `mlflow run` with `--git-username` and `--git-password` for a user with token authorization it's failing.  In our organization, it's the strict policy to use token-based auth for GitHub.

### Source code / logs
```
$ mlflow run --git-username user --git-password token https://github.com/wix-private/data-science.git#mlflow_test/sklearn_elasticnet_wine -P alpha=0.1 

2018/12/30 10:32:37 INFO mlflow.projects: === Fetching project from https://github.com/private/data-science.git#mlflow_test/sklearn_elasticnet_wine into /tmp/tmppMmJHU ===
Username for 'https://github.com': Password for 'https://github.com': 
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mlflow/cli.py", line 128, in run
    run_id=run_id,
  File "/usr/local/lib/python2.7/dist-packages/mlflow/projects/__init__.py", line 171, in run
    storage_dir=storage_dir, block=block, run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/mlflow/projects/__init__.py", line 54, in _run
    git_username=git_username, git_password=git_password)
  File "/usr/local/lib/python2.7/dist-packages/mlflow/projects/__init__.py", line 297, in _fetch_project
    _fetch_git_repo(parsed_uri, version, dst_dir, git_username, git_password)
  File "/usr/local/lib/python2.7/dist-packages/mlflow/projects/__init__.py", line 347, in _fetch_git_repo
    origin.fetch()
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 675, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: Authentication failed for 'https://github.com/private/data-science.git''

```

**Comment by hanyucui** [comment]
I think the option `--git-password` takes a password rather than a token. Are you requesting support for tokens?

**Comment by weldpua2008** [comment]
@hanyucui Yes, I am requesting a support for tokens

**Comment by weldpua2008** [comment]
@hanyucui Thank you

**Comment by hanyucui** [comment]
Hi @weldpua2008 , I think I made a mistake. The way you used the token is indeed correct. I have tried using a token in the same way and was able to run the project on Github. Can you verify the token you use is correct? Since you can only see the token once, I suggest you create a new token for debugging this.

**Comment by max-allen-db** [comment]
@weldpua2008 were you able to use a token as Hanyucui suggested?
