### ISSUE TITLE
Warning Message is returned when logging and loading the models with more than 100 columns

### ISSUE THREAD

**Issue by VishnuMurthyChakka** [mlflow/mlflow#7946]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.0
- Tracking server: 2.1.0

### System information

Ubuntu 22.04.1 LTS

### Describe the problem

I have built a xgboost model with 600 input columns. While logging the model, the following warning message is displayed

*****************************************************************************************************************************
2023/03/02 15:34:44 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under s3://rml-model-artifacts/users/csvishnumurthy/3/f553c33d93ee4dd5b09e05e5b6a46ba8/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the tracking store. If logging to a mlflow server via REST, consider upgrading the server version to MLflow 1.7.0 or above. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
*****************************************************************************************************************************

Similarly, when I load the model, the following warning message appears 500 times

*****************************************************************************************************************************
/miniconda/lib/python3.10/site-packages/mlflow/models/utils.py:453: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_pf_input[x] = _enforce_mlflow_datatype(x, pf_input[x], input_types[i])
*****************************************************************************************************************************

What I have observed is that whenever the number of input columns crosses 100, these warning messages appear.
We are not sure if these warning messages indicate any issues that causing high latency when we converted the model to REST API

### Tracking information

```shell
REPLACE_ME
```
MLflow version: 2.1.0
Tracking URI: https://csvis9t6ii-server.ostack.babyrocket.net/
System information: Linux #1 SMP Wed Jan 25 23:14:15 UTC 2023
Python version: 3.10.9
MLflow version: 2.1.0
MLflow module location: /miniconda/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: https://csvis9t6ii-server.ostack.babyrocket.net/
Registry URI: https://csvis9t6ii-server.ostack.babyrocket.net/
MLflow environment variables: 
  MLFLOW_TRACKING_URI: https://csvis9t6ii-server.ostack.babyrocket.net/
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.1.2
  alembic: 1.9.4
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.0.0
  markdown: 3.4.1
  matplotlib: 3.7.0
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.3
  protobuf: 3.20.3
  pyarrow: 10.0.1
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.1.1
  scipy: 1.8.1
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3

### Code to reproduce issue

```
REPLACE_ME
```
I have created the dataframe with random data in 600 columns

ncols = 600
nrows = 10000

median = np.random.uniform(low=100, high=1000, size=ncols)
std = np.random.uniform(low=1, high=50, size=ncols)
target = np.random.uniform(low=100, high=1000, size=nrows)

df_dict = dict()

col_pre = 'col'
for i in np.arange(0,ncols):
    col_name = col_pre + str(i)
    df_dict[col_name] = np.random.normal(loc=median[i], scale=std[i], size=nrows)
df = pd.DataFrame(df_dict)
print(df.shape)

df1 = df.copy(deep=True)

XGB = XGBRegressor(max_depth=1, n_estimators=200)
XGB.fit(df1, target)

Created the signature
from mlflow.models.signature import infer_signature
input_signature = infer_signature(df1, target)

Dumped the model in local
joblib.dump(XGB,                                        # fitted model
            filename='XGB_R.bz2',                         # Name of the pickled file
            compress=('bz2', 9))                          # Compression method and level

Build the wrapper
class ModelWrapper(mlflow.pyfunc.PythonModel):
    
    def load_context(self,context):
            
        model  = context.artifacts["model"]
        self.model  = joblib.load(filename=model)
         
    def predict(self, context, model_input):
        TimeStamp = datetime.datetime.now()
        
        prediction = 0.50
        
        output = dict({"model_probability": prediction[0],
                       "model_pointers" : model_pointers,
                       "model_db_data" :model_db_data})
        
        return prediction

Logged the model using pyfunc
with mlflow.start_run(experiment_id=Exp_Id) as run:
    
    model_artifacts = {"model": "XGB_R.bz2"}
    pyfunc_model = ModelWrapper()
    
    mlflow.pyfunc.log_model(artifact_path="model",
                            python_model=pyfunc_model,
                            signature=input_signature,
                            input_example=df1.iloc[0:1:,::],
                            artifacts=model_artifacts,
                            conda_env=conda_env)
    
print("Run Name: ", run.info.run_name)

### Stack trace

```
REPLACE_ME
```
2023/03/03 09:25:23 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under s3://rml-model-artifacts/users/csvishnumurthy/3/a5d8d0149c644044bf1a53ad1cdd45c0/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the tracking store. If logging to a mlflow server via REST, consider upgrading the server version to MLflow 1.7.0 or above. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

### Other info / logs

```
REPLACE_ME
```
/miniconda/lib/python3.10/site-packages/mlflow/models/utils.py:453: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_pf_input[x] = _enforce_mlflow_datatype(x, pf_input[x], input_types[i])

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@VishnuMurthyChakka 

Could you run `logging.getLogger("mlflow").setLevel(logging.DEBUG)` before you running above reproducing code ? and rerun your code and then provide the full traceback log for debugging ?

Thank you!

**Comment by VishnuMurthyChakka** [comment]
@WeichenXu123 ,

Thanks for response. Please find the full traceback log for this warning.

2023/03/10 07:34:20 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under s3://rml-model-artifacts/users/csvishnumurthy/3/bf8257f63fc84f6c870e0674d4dea615/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the tracking store. If logging to a mlflow server via REST, consider upgrading the server version to MLflow 1.7.0 or above. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2023/03/10 07:34:20 DEBUG mlflow.models.model: 
Traceback (most recent call last):
  File "/miniconda/lib/python3.10/site-packages/mlflow/models/model.py", line 489, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/miniconda/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 985, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/miniconda/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1370, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/miniconda/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 404, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/miniconda/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 325, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/miniconda/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/miniconda/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/miniconda/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Tag value '[{"run_id": "bf8257f63fc84f6c870e0674d4dea615", "artifact_path": "model", "utc_time_created": "2023-03-10 07:34:20.350545", "flavors": {"python_function": {"model_path": "model.pkl", "predict_fn": "predict", "loader_module": "mlflow.sklearn", "python' had length 28273, which exceeded length limit of 5000

**Comment by yukimori** [comment]
@WeichenXu123 Thank you for your comment! But I think the main issue may be the storage of the entire model information, including input examples and signatures, in tags. This is because the size limit for tag values is fixed, while input examples and signatures can significantly increase in size depending on the training data.

I believe the problem could be resolved by saving input examples and signatures through a different method and separating the storage of other model information in mlflow.log-model.history. This is because, apart from input examples and signatures, most of the model information has relatively fixed lengths.

I haven't been able to investigate if the input examples and signatures stored in mlflow.log-model.history are being used anywhere. If MLflow requires those information, alternative approaches will need to be considered.

**Comment by WeichenXu123** [comment]
(1)

We have some limitation values defined here:
https://github.com/mlflow/mlflow/blob/a5b61dbe967633e8f5f97f3bd11002d42c1fc9cc/mlflow/utils/validation.py#L47

For safety / performance reason we don't want to make the default value to be too large. You can increase these values if your own case require larger value.

(2)

> PerformanceWarning: DataFrame is highly fragmented

Such warning is caused by the dataframe with too many columns, currently we haven't optimized code for dataframes with many columns, for such case, I recommend to use the approach https://github.com/mlflow/mlflow/issues/7946#issuecomment-1556851817

**Comment by B-Step62** [comment]
The first warning is a client/server version mismatch (your client is newer than the 1.x server, so metadata logging to the store is skipped; artifacts still log fine, upgrade the server to clear it). The pandas `PerformanceWarning` about a fragmented DataFrame is benign and does not indicate a failure. Closing as not a bug; if wide-model scoring latency is the real concern, please open a focused issue with profiling.
