### ISSUE TITLE
Can't log artifact to remote server: Permission Denied on local machine

### ISSUE THREAD

**Issue by budmitr** [mlflow/mlflow#810]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: fedora 28
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.8.1
- **Python version**: 3.7.1
- **Exact command to reproduce**: MLFLOW_TRACKING_URI=http://myaws:5000 python mlflow/examples/quickstart/mlflow_tracking.py

### Problem
I have AWS-based remote server up and running
On my local machine I run example file which logs some metrics and adds simple artifact

**Expected** no errors, UI shows metadata and artifact
**Actual**: artifact error (see below), UI shows only metadata and no artifact

On the server `/home/ec2-user/mlruns` folder is created and has metadata
UI can show metrics nicely

### Source code / logs
```
Running mlflow_tracking.py
Traceback (most recent call last):
  File "mlflow_tracking.py", line 23, in <module>
    log_artifacts("outputs")
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 227, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/site-packages/mlflow/tracking/client.py", line 174, in log_artifacts
    artifact_repo.log_artifacts(local_dir, artifact_path)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/site-packages/mlflow/store/local_artifact_repo.py", line 31, in log_artifacts
    mkdir(artifact_dir)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 105, in mkdir
    raise e
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 102, in mkdir
    os.makedirs(target)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/localuser/miniconda3/envs/mflow/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ec2-user'
```

Why the hack **local client tries to create same folder as on the server** as it already created `outputs` folder to upload file?

Local client should not care at all which path is used on remote server

**Comment by hanyucui** [comment]
What was the exact command line used to start the server?

**Comment by budmitr** [comment]
@hanyucui simply that:

```
[ec2-user@ip-10-0-0-148 ~]$ pwd
/home/ec2-user

[ec2-user@ip-10-0-0-148 ~]$ mlflow server --host 0.0.0.0
[2019-01-21 10:33:02 +0000] [2259] [INFO] Starting gunicorn 19.9.0
[2019-01-21 10:33:02 +0000] [2259] [INFO] Listening at: http://0.0.0.0:5000 (2259)
[2019-01-21 10:33:02 +0000] [2259] [INFO] Using worker: sync
[2019-01-21 10:33:02 +0000] [2262] [INFO] Booting worker with pid: 2262
[2019-01-21 10:33:02 +0000] [2263] [INFO] Booting worker with pid: 2263
[2019-01-21 10:33:02 +0000] [2265] [INFO] Booting worker with pid: 2265
[2019-01-21 10:33:02 +0000] [2268] [INFO] Booting worker with pid: 2268

```

and then from client:

```
quickstart$ MLFLOW_TRACKING_URI=http://***.compute.amazonaws.com:5000 python mlflow_tracking.py

......

PermissionError: [Errno 13] Permission denied: '/home/ec2-user'
```

**Comment by hanyucui** [comment]
@budmitr Looks like this expected behavior. According to the [documentation](https://mlflow.org/docs/latest/tracking.html#storage), the client directly logs into the artifact store. And since it can't access '/home/ec2-user', it bails out. In your case, you probably want to set the URI to an S3 bucket. This is the original text:
> The _artifact store_  ... and is where _clients_ log their artifact output (for example, models).

**Comment by naveen-9697** [comment]
I get the same error when I am trying to store artifacts locally. This is the error:
```
PermissionError: [Errno 13] Permission denied: './mlruns/2/tags'
```

Here's how I had started mlflow server:
```
ubuntu@ip-xxx-xxx-xxx-xxx:~/pump-it-up$ mlflow ui
[2021-01-26 05:35:17 +0000] [1019] [INFO] Starting gunicorn 20.0.4
[2021-01-26 05:35:17 +0000] [1019] [INFO] Listening at: http://127.0.0.1:5000 (1019)
[2021-01-26 05:35:17 +0000] [1019] [INFO] Using worker: sync
[2021-01-26 05:35:17 +0000] [1021] [INFO] Booting worker with pid: 1021
2021/01/26 05:35:30 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/experiments/set-experiment-tag [POST]
Traceback (most recent call last):
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/mlflow/server/handlers.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/mlflow/server/handlers.py", line 411, in _set_experiment_tag
    _get_tracking_store().set_experiment_tag(request_message.experiment_id, tag)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 812, in set_experiment_tag
    make_containing_dirs(tag_path)
  File "/home/ubuntu/ds_jup_venv/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 124, in make_containing_dirs
    os.makedirs(dir_name)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './mlruns/2/tags'
```

I have started the server on a AWS EC2 instance(c5.4x) running Minimal Ubuntu 20.04LTS. The experiment I was trying to access from UI was actually created on my local machine(Ubuntu 20.04LTS laptop) and as I needed more compute power, I moved everything to an S3 bucket, then downloaded them inside the EC2 instance; and when tried to continue my work, that is the error I see. I am the only user of this machine and I couldn't launch mlflow by doing `sudo mlflow ui` as well.

what has caused this and how do I fix this?

**Comment by dvalenciar** [comment]
Not sure if this is still helpful or relevant, but I wanted to share the solution that worked for me in case it helps others.

I was running an MLflow tracking server on a local machine (not using S3 or cloud storage) and had trouble logging artifacts from a remote training machine.

The command that solved my issue was:

```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri sqlite:///mlflow_server/mlflow.db \
    --artifacts-destination ./mlflow_server/artifacts
```

The key component is the   `artifacts-destination` flag, which tells the MLflow server where to store the artifacts and enables HTTP-proxied artifact uploads.
Without this, the client will incorrectly try to write files directly to the server’s file system and cause permission errors.
