### ISSUE TITLE
[BUG] mlflow gc is unable to properly delete runs with an invalid artifact URI.

### ISSUE THREAD

**Issue by PenHsuanWang** [mlflow/mlflow#8211]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 1.30.0
- Tracking server: 1.30.1
- Test mlflow gc cli with latest dev version : 2.2.3.dev0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 11 (bullseye) 
- **Python version**: 3.7.16(tracking server), 3.9.0(CLI)
- **yarn version, if running the dev UI**: 

### Describe the problem

I am running an MLflow tracking server with MySQL backend store, together with an HTTP artifact server as following command.

```
mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri mysql+pymysql://'${MLFLOW_BACKEND_DB_USERNAME}':'${MLFLOW_BACKEND_DB_PASSWORD}'@${MLFLOW_BACKEND_URL}:3316/${MLFLOW_BACKEND_DB}
      --default-artifact-root http://${MLFLOW_TRACKING_BACKEND_URL}:5500/api/2.0/mlflow-artifacts/artifacts/experiments
      --gunicorn-opts "--log-level debug"
```
When I have a typo in the artifact server hostname ENV variable, it cause an invalid uri to be inserted into the RDB.

![截圖 2023-04-12 上午10 55 44](https://user-images.githubusercontent.com/13614761/231336361-e5472324-27b6-4bfd-89d0-e9e0193e2388.png)

In this case, I cannot properly delete this incorrect experiment using mlflow gc because the `requests.exceptions.InvalidURL` exception stops the gc process."

<img width="1200" alt="截圖 2023-04-12 上午10 33 02" src="https://user-images.githubusercontent.com/13614761/231336571-b77613e9-ced1-4602-8ea5-8ce19e438810.png">

The code responsible for deleting artifacts is located in `mlflow/store/artifact/http_artifact_repo.py", line 77`.
The exception `MlflowException` is raised in `mlflow/utils/rest_utils.py", line 184`.

Is it possible to implement exception handling from these two parts? That allows us to skip over the invalid URI exception and continue deleting failed experiments with `mlflow gc`?

### Tracking information

```shell
```

### Code to reproduce issue

start mlflow tracking server with invalid hostname enviroments variable to artifact server.

```
mlflow server \
      --host 0.0.0.0 \
      --port 5001 \
      --backend-store-uri mysql+pymysql://'<user>':<passwd>@127.0.0.1:3316/<db_name>\
      --default-artifact-root http://${INVALID_URI}:5500/api/2.0/mlflow-artifacts/artifacts/experiments \
      --gunicorn-opts "--log-level debug"
```

1. Run any official provided example.
2. Delete the experiment from UI.

Then check the backend store RDB to validate the experiment lifecycle has been labeled as `deleted` . 
![截圖 2023-04-12 上午10 12 35](https://user-images.githubusercontent.com/13614761/231329844-c63883a3-570d-4202-ae79-e319d7ebcebc.png)

Then using mlflow gc --backend-store-uri <target backend store uri> to permanently delete the experiment will raise `requests.exceptions.InvalidURL`, the gc process is failed.

I switch to use the mlflow version 2.2.3.dev version install from latest commit.

<img width="1200" alt="截圖 2023-04-12 上午10 33 02" src="https://user-images.githubusercontent.com/13614761/231333792-754055f5-e46c-4a18-88d1-1c14afe18652.png">

### Stack trace

```
Traceback (most recent call last):
  File "/BenWork/OpenSourceProject/MLFlow/mlflow/mlflow/utils/rest_utils.py", line 166, in http_request
    return _get_http_response_with_retries(
  File "/BenWork/OpenSourceProject/MLFlow/mlflow/mlflow/utils/rest_utils.py", line 97, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http://:5500/api/2.0/mlflow-artifacts/artifacts/experiments/1/47f3b9e246974868aca7fd35cb8e0704/artifacts/': No host supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow-dev-env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow/mlflow/cli.py", line 587, in gc
    artifact_repo.delete_artifacts()
  File "/BenWork/OpenSourceProject/MLFlow/mlflow/mlflow/store/artifact/http_artifact_repo.py", line 77, in delete_artifacts
    resp = http_request(self._host_creds, endpoint, "DELETE", stream=True)
  File "/BenWork/OpenSourceProject/MLFlow/mlflow/mlflow/utils/rest_utils.py", line 184, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://:5500/api/2.0/mlflow-artifacts/artifacts/experiments/1/47f3b9e246974868aca7fd35cb8e0704/artifacts/ failed with exception Invalid URL 'http://:5500/api/2.0/mlflow-artifacts/artifacts/experiments/1/47f3b9e246974868aca7fd35cb8e0704/artifacts/': No host supplied
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
I think this is a great idea. Please ping when your PR is ready (and make sure that the user gets alerted to the fact that there were invalid paths that need manual cleanup, while not aborting the gc operation)
