### ISSUE TITLE
[BUG] ONNX model deployment on Azure Managed Endpoint failing with TypeError: Object of type ndarray is not JSON serializable

### ISSUE THREAD

**Issue by natasha-savic-msft** [mlflow/mlflow#8220]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1
- azureml-mlflow==1.48.0

### System information

- **OS: Linux 23.02.06  AzureML compute instance**
- **Python version: 3.8**

### Describe the problem

Hello! I have used MLFlow `mlflow.onnx.log_model()` to register my onnx model into AzureML and deploy it to a managed endpoint. When running the inference call on the managed endpoint, there seems to be a problem with the output of the MLFlow model which returns a ndarray. This cannot be posted back as API response. Since I used MLflow, I used all the provided artefacts as basis for deployment, there has been no customisation.  

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
import onnx

mlflow_model_path = "./write_to_local_mlflow_model_location"
registered_model_name = "<registered_model_name for AzureML>"

mlflow.onnx.log_model(onnx_model=onnx_model, artifact_path=mlflow_model_path, registered_model_name=registered_model_name, input_example = img_data)
```

Deployment was done as per this documentation: https://github.com/Azure/azureml-examples/blob/main/sdk/python/using-mlflow/deploy/mlflow_sdk_online_endpoints.ipynb

```
from azure.ai.ml.entities import (
    ManagedOnlineDeployment,
    Model,
    Environment,
    CodeConfiguration,
)
import json

deployment_name = "default"
deploy_config = {
    "instance_type": "Standard_DS3_v2",
    "instance_count": 1,
    }

deployment_config_path = "deployment_config.json"
with open(deployment_config_path, "w") as outfile:
    outfile.write(json.dumps(deploy_config))

deployment = deployment_client.create_deployment(
    name=deployment_name,
    endpoint=endpoint.name,
    model_uri=f"models:/{registered_model_name}/{version}",
    config={"deploy-config-file": deployment_config_path},
)
```

### Stack trace

```
ERROR:entry_module:Error collecting model_outputs collection request. Per-column arrays must each be 1-dimensional
2023-04-13 00:50:31,567 E [640] azmlinfsrv - Encountered Exception: Traceback (most recent call last):
  File "/opt/miniconda/envs/userenv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda/envs/userenv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/miniconda/envs/userenv/lib/python3.8/site-packages/azureml_inference_server_http/server/routes.py", line 252, in handle_score
    response = wrap_response(response)
  File "/opt/miniconda/envs/userenv/lib/python3.8/site-packages/azureml_inference_server_http/server/routes.py", line 39, in wrap_response
    return AMLResponse(response_body, response_status_code, response_headers, json_str=True)
  File "/opt/miniconda/envs/userenv/lib/python3.8/site-packages/azureml_inference_server_http/api/aml_response.py", line 17, in __init__
    super().__init__(json.dumps(message), status=status_code, mimetype="application/json")
  File "/opt/miniconda/envs/userenv/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/miniconda/envs/userenv/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/miniconda/envs/userenv/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/miniconda/envs/userenv/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

### Other info / logs

```
2023-04-13 01:04:04,713 I [640] gunicorn.access - 127.0.0.1 - - [13/Apr/2023:01:04:04 +0000] "GET / HTTP/1.0" 200 7 "-" "kube-probe/1.18"
2023-04-13 01:04:09,352 I [640] azmlinfsrv - GET /swagger.json 200 108.324ms 2960885
2023-04-13 01:04:09,354 I [640] gunicorn.access - 127.0.0.1 - - [13/Apr/2023:01:04:09 +0000] "GET /swagger.json HTTP/1.0" 200 2960885 "-" "-"
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @natasha-savic-msft, I'm looking at https://learn.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http?view=azureml-api-2. I'm not familiar with `azureml_inference_server_http`, but is it possible to create `score.py` as described [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http?view=azureml-api-2#end-to-end-example) to convert a numpy array to a list?

**Comment by natasha-savic-msft** [comment]
@harupy Appreciate your support, thank you. I'm now modifying `score.py` to make it work. How do I get the modified `score.py` file into the mlflow model that is currently registered in my Azure Machine Learning model registry? 

Also, this seems like a workaround. Is it possible to modify the default score.py file in a way that it does not output a numpy array that cannot be serialised into a json object required for the API response?

**Comment by santiagxf** [comment]
@harupy looks like the ONNX flavor violates the signature of the predict method, since it returns a dictionary. It's not in the list of supported types: 


[mlflow/models/utils.py:L40](https://github.com/mlflow/mlflow/blob/92aa6c9575c0134e4445d289f1de3f32f73a511a/mlflow/models/utils.py#L34) `PyFuncOutput = Union[pd.DataFrame, pd.Series, np.ndarray, list, str]`

Should this be adjusted or the ONNX flavor to return one of the supported types?

**Comment by B-Step62** [comment]
This fails in the Azure ML-managed deployment path, and MLflow's `azureml` integration has since been removed. Closing as obsolete; the current scoring server returns JSON-safe output for standard deployments.
