### ISSUE TITLE
[BUG] MlflowException(f"Run with id={run_uuid} not found", RESOURCE_DOES_NOT_EXIST)

### ISSUE THREAD

**Issue by clementlefevre** [mlflow/mlflow#8233]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.2.3.dev0
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution Ubuntu 20.04.1 LTS:
- **Python version : 3.8.15
- **yarn version, if running the dev UI:  1.22.19

### Describe the problem

from ``/workspaces/mlflow/examples/sklearn_elasticnet_wine``

when running `mlflow run . -P alpha=0.5 `
with **train.py** set up with 

```
    mlflow.set_tracking_uri("sqlite:///mlruns/mlflow.db")
    with mlflow.start_run():
```

i get :

`  File "/root/.mlflow/envs/mlflow-eee90753fcbd811c61a366651b95e9611177504d/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 509, in _get_run
    raise MlflowException(f"Run with id={run_uuid} not found", RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run with id=0c893feb616446bd9ddefe565aa841d2 not found
2023/04/14 09:41:47 ERROR mlflow.cli: === Run (ID '0c893feb616446bd9ddefe565aa841d2') failed ===`

### Tracking information

```
mlflow.__version__ : '2.2.2'
mlflow.get_tracking_uri() : 'sqlite:////workspaces/mlflow/mlruns.db'
mlflow.get_artifact_uri() : 
2023/04/14 09:57:35 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2023/04/14 09:57:35 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
*** alembic.util.exc.CommandError: Can't locate revision identified by '3500859a5d39'
```

### Code to reproduce issue

```
# The data set used in this example is from http://archive.ics.uci.edu/ml/datasets/Wine+Quality
# P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
# Modeling wine preferences by data mining from physicochemical properties. In Decision Support Systems, Elsevier, 47(4):547-553, 2009.

import os
import warnings
import sys

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from urllib.parse import urlparse
import mlflow
import mlflow.sklearn

import logging

logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)


logger.error(f"MLflow version: {mlflow.__version__}")
logger.error(f"Tracking URI: {mlflow.get_tracking_uri()}")
logger.error(f"Artifact URI: {mlflow.get_artifact_uri()}")


def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2


if __name__ == "__main__":
    warnings.filterwarnings("ignore")
    np.random.seed(40)

    # Read the wine-quality csv file from the URL
    csv_url = (
        "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-red.csv"
    )
    try:
        data = pd.read_csv(csv_url, sep=";")
    except Exception as e:
        logger.exception(
            "Unable to download training & test CSV, check your internet connection. Error: %s", e
        )

    # Split the data into training and test sets. (0.75, 0.25) split.
    train, test = train_test_split(data)

    # The predicted column is "quality" which is a scalar from [3, 9]
    train_x = train.drop(["quality"], axis=1)
    test_x = test.drop(["quality"], axis=1)
    train_y = train[["quality"]]
    test_y = test[["quality"]]

    alpha = float(sys.argv[1]) if len(sys.argv) > 1 else 0.5
    l1_ratio = float(sys.argv[2]) if len(sys.argv) > 2 else 0.5


    mlflow.set_tracking_uri("sqlite:///mlruns/mlflow.db")
    with mlflow.start_run():
        lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
        lr.fit(train_x, train_y)

        predicted_qualities = lr.predict(test_x)

        (rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)

        print("Elasticnet model (alpha={:f}, l1_ratio={:f}):".format(alpha, l1_ratio))
        print("  RMSE: %s" % rmse)
        print("  MAE: %s" % mae)
        print("  R2: %s" % r2)

        mlflow.log_param("alpha", alpha)
        mlflow.log_param("l1_ratio", l1_ratio)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("r2", r2)
        mlflow.log_metric("mae", mae)

        tracking_url_type_store = urlparse(mlflow.get_tracking_uri()).scheme

        # Model registry does not work with file store
        if tracking_url_type_store != "file":
            # Register the model
            # There are other ways to use the Model Registry, which depends on the use case,
            # please refer to the doc for more information:
            # https://mlflow.org/docs/latest/model-registry.html#api-workflow
            mlflow.sklearn.log_model(lr, "model", registered_model_name="ElasticnetWineModel")
        else:
            mlflow.sklearn.log_model(lr, "model")
```

### Stack trace

```
➜  sklearn_elasticnet_wine git:(master) ✗ mlflow run . -P alpha=0.5

2023/04/14 10:02:31 INFO mlflow.utils.virtualenv: Installing python 3.8.15 if it does not exist
2023/04/14 10:02:31 INFO mlflow.utils.virtualenv: Environment /root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e already exists
2023/04/14 10:02:31 INFO mlflow.projects.utils: === Created directory /tmp/tmp94wf5vdf for downloading remote URIs passed to arguments of type 'path' ===
2023/04/14 10:02:31 INFO mlflow.projects.backend.local: === Running command 'source /root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/bin/activate && python train.py 0.5 0.1' in run with ID '04dbf97573ca4c6bbe4ae04c4749dd33' === 
ERROR:__main__:MLflow version: 2.2.2
ERROR:__main__:Tracking URI: sqlite:////workspaces/mlflow/mlruns.db
2023/04/14 10:02:33 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2023/04/14 10:02:33 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/base.py", line 240, in _catch_revision_errors
    yield
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/base.py", line 450, in _upgrade_revs
    for script in reversed(list(revs))
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 797, in iterate_revisions
    revisions, heads = fn(
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 1452, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 525, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 525, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 550, in get_revisions
    return tuple(
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 551, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/revision.py", line 622, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '3500859a5d39'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    logger.error(f"Artifact URI: {mlflow.get_artifact_uri()}")
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1333, in get_artifact_uri
    run_id=_get_or_start_run().info.run_id, artifact_path=artifact_path
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1552, in _get_or_start_run
    return start_run()
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 278, in start_run
    client = MlflowClient()
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/client.py", line 69, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 51, in __init__
    self.store
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 55, in store
    return utils._get_store(self.tracking_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 217, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 150, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 134, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/store/db/utils.py", line 82, in _initialize_tables
    _upgrade_db(engine)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/store/db/utils.py", line 206, in _upgrade_db
    command.upgrade(config, "heads")
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/runtime/migration.py", line 609, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/command.py", line 367, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/base.py", line 446, in _upgrade_revs
    return [
  File "/root/.pyenv/versions/3.8.15/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.mlflow/envs/mlflow-3722f277f238f9db655c45d93951cd51a180e71e/lib/python3.8/site-packages/alembic/script/base.py", line 272, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '3500859a5d39'
2023/04/14 10:02:34 ERROR mlflow.cli: === Run (ID '04dbf97573ca4c6bbe4ae04c4749dd33') failed ===
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@clementlefevre The reason the run wasn't found is because the run was created in the local file system, not in the database. `mlflow run` creates a run before running the entrypoint. As `MLFLOW_TRACKING_URI` is not set, it creates a run in the local file system, and store its ID to `MLFLOW_RUN_ID`, and then runs the entrypoint.

```
export MLFLOW_TRACKING_URI=sqlite:///mlruns/mlflow.db
mlflow run . -P alpha=0.5
```

should work.
