### ISSUE TITLE
[BUG] mlflow server attempts to fetch artifact from s3 in Scenario 4 setup

### ISSUE THREAD

**Issue by chris-ds-dk** [mlflow/mlflow#8276]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: not relevant
- Tracking server: 2.3.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat 8.5.0-16 (Linux version 4.18.0)
- **Python version**: 3.9.15
- **yarn version, if running the dev UI**: not relevant

### Describe the problem

In the "Scenario 4" setup described at [MLflow Tracking](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores), the mlflow server seems unaware that it has no access to s3 (MinIO in our case).

When inspecting a run the GIF in the "Artifacts" collapsible spins endlessly
![UI-loads-forever](https://user-images.githubusercontent.com/52947810/233060381-570ab32f-2fc5-43d3-bda4-1d205918b222.jpg)

The server logs contains errors similar to the one shown in "Stack Trace" below.

**Further details**
While it would be nice for the UI to reflect the "No serve artifact" mode, the main issue for my organisation is that our logs are spammed with errors.

The provided example config and log is a minimalistic repro of the problem. In practice, we run mlflow server in a docker container and have seen many variations of stack traces depending on which further input args for the `mlflow server` command or environmental variables has been added. For example, the presence of AWS-related env vars appears to cause the mlflow server to attempt to establish a connection to s3.

My testing has lead me to believe that some logic is missing for the mlflow server (and UI) to ignore artifacts in Scenario 4. Please correct me, if I am simply providing a false combination of input args or if I need to also create a UI issue.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
mkdir mlflow-test
python3.9 --version
#>> Python 3.9.15
python3.9 -m venv venv
source venv/bin/activate
pip install mlflow
pip show mlflow | grep Version
#>> Version: 2.3.0
pip install psycopg2-binary

mlflow server --backend-store-uri postgresql://<user>:<pass>@<host>:<port>/<dbname> --default-artifact-root s3://<bucket> --host 0.0.0.0 --port <port> --no-serve-artifacts
```

### Stack trace

```
[2023-04-19 11:28:01 +0200] [860939] [INFO] Starting gunicorn 20.1.0
[2023-04-19 11:28:01 +0200] [860939] [INFO] Listening at: http://0.0.0.0:30805 (860939)
[2023-04-19 11:28:01 +0200] [860939] [INFO] Using worker: sync
[2023-04-19 11:28:01 +0200] [860940] [INFO] Booting worker with pid: 860940
[2023-04-19 11:28:01 +0200] [860941] [INFO] Booting worker with pid: 860941
[2023-04-19 11:28:01 +0200] [860942] [INFO] Booting worker with pid: 860942
[2023-04-19 11:28:01 +0200] [860943] [INFO] Booting worker with pid: 860943
2023/04/19 11:33:25 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "[path]/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "[path]/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "[path]/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "[path]/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "[path]/venv/lib/python3.9/site-packages/mlflow/server/handlers.py", line 475, in wrapper
    return func(*args, **kwargs)
  File "[path]/venv/lib/python3.9/site-packages/mlflow/server/handlers.py", line 516, in wrapper
    return func(*args, **kwargs)
  File "[path]/venv/lib/python3.9/site-packages/mlflow/server/handlers.py", line 922, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
AttributeError: 'Response' object has no attribute 'list_artifacts'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@chris-ds-dk `--no-serve-artifacts` basically means disabling the endpoints for proxy artifact operations and doesn't disable the endpoints that UI uses to display artifacts.

**Comment by chris-ds-dk** [comment]
> @chris-ds-dk `--no-serve-artifacts` basically means disabling the endpoints for proxy artifact operations and doesn't disable the endpoints that UI uses to display artifacts, so it doesn't mean "Do not show artifacts on UI".

Thank you for the clarification. Does that mean I should create a feature request for the UI component on an option to "Disable showing artifacts in the UI"? I assume it should include a flag to the mlflow server cli

**Comment by harupy** [comment]
@chris-ds-dk Could you tell us why you want to hide artifacts on MLflow UI?
