### ISSUE TITLE
[BUG] mlflow.pyfunc.load_model fails for ONNX custom model

### ISSUE THREAD

**Issue by benjaminbluhm** [mlflow/mlflow#8330]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow: 2.0.1
- onnx: 1.13.1

### System information

- **Databricks Runtime 12.0 for Machine Learning**

### Describe the problem

I need to build a custom model wrapper around a logged onnx model. I am running into `FileNotFoundError` when loading the model in my custom model wrapper via` mlflow.onnx._load_pyfunc(context.artifacts["CustomModel"])`.

I am not sure if the source of the problem is a bug or an incorrect specification of my model wrapper and logging logic. Would be great to get some feedback on this!

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import numpy as np
import mlflow
import onnx
import torch
from torch import nn

logging.getLogger("mlflow").setLevel(logging.DEBUG)

# define a torch model
net = nn.Linear(6, 1)
loss_function = nn.L1Loss()
optimizer = torch.optim.Adam(net.parameters(), lr=1e-4)

X = torch.randn(6)
y = torch.randn(1)

# run model training
epochs = 5
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = net(X)

    loss = loss_function(outputs, y)
    loss.backward()

    optimizer.step()

# convert model to ONNX and load it
torch.onnx.export(net, X, "model.onnx")
onnx_model = onnx.load_model("model.onnx")

# log the model into a mlflow run
mlflow.onnx.log_model(onnx_model, "model")

# create custom model
class CustomModel(mlflow.pyfunc.PythonModel):
    def load_context(self, context):

        self.onnx_model = mlflow.onnx._load_pyfunc(context.artifacts["CustomModel"])

    def predict(self, context, model_input):
        return self.onnx_model.predict(model_input)

# log custom model
compatible_model = mlflow.pyfunc.log_model(
    python_model=CustomModel(),
    artifact_path = "CustomModel",
    artifacts={
        "CustomModel": f"runs:/{mlflow.active_run().info.run_uuid}/model", 
    },
)

mlflow.end_run()

# load custom model
loaded_pyfunc = mlflow.pyfunc.load_model(compatible_model.model_uri)
```

### Stack trace

```
2023/04/26 08:27:53 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp5pm2vjez/model, flavor: python_function), fall back to return ['cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2023/04/26 08:27:53 DEBUG mlflow.utils.environment: 
Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/environment.py", line 389, in infer_pip_requirements
    return _infer_requirements(model_uri, flavor)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 381, in _infer_requirements
    modules = _capture_imported_modules(model_uri, flavor)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 284, in _capture_imported_modules
    _run_command(
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 223, in _run_command
    raise MlflowException(msg)
mlflow.exceptions.MlflowException: Encountered an unexpected error while running [...]
exit status: 1
stdout: 
stderr: Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/_capture_modules.py", line 181, in <module>
    main()
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/_capture_modules.py", line 156, in main
    mlflow.pyfunc.load_model(model_path)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 528, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/_capture_modules.py", line 153, in _load_pyfunc_patch
    return original(*args, **kwargs)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/model.py", line 285, in _load_pyfunc
    python_model.load_context(context=context)
  File "<command-725617241430041>", line 38, in load_context
  File "/databricks/python/lib/python3.9/site-packages/mlflow/onnx.py", line 352, in _load_pyfunc
    return _OnnxModelWrapper(path)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/onnx.py", line 221, in __init__
    model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))
  File "/databricks/python/lib/python3.9/site-packages/mlflow/models/model.py", line 301, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5pm2vjez/model/artifacts/MLmodel'

Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<command-725617241430041>", line 53, in <module>
    loaded_pyfunc = mlflow.pyfunc.load_model(compatible_model.model_uri)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 528, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/model.py", line 285, in _load_pyfunc
    python_model.load_context(context=context)
  File "<command-725617241430041>", line 38, in load_context
    self.onnx_model = mlflow.onnx._load_pyfunc(context.artifacts["CustomModel"])
  File "/databricks/python/lib/python3.9/site-packages/mlflow/onnx.py", line 352, in _load_pyfunc
    return _OnnxModelWrapper(path)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/onnx.py", line 221, in __init__
    model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))
  File "/databricks/python/lib/python3.9/site-packages/mlflow/models/model.py", line 301, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpd9cofh5o/CustomModel/artifacts/MLmodel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/databricks/python/lib/python3.9/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by benjaminbluhm** [comment]
@harupy Thanks for quick feedback!

Indeed this works when using `load_model`. But then another problem arises when I try to predict on the loaded model `loaded_pyfunc.predict(X.numpy())`, it throws an error `AttributeError: predict`

I suppose this is because the native onnx flavor does not have a predict method, but I need to load the onnx model in its `pyfunc `flavor to serve it to an endpoit.

**Comment by harupy** [comment]
@benjaminbluhm Can we close this issue?

**Comment by benjaminbluhm** [comment]
Yes!
