### ISSUE TITLE
[BUG] missing mysql+pymysql

### ISSUE THREAD

**Issue by space192** [mlflow/mlflow#8426]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Tracking server: 2.3.1

### System information

- docker image ghcr.io/mlflow/mlflow:v2.3.1
- mysql server : 8.0.32

### Describe the problem

pymysql and MySQLdb are not installed with pip3 in the docker image

### Tracking information

```shell
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
2023/05/12 11:56:14 ERROR mlflow.cli: Error initializing backend store
2023/05/12 11:56:14 ERROR mlflow.cli: No module named 'pymysql'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 404, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 278, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 257, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 118, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 128, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 225, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 281, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@space192 I think we want to make the docker image small so we don't install all possible dependencies. You can use "sqlite" database instead of mysql in docker container, or you can manually install mysql + pymysql which should be simple. :)

**Comment by space192** [comment]
Yeah in the end I modified the Dockerfile to add pymsql as a client, the only i'm still having trouble with is the hadoop client for hdfs artifcats destination 🤔 if you have any idea ?

**Comment by WeichenXu123** [comment]
> Yeah in the end I modified the Dockerfile to add pymsql as a client, the only i'm still having trouble with is the hadoop client for hdfs artifcats destination 🤔 if you have any idea ?

We use pyarrow hdfs client, what issue did you hit ? You should confirm first that pyarrow is correctly installed.

**Comment by space192** [comment]
it was complaining about the hadoop executable missing but I also did not install pyarrow, I will try this out !

**Comment by WeichenXu123** [comment]
I will close this ticket since no updates, if you have new issues feel free to reopen it.

**Comment by kavita1205** [comment]
Can someone help me here as I am also getting same error message. Even though I am using latest version i.e. 2.4.1 for installation.

```
2023/06/23 10:12:41 ERROR mlflow.cli: Error initializing backend store
2023/06/23 10:12:41 ERROR mlflow.cli: No module named 'pymysql'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 426, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 279, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 258, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 119, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 138, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 225, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 281, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
(base) [kavsingh@sjc2-nixutil01 ~]$

```

**Comment by WeichenXu123** [comment]
@kavita1205 

You need to run `pip install pymysql` to install it.

**Comment by azarezade** [comment]
i get the same error after pulling latest official docker `docker pull ghcr.io/mlflow/mlflow:v2.7.0` and run it.
```
mlflow-mlflow-1  | 2023/09/18 06:47:00 ERROR mlflow.cli: Error initializing backend store
mlflow-mlflow-1  | 2023/09/18 06:47:00 ERROR mlflow.cli: No module named 'pymysql'
mlflow-mlflow-1  | Traceback (most recent call last):
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 426, in server
mlflow-mlflow-1  |     initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 289, in initialize_backend_stores
mlflow-mlflow-1  |     _get_tracking_store(backend_store_uri, default_artifact_root)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 268, in _get_tracking_store
mlflow-mlflow-1  |     _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
mlflow-mlflow-1  |     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
mlflow-mlflow-1  |     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 129, in _get_sqlalchemy_store
mlflow-mlflow-1  |     return SqlAlchemyStore(store_uri, artifact_uri)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 150, in __init__
mlflow-mlflow-1  |     ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 228, in create_sqlalchemy_engine_with_retry
mlflow-mlflow-1  |     engine = create_sqlalchemy_engine(db_uri)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 284, in create_sqlalchemy_engine
mlflow-mlflow-1  |     return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
mlflow-mlflow-1  |   File "<string>", line 2, in create_engine
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
mlflow-mlflow-1  |     return fn(*args, **kwargs)  # type: ignore[no-any-return]
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
mlflow-mlflow-1  |     dbapi = dbapi_meth(**dbapi_args)
mlflow-mlflow-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
mlflow-mlflow-1  |     return __import__("pymysql")
mlflow-mlflow-1  | ModuleNotFoundError: No module named 'pymysql'

```
