### ISSUE TITLE
[BUG] Timeout errors while uploading large models to mlflow server

### ISSUE THREAD

**Issue by rohanicad** [mlflow/mlflow#8539]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.2.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10, Version 22H2
- **Python version**: 3.9.9
- **yarn version, if running the dev UI**:

### Describe the problem

I am trying to upload  a PCA model (trained using sklearn) to a custom ec2 server. The size of the model is 1.5Gb. I am receiving timeout errors despite increasing  the timeout to 900. I referred to #2401 and tried to increase server timeout but it doesnt help. 

The server configurations during the code run were
```
[Unit]
Description=Mlflow server configuration
[Service]
Type=simple
User=ubuntu
ExecStart=/bin/bash -c 'PATH=/home/ubuntu/.local/bin/:$PATH exec mlflow server --host 0.0.0.0 --port 8883 --artifacts-destination s3://icad-mlflow-artifacts --serve-artifacts --backend-store-uri /home/ubuntu/mlruns --gunicorn-opts "--log-level debug --timeout 900 --graceful-timeout 120"'
WorkingDirectory=/home/ubuntu
Restart=always
[Install]
WantedBy=multi-user.target
```

As highlighted the timeout was set to 900 as recommended in #2401 but the upload was not successful. Additionally, the internet speed should not be an issue and both the upload and download are greater than 10Mbps

### Tracking information

```shell
System information: Windows 10.0.19045
Python version: 3.9.9
MLflow version: 2.2.1
MLflow module location: C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\__init__.py
Tracking URI: <omitted>
Registry URI: <omitted>
Active experiment ID: 586086446372044084
Active run ID: 4a42167d9b324b3eab64db95e79bc882
Active run artifact URI: mlflow-artifacts:/586086446372044084/4a42167d9b324b3eab64db95e79bc882/artifacts
MLflow dependencies:
  Flask: 2.2.3
  Jinja2: 3.1.2
  alembic: 1.10.2
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.31
  importlib-metadata: 6.0.0
  markdown: 3.4.1
  matplotlib: 3.7.1
  numpy: 1.23.5
  packaging: 23.0
  pandas: 1.5.3
  protobuf: 4.22.1
  pyarrow: 11.0.0
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.1
  scipy: 1.9.1
  shap: 0.41.0
  sqlalchemy: 2.0.5.post1
  sqlparse: 0.4.3
  waitress: 2.1.2
```

### Code to reproduce issue

```
import os
import cv2
import numpy as np
import json
import mlflow.pytorch
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import pickle as pk

folder = 'enter the path of folder'
images = []
image_names = []
count =0 
for filename in os.listdir(folder):
    img = cv2.imread(os.path.join(folder,filename))
    img = np.resize(img,(90, 360))
    # print(img.shape)
    if img is not None:
        # print(len(img.flatten()/255))
        images.append(img.flatten()/255)
        image_names.append(filename)

mlflow.set_tracking_uri("mention your tracking uri") 
mlflow.set_experiment(experiment_name="your experiment name")
exp = 'some random name'

with mlflow.start_run(run_name=exp) as run:
    print("run started")
    pca_2000 = PCA(n_components=7000)
    pca_2000_reduced = pca_2000.fit_transform(images)
    pk.dump(pca_2000, open("pca_test_cat.pkl","wb"))
    print("started upload")
    model_info = mlflow.sklearn.log_model(sk_model=pca_2000, artifact_path="pca_cat_dog",registered_model_name= "pca_model_test_notuseful")
```

For the purpose of testing I had used cat dog dataset available on [Kaggle](https://www.kaggle.com/competitions/dogs-vs-cats/data), but one can use any dataset as long as the size of PCA model >= 1.5Gb.  

### Stack trace

```

2023/05/25 19:22:47 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!
Traceback (most recent call last):
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1079, in _send_output
    self.send(chunk)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1001, in send
    self.sock.sendall(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<server url>', port=8883): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/586086446372044084/031b643c33c54003a364e1a26369ff7b/artifacts/pca_cat_dog/model.pkl (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\utils\rest_utils.py", line 167, in http_request
    return _get_http_response_with_retries(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\utils\rest_utils.py", line 98, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='<server url>', port=8883): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/586086446372044084/031b643c33c54003a364e1a26369ff7b/artifacts/pca_cat_dog/model.pkl (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\someting\OneDrive - iCAD Dental\Desktop\git_igps\clustering\training_code_pca\pca_mnist.py", line 39, in <module>
    model_info = mlflow.sklearn.log_model(sk_model=pca_2000, artifact_path="pca_cat_dog",registered_model_name= "pca_model_test_notuseful")
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\sklearn\__init__.py", line 424, in log_model
    return Model.log(
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\store\artifact\http_artifact_repo.py", line 40, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\store\artifact\http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "C:\Users\something\AppData\Local\Programs\Python\Python39\lib\site-packages\mlflow\utils\rest_utils.py", line 185, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to <server url>:8883/api/2.0/mlflow-artifacts/artifacts/586086446372044084/031b643c33c54003a364e1a26369ff7b/artifacts/pca_cat_dog/model.pkl failed with exception HTTPConnectionPool(host='<server url>', port=8883): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/586086446372044084/031b643c33c54003a364e1a26369ff7b/artifacts/pca_cat_dog/model.pkl (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@rohanicad Can you try setting `export MLFLOW_HTTP_REQUEST_TIMEOUT=900`?

**Comment by rohanicad** [comment]
@harupy yes I have tried that. The solution was mentioned in #2401, but it doesnt seem to work for my case

**Comment by rohanicad** [comment]
@BenWilson2 @dbczumar @harupy @WeichenXu123 retagging for resolution

**Comment by BenWilson2** [comment]
@rohanicad can you try with the latest MLflow release? Some changes have been made to artifact serialization that may affect your error.

**Comment by jonbaiernx** [comment]
I'm seeing this behavior as well. I've tried setting timeouts as high as 5000 and it still fails the artifact upload at the same spot. I'm using version 2.9.2 with this code:

```
tinyllama_pipeline = transformers.pipeline(
    task=task,
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)

eval_data = pd.DataFrame(
    {
        "inputs": [            
            "The color of the sky is",
            "The color of the moon is",
        ],
    }
)

# Define the parameters (and their defaults) for optional overrides at inference time.
parameters_sets = [
                {"max_length": 128, "do_sample": True, "temperature": 0.1},
                {"max_length": 128, "do_sample": True, "temperature": 0.4},
                {"max_length": 128, "do_sample": True, "temperature": 0.9}
]

for parameters in parameters_sets:
    signature = mlflow.models.infer_signature(
        input_example,
        mlflow.transformers.generate_signature_output(pipeline_object, input_example),
        parameters,
    )

    #Create run name with model and current temperature
    run_name = pipeline_name + '(temp:'+str(parameters.get('temperature', '--')) + ')'

    with mlflow.start_run(run_name = run_name):
        model_info = mlflow.transformers.log_model(
            transformers_model=pipeline_object,
            artifact_path="text_generation",
            input_example=input_example,
            signature=signature,
        )
        results = mlflow.evaluate(
            model=model_info.model_uri,
            model_type='text',
            data=eval_data,
        )
```

**Comment by kelvin6666** [comment]
any update on this ?

**Comment by toinsson** [comment]
Increasing the timeout AND the number of gunicorn workers solved some issues.
Pseudocode:
```
trackingServer.extraArgs = --gunicorn-opts="--timeout=3600"
trackingServer.workers = 2
```

**Comment by HarveyYan** [comment]
If the mlflow bugs out, can it just ignore and let the program go on? is there an global option for mlflow to set all mlflow exception/error to warning messages?

**Comment by SanadMarji7** [comment]
i had the same upload issue trying to upload a large model either as an artifact or using mlflow.log_model()
i was able to solve it by specifying some envs:
    os.environ["MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD"] = "True"
    os.environ["MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE"] = "209715200"
    os.environ["MLFLOW_MULTIPART_UPLOAD_MAX_WORKERS"] = "1"
    os.environ["MLFLOW_ARTIFACT_UPLOAD_MAX_WORKERS"] = "1"
    os.environ["AZURE_STORAGE_MAX_CONCURRENCY"] = "1"
    os.environ["MLFLOW_HTTP_REQUEST_TIMEOUT"] = "3600"

it worked like magic. all the above recommendations are kinda garbage^^^

**Comment by coldhearti** [comment]
This issue needs to be fixed.

**Comment by B-Step62** [comment]
Large artifact/model uploads are now handled by multipart upload: `HttpArtifactRepository.log_artifact` automatically uses multipart upload for files at or above `MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE` (500MB). For proxied (`--serve-artifacts`) setups like this one, enable it with `MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD=true`, which chunks the upload and avoids the single-request server timeout. Closing as resolved, feel free to reopen if large uploads still time out with proxy multipart upload enabled.
