### ISSUE TITLE
[BUG] Using sftp on mlflow server from client with > 20 CPUs causes Error reading SSH protocol banner [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by vaskokj** [mlflow/mlflow#8540]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.3.2
- Tracking server: 2.3.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.6 (both client and server)
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

We have a tracking server that is using SFTP as the method of transfer for clients. 

We have several clients that have 80+ CPU cores. When a user tries to log something (see attached code here) it will fail with the following error attached on this ticket.

The issue seems to stem from this change that occurred in 2.3.x. 

https://github.com/mlflow/mlflow/blob/v2.3.2/mlflow/store/artifact/artifact_repo.py#L16

It uses the CPU count to calculate the number of threads/connections to use when spawning sftp client connections https://github.com/mlflow/mlflow/blob/v2.2.2/mlflow/store/artifact/sftp_artifact_repo.py#L82. 

I can change the code https://github.com/mlflow/mlflow/blob/v2.3.2/mlflow/store/artifact/sftp_artifact_repo.py#L82

On this particular server `self.max_workers` is 20. I can hard code the change to 8 and the code will work. 

`connections = [pysftp.Connection(**self.config) for _ in range(8)]`

My initial thought was that this was being limited by sshd_config on the sftp server by `MaxSessions` or `MaxStartups` but that seems to make no impact. 

There seems to be an upper limit of 19 for `self.max_workers` as self.max_workers works up to 19. If I set `self.max_workers = 20` then I still get the errors listed in this ticket even with changes to the `MaxSessions` or `MaxStartups` settings changed. This seems to imply that there is some other limit I am hitting somewhere else. 

This is where I am currently at, I am going to keep trying to find what limit I am running into but I am currently running out of ideas. I have already checked `/etc/security/limits.conf` and there is nothing there. This error seems to indicate a server setting limit but besides the sshd_config limits I mentioned, I'm unsure on what other limits I would be hitting. 

### Tracking information

```shell
System information: Linux #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022
Python version: 3.8.16
MLflow version: 2.3.2
MLflow module location: /home/<user>/test/venv/lib/python3.8/site-packages/mlflow/__init__.py
Tracking URI: file:///home/<user>/test/mlruns
Registry URI: file:///home/<user>/test/mlruns
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.2
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.6.0
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.24.3
  packaging: 23.1
  pandas: 2.0.1
  protobuf: 4.23.1
  pyarrow: 11.0.0
  pytz: 2023.3
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.2.2
  scipy: 1.10.1
  sqlalchemy: 2.0.15
  sqlparse: 0.4.4

```

### Code to reproduce issue

```
import mlflow

#Create a features.txt artifact file
features = "rooms, zipcode, median_price, school_rating, transport"
with open("features.txt", "w") as f:
    f.write(features)

# With artifact_path=None write features.txt under
# root artifact_uri/artifacts directory
mlflow.set_tracking_uri('http://mlflow.example.com:8000')
tracking_uri = mlflow.get_tracking_uri()
print("Current tracking uri: {}".format(tracking_uri))

with mlflow.start_run():
    mlflow.log_artifact("features.txt")
```

### Stack trace

```
Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/<user>/test/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2276, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/<user>/test/venv/lib/python3.8/site-packages/paramiko/packet.py", line 375, in readline
    buf += self._read_timeout(timeout)
  File "/home/<user>/test/venv/lib/python3.8/site-packages/paramiko/packet.py", line 603, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<user>/test/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2093, in run
    self._check_banner()
  File "/home/<user>/test/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2280, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by vaskokj** [comment]
@harupy any thoughts on this changes impacting SFTP connections and a possible way to get around it? https://github.com/mlflow/mlflow/blob/v2.3.2/mlflow/store/artifact/artifact_repo.py#L16

**Comment by vaskokj** [comment]
Ok I figured out the issue. The Pala Alto Firewall was seeing this as threat ID 40015 (Brute Force Accept). Disabling this threat ID fixes the issue.

I would recommend decreasing this back down to ~10-12 connections OR making the `_NUM_MAX_THREADS` configurable.
