### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nicolasang333** [mlflow/mlflow#8560]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- ML Flow Version : 2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MAC OS Ventura 13.4
- **Python version**: 3.9.16 
- **yarn version, if running the dev UI**:

### Describe the problem

When I use ML Flow Projects

When I specify a Google Cloud Storage path as a parameter, despite inserting the right credentials, ML Flow will throw a credentials error. 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

[mlflow_error.zip](https://github.com/mlflow/mlflow/files/11593093/mlflow_error.zip)

### Stack trace

2023/05/30 00:08:18 INFO mlflow.utils.conda: Conda environment mlflow-ea89550c19a8d363d5998306efd93905a9c2fcba already exists.
2023/05/30 00:08:18 INFO mlflow.projects.utils: === Created directory /var/folders/1j/hgcglh2d6v556c4k94wp8qxr0000gp/T/tmpghe3ks84 for downloading remote URIs passed to arguments of type 'path' ===
Traceback (most recent call last):
  File "/opt/homebrew/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/cli.py", line 201, in run
    projects.run(
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 338, in run
    submitted_run_obj = _run(
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 105, in _run
    submitted_run = backend.run(
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/backend/local.py", line 181, in run
    command_args += get_entry_point_command(project, entry_point, params, storage_dir)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/utils.py", line 331, in get_entry_point_command
    project.get_entry_point(entry_point).compute_command(parameters, storage_dir_for_run)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/_project_spec.py", line 233, in compute_command
    params, extra_params = self.compute_parameters(user_parameters, storage_dir)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/_project_spec.py", line 226, in compute_parameters
    final_params[key] = param_obj.compute_value(value, storage_dir, key_position)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/_project_spec.py", line 281, in compute_value
    return self._compute_path_value(param_value, storage_dir, key_position)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/projects/_project_spec.py", line 275, in _compute_path_value
    return artifact_utils._download_artifact_from_uri(
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py", line 241, in download_artifacts
    if self._is_directory(artifact_path):
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py", line 79, in _is_directory
    listing = self.list_artifacts(artifact_path)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 107, in list_artifacts
    infos = self._list_folders(bkt, prefix, artifact_path)
  File "/opt/homebrew/lib/python3.10/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 123, in _list_folders
    for page in results.pages:
  File "/opt/homebrew/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 244, in _page_iter
    page = self._next_page()
  File "/opt/homebrew/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
    response = self._get_next_page_response()
  File "/opt/homebrew/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 432, in _get_next_page_response
    return self.api_request(
  File "/opt/homebrew/lib/python3.10/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/opt/homebrew/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/opt/homebrew/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/opt/homebrew/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
    response = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
    return self._do_request(
  File "/opt/homebrew/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
    return self.http.request(
  File "/opt/homebrew/lib/python3.10/site-packages/google/auth/transport/requests.py", line 585, in request
    self.credentials.refresh(auth_request)
  File "/opt/homebrew/lib/python3.10/site-packages/google/auth/credentials.py", line 196, in refresh
    raise exceptions.InvalidOperation("Anonymous credentials cannot be refreshed.")
google.auth.exceptions.InvalidOperation: Anonymous credentials cannot be refreshed.

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nicolasang333 Can you log an artifact?

```python
import mlflow

# Set GCS as an arifact storage?

with mlflow.start_run():
    mlflow.log_artifact(...)
```

**Comment by harupy** [comment]
@nicolasang333 How do you set `GOOGLE_APPLICATION_CREDENTIALS`? Do you set it by `export GOOGLE_APPLICATION_CREDENTIALS=...`. If not, can you try that?
