### ISSUE TITLE
[BUG] / Question : Is `mlflow serve` supposed to work inside of databricks notebooks for spark based flavors?

### ISSUE THREAD

**Issue by C-K-Loan** [mlflow/mlflow#8724]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

Latest

### System information

Latest databricks runtime 13.1

### Describe the problem

I am trying to use `mlflow serve` with spark/johnsnowlabs flavor models but its not possible to launch
a sparksession for the newly launched serve process.

Either I am doing something wrong, there is a bug in pyspark or it is not intended to get the existing SparkSession from a new process launched via a Databricks notebook.  This was requested for DAIS

Since `mlflow serve` launches a new process, the new process must find the sparkcontext from databricks cluster if it is a spark model like it is the case for johnsnowlabs for spark flavors.

The following steps are made inside databricks notebook
1. Create a logistRegression model and save via Mlflow 
2. Try serve it  --->  `RuntimeError: An application name must be set in your configuration` 
3. Try set App Name --> `RuntimeError: A master URL must be set in your configuration`
4. Add Master URL ---> `: org.apache.spark.SparkException: In Databricks, developers should utilize the shared SparkContext instead of creating one using the constructor. In Scala and Python notebooks, the shared context can be accessed as sc. When running a job, you can access the shared context by calling SparkContext.getOrCreate(). ` 

-----

If you check the error trace, you can see on the Python side **SparkContext.getOrCreate()**. was actually called and is throwing the error.   

On the JVM side **org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:3132)** is called and right after that **SparkContext.init**

This only happens when using mlflow serve.  
Trying to run `SparkContext.getOrCreate()`  in the Databricks notebook works fin
But Mlflow is starting a fresh process

### Tracking information

Not relevant

### Code to reproduce issue

See Attached notebook, it has a minimal example for reproducing the error inside of databricks.

### Stack trace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/databricks/spark/python/pyspark/sql/session.py", line 484, in getOrCreate
    else SparkContext.getOrCreate(sparkConf)
  File "/databricks/spark/python/pyspark/context.py", line 560, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/databricks/spark/python/pyspark/context.py", line 204, in __init__
    self._do_init(
  File "/databricks/spark/python/pyspark/context.py", line 294, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
  File "/databricks/spark/python/pyspark/context.py", line 433, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: In Databricks, developers should utilize the shared SparkContext instead of creating one using the constructor. In Scala and Python notebooks, the shared context can be accessed as sc. When running a job, you can access the shared context by calling SparkContext.getOrCreate(). The other SparkContext was created at:
CallSite(SparkContext at DatabricksILoop.scala:362,org.apache.spark.SparkContext.<init>(SparkContext.scala:117)
com.databricks.backend.daemon.driver.DatabricksILoop$.$anonfun$initializeSharedDriverContext$1(DatabricksILoop.scala:362)
com.databricks.backend.daemon.driver.ClassLoaders$.withContextClassLoader(ClassLoaders.scala:29)
com.databricks.backend.daemon.driver.DatabricksILoop$.initializeSharedDriverContext(DatabricksILoop.scala:362)
com.databricks.backend.daemon.driver.DatabricksILoop$.getOrCreateSharedDriverContext(DatabricksILoop.scala:291)
com.databricks.backend.daemon.driver.DriverCorral.driverContext(DriverCorral.scala:272)
com.databricks.backend.daemon.driver.DriverCorral.<init>(DriverCorral.scala:143)
com.databricks.backend.daemon.driver.DriverDaemon.<init>(DriverDaemon.scala:68)
com.databricks.backend.daemon.driver.DriverDaemon$.create(DriverDaemon.scala:618)
com.databricks.backend.daemon.driver.DriverDaemon$.wrappedMain(DriverDaemon.scala:975)
com.databricks.DatabricksMain.$anonfun$main$1(DatabricksMain.scala:148)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
com.databricks.DatabricksMain.$anonfun$withStartupProfilingData$1(DatabricksMain.scala:466)
com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:562)
com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:656)
com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:674)
com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:420)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:205)
com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:418))
	at org.apache.spark.SparkContext$.$anonfun$assertNoOtherContextIsRunning$2(SparkContext.scala:3278)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:3272)
	at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:3407)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:127)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:257)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
```

### Other info / logs

x

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by C-K-Loan** [comment]
Thanks, this makes a lot more sense now

**Comment by B-Step62** [comment]
When the scoring server launches it runs in a separate process that does not inherit the Databricks notebook's `SparkSession`, so Spark-flavor models needing a live cluster session cannot be served this way in-notebook. This is expected; use `spark_udf` for batch scoring, or serve outside the notebook with a configured Spark session. Closing as out of scope.
