### ISSUE TITLE
UI crashed

### ISSUE THREAD

**Issue by LeanderK** [mlflow/mlflow#873]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes, tracking code for my project
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: from pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2
- **Python version**: Python 3.6.8 :: Anaconda, Inc.
- **npm version (if running the dev UI): -
- **Exact command to reproduce**: mlflow ui --file-store .

### Describe the problem
It is unable to load my project. It just shows:

> Oops! Something went wrong.
> If this error persists, please report an issue on our GitHub page.

The problem persists after restarts.

I started the mlflow-ui with:` mlflow ui --file-store .`

While it's loading, i can correctly see the name of the project on the left.
### Source code / logs

```python
[2019-02-05 20:22:21,772] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/runs/search [POST]
Traceback (most recent call last):
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "(just a normal path)/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/server/handlers.py", line 272, in _search_runs
    run_view_type)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 518, in search_runs
    run_infos = self._list_run_infos(experiment_id, run_view_type)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 504, in _list_run_infos
    run_info = self._get_run_info(r_id)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 369, in _get_run_info
    run_info = _read_persisted_run_info_dict(meta)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 40, in _read_persisted_run_info_dict
    dict_copy = run_info_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
[2019-02-05 20:22:22,234] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/experiments/get [GET]
Traceback (most recent call last):
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "(just a normal path)/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "(just a normal path)/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/server/handlers.py", line 127, in _get_experiment
    run_view_type=ViewType.ACTIVE_ONLY)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 526, in list_run_infos
    return self._list_run_infos(experiment_id, run_view_type)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 504, in _list_run_infos
    run_info = self._get_run_info(r_id)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 369, in _get_run_info
    run_info = _read_persisted_run_info_dict(meta)
  File "(just a normal path)/lib/python3.6/site-packages/mlflow/store/file_store.py", line 40, in _read_persisted_run_info_dict
    dict_copy = run_info_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by smurching** [comment]
@LeanderK it unfortunately looks like a run metadata file has gotten into a bad state (my guess is that it's empty, causing `meta` [here](https://github.com/mlflow/mlflow/blob/v0.8.2/mlflow/store/file_store.py#L368) to be None. You can identify the problematic run metadata via the following Python snippet:

```
import os
filestore_root_dir = ... # insert your filestore dir (string) here
experiment_id = ... # insert your experiment ID (int) here
for run_dir in os.listdir(os.path

```

**Comment by LeanderK** [comment]
I get: 
`Run data in file ./mlflow_debug/0/a661de439c5a4004863211cb9c272be9/meta.yaml was malformed`

**Comment by LeanderK** [comment]
./mlflow_debug/0/a661de439c5a4004863211cb9c272be9/` looks normal (logged params, metrics and artifacts etc.), but `meta.yaml` is empty.
I don't know what happened, but i think a more graceful handling would be beneficial (maybe mention that run XY couldn't be loaded due to some error).

**Comment by apurva-koti** [comment]
@LeanderK were you able to resolve the issue?

**Comment by LeanderK** [comment]
I need to check whether it's still occurring. I am currently again in a research mode and not doing much experiments. Last time i wanted to review some results it still occurred (but this was weeks ago and was not on the newest mlflow version back then).

**Comment by culmskami** [comment]
Even I am facing the same issue in mlflow version 1.5.0

**Comment by buti1021** [comment]
Ran into the same issue with version 1.15

**Comment by andreys42** [comment]
Same problem in 2021))

**Comment by GreyDGL** [comment]
Same problem in 2022

**Comment by hoangphucITJP** [comment]
The problem persists in 2.3.1

**Comment by wzm2256** [comment]
Same problem 2.10. Is this problem forgotten?

**Comment by OBrink** [comment]
Same in 2.18!

**Comment by justinas-kazanavicius** [comment]
still getting the same issue!
