### ISSUE TITLE
[BUG] Failed to establish a new connection on Docker

### ISSUE THREAD

**Issue by chrislevn** [mlflow/mlflow#8783]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.3.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS M1 
- **Python version**: 3.9

### Describe the problem

I'm learning MLOPs and I am experimenting running my python script on Docker. 

Python script: 

```Python
python3 src/model_predictor.py --config-path data/model_config/phase-1/prob-1/model-1.yaml --port 8000
```

On the local machine's terminal, if I ran: 
```bash 
export MLFLOW_TRACKING_URI="http://localhost:5001"
```

then following the Python script, the app works fine. 

However, when I try to run this with my Dockerfile

```Dockerfile
# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . /app/

ENV MLFLOW_TRACKING_URI="http://localhost:5001"

CMD ["python3", "src/model_predictor.py", "--config-path", "data/model_config/phase-1/prob-1/model-1.yaml", "--port", "8000"]
```

Even though I have set specifically `http://127.0.0.1:5001` for my tracking URI instead of MLFLOW_TRACKING_URI

```Python
mlflow.set_tracking_uri("http://127.0.0.1:5000")
``` 

It will still return this log:

Logs:
```console
2023-06-17 23:26:07,213 - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff839672b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/model-versions/get-download-uri?name=phase-1_prob-1_model-1&version=3
```

Model has been registered. 

How can I fix this issue? Any leads would be appreciated. Thank you!

### Tracking information

```shell
➜  mlops-mara-sample-public git:(main) ✗ docker build -t mlops-demo .             
[+] Building 0.7s (10/10) FINISHED                                                                                                                                                                                
 => [internal] load .dockerignore                                                                                                                                                                            0.0s
 => => transferring context: 73B                                                                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                         0.0s
 => => transferring dockerfile: 601B                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                                                                           0.4s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:0074c6241f2ff175532c72fb0fb37264e8a1ac68f9790f9ee6da7e9fdfb67a0e                                                                                     0.0s
 => [internal] load build context                                                                                                                                                                            0.0s
 => => transferring context: 20.53kB                                                                                                                                                                         0.0s
 => CACHED [2/5] WORKDIR /app                                                                                                                                                                                0.0s
 => CACHED [3/5] COPY requirements.txt /app/                                                                                                                                                                 0.0s
 => CACHED [4/5] RUN pip install --no-cache-dir -r requirements.txt                                                                                                                                          0.0s
 => [5/5] COPY . /app/                                                                                                                                                                                       0.1s
 => exporting to image                                                                                                                                                                                       0.1s
 => => exporting layers                                                                                                                                                                                      0.1s
 => => writing image sha256:df21be09c451ce381438e9f284833b0367414fae3c8cfe68047699045abddb5d                                                                                                                 0.0s
 => => naming to docker.io/library/mlops-demo                                                                                                                                                                0.0s
➜  mlops-mara-sample-public git:(main) ✗ docker run -p 8000:8000 mlops-demo
2023/06/17 23:42:46 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2023-06-17 23:42:46,208 - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b562b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:42:50,214 - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6c852a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:42:58,226 - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6c852a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create

```

### Code to reproduce issue

Clone this repo: https://github.com/chrislevn/mlops-mara-sample-public

## Quickstart

1.  Prepare environment

    ```bash
    # Install python 3.9
    # Install docker version 20.10.17
    # Install docker-compose version v2.6.1
    pip install -r requirements.txt
    make mlflow_up
    ```

2.  Train model

    -   Download data, `./data/raw_data` dir should look like

        ```bash
        data/raw_data
        ├── .gitkeep
        └── phase-1
            └── prob-1
                ├── features_config.json
                └── raw_train.parquet
        ```

    -   Process data

        ```bash
        python src/raw_data_processor.py --phase-id phase-1 --prob-id prob-1
        ```

    -   After processing data, `./data/train_data` dir should look like

        ```bash
        data/train_data
        ├── .gitkeep
        └── phase-1
            └── prob-1
                ├── category_index.pickle
                ├── test_x.parquet
                ├── test_y.parquet
                ├── train_x.parquet
                └── train_y.parquet
        ```

    -   Train model

        ```bash
        export MLFLOW_TRACKING_URI=http://localhost:5001
        python src/model_trainer.py --phase-id phase-1 --prob-id prob-1
        ```

    -   Register model: Go to mlflow UI at <http://localhost:5001> and register a new model named **phase-1_prob-1_model-1**

3.  Deploy model predictor

    -   Create model config at `data/model_config/phase-1/prob-1/model-1.yaml` with content:

        ```yaml
        phase_id: "phase-1"
        prob_id: "prob-1"
        model_name: "phase-1_prob-1_model-1"
        model_version: "1"
        ```

    -   Test model predictor

        ```bash
        # run model predictor
        export MLFLOW_TRACKING_URI=http://localhost:5001
        python src/model_predictor.py --config-path data/model_config/phase-1/prob-1/model-1.yaml --port 8000

        # curl in another terminal
        curl -X POST http://localhost:8000/phase-1/prob-1/predict -H "Content-Type: application/json" -d @data/curl/phase-1/prob-1/payload-1.json

        # stop the predictor above
        ```

    -   Deploy model predictor

        ```bash
        make predictor_up
        make predictor_curl
        ```

    -   After running `make predictor_curl` to send requests to the server, `./data/captured_data` dir should look like:

        ```bash
         data/captured_data
         ├── .gitkeep
         └── phase-1
             └── prob-1
                 ├── 123.parquet
                 └── 456.parquet
        ```

4. Run Docker: 
- Make sure Docker is running on your machine 
- Move to root folder
- Create a Docker image with 
```shell
docker build -t mlops-demo .
```

- Run the Docker image: 
```shell
docker run -p 8000:8000 mlops-demo
```

5.  Teardown

    ```bash
    make teardown
    ```

### Stack trace

```
➜  mlops-mara-sample-public git:(main) ✗ docker run -p 8000:8000 mlops-demo
2023/06/17 23:42:46 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2023-06-17 23:42:46,208 - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b562b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:42:50,214 - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6c852a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:42:58,226 - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6c852a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:43:14,244 - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b34aac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
2023-06-17 23:43:46,272 - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b34ab50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/create
MLflow version: 2.3.2
Tracking URI: http://127.0.0.1:5001
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff5b362160>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b362160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 187, in http_request
    return _get_http_response_with_retries(
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 118, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b362160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/model_predictor.py", line 158, in <module>
    predictor = ModelPredictor(config_file_path=args.config_path)
  File "/app/src/model_predictor.py", line 48, in __init__
    print("Artifact URI:", mlflow.get_artifact_uri())
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 1334, in get_artifact_uri
    run_id=_get_or_start_run().info.run_id, artifact_path=artifact_path
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 1553, in _get_or_start_run
    return start_run()
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 351, in start_run
    active_run_obj = client.create_run(
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/client.py", line 280, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/usr/local/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 131, in create_run
    return self.store.create_run(
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/usr/local/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 300, in call_endpoint
    response = http_request(
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 205, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:5001/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5b362160>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
It looks like you're not opening the correct ports in your container. The -p option should be in the format:

`docker run -p <host-port>:<container-port> <image-name>`

You've opened up port 8000 based on your pasted bash commands. Could you make sure that you're opening the right port so that the tracking server running in the container can talk to the outside world? If your tracking server is setup to communicate via port 5001, then that port needs to be open.

**Comment by B-Step62** [comment]
Inside a container, `localhost` refers to the container itself, not the host running the tracking server. Use `host.docker.internal` (or the service name on a shared Docker network) as the tracking URI host. Closing as a configuration issue, feel free to reopen if it reproduces with correct container networking.
