### ISSUE TITLE
[SETUP-BUG] 

### ISSUE THREAD

**Issue by kavita1205** [mlflow/mlflow#8820]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**: 2.4.1
- **Python version**: Python 3.10.6
- - Tracking server: 2.4.1
- 

Hi Team,

I am using mlflow version 2.4.1 image for deploying helm chart in kubernetes cluster. I am using mysql as database and passing pymsql as dilect/driver but I am getting below error message:

Can someone please help me here.

```
2023/06/23 10:12:41 ERROR mlflow.cli: Error initializing backend store
2023/06/23 10:12:41 ERROR mlflow.cli: No module named 'pymysql'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 426, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 279, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 258, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 119, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 138, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 225, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 281, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
(base) [kavsingh@sjc2-nixutil01 ~]$

```

### Code to reproduce issue

helm install mlflow helm-repository/mlflow -f values.yaml -f Chart.yaml

### Describe the problem

After running helm install, pod is going into crashloopbackoff due to above error message.

**Comment by WeichenXu123** [comment]
@kavita1205 Hi you just need to install `pymysql` by pip.
