### ISSUE TITLE
[BUG] Cannot load registered huggingface ImageClassificationPipeline pipeline on CUDA device (Azure ML studio)

### ISSUE THREAD

**Issue by Thodorissio** [mlflow/mlflow#8855]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.4.1
- azureml-mlflow: 1.52.0

### System information

- **OS Platform and Distribution **: Ubuntu 20.04.6 LTS
- **Python version**: 3.10.11

### Describe the problem

We are currently working in Azure ML Studio in order to train a (transformers ImageClassificationPipeline)[]. While we have succeded in training the model and we have also successfully registered the model in the Azure ML Studio Model Registry, we face some problems to load back the registered model in order to perform inference. Our issue is that we cannot load the model on the CUDA device. 

We use the [mlflow.transformers.log_model](https://mlflow.org/docs/2.4.1/python_api/mlflow.transformers.html#mlflow.transformers.log_model) method to log the pipeline, according to the example.

We use the [mlflow.register_model](https://mlflow.org/docs/2.4.1/python_api/mlflow.html#mlflow.register_model) method to register the pipeline.

Finally, to load back the model we use the [mlflow.transformers.load_model](https://mlflow.org/docs/2.4.1/python_api/mlflow.transformers.html#mlflow.transformers.load_model) method, setting the device argument to 0 as this value is supposed to load the model on CUDA device.

No errors occur, but we got the following warning : 
**WARNING mlflow.transformers: Could not specify device parameter for this pipeline type**

### Tracking information

```shell
System information: Linux #42~20.04.1-Ubuntu SMP Wed Mar 1 19:17:41 UTC 2023
Python version: 3.10.11
MLflow version: 2.4.1
MLflow module location: /anaconda/envs/classification/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: azureml://XXXX
Registry URI: azureml://XXXX
MLflow environment variables: 
  MLFLOW_TRACKING_URI: azureml://XXXX
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.7.0
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.23.5
  packaging: 22.0
  pandas: 2.0.2
  protobuf: 4.23.3
  pyarrow: 12.0.0
  pytz: 2023.3
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.2.2
  scipy: 1.10.1
  sqlalchemy: 2.0.16
  sqlparse: 0.4.4
```

### Code to reproduce issue

```python
import logging
import mlflow
from transformers import pipeline
from transformers import AutoImageProcessor, AutoModelForImageClassification

logger = logging.getLogger("my-logger")
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
ch.setFormatter(logging.Formatter("%(levelname)s - %(message)s"))
logger.addHandler(ch)

feature_extractor = AutoImageProcessor.from_pretrained("microsoft/dit-base-finetuned-rvlcdip")
model = AutoModelForImageClassification.from_pretrained("microsoft/dit-base-finetuned-rvlcdip")

clf = pipeline(
    task="image-classification",
    model=model,
    feature_extractor=feature_extractor,
    batch_size=256,
    device=0,
)

logger.debug(f"pipeline device when registering: {clf.device}")

mlflow.set_experiment("pipeline_to_mlflow")

with mlflow.start_run() as run:
    mlflow.transformers.log_model(transformers_model=clf, artifact_path="dit-pipeline")
    mlflow.transformers.save_model(transformers_model=clf, path="local-dit-pipeline")
    
run_id = run._info.run_id
mlflow.register_model(f"runs:/{run_id}/dit-pipeline/", "dit-pipeline")

logger.debug(f"Mlflow gpu available: {mlflow.transformers.is_gpu_available()}")

clf = mlflow.transformers.load_model("models:/dit-pipeline/latest", device=0)
logger.debug(f"Loaded pipeline from registry, device: {clf.device}")

clf_local = mlflow.transformers.load_model("local-dit-pipeline", device=0)
logger.debug(f"Loaded pipeline from local dir, device: {clf_local.device}")
```

### Stack trace

No Errors occur

### Other info / logs

```
2023-06-27 09:43:07.751475: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use
 available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags
.
2023-06-27 09:43:08.648673: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRTCould not find image processor class in the image processor config or the model config. Loading based on pattern matching w
ith the model's feature extractor configuration.
/anaconda/envs/classification/lib/python3.10/site-packages/transformers/models/beit/image_processing_beit.py:108: FutureWarning: The `reduce_labels` parameter is deprecated and will be removed in a future version. Please use `do_reduce_labels
` instead.
  warnings.warn(DEBUG - pipeline device when registering: cuda:0
2023/06/27 09:43:23 WARNING mlflow.transformers: This model is unable to be used for pyfunc prediction because the model is
 not a language-based model and requires a complex input type that is currently not supported. The pyfunc flavor will not be added to the Model.
2023/06/27 09:43:23 WARNING mlflow.transformers: Could not infer model execution engine type due to huggingface_hub not bei
ng installed or unable to connect in online mode. Adding full dependency chain: ['transformers==4.28.0', 'torch==2.0.1', 't
orchvision==0.15.2', 'tensorflow==2.12.0'].
Failure cause: No module named 'accelerate'
2023/06/27 09:43:27 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (mod
el URI: /tmp/tmpw86fjiql/model, flavor: transformers), fall back to return ['transformers==4.28.0', 'torch==2.0.1', 'torchv
ision==0.15.2', 'tensorflow==2.12.0']. Set logging level to DEBUG to see the full traceback.
/anaconda/envs/classification/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is r
eplacing distutils.
2023/06/27 09:43:53 WARNING mlflow.transformers: This model is unable to be used for pyfunc prediction because the model is
 not a language-based model and requires a complex input type that is currently not supported. The pyfunc flavor will not b
e added to the Model.
2023/06/27 09:43:53 WARNING mlflow.transformers: Could not infer model execution engine type due to huggingface_hub not bei
ng installed or unable to connect in online mode. Adding full dependency chain: ['transformers==4.28.0', 'torch==2.0.1', 't
orchvision==0.15.2', 'tensorflow==2.12.0'].
Failure cause: No module named 'accelerate'
2023/06/27 09:43:57 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (mod
el URI: /path/to/local-dit-pipeline, flavor: transformers), fall back to return ['transformers==4.28.0', 'torch==2.0.1', 'torchvision==0.15.2', 'tensorflow==2.12.0'
]. Set logging level to DEBUG to see the full traceback.
Registered model 'dit-pipeline' already exists. Creating a new version of this model...
2023/06/27 09:43:59 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: dit-pipeline, version 4
Created version '4' of model 'dit-pipeline'.
DEBUG - Mlflow gpu available: True
2023/06/27 09:44:09 INFO mlflow.transformers: 'models:/dit-pipeline/latest' resolved as 'azureml://XXXX/artifacts/dit-pipe
line/'
2023/06/27 09:44:10 WARNING mlflow.transformers: Could not specify device parameter for this pipeline type
DEBUG - Loaded pipeline from registry, device: cpu
2023/06/27 09:44:20 WARNING mlflow.transformers: Could not specify device parameter for this pipeline type
DEBUG - Loaded pipeline from local dir, device: cpu
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Could you attach the stacktrace of the exception raised here ? https://github.com/mlflow/mlflow/blob/991eec617a097e4938fbff953ed64066cf159126/mlflow/transformers.py#L857

You can use my modified code to make the stacktrace printed:
https://github.com/mlflow/mlflow/compare/master...WeichenXu123:mlflow:debug8855?expand=1

You can install my modified mlflow by `pip install git+https://github.com/WeichenXu123/mlflow.git@debug8855`

**Comment by Thodorissio** [comment]
Yes certainly.

The stacktrace of the exception:
```shell
Traceback (most recent call last):
  File "/anaconda/envs/classification/lib/python3.10/site-packages/mlflow/transformers.py", line 913, in _load_model
    model = model_instance.from_pretrained(model_path, **accelerate_model_conf)
  File "/anaconda/envs/classification/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2202, in from_pretrained
    raise ImportError(
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/classification/lib/python3.10/site-packages/mlflow/transformers.py", line 856, in _try_load_model_with_device
    model = model_instance.from_pretrained(model_path, **load_model_conf)
  File "/anaconda/envs/classification/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: BeitForImageClassification.__init__() got an unexpected keyword argument 'device'
```

I installed accelerate to fix the ImportError and the new stacktrace of the exception is the following:
```shell
Traceback (most recent call last):
  File "/anaconda/envs/classification/lib/python3.10/site-packages/mlflow/transformers.py", line 913, in _load_model
    model = model_instance.from_pretrained(model_path, **accelerate_model_conf)
  File "/anaconda/envs/classification/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2703, in from_pretrained
    raise ValueError(f"{model.__class__.__name__} does not support `device_map='{device_map}'` yet.")
ValueError: BeitForImageClassification does not support `device_map='auto'` yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/classification/lib/python3.10/site-packages/mlflow/transformers.py", line 856, in _try_load_model_with_device
    model = model_instance.from_pretrained(model_path, **load_model_conf)
  File "/anaconda/envs/classification/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: BeitForImageClassification.__init__() got an unexpected keyword argument 'device'
```

**Comment by Thodorissio** [comment]
Yes, I have not found the device argument inside the `BeitForImageClassification` but running the code below
```python
clf = mlflow.transformers.load_model("models:/dit-pipeline/latest", device=0)
print(type(clf.model))
print(clf.model.device)
```

works fine with device:

```shell
<class 'transformers.models.beit.modeling_beit.BeitForImageClassification'>
cpu
```

**Comment by WeichenXu123** [comment]
It loaded successfully because it fallbacks to load model without device argument, see this line code:
https://github.com/mlflow/mlflow/blob/152063e0b6fbadfbb2baecaf7d0ac7ca1b304b31/mlflow/transformers.py#L859

But does `BeitForImageClassification` support loading model to GPU device ?

**Comment by Thodorissio** [comment]
Yes but the `BeitForImageClassification` can be loaded with cuda:

```python
clf.model.to(torch.device("cuda"))
print(clf.mode.device)
```

Outputs:
```shell
cuda:0
```

**Comment by WeichenXu123** [comment]
@Thodorissio 

I discussed with @Ben

model serving does not support `model.to(device)` because it only supports [accelerate](https://huggingface.co/docs/accelerate/index) library

**Comment by WeichenXu123** [comment]
I think we're going to have to support this by way of a feature branch that supports more things from the image libraries (I don't think it's going to be a quick fix)

**Comment by Thodorissio** [comment]
Okay thank you very much for the update! I will also look into it.

**Comment by Dobatymo** [comment]
I am having the same issue.

```python
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

# logging the model
pipeline(
    task="text-classification",
    model=trainer.model,  # trainer is the transformers trainer
    tokenizer=tokenizer,
)
mlflow.transformers.log_model(pipe, "my_model")

# loading the model
model = mlflow.transformers.load_model(model_path, device=0)
print(model.device)  # "cpu"
```
yields
> 2024/04/26 13:45:29 WARNING mlflow.transformers.model_io: Could not specify device parameter for this pipeline type.Falling back to loading the model with the default device.
cannot access local variable 'model' where it is not associated with a value
cannot access local variable 'model' where it is not associated with a value

However
```python
model = AutoModelForSequenceClassification.from_pretrained(the_model_path)  # saved by trainer.save_model(the_model_path)
tokenizer = AutoTokenizer.from_pretrained(tok_path)
pipe = pipeline(task="text-classification", model=model, tokenizer=tokenizer, device=0)
print(pipe.device)  # cuda:0
```
works fine.

**Comment by mosama1994** [comment]
I am also running into the same issue the model loaded from registry gets offloaded to cpu and disk, although i mentioned device=0 and also passed kwargs.

**Comment by mosama1994** [comment]
You can try the following, it loads on cuda, I tested it in databricks mlflow.

model_name = "llama3-sql"
model_version = 1

model = mlflow.transformers.load_model(model_uri = f"models:/{model_name}/{model_version}", return_type='pipeline', kwargs={'device_map': "auto", "torch_dtype": torch.bfloat16})

This resolves the issue. If it still does not work for you, try this:
model = mlflow.transformers.load_model(model_uri = f"models:/{model_name}/{model_version}", return_type='pipeline', kwargs={'device_map': "cuda:0", "torch_dtype": torch.bfloat16}, device="cuda:0")

Hopefully this will resolve the issue.

I am using transformers 4.40.0 and mlflow 2.13.0
