### ISSUE TITLE
[BUG] Missing databricks profile info in artifact_uri

### ISSUE THREAD

**Issue by RuairiB** [mlflow/mlflow#8961]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.4.1
- Tracking server: n/a

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.6.5
- **Python version**: 3.10.9
- **yarn version, if running the dev UI**: n/a

### Describe the problem

(this is a replacement for the mislabelled #8953)

**Example scenario:**
Using artifacts API to download artifacts from models stored in a Databricks Model Registry, with Databricks profile info specified only by `tracking_uri` parameter passed to `mlflow.artifacts.download_artifacts`. i.e. `mlflow.set_tracking_uri()` and Databricks profile environment variables have not been set.

**Bug:**
`tracking_uri` parameter is ignored by `mlflow.artifacts.download_artifacts()` when an `artifact_uri` is passed instead of a `run_id`. If the documented form for `artifact_uri` is used, databricks profile information is missing and an MLflowException is returned:

> mlflow.exceptions.MlflowException: Could not find registered model with name <model_name>

Adjusting `artifact_uri` using `mlflow.tracking.artifact_utils.add_databricks_profile_into_to_artifact_uri` solves issue.

**Suggested fix:**
Add ` add_databricks_profile_info_to_artifact_uri` to https://github.com/mlflow/mlflow/blob/9bab5d93f62da6a2ba16896d910ad78fb282ef2a/mlflow/artifacts/__init__.py#L59-L60:

```python
    if artifact_uri is not None:
        return _download_artifact_from_uri(
            add_databricks_profile_info_to_artifact_uri(artifact_uri, tracking_uri),
            output_path=dst_path,
        )
```

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000
Python version: 3.10.9
MLflow version: 2.4.1
MLflow module location: /opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: file:///Users/rbrett/debug/mlruns
Registry URI: file:///Users/rbrett/debug/mlruns
MLflow dependencies:
  Flask: 2.2.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.30
  gunicorn: 20.1.0
  importlib-metadata: 5.2.0
  markdown: 3.4.1
  matplotlib: 3.7.0
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.3
  protobuf: 4.21.12
  pyarrow: 10.0.1
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.1
  scipy: 1.10.0
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
None
```

### Code to reproduce issue

```python
import mlflow

databricks_profile = "TEST-PROFILE"
model_name = "test_model"
model_stage = "None"
output_dir = "data"

# set databricks tracking URI to use local databricks profile
remote_uri = f"databricks://{databricks_profile}"
# set model_artifact_uri following mlflow.artifacts.download_artifacts docstring
model_artifact_uri = f"models:/{model_name}/{model_stage}"

local_output_path = mlflow.artifacts.download_artifacts(
    artifact_uri=model_artifact_uri,
    dst_path=output_dir,
    tracking_uri=remote_uri,
)
```

### Stack trace

```shell

Traceback (most recent call last):
  File "/Users/rbrett/debug/download_mlflow.py", line 111, in <module>
    local_path = mlflow.artifacts.download_artifacts(
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/artifacts/__init__.py", line 60, in download_artifacts
    return _download_artifact_from_uri(artifact_uri, output_path=dst_path)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 114, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 44, in __init__
    uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 78, in get_underlying_uri
    (name, version) = get_model_name_and_version(client, uri)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py", line 94, in get_model_name_and_version
    return model_name, str(_get_latest_model_version(client, model_name, model_stage))
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py", line 32, in _get_latest_model_version
    latest = client.get_latest_versions(name, None if stage is None else [stage])
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/tracking/client.py", line 2425, in get_latest_versions
    return self._get_registry_client().get_latest_versions(name, stages)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 140, in get_latest_versions
    return self.store.get_latest_versions(name, stages)
  File "/opt/anaconda3/envs/mlflow_debug/lib/python3.10/site-packages/mlflow/store/model_registry/file_store.py", line 363, in get_latest_versions
    raise MlflowException(
mlflow.exceptions.MlflowException: Registered Model with name=test_model not found
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this! I think your proposed fix makes sense. Feel free to file a PR !

**Comment by RuairiB** [comment]
> Thanks for reporting this! I think your proposed fix makes sense. Feel free to file a PR !

PR filed & ready for review: #8965 !
