### ISSUE TITLE
Error while using mlflow tracking server as SFTP-server for artifacts store

### ISSUE THREAD

**Issue by AlinaYablokova** [mlflow/mlflow#898]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3.6.7.
- **npm version (if running the dev UI): - 
- **Exact command to reproduce**:follow the link to run results a t<tracking_server_uri>

### Describe the problem
I tried to use the SFTP for artifact storage and encountered with following issues:

1. I started the MLFLow server (**server 1**) in the following way:

`mlflow server --host *.*.*.*  --file-store /home/user/file_store_location/`

2. Also I set artifacts storage uri in the mlflowscript:
```
client = MlflowClient(tracking_uri=**<server 1>**)
exp_id = client.create_experiment(exp_name, artifact_location=**<server 2>**/home/user/arts_store_location/)
```
**server 2** is SFTP server physically located at the same machine as **server 1**.
3. Client code runs on **server 3**. And everything works fine: I got the metrics and params at **server 1** and I got artifacts at **server 2** (but file store and artifacts store are just the nearby folders on the one machine).
4. The problems appear when I try to look at the experiment results at server 1. I open in browser http://*.*.*.*:5000 and I can see the list of runs. But when I try to follow by the link to specific run I got an error:

/home/mroot/.local/lib/python3.6/site-packages/pysftp/__init__.py:61: UserWarning: Failed to load HostKeys from /home/mroot/.ssh/known_hosts.  You will need to explicitly load HostKeys (cnopts.hostkeys.load(filename)) or disableHostKey checking (cnopts.hostkeys = None).
  warnings.warn(wmsg, UserWarning)
[2019-02-18 11:49:19,561] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 288, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 345, in _get_artifact_repo
    return ArtifactRepository.from_artifact_uri(run.info.artifact_uri, store)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/store/artifact_repo.py", line 117, in from_artifact_uri
    return SFTPArtifactRepository(artifact_uri)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/store/sftp_artifact_repo.py", line 50, in __init__
    self.sftp = pysftp.Connection(**self.config)
  File "/home/mroot/.local/lib/python3.6/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/home/mroot/.local/lib/python3.6/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
paramiko.ssh_exception.SSHException: No hostkey for host <server 1> found.

5. Then I have created known_hosts by:
`ssh-keyscan -H [hostname],[ip_address] >> ~/.ssh/known_hosts
ssh-keyscan -H [ip_address] >> ~/.ssh/known_hosts
ssh-keyscan -H [hostname] >> ~/.ssh/known_hosts`
Running mlflow script finished successfully as previously. But new error at the same point is:

/home/mroot/.local/lib/python3.6/site-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.ecdsa_curve.curve_class(), pointinfo
[2019-02-18 12:06:15,289] ERROR in app: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mroot/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 288, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/server/handlers.py", line 345, in _get_artifact_repo
    return ArtifactRepository.from_artifact_uri(run.info.artifact_uri, store)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/store/artifact_repo.py", line 117, in from_artifact_uri
    return SFTPArtifactRepository(artifact_uri)
  File "/home/mroot/.local/lib/python3.6/site-packages/mlflow/store/sftp_artifact_repo.py", line 50, in __init__
    self.sftp = pysftp.Connection(**self.config)
  File "/home/mroot/.local/lib/python3.6/site-packages/pysftp/__init__.py", line 142, in __init__
    self._set_authentication(password, private_key, private_key_pass)
  File "/home/mroot/.local/lib/python3.6/site-packages/pysftp/__init__.py", line 156, in _set_authentication
    raise CredentialException("No password or key specified.")
pysftp.exceptions.CredentialException: No password or key specified.

The issue seems similar to https://github.com/mlflow/mlflow/issues/447. But I have no problems with logging artifacts, just displaying.
### Source code / logs
![image](https://user-images.githubusercontent.com/28987306/52942850-e4da8c00-337c-11e9-9879-4638bf000f6b.png)
![image](https://user-images.githubusercontent.com/28987306/52942935-0b98c280-337d-11e9-84a9-62639ab7c468.png)

**Comment by AlinaYablokova** [comment]
I suppose, I've solved this problem by providing server 1 an access to itself through ssh (like on sftp-server). It looks strange, but it works...

**Comment by enpinzolas** [comment]
This error might had happened because the client didn´t have the server in the known_hosts list. 
Then, as both server1 and 2 are the same server, connecting 1 to himself added the public its own public key to its know hosts, and the you could connect through pysftp.

**Comment by AlinaYablokova** [comment]
@enpinzolas , thanks. As I aforementioned, I did exactly what you say. And everything works. I'm glad to hear that my solution was "approved".

**Comment by maltequast** [comment]
I am still facing the same issue. Tried this solution, but I still get a connection refused. May I ask how your sshd_config looks. Thanks in advance.
