### ISSUE TITLE
[BUG] Error when returning a null value for array types in spark_udf

### ISSUE THREAD

**Issue by freud14-tm** [mlflow/mlflow#8986]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu AWS
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

When returning an array type in a model and using spark_udf, I get the following error message:

### Code to reproduce issue

Here is a minimal reproducible example:

```python
import mlflow
import numpy as np
import pandas as pd
import pyspark.sql.functions as F


class MyMLFLowModel(mlflow.pyfunc.PythonModel):
    def predict(self, context, model_input):
        model_input["B"] = list(np.random.rand(len(model_input), 100))
        # Insert null values
        model_input["B"] = [v if i % 2 == 1 else None for i, v in zip(model_input["A"], model_input["B"])]
        return model_input

with mlflow.start_run():
    model = MyMLFLowModel()
    model_info = mlflow.pyfunc.log_model("model", python_model=model)

model_udf = mlflow.pyfunc.spark_udf(spark, model_uri=model_info.model_uri, result_type="B array<double>")


test_df = spark.createDataFrame(pd.DataFrame(np.arange(10), columns=['A']))
pred_df = test_df.withColumn("prediction", model_udf(F.struct("*")))
pred_df.toPandas()
```

It works fine when creating my own UDF:

```python
from typing import Any, Union, Iterator, Tuple
import numpy as np
import pandas as pd
import pyspark.sql.functions as F

@F.pandas_udf("B array<double>")
def custom_udf(
    iterator: Iterator[Tuple[Union[pd.Series, pd.DataFrame], ...]]
) -> Iterator[pd.DataFrame]:
    for input_batch in iterator:
        if isinstance(input_batch, (pd.Series, pd.DataFrame)):
            # UDF is called with only one argument
            row_batch_args = (input_batch,)
        else:
            row_batch_args = input_batch

        if len(row_batch_args[0]) > 0:
            pred = model_loaded.predict(*row_batch_args)
            yield pred

test_df = spark.createDataFrame(pd.DataFrame(np.arange(10), columns=['A']))
pred_df = test_df.withColumn("prediction", custom_udf(F.struct("*"))).select("A", "prediction.*")
pred_df.toPandas()
```

### Stack trace

```python
Traceback (most recent call last):
  File "pyarrow/array.pxi", line 915, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 312, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Can only convert 1-dimensional array values
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
See https://github.com/mlflow/mlflow/pull/8934/commits/d8f76719dabf10f7ff5e8f248bd149849f4e97fa
You can help test it .

**Comment by harupy** [comment]
Do we need to fix this issue #8934?

**Comment by WeichenXu123** [comment]
I will file a separate PR .

**Comment by WeichenXu123** [comment]
I create a temp branch for @freud14-tm testing. https://github.com/WeichenXu123/mlflow/tree/infer-spark-udf-return-type-test

Separate PR will be filed later, after https://github.com/mlflow/mlflow/pull/8934 is merged.

**Comment by freud14-tm** [comment]
Hi @WeichenXu123 , your branch seems to work fine with my example. Could expand it with np.nan as well as None for the null value?

**Comment by freud14-tm** [comment]
Something like this maybe?

```python
    def isnull(x):
        return x is None or (isinstance(x, float) and bool(np.isnan(x)))

    if array_dim == 1:
        return [
            np.array(v, dtype=np_type) if not isnull(v) else None
            for v in values
        ]
    else:
        return [
            list(np.array(v, dtype=np_type)) if not isnull(v) else None
            for v in values
        ]
```

**Comment by WeichenXu123** [comment]
@freud14-tm 

Curious, using nan to represent a Null array type value looks weird, why not normalize them to None in your model PyFunc code ?

**Comment by freud14-tm** [comment]
@WeichenXu123 [Pandas' mask function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mask.html) uses NaN by default to mask values:

```python
In [1]: import pandas as pd
    ...: import numpy as np
    ...: df = pd.DataFrame(np.arange(10), columns=['A'])
    ...: df["B"] = list(np.random.rand(len(df), 100))
    ...: df["B"] = df["B"].mask(df["A"] > 6)

In [2]: df
Out[2]: 
   A                                                  B
0  0  [0.1662489584427871, 0.5755128839154969, 0.742...
1  1  [0.41264499355065565, 0.3730176504554157, 0.91...
2  2  [0.35416690679816887, 0.3460157576018883, 0.80...
3  3  [0.6997412903780977, 0.3410781680833527, 0.207...
4  4  [0.12594319666172327, 0.07381316666689552, 0.3...
5  5  [0.17082912559752683, 0.3902643417345594, 0.97...
6  6  [0.5727333826943939, 0.9925955283710716, 0.454...
7  7                                                NaN
8  8                                                NaN
9  9                                                NaN
```
