### ISSUE TITLE
[BUG] Mlflow 2.4.1 HTTSConnectionPool exception while trying to use create experiment API from Mlflow client app

### ISSUE THREAD

**Issue by ChitraNairInfosys** [mlflow/mlflow#9041]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 1.29.0
- Tracking server: 2.4.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon Linux 2
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

I am upgrading MLflow 1.4 to 2.4.1 - In dev environment everything looks fine and while performing production upgrade with the same Mlflow package I had to get the server up via Gunicorn command instead of Mlflow server

With that when I try mlflow create experiment from a client application - it is throwing HTTSConnectionPool exception
Max retries exceeded with url: /api/2.0/mlflow/experiments/create (Caused by ResponseError('too many 500 error responses'))
Get, List are working which means connectivity to backend is fine, and pipeline trigger via Databricks is also looking good

I have reviewed all the steps multiple times, and also tried reinstall - reconnect to RDS and S3 - reviewed the permissions, access - Anyone can help suggest anything? Would be great help as I am stuck with this. Thanks.

Traceback (most recent call last):
  File "mlflow_prod_final_test.py", line 32, in <module>
    exp_id = mlflow_helper.get_or_create_experiment("pdf_athena_mlflow_dev_test_new2_12")
  File "mlflow_prod_final_test.py", line 27, in get_or_create_experiment
    exp_id = self.client.create_experiment(experiment_name)
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/tracking/client.py", line 617, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 240, in create_experiment
    return self.store.create_experiment(
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 124, in create_experiment
    response_proto = self._call_endpoint(CreateExperiment, req_body)
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 271, in call_endpoint
    response = http_request(
  File "/home/ec2-user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 178, in http_request
    raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to https://<mlflow_url>/api/2.0/mlflow/experiments/create failed with exception HTTPSConnectionPool(host='mlflow.prod.mlp.mcafee.red', port=443): Max retries exceeded with url: /api/2.0/mlflow/experiments/create (Caused by ResponseError('too many 500 error responses'))

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @ChitraNairInfosys Could you share the code to reproduce your problem? A setup about your environment could be useful as well. Thanks :)

**Comment by B-Step62** [comment]
This is a client/server connectivity error (`HTTPSConnectionPool`), not an MLflow defect, and there is not enough detail to diagnose. Closing, feel free to reopen with the full traceback and your server/network setup on a current version.
