### ISSUE TITLE
mlflow ui exception could be more explanatory

### ISSUE THREAD

**Issue by dmatrix** [mlflow/mlflow#91]
If you already have an existing Flask server running or bound to port 5000 and you forgot about it, a subsequent invocation of  'mlflow ui' on command fails with the exception: 
Traceback (most recent call last):
  File "/Users/jules/pyenv/vpyenv/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/mlflow/cli.py", line 131, in ui
    mlflow.server._run_server(file_store, file_store, host, port, 1)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/mlflow/server/__init__.py", line 48, in _run_server
    env=env_map, stream_output=True)
  File "/Users/jules/pyenv/vpyenv/lib/python2.7/site-packages/mlflow/utils/process.py", line 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1

Better to extract the exception or root cause of the error: For example port 5000 already bound, or failed to connect to port 5000. Already in use. 
Cheers

**Comment by mikehuston** [comment]
@dmatrix do you think we can close this issue with https://github.com/databricks/mlflow/pull/140 merged? Thanks!

**Comment by smurching** [comment]
@mikehuston thanks for the contribution! Thanks @dmatrix for reporting the issue, feel free to reopen if something comes up :)
