### ISSUE TITLE
[BUG] psycopg3 mlflow-server error : operator does not exist: integer = character varying

### ISSUE THREAD

**Issue by raphaelauv** [mlflow/mlflow#9151]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.5.0
- Tracking server: 2.5.0

### System information

- ubuntu 22.04
- 3.10

### Describe the problem

If I use an mlflow-server with `psycopg[binary,pool]==3.1.9`

when I try to log_param , it fail 

### Tracking information

```shell
System information: Linux #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
Python version: 3.10.6
MLflow version: 2.5.0
MLflow module location: /XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: http://localhost:5000
Registry URI: http://localhost:5000
MLflow environment variables: 
  MLFLOW_S3_ENDPOINT_URL: http://localhost:9020
MLflow dependencies: 
  Flask: 2.2.2
  Jinja2: 3.1.2
  alembic: 1.8.1
  click: 8.1.3
  cloudpickle: 2.2.0
  databricks-cli: 0.17.3
  docker: 6.0.0
  entrypoints: 0.4
  gitpython: 3.1.29
  gunicorn: 20.1.0
  importlib-metadata: 5.0.0
  markdown: 3.4.3
  matplotlib: 3.7.2
  numpy: 1.23.4
  packaging: 21.3
  pandas: 1.5.1
  protobuf: 4.21.8
  pyarrow: 12.0.1
  pytz: 2022.5
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 1.3.0
  scipy: 1.9.3
  sqlalchemy: 1.4.42
  sqlparse: 0.4.3
```

### Code to reproduce issue

```
import os

from random import random, randint
from mlflow import  log_param

import mlflow as ml

ml.set_tracking_uri("http://localhost:5000")
ml.set_experiment("my-experiment")

if __name__ == "__main__":
    log_param("param1", randint(0, 100))

```

### Stack trace

```
Traceback (most recent call last):
  File "XXXXXXXXXXXX/src/jobs/test.py", line 19, in <module>
    log_param("param1", randint(0, 100))
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 600, in log_param
    run_id = _get_or_start_run().info.run_id
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1768, in _get_or_start_run
    return start_run()
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 366, in start_run
    active_run_obj = client.create_run(
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 326, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 133, in create_run
    return self.store.create_run(
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 203, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "XXXXXXXXXXXX/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 135, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg.errors.UndefinedFunction) operator does not exist: integer = character varying
LINE 3: WHERE experiments.experiment_id = $1::VARCHAR AND experiment...
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT experiments.experiment_id AS experiments_experiment_id, experiments.name AS experiments_name, experiments.artifact_location AS experiments_artifact_location, experiments.lifecycle_stage AS experiments_lifecycle_stage, experiments.creation_time AS experiments_creation_time, experiments.last_update_time AS experiments_last_update_time 
FROM experiments 
WHERE experiments.experiment_id = %(experiment_id_1)s::VARCHAR AND experiments.lifecycle_stage IN (%(lifecycle_stage_1_1)s::VARCHAR, %(lifecycle_stage_1_2)s::VARCHAR)]
[parameters: {'experiment_id_1': '1', 'lifecycle_stage_1_1': 'active', 'lifecycle_stage_1_2': 'deleted'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@raphaelauv Thanks for reporting issue. Can you create a docke compose file that can reproduce this issue?

**Comment by raphaelauv** [comment]
Hello :wave: 

```Dockerfile
FROM python:3.11-slim
ENV PIP_NO_CACHE_DIR=TRUE
RUN python3 -m pip install mlflow==2.5.0 psycopg[binary,pool]==3.1.9
```

```yaml
version: '3.8'

services:
  mlflow-db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  mlflow-server:
    image: mymlflow:0.1
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql+psycopg://mlflow:password@mlflow-db:5432/mlflowdb
```

**Comment by harupy** [comment]
I was able to repro the issue locally. Filed https://github.com/mlflow/mlflow/pull/9156 to see if we can repro in CI.

**Comment by harupy** [comment]
The error hint implies there is a type mismatch (e.g. compare a string and an integer).

**Comment by harupy** [comment]
Confirmed the following change worked:

```
diff --git a/mlflow/store/tracking/sqlalchemy_store.py b/mlflow/store/tracking/sqlalchemy_store.py
index bdf24b94c..a96601b55 100644
--- a/mlflow/store/tracking/sqlalchemy_store.py
+++ b/mlflow/store/tracking/sqlalchemy_store.py
@@ -341,7 +341,7 @@ class SqlAlchemyStore(AbstractStore):
             session.query(SqlExperiment)
             .options(*query_options)
             .filter(
-                SqlExperiment.experiment_id == experiment_id,
+                SqlExperiment.experiment_id == int(experiment_id),
                 SqlExperiment.lifecycle_stage.in_(stages),
             )
             .one_or_none()
```

**Comment by raphaelauv** [comment]
I just realized that mlflow==2.5.0 is using sqlalchemy==1.4.42 and not the v2 of sqlalchemy

only the v2 of sqlalchemy is officialy compatible wth `psycopg3`

**Comment by harupy** [comment]
> sqlalchemy==1.4.42

This is the version installed in the client, or server?

**Comment by raphaelauv** [comment]
sorry I was checking the version on the venv of the client 

the server is using `SQLAlchemy==2.0.19` :+1:

**Comment by gersonvneto** [comment]
Having the same issue here. Did anyone manage to fix it?

**Comment by gersonvneto** [comment]
Solved by passing the `set_tracking_uri` before `set_experiment`

**Comment by jmahlik** [comment]
I think the casts in https://github.com/mlflow/mlflow/pull/9156 may still be needed. It makes sense since they are int columns. It's just by happenstance they work from autocasting in most of the database drivers.

**Comment by harupy** [comment]
Closing as resolved — the codebase now consistently applies `int()` casts when passing `experiment_id` to SQLAlchemy queries, which prevents the psycopg3 type mismatch. Verified by running tests with `postgresql+psycopg` (psycopg3) on current `master` — all pass.
