### ISSUE TITLE
[BUG] AssertionError when enabling autolog for sklearn

### ISSUE THREAD

**Issue by Nusret-Ozates** [mlflow/mlflow#9173]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.5.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: Python 3.9/10/11
- **yarn version, if running the dev UI**:

### Describe the problem

If I use `mlflow.sklearn.log_model()` and then run `mlflow.sklearn.autolog()` command, I get the AssertionError

### Code to reproduce issue

```python
import os
import requests
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import pandas as pd
import mlflow


# Create necessary folders if not exists
if not os.path.exists('data'):
    os.makedirs('data')

if not os.path.exists('models'):
    os.makedirs('models')

url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-01.parquet'
file_content = requests.get(url, allow_redirects=True).content
with open('./data/green_tripdata_2021-01.parquet', 'wb') as f:
    f.write(file_content)

url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-02.parquet'
file_content = requests.get(url, allow_redirects=True).content
with open('./data/green_tripdata_2021-02.parquet', 'wb') as f:
    f.write(file_content)
    
    
def read_dataframe(filename):
    df = pd.read_parquet(filename)

    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)

    df['duration'] = df.lpep_dropoff_datetime - df.lpep_pickup_datetime
    df.duration = df.duration.apply(lambda td: td.total_seconds() / 60)

    df = df[(df.duration >= 1) & (df.duration <= 60)]

    categorical = ['PULocationID', 'DOLocationID']
    df[categorical] = df[categorical].astype(str)
    
    return df    

df_train = read_dataframe('./data/green_tripdata_2021-01.parquet')
df_val = read_dataframe('./data/green_tripdata_2021-02.parquet')

df_train['PU_DO'] = df_train['PULocationID'] + '_' + df_train['DOLocationID']
df_val['PU_DO'] = df_val['PULocationID'] + '_' + df_val['DOLocationID']

categorical = ['PU_DO'] #'PULocationID', 'DOLocationID']
numerical = ['trip_distance']

dv = DictVectorizer()

train_dicts = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

target = 'duration'
y_train = df_train[target].values
y_val = df_val[target].values

from mlflow.data.numpy_dataset import from_numpy
from mlflow.models import infer_signature
with mlflow.start_run():

    mlflow.set_tag("developer", "Nusret")

    train_dataset = from_numpy(X_train.toarray(),'data/green_tripdata_2021-01.parquet',name='green_tripdata_2021-01')
    mlflow.log_input(train_dataset, "train")

    test_dataset = from_numpy(X_val.toarray(),'data/green_tripdata_2021-02.parquet',name='green_tripdata_2021-02')
    mlflow.log_input(test_dataset, "test")

    alpha = 0.006

    model = Ridge(alpha)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)
    rmse = mean_squared_error(y_val, y_pred, squared=False)
    signature = infer_signature(X_val, y_pred)

    mlflow.log_param("alpha", alpha)
    mlflow.log_param('model', model.__class__.__name__)
    mlflow.log_metric("rmse", rmse)
    # Comment out this part and you won't get an error
    mlflow.sklearn.log_model(model, "model",signature=signature)


mlflow.sklearn.autolog()
```

### Stack trace

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[20], line 4
      1 from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
      2 from sklearn.svm import LinearSVR
----> 4 mlflow.sklearn.autolog()
      6 for model_class in (GradientBoostingRegressor,LinearSVR, RandomForestRegressor, ExtraTreesRegressor ):
      8     with mlflow.start_run():

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/utils/autologging_utils/__init__.py:424, in autologging_integration.<locals>.wrapper.<locals>.autolog(*args, **kwargs)
    405 with set_mlflow_events_and_warnings_behavior_globally(
    406     # MLflow warnings emitted during autologging setup / enablement are likely
    407     # actionable and relevant to the user, so they should be emitted as normal
   (...)
    420     disable_warnings=is_silent_mode,
    421 ):
    422     _check_and_log_warning_for_unsupported_package_versions(name)
--> 424     return _autolog(*args, **kwargs)

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py:1210, in autolog(log_input_examples, log_model_signatures, log_models, log_datasets, disable, exclusive, disable_for_unsupported_versions, silent, max_tuning_runs, log_post_training_metrics, serialization_format, registered_model_name, pos_label)
    927 @autologging_integration(FLAVOR_NAME)
    928 def autolog(
    929     log_input_examples=False,
   (...)
    941     pos_label=None,
    942 ):  # pylint: disable=unused-argument
    943     """
    944     Enables (or disables) and configures autologging for scikit-learn estimators.
    945 
   (...)
   1208                       be logged. If used for regression model, the parameter will be ignored.
   1209     """
-> 1210     _autolog(
   1211         flavor_name=FLAVOR_NAME,
   1212         log_input_examples=log_input_examples,
   1213         log_model_signatures=log_model_signatures,
   1214         log_models=log_models,
   1215         log_datasets=log_datasets,
   1216         disable=disable,
   1217         exclusive=exclusive,
   1218         disable_for_unsupported_versions=disable_for_unsupported_versions,
   1219         silent=silent,
   1220         max_tuning_runs=max_tuning_runs,
   1221         log_post_training_metrics=log_post_training_metrics,
   1222         serialization_format=serialization_format,
   1223         pos_label=pos_label,
   1224     )

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py:1773, in _autolog(flavor_name, log_input_examples, log_model_signatures, log_models, log_datasets, disable, exclusive, disable_for_unsupported_versions, silent, max_tuning_runs, log_post_training_metrics, serialization_format, pos_label)
   1771     allow_children_patch = True
   1772 else:
-> 1773     estimators_to_patch = _gen_estimators_to_patch()
   1774     patched_fit_impl = fit_mlflow
   1775     allow_children_patch = False

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py:97, in _gen_estimators_to_patch()
     91 def _gen_estimators_to_patch():
     92     from mlflow.sklearn.utils import (
     93         _all_estimators,
     94         _get_meta_estimators_for_autologging,
     95     )
---> 97     _, estimators_to_patch = zip(*_all_estimators())
     98     # Ensure that relevant meta estimators (e.g. GridSearchCV, Pipeline) are selected
     99     # for patching if they are not already included in the output of `all_estimators()`
    100     estimators_to_patch = set(estimators_to_patch).union(
    101         set(_get_meta_estimators_for_autologging())
    102     )

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/utils.py:856, in _all_estimators()
    853 try:
    854     from sklearn.utils import all_estimators
--> 856     return all_estimators()
    857 except ImportError:
    858     return _backported_all_estimators()

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/utils/discovery.py:63, in all_estimators(type_filter)
     60 # Ignore deprecation warnings triggered at import time and from walking
     61 # packages
     62 with ignore_warnings(category=FutureWarning):
---> 63     for _, module_name, _ in pkgutil.walk_packages(path=[root], prefix="sklearn."):
     64         module_parts = module_name.split(".")
     65         if (
     66             any(part in _MODULE_TO_IGNORE for part in module_parts)
     67             or "._" in module_name
     68         ):

File ~/miniconda3/envs/mlflow_training/lib/python3.11/pkgutil.py:92, in walk_packages(path, prefix, onerror)
     90 if info.ispkg:
     91     try:
---> 92         __import__(info.name)
     93     except ImportError:
     94         if onerror is not None:

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/__init__.py:15
     13 from .._min_dependencies import CYTHON_MIN_VERSION
     14 from ..externals._packaging.version import parse
---> 15 from .openmp_helpers import check_openmp_support
     16 from .pre_build_helpers import basic_check_build
     18 DEFAULT_ROOT = "sklearn"

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/openmp_helpers.py:12
      9 import textwrap
     10 import warnings
---> 12 from .pre_build_helpers import compile_test_program
     15 def get_openmp_flag():
     16     if sys.platform == "win32":

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/pre_build_helpers.py:10
      7 import tempfile
      8 import textwrap
---> 10 from setuptools.command.build_ext import customize_compiler, new_compiler
     13 def compile_test_program(code, extra_preargs=None, extra_postargs=None):
     14     """Check that some C code can be compiled and run"""

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/setuptools/__init__.py:7
      4 import os
      5 import re
----> 7 import _distutils_hack.override  # noqa: F401
      9 import distutils.core
     10 from distutils.errors import DistutilsOptionError

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/override.py:1
----> 1 __import__('_distutils_hack').do_override()

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py:77, in do_override()
     75 if enabled():
     76     warn_distutils_present()
---> 77     ensure_local_distutils()

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py:64, in ensure_local_distutils()
     62 # check that submodules load as expected
     63 core = importlib.import_module('distutils.core')
---> 64 assert '_distutils' in core.__file__, core.__file__
     65 assert 'setuptools._distutils.log' not in sys.modules

AssertionError: /home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/distutils/core.py
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @Nusret-Ozates Could you try a simple example like below to see if the problem still exists:
```
model = sklearn.cluster.KMeans()
iris = sklearn.datasets.load_iris()
X = iris.data[:, :2]
y = iris.target

with mlflow.start_run():
    model.fit(X, y)
    mlflow.sklearn.log_model(model, "model")

mlflow.sklearn.autolog()
```

BTW which sklearn version are you using?

**Comment by Nusret-Ozates** [comment]
That code gives me sklearn doesn't have a module `cluster` but I basically changed the code a little bit and got the same results. My sklearn version is 1.3.0 but I also tried with 1.2 too.
```
import mlflow
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris

model = KMeans()
iris = load_iris()
X = iris.data[:, :2]
y = iris.target

with mlflow.start_run():
    model.fit(X, y)
    mlflow.sklearn.log_model(model, "model")

mlflow.sklearn.autolog()
```

```
2023/08/01 09:35:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils."
2023/08/01 09:35:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
Traceback (most recent call last):
  File "/mnt/c/Users/mnusr/PycharmProjects/langchain_retrieval_qa_bot/deneme.py", line 15, in <module>
    mlflow.sklearn.autolog()
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/utils/autologging_utils/__init__.py", line 424, in autolog
    return _autolog(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py", line 1210, in autolog
    _autolog(
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py", line 1773, in _autolog
    estimators_to_patch = _gen_estimators_to_patch()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/__init__.py", line 97, in _gen_estimators_to_patch
    _, estimators_to_patch = zip(*_all_estimators())
                                  ^^^^^^^^^^^^^^^^^
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/utils.py", line 856, in _all_estimators
    return all_estimators()
           ^^^^^^^^^^^^^^^^
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/utils/discovery.py", line 63, in all_estimators
    for _, module_name, _ in pkgutil.walk_packages(path=[root], prefix="sklearn."):
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/pkgutil.py", line 92, in walk_packages
    __import__(info.name)
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/__init__.py", line 15, in <module>
    from .openmp_helpers import check_openmp_support
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/openmp_helpers.py", line 12, in <module>
    from .pre_build_helpers import compile_test_program
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/_build_utils/pre_build_helpers.py", line 10, in <module>
    from setuptools.command.build_ext import customize_compiler, new_compiler
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/setuptools/__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: /home/nusret/miniconda3/envs/mlflow_training/lib/python3.11/distutils/core.py
```

**Comment by Nusret-Ozates** [comment]
Yeap, that solves the problem

**Comment by dbczumar** [comment]
Hi @Nusret-Ozates , this appears to be a scikit-learn issue.

```
File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/mlflow/sklearn/utils.py:856, in _all_estimators()
    853 try:
    854     from sklearn.utils import all_estimators
--> 856     return all_estimators()
    857 except ImportError:
    858     return _backported_all_estimators()

File ~/miniconda3/envs/mlflow_training/lib/python3.11/site-packages/sklearn/utils/discovery.py:63, in all_estimators(type_filter)
     60 # Ignore deprecation warnings triggered at import time and from walking
     61 # packages
     62 with ignore_warnings(category=FutureWarning):
---> 63     for _, module_name, _ in pkgutil.walk_packages(path=[root], prefix="sklearn."):
     64         module_parts = module_name.split(".")
     65         if (
     66             any(part in _MODULE_TO_IGNORE for part in module_parts)
     67             o
...
```

We recommend filing this issue against the scikit-learn repository in the meantime. Thank you for using MLflow!
