### ISSUE TITLE
[BUG] Quickstart errors out while trying to install python 3.8.17 virtualenv

### ISSUE THREAD

**Issue by chenmoneygithub** [mlflow/mlflow#9174]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.5.0

### System information

- OS: ubuntu 20.04
- python env: conda env (python 3.8.17)

### Describe the problem

I was running the [quickstart guide](https://mlflow.org/docs/latest/quickstart_mlops.html), but it errors out when running the command:
```
mlflow run -e hyperopt . --env-manager="local"
```

Same error if removing `--env-manager="local"`. Please see the stacktrace below:
```
2023/07/29 15:28:35 INFO mlflow.utils.virtualenv: Installing python 3.8.17 if it does not exist
Downloading Python-3.8.17.tar.xz...
-> https://www.python.org/ftp/python/3.8.17/Python-3.8.17.tar.xz
Installing Python-3.8.17...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chen/.pyenv/versions/3.8.17/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chen/.pyenv/versions/3.8.17/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 20.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230729152835.25190
Results logged to /tmp/python-build.20230729152835.25190.log

Last 10 log lines:
	LD_LIBRARY_PATH=/tmp/python-build.20230729152835.25190/Python-3.8.17 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmpq0jlfw0m
Processing /tmp/tmpq0jlfw0m/setuptools-56.0.0-py3-none-any.whl
Processing /tmp/tmpq0jlfw0m/pip-23.0.1-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.8 are installed in '/home/chen/.pyenv/versions/3.8.17/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.0.1 setuptools-56.0.0
Traceback (most recent call last):
  File "/home/chen/miniconda3/envs/mlflow/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/cli.py", line 205, in run
    projects.run(
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 337, in run
    submitted_run_obj = _run(
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 105, in _run
    submitted_run = backend.run(
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/backend/local.py", line 163, in run
    python_bin_path = _install_python(python_env.python, pyenv_root=pyenv_root)
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/virtualenv.py", line 133, in _install_python
    _exec_cmd(
  File "/home/chen/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/process.py", line 117, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['pyenv', 'install', '--skip-existing', '3.8.17']
```

Checking the log it failed while installing the python virtualenv, however I do have OpenSSL and bz2 installed as `import bz2` works and `$openssl version` prints:
```
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
```
I also tried the code with python virtualenv instead of conda env, and it failed with the same issue. 

### Code to reproduce issue

[N/A](https://mlflow.org/docs/latest/quickstart_mlops.html)

### Stack trace

N/A

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @chenmoneygithub Your error looks irrelevant to mlflow, it echoes error when building python. With a quick google search, maybe this helps https://stackoverflow.com/questions/67807596/pyenv-install-3-x-build-failed-ubuntu-20-04-using-python-build-20180424?

**Comment by harupy** [comment]
I don't think this is an MLflow issue. Installing `libssl-dev` and `libbz2-dev` should fix the issue:

- https://stackoverflow.com/a/12806325
- https://stackoverflow.com/a/37828891

**Comment by chenmoneygithub** [comment]
Reopen this for tracking, I have done the installation above and did not work.

Also I think we may want to treat this as an MLFlow-related issue - it's not common to require developers to set up another virtual env at runtime, but if we do, we need to make sure the required libs are installed or at least provide a clear error message. The least we shall do is to fix the quickstart guide. Users could get quickly frustrated if the quickstart guide fails.

**Comment by harupy** [comment]
@chenmoneygithub I agree. The hyperparam example is too complex as a quick starter.

**Comment by nkaretnikov** [comment]
I think this might be fixed by https://github.com/mlflow/mlflow/pull/9462. cc @harupy

**Comment by VladOnMyOwn** [comment]
Fixed by:
`sudo apt-get install zlib1g-dev libssl-dev libbz2-dev libncursesw5-dev libffi-dev libreadline-dev libsqlite3-dev tk-dev liblzma-dev`
