### ISSUE TITLE
Mlflow is not working with Azure User Manage Identity on AKS cluster

### ISSUE THREAD

**Issue by amitganvir23** [mlflow/mlflow#9257]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

Mlflow version 2.1.1
Python  version: 3.10.6
azure-storage-blob version:  12.17.0
Docker Image: ghcr.io/mlflow/mlflow:v2.1.1

### System information

Docker Image: ghcr.io/mlflow/mlflow:v2.1.1
Azure Kubernetes Servcie (AKS) cluster with v1.25.6 k8s version

### Describe the problem

We are trying to store mlflow artifacts on Azure Blob containers using User Manage Identity authentication but its not able to store data and this what we needed.

If we use "AZURE_STORAGE_ACCESS_KEY" of Azure storage account then it works and able to store artifacts on blob containers. But we need to store artifacts using Azure User Mange Identity instead of usering "AZURE_STORAGE_ACCESS_KEY".

```
mlflow server \
--host 0.0.0.0 \
-p 5100 \
--backend-store-uri mysql+pymysql://root:1234@172.16.7.35:3306/test \
--default-artifact-root wasbs://mlflowaganvir@amit4.blob.core.windows.net \
--serve-artifacts
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Did you install `azure-identity` package ?
Could you provide error stack ?

**Comment by BenWilson2** [comment]
@akshaya-a do you have any insight into what might be going on here? Thanks!

**Comment by santiagxf** [comment]
Hi @amitganvir23! Access to Blob Storage Accounts is always granted using access keys. IAM is used to perform control plane operations over the resource. On the contrary, Azure Data Lake Gen2 Storage Accounts have ACL that would match your scenario, however, they are not supported as artifact backends for MLflow server. Hope that helps!

**Comment by amitganvir23** [comment]
Hi @WeichenXu123 ,

I already installed `azure-idenity` packages but still it was giving error and here the error

```
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.793164022927685
  MAE: 0.6271946374319586
  R2: 0.10862644997792636


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5100): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/83176ee5ebb3483a92e5e5893f28ee17/artifacts/model/requirements.txt (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 167, in http_request
    return _get_http_response_with_retries(
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 98, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='127.0.0.1', port=5100): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/83176ee5ebb3483a92e5e5893f28ee17/artifacts/model/requirements.txt (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/halo/test.py", line 82, in <module>
    mlflow.sklearn.log_model(lr, "model", registered_model_name="ElasticnetWineModel")
  File "/usr/local/lib/python3.10/site-packages/mlflow/sklearn/__init__.py", line 417, in log_model
    return Model.log(
  File "/usr/local/lib/python3.10/site-packages/mlflow/models/model.py", line 487, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 810, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1048, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 40, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 185, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://127.0.0.1:5100/api/2.0/mlflow-artifacts/artifacts/0/83176ee5ebb3483a92e5e5893f28ee17/artifacts/model/requirements.txt failed with exception HTTPConnectionPool(host='127.0.0.1', port=5100): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/0/83176ee5ebb3483a92e5e5893f28ee17/artifacts/model/requirements.txt (Caused by ResponseError('too many 500 error responses'))
```

Hi @santiagxf , 
We dont need to use Mlflow Azure Machine Learning, We deployed our own Mlflow server for each user and need to access Azure Storage Blob containers from Mlflow `--default-artifact-root wasbs://mlflowaganvir@amit4.blob.core.windows.net` using Azure User Manage Identity
