### ISSUE TITLE
[BUG] fail to log the optimum model by mlflow 

### ISSUE THREAD

**Issue by jinholee-makinarocks** [mlflow/mlflow#9371]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.4.2
- Tracking server: not used
- python version : 3.9.16
- transformers[torch] version : 4.31.0
- optimum : 1.11.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **Python version**: 3.9.16
- **yarn version, if running the dev UI**:

### Describe the problem

Try to run following code:
```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
from optimum.pipelines import pipeline
import mlflow

tokenizer = AutoTokenizer.from_pretrained("optimum/gpt2")
model = ORTModelForCausalLM.from_pretrained("optimum/gpt2")
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

mlflow.transformers.log_model(transformers_model=generator, artifact_path="my_pipeline")
```
You can see error log as:
```sh
<stdin>:1: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.29.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/models/model.py:562: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.29.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
  flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/utils/docstring_utils.py", line 235, in version_func
    return func(*args, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 728, in log_model
    return Model.log(
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/models/model.py", line 562, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/utils/docstring_utils.py", line 235, in version_func
    return func(*args, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 390, in save_model
    _validate_transformers_model_dict(transformers_model)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 176, in _validate_transformers_model_dict
    raise MlflowException(
mlflow.exceptions.MlflowException: The submitted model type ORTModelForCausalLM does not inherit from a transformers pre-trained model. It is missing the attribute 'name_or_path'. Please verify that the model is a supported transformers model.
```

Since it's a transformers model, I think it should be logged normally through the transformers flavor of mlflow.
when I try to run with normally a pipeline of the transformer, it works well.
```python
from transformers import pipeline
qa_pipe = pipeline("question-answering", "csarron/mobilebert-uncased-squad-v2")
mlflow.transformers.log_model(transformers_model=qa_pipe, artifact_path="my_pipeline")
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
from optimum.pipelines import pipeline
import mlflow

tokenizer = AutoTokenizer.from_pretrained("optimum/gpt2")
model = ORTModelForCausalLM.from_pretrained("optimum/gpt2")
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

mlflow.transformers.log_model(transformers_model=generator, artifact_path="my_pipeline")
```

### Stack trace

```sh
<stdin>:1: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.29.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/models/model.py:562: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.29.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
  flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/utils/docstring_utils.py", line 235, in version_func
    return func(*args, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 728, in log_model
    return Model.log(
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/models/model.py", line 562, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/utils/docstring_utils.py", line 235, in version_func
    return func(*args, **kwargs)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 390, in save_model
    _validate_transformers_model_dict(transformers_model)
  File "/Users/mark/.pyenv/versions/3.9.15/lib/python3.9/site-packages/mlflow/transformers.py", line 176, in _validate_transformers_model_dict
    raise MlflowException(
mlflow.exceptions.MlflowException: The submitted model type ORTModelForCausalLM does not inherit from a transformers pre-trained model. It is missing the attribute 'name_or_path'. Please verify that the model is a supported transformers model.
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @jinholee-makinarocks thank you for using the transformers flavor in MLflow. Unfortunately, at this time, we don't provide support for the ``optimum`` package from huggingface. 
In order to support the different backend implementations of each model that the ``optimum`` package provides, significant changes will need to be made to the logging logic and the component loader to ensure that the appropriate deserialization module is selected. 
As this isn't a bug, I'm going to modify this to a Feature Request and we will monitor community feedback to determine if there is a large demand for enabling this functionality.

**Comment by jinholee-makinarocks** [comment]
@BenWilson2. Thank you !

**Comment by LazaUK** [comment]
Hello @BenWilson2, please advise if there was any progress with this Feature Request, as it still fails for the optimum package from HF. Thank you.
