### ISSUE TITLE
[BUG] Artifacts don't show up in UI

### ISSUE THREAD

**Issue by asysuev** [mlflow/mlflow#9404]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.5.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker default python-3.8
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

**Artifacts are not shown in UI: infinite spinner.**
Inspect/Network show all requests to artifacts server returns with 200OK.

Artifacts are presented in target location (S3 bucket) and are uploading there through Python SDK without any problems.
Deployment info:
 - MLFlow is deployed to ECS with docker image, derived from python-3.8
 - Tracking server and artifacts server are deployed to 2 different containers
 - Artifacts storage is s3 bucket
 - Backend DB: AWS RDS Postgres
Artifacts can be queried via API.

### Steps to reproduce the bug

- Deploy MLFlow to ECS in Docker images
- Deploy Tracking and Artifacts servers separately
- Use S3 bucket as destination for artifacts
- Run run 🤷 and upload some artifacts during run
- Artifacts are not shown in the UI.

### Is the console panel in DevTools showing errors relevant to the bug?

```
Reducers.ts:420 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sklearn_model_pipeline_45')
    at Reducers.ts:420:45
    at Array.forEach (<anonymous>)
    at artifactsByRunUuid (Reducers.ts:419:19)
    at redux.js:528:29
    at redux.js:528:29
    at v (redux.js:288:22)
    at index.js:82:26
    at index.js:11:16
    at dispatch (redux.js:659:28)
    at index.js:171:11
```

**Comment by BenWilson2** [comment]
Are there any other details of a stack trace in the devtools console?

**Comment by asysuev** [comment]
If I expand stack trace
```Reducers.ts:420 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sklearn_model_pipeline_45')
    at Reducers.ts:420:45
    at Array.forEach (<anonymous>)
    at artifactsByRunUuid (Reducers.ts:419:19)
    at redux.js:528:29
    at redux.js:528:29
    at v (redux.js:288:22)
    at index.js:82:26
    at index.js:11:16
    at dispatch (redux.js:659:28)
    at index.js:171:11
(anonymous) @ Reducers.ts:420
artifactsByRunUuid @ Reducers.ts:419
(anonymous) @ redux.js:528
(anonymous) @ redux.js:528
v @ redux.js:288
(anonymous) @ index.js:82
(anonymous) @ index.js:11
dispatch @ redux.js:659
(anonymous) @ index.js:171
await in (anonymous) (async)
componentDidMount @ ArtifactPage.tsx:114
vs @ react-dom.production.min.js:219
Pl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Il @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:244
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
o @ Subscription.js:90
v @ redux.js:296
(anonymous) @ index.js:82
(anonymous) @ index.js:11
dispatch @ redux.js:659
(anonymous) @ index.js:171
Promise.then (async)
(anonymous) @ index.js:191
(anonymous) @ index.js:11
n.<computed> @ bindActionCreators.js:9
componentDidMount @ RunPage.tsx:45
vs @ react-dom.production.min.js:219
Pl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Il @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
```
<img width="572" alt="image" src="https://github.com/mlflow/mlflow/assets/4270880/eb2412fe-f9e1-44c6-b2e3-383be459be02">

No other errors there

**Comment by harupy** [comment]
@asysuev Can you provide a minimum python code that can log a model that can reproduce this error?

**Comment by davidzajac1** [comment]
@asysuev @harupy I had the same issue when running MLFlow within a Fargate task. The issue has to do with the `artifact_url` value in the `meta.yaml` file. This value defaults to the full path of where you are running MLFlow. If you are running a MLFlow in a containerized application the full path to your artifact will probably be something like `file://src/your-ml-project/your-artifact`. Thus when you try to run MLFlow on your local machine this path doesn't work, it's expecting something more like `file:///Users/david/Desktop/your-ml-project/your-artifact`

I created sort of a hacky fix for this where the application opens the `meta.yaml` and changes all of the paths from `file://src/your-ml-project/your-artifact` to `./your-ml-project/your-artifact`

I can create a PR for this if y'all think it's worth it.
