### ISSUE TITLE
[BUG] `MlflowClient.log_artifact` fails when 'file'

### ISSUE THREAD

**Issue by mgbckr** [mlflow/mlflow#9457]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.6.0
- Tracking server: 2.6.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 22.04.3 LTS
- **Python version**: 3.11
- **yarn version, if running the dev UI**: N/A

### Describe the problem

The `tracking_uri` parameter of `MlflowClient` is not used when getting the artifact repository.

Concretely, in `MlflowArtifactsRepository.__init__`, `get_tracking_uri()` is called which retrieves the global `tracking_uri` and not the one used in `MlflowClient`.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

Run server like this
```bash

artifact_dir="."
password="pwd"

mlflow server \
    --backend-store-uri postgresql://mlflow:${password}@localhost:5432/mlflow \
    --artifacts-destination file://$artifact_dir \
    --default-artifact-root mlflow-artifacts:/ \
    --host localhost \
    --port 5000
```

And then try to log an artifact:

```python
from pathlib import Path
from mlflow import MlflowClient

client = MlflowClient("http://localhost:5000")
experiment_id = client.create_experiment("test")

experiment = client.get_experiment(experiment_id)
print("Artifact Location: {}".format(experiment.artifact_location))

r = client.create_run(experiment_id=experiment_id)
client.log_artifact(r.info.run_id, "./test.md")
```

### Stack trace

```bash
Traceback (most recent call last):
  File "/home/mgbckr/Documents/workspaces/mlflow/tests/store/artifact/test_mlflow_artifact_repo_client.py", line 16, in <module>
    test_mlflow_artifact_repo_client()
  File "/home/mgbckr/Documents/workspaces/mlflow/tests/store/artifact/test_mlflow_artifact_repo_client.py", line 12, in test_mlflow_artifact_repo_client
    client.log_artifact(r.info.run_id, "./test.md")
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/tracking/client.py", line 1092, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/tracking/_tracking_service/client.py", line 446, in log_artifact
    artifact_repo = self._get_artifact_repo(run_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/tracking/_tracking_service/client.py", line 431, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/store/artifact/artifact_repository_registry.py", line 113, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/store/artifact/artifact_repository_registry.py", line 71, in get_artifact_repository
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/store/artifact/mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/store/artifact/mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "/home/mgbckr/Documents/workspaces/mlflow/mlflow/store/artifact/mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
```

### Other info / logs

```
N/A
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @mgbckr is ``file://.`` a valid URI in all systems? 
Can you try to provide an absolute path in your server configuration and see if that functions correctly?

**Comment by mgbckr** [comment]
Hi @BenWilson2 , I actually do use an absolute path in my server config. I just changed that for the example above.

**Comment by mgbckr** [comment]
Correct. The reason is that `HttpArtifactRepository` (`mlflow/store/artifact/mlflow_artifacts_repo.py`, line 45) is initialized with `get_tracking_uri()` without passing the tracking URI from the client.

See:
https://github.com/mlflow/mlflow/pull/9458/files#r1311517023
