### ISSUE TITLE
[BUG] Error during upgrade 2.2.1 to 2.6.0

### ISSUE THREAD

**Issue by serkef** [mlflow/mlflow#9484]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 2.2.1 (while migrating to 2.6.0)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Debian 11 (bullseye)
- **Python version**: 3.8
- **yarn version, if running the dev UI**:-

### Describe the problem

When upgrading from `2.2.1` to `2.6.0` we got attached error.
This seems to be an issue with the database.
We use MySql 8 managed on GCP 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
Traceback (most recent call last):
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (3780, "Referencing column 'name' and referenced column 'name' in foreign key constraint 'registered_model_alias_name_fkey' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/mlflow/venv/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/mlflow/db.py", line 28, in upgrade
    mlflow.store.db.utils._upgrade_db(engine)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/mlflow/store/db/utils.py", line 217, in _upgrade_db
    command.upgrade(config, "heads")
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/command.py", line 382, in upgrade
    script.run_env()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/mlflow/venv/lib/python3.8/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 922, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/mlflow/store/db_migrations/versions/3500859a5d39_add_model_aliases_table.py", line 27, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/operations/ops.py", line 1303, in create_table
    return operations.invoke(op)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/operations/base.py", line 393, in invoke
    return fn(self, operation)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 128, in create_table
    operations.impl.create_table(table)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/srv/mlflow/venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/srv/mlflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/srv/mlflow/venv/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3780, "Referencing column 'name' and referenced column 'name' in foreign key constraint 'registered_model_alias_name_fkey' are incompatible.")
[SQL:
CREATE TABLE registered_model_aliases (
	alias VARCHAR(256) NOT NULL,
	version INTEGER NOT NULL,
	name VARCHAR(256) NOT NULL,
	CONSTRAINT registered_model_alias_pk PRIMARY KEY (name, alias),
	CONSTRAINT registered_model_alias_name_fkey FOREIGN KEY(name) REFERENCES registered_models (name) ON DELETE cascade ON UPDATE cascade
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serkef** [comment]
The mysql error is pretty clear, searching in StackOverflow, one possible reason for this could be encodings
https://stackoverflow.com/questions/69960902/error-3780-referencing-column-and-referenced-column-in-foreign-key-constraint-a

**Comment by serkef** [comment]
This is the schema of `registered_models`
<img width="1163" alt="image" src="https://github.com/mlflow/mlflow/assets/3225779/30407cb1-c3a2-4e2b-a402-bd7fa76575d7">

**Comment by serkef** [comment]
This is my charset variables 
<img width="446" alt="image" src="https://github.com/mlflow/mlflow/assets/3225779/dd6820ee-5139-481c-a044-4c64e0f41238">

**Comment by serkef** [comment]
ok, I had to disable foreign key checks, convert all tables to utf8mb4, readable checks and then alembic worked.
I'll leave the issue open if someone wants to make an improvement for other users, otherwise feel free to close it

**Comment by vsbaldeev** [comment]
Also seeing this error message while upgrading from 2.2.2 to 2.8.1.

**Comment by serkef** [comment]
here's what I ran:

```sql
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE
    experiment_tags
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    experiments
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    latest_metrics
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    metrics
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    model_version_tags
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    model_versions
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    params
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    registered_model_tags
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    registered_models
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    runs
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE
    tags
    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
```
