### ISSUE TITLE
Official Mlflow docker image does not support postgres

### ISSUE THREAD

**Issue by benelot** [mlflow/mlflow#9513]
Hello!

I am wondering why the default mlflow/mlflow docker image in the github container registry does not have the necessary requirements installed to run with a postgres server? It seems that many tutorials for the mlflow server on the official website use postgres://... uris for the db backend. As far as I can see, even your tests run some postgres, but the image does not support it (missing psycopg package). Am I wrong? Do I really have to roll my own Dockerfile instead of using one that comes from the official repo?

Thanks!

Benjamin

**Comment by serena-ruan** [comment]
Hi @benelot, thanks for raising the issue! For installing postgres related requirements it would increase image size, and we're not sure if all customers are using it. But we can keep this issue open to see if any more people vote on this :D

**Comment by shantanu-bbai** [comment]
Would it be possible to provide a flag that would download the psycopg2-binary or if postgres environment variables are detected? You'd likely need some sort of startup script.

@benelot I didn't need to roll my own Dockerfile... passing this as the command works:

`bash -c "python3 -m pip install pip --upgrade && \
      python3 -m pip install psycopg2-binary && \
      mlflow server ${WHATEVER_FLAGS_YOU_NEED}"`

**Comment by ziadloo** [comment]
The same goes for MySQL:

```
2023/09/17 17:54:47 ERROR mlflow.cli: Error initializing backend store
2023/09/17 17:54:47 ERROR mlflow.cli: No module named 'MySQLdb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 426, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 289, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 268, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 129, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 150, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 228, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 284, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 152, in import_dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'

```

Forgive my rudeness, but you can make the image even slimmer by removing the whole MLFlow from the package. These are features that you are removing from the Docker image. Please include them both in the image.

The solution provided by @shantanu-bbai does not work for me since I'm running this Docker image on a TrueNAS Scale (Kubernetes) and I could not find a way to introduce those extra commands to the app.

**Comment by ziadloo** [comment]
If anyone's interested in creating their own docker image with MySQL and Postgres client support, here's how its Dockerfile looks like:

```
FROM ghcr.io/mlflow/mlflow:v2.7.0

RUN apt-get -y update && \
    apt-get -y install python3-dev default-libmysqlclient-dev build-essential pkg-config && \
    pip install --upgrade pip && \
    pip install mysqlclient && \
    pip install psycopg2-binary

CMD ["bash"]
```

But I still strongly believe this should be part of the official image.

**Comment by CafeLungo** [comment]
Somewhat related to useful packages missing from the base image, the prometheus exporter is also missing:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/__init__.py", line 50, in <module>
    from mlflow.server.prometheus_exporter import activate_prometheus_exporter
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/prometheus_exporter.py", line 2, in <module>
    from prometheus_flask_exporter.multiprocess import GunicornInternalPrometheusMetrics
ModuleNotFoundError: No module named 'prometheus_flask_exporter'
```

And, to workaround, you can of course extend the above Dockerfile with:
`pip install prometheus-flask-exporter`

**Comment by bonovoxly** [comment]
If your application supports Postgres, it seems logical that you would include that support all the way to the official Docker image.

This is somewhat a bad idea, and people will begin to use public images that have the support built in, causing everyone to think they are using the official Docker image when they are most definitely not.

Case in point: The community Helm chart for Mlflow. https://github.com/community-charts/helm-charts/blob/main/charts/mlflow/values.yaml

In this case, they're not using the official Mlflow Docker image, they're https://github.com/burakince/mlflow .

This info came from this site: https://artifacthub.io/packages/helm/community-charts/mlflow , which has a link to this official GitHub repo. If you go to LINKS on the right, you'll see official links for Mlflow in the Homepage, Source. This was as of Nov 15th, 2023.

I realize they are "community charts". But I think there is a case to be made that you SHOULD add support to the official Docker image for the databases and services Mlflow uses.

One potential solution: have a `slim` version of the image that is smaller and doesn't have these modules (or the opposite, `full` that has everything). Then our deployments are aligned with you as the upstream.

Just some thoughts, hope it is considered. TY for the support.

**Comment by hongbo-miao** [comment]
(Just sharing this info for future reference as an alternative option. It looks like the [bitnami/mlflow](https://github.com/bitnami/charts/tree/main/bitnami/mlflow) image supports Postgres and S3 by default ☺️)

**Comment by wevonosky** [comment]
> If anyone's interested in creating their own docker image with MySQL and Postgres client support, here's how its Dockerfile looks like:
> 
> ```
> FROM ghcr.io/mlflow/mlflow:v2.7.0
> 
> RUN apt-get -y update && \
>     apt-get -y install python3-dev default-libmysqlclient-dev build-essential pkg-config && \
>     pip install --upgrade pip && \
>     pip install mysqlclient && \
>     pip install psycopg2-binary
> 
> CMD ["bash"]
> ```
> 
> But I still strongly believe this should be part of the official image.

I know this is old, but the psycopg2 maintainers suggest that depending on the `psycopg2-binary` package in production is discouraged. Even more reason IMO that there be an official MLFlow image that includes this python dep and its necessary system dependencies so the community doesn't need to solve this problem every time it comes up.

**Comment by iMerica** [comment]
Here is a working image until the MLFlow team provides one:

https://hub.docker.com/r/imichael/mlflow

**Comment by ThyrixYang** [comment]
Users turn to Docker precisely to avoid the hassle of installing all the prerequisites. I can't understand why the developers consider this feature unnecessary.

**Comment by ocharles** [comment]
Another surprised user who just wanted to try MLFlow to see if it's a good fit and was a bit disappointed to instantly have to jump through hoops

**Comment by SonGokussj4** [comment]
And another... We were using custom docker image. Wanted to go back to the original because after 3 years we forgot why we did it.... 
```
ModuleNotFoundError: No module named 'psycopg2'
```
Ok.... Here is the answer...

**Comment by austinhnelson** [comment]
Just ran into this issue of needing to install psycopg2 manually .... I don't understand why MLFlow supports PostgreSQL integration but the image doesn't actually come ready to actually _integrate_ it.

Is there any second thought on adding it into the main image? Or even having a separate package with it? Or something else?

**Comment by v4ler11** [comment]
Having the same issue here (who would've thought if hadn't been fixed). 
If you don't want to include extra dependencies into your image -> create a dedicated image with all dependencies needed to work with postgres out-of-the-box. Your decision not to include it and make user install it itself it at very least silly

**Comment by SbstnErhrdt** [comment]
I made it work with Postgres and S3 using the following`Dockerfile` and `docker compose` file

`Dockerfile`
```Dockerfile
FROM ghcr.io/mlflow/mlflow

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir boto3==1.37.11 psycopg2-binary==2.9.10
```

`docker-compose.yml`
```yml
services:
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mlflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mlflow-server
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow_db
        --default-artifact-root s3://equation-mlflow
    environment:
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_DEFAULT_REGION=xxx
    ports:
      - "8080:5000"
    depends_on:
      - postgres

```

**Comment by senarvi** [comment]
> I didn't need to roll my own Dockerfile... passing this as the command works (I'm starting up the mlflow server in a docker compose):
> 
> `bash -c "python3 -m pip install pip --upgrade && \ python3 -m pip install psycopg2-binary && \ mlflow server ${WHATEVER_FLAGS_YOU_NEED}"`

This is a great solution actually. No need to maintain a custom Docker image. The command line can be made even simpler:

```shell
bash -c 'pip install psycopg2-binary && mlflow server ...'
```

This will take just a second at the startup.

**Comment by CodePint** [comment]
> > I didn't need to roll my own Dockerfile... passing this as the command works (I'm starting up the mlflow server in a docker compose):
> > `bash -c "python3 -m pip install pip --upgrade && \ python3 -m pip install psycopg2-binary && \ mlflow server ${WHATEVER_FLAGS_YOU_NEED}"`
> 
> This is a great solution actually. No need to maintain a custom Docker image. The command line can be made even simpler:
> 
> bash -c 'pip install psycopg2-binary && mlflow server ...'
> 
> This will take just a second at the startup.

Except you just made your image inconsistant to run and dependant on being able to access than binary. Which is why we use Dockerfiles which produce images. 

Also +1 on being annoyed by this, I autogenerated some kubernetes manifests using chatgpt and was suprised to see some random image from flyte suggest...and now I'm here, reading this thread, typing this comment....instead of developing with MLFlow

**Comment by CodePint** [comment]
For anyone wanting a solution: `docker pull bitnami/mlflow:latest`
https://hub.docker.com/r/bitnami/mlflow

**Comment by benelot** [comment]
So bitnami understood that they could fix my issue at the same time as making the image safe/root-less. Great call, bitnami.

**Comment by xhensiladoda** [comment]
Having the same issue here as well:
```
2025/09/29 09:29:51 ERROR mlflow.cli: Error initializing backend store
2025/09/29 09:29:51 ERROR mlflow.cli: No module named 'psycopg2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 446, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 425, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 402, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 45, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 56, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 223, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 209, in __init__
    mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 243, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 314, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 617, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 696, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```

After the Bitnami announcement to put everything behind a paywall, I thought to use the official MLFlow image to not have maintain my own image, and now I have to build the image myself to support PostgreSQL.
I agree with the previous comments here, we shouldn't need to install ourselves what is needed to make MLFlow compatible with PostgreSQL when this database is ideally supported.

**Comment by CodePint** [comment]
And as of today I'm back here due to Bitnami discontinuing support for their images (thanks again broadcom). Why are we refusing to take action here?

**Comment by tvdhout** [comment]
Here to bump this issue. mlflow image should come with the packages it needs for regular operation...

**Comment by bra-fsn** [comment]
> And as of today I'm back here due to Bitnami discontinuing support for their images (thanks again broadcom). Why are we refusing to take action here?

Oh, crap: https://hub.docker.com/r/bitnami/mlflow
> This image is no longer available for free through Docker Hub. This image is available as a built OCI artifact in both Debian and Photon base OS formats through a commercial subscription of Bitnami Secure Images.

**Comment by PerilousApricot** [comment]
This is an issue for me as well, being able to deploy mlflow tracking in production without having to maintain my own GH actions to add the dep to the image would greatly simplify things for us

**Comment by Yc-Chen** [comment]
To account for different use cases while keeping the image size small, you can provide multiple tags, like mlflow:postgres-22.2. See examples like cypress: https://hub.docker.com/r/cypress/browsers/tags

**Comment by CodePint** [comment]
Do you need help implementing this, or should we look at migrating due to the lack of active maintenance?

This is an incredibly easy fix and is the second most commented open issue, yet there has been no movement to resolve this problem.

**Comment by CodePint** [comment]
Pull request has been sat open here for two years?
https://github.com/mlflow/mlflow/pull/11669

PLEASE, help us, help you.

What do you need?

**Comment by ocharles** [comment]
Thank you @serena-ruan - I don't think we ever expected this issue to be closed. You're a hero! 🙏

**Comment by remidebette** [comment]
Very nice fix @serena-ruan, When do we think a first `-full` package can be deployed?
I don't see any so far

https://github.com/mlflow/mlflow/pkgs/container/model-server
```bash
❯ docker pull ghcr.io/mlflow/mlflow-server:v3.8.1-full
Error response from daemon: failed to resolve reference "ghcr.io/mlflow/mlflow-server:v3.8.1-full": ghcr.io/mlflow/mlflow-server:v3.8.1-full: not found
```

**Comment by stephanerenou** [comment]
Thanks for doing it. You may want as well to use that version in the docker-compose file to help users starts with a fully operational env without the extra step of reinstalling each time we start the compose.
