### ISSUE TITLE
[BUG] Permission database initialize error when use MYSQL

### ISSUE THREAD

**Issue by JiayuZhai** [mlflow/mlflow#9642]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.7.0
- Tracking server: 2.7.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Monterey 12.3.1
- **Python version**: 3.9.6
- *Mysql version**: Ver 14.14 Distrib 5.7.31

### Describe the problem

Followed the [documentation](https://mlflow.org/docs/2.7.0/auth/index.html#permissions-database) about authentication setup, I changed the permission db url from default sqlite to mysql. Then initial setup failed.

This should caused by mysql CONSTRAINT_NAME cannot be duplicated within a database. While the table `experiment_permissions` and `registered_model_permissions` in permission db share the same name Foreign Key Constraint name `fk_user_id`.

My workaround is: 
1. Change the Foreign Key Constraint name of table `registered_model_permissions` to something like `fk_user_id_reg_model`.
2. Manually run create table sql in mysql. 
```sql
CREATE TABLE registered_model_permissions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(255) NOT NULL, 
	user_id INTEGER NOT NULL, 
	permission VARCHAR(255), 
	PRIMARY KEY (id), 
	CONSTRAINT fk_user_id_reg_model FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT unique_name_user UNIQUE (name, user_id)
)
```
3. Manually insert the version number. 
```sql
insert into alembic_version (`version_num`) values ('8606fa83a998');
```

Finally I suggest to add different names for the Foreign Keys in this two lines:
https://github.com/mlflow/mlflow/blob/1fce1d1e335780a9e6eb000a491f7dd23d5dd6dc/mlflow/server/auth/db/models.py#L42
https://github.com/mlflow/mlflow/blob/1fce1d1e335780a9e6eb000a491f7dd23d5dd6dc/mlflow/server/auth/db/models.py#L58

### Code to reproduce issue

```shell
python -m mlflow.server.auth db upgrade --url mysql://[user]:[pw]@[ip]:[port]/mlflow_permission
```

### Stack trace

```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 8606fa83a998, initial_migration
Traceback (most recent call last):
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1022, "Can't write; duplicate key in table 'registered_model_permissions'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/__main__.py", line 4, in <module>
    commands()
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/db/cli.py", line 17, in upgrade
    utils.migrate(engine, revision)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/db/utils.py", line 27, in migrate
    upgrade(alembic_cfg, revision)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/db/migrations/env.py", line 76, in <module>
    run_migrations_online()
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/db/migrations/env.py", line 70, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/mlflow/server/auth/db/migrations/versions/8606fa83a998_initial_migration.py", line 36, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/operations/ops.py", line 1250, in create_table
    return operations.invoke(op)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/ddl/impl.py", line 258, in create_table
    self._exec(schema.CreateTable(table))
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/jiayuzhai/opt/miniconda3/envs/base396/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1022, "Can't write; duplicate key in table 'registered_model_permissions'")
[SQL: 
CREATE TABLE registered_model_permissions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(255) NOT NULL, 
	user_id INTEGER NOT NULL, 
	permission VARCHAR(255), 
	PRIMARY KEY (id), 
	CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT unique_name_user UNIQUE (name, user_id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@JiayuZhai thanks for reporting this issue, I'll file a PR :)

**Comment by hadaney** [comment]
Any updates here? If you're working on a PR, please link it to this issue. @harupy

**Comment by vsbaldeev** [comment]
Got the same issue while trying to store auth db in mysql

**Comment by zeotuan** [comment]
This is a problem on MSSQL as well
