### ISSUE TITLE
[BUG] db_uri change causes migration error

### ISSUE THREAD

**Issue by mohitanchlia** [mlflow/mlflow#9711]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Tracking server: 2.6.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux ip-10-10-131-116 5.15.0-1021-aws #25~20.04.1-Ubuntu SMP Thu Sep 22 13:59:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- **Python version**:3.10

### Describe the problem

changed basic_auth.ini from  `database_uri = sqlite:///basic_auth.db`
to 
`database_uri = mysql+pymysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}`

Got the following error

```
Traceback (most recent call last):
--
File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 427, in server
initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 279, in initialize_backend_stores
_get_tracking_store(backend_store_uri, default_artifact_root)
File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 258, in _get_tracking_store
_tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 119, in _get_sqlalchemy_store
return SqlAlchemyStore(store_uri, artifact_uri)
File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 143, in __init__
mlflow.store.db.utils._initialize_tables(self.engine)
File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 94, in _initialize_tables
_upgrade_db(engine)
File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 217, in _upgrade_db
command.upgrade(config, "heads")
File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 399, in upgrade
script.run_env()
File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 578, in run_env
util.load_python_file(self.dir, "env.py")
File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
module = load_module_py(module_id, path)
File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
spec.loader.exec_module(module)  # type: ignore
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/local/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
run_migrations_online()
File "/usr/local/lib/python3.10/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
context.run_migrations()
File "<string>", line 8, in run_migrations
File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 937, in run_migrations
self.get_context().run_migrations(**kw)
File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
step.migration_fn(**kw)
File "/usr/local/lib/python3.10/site-packages/mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py", line 20, in upgrade
op.add_column("metrics", sa.Column("step", sa.BigInteger(), nullable=False, server_default="0"))
File "<string>", line 8, in add_column
File "<string>", line 3, in add_column
File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 2128, in add_column
return operations.invoke(op)
File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 393, in invoke
return fn(self, operation)
File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 168, in add_column
operations.impl.add_column(table_name, column, schema=schema, **kw)
File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 322, in add_column
self._exec(base.AddColumn(table_name, column, schema=schema))
File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
return conn.execute(  # type: ignore[call-overload]
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
return meth(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
return connection._execute_ddl(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
ret = self._execute_context(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
return self._exec_single_context(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
self.dialect.do_execute(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
cursor.execute(statement, parameters)
File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
result = self._query(query)
File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
conn.query(q)
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
result.read()
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
first_packet = self.connection._read_packet()
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
packet.raise_for_error()
File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'step'")
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Was this an empty database that you were trying to run this against?

**Comment by BenWilson2** [comment]
Hi @mohitanchlia can you give us an exact repro sequence of events of what you did when you encountered this? (state of systems, what versions, what commands you ran...)

**Comment by mohitanchlia** [comment]
@BenWilson2 
Following are the sequence of events:
- Create mlflow on ecs without any authentication
- Run experiments
- Enable Basic Auth using sqlite
- Add several users
- Change the db_uri to mysql as shows above
- ecs service fails to come up with the error as mentioned above

**Comment by BenWilson2** [comment]
You're attempting to run an auth migration to the MLflow tracking server?

**Comment by mohitanchlia** [comment]
@BenWilson2 No I am not running any migration commands. Simply changing the db_uri to point to mysql

**Comment by BenWilson2** [comment]
Does the same thing happen if you define a new database within the mysql instance? The migration script error that you're getting is raising an error based on a tracking server metrics table field that is already in existence. 
We're trying to figure out exactly the details on how to reproduce this.

**Comment by mohitanchlia** [comment]
@BenWilson2 That's interesting because all I changed was db_uri in basic_auth which shouldn't have anything to do with it. Unless the DB connection is not thread-safe (just a guess). When I changed the db_uri back to sqllite it worked again.

I'll try creating a new db and give it a shot

**Comment by mohitanchlia** [comment]
@BenWilson2 I created a new database mlflow_auth in the same DB instance. Pointed database_uri in basic_auth.ini and I still get exactly the same error. Not sure why it's showing an error on the metric table when it shouldn't matter at all. When I point database_uri back to sqllite then it works.

`database_uri = mysql+pymysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${AUTH_DATABASE}`

**Comment by mohitanchlia** [comment]
@harupy No specific command. I am not migrating the database. I am just using this basic auth as an option

```
$ cat basic_auth.ini
[mlflow]
default_permission = NO_PERMISSIONS
database_uri = mysql+pymysql://${USER}:${PASSWORD}@${HOST}:${PORT}/${AUTH_DATABASE}
admin_username = admin
admin_password = password
FROM --platform=linux/amd64 python:3.10.11

RUN pip install \
    mlflow==2.6.0 \
    pymysql==1.0.2 \
    boto3 && \
    mkdir /mlflow/

COPY ./basic_auth.ini /usr/local/lib/python3.10/site-packages/mlflow/server/auth/basic_auth.ini

EXPOSE 80

CMD mlflow server \
    --host 0.0.0.0 \
    --port 80 \
    --default-artifact-root ${BUCKET} \
    --backend-store-uri mysql+pymysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE} \
    --app-name basic-auth
```

**Comment by mohitanchlia** [comment]
Just checking to see what the next steps are

**Comment by harupy** [comment]
compose.yml

```yaml
services:
  mysql-tracking:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mlflowdb
      MYSQL_USER: mlflowuser
      MYSQL_PASSWORD: mlflowpassword
    command: mysqld --default-authentication-plugin=mysql_native_password

  mysql-auth:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mlflowdb
      MYSQL_USER: mlflowuser
      MYSQL_PASSWORD: mlflowpassword
    command: mysqld --default-authentication-plugin=mysql_native_password

  mlflow:
    image: mlflow
    build:
      context: .
    depends_on:
      - mysql-tracking
      - mysql-auth
    working_dir: /mlflow
    volumes:
      - ./auth.ini:/tmp/auth.ini
    environment:
      - MLFLOW_AUTH_CONFIG_PATH=/tmp/auth.ini
    command: bash -c "pip install --force-reinstall --no-deps . && mlflow server --host 0.0.0.0 --port 5000 --workers 1 --app-name basic-auth --backend-store-uri mysql://mlflowuser:mlflowpassword@mysql-tracking:3306/mlflowdb?charset=utf8mb4"
```

Dockerfile

```Dockerfile
FROM python:3.10

RUN pip install mlflow pymysql mysqlclient
```

auth.ini

```
[mlflow]
default_permission = NO_PERMISSIONS
database_uri = mysql://mlflowuser:mlflowpassword@mysql-auth:3306/mlflowdb?charset=utf8mb4
admin_username = admin
admin_password = password
```

**Comment by retzero** [comment]
+1 I see the same issue w/ `postgres` db. (mlflow 2.9.2)
