### ISSUE TITLE
[FR] Configurable Hashing Algorithm/Using MLFlow in FIPS environment

### ISSUE THREAD

**Issue by bwhartlove** [mlflow/mlflow#9905]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I would like to have some way to configure the hashing algorithm to be used in the backend. I am very new to MLFlow, but testing it out today I noticed I was running into FIPS errors due to the use of MD5 in the `file_store.py` file. Would it be possible to provide a configuration option that would allow users to switch to another algorithm to bypass these issues?

### Motivation

> #### What is the use case for this feature?
The use case would be leveraging MLFlow in a FIPS enabled environment.

> #### Why is this use case valuable to support for MLflow users in general?
This would allow more interested users who are constrained by FIPS to make use of the tool set.

> #### Why is this use case valuable to support for your project(s) or organization?
Our project is unable to disable FIPS at this time, and this limits our ability to use MLFlow in it's current state.

> #### Why is it currently difficult to achieve this use case?
There is no way, at least as far as I know, to get around this limitation without disabling FIPS outright.
 

### Details

The offending line (though there are many more references to md5 in the code):
`md5 = hashlib.md5(dataset_name.encode("utf-8"))`

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mdcrank** [comment]
Commenting for visibility and tracking.

**Comment by harupy** [comment]
@bwhartlove How can we reproduce the error? Can we use Docker to reproduce it?

**Comment by bwhartlove** [comment]
@harupy I installed MLFlow using pip inside a Python based container and spun it up as a pod in a K8S cluster. I can supply the Dockerfile and specific versions tomorrow if that would help.The CMD for the Dockerfile was just 'mlflow server'. The pod was running on a  RHEL 8.8 based cluster with FIPS enabled. When I tried to save the model using the Python SDK, I got warnings regarding FIPS in the container. I'll update this thread with more details in the morning regarding the specific error and environment.

**Comment by harupy** [comment]
> I can supply the Dockerfile and specific versions tomorrow if that would help.

Awesome, that'd be helpful.

**Comment by bwhartlove** [comment]
Alright, the Dockerfile is using a python39 base image, and we are installing mlflow version 2.7.1 using pip. The CMD for the Dockerfile is as follows:
`CMD ["mlflow", "server", "--host", "0.0.0.0"]`

Just as a quick note, I am running the above container as a pod and trying to communicate with it from another pod in the same cluster.

Here is the code I ran in my 'client' pod to trigger the error I saw:
`import mlflow
from mlflow.models import infer_signature

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

mlflow.set_tracking_uri('http://my-kubeflow-service')
mlflow.set_registry_uri('http://my-kubeflow-service')
mlflow.autolog()

db = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

# Create and train models.
rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
rf.fit(X_train, y_train)

# Use the model to make predictions on the test dataset.
predictions = rf.predict(X_test)`

Below is the Python error on the client side:
`2023/10/13 12:55:01 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The following failures occurred while performing one or more logging operations: [MlflowException('Failed to perform one or more operations on the run with ID a9ff66e5f1704b87a86ede9dbeec8217. Failed operations: [MlflowException("API request to http://my-kubeflow-service/api/2.0/mlflow/runs/log-inputs failed with exception HTTPConnectionPool(host=\'my-kubeflow-service\', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/log-inputs (Caused by ResponseError(\'too many 500 error responses\'))")]')]`

And the error in the mlflow server pod:
`mlflow 2023/10/13 12:55:01 ERROR mlflow.server: Exception on /api/2.0/mlflow/runs/log-inputs [POST]                                                                                                   
mlflow Traceback (most recent call last):                                                                                                                                                             
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app                                                                                                  
mlflow     response = self.full_dispatch_request()                                                                                                                                                    
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request                                                                                     
mlflow     rv = self.handle_user_exception(e)                                                                                                                                                         
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request                                                                                     
mlflow     rv = self.dispatch_request()                                                                                                                                                               
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request                                                                                          
mlflow     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                   
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 486, in wrapper                                                                                       
mlflow     return func(*args, **kwargs)                                                                                                                                                               
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 527, in wrapper                                                                                       
mlflow     return func(*args, **kwargs)                                                                                                                                                               
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 828, in _log_inputs                                                                                   
mlflow     _get_tracking_store().log_inputs(run_id, datasets=datasets)                                                                                                                                
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 1108, in log_inputs                                                                         
mlflow     dataset_id = FileStore._get_dataset_id(                                                                                                                                                    
mlflow   File "/home/mlflow/.local/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 1131, in _get_dataset_id                                                                    
mlflow     md5 = hashlib.md5(dataset_name.encode("utf-8"))                                                                                                                                            
mlflow ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS`

**Comment by harupy** [comment]
@bwhartlove can you share the Dockerfile?

**Comment by bwhartlove** [comment]
@harupy  Sure thing:
```
FROM docker.io/library/python:3.9

USER root
ENV NON_ROOT_USER=mlflow
ENV NON_ROOT_GID="1000" \
    NON_ROOT_UID="1000" \
    NON_ROOT_HOME_DIR=/home/${NON_ROOT_USER}

RUN groupadd -g $NON_ROOT_GID parser && useradd -m -s $NON_ROOT_HOME_DIR -u $NON_ROOT_UID $NON_ROOT_USER -g $NON_ROOT_GID

USER mlflow
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
ENV PATH="$PATH:/home/mlflow/.local/bin"
WORKDIR $NON_ROOT_HOME_DIR

CMD ["mlflow", "server", "--host", "0.0.0.0"]
```

**Comment by harupy** [comment]
How can we reproduce the error with this dockerfile?

**Comment by bwhartlove** [comment]
I would reproduce the following way:

- Build the container using the Dockerfile above
- Spin up a RHEL 8 machine with FIPS enabled
- Run the container on that FIPS machine
- From the same machine (or another machine RHEL machine with FIPS enabled), run the code I supplied above. I believe it's the 'autolog' feature in particular that trips the error

**Comment by bwhartlove** [comment]
Correct. Any basic RHEL 8 VM with FIPS enabled should suffice.

**Comment by harupy** [comment]
Got it. https://github.com/cupy/cupy/issues/5959 is the same issue.

**Comment by harupy** [comment]
Can we use `hashlib.sha256`?

**Comment by harupy** [comment]
we could add an environment variable to configure the hashing algorithm to use.

**Comment by bhartlovecode** [comment]
`hashlib.sha256` would work great. It would be awesome if that could be switched via a flag or environment variable.

**Comment by harupy** [comment]
Another option is a function like this:

```python
import functools
import hashlib


@functools.lru_cache(max_size=1)
def get_hashing_func():
    try:
        hashlib.md5()
        return hashlib.md5
    except Exception:
        return hashlib.sha256

```

**Comment by harupy** [comment]
or can we just add `usedforsecurity=False`?

**Comment by harupy** [comment]
- https://github.com/pytest-dev/pytest-randomly/issues/414
- https://github.com/pytest-dev/pytest-randomly/pull/415

**Comment by harupy** [comment]
@TomeHirata Are you interested in working on this?

**Comment by harupy** [comment]
@bhartlovecode I filed #9961.

**Comment by bhartlovecode** [comment]
> @bhartlovecode I filed #9961. The following command install mlflow from this PR if you want to test it:
> 
> ```
> pip install git+https://github.com/mlflow/mlflow.git@refs/pull/9961/merge
> ```

Roger that. I'll give it a try tomorrow. Thanks for the quick turnaround!

**Comment by harupy** [comment]
@bhartlovecode Does `hashlib.sha1` works fine?

**Comment by bwhartlove** [comment]
@harupy The `usedforsecurity` flag appears to get arround the issue. `hashlib.sha1` should work as well, though at some point FIPS is looking to move away from that (2025, I think), so the same flag may need to be supplied to sha1 if that is used in the future.

**Comment by shsma** [comment]
> @bhartlovecode I filed #9961. The following command install mlflow from this PR if you want to test it:
> 
> ```
> pip install git+https://github.com/mlflow/mlflow.git@refs/pull/9961/merge
> ```


@harupy Was this fix included in any new release?
